### ISSUE TITLE
Only 1 TPU core is utilized regardless of `num_processes` flag value

### ISSUE THREAD

**Issue by RahulBhalley** [huggingface/accelerate#1005]
### System Info

```Shell
Cannot select options with keys on Kaggle (hence, couldn't run `accelerate config`) so writing the settings here.

- `Accelerate` version: 0.15.0
- Platform: Linux-5.15.65+-x86_64-with-debian-buster-sid
- Python version: 3.7.10
- Numpy version: 1.19.5
- PyTorch version (GPU?): 1.11.0+cpu (False)
- `Accelerate` default config:
	- compute_environment: CLOUD Kaggle MACHINE
	- distributed_type: TPU
	- mixed_precision: yes
	- use_cpu: False
	- dynamo_backend: NO
	- num_processes: 8
	- machine_rank: 0
	- num_machines: 1
	- gpu_ids: None
	- main_process_ip: None
	- main_process_port: None
	- rdzv_backend: static
	- same_network: True
	- main_training_function: main
	- deepspeed_config: {}
	- fsdp_config: {}
	- megatron_lm_config: {}
	- downcast_bf16: yes
	- tpu_name: TPU v3-8
	- tpu_zone: IDK
	- command_file: None
	- commands: None
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

[Link to my Accelerate script](https://github.com/RahulBhalley/lightning-examples/blob/main/image-classification-accelerate.py). I'm not gonna write it down. 

You can use the following command to run the code:

```sh
accelerate launch \
--mixed_precision 'bf16' \
--num_processes 8 \
    ./image-classification-accelerate.py \
--accumulate_grad_batches 1 \
--max_epochs 10 \
--batch_size 64 \
--persistent_workers \
--workers 4 \
--network 'resnet50' \
--image_size 224 \
--optim_name 'adam'
```

The console output is as follows:
```
PyTorch version: 1.11.0+cpu
CPU cores: 4
Files already downloaded and verified
[Epoch: 0 | Loss: 0.0]:  55%|█████████▍       | 433/781 [01:01<00:46,  7.42it/s]
```

### Expected behavior

```Shell
The CIFAR10 train set size is 50000 and batch size I set is 64 so 50000 / 64 = 781 steps. This is correct if we are using only 1 TPU core but I'm trying to use 8 cores (see `--num_processes 8` flag). This should make the steps to be 781 / 8 = 97 but the steps are still 781. 

I tested the cores setting for PyTorch Lightning and it did show 97 steps but Accelerate doesn't. So, I consider this as a bug i.e. only 1 TPU core is utilized regardless of `num_processes` flag value.
```

**Comment by RahulBhalley** [comment]
Rewriting the expected behavior here.

The CIFAR10 train set size is 50000 and batch size I set is 64 so 50000 / 64 = 781 steps. This is correct if we are using only 1 TPU core but I'm trying to use 8 cores (see `--num_processes 8` flag). This should make the steps to be 781 / 8 = 97 but the steps are still 781. 

I tested the cores setting for PyTorch Lightning and it did show 97 steps but Accelerate doesn't. So, I consider this as a bug i.e. only 1 TPU core is utilized regardless of `num_processes` flag value.

**Comment by muellerzr** [comment]
@RahulBhalley since you created a config you should not pass anything to `accelerate launch` aside parameters for your file. Can you try running:

```bash
accelerate launch ./image-classification-accelerate.py \
--accumulate_grad_batches 1 \
--max_epochs 10 \
--batch_size 64 \
--persistent_workers \
--workers 4 \
--network 'resnet50' \
--image_size 224 \
--optim_name 'adam'
```

And see if this works? I believe you may also hit an issue because `mixed_precision` should be one of `bf16`, `fp16`, or `no` during `accelerate config`. But let's start there

**Comment by RahulBhalley** [comment]
Thanks for a quick response @muellerzr. 

It's actually not possible to select settings of `accelerate config` in Kaggle / Colab environment because keyboard keys don't work in cell output.

So, I used the following command to (try) run my code on TPU 8 cores with bf16 precision:

```
accelerate launch \
--mixed_precision 'bf16' \
--num_processes 8 \
    ./image-classification-accelerate.py \
--accumulate_grad_batches 1 \
--max_epochs 10 \
--batch_size 64 \
--persistent_workers \
--workers 4 \
--network 'resnet50' \
--image_size 224 \
--optim_name 'Adam'
```

But it only runs on 1 core as I mentioned before. [My Accelerate script](https://github.com/RahulBhalley/lightning-examples/blob/main/image-classification-accelerate.py).

**Comment by muellerzr** [comment]
@RahulBhalley since you're in colab, you should do the following then:

```
accelerate launch \
--tpu \
--num_processes 8 \
--mixed_precision 'bf16' \ 
./image-classification-accelerate.py \
 --accumulate_grad_batches 1 \
--max_epochs 10 \
--batch_size 64 \
--persistent_workers \
--workers 4 \
--network 'resnet50' \
--image_size 224 \
--optim_name 'Adam'
```
Let me know if that doesn't work still and I'll try looking at this myself later this week to see what could be going on :)

**Comment by RahulBhalley** [comment]
@muellerzr I get the following error if I use `--tpu` flag. 

```
Traceback (most recent call last):
  File "/opt/conda/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/opt/conda/lib/python3.7/site-packages/accelerate/commands/launch.py", line 1100, in launch_command
    tpu_launcher(args)
  File "/opt/conda/lib/python3.7/site-packages/accelerate/commands/launch.py", line 815, in tpu_launcher
    if not hasattr(mod, args.main_training_function):
TypeError: hasattr(): attribute name must be string
```

But if I remove it code runs on 1 core.

**Comment by RahulBhalley** [comment]
If there's any workaround this error (seems simple but I'm not familiar with Accelerate source code) then let me know. I'll fork and edit it to get it working for myself at least. 

Thanks. :)

**Comment by muellerzr** [comment]
Ah! Yes! There's one missing one there, apologies.
**BUT** that does mean we're doing the right thing!

Run:
```
accelerate launch \
--tpu \
--main_training_function "main" \
--num_processes 8 \
--mixed_precision 'bf16' \ 
./image-classification-accelerate.py \
 --accumulate_grad_batches 1 \
--max_epochs 10 \
--batch_size 64 \
--persistent_workers \
--workers 4 \
--network 'resnet50' \
--image_size 224 \
--optim_name 'Adam'
```

And change the tail end of your script to be:

```diff
- if __name__ == "__main__":
+ def main()
    accelerator = Accelerator()

    # Get opts
    opts = get_opts()
    
    # Begin training
    train(opts, accelerator)

    print("OMFN, training finished!")
```

You don't need `if __name__ == "__main__"` as `Accelerate` will do that based on the main function instead

**Comment by RahulBhalley** [comment]
HELL YEAH! That works!! Thank you so much!! 

But now I'm running out of memory. How can I fix this? Reduce num workers or do something else?

**Comment by muellerzr** [comment]
You'd want to reduce your batch size to start with

**Comment by RahulBhalley** [comment]
Okay! Thank you so much. This speed is gonna be crazy (if linear increase then 8x)! It's awesome!

**Comment by muellerzr** [comment]
Note that it won't quite be linear :) I recommend reading this doc which has some helpful gotchas: https://huggingface.co/docs/accelerate/concept_guides/performance

**Comment by RahulBhalley** [comment]
Just realized that after experimenting. But it's cool. Thanks for docs. :)

**Comment by RahulBhalley** [comment]
@muellerzr (sorry to ping you). It's suggested in documentation that the learning rate must be scaled based on number of processes. So, should it also be scaled when using accumulated gradient batches (I'm using my own accumulation code, not DeepSpeed)?

**Comment by muellerzr** [comment]
@RahulBhalley I'd say yes, most likely that is the route you want to take. Worst case run a quick experiment and let us know :)

**Comment by RahulBhalley** [comment]
Okay, thanks.
