### ISSUE TITLE
cannot import name 'LRScheduler' from 'torch.optim.lr_scheduler'

### ISSUE THREAD

**Issue by cccntu** [huggingface/accelerate#1019]
### System Info

```Shell
env: nvcr.io/nvidia/pytorch:22.12-py3
PyTorch Version 1.14.0a0+410ce96

accelerate-0.15.0
transformers==4.25.1
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

1. nvidia-docker run -ti --rm nvcr.io/nvidia/pytorch:22.12-py3 bash
2. pip install transformers accelerate
3. accelerate env

### Expected behavior

```Shell
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 5, in <module>
    from accelerate.commands.accelerate_cli import main
  File "/usr/local/lib/python3.8/dist-packages/accelerate/__init__.py", line 7, in <module>
    from .accelerator import Accelerator
  File "/usr/local/lib/python3.8/dist-packages/accelerate/accelerator.py", line 102, in <module>
    from torch.optim.lr_scheduler import LRScheduler as LRScheduler
ImportError: cannot import name 'LRScheduler' from 'torch.optim.lr_scheduler' (/usr/local/lib/python3.8/dist-packages/torch/optim/lr_scheduler.py)
```
```

**Comment by sgugger** [comment]
Yes, this is a known bug and will be fixed by #1017 
Thanks for the report!

**Comment by ashmalvayani** [comment]
updating transformer version from 4.39.1 to 4.39.3 worked for me.

**Comment by lorsonblair** [comment]
Has this been fixed? I'm still getting this error with Pytorch 2.3 cuda 12.1

**Comment by meirashaf** [comment]
> Has this been fixed? I'm still getting this error with Pytorch 2.3 cuda 12.1

upgrading to torch==2.4.0 fixed the problem for me

**Comment by elghayatiloubna** [comment]
this '!pip install transformers --upgrade' worked for me
