### ISSUE TITLE
SummaryWriter issues

### ISSUE THREAD

**Issue by Yaicky** [huggingface/accelerate#102]
Hello, 
It seems like that num_of_processes tb.records will be saved when I use SummaryWriter.
It's obvious but If I only need one summarized tb.record, are there any ways to do that?
Thanks.

btw, one importerror occurred on my pytorch==1.4.0, 'start_processes' is not found in torch.multiprocessing.
Which was added after 1.5.0 according to official doc. So I replaced *.py under xxxx/multiprocessing/ with the 1.8.0 ones.
works fine so far.

**Comment by sgugger** [comment]
Hi there! To only execute some code once, you just need to put it inside a
```
if accelerator.is_main_process:
   code_to_execute_once_only
```

For your second issue, Ì had not realized it was requiring v5, I thought that function was in v4 too. Will fix!

**Comment by Yaicky** [comment]
> Hi there! To only execute some code once, you just need to put it inside a
> 
> ```
> if accelerator.is_main_process:
>    code_to_execute_once_only
> ```
> 
> For your second issue, Ì had not realized it was requiring v5, I thought that function was in v4 too. Will fix!

Many thanks for your quick reply.
