### ISSUE TITLE
Accelerate Config not working Google Colab

### ISSUE THREAD

**Issue by sr5434** [huggingface/accelerate#1029]
### System Info

Google Colab running the latest version of accelerate v0.15.0

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

When I try to run `accelerate config`, a prompt pops up asking me whether I am using a local machine or AWS. It says to use arrow keys or numbers to select my answer, and the enter key to move on to the next prompt. However, none of the controls do anything. Please note that when I type into the cell the number 1 or 2, it does not do anything

### Expected behavior

When I click the enter key, it should move on to the next prompt. However, it appears that there is a conflict(Colab uses the enter key to skip to the next cell, accelerate uses enter to skip to the next prompt, etc.)

**Comment by muellerzr** [comment]
@sr5434 you won't be able to use the CLI tool in that way from the jupyter environment. You should either run config from the CLI interface in Colab, or create your own config file to use.

Note if you are using the `notebook_launcher` you don't need to run the config iirc.

**Comment by sr5434** [comment]
Thanks, but where do I put the config file and how do I reference it?

**Comment by muellerzr** [comment]
You put the config file anywhere, and reference it as part of `accelerate launch --config_file ...`. You can check out `accelerate launch -h` or check out the docs: https://huggingface.co/docs/accelerate/basic_tutorials/launch#custom-configurations

**Comment by sr5434** [comment]
Thanks!
