### ISSUE TITLE
transformers codegen 16B pretrained model

### ISSUE THREAD

**Issue by BoyuanJackChen** [huggingface/accelerate#1032]
I'm trying to load the the 16B codegen model from transformers and run inference task. I have 8 RTX 3090 GPUs on my lab machine. The 16B model requires 32GB of VRAM, but each 3090 has only 24GB, so I'm trying to load the model on multiple GPUs, with accelerate. Below is the code:
```
# import pytorch and model related libraries
from accelerate import Accelerator
accelerator = Accelerator()
model = AutoModelForCausalLM.from_pretrained("Salesforce/codegen-16B-mono")
model = accelerator.prepare(model)
...
generated_ids = model.generate( 
        input_ids,
        max_new_tokens=100,
        top_k = 20,
        do_sample = False,
        penalty_alpha = 0.3
    )
```
And I called the script with `accelerate launch infer_big.py`, under conda environment. 
The GPU memories were quickly filled up and I received error message as follows:
![image](https://user-images.githubusercontent.com/43197439/215808796-3786cb34-f026-47d1-9d82-1f59cce10b17.png)
I wonder how to distribute this 16B model.

**Comment by sgugger** [comment]
To load the model on several GPUs, the proper code is:
```
# import pytorch and model related libraries
model = AutoModelForCausalLM.from_pretrained("Salesforce/codegen-16B-mono", device_map="auto")

generated_ids = model.generate( 
        input_ids,
        max_new_tokens=100,
        top_k = 20,
        do_sample = False,
        penalty_alpha = 0.3
    )
```
Which uses Accelerate behind the scenes. No need to prepare your model, it needs to be loaded on the GPUs directly.

**Comment by BoyuanJackChen** [comment]
> , device_map="auto"

This solved it! Thank you!
