### ISSUE TITLE
Cannot find GPU on V100

### ISSUE THREAD

**Issue by ShaoTengLiu** [huggingface/accelerate#1048]
Hi,

I use Tesla V100. My environment is torch1.12.1-cu116. (torch.cuda.is_available() is True)

However, I observe that accelerate cannot find the gpu.

![截屏2023-02-08 下午8 57 06](https://user-images.githubusercontent.com/51499992/217535906-b613423c-e8de-4f58-b1be-32cede84acbf.png)

**Comment by muellerzr** [comment]
@ShaoTengLiu when opening this issue you should have been prompted to provide us with more information, such as the output from `accelerate env`, how you are launching the script, and more. Please provide us these details so we can try to accurately recreate your environment to test this.

**Comment by ShaoTengLiu** [comment]
Thanks for your reply!

Here is my accelerate env:
- `Accelerate` version: 0.16.0
- Platform: Linux-5.4.15-1.el7.elrepo.x86_64-x86_64-with-glibc2.27
- Python version: 3.9.16
- Numpy version: 1.23.5
- PyTorch version (GPU?): 1.12.1+cu116 (True)
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: NO
        - mixed_precision: no
        - use_cpu: True
        - dynamo_backend: NO
        - num_processes: 1
        - machine_rank: 0
        - num_machines: 1
        - rdzv_backend: static
        - same_network: False
        - main_training_function: main
        - deepspeed_config: {}
        - fsdp_config: {}
        - megatron_lm_config: {}
        - downcast_bf16: False

run:
`accelerate launch train.py --config=./config.yaml`

inside train.py:
`    accelerator = Accelerator(
        gradient_accumulation_steps=gradient_accumulation_steps,
        mixed_precision=mixed_precision,
    )`

**Comment by muellerzr** [comment]
You have `use_cpu` as `True`, it's going to use the CPU no matter what this way. You need to set it to `False` to have it use the GPU

**Comment by ShaoTengLiu** [comment]
My problem has been solved. Thanks!
