### ISSUE TITLE
What to use instead of dist.all_reduce?

### ISSUE THREAD

**Issue by HashmatShadab** [huggingface/accelerate#1057]
```
 @torch.no_grad()
    def update_center(self, teacher_output):
        """
        Update center used for teacher output.
        """
        batch_center = torch.sum(teacher_output, dim=0, keepdim=True)
        dist.all_reduce(batch_center)
        batch_center = batch_center / (len(teacher_output) * dist.get_world_size())

        # ema update
        self.center = self.center * self.center_momentum + batch_center * (1 - self.center_momentum)
```
In the above template, what would be the replacement for dist.all_reduce if using accelerate for training? The code is from https://github.com/microsoft/esvit/blob/ca16a2c45f7a8a1daaf92b71773de3f4b7d9cd3f/main_esvit.py#L651

**Comment by pacman100** [comment]
Hello @HashmatShadab, it would be `accelerator.reduce()`: https://huggingface.co/docs/accelerate/package_reference/accelerator#accelerate.Accelerator.reduce

**Comment by pacman100** [comment]
Please ask the queries on discussion forum: https://discuss.huggingface.co/c/accelerate/18

**Comment by HashmatShadab** [comment]
Ok. Thanks.
