### ISSUE TITLE
Reduce support for multi_cpu

### ISSUE THREAD

**Issue by alex-hh** [huggingface/accelerate#1058]
As far as I can tell, reduce for multi_cpu actually just performs a within-process instead of an across-process reduction. 

https://github.com/huggingface/accelerate/blob/36beea9a1be9251a3ad07f7c10fd425c96954f46/src/accelerate/utils/operations.py#L430-L443

**Comment by sgugger** [comment]
Indeed. Would you like to open a PR with a fix?

**Comment by alex-hh** [comment]
Sure - I'll look into it
