### ISSUE TITLE
[for help] How to debug the distributed training code in PyCharm

### ISSUE THREAD

**Issue by koking0** [huggingface/accelerate#1067]
I started a multi-GPU training [script](https://github.com/lvwerra/trl/blob/main/examples/sentiment/scripts/gpt2-sentiment.py) through accelerate. The startup command is `accelerate launch gpt2-sentiment.py`, but there seems to be some problems.

The training process has been stuck in the first epoch, and there is no error or timeout. I can run through PyCharm to debug on 1 GPU, so the problem should be on multiple GPUs.

I suspect that the communication between the GPUs may be stuck in some places, or due to deadlocks, etc., but I am not sure now, so I want to debug the execution process of accelerate step by step through PyCharm, how should I configure it?

![image](https://user-images.githubusercontent.com/45281765/218633731-a770d6de-ec10-40bb-837a-b4b30dec06e1.png)

**Comment by sgugger** [comment]
I don't think that is possible, since the script is then launched in different subprocesses.

**Comment by koking0** [comment]
> I don't think that is possible, since the script is then launched in different subprocesses.

Thanks, I will use the most original print to debug.
