### ISSUE TITLE
FP16 cannot be used

### ISSUE THREAD

**Issue by raicnc** [huggingface/accelerate#1072]
### System Info

```Shell
Python 3.9.13
torch: 1.12.1+cu113
accelerate: 0.16.0
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

```
import torch
import accelerate

accelerator = accelerate.Accelerator(fp16=True)
```
output:
Traceback (most recent call last)
/tmp/ipykernel_9062/3331576430.py in <cell line: 4>()
      2 import accelerate
      3 
----> 4 accelerator = accelerate.Accelerator(fp16=True)

TypeError: __init__() got an unexpected keyword argument 'fp16'

### Expected behavior

```Shell
Successfully imported.
```

**Comment by muellerzr** [comment]
As the docstring states, you need to use `mixed_precision="fp16"` instead

**Comment by raicnc** [comment]
> As the docstring states, you need to use `mixed_precision="fp16"` instead

thanks
