### ISSUE TITLE
megatron_generate function for T5 models

### ISSUE THREAD

**Issue by WenzhengZhang** [huggingface/accelerate#1085]
It seems that the `megatron_generate` function [here](https://github.com/huggingface/accelerate/blob/b34db0b98743692993288979822f9eabe6098008/src/accelerate/utils/megatron_lm.py#L1228) only supports GPT models. Do you have any plan to support T5 megatron_generate?

**Comment by sgugger** [comment]
cc @pacman100

**Comment by pacman100** [comment]
Hello @WenzhengZhang, currently it is not in our backlog. If people are interested in this feature, please react to this comment. Based on the interest, it will prioritized accordingly. 

Also, PRs are always welcome.

**Comment by WenzhengZhang** [comment]
> Hello @WenzhengZhang, currently it is not in our backlog. If people are interested in this feature, please react to this comment. Based on the interest, it will prioritized accordingly.
> 
> Also, PRs are always welcome.

Hi @pacman100 , thanks for reply! Do you have any scripts for converting Megatron_T5 to HF_T5 so that I can do inference using HF `generate` function?
