### ISSUE TITLE
checkpoint_reshaping_and_interoperability.py HF->Megatron checkpoint can't be loaded by megatron

### ISSUE THREAD

**Issue by dumpmemory** [huggingface/accelerate#1088]
### System Info

Hi, i have try to convert hf checkpoint to megatron checkpoint with checkpoint_reshaping_and_interoperability.py tp=8 pp=1 dp=1. I try to load the converted checkpoint with --resume_from_checkpoint args, but it failed to work. only one gpu has been used.  I have checked the saved checkpoint from accelerate.save_state with converted one. converted one has ['model']['words_embedding_for_head'] which is not in save_state version.

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

1. gpt config `{
  "activation_function": "gelu_fast",
  "architectures": [
    "GPT2LMHeadModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "attention_type": "self",
  "attn_pdrop": 0.1,
  "bos_token_id": 7,
  "embd_pdrop": 0.1,
  "eos_token_id": 7,
  "fp16": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "initializer_range": 0.02,
  "intermediate_size": 768,
  "layer_norm_epsilon": 1e-05,
  "layernorm_epsilon": 1e-05,
  "masked_softmax_fusion": false,
  "model_type": "gpt2",
  "n_embd": 2048,
  "n_head": 32,
  "n_inner": null,
  "n_layer": 24,
  "n_positions": 2048,
  "reorder_and_upcast_attn": false,
  "resid_pdrop": 0.1,
  "scale_attn_by_inverse_layer_idx": false,
  "scale_attn_weights": true,
  "summary_activation": null,
  "summary_first_dropout": 0.1,
  "summary_proj_to_labels": true,
  "summary_type": "cls_index",
  "summary_use_proj": true,
  "tokenizer_class": "PreTrainedTokenizer",
  "transformers_version": "4.27.0.dev0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 51200
}`
2. python checkpoint_reshaping_and_interoperability.py \
--load_path "1.3b_hg_gelu" \
--save_path "1.3b_hg_gelu_megatron" \
--target_tensor_model_parallel_size 8 \
--target_pipeline_model_parallel_size 1 \
--target_data_parallel_size 1 \
--target_params_dtype "fp16" \
--use_distributed_optimizer \
--print-checkpoint-structure

3. accelerate launch --config_file megatron_gpt_config.yaml megatron_lm_gpt_pretraining.py \
--resume_from_checkpoint '1.3b_hg_gelu_megatron' \
--config_name "1.3b_hg_gelu" \
--tokenizer_name "1.3b_hg_gelu" \
--dataset_name wikitext \
--dataset_config_name wikitext-2-raw-v1 \
--block_size 1024 \
--learning_rate 5e-5 \
--per_device_train_batch_size 2 \
--per_device_eval_batch_size 2 \
--num_train_epochs 1 \
--with_tracking \
--output_dir "awesome_model_1.3"

### Expected behavior

```Shell
can be loaded
```

**Comment by sgugger** [comment]
cc @pacman100
