### ISSUE TITLE
Misspelling in accelerate/util/modeling

### ISSUE THREAD

**Issue by whiteknight6766** [huggingface/accelerate#1093]
### System Info

```Shell
- `Accelerate` version: 0.12.0
- Platform: Linux-5.18.9-arch1-1-x86_64-with-glibc2.35
- Python version: 3.10.5
- Numpy version: 1.23.3
- PyTorch version (GPU?): 1.12.1+cu102 (True)
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

The script i am trying accomplish. 

```
with` init_empty_weights():
    model = AutoModelForCausalLM.from_config(config)

device_map = infer_auto_device_map(model, max_memory={0: "7GiB", 1: "20GiB"}) #, "cpu": "20GiB"})

model = load_checkpoint_and_dispatch(model, ModelPath, device_map=device_map, offload_folder=offloadFolder)
```

Loads from directory that contains two models (because safetensors and ckpt are both downloaded by default with git clone). 

The following error is thrown,

```
  File ".local/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 649, in load_checkpoint_in_model
    raise ValueError(f"{checkpoint} containing mote than one `.index.json` file, delete the irrelevant ones.")
ValueError: .../cache/bloom/ containing mote than one `.index.json` file, delete the irrelevant ones.

```

### Expected behavior

```Shell
Value error should read 

"containing more than one `.index.json` file, delete the irrelevant ones."

Note that the official script has a misspelling using the wore "mote" vice "more"
```

**Comment by sgugger** [comment]
Thanks for flagging! Do you want to open a PR with those fixes?

**Comment by whiteknight6766** [comment]
Its supposed to be easy, but i can't figure out github. Good luck!
