### ISSUE TITLE
How to pass custom arguments to DDP / GradScaler

### ISSUE THREAD

**Issue by ppwwyyxx** [huggingface/accelerate#11]
Thanks for creating this nice tool!

I am wondering what's the best way to use accelerate, but still keep the capability to tune the arguments of DDP / GradScaler / (perhaps other classes as well). They have some pretty useful arguments (e.g. https://pytorch.org/docs/stable/generated/torch.nn.parallel.DistributedDataParallel.html).

**Comment by sgugger** [comment]
Hi there! For DDP, you can still wrap the model yourself by not passing it to the `prepare` method, the downside is that you then lose the fact your script is compatible on single-GPU/multi-GPU/TPU, but it would work with the rest. For the `GradScaler`, you can just replace your `accelerator.scaler` with what you want, but it would be bound by the same caveats.

An alternative is to have fields in the config (the file generated when you do `accelerate config`) or another config-like file that can be used to set values that would be used as kwargs in those methods when called. So in this case the script would still work on all setups but you would have to fill that config file kind of manually.

What do you think?

**Comment by thomwolf** [comment]
Another possibility, maybe we could have an optional `DDPConfig` and/or `GradScalerConfig` passed to the initialization of the Accelerate object? with the same arguments as the PyTorch counterparts

**Comment by ppwwyyxx** [comment]
> you can still wrap the model yourself by not passing it to the prepare method, the downside is that you then lose the fact your script is compatible on single-GPU/multi-GPU/TPU, but it would work with the rest

In that case I think user will lose the ability to use fp16+ddp using accelerate, which requires passing the model to `prepare`.

Some "config" might work, although note that some features of DDP is not in its `__init__`, e.g.: https://pytorch.org/docs/stable/ddp_comm_hooks.html

**Comment by sgugger** [comment]
> Another possibility, maybe we could have an optional DDPConfig and/or GradScalerConfig passed to the initialization of the Accelerate object? 

I like that idea a lot!

> Some "config" might work, although note that some features of DDP is not in its __init__

Features that are more exotic won't be covered by the API, the same way it doesn't provide everything `torch.distributed` provides in terms of operations. For those, you would still need to do some specific test like, for instance,

```
if isinstance(model, torch.nn.parallel.DistributedDataParallel):
    model.register_comm_hook(xxx)
```
