### ISSUE TITLE
Preparing dataloaders in two accelerator.prepare calls when deepspeed is enabled issue.

### ISSUE THREAD

**Issue by lqtrung1998** [huggingface/accelerate#1101]
Hi, I recently encounter this:
```
## Deepspeed enabled
dataloader1 = accelerator.prepare(dataloader1) # correctly prepared 
dataloader2 = accelerator.prepare(dataloader2) #  not correctly prepared
```
https://github.com/huggingface/accelerate/blob/03754c1e026b6e36cad05728aac75b82fac63b20/src/accelerate/accelerator.py#L1154 
Correct me if I'm wrong but ... It seems that when deepspeed is enabled, only in the first prepare that the dataloader is prepared ... after the first prepare, I guess the `train_micro_batch_size_per_gpu` will not be 'auto', thus, the original dataloader2 is returned.

Is it a bug or it is expected and this has been mentioned somewhere in the doc ?

Thank you,
Trung

**Comment by sgugger** [comment]
cc @pacman100

**Comment by pacman100** [comment]
Hello @lqtrung1998, please let us know if the above PR fixes the issue?
