### ISSUE TITLE
Overflows with BNB-quantized BLOOM

### ISSUE THREAD

**Issue by barsuna** [huggingface/accelerate#1104]
### System Info

```Shell
accelerate               0.16.0
bitsandbytes             0.37.0
torch                    1.12.1+cu113
transformers             4.26.1

python 3.8.10
OS Ubuntu 20.04.4 kernel 5.4.0-100

GPU: driver 465.19.01, boards: 8x Tesla v100 (32GB each)
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

In short: i load BLOOM (or BLOOMz) in 8-bit using below device_map and model loads fine. However when trying to do inference it either produces <unk> tokens (0) or crashes due to Inf in the intermediate outputs. Successive debugging shows there are overflows (inf) in the intermediate layers:

The model loading part is like so (no error at this stage though):

device map:

dmap2 = {'lm_head': 0,
 'transformer.word_embeddings': 0,
 'transformer.word_embeddings_layernorm': 0,
 'transformer.h.0': 0,
 'transformer.h.1': 0,
 'transformer.h.2': 0,
 'transformer.h.3': 0,
 'transformer.h.4': 0,
 'transformer.h.5': 1,
 'transformer.h.6': 1,
 'transformer.h.7': 1,
 'transformer.h.8': 1,
 'transformer.h.9': 1,
 'transformer.h.10': 1,
 'transformer.h.11': 1,
 'transformer.h.12': 1,
 'transformer.h.13': 1,
 'transformer.h.14': 1,
 'transformer.h.15': 1,
 'transformer.h.16': 2,
 'transformer.h.17': 2,
 'transformer.h.18': 2,
 'transformer.h.19': 2,
 'transformer.h.20': 2,
 'transformer.h.21': 2,
 'transformer.h.22': 2,
 'transformer.h.23': 2,
 'transformer.h.24': 2,
 'transformer.h.25': 2,
 'transformer.h.26': 2,
 'transformer.h.27': 3,
 'transformer.h.28': 3,
 'transformer.h.29': 3,
 'transformer.h.30': 3,
 'transformer.h.31': 3,
 'transformer.h.32': 3,
 'transformer.h.33': 3,
 'transformer.h.34': 3,
 'transformer.h.35': 3,
 'transformer.h.36': 3,
 'transformer.h.37': 3,
 'transformer.h.38': 4,
 'transformer.h.39': 4,
 'transformer.h.40': 4,
 'transformer.h.41': 4,
 'transformer.h.42': 4,
 'transformer.h.43': 4,
 'transformer.h.44': 4,
 'transformer.h.45': 4,
 'transformer.h.46': 4,
 'transformer.h.47': 4,
 'transformer.h.48': 4,
 'transformer.h.49': 5,
 'transformer.h.50': 5,
 'transformer.h.51': 5,
 'transformer.h.52': 5,
 'transformer.h.53': 5,
 'transformer.h.54': 5,
 'transformer.h.55': 5,
 'transformer.h.56': 5,
 'transformer.h.57': 5,
 'transformer.h.58': 5,
 'transformer.h.59': 5,
 'transformer.h.60': 6,
 'transformer.h.61': 6,
 'transformer.h.62': 6,
 'transformer.h.63': 6,
 'transformer.h.64': 6,
 'transformer.h.65': 6,
 'transformer.h.66': 6,
 'transformer.h.67': 6,
 'transformer.h.68': 6,
 'transformer.h.69': 6,
 'transformer.ln_f': 6}

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
model = AutoModelForCausalLM.from_pretrained('bigscience/bloomz', device_map=dmap2, load_in_8bit=True, torch_dtype=torch.int8)

Above loads ok, i then follow to try generation

tokenizer = AutoTokenizer.from_pretrained('bigscience/bloomz')
inputs = tokenizer("Do androids dream of", return_tensors="pt")["input_ids"]
outputs = model.generate(inputs.to(0), temperature=0.7, do_sample=False, max_new_tokens=5)
print(tokenizer.decode(outputs[0]))

Which produces  0-filled vector

Do androids dream of<unk><unk><unk><unk><unk>

or an error in case of do_sample=True

outputs = model.generate(inputs.to(0), temperature=0.7, do_sample=True, max_new_tokens=5)

"""
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[9], line 2
      1 inputs = tokenizer("Do androids dream of", return_tensors="pt")["input_ids"]
----> 2 outputs = model.generate(inputs.to(0), temperature=0.7, do_sample=True, max_new_tokens=5) #, do_sample=True)
      3 print(tokenizer.decode(outputs[0]))

File /raid/test/accelerate/lib/python3.8/site-packages/torch/autograd/grad_mode.py:27, in _DecoratorContextManager.__call__.<locals>.decorate_context(*args, **kwargs)
     24 @functools.wraps(func)
     25 def decorate_context(*args, **kwargs):
     26     with self.clone():
---> 27         return func(*args, **kwargs)

File /raid/test/accelerate/lib/python3.8/site-packages/transformers/generation/utils.py:1437, in GenerationMixin.generate(self, inputs, generation_config, logits_processor, stopping_criteria, prefix_allowed_tokens_fn, synced_gpus, **kwargs)
   1429     input_ids, model_kwargs = self._expand_inputs_for_generation(
   1430         input_ids=input_ids,
   1431         expand_size=generation_config.num_return_sequences,
   1432         is_encoder_decoder=self.config.is_encoder_decoder,
   1433         **model_kwargs,
   1434     )
   1436     # 13. run sample
-> 1437     return self.sample(
   1438         input_ids,
   1439         logits_processor=logits_processor,
   1440         logits_warper=logits_warper,
   1441         stopping_criteria=stopping_criteria,
   1442         pad_token_id=generation_config.pad_token_id,
   1443         eos_token_id=generation_config.eos_token_id,
   1444         output_scores=generation_config.output_scores,
   1445         return_dict_in_generate=generation_config.return_dict_in_generate,
   1446         synced_gpus=synced_gpus,
   1447         **model_kwargs,
   1448     )
   1450 elif is_beam_gen_mode:
   1451     if generation_config.num_return_sequences > generation_config.num_beams:

File /raid/test/accelerate/lib/python3.8/site-packages/transformers/generation/utils.py:2479, in GenerationMixin.sample(self, input_ids, logits_processor, stopping_criteria, logits_warper, max_length, pad_token_id, eos_token_id, output_attentions, output_hidden_states, output_scores, return_dict_in_generate, synced_gpus, **model_kwargs)
   2477 # sample
   2478 probs = nn.functional.softmax(next_token_scores, dim=-1)
-> 2479 next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
   2481 # finished sentences should have their next token be a padding token
   2482 if eos_token_id is not None:

RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
"""

I have used https://github.com/huggingface/transformers/blob/main/docs/source/en/debugging.mdx to locate the place where overflow happens.

output has infs

Detected inf/nan during batch_number=0
Last 21 forward frames:
abs min  abs max  metadata
… skipped…
                  transformer.h.61.mlp.dense_h_to_4h Linear8bitLt
0.00e+00 1.27e+02 weight
2.98e-07 6.30e-02 bias
2.80e-06 8.22e+01 input[0]
0.00e+00 1.66e+01 output
                  transformer.h.61.mlp.gelu_impl BloomGelu
0.00e+00 1.66e+01 input[0]
0.00e+00 9.98e+00 output
                  transformer.h.61.mlp.dense_4h_to_h Linear8bitLt
0.00e+00 1.27e+02 weight
2.98e-06 1.10e-01 bias
0.00e+00 9.98e+00 input[0]
0.00e+00      inf output

Trying to alleviate the overflow i've added the blockname (transformer.h.61.mlp.dense_4h_to_h) to 'load_in_8bit_skip_modules' list, and reloaded the model as below:

model = AutoModelForCausalLM.from_pretrained(checkpoint, device_map=dmap2, load_in_8bit=True, torch_dtype=torch.int8, load_in_8bit_skip_modules= ['transformer.h.61.mlp.dense_4h_to_h'])

Model loads fine (everything is in GPUs), but when trying generation, a new error appears, that i haven't found much on 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[6], line 2
      1 inputs = tokenizer("Are androids dreaming of", return_tensors="pt")["input_ids"]
----> 2 outputs = model.generate(inputs.to(0), temperature=0.7, do_sample=True, max_new_tokens=5) #, do_sample=True)
      3 print(tokenizer.decode(outputs[0]))  # A cat sat on a mat...

File /raid/test/accelerate/lib/python3.8/site-packages/torch/autograd/grad_mode.py:27, in _DecoratorContextManager.__call__.<locals>.decorate_context(*args, **kwargs)
     24 @functools.wraps(func)
     25 def decorate_context(*args, **kwargs):
     26     with self.clone():
---> 27         return func(*args, **kwargs)

File /raid/test/accelerate/lib/python3.8/site-packages/transformers/generation/utils.py:1437, in GenerationMixin.generate(self, inputs, generation_config, logits_processor, stopping_criteria, prefix_allowed_tokens_fn, synced_gpus, **kwargs)
   1429     input_ids, model_kwargs = self._expand_inputs_for_generation(
   1430         input_ids=input_ids,
   1431         expand_size=generation_config.num_return_sequences,
   1432         is_encoder_decoder=self.config.is_encoder_decoder,
   1433         **model_kwargs,
   1434     )
   1436     # 13. run sample
-> 1437     return self.sample(
   1438         input_ids,
   1439         logits_processor=logits_processor,
   1440         logits_warper=logits_warper,
   1441         stopping_criteria=stopping_criteria,
   1442         pad_token_id=generation_config.pad_token_id,
   1443         eos_token_id=generation_config.eos_token_id,
   1444         output_scores=generation_config.output_scores,
   1445         return_dict_in_generate=generation_config.return_dict_in_generate,
   1446         synced_gpus=synced_gpus,
   1447         **model_kwargs,
   1448     )
   1450 elif is_beam_gen_mode:
   1451     if generation_config.num_return_sequences > generation_config.num_beams:

File /raid/test/accelerate/lib/python3.8/site-packages/transformers/generation/utils.py:2443, in GenerationMixin.sample(self, input_ids, logits_processor, stopping_criteria, logits_warper, max_length, pad_token_id, eos_token_id, output_attentions, output_hidden_states, output_scores, return_dict_in_generate, synced_gpus, **model_kwargs)
   2440 model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)
   2442 # forward pass to get next token
-> 2443 outputs = self(
   2444     **model_inputs,
   2445     return_dict=True,
   2446     output_attentions=output_attentions,
   2447     output_hidden_states=output_hidden_states,
   2448 )
   2450 if synced_gpus and this_peer_finished:
   2451     continue  # don't waste resources running the code we don't need

File /raid/test/accelerate/lib/python3.8/site-packages/torch/nn/modules/module.py:1130, in Module._call_impl(self, *input, **kwargs)
   1126 # If we don't have any hooks, we want to skip the rest of the logic in
   1127 # this function, and just call forward.
   1128 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130     return forward_call(*input, **kwargs)
   1131 # Do not call functions when jit is used
   1132 full_backward_hooks, non_full_backward_hooks = [], []

File /raid/test/accelerate/lib/python3.8/site-packages/accelerate/hooks.py:158, in add_hook_to_module.<locals>.new_forward(*args, **kwargs)
    156         output = old_forward(*args, **kwargs)
    157 else:
--> 158     output = old_forward(*args, **kwargs)
    159 return module._hf_hook.post_forward(module, output)

File /raid/test/accelerate/lib/python3.8/site-packages/transformers/models/bloom/modeling_bloom.py:913, in BloomForCausalLM.forward(self, input_ids, past_key_values, attention_mask, head_mask, inputs_embeds, labels, use_cache, output_attentions, output_hidden_states, return_dict, **deprecated_arguments)
    900 transformer_outputs = self.transformer(
    901     input_ids,
    902     past_key_values=past_key_values,
   (...)
    909     return_dict=return_dict,
    910 )
    911 hidden_states = transformer_outputs[0]
--> 913 lm_logits = self.lm_head(hidden_states)
    915 loss = None
    916 if labels is not None:
    917     # Shift so that tokens < n predict n

File /raid/test/accelerate/lib/python3.8/site-packages/torch/nn/modules/module.py:1130, in Module._call_impl(self, *input, **kwargs)
   1126 # If we don't have any hooks, we want to skip the rest of the logic in
   1127 # this function, and just call forward.
   1128 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130     return forward_call(*input, **kwargs)
   1131 # Do not call functions when jit is used
   1132 full_backward_hooks, non_full_backward_hooks = [], []

File /raid/test/accelerate/lib/python3.8/site-packages/accelerate/hooks.py:158, in add_hook_to_module.<locals>.new_forward(*args, **kwargs)
    156         output = old_forward(*args, **kwargs)
    157 else:
--> 158     output = old_forward(*args, **kwargs)
    159 return module._hf_hook.post_forward(module, output)

File /raid/test/accelerate/lib/python3.8/site-packages/bitsandbytes/nn/modules.py:235, in Linear8bitLt.forward(self, x)
    233 def forward(self, x: torch.Tensor):
    234     self.state.is_training = self.training
--> 235     if self.weight.CB is not None:
    236         self.init_8bit_state()
    238     # weights are cast automatically as Int8Params, but the bias has to be cast manually

AttributeError: 'Parameter' object has no attribute 'CB'

### Expected behavior

```Shell
Be able to run generation without error.

Am i using the load_in_8bit_skip_modules incorrectly?

In https://github.com/huggingface/transformers/pull/10956
there is are couple of mitigations suggested: the load_in_8bit_skip_modules and also 
'loss penalty factor' - which seems to require code modification... so i wonder is it right idea to dive deeper into the weeds, or is there better way to get rid or overflows (while staying in 8bit)
```

**Comment by muellerzr** [comment]
cc @sgugger

**Comment by barsuna** [comment]
Looking at replace_8bit_linear function i realized that names in load_in_8bit_skip_modules should include only the last bit, so i've changed the loading function to 

model = AutoModelForCausalLM.from_pretrained(checkpoint, device_map=dmap2, load_in_8bit=True, torch_dtype=torch.int8, load_in_8bit_skip_modules = [ 'dense_4h_to_h', 'lm_head'])

This loads, but since it now doesn't convert dense_4h_to_h in all 70 layers - the GPU memory is full everywhere and i still get inf related error (as before), but cannot anymore debug the location (that requires about 3GB of GPU memory)

Is there no way to skip conversion of particular layer?

**Comment by sgugger** [comment]
cc @younesbelkada

**Comment by barsuna** [comment]
Another update: i've modified replace_8bit_linear to allow excluding specific layer/module and after a lot of fiddling managed to get generation working. 

Have to say though, it is a research-grade workaround at best: i had to skip converting 10 modules before the overflows went way: had to skip a module in layer 22, then every layer from 61 to 69 - tried a few different prompts, dont see overflows. 

Since skipped modules are larger in size, i had to tweak the max_memory, for each GPU individually, so that infer_auto_device_map generates plausible device_map (which still had to be modified manually a little bit)

This made we wonder if there is a better solution to these overflows: if these are not input (prompt) related, then do others also see them?

Not sure, if this has anything to do, but GPUs i'm using are pre-Turing (i.e. compute cap 7.0), but to my understanding that should impact performance (since they dont have tensorcores support for int8), not lead to overflows.

**Comment by barsuna** [comment]
Spoke too soon :) Upon broader testing - there are still many parameter cobinations and prompts that still lead to inf errors. Also the <unk> (token 0) are still present in response to some other prompts.
