### ISSUE TITLE
I got a error:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 2 (pid: 4296) of binary

### ISSUE THREAD

**Issue by pengjunfeng11** [huggingface/accelerate#1106]
### System Info

```Shell
Copy-and-paste the text below in your GitHub issue

- `Accelerate` version: 0.16.0
- Platform: Linux-4.15.0-189-generic-x86_64-with-glibc2.27
- Python version: 3.9.13
- Numpy version: 1.22.3
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: FSDP
        - mixed_precision: no
        - use_cpu: False
        - dynamo_backend: NO
        - num_processes: 8
        - machine_rank: 0
        - num_machines: 1
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - deepspeed_config: {}
        - fsdp_config: {'fsdp_auto_wrap_policy': 'TRANSFORMER_BASED_WRAP', 'fsdp_backward_prefetch_policy': 'BACKWARD_PRE', 'fsdp_offload_params': True, 'fsdp_sharding_strategy': 1, 'fsdp_state_dict_type': 'LOCAL_STATE_DICT', 'fsdp_transformer_layer_cls_to_wrap': 'berry_TEST_layer'}
        - megatron_lm_config: {}
        - downcast_bf16: no
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

I has run the official example for test my accelerate.[The full code is here](https://github.com/huggingface/accelerate/blob/main/examples/nlp_example.py).

And the command that I use to launch this file is :
`CUDA_VISIBLE_DEVICES="1,2,3,4,5,6,7" accelerate launch --multi_gpu --mixed_precision=fp16 --num_processes=7 demo.py`

Then , I got a exception and I can't get other information from the log info.
Here is my debug info:

> - This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
> - This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
> Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-cased and are newly initialized: ['classifier.weight', 'classifier.bias']
> You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 4487 closing signal SIGTERM
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 4488 closing signal SIGTERM
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 4489 closing signal SIGTERM
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 4490 closing signal SIGTERM
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 4491 closing signal SIGTERM
> WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 4492 closing signal SIGTERM
> ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 0 (pid: 4486) of binary: /home/ubuntu/anaconda3/envs/pytorch39/bin/python3.9

I has set my logging level with :
`import logging
logging.basicConfig(level=logging.DEBUG)`

But i can't get more information about this exception.

### Expected behavior

```Shell
Just want my accelerate can be use😢.
```

**Comment by sgugger** [comment]
You are using 7 GPUs with a config at 8 processes. The mismatch is what causes the error. Fix either (so change `CUDA_VISIBLE_DEVICES` or your config) and it should work.

**Comment by pengjunfeng11** [comment]
> You are using 7 GPUs with a config at 8 processes. The mismatch is what causes the error. Fix either (so change `CUDA_VISIBLE_DEVICES` or your config) and it should work.

Ok, thank you, now I change the command with `CUDA_VISIBLE_DEVICES="0,1,2,3,4,5,6,7"`, but I still got the same wrong , should I provide more infomation?

**Comment by pengjunfeng11** [comment]
> You are using 7 GPUs with a config at 8 processes. The mismatch is what causes the error. Fix either (so change `CUDA_VISIBLE_DEVICES` or your config) and it should work.

Oh, sorry , I'm such a newbie. This problem is because my `num_processes: 8` in the config  and `CUDA_VISIBLE_DEVICES ` ,`--num_processes=7` in the command, these three parameters did not match

**Comment by pengjunfeng11** [comment]
> You are using 7 GPUs with a config at 8 processes. The mismatch is what causes the error. Fix either (so change `CUDA_VISIBLE_DEVICES` or your config) and it should work.

Anyway , still thank you !!

**Comment by AnustupOCR** [comment]
> ### System Info
> 
> ```shell
> Copy-and-paste the text below in your GitHub issue
> 
> - `Accelerate` version: 0.16.0
> - Platform: Linux-4.15.0-189-generic-x86_64-with-glibc2.27
> - Python version: 3.9.13
> - Numpy version: 1.22.3
> - PyTorch version (GPU?): 1.13.1+cu117 (True)
> - `Accelerate` default config:
>         - compute_environment: LOCAL_MACHINE
>         - distributed_type: FSDP
>         - mixed_precision: no
>         - use_cpu: False
>         - dynamo_backend: NO
>         - num_processes: 8
>         - machine_rank: 0
>         - num_machines: 1
>         - rdzv_backend: static
>         - same_network: True
>         - main_training_function: main
>         - deepspeed_config: {}
>         - fsdp_config: {'fsdp_auto_wrap_policy': 'TRANSFORMER_BASED_WRAP', 'fsdp_backward_prefetch_policy': 'BACKWARD_PRE', 'fsdp_offload_params': True, 'fsdp_sharding_strategy': 1, 'fsdp_state_dict_type': 'LOCAL_STATE_DICT', 'fsdp_transformer_layer_cls_to_wrap': 'berry_TEST_layer'}
>         - megatron_lm_config: {}
>         - downcast_bf16: no
> ```
> 
> ### Information
> 
>     * [x]  The official example scripts
> 
>     * [ ]  My own modified scripts
> 
> 
> ### Tasks
> 
>     * [x]  One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
> 
>     * [ ]  My own task or dataset (give details below)
> 
> 
> ### Reproduction
> 
> I has run the official example for test my accelerate.[The full code is here](https://github.com/huggingface/accelerate/blob/main/examples/nlp_example.py).
> 
> And the command that I use to launch this file is : `CUDA_VISIBLE_DEVICES="1,2,3,4,5,6,7" accelerate launch --multi_gpu --mixed_precision=fp16 --num_processes=7 demo.py`
> 
> Then , I got a exception and I can't get other information from the log info. Here is my debug info:
> 
> > * This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
> > * This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
> >   Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-cased and are newly initialized: ['classifier.weight', 'classifier.bias']
> >   You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
> >   WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 4487 closing signal SIGTERM
> >   WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 4488 closing signal SIGTERM
> >   WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 4489 closing signal SIGTERM
> >   WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 4490 closing signal SIGTERM
> >   WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 4491 closing signal SIGTERM
> >   WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 4492 closing signal SIGTERM
> >   ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 0 (pid: 4486) of binary: /home/ubuntu/anaconda3/envs/pytorch39/bin/python3.9
> 
> I has set my logging level with : `import logging logging.basicConfig(level=logging.DEBUG)`
> 
> But i can't get more information about this exception.
> ### Expected behavior
> 
> ```shell
> Just want my accelerate can be use😢.
> ```

Hi, I have been facing the same issue.And the fix mentioned here is not the cause in my case? Any other reason for this problem?

**Comment by muellerzr** [comment]
@AnustupOCR can you provide a reproducer?

**Comment by wangyePHD** [comment]
I also have the same issue. I find that if I use 2 GPUs for training, which is ok. but if more than 2 GPUs (3,4)， it will appear errors.

**Comment by wangyePHD** [comment]
hey guys， I also have the same issue when I use accelerate to train Stable Diffusion. At last, I find that the reason is the CPU memory is not enough.

**Comment by xuwenxinedu** [comment]
> hey guys， I also have the same issue when I use accelerate to train Stable Diffusion. At last, I find that the reason is the CPU memory is not enough.

@wangyePHD This reply saved me so much time. Awesome!
