### ISSUE TITLE
Wrong accelerate config path doesn't throw any errors

### ISSUE THREAD

**Issue by pratogab** [huggingface/accelerate#1115]
### System Info

```Shell
`Accelerate` version: 0.15.0
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

`accelerate launch --config_file=path/that/does/not/exist/example_config.yaml` example_script_that_exists.py`
This will launch the script just fine and use the default values. This behaviour is very confusing and unexpected. You would assume that a wrong path to the config would throw an error.

### Expected behavior

```Shell
See above.
```

**Comment by muellerzr** [comment]
This was fixed last week via https://github.com/huggingface/accelerate/pull/1074 and will be pushed on the next release
