### ISSUE TITLE
How to specify a logger from the cli?

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [huggingface/accelerate#1117]
### System Info

```Shell
Copy-and-paste the text below in your GitHub issue

- `Accelerate` version: 0.16.0
- Platform: Linux-5.19.0-31-generic-x86_64-with-glibc2.36
- Python version: 3.9.13
- Numpy version: 1.24.2
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: NO
        - mixed_precision: fp16
        - use_cpu: False
        - dynamo_backend: NO
        - num_processes: 1
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: 0
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - deepspeed_config: {}
        - fsdp_config: {}
        - megatron_lm_config: {}
        - downcast_bf16: no
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

I tried to use `--log_with` from the cli but It's not a valid comand

### Expected behavior

```Shell
I would like to know if is possible to add a logger from the cli - Thanks
```

**Comment by muellerzr** [comment]
That's specific to the script, you need to specify that in the `Accelerator` as the docs show: https://huggingface.co/docs/accelerate/usage_guides/tracking

**Comment by FrancescoSaverioZuppichini** [comment]
Got it, I was doing it this way before but I was looking if there was a way from the cli - thanks
