### ISSUE TITLE
[feature request / discussion] `accelerate tune`

### ISSUE THREAD

**Issue by dbpprt** [huggingface/accelerate#1120]
*(Note: this issue is intended to have a quick discussion about a potential feature)*

The current implementation of **SageMaker** as execution environment supports training in AWS. It would be potentially quite easy to extend the mechanism in order to additionally do hyperparameter optimization using  [SageMaker Automatic Model Tuning](https://docs.aws.amazon.com/sagemaker/latest/dg/automatic-model-tuning.html). 

**Use-case:**
Accelerate is excellent for quick prototyping and experimentation, especially fine-tuning one of many models to evaluate use-cases or even using `peft`. Finding the right hyperparameters involves intuition, the papers for the corresponding models, or copy & paste from examples (which likely followed a similar approach). `accelerate tune` helps to quickly iterate through several parameters, making it even more valuable for a potential user, especially when using it for fine-tuning tasks, which do not take a lot of time but potentially benefit a lot from HPO.

**Proposal:**
- *Nice to have: Add SageMaker experiments as a tracker, not required but potentially useful for the target audience.*
- Support a new CLI command `accelerate tune`
- Allow defining continuous, categorical and integer values as an extension to the current way specifying args for the training script.
- re-use the configuration created for SageMaker, there is no need to extend the wizard or add anything to the config in order to create a tuning job.

**Remarks:**
- There is no local equivalent (for now), but potentially could be, not sure how relevant it is though.
- Understanding the results is not part of `accelerate`, this would be an `example` on how to analyze the results.
- ...? probably more.

I'd like to get your feedback on this, happy to open a PR with a potential implementation.

**Comment by muellerzr** [comment]
Hi @dbpprt, considering this is a bit more SageMaker specific this is not something we would want to maintain in `Accelerate`, and instead have someone else (or SageMaker) implement this themselves. Thanks for the idea though!
