### ISSUE TITLE
[bug] - AcceleratorState initialization in DS case ignores timeout argument

### ISSUE THREAD

**Issue by VictorSanh** [huggingface/accelerate#1129]
### System Info

```Shell
- `Accelerate` version: 0.16.0
- Platform: Linux-5.4.0-1100-gcp-x86_64-with-glibc2.17
- Python version: 3.8.13
- Numpy version: 1.23.3
- PyTorch version (GPU?): 1.12.1+cu102 (True)
- `Accelerate` default config:
        Not found
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

Essentially, the problem is that this line 
https://github.com/huggingface/accelerate/blob/639c1da8df8cdc0dfa4dd057c7f3e7e01b40f3f5/src/accelerate/state.py#L129
does not use kwargs. So even if I tune the timeout with a `InitProcessGroupKwargs(timeout=...)`, deepspeed which initialize the dist backend, doesn't have the new timeout.
I believe the line should pass the `timeout` arg conditionally on the fact that `kwargs` has it.

in my `main.py`:
```
    kwargs_handlers = [InitProcessGroupKwargs(timeout=timedelta(seconds=3_600))]
    accelerator = Accelerator(
        log_with="all",
        rng_types=["torch", "cuda", "generator"],
        gradient_accumulation_steps=GRAD_ACC_SIZE,
        kwargs_handlers=kwargs_handlers,
    )
```    

`accelerate_config.yaml`:
```compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_multinode_launcher: standard
  deepspeed_config_file: /home/victor/m4/experiments/pretraining/vloom/tr_victordebug/ds_config.json
  zero3_init_flag: true
distributed_type: DEEPSPEED
fsdp_config: {}
machine_rank: 0
main_process_ip: null
main_process_port: 29399
main_training_function: main
num_machines: 1
num_processes: 1
use_cpu: false
gpu_ids: 0,
```
`ds_config.json`:
```
{
    "bf16": {
        "enabled": false
    },
    "fp16": {
        "enabled": false,
        "auto_cast": true,
        "loss_scale": 0.0,
        "initial_scale_power": 1,
        "loss_scale_window": 1000,
        "hysteresis": 2,
        "min_loss_scale": 1
    },
    "zero_optimization": {
        "stage": 3,
        "allgather_partitions": true,
        "allgather_bucket_size": 5e8,
        "overlap_comm": false,
        "reduce_scatter": true,
        "reduce_bucket_size": "auto",
        "contiguous_gradients": true,
        "stage3_gather_16bit_weights_on_model_save": true,
        "offload_optimizer": {
            "device": "cpu"
        },
        "offload_param": {
            "device": "cpu"
        }
    },
    "gradient_clipping": "auto",
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "steps_per_print": 2000000
}
```

Deepspeed version: `Version: 0.8.2+9bfee830`

### Expected behavior

```Shell
-
```

**Comment by VictorSanh** [comment]
cc @SaulLu @stas00

**Comment by sgugger** [comment]
cc @pacman100

**Comment by pacman100** [comment]
Hello @VictorSanh, above PR should fix the above issue for DS Stages 1 and 2. However, for Stage 3, if `zero.init()` is being used, it will init dist setup without any other kwargs, below are those lines of DS repo and uses default timeout of 30 minutes. That is beyond the scope of Accelerate and needs to be fixed in DeepSpeed.

https://github.com/microsoft/DeepSpeed/blob/41a9bde14c808a75452baaa2609681316fc6912b/deepspeed/runtime/zero/partition_parameters.py#L654-L656

**Comment by VictorSanh** [comment]
gotcha thanks for explainign and fixing!

**Comment by stas00** [comment]
You mean only if the model that uses `zero.Init` is instantiated before accelerate. You should be able to set it correctly otherwise.

In other words Victor does it not work now correctly with @pacman100's fix above? I

**Comment by stas00** [comment]
I filed a feature request here: https://github.com/microsoft/DeepSpeed/issues/2927

**Comment by stas00** [comment]
another thought, @VictorSanh, as a short term gap if the above doesn't work, we can just do:

```
                if not torch.distributed.is_initialized():
                    torch.distributed.init_process_group(backend="nccl", timeout=timedelta(seconds=3*60*60)))
```

ourselves, on top of main. But let's try with Suraj's fix first.
