### ISSUE TITLE
Unscaling Wrapped optimizer making the gradient is unscaled twice

### ISSUE THREAD

**Issue by lqtrung1998** [huggingface/accelerate#113]
Hi, thank you for the useful tool. 

https://github.com/huggingface/accelerate/blob/main/src/accelerate/accelerator.py#L416-L417

I'm referring to these lines of code where the wrapped optimizer is unscaled when gradient clipping. I think the inner optimizer  should be unscaled instead. Since the scaler will mark the optimizer state based on its id, giving wrapped optimizer and unscaling it would make the gradient get unscaled but the inner optimizer is not marked as unscaled. Then when calling `accelerator.backward()`, gradient get unscaled again.

**Comment by sgugger** [comment]
That's right. Do you want to make a PR to fix this?

**Comment by lqtrung1998** [comment]
It is ok, you can fix it
