### ISSUE TITLE
Any method to resume dataloader from exact step?

### ISSUE THREAD

**Issue by AlvL1225** [huggingface/accelerate#1130]
Hi, 
For an example, if I want to resume from epoch 2 and step 200, what should I add?

Does accelerate lib have method like DistributedSampler.set_epoch() or resume from exact step?

Thanks!

**Comment by sgugger** [comment]
You don't need to do anything for the epoch, as long as you use the checkpointing from Accelerate (which will restore the RNG states). To resume from step 200 in your dataloader, we have a new `skip_first_batches` function.

**Comment by muellerzr** [comment]
Adding a note here that we need to add this to the relevant docs:

- https://huggingface.co/docs/accelerate/usage_guides/checkpoint
- https://huggingface.co/docs/accelerate/usage_guides/explore (checkpointing area)

**Comment by xiechun-tsukuba** [comment]
> You don't need to do anything for the epoch, as long as you use the checkpointing from Accelerate (which will restore the RNG states). To resume from step 200 in your dataloader, we have a new `skip_first_batches` function.

Hi @sgugger . I found that I do need to do something for the epoch when resuming checkpoints saved by Accelerate. Could you please have a check of this issue #3242  ? Thanks!
