### ISSUE TITLE
Multi-GPU inference issue - "Expected all tensors to be on the same device"

### ISSUE THREAD

**Issue by bingjie3216** [huggingface/accelerate#1149]
### System Info

```Shell
Tried multiple use cases on hugging face with V100-32G node - 8 GPUs, 40 CPU cores on the node. 

I could load the model to 8 GPUs but I could not run the inference code due to "RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:3! (when checking argument for argument mat2 in method wrapper_mm)"
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

Example code (https://huggingface.co/google/flan-ul2):
```py
from transformers import T5ForConditionalGeneration, AutoTokenizer
import torch
model = T5ForConditionalGeneration.from_pretrained("google/flan-ul2", torch_dtype=torch.bfloat16, device_map="auto")                                                                 
tokenizer = AutoTokenizer.from_pretrained("google/flan-ul2")

input_string = "Answer the following question by reasoning step by step. The cafeteria had 23 apples. If they used 20 for lunch, and bought 6 more, how many apple do they have?"                                               

inputs = tokenizer(input_string, return_tensors="pt").input_ids.to("cuda")
outputs = model.generate(inputs, max_length=200)
```

It throws:
```
File /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/torch/nn/modules/linear.py:114, in Linear.forward(self, input)
    113 def forward(self, input: Tensor) -> Tensor:
--> 114     return F.linear(input, self.weight, self.bias)

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:3! (when checking argument for argument mat2 in method wrapper_mm)
```

### Expected behavior

```Shell
the model could generate the outputs with the auto device map
```

**Comment by bingjie3216** [comment]
The following code could work well:

from transformers import T5ForConditionalGeneration, AutoTokenizer
import torch
model = T5ForConditionalGeneration.from_pretrained("azureml-models/flan-ul2/1/flan-ul2", torch_dtype=torch.bfloat16, device_map="balanced_low_0")                                                                 
tokenizer = AutoTokenizer.from_pretrained("azureml-models/flan-ul2/1/flan-ul2")


######### the following code is added to make it work################
from accelerate import init_empty_weights, dispatch_model, infer_auto_device_map, load_checkpoint_and_dispatch, load_checkpoint_in_model, dispatch_model

load_checkpoint_and_dispatch(
    model, 
    <your_model_path>, 
    device_map=model.hf_device_map, 
    offload_folder=None, 
    dtype='float16', 
    offload_state_dict=True
)

################### end #####################

input_string = "Answer the following question by reasoning step by step. The cafeteria had 23 apples. If they used 20 for lunch, and bought 6 more, how many apple do they have?"                                               

inputs = tokenizer(input_string, return_tensors="pt").input_ids.to("cuda")
outputs = model.generate(inputs, max_length=200)

print(tokenizer.decode(outputs[0]))

**Comment by sgugger** [comment]
Executing your reproducer works perfectly on my side, and I get the following answer after adding this line:
```py
tokenizer.decode(outputs[0].tolist())
```
'<pad> They have 23 - 20 = 3 apples left. They have 3 + 6 = 9 apples. Therefore, the answer is 9.</s>'

Are you sure you are using the last version of Accelerate? Can you try with a source install as well?

**Comment by bingjie3216** [comment]
@sgugger Thank you for your fast response.

The original code(the first comment) does not work with the V100-32G node (with 8 GPUs)
My second run does work(the second comment) after I added the load_checkpoint_and_dispatch() function.

Do you mean that you can run the code even with the code in the first comment on a multi-GPU node?

**Comment by sgugger** [comment]
Yes, I can run the code at the top without any problem. Could you try with a source install?

**Comment by zkx06111** [comment]
I get exactly the same error with exactly the same example script. Have you found the solution?

**Comment by Saibo-creator** [comment]
> @sgugger Thank you for your fast response.
> 
> The original code(my first comment) does not work with the V100-32G node (with 8 GPUs) My second run does work(my second comment) after I added the load_checkpoint_and_dispatch() function. However, it is not reflected on the model card (and I would suggest adding the load_checkpoint_and_dispatch function to the model card so that other people with multi-GPU could run it through in one shot)
> 
> Do you mean that you can run the code(without load_checkpoint_and_dispatch) in my first comment on a multi-GPU node?
> 
> I have been using the latest accelerate, with version as Version: 0.16.0 https://pypi.org/project/accelerate/

Not sure if this is a coincidence, I run into the same error with 4 V100. I'm going to see if running on 4 A100 will get to the same error.

**Comment by sgugger** [comment]
@serenalotreck Your code sample contains a folder I don't have access to, so I can't execute it, but
```py
checkpoint = 'hiepnh/vicuna-13B-1.1-HF-sharded'
model = AutoModelForCausalLM.from_pretrained(checkpoint, torch_dtype=torch.float16, device_map='auto')
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
inputs = tokenizer("Hello my name is", return_tensors='pt')
inputs = inputs.to(0)
output = model.generate(inputs['input_ids'])
print(tokenizer.decode(output[0].tolist()))
```
works without any issue on my side.

**Comment by serenalotreck** [comment]
@sgugger sorry about that! It's just my relative path to the repo obtained by running `git clone https://huggingface.co/hiepnh/vicuna-13B-1.1-HF-sharded with `git lfs`.

The model is too large to load into memory all at once on my machine, so I wanted to use `load_checkpoint_and_dispatch` specifically. If you replace the relative path I have there with the path to the repo I linked above, are you able to run my code as-is?

**Comment by sgugger** [comment]
@serenalotreck The command I pasted will load the model shard by shard and is the best way to load big models for inference.

**Comment by serenalotreck** [comment]
@sgugger thanks!

I'm currently running the code you posted, and it's been downloading shards for at least 5 minutes. When I run the code that I posted, which is directly basedon [this tutorial](https://huggingface.co/docs/accelerate/usage_guides/big_modeling), `load_checkpoint_and_dispatch` runs in a few seconds. I fully recognize I don't have a complete understanding of what's happening under the hood, and that potentially what's taking up time using `AutoModelForCausalLM.from_pretrained()` doesn't happen until I call `generate` in my own code, but I was wondering if you had thoughts on why what's suggested in the tutorial is faster and/or what the benefit of using the code you posted over what's in the tutorial would be?

**Comment by serenalotreck** [comment]
@sgugger Thanks for the clarification, that was helpful! I ran it a second time and it was indeed faster.

**Comment by sgugger** [comment]
By the way in your original sample of code, what is missing is the name of the modules to keep on the same device (which Transformers fetches for you):
```py
model = load_checkpoint_and_dispatch(
    model,
    '../models/vicuna-13B-1.1-HF-sharded/',
    device_map='auto',
    no_split_module_classes=["LlamaDecoderLayer"],
)
```
