### ISSUE TITLE
Question: When accelerate is used for offloading to CPU/CPUram only one core of the CPU is utilized.

### ISSUE THREAD

**Issue by Ph0rk0z** [huggingface/accelerate#1152]
I am using a project (https://github.com/oobabooga/text-generation-webui/) where transformers and the accelerate library is used to auto split the model if it doesn't fit in GPU ram. While inference is performed, only one CPU core is used at 100%. Other solutions like flexgen can peg all my cores at 100% and inference is performed much faster.

Is there a reason why this happens or a way to fix it to utilize more of the CPU? CPU is AMD ryzen, but I'm not sure if that is relevant. Environment is Ubuntu 20.04 on python 3.10.

To me this looks like a bottleneck but I'm still learning how this all goes together so correct me if I'm wrong.

**Comment by muellerzr** [comment]
cc @sgugger

**Comment by Ph0rk0z** [comment]
Well thanks for the explanation and that part does make sense. However the entire core is utilized at 100% for long periods of time. That still screams CPU bound to me.
