### ISSUE TITLE
[Feature request] load pretrained states of a baseline model to the baseline model that has been extended with extra modules

### ISSUE THREAD

**Issue by chris-opendata** [huggingface/accelerate#1159]
Here is the scenario:

With Accelerate package, I saved the states of a baseline model trained on a dataset. I now extend the baseline model to connect with a few extra modules without altering the baseline model's internal for fine-tuning with a second dataset. I would like to initialize the extended model with the saved baseline model state without facing the KeyError exception because of no states for those extended modules.
This is quite a common scenario in practice. I haven't found a way to do this with the Accelerate package. It would be useful to have this feature.

Thank you

**Comment by sgugger** [comment]
Hi @chris-opendata
This is not really in the scope of Accelerate as it has nothing to do with distributed training, mixed precision training or training loop alteration. This is also something that is super hard to do without knowing in advance the structure of the models, so having a general solution doesn't seem possible to me. Maintaining the corresponding code in Transformers, where all transformer models follow the same API is already a nightmare for instance.

**Comment by chris-opendata** [comment]
Hi sgugger,

Thank you for your speedy reply and for providing me with the possibility of my feature request.
