### ISSUE TITLE
RuntimeError: Expected to have finished reduction

### ISSUE THREAD

**Issue by sonix022** [huggingface/accelerate#116]
Hello,

I'm trying to use accelerate to train a simple two tower model (each tower being a huggingface pretrained model) on a machine with 2 GPUS.

Launch command: CUDA_VISIBLE_DEVICES=0,1 accelerate launch main.py

Right after it does the forward pass for the first batch it gives the following error:

_Traceback (most recent call last):
  File "main.py", line 79, in <module>
    batch_loss = model(**batch)
  File "/home/akson/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/akson/.local/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 692, in forward
    if self.reducer._rebuild_buckets():
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue(e.g. list, dict, iterable)._

If I remove the optimize.backward, the forward pass works properly. 

Any help with this would be appreciated.

**Comment by sonix022** [comment]
Forward Pass:

`model, optimizer, train_loader, valid_loader = accelerator.prepare(model, optimizer, train_loader, valid_loader)

#####################################################################
# Training Loop
#####################################################################
for epoch in range(epoch, args.epochs):
    logging.info(f"Training started for epoch: {epoch}")
    model.train()
    torch.set_grad_enabled(True)

    pbar = tqdm(enumerate(train_loader, 0), disable=not accelerator.is_main_process)
    loss = 0
    for step, batch in pbar:
        batch = {key: value.to(DEVICE) for key, value in batch.items()}
        batch_loss = model(**batch)
        accelerator.backward(batch_loss)
        optimizer.step()
        optimizer.zero_grad()
        loss += batch_loss
    if accelerator.is_main_process:
        print(f"\nLoss after epoch: {epoch} is = {loss/step}. best_loss = {best_loss}")`

**Comment by sgugger** [comment]
Since PyTorch suggests to set `find_unused_parameters=True`, you should do that with `DistributedDataParallelKwargs`:
```
kwargs_handlers = [DistributedDataParallelKwargs(find_unused_parameters=True)]
accelerator = Accelerator(kwargs_handlers=kwargs_handlers)
```

**Comment by sonix022** [comment]
Works great! Thanks @sgugger!

**Comment by yujianll** [comment]
@sonix022 Can I know how did `find_unused_parameters=True` solve your problem? In my case, it didn't change anything (I got the same error message).
