### ISSUE TITLE
should accelerator.save_state be under accelerator.is_main_process

### ISSUE THREAD

**Issue by better629** [huggingface/accelerate#1171]
### System Info

```Shell
Ubuntu 20.04
Nvidia GTX 3090
CUDA Version: 11.7
Torch: 1.13.1
Diffusers: 0.15.0.dev0
deepspeed: 0.8.1
xformers: 0.0.17.dev466
accelerate: 0.16.0
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

when run huggingface diffusers https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image_lora.py#L767-L771

it will hangs  when `accelerator.save_state` using DeepSpeed with multi-gpus in one node.

The question is that  if the `save_state` should be under the main_process (`is_main_process`)? I have seen the `save the model only for the main process when using the distributed training mode in pytorch`.

### Expected behavior

```Shell
-
```

**Comment by sgugger** [comment]
cc @pacman100 since it's some interaction with DeepSpeed.

**Comment by TingchenFu** [comment]
Hi, is there any update on this discussion? I try to run [the language modeling example from transformers](https://github.com/huggingface/transformers/blob/main/examples/pytorch/language-modeling/run_clm_no_trainer.py) using multi-gpus in one node with deepspeed ZeRO2  and it seems that just save with `is_main_process` is not necessary

**Comment by pacman100** [comment]
Hello, this is independent of using DeepSpeed. `accelerator.save_state` should be called without the check for `is_main_process`. Accelerate will handle it where necessary, please raise issue with diffusers to get this corrected.

**Comment by pacman100** [comment]
For example, check the official accelerate example https://github.com/huggingface/accelerate/blob/main/examples/complete_nlp_example.py#L222

**Comment by better629** [comment]
@TingchenFu

**Comment by garychan22** [comment]
do we need to pop the weights manually when custom the saving hook for accelerate.save_state?
