### ISSUE TITLE
Almost 2x increase in memory requirement for fp16 compared to accelerate 0.15.0

### ISSUE THREAD

**Issue by GenTxt** [huggingface/accelerate#1182]
I've noticed this increased memory use since accelerate 0.16 and transformers 4.26.  Loading large models @ 20b-30b worked effortlessly under accelerate 0.15 and transformers 4.25.1

Unclear why there is an almost 2x increase in memory requirement for fp16. See nvidia-smi terminal captures below.

Using ubuntu 22.04, cuda 12, bitsandbytes 37.0, torch 1.13.1, Python 3.10.6, 2x 24gig RTX GPU, 64 gigs ram, and local models (no hub)

model_name = 'models/bloom-7b1'

model = AutoModelForCausalLM.from_pretrained(model_name, device_map="auto")

tokenizer = AutoTokenizer.from_pretrained(model_name)

text = """ A funny thing happened to me on my way to the """

input_ids = tokenizer(text, return_tensors="pt").input_ids.to('cuda')

gen_tokens = model.generate(input_ids, do_sample=True, temperature=0.9, top_p=0.95, max_new_tokens=256)

gen_text = tokenizer.batch_decode(gen_tokens[:, input_ids.shape[1]:], skip_special_tokens=True)[0]
  
print(f'Result: {gen_text}')

fp16 load and generation memory used with accelerate 0.15, transformers 4.25.dev0 :

|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0 Off |                  N/A |
| 58%   63C    P2   178W / 220W |   8202MiB / 24576MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Quadro RTX 6000     On   | 00000000:03:00.0 Off |                  Off |
| 34%   44C    P2    74W / 130W |   7518MiB / 24576MiB |     44%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

Memory using **same** model above with accelerate 0.17, transformers 4.27.dev0 :

|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0 Off |                  N/A |
| 57%   64C    P2   192W / 220W |  15294MiB / 24576MiB |     87%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Quadro RTX 6000     On   | 00000000:03:00.0 Off |                  Off |
| 34%   53C    P2    94W / 130W |  14294MiB / 24576MiB |     22%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

Under accelerate 0.15 I'm able to run opt30 with a custom device_map on both gpus and cpu in fp16

Running same map with accelerate 0.16+ = OOM 

load_in_8bit=True memory use is approximately the same for both.

Is there a better way to load large models with accelerate 0.17 that uses memory more efficiently as per

accelerate 0.15?

Thanks

**Comment by sgugger** [comment]
This is very likely due to the fixes we did in loading state dict inside the models to get aligned with PyTorch: we used to take the dtype of the checkpoint, but now we respect the dtype of the model like PyTorch does.

To use the model in float16, you need to pass along `torch_dtype=torch.float16` in your call to `from_pretrained`.

**Comment by GenTxt** [comment]
Thanks. That was the missing piece of the puzzle. Accelerate 17.1 and transformers 4.27.dev working with custom device maps. No more OOM.

Thanks for the ongoing work on these essential libraries. Looking forward to Llama 4bit integration. Have it currently working with Llama 65b 4bit

Cheers
