### ISSUE TITLE
Question regarding launching accelerate via interactive script

### ISSUE THREAD

**Issue by Michael-H777** [huggingface/accelerate#1185]
Hello, 

i have been using `accelerate launch main.py` in terminal to utilize the many features provided in the package. 

However, my lab manager had asked me to write a frontend for the training script. The plan is to use javascript (specifically React and Flask) and build a simple UI with a 'train' button on it (among other things). 

My questions is, I can get the train button to trigger a function in the backend, but how to I have the function perform the `accelerate launch main.py` function? 

I would like to monitor the training progress, is there anyother way to do it other than using the `subprocess.popen` ? 

many thanks. 
Michael

**Comment by muellerzr** [comment]
@Michael-H777 you can call accelerate's launcher directly with python, however you'd face the same problem that you would have if you ran `torchrun` in a python script, `subprocess` would be called underneath the hood
regardelss. *Technically* it can be done by importing the argparser and having everything aligned, but we do not explicitly condone this behavior.

**Comment by Michael-H777** [comment]
Hi, thanks for commenting. 

I took a quick look at the entry point for `accelerate launch xxx` in [src/command/launch.py](https://github.com/huggingface/accelerate/blob/main/src/accelerate/commands/launch.py?plain=1#L921). if i just import the `launch_command` function and modify the `args` parameter accordingly, would it achieve the same effect? 

I can have the UI read from a log file to achieve the monitoring feature.

**Comment by muellerzr** [comment]
Yes

**Comment by Michael-H777** [comment]
ok, thank you for confirming!
