### ISSUE TITLE
NCCL error when using accelerate with megatron.

### ISSUE THREAD

**Issue by junjie18** [huggingface/accelerate#1186]
Thanks for your great work.
Here is my minimal reproducible example:
``` 
# example.py
from accelerate import Accelerator
if __name__ == "__main__":
    accelerator = Accelerator()
    with accelerator.main_process_first(): 
        print(accelerator.state)
```

I run the `example.py` with following command, everything **works fine**.
```
accelerate launch --num_processes 4 --num_machines 1  example.py
```

But when I add `--use_megatron_lm` to the above command, following error occurs(set `--num_processes 1`, the error still occurs):
```
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    with accelerator.main_process_first():
  File "~/anaconda3/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "~/workspace/accelerate/src/accelerate/accelerator.py", line 712, in main_process_first
    with self.state.main_process_first() as c:
  File "~/anaconda3/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "~/accelerate/src/accelerate/state.py", line 681, in main_process_first
    with PartialState().main_process_first() as c:
  File "~/anaconda3/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "~/accelerate/src/accelerate/state.py", line 324, in main_process_first
    yield from self._goes_first(self.is_main_process)
  File "~/accelerate/src/accelerate/state.py", line 298, in _goes_first
    self.wait_for_everyone()
  File "~/accelerate/src/accelerate/state.py", line 292, in wait_for_everyone
    torch.distributed.barrier()
  File "~/anaconda3/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 3145, in barrier
    work = default_pg.barrier(opts=opts)
RuntimeError: NCCL error in: ../torch/csrc/distributed/c10d/NCCLUtils.hpp:121, unhandled cuda error, NCCL version 2.14.3
ncclUnhandledCudaError: Call to CUDA function failed.
Last error:
Cuda failure 'the provided PTX was compiled with an unsupported toolchain.'
```

My Enviroment
```
torch == 1.13.1+cu117
cuda == 11.7
megatron (official git, python setup.py develop)
torch.cuda.nccl.version() is 2.14.3
```

**Comment by sgugger** [comment]
cc @pacman100

**Comment by Zhangwenyao1** [comment]
> Thanks for your great work. Here is my minimal reproducible example:
> 
> ```
> # example.py
> from accelerate import Accelerator
> if __name__ == "__main__":
>     accelerator = Accelerator()
>     with accelerator.main_process_first(): 
>         print(accelerator.state)
> ```
> 
> I run the `example.py` with following command, everything **works fine**.
> 
> ```
> accelerate launch --num_processes 4 --num_machines 1  example.py
> ```
> 
> But when I add `--use_megatron_lm` to the above command, following error occurs(set `--num_processes 1`, the error still occurs):
> 
> ```
> Traceback (most recent call last):
>   File "example.py", line 6, in <module>
>     with accelerator.main_process_first():
>   File "~/anaconda3/lib/python3.8/contextlib.py", line 113, in __enter__
>     return next(self.gen)
>   File "~/workspace/accelerate/src/accelerate/accelerator.py", line 712, in main_process_first
>     with self.state.main_process_first() as c:
>   File "~/anaconda3/lib/python3.8/contextlib.py", line 113, in __enter__
>     return next(self.gen)
>   File "~/accelerate/src/accelerate/state.py", line 681, in main_process_first
>     with PartialState().main_process_first() as c:
>   File "~/anaconda3/lib/python3.8/contextlib.py", line 113, in __enter__
>     return next(self.gen)
>   File "~/accelerate/src/accelerate/state.py", line 324, in main_process_first
>     yield from self._goes_first(self.is_main_process)
>   File "~/accelerate/src/accelerate/state.py", line 298, in _goes_first
>     self.wait_for_everyone()
>   File "~/accelerate/src/accelerate/state.py", line 292, in wait_for_everyone
>     torch.distributed.barrier()
>   File "~/anaconda3/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 3145, in barrier
>     work = default_pg.barrier(opts=opts)
> RuntimeError: NCCL error in: ../torch/csrc/distributed/c10d/NCCLUtils.hpp:121, unhandled cuda error, NCCL version 2.14.3
> ncclUnhandledCudaError: Call to CUDA function failed.
> Last error:
> Cuda failure 'the provided PTX was compiled with an unsupported toolchain.'
> ```
> 
> My Enviroment
> 
> ```
> torch == 1.13.1+cu117
> cuda == 11.7
> megatron (official git, python setup.py develop)
> torch.cuda.nccl.version() is 2.14.3
> ```

I meet same issue, have you solved it?
