### ISSUE TITLE
deepspeed bug  or accelerate bug ?    In a multi-machine and multi-gpu environment, each machine is running, but the log has not been refreshed after more than 30 hours, but the gpu of each machine is running

### ISSUE THREAD

**Issue by bestpredicts** [huggingface/accelerate#1190]
### System Info

```Shell
accelerate version 0.16.0, cent os 7 ,python3.9, torch2.0, accelrate config


compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_hostfile: /xxxx/xxxx/hostfile.txt
  deepspeed_multinode_launcher: pdsh
  gradient_accumulation_steps: 1
  gradient_clipping: 1.0
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: true
  zero3_save_16bit_model: true
  zero_stage: 3
distributed_type: DEEPSPEED
downcast_bf16: 'no'
dynamo_backend: 'NO'
fsdp_config: {}
machine_rank: 0
main_process_ip: 10.201.112.16
main_process_port: 8008
main_training_function: main
megatron_lm_config: {}
mixed_precision: bf16
num_machines: 4
num_processes: 32
rdzv_backend: static
same_network: true
use_cpu: false
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

1. I run the scripts in transformers/example/language_models/pytroch/run_clm_no_trainer.py , I chose the bloom 7B model as pretained model,  use pdsh as deepspeed launcher   to run 4 machine  and 32 gpus, 
I observed the log, and it was normal for the first 32 hours, and a loss was printed every two minutes, but after 32 hours, the log was not refreshed, and I continued to observe for another 6 hours and it was still the same. . .

### Expected behavior

```Shell
The log is updated every two minutes until the end
```

**Comment by sgugger** [comment]
cc @muellerzr for logging and @pacman100 for DeepSpeed.

**Comment by pacman100** [comment]
Hello @bestpredicts,  based on your comment `I observed the log, and it was normal for the first 32 hours, and a loss was printed every two minutes,` it feels like DeepSpeed is running fine. Can you provide a minimal example that we can run on our end because there is no error in this case? I have run simple `complete_nlp_example.py` in multi-node using DeepSpeed and it works fine.

**Comment by pacman100** [comment]
Hello, see this https://github.com/huggingface/accelerate/issues/1317#issuecomment-1521636997. I'm able to run properly the deepspeed multi-node training

**Comment by pacman100** [comment]
Based on the pointers from Stas who has experience with long-running training runs, few things to try:
1. run top and py-spy to check whether the training is actually happening
2. If it is hanging then it depends where. If it's hanging in any comms or a barrier, then typically after 30min they would time out. if it's hanging in somewhere in user land it could be forever.
