### ISSUE TITLE
Question: Layer Dropout with distributed training

### ISSUE THREAD

**Issue by ruizhecao96** [huggingface/accelerate#1191]
Normally in DDP, the model is required all trainable parameters to receive grad and are used to produce the loss. But if I apply layer dropout in the training process, e.g. randomly replacing one layer with residual connection, the parameters of this layer will not receive the grad and the training turns to error. Do you have any idea to solve this problem or will you fix it in the future?

**Comment by sgugger** [comment]
I am not sure what you mean here, do you have an example of code that fails? All Transformer models use dropout during training and we have nor problem running it distributed.

**Comment by ruizhecao96** [comment]
Thank you for your reply. The layer drop idea is from the paper "Deep Networks with Stochastic Depth". Normally when an entire layer is dropped, the parameter of this layer will not receive grad. But now I have solved the problem by setting find_unused_parameter=True and adding DeepSpeedPlugin in accelerator.
