### ISSUE TITLE
model parallel

### ISSUE THREAD

**Issue by beautifull4frank** [huggingface/accelerate#1193]
Hello, I just successfully run "summarize_rlhf/trlx_gptj_text_summarization.py", but I am not sure whether  it is implemented using model parallel or not.  I have to run large size gpt3, so I need to seperate the huge mode into several gpus  using model paralled.

**Comment by sgugger** [comment]
Maybe ask on the repo where you picked that example? I have no idea what the script "summarize_rlhf/trlx_gptj_text_summarization.py" is so can't really help.

**Comment by beautifull4frank** [comment]
cool man, I am so sorry, I got a mistake, I used trlx to train a chat bloom, I put my issue in wrong place.  I success train the bloom560m. But , the trlx uses accelerate to train huge  chat gpt model.  I am just not sure whether accelerate can use model parallel to train 300g chat bloomz.

**Comment by lifefeel** [comment]
> cool man, I am so sorry, I got a mistake, I used trlx to train a chat bloom, I put my issue in wrong place. I success train the bloom560m. But , the trlx uses accelerate to train huge chat gpt model. I am just not sure whether accelerate can use model parallel to train 300g chat bloomz.

I wondered the same thing when I was using trlx. I found the following in the Accelerate documentation ([Handling big models for inference](https://huggingface.co/docs/accelerate/v0.18.0/en/usage_guides/big_modeling#handling-big-models-for-inference))


> The model parallelism used when your model is split on several GPUs is naive and not optimized, meaning that only one GPU works at a given time and the other sits idle.

It seems that model parallelism is still partially supported.

**Comment by sgugger** [comment]
We have never claimed supporting pipeline parallelism (where there is a schedule that split your batches in micro-batches and make sure all GPUs work at the same time) only sequential model parallelism (where the GPU1 waits for GPU 0 to finish and so forth). This is still quite fast if you batch your inputs together.

**Comment by lifefeel** [comment]
> We have never claimed supporting pipeline parallelism (where there is a schedule that split your batches in micro-batches and make sure all GPUs work at the same time) only sequential model parallelism (where the GPU1 waits for GPU 0 to finish and so forth). This is still quite fast if you batch your inputs together.

Thanks for the detailed explanation 😄
