### ISSUE TITLE
Native multi-GPU training requires pytorch>=1.9.1

### ISSUE THREAD

**Issue by sailist** [huggingface/accelerate#1199]
### System Info

```Shell
I encountered an error while running a multi-GPU training program using accelerate. The `accelerate launch scripts.py` raise an NotImplementException


Native multi-GPU training requires pytorch>=1.9.1
```

 - Have the developers abandoned support for PyTorch with version lower than that? 
 - If there are any workarounds that can be used to continue using PyTorch 1.8 with accelerate to use multi-GPU training.

```
torch                    1.8.1+cu101
accelerate               0.16.0
```
```


### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

In any environment with pytorch version lower than 1.9.1

### Expected behavior

```Shell
Run without any exception.
```

**Comment by muellerzr** [comment]
Hi, it's the CLI that requires >=1.9.1, please use `torch.distributed.launch` directly through the CLI to launch the code using Accelerate

**Comment by Chen-Suyi** [comment]
> Hi, it's the CLI that requires >=1.9.1, please use `torch.distributed.launch` directly through the CLI to launch the code using Accelerate

Does it mean accelerate does not support torch with version < 1.9.1?

**Comment by muellerzr** [comment]
Just `accelerate launch` specifically on multi GPU. You can launch with `torchrun` and use accelerate code that way
