### ISSUE TITLE
Can't send the values of int to device

### ISSUE THREAD

**Issue by theschnitz** [huggingface/accelerate#12]
My training data looks like:

src_image, target_image, src_camera, target_camera, src_camera_idx, target_camera_idx

Where src_camera_idx, target_camera_idx are integers

When I try to apply accelerate I get the following error:
TypeError: Can't send the values of type <class 'int'> to device cuda:0, only of nested list/tuple/dicts of tensors or objects having a `to` method.

We don't need to send the integers to the device. Perhaps instead of raising an error here, you can simply skip the items that cannot be moved to device? Or at least give me the option to skip them if I know my data has such objects.

**Comment by theschnitz** [comment]
@sgugger

**Comment by sgugger** [comment]
Oh indeed, I did not take that case into account. Not raising an error seems a better option.
Will send a fix later this evening or tomorrow morning!

**Comment by theschnitz** [comment]
Awesome, thanks
