### ISSUE TITLE
tensorboard dir cannot be set

### ISSUE THREAD

**Issue by lierik** [huggingface/accelerate#1205]
### System Info

```Shell
Hello, thank you for providing this awesome tools to further finetune huggingface model.
I follow the examples/by_features/megatron_lm_gpt_pretraining to train the my own gpt model. But I found that if I set the --report_to into "tensorboard", the tensorboard_dir arg cannot be set and always be none.

--tensorboard_dir is init in megatron_initialize part, which call parse_args imported from megatron. But the args set from accelerate are not passed into init func. 

refer to line841 in megatron_lm.py
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

accelerate launch --config_file megatron_megatronlm_config.yaml \
accelerate/examples/by_feature/megatron_lm_gpt_pretraining.py \
--config_name $MODELPATH \
--tokenizer_name $MODELPATH \
--dataset_name wikitext \
--dataset_config_name wikitext-2-raw-v1 \
--block_size 512 \
--learning_rate 5e-5 \
--per_device_train_batch_size 12 \
--per_device_eval_batch_size 12 \
--num_train_epochs 1 \
--with_tracking \
--report_to tensorboard \
--output_dir "awesome_model"

### Expected behavior

```Shell
swin_backbone_type .............................. tiny
  tensor_model_parallel_size ...................... 1
  tensorboard_dir ................................. None
  tensorboard_log_interval ........................ 1
  tensorboard_queue_size .......................... 1000
  titles_data_path ................................ None

Here is the log from consul.
```

**Comment by sgugger** [comment]
cc @muellerzr

**Comment by lierik** [comment]
> @lierik you need to set `--output_dir` to where you want the tensorboard logs to be, as shown here: https://github.com/huggingface/accelerate/blob/main/examples/by_feature/megatron_lm_gpt_pretraining.py#L254-L256
> 
> So:
> 
> ```python
> accelerate launch megatron_lm_gpt_pretraining.py --output_dir somedirtobeused --report_to tensorboard
> ```

OK, got it, thanks, i miss this file
