### ISSUE TITLE
unwrap function not support 'torch._dynamo.eval_frame.OptimizedModule'

### ISSUE THREAD

**Issue by Rapisurazurite** [huggingface/accelerate#1207]
### System Info

```Shell
- `Accelerate` version: 0.17.1
- Platform: Linux-5.4.0-139-generic-x86_64-with-glibc2.27
- Python version: 3.9.1
- Numpy version: 1.23.5
- PyTorch version (GPU?): 2.0.0 (True)
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: DEEPSPEED
        - mixed_precision: no
        - use_cpu: False
        - num_processes: 2
        - machine_rank: 0
        - num_machines: 1
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - deepspeed_config: {'gradient_accumulation_steps': 1, 'gradient_clipping': 1.0, 'offload_optimizer_device': 'none', 'offload_param_device': 'none', 'zero3_init_flag': True, 'zero_stage': 2}
        - fsdp_config: {}
        - megatron_lm_config: {}
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - dynamo_config: {}
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

accelerator.unwrap_model(self.model) should return a "torch.nn.Module", but a 'torch._dynamo.eval_frame.OptimizedModule'

### Expected behavior

```Shell
return a "torch.nn.Module"
```

**Comment by muellerzr** [comment]
cc @sgugger or I can look next week

**Comment by sgugger** [comment]
Not even sure if the API exists in PyTorch. Will ask.

**Comment by pacman100** [comment]
As per the docs, `model.state_dict()` should work as expected for saving the model which wouldn't need unwrapping the model.

**Comment by sgugger** [comment]
True but this method is also used to put the model back in its original state (it can remove the mixed precision wrappers for instance).

**Comment by csarron** [comment]
this will break the code like `generated_tokens = accelerator.unwrap_model(model).generate(batch)`, it gave errors like: 'DistributedDataParallel' object has no attribute 'generate', see https://github.com/huggingface/transformers/issues/18974.

I'm able to bypass the issue by setting the dynamo_backend to no
`accelerate launch --dynamo_backend=no`

**Comment by ross-Hr** [comment]
I also face the bug
