### ISSUE TITLE
Feature request: logger in terminal and log

### ISSUE THREAD

**Issue by iRuizeWu** [huggingface/accelerate#1221]
### System Info

```Shell
- `Accelerate` version: 0.17.0
- Platform: Linux-5.4.0-117-generic-x86_64-with-glibc2.17
- Python version: 3.8.13
- Numpy version: 1.24.2
- PyTorch version (GPU?): 1.12.1+cu113 (True)
- `Accelerate` default config:
        Not found
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

I want to add a handler because I want to show it in the terminal and save it into log files.
But it says 'MultiProcessAdapter' object has no attribute 'addHandler'
The code is below.
```python
log_format = '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
logger = get_logger(__name__)
file_handler = logging.FileHandler("mylogs.log")
formatter = logging.Formatter(log_format)
file_handler.setFormatter(formatter)

# Don't forget to add the file handler
logger.addHandler(file_handler)
logger.info("I am a log from project")
```

### Expected behavior

```Shell
logger in terminal and log
```

**Comment by bcol23** [comment]
Currently using `logger.logger.addHandler(file_handler)` should work.
