### ISSUE TITLE
Using only some of the GPUs at a time

### ISSUE THREAD

**Issue by thisis-nkul** [huggingface/accelerate#123]
Hello! First of all, thanks for making this great library for effortless distributed training.
I wanted to ask if there is any way to run the training on only a subset of GPUs (eg: 3 out of 8) ?

If there isn't, is it planned for the future?? 

Thank You.

**Comment by LysandreJik** [comment]
Hello! This should be managed with CUDA directly, with the `CUDA_VISIBLE_DEVICES` environment variable:
```
CUDA_VISIBLE_DEVICES=0,1,2,3 python ...
```

**Comment by LysandreJik** [comment]
See https://developer.nvidia.com/blog/cuda-pro-tip-control-gpu-visibility-cuda_visible_devices/
