### ISSUE TITLE
invalid `deepspeed_plugin.zero_stage` when using ds_config file

### ISSUE THREAD

**Issue by stas00** [huggingface/accelerate#1231]
### System Info

```Shell
`accelerate@main`
```

### Reproduction

when using a stage 3 config with ds_config file, this returns `2` instead of expected `3`:
```
    print(f"STAGE {AcceleratorState().deepspeed_plugin.zero_stage}")
```

I think this issue comes from:

https://github.com/huggingface/accelerate/blob/6e4e8702030222979d7ff54a2d8b0406cdf96393/src/accelerate/utils/dataclasses.py#L489-L490

why does it use the default of 2? this would be incorrect in 3 out of 4 cases as there are 4 stages.

If `zero_stage` isn't explicitly passed there is the config file to derive this value from. Bur perhaps you'd want to use this API to explicitly express the value that was passed via `zero_stage` - so the other possibility is to return `None` if it wasn't set by the API or the env var.

But the default should definitely not be `2`. 

@pacman100

**Comment by pacman100** [comment]
Hello, the default is ZeRO Stage 2 as it will be the best tradeoff in terms of speed and decreasing memory usage.

The above PR should resolve the issue when using ds_config file

**Comment by stas00** [comment]
FWIW, Stage 1 is faster than Stage 2.

Why not let user specify the stage they want - I think the user needs to understand what they are doing. One gets the most benefits from Deepspeed when they make an informed choice.
