### ISSUE TITLE
[feature request] api to get deepspeed zero stage

### ISSUE THREAD

**Issue by stas00** [huggingface/accelerate#1232]
I'm struggling to figure out how to get the zero stage from `AcceleratorState().deepspeed_plugin` - my first attempt [failed](https://github.com/huggingface/accelerate/issues/1231) - would it be possible to provide a public API to return the stage regardless of which of the 2 config styles were used?

Thanks a lot

@pacman100

**Comment by pacman100** [comment]
Hello Stas, please let us know if the above PR serves the purpose.  `AcceleratorState().deepspeed_plugin.zero_stage` should now work properly when using ds_config
