### ISSUE TITLE
If I set the deepspeed_config.zero_stage: 3, how should I save my model ?

### ISSUE THREAD

**Issue by lyx564** [huggingface/accelerate#1238]

**Comment by lyx564** [comment]
I used the following code but the saved model files missed the pytorch_model-00001-of-00003.bin
```
accelerator.wait_for_everyone()
unwrapped_model = accelerator.unwrap_model(model)
unwrapped_model.save_pretrained(save_dir, save_function=accelerator.save, state_dict=accelerator.get_state_dict(model))
```

<img width="747" alt="image" src="https://user-images.githubusercontent.com/52693012/227166644-33e0ae15-3437-4373-aca3-60be4c12b40d.png">

**Comment by Salierioo** [comment]
Have you solve the problem? I get the same problem.

**Comment by Salierioo** [comment]
> > Have you solve the problem? I get the same problem.
> 
> I solved the problem by modifying the transformer source code. I remove the line of code that deletes model files in the save_pretrained function.

Thank you! I have solved the problem after removing the code.
