### ISSUE TITLE
It is SUPER unclear how to run multi-node distributed training with HuggingFace Accelerate

### ISSUE THREAD

**Issue by adivekar-utexas** [huggingface/accelerate#1242]
Hi! I quite like `accelerate`, it's a great platform which I've integrated into a few of our internal systems at Amazon (for single-node training)

The docs for launching from a Jupyter notebook are called "Launching **Multi-Node** Training from a Jupyter Environment": https://huggingface.co/docs/accelerate/basic_tutorials/notebook

...however, there's no mention of using multiple nodes anywhere? The docs just describe running on multiple GPUs within a single node from Jupyter (useful on its own, but not what the article title advertises!).

PyTorch has torchrun and other ways to run multi-node: https://lambdalabs.com/blog/multi-node-pytorch-distributed-training-guide

Any setup I must do? For context, I have a 8 machines used for training.

**Comment by adivekar-utexas** [comment]
To clarify: I would like to run multi-node training from my Jupyter notebook

**Comment by sgugger** [comment]
Thanks for flagging, the doc is wrong, this is for multi-GPU but on a single node. I don't think you can launch a multi-node distributed training from a notebook.

cc @muellerzr

**Comment by adivekar-utexas** [comment]
There's probably a way to do it without Ray, but my knowledge of distributed computing protocols is lacking here.

**Comment by muellerzr** [comment]
@adivekar-utexas yes, it is. See this issue here: https://github.com/huggingface/accelerate/issues/1185

**Comment by muellerzr** [comment]
You can certainly make a feature request ;) Though the notebook_launcher is very limited in its capabilities, hence why there's not really much there to do. Parser args can actually be made into a dataclass to get though, see what I do here: https://github.com/huggingface/accelerate/blob/main/src/accelerate/commands/launch.py#L598 + https://github.com/huggingface/accelerate/blob/main/src/accelerate/utils/launch.py#L46

**Comment by muellerzr** [comment]
Also @adivekar-utexas what you'll notice there is that we lightly wrap around `torchrun` for many things :)

**Comment by pacman100** [comment]
Hello @adivekar-utexas, happy to see you here (hope you remember me 😁) and thrilled to know that Amazon has started using it internally 🚀.

 with respect to using Accelerate with Ray, below are few PRs/issues that might provide more insight (I haven't done deep dive into this though):
1. https://github.com/huggingface/accelerate/pull/1123
2. https://github.com/ray-project/ray/pull/33269
3. https://github.com/CarperAI/trlx/pull/386

**Comment by adivekar-utexas** [comment]
Hey @pacman100, great to hear from you again! Yes I do remember you 😄 I've been pushing Accelerate internally as a way to fine-tune on huge datasets (which there is no shortage) and running multi-node is one of the main difficulties. 

Thanks for the links to [AccelerateTrainer](https://docs.ray.io/en/master/train/api/doc/ray.train.huggingface.accelerate.AccelerateTrainer.html#ray.train.huggingface.accelerate.AccelerateTrainer), which I see was recently merged in the Ray 3.0.0.dev0 branch. I was planning on implementing a very similar class and now I'm glad I don't have to.

**Comment by saiajaym** [comment]
Hi, 
I currently have a node with all the data setup. Do I need to copy this data to all the instances that I wanna train on?
