### ISSUE TITLE
Why default to use DataLoaderShard, which extremely slow for large world_size?

### ISSUE THREAD

**Issue by li-yi-dong** [huggingface/accelerate#1245]
### System Info

```Shell
v0.17.1
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

When passing `DataLoader` to `accelerator.prepare`, it would change the `DataLoader` into `DataLoaderShard` by default.

`DataLoaderShard` would only read data from rank 0 and distribute the data to other ranks. When the world_size is big and there are multiple nodes, this approach would be extremely slow.

```python
model_to_train, optimizer, train_dataloader, lr_scheduler = \
    accelerator.prepare(model_to_train, optimizer, train_dataloader, lr_scheduler)
```

### Expected behavior

```Shell
At least notify users this may impact the training speed. Otherwise it is quite hard to locate.
```

**Comment by sgugger** [comment]
`DataLoaderShard` is just a wrapper class, it's not slow or fast, it just puts the data on the right device and keeps track of the last batch. It's impossible for us to know what might be slower in your case without knowing the script you run for training.

**Comment by li-yi-dong** [comment]
@sgugger Hi👋 
Sorry, the problem is not due to `DataLoaderShard`. It's `DataLoaderDispatcher`.

I'm running https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image.py with DeepSpeed. The `Dataset` is a customized `IterableDataset`. The dataset would yield different partition of data on different rank. And I pass the Dataloader to `accelerator.prepare` just as in the `train_text_to_image.py`.

As described in here:
```
  dispatch_batches (`bool`, *optional*):
      If set to `True`, the dataloader prepared by the Accelerator is only iterated through on the main process
      and then the batches are split and broadcast to each process. Will default to `True` for `DataLoader` whose
      underlying dataset is an `IterableDataset`, `False` otherwise.
```
`Accelerator` would default to only read data on rank 0 with `IterableDataset` .  It used to be fine with older version of accelerate for my case  because `Accelerator._prepare_deepspeed` skipped `_prepare_dataloader`(Maybe carelessly).
```
if deepspeed_plugin.deepspeed_config["train_micro_batch_size_per_gpu"] == "auto":
            result = [
                self._prepare_one(obj, first_pass=True) if isinstance(obj, torch.utils.data.DataLoader) else obj
                for obj in args
            ]
```
But in newer version you guys fixed it. The above code changes into:
```
if deepspeed_plugin.deepspeed_config["train_micro_batch_size_per_gpu"] == "auto" or is_dataloader_present:
            result = [
                self._prepare_one(obj, first_pass=True) if isinstance(obj, torch.utils.data.DataLoader) else obj
                for obj in args
            ]
```
But unfortunately, for me, my training slows down dramatically without changing anything other than upgraded accelerate.
By moving Dataloader out from `accelerator.prepare`, the speed becomes normal again. 

So, maybe, a better documentation may help others.

**Comment by pacman100** [comment]
Hello @li-yi-dong, could you please let us know where in the documentation or which part needs clarity which could have avoided above issue?

**Comment by li-yi-dong** [comment]
> Hello @li-yi-dong, could you please let us know where in the documentation or which part needs clarity which could have avoided above issue?

Maybe here https://huggingface.co/docs/accelerate/v0.18.0/en/package_reference/accelerator#accelerate.Accelerator.prepare
