### ISSUE TITLE
Scripts Converting Megatron_T5 to HF_T5 

### ISSUE THREAD

**Issue by lierik** [huggingface/accelerate#1252]
Hello guys, could you please provide any script that can convert megatron t5 into hf t5 model? Especially when TP and PP is not equal to 1.

**Comment by sgugger** [comment]
cc @pacman100

**Comment by pacman100** [comment]
Hello, this is not currently available and we need considerable interest from users to prioritise it.

**Comment by lierik** [comment]
Got it, thanks!
