### ISSUE TITLE
How to use deepspeed and megatron in accelerate simultaneously?

### ISSUE THREAD

**Issue by Wangpeiyi9979** [huggingface/accelerate#1256]
### Config Info

With accelerate, can we use both deepspeed (Data Parallelism) and megatron (Model Parallelism) simultaneously?

I found that when configuring accelerate config, deepspeed and megatron-LM are mutually exclusive (If I choose yes to use DeepSpeed, the option of using megatron-LM will not appear).
![image](https://user-images.githubusercontent.com/42565075/228117650-c8086f8c-152d-4a2b-b1f1-2bb986e6d381.png)

I also found that the [documentation](https://huggingface.co/docs/accelerate/usage_guides/deepspeed) only mentions accelerate + deepspeed or accelerate + Megatron-LM separately, but not accelerate+ megatron+ deepspeed.

**Comment by pacman100** [comment]
Hello @Wangpeiyi9979, as you mentioned, both integrations are mutually exclusive ways of supporting LLM training. Therefore, both DeepSpeed and Megatron-LM integrations can't be used simultaneously. Megatron-LM integration does support ZeRO Stage-2, so benefits of DeepSpeed are already available in it. 

https://github.com/microsoft/Megatron-DeepSpeed manages to integrate best of both worlds, but that isn't currently integrated in Accelerate.

**Comment by Wangpeiyi9979** [comment]
Thank you very much. Will Accelerate integrate the Megatron-DeepSpeed in the future?
