### ISSUE TITLE
`accelerator.gather` silently fails if any item in the list is not a tensor

### ISSUE THREAD

**Issue by stas00** [huggingface/accelerate#1263]
### System Info

```Shell
main
```

### Reproduction

```
$ cat test.py
import torch
from accelerate import Accelerator

accelerator = Accelerator()
process_tensor = torch.tensor([accelerator.process_index], device="cuda")
gathered_tensor, i = accelerator.gather((process_tensor, 1))
```

run:

```
$ python -m torch.distributed.run --nproc_per_node=2 test.py 
WARNING:__main__:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
Traceback (most recent call last):
  File "test.py", line 6, in <module>
  File "test.py", line 6, in <module>
        gathered_tensor, i = accelerator.gather((process_tensor, 1))gathered_tensor, i = accelerator.gather((process_tensor, 1))

ValueErrorValueError: : not enough values to unpack (expected 2, got 0)not enough values to unpack (expected 2, got 0)
```

### Expected behavior

`accelerator.gather` doesn't validating the incoming argument and fails with a misleading error that doesn't tell the user what's wrong.

Expecting for it to tell the user that one or more items on the list aren't tensors and not return an empty list.

Please note that it works fine on a single gpu, so the test needs to be 2 gpus or more.

Thank you.

**Comment by sgugger** [comment]
The error is there, but it looks like `torchrun` (or `torch.distributed.run`) ignores TypeErrors... I'll change the error to a `ValueError`, which will provide the (more helpful) error message
```
ValueError: Can't apply _gpu_gather_one on object of type <class 'int'>, only of nested list/tuple/dicts of objects that satisfy is_torch_tensor.
```

**Comment by stas00** [comment]
That works, if you think the user can connect the dots as this is not the function the user calls. But hopefully they will figure it out from the traceback.

I think checking the inputs are all tensors is probably expensive, since it's the same function called again and again and this overhead will add up.

So your proposal works for me.

Thank you, Sylvain

**Comment by gebalassa** [comment]
> The error is there, but it looks like `torchrun` (or `torch.distributed.run`) ignores TypeErrors... I'll change the error to a `ValueError`, which will provide the (more helpful) error message
> 
> ```
> ValueError: Can't apply _gpu_gather_one on object of type <class 'int'>, only of nested list/tuple/dicts of objects that satisfy is_torch_tensor.
> ```

Excuse me for reviving this issue, but how was the "ValueError" being reached in the first place? Shouldn't it have failed in  "_gpu_gather_one" when trying to check for the "ndim" property on an integer (1)? The error message makes no sense to me.
