### ISSUE TITLE
accelerate can't support checkpoint like Trainer API

### ISSUE THREAD

**Issue by liangwq** [huggingface/accelerate#1265]
1.checkpoint save hard
2.can't limit how much checkpoint save 
3.continuing to peft, the support for lora breakpoint rerun is not good
@xianbaoqian

**Comment by muellerzr** [comment]
Re; 1 and 2, I don't quite follow.

For 1, it's `accelerator.save_state("some_folder_name")`

For 2:
```python
from accelerate.utils import ProjectConfiguration
config = ProjectConfiguration(automatic_checkpoint_naming=True, total_limit=SOME_LIMIT)
accelerator = Accelerator(project_configuration=config)
```

For 3, don't quite follow there. Are you using `load_state` to restore the RNG states?
