### ISSUE TITLE
Why do we need to cast fp16 to float in `get_state_dict()` while saving?

### ISSUE THREAD

**Issue by fnshwi** [huggingface/accelerate#1269]
Version: 0.18.0

When I use DeepSpeed ZeRO Stage-3 to save all model shards, I follow this:
```
unwrapped_model = accelerator.unwrap_model(model)
unwrapped_model.save_pretrained(
    args.output_dir,
    is_main_process=accelerator.is_main_process,
    save_function=accelerator.save,
    state_dict=accelerator.get_state_dict(model),
)
```
However, this would save the fp16 model as fp32 version, since in `get_state_dict` we have:
https://github.com/huggingface/accelerate/blob/v0.18.0/src/accelerate/accelerator.py#L2523-L2526
```
if state_dict is not None:
    for k in state_dict:
        if state_dict[k].dtype == torch.float16:
            state_dict[k] = state_dict[k].float()
```
I wonder why we need this, seems fp16 is better or at least an option.

**Comment by pacman100** [comment]
Hello @fnshwi, model weights being available in  FP32 are important from an interoperability and exportability point of view. As you mentioned, maybe an option to not do it would serve your purpose.
