### ISSUE TITLE
why model.generate() is much slower than forward?

### ISSUE THREAD

**Issue by wangskyone** [huggingface/accelerate#1271]
when I use code below
` accelerator.unwrap_model(model).generate`

The inference speed of the model becomes very slow

**Comment by sgugger** [comment]
`generate` executes multiple forward passes to generate a full sentence, that's probably the reason.

**Comment by wangskyone** [comment]
I have another question，
when I use
`pred = accelerator.unwrap_model(net).generate(**batch, max_newtokens=100, topk=2, early_stopping=True)`
got
`ValueError: The following `model_kwargs` are not used by the model: ['topk', 'max_newtokens'] (note: typos in the generate arguments will also show up in this list)
`
I can only set `max_length`
