### ISSUE TITLE
FP8 causes exception: name `te` not defined

### ISSUE THREAD

**Issue by JulesGM** [huggingface/accelerate#1276]
### System Info

```Shell
Accelerate 0.18.0
Transformers 4.27.4
Torch 2.0.0
```

### Reproduction

When launching with `mixed_precision=fp8` in the config_file, I get

![name `te` is not defined](https://i.imgur.com/JX6HeI0.png)

**Comment by muellerzr** [comment]
Hi @JulesGM, this should be solved via https://github.com/huggingface/accelerate/pull/1283

Can you do `pip install git+https://github.com/huggingface/accelerate` to double check? :)

**Comment by JulesGM** [comment]
hello @muellerzr , I get `ImportError: Using `has_transformer_engine_layers` requires transformer_engine to be installed.`

**Comment by JulesGM** [comment]
<img width="412" alt="Screen Shot 2023-04-03 at 12 48 19 PM" src="https://user-images.githubusercontent.com/3231217/229575197-a5cf166d-1f59-48c8-8fbe-62647d48318d.png">

**Comment by muellerzr** [comment]
That is correct, have you installed the transformer engine on your system? :)

**Comment by JulesGM** [comment]
hmm also, it's only on `H100`s, ok, sad. I was hoping it would also be ok with A100 somehow.

**Comment by JulesGM** [comment]
> No I have not. But it is a weird error to get. I did not know I needed transformer_engine to use fp8, I just selected the option because I saw it in accelerate config.

I suggest that the library checks if `transformer_engine` is installed, and raises if it's not, explaining that it's required. It would be more clean than this.

**Comment by JulesGM** [comment]
Like this, it makes one think it could be a bug.

**Comment by muellerzr** [comment]
Thanks @JulesGM, that does indeed make sense. Should be addressed via https://github.com/huggingface/accelerate/pull/1287, need to see with Sylvain if we want to raise that in the CLI as well (since config files can be swapped/passed through machines). However this will raise the right error when running the script now more clearly

**Comment by JulesGM** [comment]
cool thanks. I can close this if you want

**Comment by muellerzr** [comment]
Sure :)
