### ISSUE TITLE
Upload model to GCS during multi-TPU training in colab, cell stuck

### ISSUE THREAD

**Issue by apoorvumang** [huggingface/accelerate#128]
Hi

I am trying to run multi-TPU training on colab using notebook_launcher. In the training loop, I am able to save the model locally using ``accelerator.save(model.state_dict(), local_file_name)``. However when I try to upload it to GCS using ``gsutil cp``, the cell gets stuck
```
accelerator.print('Inside saving')
accelerator.save(model.state_dict(), local_file_name)
accelerator.print('Model saved')
accelerator.print('Uploading model')
if accelerator.is_main_process:
  gcs_file_name = os.path.join(MODELS_DIR, args.save_prefix, '{}.pt'.format(num_steps))
  ! gsutil cp {local_file_name} {gcs_file_name}
accelerator.print('Upload done to {}!'.format(gcs_file_name))
```
Output and where it gets stuck:
```
Inside saving
Model saved
Uploading model
```
Is it not possible to upload to GCS during train loop? If so, is there another solution?

Thanks

**Comment by sgugger** [comment]
I am very unfamiliar with GCS, so can't really chime in. Maybe it doesn't work properly in the subprocesses run for the 8 cores of the TPU. Does it work if you do this after the `notebook_launcher(training_func)`?

**Comment by apoorvumang** [comment]
@sgugger yes it works after ``notebook_launcher(training_func)``. 

But that would mean that the upload would only happen if the training loop finishes. Then in case colab interrupts my training and closes the runtime, the local files would be gone.

**Comment by apoorvumang** [comment]
@sgugger I know this isn't really huggingface/accelerate related, but do you know of a solution/hack so that I don't lose training progress? It doesn't have to be GCS upload.

Any help would be much appreciated!

**Comment by sgugger** [comment]
You could push your model to the Hugging Face Hub when you want to checkpoint (with the `push_to_hub` method), this way you can resume training from anywhere.
