### ISSUE TITLE
 About FSDP work problems 

### ISSUE THREAD

**Issue by junetou** [huggingface/accelerate#1280]
I have a issue about FSDP:
I have two devices and 8 gpu on each devices. Name is device1 and device2. I use pytorch 2.0 and fsdp train model.
I train a 3.5B gpt2 model in a device1 or device2. It work.
I train a 3.5B gpt2 model in device1 and device2, it work.
I train a 4B gpt2 model in a device1 or device2. It not work.
I train a 4B gpt2 model in device1 and device2, It still not work.Output: torch.cuda.OutOfMemoryError: CUDA out of memory
I want to train a 4B model in device1 and device2 use fsdp.How should I solve this problem? thx

This is config files about fsdp:
compute_environment: LOCAL_MACHINE
distributed_type: FSDP
downcast_bf16: 'no'
fsdp_config:
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_backward_prefetch_policy: NO_PREFETCH
  fsdp_offload_params: true
  fsdp_sharding_strategy: 1
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_transformer_layer_cls_to_wrap: GPT2Block
machine_rank: 1
main_process_ip: 'xxx'
main_process_port: 14781
main_training_function: main
mixed_precision: 'no'
num_machines: 2
num_processes: 16
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false

**Comment by pacman100** [comment]
Are you changing the `machine_rank` across nodes?

**Comment by junetou** [comment]
> Are you changing the `machine_rank` across nodes?

Thank you for your replay.

**Comment by pacman100** [comment]
how long are the sequence lengths? It is difficult to narrow the issue given that there is no other info than "OOM error". 
Maybe, activations end up taking a lot of storage due to long sequence lengths resulting in OOM

**Comment by junetou** [comment]
> how long are the sequence lengths? It is difficult to narrow the issue given that there is no other info than "OOM error". Maybe, activations end up taking a lot of storage due to long sequence lengths resulting in OOM

Thank you.The Sequence lengths is 512,The 4B model size is:
config = GPT2Config(n_embd=3072,n_layer=32,n_head=32,n_positions=1024,n_ctx=1024,vocab_size=52000)
