### ISSUE TITLE
Errror even if offload_dir is provided (actually 2 errors)

### ISSUE THREAD

**Issue by toncho11** [huggingface/accelerate#1281]
### System Info

```Shell
Windows 10
Accelerate Version: 0.18.0.dev0
Python 3.8.0
4GB GPU
16GB RAM
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction
I get the following error:
```

 File "\peft\peft_model.py", line 177, in from_pretrained
    model = dispatch_model(model, device_map=device_map)

  File "\accelerate\big_modeling.py", line 343, in dispatch_model
    raise ValueError(

ValueError: We need an `offload_dir` to dispatch this model according to this `device_map`, the following submodules need to be offloaded: base_model.model.model.layers.4, base_model.model.model.layers.5,
```

The offload folder is specified in my code. But I am forced to hard code the folder like this: offload_dir = "offload" in big_modeling.py at line 341 in order to avoid the error.

This is the code to reproduce the error:

```
import torch
from peft import PeftModel
import transformers
import os, time
import tempfile

assert ("LlamaTokenizer" in transformers._import_structure["models.llama"]), "LLaMA is now in HuggingFace's main branch.\nPlease reinstall it: pip uninstall transformers && pip install git+https://github.com/huggingface/transformers.git"
from transformers import LlamaTokenizer, LlamaForCausalLM, GenerationConfig

tokenizer = LlamaTokenizer.from_pretrained("decapoda-research/llama-7b-hf")

BASE_MODEL = "decapoda-research/llama-7b-hf"
LORA_WEIGHTS = "tloen/alpaca-lora-7b"

force_cpu = False

if torch.cuda.is_available() and not force_cpu:
    device = "cuda"
    print("Video memory available:", torch.cuda.get_device_properties(0).total_memory / 1024 / 1024, "MBs")
else:
    device = "cpu"
print("Compute device is:", device)

print("Loading model with selected weights ...")

if device == "cuda":
    
    print("model on cuda")
    
    model = LlamaForCausalLM.from_pretrained(
        BASE_MODEL,
        load_in_8bit=False,
        torch_dtype=torch.float16,
        device_map="auto",
        offload_folder="offload", 
    )
    
    model = PeftModel.from_pretrained(
        model, 
        LORA_WEIGHTS, 
        torch_dtype=torch.float16,
        device_map="auto",
        offload_folder="offload", 
        
    )
```

### Expected behavior

No error.

**Comment by toncho11** [comment]
If I restart the Python kernel it gives the first run:

```
  File "c:\work\pythoncode\ml_examples\eeg_class\lib\site-packages\accelerate\big_modeling.py", line 333, in dispatch_model
    main_device = [d for d in device_map.values() if d not in ["cpu", "disk"]][0]

IndexError: list index out of range
```

And on second run it gives the error above.

**Comment by sgugger** [comment]
The error about the `offload_dir` comes from `peft` at a first glance of your reproducer, not Accelerate. For the second error, it looks like you do not have a CUDA GPU, and offload on the CPU or the disk only supports CUDA GPUs for now.

**Comment by toncho11** [comment]
So in my case I am loading the LLaMA model with weights from Alpaca.

**Comment by toncho11** [comment]
So in my case I am loading the LLaMA model with weights from Alpaca. 

BASE_MODEL = "decapoda-research/llama-7b-hf"
LORA_WEIGHTS = "tloen/alpaca-lora-7b"

So the `offload_dir` is provided to the `from_pretrained()` method in the **kwargs and it is lost in the next lines from 119 to 163 in  peft_model.py.

**Comment by toncho11** [comment]
I found it.
I made a quick [PR](https://github.com/huggingface/peft/pull/257)

**Comment by pacman100** [comment]
Thanks a lot @toncho11! 😄
