### ISSUE TITLE
Issues using multi-gpu setup with notebook_launcher

### ISSUE THREAD

**Issue by lucala** [huggingface/accelerate#1290]
```
from accelerate import notebook_launcher
args = (config, model, noise_scheduler, optimizer, train_dataloader, lr_scheduler)

notebook_launcher(train_loop, args, num_processes=4)
```
from the [diffuser training example](https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/training_example.ipynb) gives the following error:
```
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
```

I copied the launcher code and swapped the line causing the issue from 
`start_processes(launcher, args=args, nprocs=num_processes, start_method="fork")` to 
`start_processes(launcher, args=args, nprocs=num_processes, start_method="spawn")`

However, now the error is `AttributeError: Can't pickle local object 'get_cosine_schedule_with_warmup..lr_lambda'`

Any idea how to solve this?

**Comment by muellerzr** [comment]
You can test this by running `torch.cuda.is_initialized()` before running any cells with `notebook_launcher`

**Comment by muellerzr** [comment]
That means someone else behind the hood is somehow initializing cuda before we spawn... I'll take a look at it. Thanks!

**Comment by muellerzr** [comment]
This is an issue with diffusers, the team have been alerted. Thanks for the notice @lucala!
