### ISSUE TITLE
test wont work unless --config_path is provided?

### ISSUE THREAD

**Issue by fawazsammani** [huggingface/accelerate#130]
Hi, thanks for the great library.

I have two questions:

1)
When running:   `accelerate config`, then `accelerate test`, the script doesnt work and throws the error: 
`FileNotFoundError: [Errno 2] No such file or directory: 'None'`
Which means the default path is None rather than in the cache folder? 

However it does work perfectly when using: 
` accelerate config --config_file /path/config.json`
`accelerate test --config_file /path/config.json`

2) If I want to use evaluation on one GPU only (not distributed evaluation), it is mentioned: 

> You can perform regular evaluation in your training script, if you leave your validation dataloader out of the prepare() method. In this case, you will need to put the input data on the accelerator.device manually.

If I do this, do I also need to wrap my code inside: `if accelerator.is_main_process():` ?

Thanks a lot!

**Comment by sgugger** [comment]
Could you please post the whole stack trace for 1? Thanks.
For 2, you should put the evaluation code in an `if accelerator.is_main_process():` to only have one process compute it, yes. Otherwise all processes will compute the same thing.

**Comment by fawazsammani** [comment]
Here is the full trace for 1):

`accelerate config`
In which compute environment are you running? ([0] This machine, [1] AWS (Amazon SageMaker)): 0
Which type of machine are you using? ([0] No distributed training, [1] multi-GPU, [2] TPU): 1
How many different machines will you use (use more than 1 for multi-node training)? [1]: 1
How many processes in total will you use? [1]: 2
Do you wish to use FP16 (mixed precision)? [yes/NO]: yes

`accelerate test`

Running:  accelerate-launch **--config_file=None** /home/fawaz/anaconda3/lib/python3.8/site-packages/accelerate/test_utils/test_script.py
stderr: Traceback (most recent call last):
stderr:   File "/home/fawaz/anaconda3/bin/accelerate-launch", line 8, in <module>
stderr:     sys.exit(main())
stderr:   File "/home/fawaz/anaconda3/lib/python3.8/site-packages/accelerate/commands/launch.py", line 319, in main
stderr:     launch_command(args)
stderr:   File "/home/fawaz/anaconda3/lib/python3.8/site-packages/accelerate/commands/launch.py", line 285, in launch_command
stderr:     defaults = load_config_from_file(args.config_file)
stderr:   File "/home/fawaz/anaconda3/lib/python3.8/site-packages/accelerate/commands/config/config_args.py", line 43, in load_config_from_file
stderr:     with open(config_file, "r", encoding="utf-8") as f:
stderr: FileNotFoundError: [Errno 2] No such file or directory: 'None'
Traceback (most recent call last):
  File "/home/fawaz/anaconda3/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/fawaz/anaconda3/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 41, in main
    args.func(args)
  File "/home/fawaz/anaconda3/lib/python3.8/site-packages/accelerate/commands/test.py", line 52, in test_command
    result = execute_subprocess_async(cmd, env=os.environ.copy())
  File "/home/fawaz/anaconda3/lib/python3.8/site-packages/accelerate/test_utils/testing.py", line 134, in execute_subprocess_async
    raise RuntimeError(
RuntimeError: 'accelerate-launch --config_file=None /home/fawaz/anaconda3/lib/python3.8/site-packages/accelerate/test_utils/test_script.py' failed with returncode 1

The combined stderr from workers follows:
Traceback (most recent call last):
  File "/home/fawaz/anaconda3/bin/accelerate-launch", line 8, in <module>
    sys.exit(main())
  File "/home/fawaz/anaconda3/lib/python3.8/site-packages/accelerate/commands/launch.py", line 319, in main
    launch_command(args)
  File "/home/fawaz/anaconda3/lib/python3.8/site-packages/accelerate/commands/launch.py", line 285, in launch_command
    defaults = load_config_from_file(args.config_file)
  File "/home/fawaz/anaconda3/lib/python3.8/site-packages/accelerate/commands/config/config_args.py", line 43, in load_config_from_file
    with open(config_file, "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'None'

As you can see in the bold part, the default is None

**Comment by fawazsammani** [comment]
It seems like this issue was raised in pull request #79. As i can see it is merged...but the error still appears even after I updated the accelerate library to ensure the latest version

**Comment by sgugger** [comment]
I just tried again in a fresh env and I'm not able to reproduce. Are you sure you have a source install of `accelerate` using the main branch? From the line counts in the stack trace it doesn't seem like it.

**Comment by fawazsammani** [comment]
I uninstalled it and re-installed it with `pip install git+https://github.com/huggingface/accelerate` and now it works
Previously i installed it with `pip install accelerate` so it doesent seem to install from main

**Comment by sgugger** [comment]
No, `pip install accelerate` installs the last released version :-)
