### ISSUE TITLE
Native multi-GPU training requires pytorch>=1.9.1

### ISSUE THREAD

**Issue by PeiwenSun2000** [huggingface/accelerate#1301]
### System Info

```Shell
I have already tried both pytorch==1.9.1 and 2.1.0 in CUDA=10.2

but still, get the ERROR of native multi-GPU training requires pytorch>=1.9.1.

Reinstallation of Accelerate==0.18.0 and 0.17.0 also cannot solve the problem.
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

Environment

### Expected behavior

accelerate launch successfully

**Comment by muellerzr** [comment]
Please share the output of `accelerate env` for us to know more about your setup

**Comment by muellerzr** [comment]
And ideally please tell us how you're installing pytorch too
