### ISSUE TITLE
main_process_first() and local_main_process_first() decorators do not work

### ISSUE THREAD

**Issue by flukeskywalker** [huggingface/accelerate#1303]
### System Info

```Shell
- `Accelerate` version: 0.18.0
- Platform: Linux-4.9.0-6-amd64-x86_64-with-glibc2.24
- Python version: 3.11.2
- Numpy version: 1.24.2
- PyTorch version (GPU?): 2.0.0+cu117 (True)
- `Accelerate` default config:
	Not found
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

test.py:
```python
from accelerate import Accelerator
from time import sleep
import os


def main():
    accelerator = Accelerator()
    with accelerator.main_process_first():
        print("HEY", accelerator.is_main_process)
        sleep(3)
        print("BYE", accelerator.is_main_process)


if __name__ == "__main__":
    main()
```
Run with:
```accelerate launch --multi_gpu --num_processes=2 test.py```

Output:
```
HEY True
HEY False
BYE True
BYE False
```
Thanks to @engintoklu for minimal example this is based on.

### Expected behavior

Should output BYE from main process before HEY from non-main processes.

**Comment by flukeskywalker** [comment]
I have a working fix. Will submit PR.

**Comment by sgugger** [comment]
cc @muellerzr
