### ISSUE TITLE
Deepspeed zero stage 3 -  teacher + student network

### ISSUE THREAD

**Issue by andrasiani** [huggingface/accelerate#1305]
Hi, 
I have a 1.5 B param GPT-XL pretrained teacher network in fp16 with requires_grad=False. The student network is a small GPT with 142 M params.
I use pytorch lightning and in train step I first call teacher then student. But the build_net method returns student network so optimizer should contain only student weights.

I managed to use deepspeed 2, but deepspeed 3 crashes.

Is there any way to partition weights of student only, will deepspeed stage 3 partition weights of teacher too?

For the future I am interested in reducing memory footprint of teacher, can deepspeed be used to partition teacher weights in this case?
I'd really appeciate your guidance, thanks!

**Comment by sgugger** [comment]
It looks like those are all questions you should ask the PyTorch ligning folks.

**Comment by andrasiani** [comment]
I'll do that, thank you!
