### ISSUE TITLE
Problem about specifying GPU number across multi-machine

### ISSUE THREAD

**Issue by qitianyuu** [huggingface/accelerate#1306]
I have two machines, each with 8 GPUs, I want to use 12 GPUs，all the GPUS on host1 and the first four GPUs(0,1,2,3) on host2, how should I do this?

I know deepspeed：
```
deepspeed --hostfile=hostfile \
--include="host1:0,1,2,3,4,5,6,7@host2:0,1,2,3" \
train.py
```
to specify the GPUs. number but this method is not applicable to accelerate.

**Comment by sgugger** [comment]
You cannot use a different number of GPUs on different hosts, this limitation comes from PyTorch, not us.
