### ISSUE TITLE
ZeroDivisionError on number of devices

### ISSUE THREAD

**Issue by toncho11** [huggingface/accelerate#1307]
### System Info

```Shell
Windows 10
Accelerate Version: 0.18.0.dev0
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

I am having the following error:

```
per_gpu = module_sizes[""] // (num_devices - 1 if low_zero else num_devices)

ZeroDivisionError: float divmod()
```

The line around 390 in modeling.py:

`max_memory = {i: torch.cuda.mem_get_info(i)[0] for i in range(torch.cuda.device_count())}`

produces {0:0} which means that my GPU has 0 memory. The line must be changed to:

`max_memory = {i: torch.cuda.mem_get_info(i)[1] for i in range(torch.cuda.device_count())}`

to get the correct memory size of a  GPU.

### Expected behavior

No error.

**Comment by sgugger** [comment]
Your GPU has no memory available when you execute the code. Using your workaround would still result in an error (out-of-memory error). You have to free GPU memory to be able to use it.

**Comment by toncho11** [comment]
I think there is still a bug.

**Comment by sgugger** [comment]
From the [PyTorch official doc](https://pytorch.org/docs/stable/generated/torch.cuda.mem_get_info.html#torch.cuda.mem_get_info):
> Returns the global free and total GPU memory occupied for a given device using cudaMemGetInfo.

So the bug is that you have 0 space available on your GPU, maybe because you imported TensorFlow which gobbles everything? Hard to know without seeing the code you run.
