### ISSUE TITLE
using environmental variables

### ISSUE THREAD

**Issue by homelifes** [huggingface/accelerate#131]
Hello. Good day
You mention:  

> Accelerate uses the environment to determine all useful information

My machine has 2 GPUs and `torch.distributed.is_available()` returns `True`.
But for some reason, 'RANK', 'WORLD_SIZE' and 'LOCAL_RANK' are not in `os.environ`. 
Does `accelerate` library uses these to determine the distributed training setup? Because if so, I need to add them to my environment variables manually...

**Comment by sgugger** [comment]
Those are automatically added when you launch you script with `torch.distributed.launch` or `accelerate launch`.

**Comment by homelifes** [comment]
Thank you very much
