### ISSUE TITLE
Can accelerate support the combination of multiple deepspeed models and optimizers?

### ISSUE THREAD

**Issue by piekey1994** [huggingface/accelerate#1310]
### System Info

```Shell
Copy-and-paste the text below in your GitHub issue

- `Accelerate` version: 0.17.1
- Platform: Linux-5.4.0-128-generic-x86_64-with-glibc2.29
- Python version: 3.8.10
- Numpy version: 1.24.2
- PyTorch version (GPU?): 1.13.0+cu117 (True)
- `Accelerate` default config:
        Not found
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

We all know that the training of ppo needs to load several models at the same time, including actor, value function, reward model and so on. Among them, actor and value function may need to be optimized by different optimizers. But at present, if you use deepspeed in accelerate, you can only use a set of models and optimizers, which will be very inconvenient.
Recently, I saw the implementation code of ppo in deepspeedchat(https://github.com/microsoft/DeepSpeedExamples/tree/master/applications/DeepSpeed-Chat), and they initialized several models with deepspeed. I wonder if accelerate can support this feature in the future.
There is also the latest hybrid_engine released by deepspeed, and it would be better if it can support it.

### Expected behavior

Call deepspeed.initialize multiple times to initialize multiple engine.

**Comment by pacman100** [comment]
Hello, as you mentioned, only a single model and its corresponding optimizer are currently supported. 
We will look into the possibility of supporting multiple ds engines as well as how to go about `hybrid_engine`
