### ISSUE TITLE
DataLoaderDispatcher can't handle two input's BatchEncoding with different (padded) input length

### ISSUE THREAD

**Issue by ChristLBUPT** [huggingface/accelerate#1320]
### System Info

```Shell
- `Accelerate` version: 0.18.0
- Platform: Linux-5.4.0-146-generic-x86_64-with-glibc2.17
- Python version: 3.8.15
- Numpy version: 1.23.5
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- `Accelerate` default config:
        Not found
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

I'm doing a pre-training task with accelerate. My dataloader uses `longest` padding, that is, a batch of different lengths will be padded to their max length to form a `transformers.tokenization_utils_base.BatchEncoding` (the well known transformers' model input structure with keywords such as `input_ids`, `attention_mask`, etc). For example, if an input batch consists of 4 sentences whose corresponding input_ids are `[1, 2, 3], [1, 2, 3, 4], [1, 2], [1]`, a BatchEncoding with `input_ids` will become `[[1, 2, 3, 0], [1, 2, 3, 4], [1, 2, 0, 0], [1, 0, 0, 0]]` (seems noob that I explained it a lot but I want to make sure all of you can understand it).
So here comes the question, during training, if I have 2 accelerate processes, the wrapped dataloader (the `DataLoaderDispatcher` class) will fuse the mini-batches fetched by two processes into one, but just as I've mentioned above, two processes' mini-batches will have different `max_length`, so during concatenating a dimension-mismatch error will occur, just as follows (two mini-batches has `max_length` of 152 and 154:

```python
  File "para_pretrain_accelerate.py", line 54, in train
    for batch in tqdm_train_loader:
  File "/home/user/downloads/ENTER/envs/OpenPrompt/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/user/downloads/ENTER/envs/OpenPrompt/lib/python3.8/site-packages/accelerate/data_loader.py", line 513, in __iter__
    next_batch, next_batch_info = self._fetch_batches(main_iterator)
  File "/home/user/downloads/ENTER/envs/OpenPrompt/lib/python3.8/site-packages/accelerate/data_loader.py", line 481, in _fetch_batches
    batch = concatenate(batches, dim=0)
  File "/home/user/downloads/ENTER/envs/OpenPrompt/lib/python3.8/site-packages/accelerate/utils/operations.py", line 366, in concatenate
    return type(data[0])({k: concatenate([d[k] for d in data], dim=dim) for k in data[0].keys()})
  File "/home/user/downloads/ENTER/envs/OpenPrompt/lib/python3.8/site-packages/accelerate/utils/operations.py", line 366, in <dictcomp>
    return type(data[0])({k: concatenate([d[k] for d in data], dim=dim) for k in data[0].keys()})
  File "/home/user/downloads/ENTER/envs/OpenPrompt/lib/python3.8/site-packages/accelerate/utils/operations.py", line 369, in concatenate
    return torch.cat(data, dim=dim)
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 152 but got size 154 for tensor number 1 in the list.
```

I've inspected the code of `accelerate/utils/operations.py and the function `concatenate`'s code is as follows:

```python
def concatenate(data, dim=0):
    """
    Recursively concatenate the tensors in a nested list/tuple/dictionary of lists of tensors with the same shape.

    Args:
        data (nested list/tuple/dictionary of lists of tensors `torch.Tensor`):
            The data to concatenate.
        dim (`int`, *optional*, defaults to 0):
            The dimension on which to concatenate.

    Returns:
        The same data structure as `data` with all the tensors concatenated.
    """
    if isinstance(data[0], (tuple, list)):
        return honor_type(data[0], (concatenate([d[i] for d in data], dim=dim) for i in range(len(data[0]))))
    elif isinstance(data[0], Mapping):
        return type(data[0])({k: concatenate([d[k] for d in data], dim=dim) for k in data[0].keys()})
    elif not isinstance(data[0], torch.Tensor):
        raise TypeError(f"Can only concatenate tensors but got {type(data[0])}")
    return torch.cat(data, dim=dim)
``` 

### Expected behavior

If the `concatenate` function took mini-batches with different input_lenghts into consideration,(for example, pad two mini-batches's `input_ids` with padding tokens), or leave an interface for users to manually define the "fusing" logic, by re-implementing a certain function or so, similar to pytorch dataloader's `collate_fn`, it might work fine.

This situation is quite common since pad `input_ids` to a mini-batch's internal max_length rather than a global max_length will greatly avoid redundant operations and improve training speed.

Looking forward to your reply.

**Comment by sgugger** [comment]
The dispatch dataloader cannot handle different sizes per processes. You should use other options (so set `dispatch_batches=False` in your Accelerator).

**Comment by ChristLBUPT** [comment]
> The dispatch dataloader cannot handle different sizes per processes. You should use other options (so set `dispatch_batches=False` in your Accelerator).

Well, that does work, although I'm trying Pytorch's `DistributedDataParallel` for my problem now, I still want to say thanks. Maybe I should learn more about `accelerate config` or dive deeper into its source code and underlying techniques or explore more of its features through examples.
