### ISSUE TITLE
Example training codes fail to start in distributed (multi-GPU on several nodes) environment

### ISSUE THREAD

**Issue by tnnandi** [huggingface/accelerate#1327]
### System Info

```Shell
- `Accelerate` version: 0.18.0.dev0
- Platform: Linux-5.3.18-57-default-x86_64-with-glibc2.17
- Python version: 3.8.13
- Numpy version: 1.23.5
- PyTorch version (GPU?): 1.12.0a0+git664058f (True)

(The lines below have been taken from the config file generated run time from the slurm script):
compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
mixed_precision: fp16
use_cpu: False
num_processes: 8
machine_rank: 0  (does it need to be different for different nodes?)
num_machines: 2
main_process_ip: 10.201.2.80
main_process_port: 9788
main_training_function: main
deepspeed_config: {}
fsdp_config: {}
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

This issue arises when trying to run the nlp_example.py file (and also the cv_example.py file) in a distributed environment (>1 node, with multiple GPUs on a single node) using a slurm job submission script.

1. Since the IP address of the host node is not known apriori (that needs to be supplied to the accelerate config file), I wrote a small bash script within the job submission file that creates a config file with the appropriate entries (e.g., it collects the IP address information from $(getent hosts $chost | awk '{print $1}' | head -n 1)).

2. When I submit the job on > 1 node (e.g., 2 nodes with 4 GPU each), the training simply fails to start.

3. The i) job submission script (jobsubmit_accelerate.sh), the ii) auxiliary script to generate the config file (create_accelerate_config_tnnandi.py), a iii) sample config file (config_multinode_tnnandi.yml), and the iv) error file showing the time out error (test_accelerate.err), are attached. If there's an easier way to submit multi-node jobs in a an HPC environment where the host IDs are not known before the job submission, please do let me know.

[accelerate_files.zip](https://github.com/huggingface/accelerate/files/11257626/accelerate_files.zip)

### Expected behavior

The training should start as follows (taken from a single node, multi gpu run):

epoch 0: {'accuracy': 0.7034313725490197, 'f1': 0.8163884673748103}
epoch 1: {'accuracy': 0.7573529411764706, 'f1': 0.8483920367534455}

**Comment by tnnandi** [comment]
Can I please have your feedback on this issue? Please let me know if you have any issues with replicating the problem, or any questions about the steps I carried out.

**Comment by muellerzr** [comment]
@tnnandi yes, it needs to be 0 on the master node (the one with the ip address etc) and 1, 2,...n for the rest. You also need to run `accelerate launch` from each machine to fully start it.

**Comment by tnnandi** [comment]
@muellerzr Thank you very much for the feedback and I'd appreciate it if you could point me to any huggingface documentation where I can find the steps for launching PBS jobs. 

Within many HPC environment, it is not known apriori which nodes will be participating in the run, and I'd request you to include some information in your documentation that talks about such cases.

Do I need to write a loop within the job script that does the same exercise (generation of the corresponding config file and launching accelerate) for all the nodes? Please feel free to suggest me an alternative way that you think is much more efficient.

**Comment by tnnandi** [comment]
Hi @muellerzr ,

Following your suggestion, I carried out the following steps for a 2 node job on our local HPC cluster, but training fails to start on both nodes:

1. check out 2 nodes interactively
2. create config files manually (see content of files named config_0.yml and config_1.yml below) using the host ip address and setting the appropriate rank
3. ssh into the 2 nodes and launch accelerate from each (**from master node**: accelerate launch --config_file config_0.yml ./nlp_example.py, **from the other node**: accelerate launch --config_file config_1.yml ./nlp_example.py).

Content of config_0.yml file:
compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
mixed_precision: fp16
use_cpu: False
num_processes: 8
machine_rank: 0
num_machines: 2
main_process_ip: 10.201.4.114
main_process_port: 9788
main_training_function: main
deepspeed_config: {}
fsdp_config: {}


Content of config_1.yml:
compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
mixed_precision: fp16
use_cpu: False
num_processes: 8
machine_rank: 1
num_machines: 2
main_process_ip: 10.201.4.137
main_process_port: 9788
main_training_function: main
deepspeed_config: {}
fsdp_config: {}

I'd really appreciate your inputs on this.

**Comment by adamxyang** [comment]
Hi @tnnandi I'm also facing the same issue for multi-GPU slurm job submissions, have you found any solutions to this? Thanks.

**Comment by tnnandi** [comment]
HI @adamxyang , yes I managed to solve the issue by creating a job submission script that:

i) grabs the node ip addresses and writes them out to config files for each node ( + other information about the distributed environment like total number of nodes and node ID), and 

ii) creates a loop over all the nodes and run the executable. HF Accelerate combines these separate runs into a single one using the information available in the config files.

**Comment by adamxyang** [comment]
@tnnandi Thanks for the info! Could you also share an example submission script?

**Comment by adamxyang** [comment]
I've got something working, though the distributed training speed is slow
```
# Once the job starts, extract node details from SLURM
num_nodes=\$SLURM_JOB_NUM_NODES
nodelist=\$SLURM_JOB_NODELIST

# Extract IPs from the nodelist using getent
ips=\$(scontrol show hostname \$nodelist | xargs -I{} getent hosts {} | awk '{print \$1}')


# Write to config files
for i in \$(seq 1 \$num_nodes); do
    ip=\$(echo \$ips | cut -d' ' -f\$i)
    
    # Create the configuration for Accelerate
    config="compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
mixed_precision: fp16
use_cpu: False
num_processes: $g
machine_rank: \$i
num_machines: \$num_nodes
main_process_ip: \$ip
main_process_port: 9788
main_training_function: main
deepspeed_config: {}
fsdp_config: {}"
    
    # Write the configuration to a file using SLURM_JOB_ID for uniqueness
    echo "\$config" > node_\${SLURM_JOB_ID}_config.yml
done
```
