### ISSUE TITLE
weird behavior during evaluation 

### ISSUE THREAD

**Issue by fawazsammani** [huggingface/accelerate#133]
Hi. I am getting a weird behavior during inference time. Some functions are running before their order. Also, the model becomes re-defined on its own. An outline of my code in given below:

```
for epoch in range(num_train_epochs):
    
    model.train()
    
    for step, batch in enumerate(train_loader):
       #  train_loop
                                                                                                             
    # Here I start evaluation                                                                                                        
    if accelerator.is_main_process:                                                                                                       
        results = sample_sequences(model, tokenizer, test_loader)   # test_loader is NOT ran though prepare
        
    with open(path, 'w') as w:
       json.dump(results, w)
        
   accuracy = get_scores()
```
After training, the `json.dump(results, w)` implements but throws an error because results is not yet defined. After throwing an error `sample_sequences` starts running and throws an `AttributeError` that some attribute of the model (that I defined) is not defined (`DistributedDataParallelObject has not attribute {}`). What exactly is happening (why are some lines implementing before the other? Perhaps the non-main process is ready before the main one and executes the rest of the code? And why is there an Attribute Error? The model becomes re-defined on its own it seems)

Here is the error stack:
![Capture](https://user-images.githubusercontent.com/30661597/128262207-0c9eade2-b863-4835-9cbf-aed38da2e510.PNG)

**Comment by sgugger** [comment]
Hi there!

For the first point, every process executes the program. If you define a variable only in the main process (under an `is_main_process` test), you will get an error in all the other processes. So here your `results` need to be dumped under the `is_main_process` test.

As per the order, they don't go at the same speed, so you can never know which is going to arrive first to a given line. That's not the problem you have here, but if you ever need to, `accelerator.wait_for_everyone()` makes sure every process has joined this stage of the program.

As for your second problem, the model is not redefined, it is wrapped in a PyTorch container for distributed training (as it would if you were running a distributed training without Accelerate). If you need to access your initial model (for instance to call methods on it, but also to save it), you just need to do
```py
unwrapped_model = accelerator.unwrap_model(model)
```
and `unwrapped_model` is your initial model.

**Comment by fawazsammani** [comment]
Many thanks for your reply. According to your answers, if I want to do my evaluation on one GPU, the below is the way to handle it? 
```
accelerator.wait_for_everyone()
unwrapped_model = accelerator.unwrap_model(model)

if accelerator.is_main_process:                                                                                                       
        results = sample_sequences(model, tokenizer, test_loader)

        with open(resFile, 'w') as w:
            json.dump(results, w)
        
        accuracy = get_scores()

unwrapped_model.save_pretrained(path, save_func = accelerate.save) # doesnt need to be inside the if statement since accelerate.save only saves on the main process
accelerate.save(optimizer.state_dict(), path)  
```
Thanks in advance!

**Comment by sgugger** [comment]
I think you need to use `unwrapped_model` in `sample_sequences` too, as you had some problems. The rest seems correct.

**Comment by fawazsammani** [comment]
Yeah its a typo, i meant passing `unwrapped_model` to `sample_sequences`:
`results = sample_sequences(unwrapped_model, tokenizer, test_loader)`

Thanks!
