### ISSUE TITLE
ValueError: weight is on the meta device, we need a `value` to put in on 0. while using AutoModelForTokenClassification

### ISSUE THREAD

**Issue by hemhemoh** [huggingface/accelerate#1335]
Hello, I am trying to load a model in 8bits using bits and bytes and I keep getting this error "ValueError: weight is on the meta device, we need a `value` to put in on 0." Here is my code below.

from transformers import AutoModelForTokenClassification

model_name = 'castorini/afriberta_large'
model = AutoModelForTokenClassification.from_pretrained(model_name,  id2label=id2label, label2id=label2id,device_map='auto',load_in_8bit=True, )

**Comment by sgugger** [comment]
I think this linked to a bug that was just fixed in Transformers. Could you try again with a source install of Transformers?

**Comment by hemhemoh** [comment]
Thank you @sgugger, bug fixed.!

**Comment by TingchenFu** [comment]
Hi @gaalp  do you fix the bug now? I use the latest version of transformers (4.31.dev0) and bitsandbytes (0.39) but also meet with the bug.
