### ISSUE TITLE
Extra memory usage after first evaluation

### ISSUE THREAD

**Issue by hepengfe** [huggingface/accelerate#1338]
### System Info

```Shell
- `Accelerate` version: 0.18.0
- Platform: Linux-5.15.0-60-generic-x86_64-with-glibc2.17
- Python version: 3.8.16
- Numpy version: 1.24.2
- PyTorch version (GPU?): 1.13.0+cu116 (True)
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: NO
        - mixed_precision: no
        - use_cpu: False
        - num_processes: 1
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: 0,1,2
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction
Under DDP setting
```
model is t5 language model
for training loop with gradient accumulation:
    (extra memory after first evaluation, not sure where it comes from)
    if eval condition is met:
         model.eval()
         eval loop  (extra memory from eval data embedding)
         model.train()
```

### Expected behavior

It's expected that after first evaluation, there is no extra memory usage. I tried to use `accelerator.clear()` after each evaluation but it doesn't help. Is there any other suggestion?

**Comment by sgugger** [comment]
This is too vague for us to be able to help. We need a clear reproducer of the issue.
