### ISSUE TITLE
How to do `python -m accelerate script.py` instead of `accelerate launch script.py`?

### ISSUE THREAD

**Issue by hepengfe** [huggingface/accelerate#1346]
I have cases that I cannot use `accelerate launch` but I can use `python -m` and I would like this way of launching accelerate. (just like `python -m torchrun script.py`.

I wonder if there is a way of doing it?

**Comment by sgugger** [comment]
cc @muellerzr

**Comment by hepengfe** [comment]
Or if there any other way to `convert python -m torchrun script.py` to the same effect of `accelerate launch script.py`? Any suggestion to achieve the effect of `accelerate launch` fast would be very helpful.

**Comment by hepengfe** [comment]
I guess just call `https://github.com/huggingface/accelerate/blob/main/src/accelerate/commands/accelerate_cli.py` will solve the problem

**Comment by muellerzr** [comment]
@hepengfe documenting this in https://github.com/huggingface/accelerate/pull/1457

However doing `python -m accelerate.commands.launch` is enough
