### ISSUE TITLE
install accelerate=0.18 fail

### ISSUE THREAD

**Issue by aa327chenge** [huggingface/accelerate#1351]
### System Info

```Shell
OS: window 10
python: 3.8
IDE: pyCharm venv
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

pip install d:\tool\accelerate-0.16.0-py3-none-any.whl

### Expected behavior

ERROR: Package 'accelerate' requires a different Python: 3.6.6 not in '>=3.7.0'

why？？？

**Comment by muellerzr** [comment]
You may need to do `pip3` instead of `pip`. You can check this by seeing if `python -V` is different than `python3 -V`

**Comment by aa327chenge** [comment]
input : pip3 install d:\tool\accelerate-0.16.0-py3-none-any.whl
output : ERROR: Package 'accelerate' requires a different Python: 3.6.6 not in '>=3.7.0'
Always still the error.

**Comment by aa327chenge** [comment]
It‘s my fault.  I choose 3.6 python venv.
