### ISSUE TITLE
Model not offloading to disk when RAM is full

### ISSUE THREAD

**Issue by hari10599** [huggingface/accelerate#1354]
### System Info

```Shell
accelerate                    0.18.0
bitsandbytes                  0.38.1
diffusers                     0.15.1
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

Looks like accelerate is not offloading models to disk when RAM is occupied. Am I missing something?

Ran in machine with 16GB RAM

```
from transformers import AutoModelForCausalLM
import torch
checkpoint = "facebook/opt-6.7b"
model = AutoModelForCausalLM.from_pretrained(checkpoint, device_map="auto", offload_folder="offload", offload_state_dict = True, torch_dtype=torch.float16)

from transformers import AutoConfig, Blip2ForConditionalGeneration,Blip2Processor
import torch
model = Blip2ForConditionalGeneration.from_pretrained("Salesforce/blip2-flan-t5-xl",device_map="auto", offload_folder="offload_1", offload_state_dict = True, torch_dtype=torch.float16)

``` 

### Expected behavior

As per the docs, shouldn't it offload the model to disk when the RAM is full?

**Comment by sgugger** [comment]
Yes but it will be very slow unless you have a very fast hard drive. You will also need to limit the RAM used by the first models (since Accelerate takes all what is available by default) with the `max_memory` argument.

**Comment by hari10599** [comment]
> Yes but it will be very slow unless you have a very fast hard drive. You will also need to limit the RAM used by the first models (since Accelerate takes all what is available by default) with the `max_memory` argument.

Can you provide a sample code?

**Comment by josephzucc** [comment]
Hi, sin jun 22, 2023 that some use says that accelerate mark it as stable, because it has not had recent activity happen on these issue i must says it is happen now ( Thursday, 6th february 2025 ) on my computer with accelerate, with latest ubunt version ( Ubuntu 24.10 uracular oriole ), trying to compile intelligence artificial model BSC-LT/ALIA-40b language model, so
what can we do now?
