### ISSUE TITLE
[Release Request] Release new versions in a fixed time interval

### ISSUE THREAD

**Issue by minhlong94** [huggingface/accelerate#136]
Recently I created an issue for feature request. It was already merged into the master branch. However it has been so long and that PR version is not released yet. Can you release the new versions on a regular basis, like 2 weeks/one month? The latest version was released in April.

**Comment by sgugger** [comment]
The main reason there was no new release is that there hasn't been any new major feature, apart from the DeepSpeed support which needs a little bit more testing.
I'll see if I can make a new release next week.

**Comment by minhlong94** [comment]
That's good to hear, thanks a lot!
