### ISSUE TITLE
How to gather object of any type

### ISSUE THREAD

**Issue by SHUMKASHUN** [huggingface/accelerate#1375]
### System Info

```Shell
It seems gather_object was already implemented in [#238](https://github.com/huggingface/accelerate/pull/238) . However, I cannot find it in the latest version 0.18.0. So how can I gather object other than Tensor?

Thanks
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

N/A

### Expected behavior

N/A

**Comment by sgugger** [comment]
cc @muellerzr

**Comment by muellerzr** [comment]
@SHUMKASHUN you want:

```python
from accelerate.utils import gather_object
```

It was moved to `utils/operations.py`

**Comment by SHUMKASHUN** [comment]
@muellerzr Thank you so much.
