### ISSUE TITLE
[Feature Request] accessible config in python

### ISSUE THREAD

**Issue by Hannibal046** [huggingface/accelerate#1389]
Hi, I am wondering if it is possible to access current accelerate config in python ?

I know I could use `accelerate config` to define a global config and use `accelerate env` to access it. But the config i actually use may differ from this global config since i could pass arguments to accelerate like `num_processes` or `mixed_precision`.

So maybe this function could be added ?
```
accelerator = Accelerator()
config = accelerator.get_config()
```

**Comment by muellerzr** [comment]
You want the `AcceleratorState` class, which you can instantiate any number of times after the Accelerator has been made and it won't change. This is also accessible via `accelerator.state`.

Docs: https://huggingface.co/docs/accelerate/package_reference/state
