### ISSUE TITLE
Unable to send extra params to DDP

### ISSUE THREAD

**Issue by theschnitz** [huggingface/accelerate#14]
My model's forward function returns losses as well as some debug output. So I need to set find_unused_parameters=True in the ddp, but there's no way to pass this in the preparation.

Perhaps we could pass some kwargs for the items being prepared? I'm not sure how generic this problem is.

**Comment by sgugger** [comment]
Hi there! This is similar to #11 so I'm going to close this one, so we can keep all the discussion there.

I will work on a fix tomorrow and implement the config solution discussed there, so you will be able to pass something like:
```
ddp_params = DDPParams(find_unused_parameters=True)
```
inside your call to `Accelerator()` to solve your issue.
