### ISSUE TITLE
ValueError, doesn't have any device set.

### ISSUE THREAD

**Issue by reddiamond1234** [huggingface/accelerate#1402]
### System Info

```Shell
- `Accelerate` version: 0.19.0
- Platform: Linux-5.19.0-32-generic-x86_64-with-glibc2.35
- Python version: 3.10.6
- Numpy version: 1.24.3
- PyTorch version (GPU?): 2.0.1+cu117 (False)
- System RAM: 6.41 GB
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: DEEPSPEED
        - mixed_precision: fp16
        - use_cpu: False
        - num_processes: 1
        - machine_rank: 0
        - num_machines: 1
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - deepspeed_config: {'gradient_accumulation_steps': 1, 'gradient_clipping': 1.0, 'offload_optimizer_device': 'none', 'offload_param_device': 'cpu', 'zero3_init_flag': True, 'zero_stage': 2}
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
        - dynamo_config: {'dynamo_backend': 'INDUCTOR', 'dynamo_mode': 'default', 'dynamo_use_dynamic': True, 'dynamo_use_fullgraph': True}
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

I am fine tuning Llama model with this code:

 model = LlamaForCausalLM.from_pretrained(
        "decapoda-research/llama-7b-hf",
        load_in_8bit=True,
        torch_dtype=torch.float16,
        device_map=device_map,
        quantization_config=quantization_config,
    )

device_map = {
    "transformer.word_embeddings": 0,
    "transformer.word_embeddings_layernorm": 0,
    "lm_head": "cpu",
    "transformer.h": 0,
    "transformer.ln_f": 0,
    }

and get this error:

Loading checkpoint shards:   0%|                                                                                                                                                                  | 0/33 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/jan/ai-development/ai/alpaca/test.py", line 745, in <module>
    fire.Fire(run)
  File "/home/jan/.local/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/jan/.local/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/jan/.local/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/jan/ai-development/ai/alpaca/test.py", line 742, in run
    train()
  File "/home/jan/ai-development/ai/alpaca/test.py", line 323, in train
    model = LlamaForCausalLM.from_pretrained(
  File "/home/jan/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2785, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/home/jan/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3126, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "/home/jan/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 701, in _load_state_dict_into_meta_model
    raise ValueError(f"{param_name} doesn't have any device set.")
ValueError: model.layers.0.self_attn.q_proj.weight doesn't have any device set.

I must be doing something wrong, and also I don't have enough experience with ML, so it might be rookie mistake...

### Expected behavior

I would like to fine tune Llama model from .json dataset.

**Comment by muellerzr** [comment]
cc @sgugger

**Comment by sgugger** [comment]
The `decapoda-research/llama-7b-hf` checkpoints cannot work with Hugging Face anyway, they are not maintained by their owner.
