### ISSUE TITLE
Using 'gloo' backend with Huggingface Accelerate

### ISSUE THREAD

**Issue by jerilkuriakose** [huggingface/accelerate#141]
I installed the huggingface `Accelerate` library to train the BERT model in multiple GPUs.  The `Accelerate` library was installed using `pip` in the `Anaconda` environment. But I couldnt the `accelerate` command in powershell (This happens whenever i use pip instead of conda install).

The following `accelerate` command 
```
accelerate config
```
throws the following error:
```
accelerate : The term 'accelerate' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ accelerate config
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (accelerate:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
I used the example mentioned in their [GitHub Page][1]. As the `accelerate` command was not working from powershell, I used the `torch.distributed.launch` to run the script as follows:
```
 python -m torch.distributed.launch --nproc_per_node 1 --use_env ./nlp_example.py
```
Since I was using Windows OS, it gave the following error:
```
RuntimeError: Distributed package doesn\'t have NCCL built in
```
My doubt is, will it to possible to change the backend to use `gloo`, rather than 'NCCL' in `Accelerate` package, or is there any other way to run the multiple GPU training.

Thank you.

  [1]: https://github.com/huggingface/accelerate/blob/main/examples/nlp_example.py

**Comment by sgugger** [comment]
To use the another backend than `nccl`, you have to do the initiliazation of `torch.distributed` yourself, before the first time you create the `Accelerator`. `accelerate` won't reinitialize the backend in that case.

**Comment by jerilkuriakose** [comment]
Thank you, it worked.

**Comment by littleyeson** [comment]
> Thank you, it worked.

I have same problem.How to fixed it. Thx

**Comment by muellerzr** [comment]
@littleyeson can you open a new issue about this please? Thanks!

**Comment by abdelkareemkobo** [comment]
> Thank you, it worked.

can you share how it worked with you?
