### ISSUE TITLE
How to not have  "rich" take over tracebacks after installing accelerate

### ISSUE THREAD

**Issue by fractaldna22** [huggingface/accelerate#1417]
please someone tell me how to not have This GOD AWFUL traceback formatting in cosmic sans ms font and the worst color scheme, least informative, zero links, zero help on where exceptions happened, "rich" formatting taking over the entire notebook session after importing accelerate? Please. Who even likes this , or wants it? Why??

**Comment by fractaldna22** [comment]
it insists on reinstalling it , even after i uninstall rich and set environ['DISABLE_RICH'] = '1' accelerate INSISTS on reinstalling it and its absolutely without any purpose whatsoever.

**Comment by muellerzr** [comment]
Sadly that's not accelerate directly, as we don't have any code in the notebook version that even *uses* rich. You'll need to completely uninstall it from the env to avoid it taking over, or open an issue on the rich repo to see if there's a way to delete it from the jupyter environment. Apologies!

**Comment by fractaldna22** [comment]
Ive figured out an insanely complicated way to install rich and it involves modifying pytorch lightning .py files after accelerator is already installed (accelerator installs rich in the requirements)

**Comment by muellerzr** [comment]
That sounds like a lightning issue then? Are you using Accelerate?

**Comment by fractaldna22** [comment]
I raised this issue on lightnings repo and they said it was not due to
lightning. after fixing lightning and everything was fixed, installing
accelerate did revert the fix back to the rich tracebacks after importing
accelerate..
Originally I thought it was diffusers, but it was only because diffusers
uses accelerate and lightning.

Im not saying its strictly accelerates fault..  but, I'm simply arguing
that we should collectively as a community delete rich from the internet lol

**Comment by pranavgade20** [comment]
You can use `import os; os.environ['ACCELERATE_DISABLE_RICH'] = "1"` before you run other code to disable rich formatting - see https://github.com/huggingface/accelerate/blob/665d5180fcc01d5700f7a9aa3f9bdb75c6055dce/src/accelerate/utils/imports.py#L162 for more info. Another way is to set this variable in your system wide profile file, which makes sure rich formatting is never used.
