### ISSUE TITLE
LSF support

### ISSUE THREAD

**Issue by williamstark01** [huggingface/accelerate#142]
Thank you for this very promising library.

I'm trying to use Accelerate on a large [LSF](https://en.wikipedia.org/wiki/IBM_Spectrum_LSF) cluster. We have an abundance of CPUs that I'd like to use for distributed training. Is this environment supported or is it outside the scope of Accelerate?

My tests even on the simplest case of a single machine with multiple cores / processors all fail and it's not clear to me whether there is some configuration I'm missing or LSF somehow interferes with how Accelerate operates in the background.

**Comment by sgugger** [comment]
Hi there! I'm not familiar with LSF clusters; Accelerate is mainly a wrapper around `torch.distributed`, do you have an example of use of this package on an LSF cluster? I could answer your question better then.

**Comment by williamstark01** [comment]
I found these projects that have implemented distributed training on LSF with `torch.distributed`:
https://github.com/sparticlesteve/nesap-stl/blob/master/utils/distributed.py
https://github.com/NYUMedML/DeepDementia/blob/main/src/lib/ddp_utils.py

At first look the implementations seem relatively simple, unless a lot more things are happening in the background, I'm guessing adding this functionality to Accelerate wouldn't be too involved.

And here is another one that might be also useful which creates a custom LSF environment class by extending the PyTorch Lightning ClusterEnvironment class:
https://github.com/exabiome/deep-taxon/blob/master/src/exabiome/nn/lsf_environment.py

I'll try to reuse some of this code for my project, but it would be good if Accelerate supported this natively.
