### ISSUE TITLE
Model Parallelism

### ISSUE THREAD

**Issue by OhadRubin** [huggingface/accelerate#143]
Hey,
Is it possible to use accelerate with model parallelism?
If so, can you provide an example?

**Comment by sgugger** [comment]
No, Accelerate only supports data parallelism to train on multiple GPUs or TPUs for now.

**Comment by qqaatw** [comment]
@sgugger Maybe we can put a proper prompt in the readme or documentation so users can be aware that currently only data parallelism is supported?

Hope Accelerate will support model parallelism in the future!
