### ISSUE TITLE
Using HF trainer together with accelerate, bf16 not recognized

### ISSUE THREAD

**Issue by cnut1648** [huggingface/accelerate#1432]
### System Info

```Shell
accelerate: 0.19.0
transformers:
pytorch: torch 2.0.0
CUDA: 11.6
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

Instead of using `no_trainer` scripts, I use trainer scripts like [this](https://github.com/huggingface/transformers/blob/main/examples/pytorch/translation/run_translation.py) one.
I am able to run the script using accelerate library together with transformer trainer via 
```shell
accelerate launch --multi_gpu --mixed_precision="fp16" examples/pytorch/translation/run_translation.py \
    --model_name_or_path Helsinki-NLP/opus-mt-en-ro \
    --fp16 \
    --do_train \
    --do_eval \
    --source_lang en \
    --target_lang ro \
    --dataset_name wmt16 \
    --dataset_config_name ro-en \
    --output_dir /tmp/tst-translation \
    --per_device_train_batch_size=4 \
    --per_device_eval_batch_size=4 \
    --overwrite_output_dir \
    --predict_with_generate
```
However I found that (1) I have to specify `--fp16` in the arguments of `run_translation.py` and using only `--mixed_precision="fp16"` does not seem to enable fp16 training. (2) Using bf16 by `--mixed_precision="bf16"` and adding `--bf16` does not seem to enable bf16 training.

Thus I wonder if using accelerate together with HF trainer is a good idea as of now. From #144 it seems that this is already on the plan and since I do can run fp16 multigpu training it seems that accelerate does support trainer? Thank you.

### Expected behavior

All features of HF trainer (e.g. bf16) should be supported.

**Comment by muellerzr** [comment]
Currently the mixed precision aspects are solely in the trainer, it does not use Accelerate yet. For now you must pass `--fp16`/`--bf16` as you ddi before, it is not part of the current implementation. (We are working on this)

**Comment by cnut1648** [comment]
I think, huggingface trainer really have a lot of cool features baked in and it will be a extremely helpful addon if it supports accelerate out of box. Thank you so much for the hard work!
