### ISSUE TITLE
Using accelerate config for SLURM cluster with dist_url input

### ISSUE THREAD

**Issue by rmchurch** [huggingface/accelerate#145]
When I normally use torch DistributedDataParallel, its on a cluster with a SLURM scheduler, and the IP address and port for initialization is more difficult to use, so I use the `dist_url`  to feed a dummy file location, since the parallel filesystem is reliably accessible across multiple nodes, e.g.
```
    args.dist_url = "file:///scratch/gpfs/dummy.txt"
    args.world_size = int(os.environ['SLURM_NTASKS'])
    args.rank = int(os.environ['SLURM_PROCID'])
    dist.init_process_group(backend="nccl", init_method=args.dist_url,
                                world_size=args.world_size, rank=args.rank)
```
Looking a bit through issues and code, it seems like the current setup for accelerate is to use IP address and port. It appears I can add this above code to avoid accelerate doing the init_process_group (I know not ideal for seamless changing from single GPU to multi-node GPU training), but I'm not clear on if I will still need to run `accelerate config` from the command line, or if other pieces of code need to be added for the default example provided.

UPDATE: I seem to be doing something wrong with this setup, as I can see for multi-GPU runs that only a single GPU per node is utilized (though all processes have the correct rank and world size)

**Comment by sgugger** [comment]
Any custom initialization should work, since Accelerate only initializes if it's not been done already.
As for your other problem, I don't know much about SLURM schedulers, so not sure I can help. It may be linked to the way you launch your script, it's unlikely the accelerate launcher will work since it does not set those environment variables. How did you launch your processes for training?

**Comment by rom1504** [comment]
Hi,

It would be appreciated to have explicit support for slurm

**Comment by rom1504** [comment]
https://gist.github.com/rom1504/474f97a95a526d40ae44a3fc3c657a2e fyi something like that works well to do slurm + accelerate

**Comment by r3dapple** [comment]
Hello, Id like to express my need for SLURM support aswell.
