### ISSUE TITLE
accelerate config examples

### ISSUE THREAD

**Issue by msank00** [huggingface/accelerate#146]
Hi Team,

Thanks for the wonderful package. :rocket: 

However, I have a request if you can enhance the documentation with some examples of `accelerate config`. What are the parameters that one might set while filling the questionnaire. For me the issue was this:

![image](https://user-images.githubusercontent.com/11691571/130607430-362da063-0024-46dd-8cd3-d440412aff3a.png)

- `how many processes in total will you use?`: Didn't realize this was asking for number of CPUs or no of GPUs?

So code was not behaving properly. After checking `pytorch distributed launch` [code](https://github.com/pytorch/pytorch/blob/master/torch/distributed/launch.py), it's clear that `--nproc_per_node=NUM_GPUS_YOU_HAVE`. 

May be this is a trivial question for anyone using multi-gpu training on pytorch for long time. But for newcomer in multi-gpu training, it might be confusing. So some examples with better paraphrasing might be helpful.

**Comment by samarth-b** [comment]
I agree that this question is unclear, if `python -m torch.distributed.launch --nproc_per_node 2 my_script.py` works, should the answer to the number of processes question be 2? can it be assigned to the number of available gpus?

**Comment by sgugger** [comment]
Which re-formulation do you think would be more helpful?

**Comment by samarth-b** [comment]
quoting from: https://pytorch.org/docs/stable/distributed.html

`In both cases of single-node distributed training or multi-node distributed training, this utility will launch the given number of processes per node (--nproc_per_node). **If used for GPU training, this number needs to be less or equal to the number of GPUs on the current system (nproc_per_node)**, and each process will be operating on a single GPU from GPU 0 to GPU (nproc_per_node - 1).`

can it be automatically set to equal to GPUs using CUDA_AVAILABLE_DEVICES?

**Comment by sgugger** [comment]
No, that's not something that should be selected automatically, as people might change the number of GPUs by setting the `CUDA_VISIBLE_DEVICES` environment variable between the time `accelerate config` and `accelerate launch` is run.

**Comment by sgugger** [comment]
On one machine, it could yes. Will look into this.

**Comment by hobbitlzy** [comment]
So, each time if I change the number of available GPU, I need to rerun the `accelerate config` to set a new number of processes?

**Comment by sgugger** [comment]
Or you can override the number of processes with `--num_processes xxx` in your launch command. The config only provides the defaults to use.
