### ISSUE TITLE
Setting NVMe in DeepSpeed ZeRO with accelerate config, but nowhere to specify NVMe path

### ISSUE THREAD

**Issue by Blair-Johnson** [huggingface/accelerate#1463]
The `accelerate config` utility offers the ability to quickly configure DeepSpeed ZeRO, however it seems to offer options that can't be used. If the user selects NVMe offloading for the optimizer or model parameters, the `accelerate config` does not follow up with a request for the path to an NVMe device. Is there currently a way to do this, or should this be a future modification to the config utility?

**Comment by sgugger** [comment]
cc @pacman100

**Comment by pacman100** [comment]
Hello @Blair-Johnson, the default `/local_nvme` was being used with NVME offloading but I agree that flexibility here is a great addition

**Comment by Blair-Johnson** [comment]
Interesting, I experienced Deepspeed errors suggesting that the path hadn't been set at all. I can get version info and put together a script to reproduce the issue.

**Comment by abhilash1910** [comment]
@Blair-Johnson could you try installing accelerate from source and re-try with accelerate config ?
