### ISSUE TITLE
continue pre-training without Trainer

### ISSUE THREAD

**Issue by flckv** [huggingface/accelerate#1480]
### System Info

```Shell
- Accelarate version:  0.19.0  
- OS: Ubuntu 20.04.4 LTS (x86_64)
- Python version: 3.11.3
- Numpy: 1.24.3
- PyTorch version: 2.0.1


- CUDA used to build PyTorch: 11.8
- Is CUDA available: True
- CUDA runtime version: 11.8.89
- CUDA_MODULE_LOADING set to: LAZY
- GPU models and configuration: 
- GPU 0: NVIDIA A100-SXM4-40GB
- GPU 1: NVIDIA A100-SXM4-40GB
- GPU 2: NVIDIA A100-SXM4-40GB
- GPU 3: NVIDIA A100-SXM4-40GB
- Huggingface_hub version: 0.14.1



(I am using SLURM:)
- Accelarate’s config: (not sure which file you mean)
accelerate config
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------In which compute environment are you running?
Please select a choice using the arrow or number keys, and selecting with enter
 ➔  This machine
    AWS (Amazon SageMaker)

there was no option for the nodes I already assigned
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

1. based on the [SLURM-accelerate template](https://github.com/huggingface/accelerate/issues/1239#issuecomment-1494331155)

2. I pre-train the [wav2vec demo on librispeech](https://github.com/huggingface/transformers/blob/main/examples/pytorch/speech-pretraining/README.md)

3. I only have 12 hours for the pretraining, so I have to be able to continue the pretraining from the checkpoint for the other 12-hours-pretrainings.

### Expected behavior

Given the wav2vec script:
- is **not** using the HuggingFace Traininer
- is using Accelerate 
- is using SLURM

Without HuggingFace Traininer how to load the last best model to continue pre-training?

**Comment by sgugger** [comment]
This example does not support it out of the box, you will need to add the saving/loading logic as described in the documentation [here](https://huggingface.co/docs/accelerate/quicktour#savingloading-entire-states).

**Comment by flckv** [comment]
I see, thank you.
