### ISSUE TITLE
Accelerate, Deepspeed, and torch.compile integration

### ISSUE THREAD

**Issue by bri25yu** [huggingface/accelerate#1500]
Hi HF accelerate folks! Not sure if this is the best place to post this, but I'm wondering about the integration between Deepspeed and torch.compile. From what I can tell, the Deepspeed flow uses `_prepare_deepspeed` which skips `prepare_model` that wraps the model in `torch.compile`. Is the plan to have DS support torch.compile?

**Comment by sgugger** [comment]
DeepSpeed does not support `torch.compile` for now, so we are waiting for them to add support.

**Comment by bri25yu** [comment]
Gotcha, thanks for the response!
