### ISSUE TITLE
set_module_tensor_to_device doesn't properly deploy BitsAndBytes Linear4bit

### ISSUE THREAD

**Issue by BlackSamorez** [huggingface/accelerate#1504]
The [explicit Linear8bitLt module name check](https://github.com/huggingface/accelerate/blob/4d583ad6a1f13d1d7617e6a37f791ec01a68413a/src/accelerate/utils/modeling.py#LL184C42-L184C42) doesn't apply to Linear4bit, but it probably could with minimal tweaks.

**Comment by younesbelkada** [comment]
Thanks for the ping @BlackSamorez 
I made https://github.com/huggingface/accelerate/pull/1505 that should resolve your issue. Could you please try it out and let me know how it goes?

**Comment by BlackSamorez** [comment]
Thanks a lot!
