### ISSUE TITLE
Can the accelerate support `torch.distributed.launch` ?

### ISSUE THREAD

**Issue by Doragd** [huggingface/accelerate#153]
For some reason, I don't want to reconfigure `accelerate config` when launching a new experiment every time. 

I just need to change an optional argument from a script if I use `torch.distributed.launch`. It's really convenient.

I have tried to change `accelerate launch` with `torch.distributed.launch` simply. It works for me.

However, when running with fp16, **I'm not sure it really works when adding the `--fp16` option.**

I would like to know if there is a chance to support `torch.distributed.launch`. I believe it is really beneficial for researchers and users. For example, somebody has proposed a similar issue: https://github.com/huggingface/accelerate/issues/148

If the repo has supported this launching way, could you add more details and examples in the `README.md`?

=============================================================
1. use `accelerate launch`  and set use_fp16 = True by `accelerate config`
```shell
CUDA_VISIBLE_DEVICES=0 accelerate launch run_translation_no_trainer.py \
    --model_name_or_path facebook/mbart-large-cc25 \
    --source_lang en \
    --target_lang ro \
    --dataset_name wmt16 \
    --dataset_config_name ro-en \
    --output_dir output \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 16 \
    --seed 42
```

2. use `torch.distributed.launch` and add `--fp16` option
```shell
CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch \
    --nproc_per_node 1 --master_port 57889 \
    --use_env run_translation_no_trainer.py \
    --model_name_or_path facebook/mbart-large-cc25 \
    --source_lang en \
    --target_lang ro \
    --dataset_name wmt16 \
    --dataset_config_name ro-en \
    --output_dir output \
    --per_device_train_batch_size 16 \
    --per_device_eval_batch_size 16 \
    --seed 42 \
    --fp16
```

**Comment by sgugger** [comment]
As indicated extensively [here](https://github.com/huggingface/accelerate/tree/main/examples), Accelerate is completely compatible with the PyTorch distributed launcher.

**Comment by Doragd** [comment]
Thanks a lot.

**Comment by Chen-Suyi** [comment]
> As indicated extensively [here](https://github.com/huggingface/accelerate/tree/main/examples), Accelerate is completely compatible with the PyTorch distributed launcher.

Sorry, I am still confused about it.

Does it mean we can launch a script implemented with Accelerate by using `torch.distributed.launch`?

I met an error asking to use `torch.distributed.launch` instead of `accelerate launch`, when I use Accelerate with torch version=1.8.1

Can you give me some examples?
