### ISSUE TITLE
How to run `torchrun` with only setting `device_map = "auto"` in multi-node distributed training environment?

### ISSUE THREAD

**Issue by jacklanda** [huggingface/accelerate#1534]
I don't find any useful documentations or introductions for training LLM, e.g. LLaMA-13B, 30B in multi-node distributed training environment. 

Note that I hope to instantiate model with `device_map = "auto"` due to the limitation of GRAM (a single A100-80GB could not hold on a full checkpoint of large model), as well as bootstrap this distributed process with PyTroch's original command `torchrun`.

How can I do to achieve that?

Thanks so much !

**Comment by sgugger** [comment]
Those are not compatible with each other. For this kind of training you need to use FSDP or DeepSpeed.

**Comment by Li-Z-Q** [comment]
Can torchrun and device_map="auto" can be compatible with each other now ?

**Comment by jacklanda** [comment]
> Can torchrun and device_map="auto" can be compatible with each other now ?
  >> Those are not compatible with each other. For this kind of training you need to use FSDP or DeepSpeed.


I believe you could use FSDP or DeepSpeed to implement that. Hope this helps.
