### ISSUE TITLE
AttributeError: 'map' object has no attribute 'backward' - when using mixed precision and transformers model outputs

### ISSUE THREAD

**Issue by alexandrethm** [huggingface/accelerate#155]
I have been getting this error when using mixed precision (`accelerator.use_fp16=True`) and transformers model outputs (extensions to `ModelOutput` with the `dataclass` decorator).

In my case, the forward of my model returns a `CustomOutput` object, defined exactly like `Seq2SeqLMOutput` in `transformers.modeling_outputs` for instance, so it should behave the same:
```
@dataclass
class CustomOutput(ModelOutput):
    """
    Custom output class, but should work just the same as `Seq2SeqLMOutput` for instance
    """
    loss: Optional[torch.FloatTensor] = None
    logits: torch.FloatTensor = None
    past_key_values: Optional[Tuple[Tuple[torch.FloatTensor]]] = None
    decoder_hidden_states: Optional[Tuple[torch.FloatTensor]] = None
```

When calling `accelerator.backward(model_outputs.loss)`, I get this error:
```
  File "/mnt/nfs/home/al.thomas/venv_py36_v2/lib64/python3.6/site-packages/accelerate/accelerator.py", line 399, in backward
    self.scaler.scale(loss).backward(**kwargs)
AttributeError: 'map' object has no attribute 'backward'
```

Indeed, when I print `model_outputs` and `model_outputs.loss`, `model_outputs.loss` is a dict containing the outputs (instead of being a tensor), and `model_outputs` is a `CustomOutput` object almost empty (only `model_outputs.loss` is not `None`). This only happens in mixed precision training when we apply the `convert_outputs_to_fp32` decorator to the model's forward, to transform its outputs.

It seems to me this is because of this line in the `convert_to_fp32` method (in utils):
```
    elif isinstance(tensor, dict):
        return type(tensor)({k: convert_to_fp32(v) for k, v in tensor.items()})
```

Changing it to 
```
    elif isinstance(tensor, dict):
        return type(tensor)(**{k: convert_to_fp32(v) for k, v in tensor.items()})
```
should fix the issue I believe.

Happy to make a PR if needed !

**Comment by sgugger** [comment]
This has been fixed in master, just make a source install and you should be good! I will also make a patch release today with this bug fix.

**Comment by sgugger** [comment]
Actually, this error is coming from Transformers, make sure to update to the latest version!

**Comment by alexandrethm** [comment]
Thanks !
