### ISSUE TITLE
Accelerator error while training dreambooth

### ISSUE THREAD

**Issue by borismartirosyandenovo** [huggingface/accelerate#1559]
### System Info

```Shell
Google Colab:
It started to not work yesterday at the afternoon, but before that I didn't get any error

│ /content/train_dreambooth.py:869 in <module>                                 │
│                                                                              │
│   866                                                                        │
│   867 if __name__ == "__main__":                                             │
│   868 │   args = parse_args()                                                │
│ ❱ 869 │   main(args)                                                         │
│   870                                                                        │
│                                                                              │
│ /content/train_dreambooth.py:425 in main                                     │
│                                                                              │
│   422 def main(args):                                                        │
│   423 │   logging_dir = Path(args.output_dir, "0", args.logging_dir)         │
│   424 │                                                                      │
│ ❱ 425 │   accelerator = Accelerator(                                         │
│   426 │   │   gradient_accumulation_steps=args.gradient_accumulation_steps,  │
│   427 │   │   mixed_precision=args.mixed_precision,                          │
│   428 │   │   log_with="tensorboard", 
                log_dir = log_dir                       │
╰──────────────────────────────────────────────────────────────────────────────╯
TypeError: Accelerator.__init__() got an unexpected keyword argument 
'logging_dir'
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

-

### Expected behavior

It should pass that part because as I understood for logging we need tensorboard, but when I delete both log and log_dir, it doesn't work!

**Comment by borismartirosyandenovo** [comment]
I have tried it now and now it changed to 'project_dir', thank you!

**Comment by muellerzr** [comment]
@borismartirosyandenovo good to close? :)

**Comment by ZYQ121** [comment]
It might because the version of accelerate is higher than 0.18.x, you can replace  the  `logging_dir=logging_dir`

in `accelerator = Accelerator(
    gradient_accumulation_steps=1,
    mixed_precision=args.mixed_precision,
    log_with=args.report_to,
    logging_dir=logging_dir,
    project_config=accelerator_project_config,
)
with` 'project_dir=logging_dir'

or install a lower version:
` pip install accelerate==0.18.0`

**Comment by BenjaminBossan** [comment]
@naarkhoo To downgrade accelerate further, you'd need to also downgrade transformers, as it has a required min version of accelerate. Instead of doing that, did you try the proposed solution above?

**Comment by naarkhoo** [comment]
I take my words back - I ended up installing everything last version and seems that worked out - downgrading to 0.18.0 did not help.
