### ISSUE TITLE
How to save optimizer?

### ISSUE THREAD

**Issue by hadaev8** [huggingface/accelerate#156]
Docs says

```
accelerator.wait_for_everyone()
unwrapped_model = accelerator.unwrap_model(model)
accelerator.save(unwrapped_model.state_dict(), filename)
```

But what about optimizer?

**Comment by sgugger** [comment]
Like any PyTorch optimizer, by saving the `optimizer.state_dict()`.

Like for the model, you should use `accelerator.save` instead of `torch.save`.

**Comment by hadaev8** [comment]
Should i use accelerator.get_state_dict(model) like in readme?

**Comment by sgugger** [comment]
If you want to use DeepSpeed, yes.

**Comment by hadaev8** [comment]
Got it, thanks.
