### ISSUE TITLE
cpu memory leak in recent version

### ISSUE THREAD

**Issue by luyvlei** [huggingface/accelerate#1572]
### System Info

```Shell
- `Accelerate` version: 0.20.3
- Platform: Linux-5.4.143.bsk.8-amd64-x86_64-with-glibc2.31
- Python version: 3.9.2
- Numpy version: 1.23.5
- PyTorch version (GPU): 2.0.1+cu117 
- `Accelerate` default config:
        Not found
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

In the recent training, I found that memory leaks will occur regularly. The target has not been determined to the specific location before, and I will continue to follow up. 

Observed phenomenon: When a memory leak occurs, the memory will be quickly occupied at a rate of 100G per minute, and the program will crash in 2 minutes. 

At the same time, when a memory leak occurs, the server monitors an outbound traffic of 0.3 Mbps (this phenomenon has been reproduced stably twice, and the outbound traffic is always 0 before a memory leak occurs)

My training code is modified from the diffusers example code: https://github.com/huggingface/diffusers/blob/main/examples/research_projects/dreambooth_inpaint/train_dreambooth_inpaint.py 

### Expected behavior

Analyze the problem.

**Comment by muellerzr** [comment]
Can you tell us which version did not include a memory leak? This will help immensely with debugging.

**Comment by luyvlei** [comment]
> Can you tell us which version did not include a memory leak? This will help immensely with debugging.

Thanks. 

In the past, I used scripts to install the latest packages before training and the earliest leak occurred when the script was launched on May 29, so the version should be 0.19.0.

I'm not sure yet if accelerate is causing the problem because the `diffusers` package also updated recently. And this phenomenon does not appear regularly, sometimes at 150 hours of training and sometimes at 20 hours. 

But one thing is certain is that the system recorded 0.3Mbps network traffic when this leak phenomenon occurred. (I have a panel that logs the state of the container during training). So I think memory leaks are highly related to the behavior of sending data out, is there any code in the accelerate framework that will send relevant data to the outside?

**Comment by muellerzr** [comment]
Nope. This would be from diffusers i believe. I'd recommend opening an issue there

**Comment by luyvlei** [comment]
> Nope. This would be from diffusers i believe. I'd recommend opening an issue there

Ok, thanks for the reply, I will roll back the diffuser version and observe.

**Comment by muellerzr** [comment]
Great, let us know if the issue still persists and we'll take a closer look @luyvlei

**Comment by luyvlei** [comment]
> Great, let us know if the issue still persists and we'll take a closer look @luyvlei

After repeated observation, I finally confirmed that the problem came from pytorch2.0.1, and diffusers and accelerate were all right. No memory leaks have occurred since switching to pytorch2.0.0.

**Comment by MarshtompCS** [comment]
> > Great, let us know if the issue still persists and we'll take a closer look @luyvlei
> 
> After repeated observation, I finally confirmed that the problem came from pytorch2.0.1, and diffusers and accelerate were all right. After switching to pytorch2.0.0, there were no memory leaks for 15 days of training.

I am using Pytorch2.0.1, and I think I meet the same problem, it bother me for a long time. The CPU memory exhausted suddenly after a period of stable training, as shown in this figure, memory usage increases from 237min, OOM occures at 240min, memory was occupied 400G within 3min:

![image](https://github.com/huggingface/accelerate/assets/43492391/c14d6e33-742a-4550-ad8c-13ccea1ba116)

I wonder if you have figured out why pytorch2.0.1 has this problem? The latest version is 2.1.0 now, but I didn't see other people have this issue.

**Comment by MarshtompCS** [comment]
pytor

> > Great, let us know if the issue still persists and we'll take a closer look @luyvlei
> 
> After repeated observation, I finally confirmed that the problem came from pytorch2.0.1, and diffusers and accelerate were all right. After switching to pytorch2.0.0, there were no memory leaks for 15 days of training.

Cannot solve my problem after switching to pytorch2.0.0
