### ISSUE TITLE
AttributeError: 'T5Attention' object has no attribute 'relative_attention_bias' when using load_checkpoint_and_dispatch to load T5-11b 

### ISSUE THREAD

**Issue by bacnv-scopic** [huggingface/accelerate#1584]
### Short description of the problem
I was trying to load a model larger than my GPU size using load_checkpoint_and_dispatch, but ran into an error
### System Info

```Shell
accelerate version: 0.20.3
OS: ubuntu 18.04
python: 3.9
torch: 2.0.1
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [x] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

Step to reproduce the bug:
1. Install related libraries by pip
2. Run the below 
```python
from transformers import T5Tokenizer, T5ForConditionalGeneration
from accelerate import init_empty_weights, load_checkpoint_and_dispatch, infer_auto_device_map
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer, AutoModel
import torch

model_name = "t5-11b"
tokenizer = T5Tokenizer.from_pretrained(model_name)
with init_empty_weights():
    model = T5ForConditionalGeneration.from_pretrained(model_name)
device_map = infer_auto_device_map(model)
model = load_checkpoint_and_dispatch(
model, "/nas/huggingface_pretrained_models/models--t5-11b/snapshots/90f37703b3334dfe9d2b009bfcbfbf1ac9d28ea3/pytorch_model.bin",
device_map=device_map)
```

### Expected behavior

The modules are loaded to the device.
However I get this error:  `AttributeError: 'T5Attention' object has no attribute 'relative_attention_bias'` . Below is the full traceback:
`Traceback (most recent call last):
  File "/nas/thuchk/NLLB_transformers/movie_subtitles_translation/T5_huggingface/batch_infer_sharded.py", line 66, in <module>
    full_result = T5_batch_infer(model_name=model_name, data_path=intputdata_path, batch_size=1)
  File "/nas/thuchk/NLLB_transformers/movie_subtitles_translation/T5_huggingface/batch_infer_sharded.py", line 27, in T5_batch_infer
    model = load_checkpoint_and_dispatch(
  File "/nas/.conda/envs/subtitle_translation/lib/python3.9/site-packages/accelerate/big_modeling.py", line 486, in load_checkpoint_and_dispatch
    load_checkpoint_in_model(
  File "/nas/.conda/envs/subtitle_translation/lib/python3.9/site-packages/accelerate/utils/modeling.py", line 1116, in load_checkpoint_in_model
    set_module_tensor_to_device(model, param_name, param_device, value=param, dtype=dtype)
  File "/nas/.conda/envs/subtitle_translation/lib/python3.9/site-packages/accelerate/utils/modeling.py", line 142, in set_module_tensor_to_device
    new_module = getattr(module, split)
  File "/nas/.conda/envs/subtitle_translation/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'T5Attention' object has no attribute 'relative_attention_bias'`

I run the debugger and find out that when I print the module `T5Attention` it doesn't have the `relative_attention_bias` layer, but `tensor_name` variable value has that layer. This discrepancy causes the error.

 
![Screenshot from 2023-06-13 16-04-42](https://github.com/huggingface/accelerate/assets/102780985/7ded2ef5-8996-44dc-8f7b-ddf97b055d19)

**Comment by sgugger** [comment]
I don't understand what you are trying to achieve with this code (that I can't reproduce). Why not use directly?
```py
model = T5ForConditionalGeneration.from_pretrained(model_name, device_map="auto")
```

**Comment by bacnv-scopic** [comment]
I was trying to load a model larger than my GPU size. The below function load each module to the CPU and then dispatch them to GPU one by one. But when I run it I got the error above.
model = load_checkpoint_and_dispatch(
model, "/nas/huggingface_pretrained_models/models--t5-11b/snapshots/90f37703b3334dfe9d2b009bfcbfbf1ac9d28ea3/pytorch_model.bin",
device_map=device_map)

**Comment by sgugger** [comment]
> I was trying to load a model larger than my GPU size.

Yes, the code above will do exactly that.

**Comment by zcakzhuu** [comment]
I am having exactly the same question here. I have been doing some research but i just cannot find the difference between from_pretrained and load_checkpoint_and_dispatch. Why is the Accelerate tutorial on making inference using big models specifically mentioned load_checkpoint_and_dispatch not just from_pretrained? Are they the same under the hood?

**Comment by sgugger** [comment]
The tutorial for Accelerate shows you how to do things for any model, it just takes a Transformer model as an example. The Transformers library is a tighter integration, so for any Transformer model, you should use `from_pretrained`
