### ISSUE TITLE
`from_pretrained` crash if `device_map` contains only "disk"

### ISSUE THREAD

**Issue by gardspirito** [huggingface/accelerate#1600]
Case when `device_map` contains only "disk" is not handled:
https://github.com/huggingface/accelerate/blob/0983a9b9b48c8239650515831d6f1995940812fa/src/accelerate/big_modeling.py#LL333C3-L333C3

**Comment by sgugger** [comment]
Yes that is not possible.

**Comment by gardspirito** [comment]
What exactly is not possible? For "disk" to be the only one? Well, somehow it does in my case.

Or is it not possible for model to work properly if the entire model is offloaded on the disk?

**Comment by sgugger** [comment]
It's not supported to have the whole device_map be disk. If you end up with this while trying to load a model, it means you don't have enough GPU/CPU RAM to host even the smallest layer so there is nothing we can do to run it.

**Comment by gardspirito** [comment]
Okay. I was actually able to load a model after patching the sources, but it didn't end up working properly. It was executing as it should be, but the output was just garbage.

I don't know if that's because I patched the source and assigned `main_device` to "cpu" or because of something else (for example, because of the fact that I was executing the model that was saved as 8-bit on CPU and not GPU).
