### ISSUE TITLE
AttributeError: 'Parameter' object has no attribute 'named_children' when use `infer_auto_device_map`

### ISSUE THREAD

**Issue by gongbaitao** [huggingface/accelerate#1602]
### System Info

```Shell
accelerate==0.19.0
OS: Linux
python: 3.9.16
torch: 2.0.1
no accelerate configuration
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

```python
from transformers import AutoModelForCausalLM, AutoTokenizer
from accelerate.utils import get_balanced_memory, infer_auto_device_map

tokenizer = AutoTokenizer.from_pretrained("openbmb/cpm-bee-1b", trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained("openbmb/cpm-bee-1b", trust_remote_code=True).cuda()

max_memory = get_balanced_memory(
    model, 
    no_split_module_classes=["CpmBeeTransformerBlock"],
    low_zero=(device_map == "balanced_low_0")
)
device_map = infer_auto_device_map(model, max_memory=max_memory, no_split_module_classes=["CpmBeeTransformerBlock"])  
```
But I get the error:
```AttributeError: 'Parameter' object has no attribute 'named_children'``` in line653
<img width="679" alt="截屏2023-06-16 19 03 11" src="https://github.com/huggingface/accelerate/assets/45178523/9770eca2-00f9-4126-8c02-35c820dda15d">
It seems that `modules_to_treat` includes some parameters.
So is the way correct I use `infer_auto_device_map`?

### Expected behavior

Get the device_map.

**Comment by sgugger** [comment]
I thinks this has been fixed since 0.19.0, could you try again on the latest version?

**Comment by gongbaitao** [comment]
It's cool. I upgrade accelerate to 0.20.3 and it's been solved. Thanks:)

**Comment by typicaldigital** [comment]
@sgugger

I am getting a similar issue in the latest version trying to run the HuggingFace "DeepFloyd/IF-I-M-v1.0" model.
 
AttributeError: 'Tensor' object has no attribute 'named_children'

 pipeline = DiffusionPipeline.from_pretrained(args.model,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python311\Lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1105, in from_pretrained
    loaded_sub_model = load_sub_model(
                       ^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python311\Lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 472, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python311\Lib\site-packages\diffusers\models\modeling_utils.py", line 713, in from_pretrained
    raise e
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python311\Lib\site-packages\diffusers\models\modeling_utils.py", line 674, in from_pretrained
    accelerate.load_checkpoint_and_dispatch(
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python311\Lib\site-packages\accelerate\big_modeling.py", line 530, in load_checkpoint_and_dispatch
    device_map = infer_auto_device_map(
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python311\Lib\site-packages\accelerate\utils\modeling.py", line 1001, in infer_auto_device_map
    modules_children = [] if isinstance(module, nn.Parameter) else list(module.named_children())
                                                                        ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Tensor' object has no attribute 'named_children'

**Comment by coollzd** [comment]
@typicaldigital 
I meet the same problem with you when I try to run Deepfloyd IF.
have you solved this?

**Comment by typicaldigital** [comment]
Nope, I have not tried again.
