### ISSUE TITLE
get_balanced_memory() ignores GPU:0 entirely if low_zero=True

### ISSUE THREAD

**Issue by poedator** [huggingface/accelerate#1607]
### System Info

```Shell
ubuntu18, python39, transformers 4292, accelerate=0.20.3
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

There may be a flaw in `get_balanced_memory()` function, which leads to completely ignoring GPU:0 entirely if `low_zero = True`.

TO REPRODUCE:
load Llama 7B model, with accelerate and device_map = "balanced_low_0", 2 GPUS with 8GIB limit on each.
or run:
```
kwargs = {'max_memory': {0: '8GIB', 1: '8GIB'}, 'no_split_module_classes': ['LlamaDecoderLayer'], 'special_dtypes': {}}
get_balanced_memory(model, low_zero=True, dtype=torch.float16, **kwargs)

# returns {0: 0, 1: 8589934592}
# expected {0: ~5GiB, 1: 8589934592}
```
WHAT HAPPENS: 
function location: https://github.com/huggingface/accelerate/blob/v0.20-release/src/accelerate/utils/modeling.py#L541
1) L588: `per_gpu` is not accounting for CUDA:0 capacity.
2) L631-632 sets max_memory[0] to 0
3) L635 attemts to calculate capacity needed on CUDA:0 (although not quite enough)
4) L636 sets max_memory[0] back to 0, because min(min_zero, max_memory[0]) = min(min_zero, 0) = 0
so 0 is returned for CUDA:0 capacity. It leads to no allocation of modules to Cuda:0.

This observation may be related to https://github.com/huggingface/accelerate/issues/1167

I can try to propose a PR if the issue is recognized. However the code for device_map = "balanced_low_0" seems quite convoluted, with logic split between get_balanced_memory() and infer_auto_device_map(). Some guidance from HF would be appreciated.

### Expected behavior

most of the model loaded go GPUs 1+ while GPU0 is utilized, but less, as described in the docs.

**Comment by sgugger** [comment]
`balanced_low_0` will use all the memory of the other GPUs and only put things on GPU 0 if there is not enough, so what you describe doesn't sound like a bug but the intended behavior of this option.

**Comment by poedator** [comment]
> 

to clarify: the observed behaviour is GPU1 is full, GPU0 stays empty and whatever did not fit to GPU1 is sent to "disk", not GPU0. This does not look like intended behaviour.

**Comment by sgugger** [comment]
Ah understood! Yes this is not normal. If you have an idea of a fix, please go ahead with a PR, I won't have time to dive into this soon.
