### ISSUE TITLE
Does HuggingFace use GPUDirectStorage?

### ISSUE THREAD

**Issue by ranggihwang** [huggingface/accelerate#1608]
### System Info

```Shell
- `Accelerate` version: 0.17.1
- Platform: Linux-5.4.0-42-generic-x86_64-with-glibc2.10
- Python version: 3.8.13
- Numpy version: 1.24.2
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: DEEPSPEED
        - mixed_precision: bf16
        - use_cpu: False
        - num_processes: 1
        - machine_rank: 0
        - num_machines: 1
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - deepspeed_config: {'gradient_accumulation_steps': 0, 'gradient_clipping': 0.0, 'offload_optimizer_device': 'cpu', 'offload_param_device': 'cpu', 'zero3_init_flag': True, 'zero3_save_16bit_model': True, 'zero_stage': 3}
        - fsdp_config: {}
        - megatron_lm_config: {}
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
        - dynamo_config: {'dynamo_backend': 'ONNXRT', 'dynamo_mode': 'default', 'dynamo_use_dynamic': True, 'dynamo_use_fullgraph': True}
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

It's not about the bug report.

### Expected behavior

Hi, all.

Before going on, it's not about bug reporting but more about feature requests.

I'm using HuggingFace's Accelerate for offloading the parameters to SSD.
But when doing it, it always occupies the CPU thread blocking other commands from being conducted in parallel.

And I found that there's a Nvidia GPUDirectStorage that uses NVMe's DMA enabling the CPU to do other commands in parallel.

Does Accelerate already include this kind of function?
If not can I use it by customizing Accelerate source code?

**Comment by sgugger** [comment]
No Accelerate does not support this/
