### ISSUE TITLE
Support of full examples 

### ISSUE THREAD

**Issue by rose-jinyang** [huggingface/accelerate#162]
Hello
How are you?
Thanks for contributing to this project.
Could u provide full examples for training, saving, and re-loading models in this project?
Thanks

**Comment by sgugger** [comment]
Hi there! Please ask questions like this on the [forums](https://discuss.huggingface.co/) as we keep issues for feature requests and bugs only.
You can find lots of examples using Accelerate with saving models in the [Transformers](https://github.com/huggingface/transformers/tree/master/examples/pytorch) examples (look for the `_no_trainer` ones).

**Comment by rose-jinyang** [comment]
Thanks for your reply.
But I think that there are all the full examples for training, evaluating, saving, and reloading models in this github project.
