### ISSUE TITLE
How to guide problem - Handling big models for inference 

### ISSUE THREAD

**Issue by mitschron** [huggingface/accelerate#1629]
### System Info

```Shell
OS: Linux #33~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Jan 30 17:03:34 UTC 2 x86_64 x86_64
GPU: NVIDIA GeForce RTX 4070, NVIDIA-SMI 530.41.03, Driver Version: 530.41.03, CUDA Version: 12.1
python: Python 3.10.6
accelerate: 0.20.3
torch: 1.13.1
numpy: 1.25.0
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

I am trying to follow the "how to guide" for running inference on a big model, but my script crashes. 
I have pieced together the various steps from [here](https://huggingface.co/docs/accelerate/usage_guides/big_modeling) as follows:

```
git clone https://huggingface.co/sgugger/sharded-gpt-j-6B
cd sharded-gpt-j-6B
git-lfs install
git lfs pull
```

And then run this:

``` 
from accelerate import init_empty_weights
from accelerate import load_checkpoint_and_dispatch
from transformers import AutoConfig, AutoModelForCausalLM

checkpoint = "EleutherAI/gpt-j-6B"
config = AutoConfig.from_pretrained(checkpoint)

with init_empty_weights():
    model = AutoModelForCausalLM.from_config(config)

model.tie_weights()

model = load_checkpoint_and_dispatch(
    model, "sharded-gpt-j-6B", device_map="auto", no_split_module_classes=["GPTJBlock"]
)

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(checkpoint)
inputs = tokenizer("Hello, my name is", return_tensors="pt")
inputs = inputs.to(0)
output = model.generate(inputs["input_ids"])
tokenizer.decode(output[0].tolist())
```

### Expected behavior

The script crashes. I get the following warning about tying the weights which is strange since `model.tie_weights` is called

```
The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
Killed
```

**Comment by sgugger** [comment]
cc @SunMarc for the warning that should not be displayed here.

The process is killed because you don't have enough RAM (probably). The option `offload_state_dict=True` might help you in this case, or using the `sharded` revision of this checkpoint to load the state dict in smaller pieces.

**Comment by mitschron** [comment]
Yes I also assume this is because I am running out of memory. I adjusted to
```
model = load_checkpoint_and_dispatch(
    model, "sharded-gpt-j-6B", device_map="auto", no_split_module_classes=["GPTJBlock"], offload_state_dict=True
)
```
but I still get the same behavior. 

You mention using the sharded revision of this checkpoint. I am not sure how to do that. I thought cloning the sharded repo was enough. 

The config file pointed to is

```json
{
  "_name_or_path": "EleutherAI/gpt-j-6B",
  "activation_function": "gelu_new",
  "architectures": [
    "GPTJForCausalLM"
  ],
  "attn_pdrop": 0.0,
  "bos_token_id": 50256,
  "embd_pdrop": 0.0,
  "eos_token_id": 50256,
  "gradient_checkpointing": false,
  "initializer_range": 0.02,
  "layer_norm_epsilon": 1e-05,
  "model_type": "gptj",
  "n_embd": 4096,
  "n_head": 16,
  "n_inner": null,
  "n_layer": 28,
  "n_positions": 2048,
  "resid_pdrop": 0.0,
  "rotary": true,
  "rotary_dim": 64,
  "scale_attn_weights": true,
  "summary_activation": null,
  "summary_first_dropout": 0.1,
  "summary_proj_to_labels": true,
  "summary_type": "cls_index",
  "summary_use_proj": true,
  "task_specific_params": {
    "text-generation": {
      "do_sample": true,
      "max_length": 50,
      "temperature": 1.0
    }
  },
  "tie_word_embeddings": false,
  "tokenizer_class": "GPT2Tokenizer",
  "torch_dtype": "float16",
  "transformers_version": "4.19.0.dev0",
  "use_cache": true,
  "vocab_size": 50400
}
```

**Comment by SunMarc** [comment]
Hi, for the warning that should not be displayed, it is solved in this [PR](https://github.com/huggingface/accelerate/pull/1595). You can clone the main branch if you don't want to see the warning anymore or wait for the next release.
