### ISSUE TITLE
Creates extra-processes

### ISSUE THREAD

**Issue by gleb270** [huggingface/accelerate#163]
I've configured accelerate to handle 4,6,8,10 processes(different setups for testing).
And it creates 7, 11, 15 and 19 processes respectively instead.
The number is N-1 +N, because it creates N-1 extra processes on the 4th card.
I.e. 
```
|    0   N/A  N/A     58825      C   python3    28175MiB |
|    1   N/A  N/A     58826      C   python3    28195MiB |
|    2   N/A  N/A     58827      C   python3    28199MiB |
|    3   N/A  N/A     58825      C   python3     1405MiB |
|    3   N/A  N/A     58826      C   python3     1405MiB |
|    3   N/A  N/A     58827      C   python3     1405MiB |
|    3   N/A  N/A     58828      C   python3    28179MiB |
```

And it doesn't matter which card will be 4th. I changed the order in CUDA_VISIBLE_DEVICES and it still creates on the 4th in order.

Is this a bug or I'm doing something wrong?

**Comment by sgugger** [comment]
Mmm, you can't create more processes than you have GPUs an expect a normal behavior.

**Comment by gleb270** [comment]
I have 16 GPUs setup, but I limit count of processes with `accelerate config` and count of available GPUs in `CUDA_VISIBLE_DEVICES` and in every setup N_GPUs > N_processes

**Comment by gleb270** [comment]
It looks like it create some kind of mirror/shadow for each process in 4th card, but I can't explain it and determine the reason

**Comment by sgugger** [comment]
Could you please share your config and the exact command you used for the launch then?

**Comment by gleb270** [comment]
```
accelerate config
In which compute environment are you running? ([0] This machine, [1] AWS (Amazon SageMaker)): 0
Which type of machine are you using? ([0] No distributed training, [1] multi-CPU, [2] multi-GPU, [3] TPU): 2
How many different machines will you use (use more than 1 for multi-node training)? [1]: 1
Do you want to use DeepSpeed? [yes/NO]: NO 
How many processes in total will you use? [1]: 4
Do you wish to use FP16 (mixed precision)? [yes/NO]: NO
```

`CUDA_VISIBLE_DEVICES=0,1,2,3,5,7,13,15 accelerate launch train.py`

**Comment by gleb270** [comment]
Well, I fixed It with adding device in loading
`torch.load(self.continue_from, self.accelerator.device)`
It created extra objects on inappropriate gpu
