### ISSUE TITLE
Accessing illegal GPU_IDs when using slurm.

### ISSUE THREAD

**Issue by WindVChen** [huggingface/accelerate#1643]
### System Info

```Shell
- `Accelerate` version: 0.18.0
- Platform: Linux-3.10.0-957.el7.x86_64-x86_64-with-glibc2.10
- Python version: 3.8.0
- Numpy version: 1.22.0
- PyTorch version (GPU?): 2.0.0+cu117 (False)
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: fp16
        - use_cpu: False
        - num_processes: 8
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: 0,1,2,3,4,5,6,7
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

```python
import torch
import time

print(torch.cuda.device_count())
```

### Expected behavior

When run:
```
srun -N 1 --gres=gpu:3 python test.py
```
The result is 3, it is correct (only access the allocated 3 GPUs):

However, when I use Accelerate, the result is 8. 
```
srun -N 1 --gres=gpu:3 accelerate launch test.py
```
It seems that `Accelerate launch` just ignores the GPUs allocated by Slurm, and can access all the GPUs on the server.

What's more, if I limit `gpu_ids=0,1,2`, it is true that the above result will be 3. However, the 3 GPUs are not the 3 GPUs allocated by Slurm, but always the first 3 GPUs in the server! (E.g., there are 8 GPUs in the server. No. 5,6,7 GPUs are idle, so Slurm will allocate that 3 GPUs to me; however, Accelerate will use No. 0,1,2 GPUs).

It is quite weird and does bring much inconvenience. Is there any solution to prevent the above problems? Thank you.

**Comment by sgugger** [comment]
No, there is no ignoring. When you do `srun -N 1 --gres=gpu:3 python test.py` only one process is launched with the 3 GPUs visible. When you do `srun -N 1 --gres=gpu:3 python test.py`, accelerate uses `torchrun` to launch your script since it sees multi-gpu in your config, so 8 processes are launched, each seeing one GPU.

**Comment by WindVChen** [comment]
Sorry, I'm still a bit confused. Meaning, even if I allocate only 3 GPUs by setting `--gres=gpu:3` in the srun command, Accelerate will skip that configuration and follow its own configuration (`--gpu_ids 0,1,2,3,4,5,6,7`) to access all 8 GPUs on the server ?

**Comment by sgugger** [comment]
That's what I said yes. You shouldn't use `accelerate launch` inside an `srun` like this as you are trying to control in two different ways the number of processes run and the number of GPUs seen.

**Comment by WindVChen** [comment]
I get it, thank you. And I just found out that I can set `--gpu_ids='all'` to have Accelerate follow the srun resources and use the correct GPUs allocated by slurm.

**Comment by yuho8818** [comment]
thanks a lot
