### ISSUE TITLE
[Question] What parts of deepspeed configuration can use auto?

### ISSUE THREAD

**Issue by chiragjn** [huggingface/accelerate#1644]
### System Info

```Shell
- `Accelerate` version: 0.20.3
- Platform: Linux-5.15.89+-x86_64-with-glibc2.31
- Python version: 3.10.11
- Numpy version: 1.24.3
- PyTorch version (GPU?): 2.0.1 (True)
- PyTorch XPU available: False
- System RAM: 83.48 GB
- GPU type: NVIDIA A100-SXM4-40GB
- `Accelerate` default config:
        Not found
```

In addition to this, I am using `transformers==4.30.1`. Recently, the internals of the `transformers.Trainer` seems to have been refactored to use more parts of `accelerate`AutoModelForCausalLM`), specifically `databricks/dolly-v2-7b` with the following deepspeed config

```
{
  "fp16": {
    "enabled": "auto",
    "loss_scale": 0,
    "loss_scale_window": 1000,
    "initial_scale_power": 16,
    "hysteresis": 2,
    "min_loss_scale": 1
  },
  "bf16": {
    "enabled": "auto"
  },
  "optimizer": {
    "type": "AdamW",
    "params": {
      "lr": "auto",
      "betas": "auto",
      "eps": "auto",
      "weight_decay": "auto"
    }
  },
  "scheduler": {
    "type": "WarmupDecayLR",
    "params": {
      "warmup_min_lr": "auto",
      "warmup_max_lr": "auto",
      "warmup_num_steps": "auto",
      "total_num_steps": "auto"
    }
  },
  "zero_optimization": {
    "stage": 2,
    "overlap_comm": true,
    "contiguous_gradients": true,
    "sub_group_size": "auto",
    "reduce_bucket_size": "auto",
    "allgather_partitions": true,
    "allgather_bucket_size": "auto",
    "reduce_scatter": true,
    "round_robin_gradients": true
  },
  "gradient_accumulation_steps": "auto",
  "gradient_clipping": "auto",
  "steps_per_print": 2000,
  "train_batch_size": "auto",
  "train_micro_batch_size_per_gpu": "auto",
  "wall_clock_breakdown": false
}
```

I run into errors initializing deepspeed, it does not seem to accept `auto` anymore for some of the arguments

```
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 1645, in train
    return inner_training_loop(
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 1759, in _inner_training_loop
    model, self.optimizer, self.lr_scheduler = self.accelerator.prepare(
  File "/opt/conda/lib/python3.10/site-packages/accelerate/accelerator.py", line 1178, in prepare
    result = self._prepare_deepspeed(*args)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/accelerator.py", line 1486, in _prepare_deepspeed
    deepspeed_plugin.deepspeed_config_process(must_match=False, **config_kwargs)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/utils/dataclasses.py", line 624, in deepspeed_config_process
    self.deepspeed_config_process(
  File "/opt/conda/lib/python3.10/site-packages/accelerate/utils/dataclasses.py", line 628, in deepspeed_config_process
    self.fill_match(prefix + key, mismatches, must_match=must_match, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/utils/dataclasses.py", line 603, in fill_match
    raise ValueError(
ValueError: `zero_optimization.sub_group_size` not found in kwargs. Please specify `zero_optimization.sub_group_size` without `auto`(set to correct value) in the DeepSpeed config file or pass it in kwargs.
```

This error does not happen with `transformers==4.29.2`, so I am wondering if I was configuring it wrong all along

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

Try to finetune any LM with deepspeed configuration with almost everything set to auto, in this case specifically `zero_optimization.sub_group_size`

My code is [here](https://github.com/truefoundry/truefoundry-examples/tree/989d3a123d325187713f734cf93469aa5640d32a/llm-finetune) just in case

### Expected behavior

Ideally, the default values from Deepspeed config should be filled in place of auto

**Comment by pacman100** [comment]
Hello,

> Ideally, the default values from Deepspeed config should be filled in place of auto

If you want the DeepSpeed default values, those shouldn't be part of config at all.

The `auto` values are meant to be inferred from training arguments and datasets. Those aren't meant to be default values from DeepSpeed config or are required parameters by DeepSpeed.

**Comment by pacman100** [comment]
The trainer handles all the config params mentioned https://github.com/huggingface/transformers/blob/main/src/transformers/deepspeed.py#L120 and https://github.com/huggingface/transformers/blob/main/src/transformers/deepspeed.py#L178. This is unchanged and you can verify that `sub_group_size ` isn't being handled for `auto`. Earlier, the check to make sure that we don't have any params with `auto` values before preparing deepspeed model wasn't there. It is now being done by Accelerate and as such the error you see above. Please follow the steps outlined in the error to resolve it.

**Comment by chiragjn** [comment]
Got it, makes sense. It is odd that deepspeed engine did not complain at all with these values being "auto" 🙈 .
Thanks, closing this, after fixing I am able to work with transformers 4.30
