### ISSUE TITLE
Multi-GPU training issue - Failing to specify which GPUs to use (socket error: errno 98)

### ISSUE THREAD

**Issue by ShashwatNigam99** [huggingface/accelerate#1649]
### System Info

```Shell
- `Accelerate` version: 0.20.3
- Platform: Linux-5.3.18-57-default-x86_64-with-glibc2.31
- Python version: 3.10.11
- Numpy version: 1.24.3
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- PyTorch XPU available: False
- System RAM: 503.54 GB
- GPU type: NVIDIA A100 80GB PCIe
- `Accelerate` default config:
        Not found
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

I am running example scripts in the diffusers library which use the accelerate library.

1. Suppose, I have a multi-gpu training running on 2 GPUs out of the 4 available to me (launched using accelerate, working well).
Launched using-
`accelerate launch --mixed_precision="fp16" --multi_gpu --num_processes 2 train_controlnet.py`
So nvidia-smi looks something like this-
![Capture](https://github.com/huggingface/accelerate/assets/30972206/dcaf0d1a-b501-4576-9a82-48e1347b0e14)

2. Now I try to run another multi-gpu process, by specifying the GPUs to specify (wish to use the idle gpus: 2 and 3):
`accelerate launch --mixed_precision="fp16" --multi_gpu --gpu_ids="2,3" --num_processes 2  train_controlnet.py `
I get this error-
`RuntimeError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:29500 (errno: 98 - Address already in use). The server socket has failed to bind to 0.0.0.0:29500 (errno: 98 - Address already in use).`

Have also tried explicitly specifying:
`export CUDA_VISIBLE_DEVICES="2,3"` before calling accelerate, getting the same error.

I am not able to launch single-gpu training as well. For example if I run any of these:
`accelerate launch --mixed_precision="fp16"  train_controlnet.py`
`accelerate launch --mixed_precision="fp16" --gpu_ids="2,3" train_controlnet.py `
`accelerate launch --mixed_precision="fp16" --gpu_ids="2" train_controlnet.py `

None of these work and throw the same error. Is there something fundamental I am missing?

### Expected behavior

Expected behaviour would have been that the second process I am launching utilized the idle GPUs.

**Comment by muellerzr** [comment]
You need to specify a different port to use, and this should fix it up. `--main_processing_port` iirc

**Comment by ShashwatNigam99** [comment]
Thanks a lot for the quick response. 

The argument is called `main_process_port` and changing that worked. This is the command I used-
`accelerate launch --mixed_precision="fp16" --multi_gpu --num_processes 2 --gpu_ids="2,3" --main_process_port=8000 train_controlnet.py`

Closing this issue!
