### ISSUE TITLE
bad_alloc when importing after some transformers modules (TPU VM)

### ISSUE THREAD

**Issue by thnkinbtfly** [huggingface/accelerate#165]
Hi,
Thanks for building this amazing product.

I was trying to debug on TPU-VM via Pycharm remote debugger, 
and I found that **I cannot import accelerate** when I run the script without `accelerate launch`, only **if I import some transformers modules before that**.

1. When I run `python import_test.py`, I get bad_alloc, but it runs well when I use `accelerate launch import_test.py` (I attached import_test.py at the very end of this issue)
![image](https://user-images.githubusercontent.com/70014488/133546807-eeec1c91-4922-471b-8f6f-2ad130c33f28.png)

2. More interestingly, **this behavior happens only after I import some transformers modules** :
- when I import accelerate only, it works well,
![image](https://user-images.githubusercontent.com/70014488/133546162-0703926c-1069-4f40-8d6e-7961473c7bbf.png)
- But when I import some of modules from transformers before it, I get bad_alloc
![image](https://user-images.githubusercontent.com/70014488/133546236-ff7355d8-ac11-4aae-9673-a8811ecbdf84.png)
- If I import some other modules, it works well
![image](https://user-images.githubusercontent.com/70014488/133547200-af562a7b-8ce3-4001-99d9-022875131b94.png)
- Thus, the only working example is importing the Accelerator at the very first line
![image](https://user-images.githubusercontent.com/70014488/133547318-64a137f0-44ff-479e-9666-d19a8ea64d1c.png)

Now I can run the script without `accelerate launch`, thus I can run the debugger!

But, could you help me understand why is this happening??

Thanks!

import_test.py : 

```
from transformers.optimization import get_scheduler, SchedulerType, LambdaLR
from accelerate import Accelerator

def main():
    pass

if __name__=="__main__":
    main()
```

**Comment by sgugger** [comment]
I haven't played much with TPU VMs, it's very likely that there is some problem with PyTorch XLA being initialized twice.
