### ISSUE TITLE
While running the command: deepspeed --num_gpus 8 --module inference_server.benchmark --model_name microsoft/bloom-deepspeed-inference-fp16 --model_class AutoModelForCausalLM --dtype fp16 --deployment_framework ds_inference --benchmark_cycles 5  I get an error " No module named  inference_server.benchmark

### ISSUE THREAD

**Issue by PromitHal** [huggingface/accelerate#1663]
### System Info

```Shell
linux
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

deepspeed --num_gpus 8 --module inference_server.benchmark --model_name microsoft/bloom-deepspeed-inference-fp16 --model_class AutoModelForCausalLM --dtype fp16 --deployment_framework ds_inference --benchmark_cycles 5

Run this command

### Expected behavior

I want to run Blooom model through CLl.

**Comment by sgugger** [comment]
I have no idea what `inference_server.benchmark` is, maybe you should raise the issue where you found it?

**Comment by PromitHal** [comment]
@sgugger  
This the command :
 python -m inference_server.benchmark --model_name bigscience/bloom --model_class AutoModelForCausalLM --dtype bf16 --deployment_framework hf_accelerate --benchmark_cycles 5


Also when I am using the command:
  python -m inference_server.cli --model_name bigscience/bloom --model_class AutoModelForCausalLM --dtype bf16 --deployment_framework hf_accelerate --generate_kwargs '{"min_length": 100, "max_new_tokens": 100, "do_sample": false}'  


I am getting the error: No module named inference_server.cli


Both of these commands are for inference to **BLOOM a**s per their GITHUB REPO : https://github.com/huggingface/transformers-bloom-inference

**Comment by sgugger** [comment]
So raise the issue there? Again this is not an example from Accelerate and the error is linked to the launch command they provide.
