### ISSUE TITLE
Impossible to save models other than those 'prepared' (e.g., EMAModel)

### ISSUE THREAD

**Issue by sachit-menon** [huggingface/accelerate#1666]
### System Info

```Shell
- `Accelerate` version: 0.20.0
- Platform: Linux-5.15.0-1030-aws-x86_64-with-glibc2.31
- Python version: 3.10.9
- Numpy version: 1.25.0
- PyTorch version (GPU?): 2.0.1 (True)
- PyTorch XPU available: False
- System RAM: 1121.82 GB
- GPU type: NVIDIA A100-SXM4-80GB
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: fp16
        - use_cpu: False
        - num_processes: 8
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: all
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

It seems like it's not (easily) possible to save models other than the one being prepared, which will then be in `._models`. This makes using things like an EMAModel (or any other moving average model) very difficult.

In this example, a custom saving hook is used (line 309), which as is requires the EMAModel to be global and everything to be in one big script (which is incompatible with a lot of codebases).
https://github.com/huggingface/diffusers/blob/main/examples/unconditional_image_generation/train_unconditional.py

### Expected behavior

An additional optional parameter for save state pre hooks and load state pre hooks that allow for additional inputs to be specified without everything being global

(If this is a misunderstanding and there's a better way to do it I'd love to know!)

**Comment by sgugger** [comment]
I'm not too sure I understand how this is linked to Accelerate. Shouldn't you report this in Diffusers?

**Comment by sachit-menon** [comment]
Hi, sorry for the miscommunication -- the example is from diffusers, but the usage limitation stems from Accelerate. Specifically, the Accelerate saving hook functions don't give the ability to save anything other than the model that's been `prepare`d, which prevents things like exponential moving averages (a very common use case). Does that make more sense? Is there a way around this other than making everything global like in the linked example?

**Comment by sgugger** [comment]
I still don't understand what the issue is. Could you share a code reproducer?
