### ISSUE TITLE
Clarify docs for saving model for use with `.from_pretrained()`

### ISSUE THREAD

**Issue by deppen8** [huggingface/accelerate#1669]
I am fine-tuning the `Mask2FormerForUniversalSegmentation` with `accelerate`. After training, I followed the docs at [this link](https://huggingface.co/docs/accelerate/v0.20.3/en/package_reference/accelerator#saving-and-loading) to save the model.

```python
accelerator.wait_for_everyone()
unwrapped_model = accelerator.unwrap_model(model)
accelerator.save(unwrapped_model.state_dict(), "/valid/path/to/my_model.pkl")
```

When I try to load it for inference, I get an error.  

```python
model = Mask2FormerForUniversalSegmentation.from_pretrained("/valid/path/to/my_model.pkl")
```

However, after some digging, I found [this snippet](https://github.com/huggingface/transformers/blob/main/examples/pytorch/semantic-segmentation/run_semantic_segmentation_no_trainer.py#L601-L608) in one of the example files:

```python
accelerator.wait_for_everyone()
unwrapped_model = accelerator.unwrap_model(model)
unwrapped_model.save_pretrained(
    args.output_dir,
    is_main_process=accelerator.is_main_process,
    save_function=accelerator.save,
)
```
This seems to work nicely with `.from_pretrained()`.

It would be helpful to have this idiom documented officially (I couldn't find it). I'd be happy to add a PR, but I am not sure I can explain the difference between using `save_pretrained(..., is_main_process=accelerator.is_main_process, save_function=accelerator.save)` and using `accelerator.save()` directly.

**Comment by sgugger** [comment]
The first one is for generic models but the second one is indeed better for Transformer models. If you'd like to add it to the doc you mention with this note, that would be great!

**Comment by deppen8** [comment]
So that I understand: the `accelerator.save()` is for generic PyTorch models and `save_pretrained()` works better if you are saving/loading a model supported by the `transformers` library?

**Comment by sgugger** [comment]
Exactly!
