### ISSUE TITLE
Some issue about the all_gather 

### ISSUE THREAD

**Issue by 13717680252** [huggingface/accelerate#167]
Everything works fine if we pad the sentences to the same length at the stage of reading data.
However. if we fit the sentence length at the stage of collation_function, and we want to gather the prediction to the same device to do some logging/evaluation, we will get stuck. That was because the implementation is not taking this into consideration. Maybe in some version later we could see the modified implementation that fixes this? Maybe like the implementation in detectron2 https://github.com/facebookresearch/detectron2/blob/cbbc1ce26473cb2a5cc8f58e8ada9ae14cb41052/detectron2/utils/comm.py

Thanks a lot.

**Comment by sgugger** [comment]
Hi there! There is a `pad_across_processes` method you can use for this. [Here](https://github.com/huggingface/transformers/blob/04976a32dc555667afa994e8f918cbee88d84a4f/examples/pytorch/token-classification/run_ner_no_trainer.py#L540) is an example of use in a token classification script.
