### ISSUE TITLE
accelerate launch uses additional VRAM?

### ISSUE THREAD

**Issue by gameveloster** [huggingface/accelerate#1677]
When I start my lora finetuning script to run on a single 24GB VRAM GPU using accelerate

    accelerate launch --num_processes 1 finetune.py

it uses a few GiB more VRAM than if I were to run it without `accelerate launch`

    python finetune.py

And my process will OOM after the first step is completed. It does not OOM if I start it without accelerate launch. Before running the script, `nvidia-smi` reports 0 GiB VRAM usage on all GPUs.

Some other memory related configs in my script include:

```py
    max_memory = "24GiB"
    device_map = "auto"

    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        quantization_config=nf4_config,
        load_in_4bit=True,
        torch_dtype=torch.bfloat16,
        device_map=device_map,
        max_memory=max_memory,
    )
    model.gradient_checkpointing_enable()
    model.config.use_cache = False
    model.resize_token_embeddings(len(tokenizer))
```

Is it normal for `accelerate launch` to use this additional amount of VRAM? Is there any way to reduce the amount of VRAM used by accelerate?

**Comment by sgugger** [comment]
Your model is loaded on all the processes on the CPU before being moved to each device, so yes, this is normal.

**Comment by gameveloster** [comment]
@sgugger Mind helping me understand how loading the model on all processes on the `C`PU can lead to an increase in VRAM usage on the `G`PU?

I can only understand how this will increase RAM usage by the CPU, not the VRAM usage on the GPU.

**Comment by sgugger** [comment]
For the RAM on the GPU, DDP will use slightly more space than non-DDP as there are some buffers created on GPU 0 for the backward pass and the grad sync at the end of each training step. If your script used almost all the GPU RAM on one process, this might be why you get OOM using DDP.
