### ISSUE TITLE
failed to run accelerate config in colab

### ISSUE THREAD

**Issue by Erickrus** [huggingface/accelerate#1683]
### System Info

```Shell
accelerate version: 0.20.3, OS: ubuntu, python version: 3.11, Google Colab Environment
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [x] My own task or dataset (give details below)

### Reproduction

In the colab notebook:

```shell
%cd /content
!git clone https://github.com/SuLvXiangXin/zipnerf-pytorch

%cd /content/zipnerf-pytorch
!pip3 install -r requirements.txt
!pip3 install ./gridencoder
!git clone https://github.com/NVlabs/nvdiffrast
!pip3 install ./nvdiffrast
CUDA='cu118'
!pip3 install torch-scatter -f https://data.pyg.org/whl/torch-2.0.0+{CUDA}.html


!mkdir -p /content/zipnerf-pytorch/data
!cd data && wget http://storage.googleapis.com/gresearch/refraw360/360_v2.zip
!cd data && unzip 360_v2.zip

!accelerate config
```

### Expected behavior

It is impossible to run `accelerate config` on colab. This means following training step could not be completed. 
Other solution is `/root/.cache/huggingface/accelerate/default_config.yaml`, need understand the configuration in advance.
After some works, I got this solution finally:

accelerate/commands/menu/selection_menu.py

L18: 
```python3
import sys
input2 = input
in_colab = False
try:
    from google.colab import drive
    in_colab = True
except:
    pass
```

L118:
```python3
                if in_colab:
                    choice = int(input2())
                else:
                    choice = self.handle_input()
```

**Comment by muellerzr** [comment]
Correct, at the current time there isn't a way to get it working, however your solution seems to work alright. Would you like to open a PR with it @Erickrus? Otherwise I can work on a solution with it over the next few days.

**Comment by Erickrus** [comment]
I dont know what's wrong with the quality check. It seems stuck here

**Comment by Erickrus** [comment]
This issue is resolved
