### ISSUE TITLE
How to convert this for tpu ?

### ISSUE THREAD

**Issue by 1kaiser** [huggingface/accelerate#169]
https://github.com/compphoto/BoostingMonocularDepth/blob/main/run.py
As there is forward passing not backward passed, for inference in tpu

**Comment by sgugger** [comment]
Please ask questions like this on the [forums](https://discuss.huggingface.co/) as we keep issues for bugs and feature requests only.

**Comment by 1kaiser** [comment]
Yes thanks, 
Now we can speed up inference by converting torch.no_grad() +++ torch.inference_mode() 🤗🙂
