### ISSUE TITLE
`accelerate test` stuck on multi-GPU multi-nodes

### ISSUE THREAD

**Issue by mjamroz** [huggingface/accelerate#1695]
### System Info

```Shell
- `Accelerate` version: 0.20.3
- Platform: Linux-3.10.0-862.2.3.el7.x86_64-x86_64-with-glibc2.17
- Python version: 3.8.16
- Numpy version: 1.23.5
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- PyTorch XPU available: False
- System RAM: 125.64 GB
- GPU type: Tesla K40m
- `Accelerate` config passed:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - use_cpu: False
        - num_processes: 2
        - machine_rank: 0
        - num_machines: 2
        ---------> - gpu_ids: all
        - main_process_ip: 10.10.21.19
        - main_process_port: 35211
        - rdzv_backend: c10d
        - same_network: True
        - main_training_function: main
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

`accelerate test --config_file default_config.yaml` on one node, 
`accelerate test --config_file default_config1.yaml` on another. 
Difference within onfig files is `machine_rank: 0 or 1`.

It gets stuck on synchronizing random numbers - with `torch.distributed.broadcast(rng_state,0)` of `accelerate/utils/random.py`.

If change `gpu_ids` from `gpu_ids: all` or `gpu_ids: 0,1` to `gpu_ids: 0` or `gpu_ids: 1` then everything goes well.

### Expected behavior

Should pass tests, but it gets stuck on `**Test random number generator synchronization**`.

**Comment by sgugger** [comment]
You cannot use `gpu_ids: 0,1` since you want to use one GPU per machine (num_processes is 2, so that makes 1 GPU per machine). It looks like `gpu_ids: all` is not correctly interpreted in this case, cc @muellerzr

**Comment by muellerzr** [comment]
Which means there is something we're missing here. Thanks @mjamroz

**Comment by muellerzr** [comment]
@mjamroz how many GPUs do you have on each machine? One or two?

**Comment by mjamroz** [comment]
@muellerzr I've 2 gpu's per machine

**Comment by mjamroz** [comment]
test for 2 gpus on 2 hosts (total 4 gpus):

- `gpu_ids: '0,1'`, `num_processes: 4` fail
```
/state.py", line 409, in _split_values                                                                   
    result += [result[-1]] * (num_samples_per_process - len(result))                                                                                                                          
IndexError: list index out of range                                                            
```
-  `gpu_ids: 'all' `, `num_processes: 4` => fail
```
    result += [result[-1]] * (num_samples_per_process - len(result))
IndexError: list index out of range
    assert results["a"] == data_copy["a"][-1]
AssertionError

```
-  `gpu_ids: 'all'`, `num_processes: 2` => fail

stuck on `stdout: **Test random number generator synchronization**`
-  `gpu_ids: '0,1'`, `num_processes: 2` => fail

same

-  `gpu_ids: '0'`. `num_processes: 2` => OK

`Test is a success! You are ready for your distributed training!`


drop me an email if you need full logs - i don't wanna to post it here with paths and hostnames.

**Comment by muellerzr** [comment]
@mjamroz because you have multiple GPUS on each machine, you need to specify which gpu ID to use for torch distributed when not wanting to use all of them. So setting `gpu_ids: '0'` is the correct solution here. 

I'll look into the failure on 2x GPUs w/ 2x nodes, however my comment is accurate still.
