### ISSUE TITLE
I want to use Accelerator --config_file option and script argument, but not working

### ISSUE THREAD

**Issue by Muneop** [huggingface/accelerate#1703]
### System Info

```Shell
hello. 
I'm using Accelerator with yaml config file. 
I need to use python argparser. So the argument must be passed to the command line.

I attach the execution command and error below.

COMMAND : 
    accelerate launch --config_file ${ACCELERATOR_PATH} $PWD/train.py --config-path 
ERROR : 
    usage: accelerate <command> [<args>]
    Accelerate CLI tool: error: unrecognized arguments: --config-path
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

accelerate launch --config_file ${ACCELERATOR_PATH} $PWD/train.py --config-path 

### Expected behavior

NO [Accelerate CLI tool: error:]

**Comment by sgugger** [comment]
The error is that your `train.py` script does not accept the argument `--config_path`.
