### ISSUE TITLE
accelerate.log()报错

### ISSUE THREAD

**Issue by fxb392** [huggingface/accelerate#1704]
### System Info

```Shell
accelerator.log({
 "train_loss": gathered_accumulation_loss.mean().item() / train_args.gradient_accumulation_steps,
                            "epoch": epoch, })

报错：AttributeError: 'Accelerator' object has no attribute 'trackers'
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

无

### Expected behavior

无

**Comment by muellerzr** [comment]
Please run `accelerate env` and report back its output, as the issue template asked
