### ISSUE TITLE
tiiuae/falcon-7b-instruct buffers are not transferred back to CUDA when include_buffers=True

### ISSUE THREAD

**Issue by abhinavkulkarni** [huggingface/accelerate#1710]
### System Info

```Shell
Ubuntu 22.04, CUDA v11.7

$ pip freeze | grep "transformers\|accelerate"
accelerate @ git+https://github.com/huggingface/accelerate.git@95bffdec4326acf6a5d1c3dbaa857a26502aa265
transformers==4.30.2
```

### Information

- [ ] The official example scripts
- [x] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

Hi,

I have the following piece of code:

```python
from transformers import AutoModelForCausalLM, AutoTokenizer, AutoConfig, TextStreamer
from huggingface_hub import snapshot_download
import torch
from accelerate import init_empty_weights, infer_auto_device_map, load_checkpoint_and_dispatch

model_path = "tiiuae/falcon-7b-instruct"
config = AutoConfig.from_pretrained(model_path, trust_remote_code=True)
with init_empty_weights(include_buffers=True):
    model = AutoModelForCausalLM.from_config(config=config,
                                                torch_dtype=torch.float16, trust_remote_code=True)

model.tie_weights()

max_memory = {0:"4GiB", "cpu":"99GiB"}
device_map = infer_auto_device_map(model, max_memory=max_memory, 
                                   no_split_module_classes=["DecoderLayer"]
)

model = load_checkpoint_and_dispatch(
    model, snapshot_download(model_path),
    device_map=device_map,
    offload_buffers=True,
)
```

I get the error: ``ValueError: inv_freq is on the meta device, we need a `value` to put in on 0.``

The model architecture is as follows:

```
RWForCausalLM(
  (transformer): RWModel(
    (word_embeddings): Embedding(65024, 4544)
    (h): ModuleList(
      (0-31): 32 x DecoderLayer(
        (input_layernorm): LayerNorm((4544,), eps=1e-05, elementwise_affine=True)
        (self_attention): Attention(
          (maybe_rotary): RotaryEmbedding()
          (query_key_value): Linear(in_features=4544, out_features=4672, bias=False)
          (dense): Linear(in_features=4544, out_features=4544, bias=False)
          (attention_dropout): Dropout(p=0.0, inplace=False)
        )
        (mlp): MLP(
          (dense_h_to_4h): Linear(in_features=4544, out_features=18176, bias=False)
          (act): GELU(approximate='none')
          (dense_4h_to_h): Linear(in_features=18176, out_features=4544, bias=False)
        )
      )
    )
    (ln_f): LayerNorm((4544,), eps=1e-05, elementwise_affine=True)
  )
  (lm_head): Linear(in_features=4544, out_features=65024, bias=False)
)
```

The inferred `device_map` is as follows:

```
{'transformer.word_embeddings': 0,
 'lm_head': 0,
 'transformer.h.0': 0,
 'transformer.h.1': 0,
 'transformer.h.2': 0,
 'transformer.h.3': 0,
 'transformer.h.4': 0,
 'transformer.h.5': 0,
 'transformer.h.6': 0,
 'transformer.h.7': 'cpu',
 'transformer.h.8': 'cpu',
 'transformer.h.9': 'cpu',
 'transformer.h.10': 'cpu',
 'transformer.h.11': 'cpu',
 'transformer.h.12': 'cpu',
 'transformer.h.13': 'cpu',
 'transformer.h.14': 'cpu',
 'transformer.h.15': 'cpu',
 'transformer.h.16': 'cpu',
 'transformer.h.17': 'cpu',
 'transformer.h.18': 'cpu',
 'transformer.h.19': 'cpu',
 'transformer.h.20': 'cpu',
 'transformer.h.21': 'cpu',
 'transformer.h.22': 'cpu',
 'transformer.h.23': 'cpu',
 'transformer.h.24': 'cpu',
 'transformer.h.25': 'cpu',
 'transformer.h.26': 'cpu',
 'transformer.h.27': 'cpu',
 'transformer.h.28': 'cpu',
 'transformer.h.29': 'cpu',
 'transformer.h.30': 'cpu',
 'transformer.h.31': 'cpu',
 'transformer.ln_f': 'cpu'}
 ```
 
 If I set `include_buffers` and `offload_buffers` to `False`, then buffers are by default allocated on CUDA. This is a problem with loading quantized models such as GPTQ or AWQ which has significant number of buffers (related to zero-point quantization) and they are by default placed on CUDA, thus overflowing it in case the GPU is smaller.
 
 I am not sure if this is a problem with `accelerate` or something in `falcon` architecture, but it is worth looking at since `tiiuae/falcon-40b-instruct` is probably the most popular large model with a commercially viable license.
 
 Thanks!

### Expected behavior

I would expect buffers to behave the same way as parameters when they are offloaded to CPU/disk. But that is clearly not happening here.

**Comment by sgugger** [comment]
I'm not sure this can work without removing the `include_buffers=True` from the init_empty_weight context manager, unless you change the state dict you are loading to include all buffers. Here the problem is that `inv_freq` is a non-persistent buffer, so it is not included in the state dict. Therefore, we do not have a value for it and that's why you get the error in `load_checkpoint_and_dispatch`.

**Comment by abhinavkulkarni** [comment]
@sgugger: Thank you very much! I wasn't aware of persistent vs non-persistent buffers. This clears things up.

It looks like rotary embeddings used in various model architectures (including `LlamaForCausalLM`) have similar non-persistent buffers. We'll figure out on our end how to deal with these model architectures.

Thanks!
