### ISSUE TITLE
About initialization of Accelerate()

### ISSUE THREAD

**Issue by ziyaxuanyi** [huggingface/accelerate#1721]
How to specify a graphics card number for the initialization of Accelerate()?

**Comment by ziyaxuanyi** [comment]
> You cannot, but you can set the GPU ids to use when doing `accelerate config`.

So how to specify a specific config file for the initialization of Accelerate()? To my knowledge, the initialization of Accelerate() does not provide parameters that can specify a specific config file.

**Comment by muellerzr** [comment]
You need to use `accelerate launch --config_file {location} script.py ...`, as detailed in the usage guide: https://huggingface.co/docs/accelerate/basic_tutorials/launch

**Comment by ziyaxuanyi** [comment]
> You need to use `accelerate launch --config_file {location} script.py ...`, as detailed in the usage guide: https://huggingface.co/docs/accelerate/basic_tutorials/launch

Thank you for your answer. But I don't want to specify the config file in the form of a command line. I want to specify the config file in the code when initializing Accelerate(). Is there a way to achieve it?

**Comment by muellerzr** [comment]
You cannot. These are limitations in pytorch/python. For instance, another way of having to do so (launching with multiple GPUs) is `torchrun --n_proc_per_node 2 {my_script.py}`.
