### ISSUE TITLE
`set_module_tensor_to_device` has wrong shape 

### ISSUE THREAD

**Issue by ArthurZucker** [huggingface/accelerate#1729]
(created by @Narsil who was stuck outside github)
```python 
from transformers import AutoModel
from accelerate.utils import set_module_tensor_to_device
import torch

model = AutoModel.from_pretrained("gpt2")

print(model.wte.weight.shape)
A = torch.zeros((2, 2))
set_module_tensor_to_device(model, 'wte.weight', "cpu", value=A)
print(model.wte.weight.shape)
```
Potential bug:
`set_module_tensor_to_device` doesn't check shapes, meaning you can potentially load invalid checkpoints onto an already loaded model.
This is triggered here in transformers : https://github.com/huggingface/transformers/blob/main/src/transformers/modeling_utils.py#L717
Is it normal ? Is the bug here, or in transformers where we should do the shape checking ?
In anycase, if you have an invalid checkpoint vs config, there will be no error. I'm not sure this is OK.

**Comment by Narsil** [comment]
Couldn't open it myself, had SSO issues, all solved now. Thanks @ArthurZucker

**Comment by sgugger** [comment]
We can add a check for shape, happy to have a look at a PR.

**Comment by Narsil** [comment]
Done a PR ! I wasn't sure if the check belonged here or in transformers.
