### ISSUE TITLE
Expose the ``cache_enabled`` parameter option to users in accelerate

### ISSUE THREAD

**Issue by yuxinyuan** [huggingface/accelerate#1737]
As is shown [here](https://github.com/huggingface/accelerate/blob/653ba110d31c86d3527bb88bf6209441c176ce11/src/accelerate/accelerator.py#L1350C54-L1350C54), right now, when users want to use ``native_amp``, accelerate will initialize ``torch.autocast`` with default parameters and wrap the forward method of user's models. However, this prevents users from customizing the ``enable_cache`` parameter inside autocast. Considering that disabling weight cache can save more GPU memories, it would be beneficial to expose the "enable_cache" option to users.

**Comment by sgugger** [comment]
Sounds like something we could do with a KwargHandler like for DDP, cc @muellerzr

**Comment by muellerzr** [comment]
Note that you can do this if you use `Accelerator.autocast(cache_enabled=True)`, however I'll add a kwarg handler for customizing autocast
