### ISSUE TITLE
what is the possible reason for accelerate running on cuda 12.2 8xA100 with error accelerate multiprocessing.api:failed (exitcode: -9)

### ISSUE THREAD

**Issue by garychan22** [huggingface/accelerate#1743]
### System Info

```Shell
ubuntu 22.04
gpu A100 80G
cuda version 12.2
accelerate version 0.21.0
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

running the demo script from diffusers [train_text_to_image.py](https://github.com/huggingface/diffusers/tree/main/examples/text_to_image) for 100k iterations with batch size 8 each gpu, 8 A100 gpus in total

### Expected behavior

successful training without any problem

**Comment by muellerzr** [comment]
We need a full stack trace to know more

**Comment by muellerzr** [comment]
And as asked, the output of `accelerate env`

**Comment by garychan22** [comment]
@muellerzr thanks for your reply!
the full stack trace is
```
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 43837 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 43839 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 43841 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 43843 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 43844 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 1 (pid: 43838) of binary: /home/gary/miniconda3/envs/blip2/bin/python
Traceback (most recent call last):
  File "/home/gary/miniconda3/envs/blip2/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/gary/miniconda3/envs/blip2/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/gary/miniconda3/envs/blip2/lib/python3.8/site-packages/accelerate/commands/launch.py", line 970, in launch_command
    multi_gpu_launcher(args)
  File "/home/gary/miniconda3/envs/blip2/lib/python3.8/site-packages/accelerate/commands/launch.py", line 646, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/gary/miniconda3/envs/blip2/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/gary/miniconda3/envs/blip2/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/gary/miniconda3/envs/blip2/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-18_13:20:30
  host      : ubuntu-server-A205
  rank      : 1 (local_rank: 1)
  exitcode  : -9 (pid: 43838)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 43838
```

and the output of  `accelerate env` is
```
- `Accelerate` version: 0.21.0
- Platform: Linux-5.15.0-76-generic-x86_64-with-glibc2.17
- Python version: 3.8.16
- Numpy version: 1.24.4
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 1007.72 GB
- GPU type: NVIDIA A100-SXM4-80GB
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: fp16
        - use_cpu: False
        - num_processes: 1
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: all
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
```

**Comment by muellerzr** [comment]
@garychan22 I think our issue here is you have "multi-gpu" selected, when you have a single process and a single machine. You can do `vim ~/.cache/huggingface/accelerate/default_config.yaml`, then modify the `distributed_type` key to be `NO`. Let me know if that fixes this

**Comment by garychan22** [comment]
@muellerzr thanks for your help! correctly modifying the accelerate config resolved the issue.

**Comment by thedaffodil** [comment]
I have the same error.
the output of  accelerate env is : 

- `Accelerate` version: 0.20.0.dev0
- Platform: Linux-5.15.0-78-generic-x86_64-with-glibc2.35
- Python version: 3.10.12
- Numpy version: 1.24.2
- PyTorch version (GPU?): 2.0.0+cu117 (True)
- PyTorch XPU available: False
- System RAM: 31.34 GB
- GPU type: NVIDIA GeForce RTX 4090
- `Accelerate` default config:
	- compute_environment: LOCAL_MACHINE
	- distributed_type: MULTI_GPU
	- mixed_precision: no
	- use_cpu: False
	- num_processes: 2
	- machine_rank: 0
	- num_machines: 1
	- gpu_ids: all
	- rdzv_backend: static
	- same_network: True
	- main_training_function: main
	- downcast_bf16: no
	- tpu_use_cluster: False
	- tpu_use_sudo: False
	- tpu_env: []


It gives 

WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 106507 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 1 (pid: 106508) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/dilara/.local/lib/python3.10/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/home/dilara/.local/lib/python3.10/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/home/dilara/.local/lib/python3.10/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/home/dilara/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/dilara/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/dilara/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
