### ISSUE TITLE
wait_for_everyone() hangs on main process sometimes

### ISSUE THREAD

**Issue by LWprogramming** [huggingface/accelerate#1752]
### System Info

```Shell
- `Accelerate` version: 0.20.3
- Platform: Linux-5.15.0-1037-aws-x86_64-with-glibc2.31
- Python version: 3.10.12
- Numpy version: 1.25.0
- PyTorch version (GPU?): 2.0.1+cu117 (False)
- PyTorch XPU available: False
- System RAM: 68.58 GB
- `Accelerate` default config:
	- compute_environment: LOCAL_MACHINE
	- distributed_type: MULTI_GPU
	- mixed_precision: no
	- use_cpu: False
	- num_processes: 8
	- machine_rank: 0
	- num_machines: 1
	- gpu_ids: all
	- rdzv_backend: static
	- same_network: True
	- main_training_function: main
	- downcast_bf16: no
	- tpu_use_cluster: False
	- tpu_use_sudo: False
	- tpu_env: []
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

Note this requires a multi-GPU setup. I typically run with 8.

```
# environment setup
git clone git@github.com:LWprogramming/audiolm-pytorch-training.git # my training scripts
cd audiolm-pytorch-training
python3 -m venv venv
source venv/bin/activate

# pull in my print statements and install dependencies
python use_patched_audiolm.py personal_hacks # Use my personal_hacks branch (mostly just print statements added) from my fork of the official audiolm_pytorch repo.
# remember to rm -r audiolm_pytorch && rm audiolm-pytorch*.zip as well, to clear out old versions
# you may get a few missing libraries like tensorboardX but once the venv is active you can just install by hand with pip-- if I recall correctly there aren't that many of them

# Data: be sure to replace dataset_folder in the script with a folder you make with a bunch of wav files inside. See here: https://github.com/LWprogramming/audiolm-pytorch-training/blob/6783b0c4d443080b49290edc3e76c03b7b3f53cf/audiolm_pytorch_demo_laion.py#L85
# My toy dataset here consists of around 200-ish files.

# script run
CHECKPOINT_SLURM_JOB_ID=123 # or whatever else-- the results are going into folders that contain this id in their name. I'm running these with slurm but you can mock the behavior by hardcoding this variable as shown.
accelerate launch audiolm_pytorch_demo_laion.py --run_mode cocochorales_overfit_1_second --slurm_job_id $CHECKPOINT_SLURM_JOB_ID --train_or_eval train_coarse
```

### Expected behavior

The coarse transformer trains all the way to the end. After every iteration of the train loop, the `wait_for_everyone()` [call](https://github.com/LWprogramming/audiolm-pytorch/blob/ad39351d97c4c8b585759ad8b59d169ff9a1a770/audiolm_pytorch/trainer.py#L1032) runs and we see a bunch of "arrived at 2" showing up. Once the last GPU arrives, then they all print "arrived 3" at some point.

However, when we train for a sufficiently large number of steps (didn't observe the bug up to around 301 train steps, but does for 501 -- this is consistent even if I vary things a bit), the last step hangs. I see all the GPUs arrive right before the wait_for_everyone and then consistently the main GPU fails to make forward progress until it times out, while the other GPUs can proceed forward.

I haven't been able to figure out why this doesn't appear for the semantic transformer in the same codebase, which trains in pretty much the exact same way, or if the number of train steps is low enough.

More info in [here](https://github.com/lucidrains/audiolm-pytorch/issues/210). Unfortunately this isn't really a minimal reproduction but if I can't figure it out I'll go on trying to figure out a minimal case to demonstrate.

**Comment by LWprogramming** [comment]
Update: I find that waiting for everyone again, after calling `trainer.train()`, seems to [work](https://github.com/LWprogramming/audiolm-pytorch-training/commit/c2cfade7c721bb4d63451eff10367ea4f54d9323) as things print out in the order expected. I hypothesize that something might be going wrong when the non-main GPU processes reach the end of their program and exit, and as a result when main GPU comes back some signal might be getting lost, though I haven't been able to verify this hypothesis using my [test script](https://github.com/LWprogramming/audiolm-pytorch-training/commit/cafc28b950a4212f6e9ce72ce8a35ef5fb2fb070).

**Comment by LWprogramming** [comment]
Oops-- having looked at the error log (before I'd just looked at the output log), I see we do end up reaching the end of the code, but for some reason the main gpu node still sticks around and times out on... something, I'm not sure what. That's odd, because I see main process running the last line of code that I wrote if I force a wait on everyone. Maybe some cleanup not working properly?

**Comment by Lanxin1011** [comment]
> Oops-- having looked at the error log (before I'd just looked at the output log), I see we do end up reaching the end of the code, but for some reason the main gpu node still sticks around and times out on... something, I'm not sure what. That's odd, because I see main process running the last line of code that I wrote if I force a wait on everyone. Maybe some cleanup not working properly?
> 
> Edit: here's the stack trace for the timeout specifically:
> 
> ```
> [E ProcessGroupNCCL.cpp:828] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1547, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1802380 milliseconds before timing out.
> [E ProcessGroupNCCL.cpp:455] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
> [E ProcessGroupNCCL.cpp:460] To avoid data inconsistency, we are taking the entire process down.
> terminate called after throwing an instance of 'std::runtime_error'
>   what():  [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1547, OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1802380 milliseconds before timing out.
> ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 2135175) of binary: /fsx/itsleonwu/audiolm-pytorch-training/venv/bin/python3.10
> Traceback (most recent call last):
>   File "/fsx/itsleonwu/audiolm-pytorch-training/venv/bin/accelerate", line 8, in <module>
>     sys.exit(main())
>   File "/fsx/itsleonwu/audiolm-pytorch-training/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
>     args.func(args)
>   File "/fsx/itsleonwu/audiolm-pytorch-training/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 932, in launch_command
>     multi_gpu_launcher(args)
>   File "/fsx/itsleonwu/audiolm-pytorch-training/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 627, in multi_gpu_launcher
>     distrib_run.run(args)
>   File "/fsx/itsleonwu/audiolm-pytorch-training/venv/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
>     elastic_launch(
>   File "/fsx/itsleonwu/audiolm-pytorch-training/venv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
>     return launch_agent(self._config, self._entrypoint, list(args))
>   File "/fsx/itsleonwu/audiolm-pytorch-training/venv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
>     raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
> ========================================================
> audiolm_pytorch_demo_laion_7173.py FAILED
> --------------------------------------------------------
> Failures:
>   <NO_OTHER_FAILURES>
> --------------------------------------------------------
> Root Cause (first observed failure):
> [0]:
>   time      : 2023-07-22_03:34:17
>   host      : [redacted]
>   rank      : 0 (local_rank: 0)
>   exitcode  : -6 (pid: 2135175)
>   error_file: <N/A>
>   traceback : Signal 6 (SIGABRT) received by PID 2135175
> ========================================================
> ```

Hello~ Have you solved this error? I've encountered exactly the same error with yours, could you please provide me with some clues?

**Comment by LWprogramming** [comment]
I haven't figured out what exactly is going on. I worked around it by deciding to save checkpoints right before the last step, e.g. if want to train for 10k steps, then just train for 10k + 1, and if I save every 1k steps, we have a ckpt at step 10k. It's a hack for sure, but I guess it works?

**Comment by Lanxin1011** [comment]
> I haven't figured out what exactly is going on. I worked around it by deciding to save checkpoints right before the last step, e.g. if want to train for 10k steps, then just train for 10k + 1, and if I save every 1k steps, we have a ckpt at step 10k. It's a hack for sure, but I guess it works?

Thanks a lot!!! I'll try if it works for me.

**Comment by pikruse** [comment]
> > I haven't figured out what exactly is going on. I worked around it by deciding to save checkpoints right before the last step, e.g. if want to train for 10k steps, then just train for 10k + 1, and if I save every 1k steps, we have a ckpt at step 10k. It's a hack for sure, but I guess it works?
> 
> Thanks a lot!!! I'll try if it works for me.

Were you able to find a proper fix for this issue at all? I'm getting the same error when saving checkpoints.
