### ISSUE TITLE
How to use c10 backend for fault tolerance

### ISSUE THREAD

**Issue by geekyGoku** [huggingface/accelerate#1758]
Hi,

I found little to no documentation on how to use c10 backend for fault tolerance with accelerate. PyTorch seems to be having this:
https://pytorch.org/docs/stable/elastic/rendezvous.html

I am looking for fault tolerance in case of crash in few nodes, which also means adjusting batch size dynamically to account for nodes that are down.

Thanks in advance.

**Comment by muellerzr** [comment]
@geekyGoku when running `accelerate config`, you can set the `rdvz_backend` to `c10d` (or modify it in the `config.yaml`, or set it as an arg manually when doing `accelerate launch` without a config file. You'll find this arg in the CLI docs and doing `accelerate launch --multi_gpu --help`
