### ISSUE TITLE
find_tied_parameters() dose not support tied parameter in MPT models

### ISSUE THREAD

**Issue by ranchlai** [huggingface/accelerate#1761]
MPT model contains tie parameter that cannot be found because it is not  in the pattern used in `find_tied_parameters()`. So the following warning  is always thrown:

>> "The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function"

I think the kind of tied parameter used in MPT does NOT affect the computation of device_map. So throwing a  warning is not appropriate. 
 

This is [forward code](https://huggingface.co/mosaicml/mpt-7b/blob/main/modeling_mpt.py) for MPT model
```python
return_dict = return_dict if return_dict is not None else self.config.return_dict
use_cache = use_cache if use_cache is not None else self.config.use_cache
if inputs_embeds is not None:
    raise NotImplementedError('inputs_embeds has to be None (for hf/peft support).')
outputs = self.transformer(input_ids=input_ids, past_key_values=past_key_values, attention_mask=attention_mask, prefix_mask=prefix_mask, sequence_id=sequence_id, return_dict=return_dict, output_attentions=output_attentions, output_hidden_states=output_hidden_states, use_cache=use_cache)
logits = self.transformer.wte(outputs.last_hidden_state.to(self.transformer.wte.weight.device), True)
```
Maybe a quick fix by ignoring this pattern? Or simply add something like" You can ignore this if ..."  to the warning information.

**Comment by sgugger** [comment]
I'm not sure which pattern of tied weights you are talking about exactly. At the stage the warning is thrown, we can only detected tied weights by object IDs as they are all on the meta device (for an init without taking memory).

**Comment by ranchlai** [comment]
Case 1: MPT model use the same nn module `self.transformer.wte` for computing input embedding and output projection. `wte` is the shared layer and the weight is already "tied" because it's owned by the same layer.  In this case, `model.tie_weights()` has no effect and `find_tied_parameters(model) ` return empty. Then a warning is thrown requesting for  calling model.tie_weights().

Case 2: For other models, such as Whispe, `model.decoder.embed_tokens` and `model.proj_out` are two different layers sharing the same weight matrix. In this case , `model.tie_weights()`  works just fine and no warning is thrown. 

I don't know the solution to this. Maybe ignore this type of tied parameters by checking if model_input_embedding() is model.get_output_embedding().

**Comment by ranchlai** [comment]
There is a difference between and MPT-7b-chat 
```python
    def get_output_embeddings(self):
        return self.transformer.wte # directly use the input embedding
```

and MPT-7b
```python
    def get_output_embeddings(self):
        return self.transformer.output_wte # defined another module for output embedding but share weights with input embedding

```

Is it required to define tied parameter in the following way? 
```python
        self.wte = SharedEmbedding(config.vocab_size, config.d_model, device=config.init_device)
        self.output_wte = SharedEmbedding(config.vocab_size, config.d_model, device=config.init_device)
        self.output_wte.weight = self.wte.weight
```
If not required, I think we can check if model.get_input_embedding() is model.get_output_embedding() before throwing a warning.

**Comment by sgugger** [comment]
cc @SunMarc

**Comment by SunMarc** [comment]
Hi @ranchlai, the best solution would be to define the parameters separately and let us tie the weights with model.tie_weights(). This behavior happens because the attribute `tie_word_embeddings`  of `self.config` is set to `True`.  If you don't have weights to tie (which is the case right now when you use the input embedding directly), another solution would be to set `tie_word_embeddings` to `False`. 
```py
self.wte = SharedEmbedding(config.vocab_size, config.d_model, device=config.init_device)
self.output_wte = SharedEmbedding(config.vocab_size, config.d_model, device=config.init_device)

def get_input_embeddings(self):
        return self.transformer.wte 
def get_output_embeddings(self):
        return self.transformer.output_wte 
```

**Comment by ranchlai** [comment]
I see. Thanks for replying. 
One last question, does id(get_input_embeddings()) == id(get_output_embeddings()) implies tie_word_embeddings = False?

**Comment by SunMarc** [comment]
No, `tie_word_embedding` is an attribute that you can set in `MPTConfig`. The super class of `MPTConfig` is `PretrainedConfig` and the default value for `tie_word_embedding` is `True`. See [doc](https://huggingface.co/docs/transformers/main/main_classes/configuration#transformers.PretrainedConfig.tie_word_embeddings)

**Comment by ranchlai** [comment]
Thanks！will close now.
