### ISSUE TITLE
RuntimeError('Tensors must be contiguous') 

### ISSUE THREAD

**Issue by adildahlan** [huggingface/accelerate#1764]
### System Info

```Shell
Libraries:
pytorch                   2.0.1
pytorch-cuda              11.8
numpy                     1.24.3
accelerate                0.21.0
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

When using the following accelerate config my code crashes as shown in the screenshot below:
```
  1 compute_environment: LOCAL_MACHINE
  2 distributed_type: MULTI_GPU
  3 downcast_bf16: 'no'
  4 gpu_ids: all
  5 machine_rank: 0
  6 main_training_function: main
  7 mixed_precision: 'no'
  8 num_machines: 1
  9 num_processes: 1
 10 rdzv_backend: static
 11 same_network: true
 12 tpu_env: []
 13 tpu_use_cluster: false
 14 tpu_use_sudo: false
 15 use_cpu: false
 16 main_process_port: 8080
```

<img width="817" alt="image" src="https://github.com/huggingface/accelerate/assets/65319353/1518ffc5-a5d4-4296-a4ef-b6a3427f8ebd">

### Expected behavior

Whereas when using the following accelerate config, the code runs perfectly:

```
  1 compute_environment: LOCAL_MACHINE
  2 distributed_type: MULTI_GPU
  3 downcast_bf16: 'no'
  4 gpu_ids: all
  5 machine_rank: 0
  6 main_training_function: main
  7 mixed_precision: fp16
  8 num_machines: 1
  9 num_processes: 1
 10 rdzv_backend: static
 11 same_network: true
 12 tpu_env: []
 13 tpu_use_cluster: false
 14 tpu_use_sudo: false
 15 use_cpu: false
 16 main_process_port: 8080
```

Doing some online search, I came across this issue https://github.com/huggingface/transformers/issues/20942 from the transformers repo. 

Something funny is happening with mixed precision setup. I hope you could help me sort this bug out!

Thank you

**Comment by muellerzr** [comment]
Please provide us a reproducer, because the part of code mentioned there is still in the original codebase.

**Comment by adildahlan** [comment]
Thanks for your quick response! Here's my code: https://github.com/adildahlan/echo_PHTN/tree/feature/9
Unfortunately I cannot share the dataset videos as they are medical data. I hope you could still figure out the issue. 
Thank you!

**Comment by muellerzr** [comment]
Hi @adildahlan, can you try installing with `pip install git+https://github.com/huggingface/accelerate@contiguous and let me know if this solves it for you? Thanks for your patience!

**Comment by adildahlan** [comment]
Yes it worked!! Thank you @muellerzr!
Is there a way to confirm if accelerate is using AMP to train the model or not?

**Comment by muellerzr** [comment]
You can check `accelerator.mixed_precision`, though if it's set in your config it's using it so long as you use `accelerate launch`

**Comment by adildahlan** [comment]
Hello @muellerzr,
I am creating a new conda env and I am trying to install accelerate as you advised, using pip install git+https://github.com/huggingface/accelerate@contiguous, however that doesn't work anymore
<img width="1063" alt="image" src="https://github.com/huggingface/accelerate/assets/65319353/0aa6e91c-4d0f-4eb3-86ac-ee937fcefda6">

Installing accelerate using `pip install accelerate` downloads the old version that was causing the bug I reported initally, as shown below:
<img width="1060" alt="image" src="https://github.com/huggingface/accelerate/assets/65319353/77654650-dcfd-45a7-9ce3-f4712b1f503e">

I hope you could help me figure this out!

Cheers

**Comment by JorgeGF24** [comment]
Same error, when using DeepSpeed.

Accelerate config:

```
{
  "compute_environment": "LOCAL_MACHINE",
  "deepspeed_config": {
    "deepspeed_config_file": "/vol/bitbucket/jg2619/augmenting_llms/model_training/model_experiments/ds_conf.json"
  },
  "distributed_type": "DEEPSPEED",
  "fsdp_config": {},
  "machine_rank": 0,
  "main_training_function": "main",
  "num_machines": 1,
  "num_processes": 1,
  "rdzv_backend": "static",
  "same_network": false,
  "tpu_use_cluster": false,
  "tpu_use_sudo": false,
  "use_cpu": false
}
```


DeepSpeed config:

```
{
    "zero_optimization": {
        "stage": 2,
        "offload_optimizer": {
            "device": "cpu",
            "pin_memory": true
        },
        "allgather_partitions": true,
        "allgather_bucket_size": 2e8,
        "overlap_comm": true,
        "reduce_scatter": true,
        "reduce_bucket_size": 2e8,
        "contiguous_gradients": true
    },
    "fp16": {
        "enabled": "auto",
        "loss_scale": 0,
        "loss_scale_window": 1000,
        "initial_scale_power": 16,
        "hysteresis": 2,
        "min_loss_scale": 1
    },
    "optimizer": {
        "type": "AdamW",
        "params": {
            "lr": "auto",
            "betas": "auto",
            "eps": "auto",
            "weight_decay": "auto"
        }
    },

    "scheduler": {
        "type": "WarmupLR",
        "params": {
            "warmup_min_lr": "auto",
            "warmup_max_lr": "auto",
            "warmup_num_steps": "auto"
        }
    },

    "gradient_accumulation_steps": "auto",
    "gradient_clipping": "auto",
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto"
}
```

CUDA version 12.2.0
Python 3.10.12
Transformers version: 4.32.0.dev0

**Comment by muellerzr** [comment]
Please try installing from main: `pip install git+https://github.com/huggingface/accelerate`

**Comment by adildahlan** [comment]
> Please try installing from main: `pip install git+https://github.com/huggingface/accelerate`

Hello @muellerzr,
Is `pip install git+https://github.com/huggingface/accelerate` different from `pip install accelerate`? Could you please explain why?
Many thanks!

**Comment by JorgeGF24** [comment]
Just did that after installing from main, upgraded accelerate from 0.21.0 to 0.22.0.dev0, and fails with the same error.

P.S. Had to manually install a requirement (pytest) after it failed to run with couldn't find pytest error.

**Comment by Natooz** [comment]
Installing from git solved the bug in my case, using DeepSpeed stage 2 on multi-node environments, transformers v4.31.0 using the GPTJ implementation and Trainer, torch v2.0.1 cu117.

**Comment by callanwu** [comment]
You can try ``pip install accelerate>=0.22.0``.
