### ISSUE TITLE
When using other_megatron_args to try to use RoPE, met an assertion error related to max_position_embeddings

### ISSUE THREAD

**Issue by leocnj** [huggingface/accelerate#1765]
### System Info

```Shell
- `Accelerate` version: 0.21.0.dev0
- Platform: Linux-5.4.0-121-generic-x86_64-with-glibc2.31
- Python version: 3.9.0
- Numpy version: 1.20.3
- PyTorch version (GPU?): 1.12.1+cu113 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 2015.70 GB
- GPU type: NVIDIA A100-SXM4-80GB
- `Accelerate` default config:
	Not found
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

In my config file, in the section related to `megatron-lm`, add following
`other_megatron_args: {'position_embedding_type': "rotary"}`

However, when running, met the following error
```
  File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/accelerate/accelerator.py", line 1200, in prepare
    result = self._prepare_megatron_lm(*args)
  File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/accelerate/accelerator.py", line 1625, in _prepare_megatron_lm
    megatron_lm_initialize(self, args_defaults=megatron_lm_plugin.megatron_lm_default_args)
  File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/accelerate/utils/megatron_lm.py", line 860, in initialize
    validate_args(args)
  File "/root/miniconda3/envs/py39/lib/python3.9/site-packages/megatron/arguments.py", line 279, in validate_args
    assert args.max_position_embeddings is None
AssertionError
```

### Expected behavior

Such assertion error should not appear.

**Comment by sgugger** [comment]
cc @pacman100

**Comment by leocnj** [comment]
After reading source codes, I found that `max_position_embeddings` variable is always setup to a value (not None) when loading supported models, BERT, GPT2, and T5. 

https://github.com/huggingface/accelerate/blob/0b36ca6e64245b123e9455521c1bd985f4b72679/src/accelerate/utils/dataclasses.py#L1273

**Comment by leocnj** [comment]
The setup in my config file is based on [How to Use Megatron-LM](https://huggingface.co/docs/accelerate/usage_guides/megatron_lm#support-for-rope-and-alibi-positional-embeddings-and-multiquery-attention)

**Comment by leocnj** [comment]
It looks that megatron/arguments.py L279 is wrong. 
`assert args.max_position_embeddings is None`
After changing to `assert args.max_position_embeddings is not None`, RoPE can be used. 
The change has been made in this [PR](https://github.com/huggingface/Megatron-LM/pull/10)
