### ISSUE TITLE
Loss in deepspeed_with_config_support.py in examples

### ISSUE THREAD

**Issue by sakshidotvakilsearch** [huggingface/accelerate#1773]
In `accelerate/examples/by_feature/deepspeed_with_config_support.py` at line 643 (https://github.com/huggingface/accelerate/blob/a2d8f540c3ab37c8f84d616be1300a0572b69cf8/examples/by_feature/deepspeed_with_config_support.py#L643) loss is being divided with gradient accumulation steps before accelerator.backward()

Is this happening because accelerate or deepspeed internally (before or during backpass) are performing a multiplicative operation with loss & gradient accumulation steps in distributed settings or is this a mistake?

Tried checking out source code but frankly couldn't get much

**Comment by pacman100** [comment]
Hello, this is duplicate of https://github.com/huggingface/accelerate/issues/1767

**Comment by sakshidotvakilsearch** [comment]
@pacman100 when you do accelerator.accumulate() & accelerate.backward(), you are also stepping optimiser & scheduler without checking if global % grad_steps == 0 or not. Is that because accelerator.accumulate() handles it internally? If it does, does that mean accelerate tracks the global step and epochs internally?
