### ISSUE TITLE
UnicodeEncodeError in accelerate/commands/menu/helpers.py when running accelerate config

### ISSUE THREAD

**Issue by ClaudiaGiardina90** [huggingface/accelerate#1781]
### System Info

```Shell
I was trying to run "accelerate config" and this error appeared in conda (version 22.9.0) environment
Traceback (most recent call last):
  File "/home/usuaris/imatge/claudia.giardina/.conda/envs/Syn108/bin/accelerate", line 10, in <module>
    sys.exit(main())
  File "/home/usuaris/imatge/claudia.giardina/.conda/envs/Syn108/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/usuaris/imatge/claudia.giardina/.conda/envs/Syn108/lib/python3.10/site-packages/accelerate/commands/config/config.py", line 67, in config_command
    config = get_user_input()
  File "/home/usuaris/imatge/claudia.giardina/.conda/envs/Syn108/lib/python3.10/site-packages/accelerate/commands/config/config.py", line 32, in get_user_input
    compute_environment = _ask_options(
  File "/home/usuaris/imatge/claudia.giardina/.conda/envs/Syn108/lib/python3.10/site-packages/accelerate/commands/config/config_utils.py", line 58, in _ask_options
    result = menu.run(default_choice=default)
  File "/home/usuaris/imatge/claudia.giardina/.conda/envs/Syn108/lib/python3.10/site-packages/accelerate/commands/menu/selection_menu.py", line 125, in run
    self.print_choice(i)
  File "/home/usuaris/imatge/claudia.giardina/.conda/envs/Syn108/lib/python3.10/site-packages/accelerate/commands/menu/selection_menu.py", line 58, in print_choice
    forceWrite(f" {self.arrow_char} ")
  File "/home/usuaris/imatge/claudia.giardina/.conda/envs/Syn108/lib/python3.10/site-packages/accelerate/commands/menu/helpers.py", line 36, in forceWrite
    sys.stdout.write(str(content) + end)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2794' in position 1: ordinal not in range(256)
srun: error: gpic09: task 0: Exited with exit code 1

- `Accelerate` version: 0.21.0
- Platform: Linux-5.4.0-1065-aws-x86_64-with-glibc2.27
- Python version: 3.10.12
- Numpy version: 1.25.0
- PyTorch version (GPU?): 2.0.0 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 314.85 GB
- GPU type: NVIDIA TITAN X (Pascal)
- `Accelerate` default config:
        Not found


I installed accelerate using "conda install -c conda-forge accelerate"
Am I missing something or do I have to change something in order to run the configuration?token
Thanks in advance for any help someone can give me.
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

1. create a conda environment
2. install pytorch, cuda toolkit, all other necessary packages (numpy, torchvision), including accelerate
3. run accelerate config

### Expected behavior

According to the official description at the page, this should be expected:
"...and answer the questions asked. This will generate a config file that will be used automatically to properly set the default options when doing"

**Comment by muellerzr** [comment]
How did you answer each question exactly? :) (Trying to help recreate your exact inputs)

**Comment by ClaudiaGiardina90** [comment]
Hi @muellerzr , sorry, I am not getting your question :(
I solved this problem by editing line 47 of selection_menu.py 
#from
self.arrow_char = "➔ "
#to
self.arrow_char = "> "

The problem (apparently) is caused due to the language python is working with, which in my case, I cannot change. I found that export lang=utf_8 might help in other scenarios.

**Comment by muellerzr** [comment]
@ClaudiaGiardina90 do you happen to know how to get what language is being used? We can include it in the if/else here easily to show the alternative (*) https://github.com/huggingface/accelerate/blob/main/src/accelerate/commands/menu/selection_menu.py#L44-L47

**Comment by ClaudiaGiardina90** [comment]
Using os.getenv('LANG') in Linux will give the language. In my case:
>>> import os
>>> os.getenv('LANG')
'en_US'
Not sure if it works in other OS (found [this](https://stackoverflow.com/a/25691701))
I was following this [explanation](https://stackoverflow.com/a/20923794), that is why I checked the language in my console, using locale:
locale
LANG=en_US
LANGUAGE=
LC_CTYPE="en_US"
LC_NUMERIC="en_US"
LC_TIME="en_US"
LC_COLLATE="en_US"
LC_MONETARY="en_US"
LC_MESSAGES="en_US"
LC_PAPER="en_US"
LC_NAME="en_US"
LC_ADDRESS="en_US"
LC_TELEPHONE="en_US"
LC_MEASUREMENT="en_US"
LC_IDENTIFICATION="en_US"
LC_ALL=
Since I can't change the language, I kept looking for alternatives and ended up editing that line. So an if/else for those of us who work on machines with limited permissions would be very nice!
