### ISSUE TITLE
Problem about how to save memory on 2 GPU at one machine.

### ISSUE THREAD

**Issue by Kangkang625** [huggingface/accelerate#1786]
Why I run my script on one GPU at batch_size 8,nothing happened, I use the accelerate launch my script on 2 GPU at same batch_size, both process terminate because CUDA out of Memory.

Here is my config :
compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
downcast_bf16: 'no'
dynamo_config:
  dynamo_backend: INDUCTOR
gpu_ids: all
machine_rank: 0
main_training_function: main
mixed_precision: 'no'
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false

When normal run my script on one GPU, the memory util is about 23GB/24GB.
Is this config make my process use more memory?

**Comment by sgugger** [comment]
Using more than one GPU results in a slightly bigger memory use on each GPU (especially GPU 0) yes. This comes form PyTorch so there is no workaround that.
