### ISSUE TITLE
[Feature request] Identify the device id

### ISSUE THREAD

**Issue by notrichardren** [huggingface/accelerate#1788]
To identify the device id of each accelerate instance during a run, I have to utilize a workaround like the following:

```
#%%

from accelerate import Accelerator
import torch

accelerator = Accelerator()
device = accelerator.device

# Get device ID
tensor = torch.tensor([4]).to(device)
device_id = int(str(tensor.device).replace("cuda:", ""))
print(f"Device ID: {device_id}")
print(f"Number of total GPUs used: {accelerator.num_processes}")
del tensor
```

I'm trying to use accelerate to save inference from many GPUs, but want to save the inference run on each GPU in its own file.

It'd be nice to directly be able to identify the device id by running device_id = device.id.

**Comment by muellerzr** [comment]
You can use `accelerator.procesd_index` or `.local_process_index`
