### ISSUE TITLE
model.eval() uses even more memory than model.train()

### ISSUE THREAD

**Issue by jcyk** [huggingface/accelerate#1792]
Hi,

I just encountered this "weird" problem.
```python
model.eval() #-> model.train()
for batch in dataloader:
    with torch.no_grad():
        model(**batch) 
```

I got OOM using `model.eval()` but everything is fine with `model.train()`.  any possible reasons?

I am using `torch==1.13.1` and `accelerate=0.20.3` and the model is an FSDP prepared by `accelerate`.

Thanks!

**Comment by sgugger** [comment]
It will be hard to know without knowing the model you are using.
