### ISSUE TITLE
questions about using deepspeed config

### ISSUE THREAD

**Issue by nickyoungforu** [huggingface/accelerate#1795]
I have two machines with 8 graphics cards each.
when I use the following config, the accelerator.num_processes printed in the main process is 16:

compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
downcast_bf16: 'no'
gpu_ids: all
machine_rank: 0
main_process_ip: xx
main_process_port: xx
main_training_function: main
mixed_precision: fp16
num_machines: 2
num_processes: 16
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false

 when I use deepspeed config, the accelerator.num_processes printed in the main process is 8,  and after calling the prepare(dataloader) function, the data is also divided into 8 parts instead of 16 parts.
the config is following:

compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_config_file: ds_config.json
  deepspeed_multinode_launcher: pdsh
  zero3_init_flag: true
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_process_ip: xx
main_process_port: xx
main_training_function: main
num_machines: 2
num_processes: 16
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false

ds_config.json:
`
{
    "fp16": {
        "enabled": true
    },
    "zero_optimization": {
        "stage": 1,
        "reduce_bucket_size": 5e8
    },
    "gradient_clipping": "auto",
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "gradient_accumulation_steps": 10,
    "steps_per_print": 10
}
`
I understand that the accelerator.num_processes here should also be equal to 16, right?
It seems that there is no communication between the two machines, but each uses 8 graphics cards for training.

Then I added a hostfile config now:
deepspeed_hostfile: hostfile 

hostfile:
ip1 slots=8
ip2 slots=8
and encountering the following error "subprocess.CalledProcessError: Command 'ssh -o PasswordAuthentication=no ip1 hostname' returned non-zero exit status 255."

**Comment by sgugger** [comment]
cc @pacman100

**Comment by pacman100** [comment]
Hello, you need to enable passwordless ssh between the 2 nodes to use `pdsh`. Read more about it in the official DeepSpeed documentation here: https://www.deepspeed.ai/getting-started/#resource-configuration-multi-node

I had to do the below steps when using pdsh. Hope this helps.

![Screenshot 2023-08-01 at 3 02 50 PM](https://github.com/huggingface/accelerate/assets/13534540/df0e27c3-5bca-404c-899b-a3e73e7f2d60)

**Comment by ncoop57** [comment]
What is using passwordless ssh is not possible? Is there a way to have accelerate pass the no_ssh_check flag to deepspeed easily?

https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/launcher/runner.py#L148

This works using pure neox megatron w/ deepspeed, but I've been trying to figure out how to enable it via accelerate and haven't had success

**Comment by ncoop57** [comment]
CC @pacman100 @muellerzr
