### ISSUE TITLE
Bug: Invalid arguments

### ISSUE THREAD

**Issue by stancld** [huggingface/accelerate#18]
Following to my PR to `transformers` repo, I've tried tested multi-GPU and multi-machine setting and got these two errors:
```
accelerate <command> [<args>] launch: error: argument --main_process_ip: invalid typing.Union[str, NoneType] value: {some_ip_address}
```
and
```
accelerate <command> [<args>] launch: error: argument --main_process_port: invalid typing.Union[int, NoneType] value: '{some_port_value}'
```

It seems to me this error can be fixed with changing `type=Optional[str] -> type=str` for `--main_process_ip` arg and `type=Optional[int] -> type=int` for `--main_process_port` arg.

@sgugger

**Comment by sgugger** [comment]
Fixed in [this commit](https://github.com/huggingface/accelerate/commit/703c702ecb8418c4ded398833973df64b6644e14). Thanks for flagging!
