### ISSUE TITLE
I want to use multi-node training, but the process is stuck.

### ISSUE THREAD

**Issue by pixeli99** [huggingface/accelerate#1804]
![image](https://github.com/huggingface/accelerate/assets/46072190/34e86cc0-ca7e-4c42-a4d5-dbc814bfe666)
![image](https://github.com/huggingface/accelerate/assets/46072190/fdb99324-f1a4-4e47-96f8-2fe65b9f12ff)

The thing is, I use multiple machines, 2x6 A100, to train controlnet, but I don't quite understand why the process gets stuck where I marked the red box and can't move on.

When I checked what cpu was doing when I was stuck, I found that ```output clock_gettime()```(using `strace -p 33104`)

I'm not sure how to solve this problem, which bothers me for a long time. I guess it's main process first's problem, so I got rid of it, which does keep the program running, but I don't understand the principle, and he will continue to get stuck as the following picture shows.
![image](https://github.com/huggingface/accelerate/assets/46072190/3076a5cf-ad49-4810-8ad9-9faff26c44f2)
code here https://github.com/huggingface/diffusers/blob/main/examples/controlnet/train_controlnet_sdxl.py

**Comment by pixeli99** [comment]
Maybe set this will work? but I don't know why(for DeepSpeed pdsh)
```
NCCL_IB_DISABLE=1
NCCL_SOCKET_IFNAME=eth0
```

**Comment by muellerzr** [comment]
@pixeli99 per https://github.com/huggingface/diffusers/issues/4430, IIUC if you remove the `main_process_first` it will run fine?

**Comment by muellerzr** [comment]
Perhaps try this solution? https://github.com/huggingface/accelerate/issues/1622#issuecomment-1661669225

**Comment by pixeli99** [comment]
> 1622 (comment)

I will try this.

If successful, I will update it in a timely manner.

In addition, speaking of what you said, if I remove the `main_process_first`, the code will not block but get stuck at the `accelerator.prepare(model)`.

**Comment by muellerzr** [comment]
@pixeli99 please provide us the output of `accelerate env` so I can see your configuration please? This is immensely important

**Comment by pixeli99** [comment]
Here

```
Copy-and-paste the text below in your GitHub issue

- `Accelerate` version: 0.21.0
- Platform: Linux-3.10.0-1160.el7.x86_64-x86_64-with-glibc2.31
- Python version: 3.10.9
- Numpy version: 1.25.1
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 1007.61 GB
- GPU type: NVIDIA A800-SXM4-80GB
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: fp16
        - use_cpu: False
        - num_processes: 16
        - machine_rank: 0
        - num_machines: 2
        - gpu_ids: all
        - main_process_ip: 172.23.31.46
        - main_process_port: 23456
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
```

**Comment by HLImg** [comment]
> 也许尝试这个解决方案？[第1622章（评论）](https://github.com/huggingface/accelerate/issues/1622#issuecomment-1661669225)

I encountered the same issue, and there was no NCCL error message. When training on two machines, the program gets stuck at the prepare(model) part. Of course, my prepare(model) is in another class, which can be seen on [code](https://github.com/HLImg/PictoRestore/blob/master/source/model/base_model.py).

*Under the same environment, in another code (where the network model is initialized and close to the program execution entry point), distributed training can be performed. *

```yaml
compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
downcast_bf16: 'no'
gpu_ids: 0, 1, 2, 3, 4, 5, 6, 7
machine_rank: 0 
main_process_ip: xxxxxxx
main_process_port : 29506
main_training_function: main
mixed_precision: 'no'
num_machines: 2 
num_processes: 8
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

**Comment by Willmish** [comment]
Heyo, bumping this up as I got the exact same issue, using this example: https://github.com/huggingface/accelerate/blob/main/examples/by_feature/fsdp_with_peak_mem_tracking.py#L198 , and this is my `accelerate env` output:
```
- `Accelerate` version: 0.31.0
- Platform: Linux-3.10.0-1160.114.2.el7.x86_64-x86_64-with-glibc2.17
- `accelerate` bash location: /state/partition1/scratch0/sduchnie/venv/bin/accelerate
- Python version: 3.9.5
- Numpy version: 1.26.4
- PyTorch version (GPU?): 2.3.1+cu121 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- PyTorch MLU available: False
- System RAM: 503.64 GB
- GPU type: NVIDIA RTX A6000
- `Accelerate` config passed:
	- compute_environment: LOCAL_MACHINE
	- distributed_type: FSDP
	- mixed_precision: no
	- use_cpu: False
	- debug: True
	- num_processes: 3
	- machine_rank: 0
	- num_machines: 1
	- rdzv_backend: static
	- same_network: True
	- main_training_function: main
	- enable_cpu_affinity: False
	- fsdp_config: {'fsdp_activation_checkpointing': False, 'fsdp_auto_wrap_policy': 'TRANSFORMER_BASED_WRAP', 'fsdp_backward_prefetch': 'BACKWARD_PRE', 'fsdp_cpu_ram_efficient_loading': True, 'fsdp_forward_prefetch': True, 'fsdp_offload_params': False, 'fsdp_sharding_strategy': 'FULL_SHARD', 'fsdp_state_dict_type': 'SHARDED_STATE_DICT', 'fsdp_sync_module_states': True, 'fsdp_use_orig_params': True}
	- downcast_bf16: no
	- tpu_use_cluster: False
	- tpu_use_sudo: False
	- tpu_env: []
```

**Comment by ioeddk** [comment]
I'm having exactlu the same issue. I can run the same script with `accelerate launch` on a SLURM session with single GPU. However, the same `accelerate launch --multi_gpu --gpu_ids 0,1 --num_processes 2` hangs at the `.prepare()` step. The following is my accelerate env:
```
- `Accelerate` version: 0.33.0
- Platform: Linux-5.15.0-119-generic-x86_64-with-glibc2.35
- `accelerate` bash location: /home/yingqi/miniconda3/envs/llm/bin/accelerate
- Python version: 3.10.14
- Numpy version: 1.26.4
- PyTorch version (GPU?): 2.4.0+rocm6.1 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- PyTorch MLU available: False
- PyTorch MUSA available: False
- System RAM: 503.70 GB
- GPU type: AMD Instinct MI210
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: no
        - use_cpu: False
        - debug: True
        - num_processes: 2
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: all
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - enable_cpu_affinity: False
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
```
