### ISSUE TITLE
Conflict between notebook_launcher function and bitsandbytes package.

### ISSUE THREAD

**Issue by looperEit** [huggingface/accelerate#1807]
When I was fine-tuning baichuan13b, I found a problem. If I want to use accelerate for training, if I import the bitsandbytes package, an error will be reported when using accelerate for training.
This is because the `notebook_launcher` function checks` torch.cuda.is_initialized()`. If this variable is true, an error will be reported:

ckpt_path = 'baichuan13b_ner'

optimizer = bnb.optim.adamw.AdamW(peft_model.parameters(),
                                  lr=6e-05,is_paged=True)  #'paged_adamw'

keras_model = KerasModel(peft_model, loss_fn =None,  optimizer=optimizer)

keras_model.load_ckpt(ckpt_path)

keras_model.fit_ddp(num_processes=2,
                    train_data=dl_train,
                    val_data=dl_val,
                    epochs=100,
                    patience=10,
                    monitor='val_loss',
                    mode='min',
                    ckpt_path=ckpt_path)

>  ---------------------------------------------------------------------------
>  ValueError                                Traceback (most recent call last)
>  Cell In[30], line 12
>        9 keras_model.load_ckpt(ckpt_path)
>       11 # 使用多GPU训练
>  ---> 12 keras_model.fit_ddp(num_processes=2,
>       13                     train_data=dl_train,
>       14                     val_data=dl_val,
>       15                     epochs=100,
>       16                     patience=10,
>       17                     monitor='val_loss',
>       18                     mode='min',
>       19                     ckpt_path=ckpt_path)
>  
>  File ~/anaconda3/envs/baichuan13b/lib/python3.9/site-packages/torchkeras/kerasmodel.py:282, in KerasModel.fit_ddp(self, num_processes, train_data, val_data, epochs, ckpt_path, patience, monitor, mode, callbacks, plot, wandb, quiet, mixed_precision, cpu, gradient_accumulation_steps)
>      279 from accelerate import notebook_launcher
>      280 args = (train_data,val_data,epochs,ckpt_path,patience,monitor,mode,
>      281     callbacks,plot,wandb,quiet,mixed_precision,cpu,gradient_accumulation_steps)
>  --> 282 notebook_launcher(self.fit, args, num_processes=num_processes)
>  
>  File ~/anaconda3/envs/baichuan13b/lib/python3.9/site-packages/accelerate/launchers.py:116, in notebook_launcher(function, args, num_processes, mixed_precision, use_port)
>      113 from torch.multiprocessing.spawn import ProcessRaisedException
>      115 if len(AcceleratorState._shared_state) > 0:
>  --> 116     raise ValueError(
>      117         "To launch a multi-GPU training from your notebook, the `Accelerator` should only be initialized "
>      118         "inside your training function. Restart your notebook and make sure no cells initializes an "
>      119         "`Accelerator`."
>      120     )
>      122 if torch.cuda.is_initialized():
>      123     raise ValueError(
>      124         "To launch a multi-GPU training from your notebook, you need to avoid running any instruction "
>      125         "using `torch.cuda` in any cell. Restart your notebook and make sure no cells use any CUDA "
>      126         "function."
>      127     )
>  
>  ValueError: To launch a multi-GPU training from your notebook, the `Accelerator` should only be initialized inside your training function. Restart your notebook and make sure no cells initializes an `Accelerator`.
> 

But as long as the `bitsandbytes` related package is imported,` torch.cuda.is_initialized()` will be set to true. So it may not be possible to run multiple cards in a notebook. I also tried to put it in the py file, but because the model is a quantized version, it will report an error that the 8-bit moel cannot run on multiple cards.

How should this be resolved?

**Comment by sgugger** [comment]
If you have loaded your model on multiple GPUs, you can't finetune it with DDP, those are incompatible (you have used your GPUs to split the model, you can't split the data on top of that without using DeepSpeed or FSDP).

**Comment by looperEit** [comment]
> 如果您已在多个 GPU 上加载模型，则无法使用 DDP 对其进行微调，这些是不兼容的（您已使用 GPU 来拆分模型，如果不使用 DeepSpeed 或 FSDP，则无法在此基础上拆分数据） 。

Thanks.
I'm using code like this in my model:

> import bits and bytes as bnb
> def find_all_linear_names(model):
>      """
>      Find all fully connected layers and add adapters for all fully connected layers
>      """
>      cls = bnb.nn.Linear4bit
>      lora_module_names = set()
>      for name, module in model.named_modules():
>          if isinstance(module, cls):
>              names = name. split('.')
>              lora_module_names.add(names[0] if len(names) == 1 else names[-1])
> 
>      if 'lm_head' in lora_module_names: # needed for 16-bit
>          lora_module_names. remove('lm_head')
>      return list(lora_module_names)

Then use the following function for training:

>      def fit_ddp(self, num_processes, train_data,
>              val_data=None, epochs=10, ckpt_path='checkpoint',
>              patience=5, monitor="val_loss", mode="min", callbacks=None,
>              plot=True, wandb=False, quiet=None,
>              mixed_precision='no', cpu=False, gradient_accumulation_steps=1
>             ):
>          from accelerate import notebook_launcher
>          args = (train_data, val_data, epochs, ckpt_path, patience, monitor, mode,
>              callbacks,plot,wandb,quiet,mixed_precision,cpu,gradient_accumulation_steps)
>          notebook_launcher(self.fit, args, num_processes=num_processes)
>          dfhistory = torch.load('dfhistory.pt')
>          return dfhistory

The connection of torchkeras is as follows:https://github.com/lyhue1991/torchkeras
as long as the bitsandbytes related package is imported, torch.cuda.is_initialized() will be set to true. 
How should this be resolved?

**Comment by muellerzr** [comment]
You need to import your bitsandbytes package information in your fit function (or some place where it is not called/imported before the `notebook_launcher`), as cuda cannot be initialized before launching, that is an unavoidable limitation

**Comment by AisingioroHao0** [comment]
@muellerzr Hello, I have a similar problem. And I found that when I import anything from accelerate, torch.cuda.is_initialized() becomes True. Or even "from accelerate import notebook_launcher".  Is this a bug?

**Comment by muellerzr** [comment]
In that case it's a bug. Thanks!

**Comment by muellerzr** [comment]
@AisingioroHao0 can you show me `pip freeze`?

**Comment by AisingioroHao0** [comment]
@muellerzr Sure.
```shell
absl-py==1.4.0
accelerate==0.21.0
aiohttp==3.8.5
aiosignal==1.3.1
anyio==3.7.1
appdirs==1.4.4
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
array-record==0.4.0
arrow==1.2.3
asttokens @ file:///home/conda/feedstock_root/build_artifacts/asttokens_1670263926556/work
async-lru==2.0.3
async-timeout==4.0.2
attrs==23.1.0
Babel==2.12.1
backcall @ file:///home/conda/feedstock_root/build_artifacts/backcall_1592338393461/work
backports.functools-lru-cache @ file:///home/conda/feedstock_root/build_artifacts/backports.functools_lru_cache_1687772187254/work
beautifulsoup4==4.12.2
bitsandbytes==0.41.0
bleach==6.0.0
brotlipy==0.7.0
cachetools==5.3.1
certifi==2023.5.7
cffi @ file:///work/ci_py311/cffi_1676822533496/work
charset-normalizer==3.2.0
click==8.1.6
cmake==3.27.0
contourpy==1.1.0
cryptography @ file:///croot/cryptography_1686613057838/work
cycler==0.11.0
datasets==2.14.0
debugpy @ file:///work/ci_py311/debugpy_1676824903649/work
decorator @ file:///home/conda/feedstock_root/build_artifacts/decorator_1641555617451/work
defusedxml==0.7.1
diffusers @ git+https://github.com/huggingface/diffusers.git@d8bc1a4e5124cd70fede43ad6ce4aa4095f07de3
dill==0.3.6
dm-tree==0.1.8
docker-pycreds==0.4.0
etils==1.3.0
executing @ file:///home/conda/feedstock_root/build_artifacts/executing_1667317341051/work
fastjsonschema==2.18.0
filelock==3.12.2
fonttools==4.41.1
fqdn==1.5.1
frozenlist==1.4.0
fsspec==2023.6.0
ftfy==6.1.1
gitdb==4.0.10
GitPython==3.1.32
gmpy2 @ file:///work/ci_py311/gmpy2_1676839849213/work
google-auth==2.22.0
google-auth-oauthlib==1.0.0
googleapis-common-protos==1.59.1
grpcio==1.56.2
huggingface-hub==0.16.4
idna @ file:///work/ci_py311/idna_1676822698822/work
imageio==2.31.1
importlib-metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1688754491823/work
importlib-resources==6.0.0
ipykernel @ file:///home/conda/feedstock_root/build_artifacts/ipykernel_1655369107642/work
ipython @ file:///home/conda/feedstock_root/build_artifacts/ipython_1685727741709/work
ipython-genutils==0.2.0
ipywidgets==8.0.7
isoduration==20.11.0
jedi @ file:///home/conda/feedstock_root/build_artifacts/jedi_1669134318875/work
Jinja2 @ file:///work/ci_py311/jinja2_1676823587943/work
json5==0.9.14
jsonpointer==2.4
jsonschema==4.18.4
jsonschema-specifications==2023.7.1
jupyter==1.0.0
jupyter-console==6.6.3
jupyter-events==0.6.3
jupyter-lsp==2.2.0
jupyter_client @ file:///home/conda/feedstock_root/build_artifacts/jupyter_client_1687700988094/work
jupyter_core @ file:///home/conda/feedstock_root/build_artifacts/jupyter_core_1669775069513/work
jupyter_server==2.7.0
jupyter_server_terminals==0.4.4
jupyterlab==4.0.3
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.8
jupyterlab_server==2.24.0
kiwisolver==1.4.4
lazy_loader==0.3
lit==16.0.6
Markdown==3.4.3
MarkupSafe==2.1.3
matplotlib==3.7.2
matplotlib-inline @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-inline_1660814786464/work
mistune==3.0.1
mkl-fft==1.3.6
mkl-random @ file:///work/mkl/mkl_random_1682950433854/work
mkl-service==2.4.0
mpmath==1.2.1
multidict==6.0.4
multiprocess==0.70.14
mypy-extensions==1.0.0
nbclient==0.8.0
nbconvert==7.7.2
nbformat==5.9.1
nest-asyncio @ file:///home/conda/feedstock_root/build_artifacts/nest-asyncio_1664684991461/work
networkx==3.1
ninja==1.11.1
notebook==7.0.0
notebook_shim==0.2.3
numpy==1.25.1
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
oauthlib==3.2.2
opencv-python-headless==4.8.0.74
overrides==7.3.1
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1681337016113/work
pandas==2.0.3
pandocfilters==1.5.0
parso @ file:///home/conda/feedstock_root/build_artifacts/parso_1638334955874/work
pathtools==0.1.2
pexpect @ file:///home/conda/feedstock_root/build_artifacts/pexpect_1667297516076/work
pickleshare @ file:///home/conda/feedstock_root/build_artifacts/pickleshare_1602536217715/work
Pillow==10.0.0
prometheus-client==0.17.1
promise==2.3
prompt-toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1688565951714/work
protobuf==4.23.4
psutil==5.9.5
ptyprocess @ file:///home/conda/feedstock_root/build_artifacts/ptyprocess_1609419310487/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
pure-eval @ file:///home/conda/feedstock_root/build_artifacts/pure_eval_1642875951954/work
pyarrow==12.0.1
pyasn1==0.5.0
pyasn1-modules==0.3.0
pyclipper==1.3.0.post4
pycparser @ file:///tmp/build/80754af9/pycparser_1636541352034/work
Pygments @ file:///home/conda/feedstock_root/build_artifacts/pygments_1681904169130/work
pyOpenSSL @ file:///croot/pyopenssl_1678965284384/work
pyparsing==3.0.9
pyre-extensions==0.0.29
PySocks @ file:///work/ci_py311/pysocks_1676822712504/work
pytesseract==0.3.10
python-bidi==0.4.2
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
python-json-logger==2.0.7
pytz==2023.3
PyWavelets==1.4.1
PyYAML==6.0.1
pyzmq @ file:///croot/pyzmq_1686601365461/work
qtconsole==5.4.3
QtPy==2.3.1
referencing==0.30.0
regex==2023.6.3
requests==2.31.0
requests-oauthlib==1.3.1
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rpds-py==0.9.2
rsa==4.9
safetensors==0.3.1
scikit-image==0.21.0
scipy==1.11.1
Send2Trash==1.8.2
sentry-sdk==1.28.1
setproctitle==1.3.2
shapely==2.0.1
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
smmap==5.0.0
sniffio==1.3.0
soupsieve==2.4.1
stack-data @ file:///home/conda/feedstock_root/build_artifacts/stack_data_1669632077133/work
sympy==1.12
tensorboard==2.13.0
tensorboard-data-server==0.7.1
tensorflow-datasets==4.9.2
tensorflow-metadata==1.13.1
termcolor==2.3.0
terminado==0.17.1
tifffile==2023.7.18
tinycss2==1.2.1
tokenizers==0.13.3
toml==0.10.2
torch==2.0.1
torchaudio==2.0.2
torchvision==0.15.2
tornado @ file:///work/ci_py311/tornado_1676823418767/work
tqdm==4.65.0
traitlets @ file:///home/conda/feedstock_root/build_artifacts/traitlets_1675110562325/work
transformers==4.31.0
triton==2.0.0
typing-inspect==0.9.0
typing_extensions @ file:///croot/typing_extensions_1686601443660/work
tzdata==2023.3
uri-template==1.3.0
urllib3 @ file:///croot/urllib3_1686163155763/work
wandb==0.15.5
wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1673864653149/work
webcolors==1.13
webencodings==0.5.1
websocket-client==1.6.1
Werkzeug==2.3.6
widgetsnbextension==4.0.8
wrapt==1.15.0
xformers==0.0.20
xxhash==3.2.0
yarl==1.9.2
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1689374466814/work
```

**Comment by muellerzr** [comment]
(Afk currently) if you uninstall bitsandbytes, does it solve it?

**Comment by AisingioroHao0** [comment]
@muellerzr I tried, if I uninstall bitsandbytes, at least I import from accelerate no longer initialize cuda. But it looks like there are other packages out there." RuntimeError:  CUDA has been initialized before the `notebook_launcher` could create a forked subprocess. This likely stems from an  outside import causing issues once the `notebook_launcher()` is called. Please review your imports and test them when  running the 'notebook_launcher()' to identify which one is problematic." Let me check

**Comment by AisingioroHao0** [comment]
@muellerzr Is running to "accelerator = (
accelerate.Accelerator(...)" starts throwing errors. I checked after each import with "torch.cuda.is_initialized()". Both are False, so it looks fine.

**Comment by muellerzr** [comment]
Yep so it's the new version of `bitsandbytes` that's initializing CUDA on import. Thanks, looking into some fixes

**Comment by AisingioroHao0** [comment]
@muellerzr Maybe not only bitsandbytes, but other packages that execute notebook_launch in the accelerate source code are imort to initialize CUDA as well. Because I've uninstalled bitsandbytes and still get "RuntimeError: CUDA has been initialized before the notebook_launcher could create a forked subprocess. This likely stems from an  outside import causing issues once the notebook_launcher() is called. Please review your imports and test them when  running the 'notebook_launcher()' to identify which one is problematic."

**Comment by muellerzr** [comment]
I can't recreate this happening upon importing `notebook_launcher`, it stems from `bnb` and a PR is up now. To solve this you can try installing accelerate via `pip install git+https://github.com/huggingface/accelerate@bnb-import`

**Comment by looperEit** [comment]
> I can't recreate this happening upon importing `notebook_launcher`, it stems from `bnb` and a PR is up now. To solve this you can try installing accelerate via `pip install git+https://github.com/huggingface/accelerate@bnb-import`

That means don't import the `bitsandbytes` package when using it？
There is my `pip freeze`:

> absl-py==1.4.0
> accelerate @ git+https://github.com/huggingface/accelerate@0dec477985584f37e4abde0d6b7f6f47a2a3b9f5
> aiofiles==23.1.0
> aiohttp==3.8.5
> aiosignal==1.3.1
> altair==5.0.1
> anyio==3.7.1
> argon2-cffi==21.3.0
> argon2-cffi-bindings==21.2.0
> arrow==1.2.3
> asttokens==2.2.1
> async-lru==2.0.4
> async-timeout==4.0.2
> attrs==23.1.0
> Babel==2.12.1
> backcall==0.2.0
> beautifulsoup4==4.12.2
> bitsandbytes==0.39.1
> bleach==6.0.0
> cachetools==5.3.1
> certifi==2023.7.22
> cffi==1.15.1
> charset-normalizer==3.2.0
> click==8.1.6
> cmake==3.27.0
> comm==0.1.3
> contourpy==1.1.0
> cycler==0.11.0
> datasets==2.14.2
> debugpy==1.6.7
> decorator==5.1.1
> defusedxml==0.7.1
> dill==0.3.7
> exceptiongroup==1.1.2
> executing==1.2.0
> fastapi==0.95.1
> fastjsonschema==2.18.0
> ffmpy==0.3.1
> filelock==3.12.2
> fire==0.5.0
> fonttools==4.42.0
> fqdn==1.5.1
> frozenlist==1.4.0
> fsspec==2023.6.0
> google-auth==2.22.0
> google-auth-oauthlib==1.0.0
> gradio==3.39.0
> gradio_client==0.3.0
> grpcio==1.56.2
> h11==0.14.0
> httpcore==0.17.3
> httpx==0.24.1
> huggingface-hub==0.16.4
> idna==3.4
> importlib-metadata==6.8.0
> importlib-resources==6.0.0
> ipykernel==6.25.0
> ipython==8.14.0
> ipython-genutils==0.2.0
> ipywidgets==8.0.7
> isoduration==20.11.0
> jedi==0.19.0
> jieba==0.42.1
> Jinja2==3.1.2
> joblib==1.3.1
> json5==0.9.14
> jsonpointer==2.4
> jsonschema==4.18.4
> jsonschema-specifications==2023.7.1
> jupyter==1.0.0
> jupyter-console==6.6.3
> jupyter-events==0.6.3
> jupyter-lsp==2.2.0
> jupyter_client==8.3.0
> jupyter_core==5.3.1
> jupyter_server==2.7.0
> jupyter_server_terminals==0.4.4
> jupyterlab==4.0.3
> jupyterlab-pygments==0.2.2
> jupyterlab-widgets==3.0.8
> jupyterlab_server==2.24.0
> kiwisolver==1.4.4
> linkify-it-py==2.0.2
> lit==16.0.6
> llmtuner==0.1.3
> longling==1.3.36
> Markdown==3.4.4
> markdown-it-py==2.2.0
> MarkupSafe==2.1.3
> matplotlib==3.7.2
> matplotlib-inline==0.1.6
> mdit-py-plugins==0.3.3
> mdurl==0.1.2
> mistune==3.0.1
> mpmath==1.3.0
> multidict==6.0.4
> multiprocess==0.70.15
> nbclient==0.8.0
> nbconvert==7.7.3
> nbformat==5.9.1
> nest-asyncio==1.5.7
> networkx==3.1
> nltk==3.8.1
> notebook==7.0.0
> notebook_shim==0.2.3
> numpy==1.25.1
> nvidia-cublas-cu11==11.10.3.66
> nvidia-cublas-cu12==12.2.4.5
> nvidia-cuda-cupti-cu11==11.7.101
> nvidia-cuda-nvrtc-cu11==11.7.99
> nvidia-cuda-runtime-cu11==11.7.99
> nvidia-cuda-runtime-cu12==12.2.128
> nvidia-cudnn-cu11==8.5.0.96
> nvidia-cudnn-cu12==8.9.2.26
> nvidia-cufft-cu11==10.9.0.58
> nvidia-curand-cu11==10.2.10.91
> nvidia-cusolver-cu11==11.4.0.1
> nvidia-cusparse-cu11==11.7.4.91
> nvidia-nccl-cu11==2.14.3
> nvidia-nvtx-cu11==11.7.91
> oauthlib==3.2.2
> orjson==3.9.2
> overrides==7.3.1
> packaging==23.1
> pandas==2.0.3
> pandocfilters==1.5.0
> parso==0.8.3
> peft @ git+https://github.com/huggingface/peft@b10a8cedf612e3994dc67fe8dad2a40c9076bcd4
> pexpect==4.8.0
> pickleshare==0.7.5
> Pillow==10.0.0
> platformdirs==3.10.0
> prometheus-client==0.17.1
> prompt-toolkit==3.0.39
> protobuf==4.23.4
> psutil==5.9.5
> ptyprocess==0.7.0
> pure-eval==0.2.2
> pyarrow==12.0.1
> pyasn1==0.5.0
> pyasn1-modules==0.3.0
> pycparser==2.21
> pydantic==1.10.11
> pydub==0.25.1
> Pygments==2.15.1
> pyparsing==3.0.9
> python-dateutil==2.8.2
> python-json-logger==2.0.7
> python-multipart==0.0.6
> pytz==2023.3
> PyYAML==6.0.1
> pyzmq==25.1.0
> qtconsole==5.4.3
> QtPy==2.3.1
> rarfile==4.0
> referencing==0.30.0
> regex==2023.6.3
> requests==2.31.0
> requests-oauthlib==1.3.1
> rfc3339-validator==0.1.4
> rfc3986-validator==0.1.1
> rouge-chinese==1.0.3
> rpds-py==0.9.2
> rsa==4.9
> safetensors==0.3.1
> scikit-learn==1.3.0
> scipy==1.11.1
> semantic-version==2.10.0
> Send2Trash==1.8.2
> sentencepiece==0.1.99
> six==1.16.0
> sniffio==1.3.0
> soupsieve==2.4.1
> sse-starlette==1.6.1
> stack-data==0.6.2
> starlette==0.26.1
> sympy==1.12
> tensorboard==2.13.0
> tensorboard-data-server==0.7.1
> tensorrt==8.6.1
> tensorrt-bindings==8.6.1
> tensorrt-libs==8.6.1
> termcolor==2.3.0
> terminado==0.17.1
> threadpoolctl==3.2.0
> tiktoken==0.4.0
> tinycss2==1.2.1
> tokenizers==0.13.3
> toml==0.10.2
> tomli==2.0.1
> toolz==0.12.0
> torch==2.0.1
> torchkeras @ git+https://github.com/lyhue1991/torchkeras@90172d62e12c20f4e7936a89aa6b548ed85d1a89
> torchvision==0.15.2
> tornado==6.3.2
> tqdm==4.65.0
> traitlets==5.9.0
> transformers==4.30.2
> transformers-stream-generator==0.0.4
> triton==2.0.0
> trl==0.5.0
> typing_extensions==4.7.1
> tzdata==2023.3
> uc-micro-py==1.0.2
> uri-template==1.3.0
> urllib3==1.26.16
> uvicorn==0.23.2
> wcwidth==0.2.6
> webcolors==1.13
> webencodings==0.5.1
> websocket-client==1.6.1
> websockets==11.0.3
> Werkzeug==2.3.6
> widgetsnbextension==4.0.8
> xxhash==3.3.0
> yarl==1.9.2
> zipp==3.16.2

**Comment by muellerzr** [comment]
Or import it in the function that you send to notebook_launcher. But correct. (The mentioned PR adjusts accelerate so it can be used)

**Comment by looperEit** [comment]
> 你需要在你的 fit 函数中导入你的bitsandbytes包信息（或者在之前没有被调用/导入的地方`notebook_launcher`），因为cuda在启动之前无法初始化，这是一个不可避免的限制

Sorry to bother you, I don't quite understand what you mean, should I import `bitsandbytes` in my fit function or delete this package directly? But I will use this package in the process of defining the model before that.
`import torch
from transformers import AutoTokenizer, AutoModelForCausalLM,AutoConfig, AutoModel, BitsAndBytesConfig
from transformers.generation.utils import GenerationConfig
import torch.nn as nn


#使用QLoRA引入的 NF4量化数据类型以节约显存
model_name_or_path ='/tmp/Baichuan-13B/Baichuan-13B-Chat' #远程 'baichuan-inc/Baichuan-13B-Chat'

bnb_config=BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_compute_dtype=torch.float16,
            bnb_4bit_use_double_quant=True,
            bnb_4bit_quant_type="nf4",
            llm_int8_threshold=6.0,
            llm_int8_has_fp16_weight=False,
        )

tokenizer = AutoTokenizer.from_pretrained(
   model_name_or_path, trust_remote_code=True)

model = AutoModelForCausalLM.from_pretrained(model_name_or_path,
                quantization_config=bnb_config,
                trust_remote_code=True) 

model.generation_config = GenerationConfig.from_pretrained(model_name_or_path)
`

**Comment by muellerzr** [comment]
This should be fixed now on main, please install accelerate via `pip install git+https://github.com/huggingface/accelerate` and it should work!

**Comment by AisingioroHao0** [comment]
@muellerzr I tried it and my code still didn't work. I installed the new accelerate via   ```pip install git+https://github.com/huggingface/accelerate ```
```shell
Launching training on 2 GPUs.
---------------------------------------------------------------------------
ProcessRaisedException                    Traceback (most recent call last)
File [~/miniconda3/envs/torch/lib/python3.11/site-packages/accelerate/launchers.py:137](https://vscode-remote+ssh-002dremote-002bhome.vscode-resource.vscode-cdn.net/home/aihao/workspace/ComicGenerator/comic_generator/train/~/miniconda3/envs/torch/lib/python3.11/site-packages/accelerate/launchers.py:137), in notebook_launcher(function, args, num_processes, mixed_precision, use_port)
    136 try:
--> 137     start_processes(launcher, args=args, nprocs=num_processes, start_method="fork")
    138 except ProcessRaisedException as e:

File [~/miniconda3/envs/torch/lib/python3.11/site-packages/torch/multiprocessing/spawn.py:197](https://vscode-remote+ssh-002dremote-002bhome.vscode-resource.vscode-cdn.net/home/aihao/workspace/ComicGenerator/comic_generator/train/~/miniconda3/envs/torch/lib/python3.11/site-packages/torch/multiprocessing/spawn.py:197), in start_processes(fn, args, nprocs, join, daemon, start_method)
    196 # Loop on join until it returns True or raises an exception.
--> 197 while not context.join():
    198     pass

File [~/miniconda3/envs/torch/lib/python3.11/site-packages/torch/multiprocessing/spawn.py:160](https://vscode-remote+ssh-002dremote-002bhome.vscode-resource.vscode-cdn.net/home/aihao/workspace/ComicGenerator/comic_generator/train/~/miniconda3/envs/torch/lib/python3.11/site-packages/torch/multiprocessing/spawn.py:160), in ProcessContext.join(self, timeout)
    159 msg += original_trace
--> 160 raise ProcessRaisedException(msg, error_index, failed_process.pid)

ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/aihao/miniconda3/envs/torch/lib/python3.11/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/aihao/miniconda3/envs/torch/lib/python3.11/site-packages/accelerate/utils/launch.py", line 543, in __call__
    self.launcher(*args)
  File "/home/aihao/workspace/ComicGenerator/comic_generator/train/comic_conditional_gen/train_conditional_gen_2d.py", line 32, in train
...
    147 else:
    148     # No need for a distributed launch otherwise as it's either CPU, GPU or MPS.
    149     if is_mps_available():

RuntimeError: CUDA has been initialized before the `notebook_launcher` could create a forked subprocess. This likely stems from an outside import causing issues once the `notebook_launcher()` is called. Please review your imports and test them when running the `notebook_launcher()` to identify which one is problematic.

```

**Comment by muellerzr** [comment]
Yep, deeply aware that something has horribly gone wrong with the notebook launcher, looking into this. (Discovered this today actually)

**Comment by muellerzr** [comment]
Will be solved via https://github.com/huggingface/accelerate/pull/1833, @AisingioroHao0 you can do `pip install git+https://github.com/huggingface/accelerate@fix-cuda` until it's merged, then `pip install git+https://github.com/huggingface/accelerate` after
