### ISSUE TITLE
broadcast() and broadcast_object_list() do not broadcast objects

### ISSUE THREAD

**Issue by tonydavis629** [huggingface/accelerate#1821]
I'm trying to do distributed inference with accelerate and it's been unclear to me how it's supposed to work. The [docs](https://huggingface.co/docs/accelerate/usage_guides/distributed_inference) show a basic example with a short list being split between 2 processes, but I am trying to do inference on a dataset of 20k images. I am trying to create a batch in the main process and split it between 4 processes, but broadcasting objects do not seem to make it to the other processes.

example.py:

```
import random

from accelerate import PartialState
from accelerate.utils import broadcast_object_list

batch_size = 8
samples = [(x, x) for x in range(64)]
data_indices = list(range(len(samples)))
dist_state = PartialState()

@dist_state.on_main_process
def get_batch(data_indices):
    rand_indices = random.sample(data_indices, batch_size)
    data_indices = list(set(data_indices) - set(rand_indices))
    batch = [samples[i] for i in rand_indices]
    print(f"sample indices: {rand_indices}")
    print(f"sample num {i}")
    batch = broadcast_object_list(batch)
    data_indices = broadcast_object_list(data_indices)
    return batch, data_indices

for i in range(0, len(samples), batch_size):
    with dist_state.main_process_first():
        batch, data_indices = get_batch(data_indices)

    with dist_state.split_between_processes(batch, apply_padding=False) as mini_batch:
        print(f"mini batch len: {len(mini_batch)}")

    dist_state.wait_for_everyone()

```

This results in a 
```
TypeError: cannot unpack non-iterable NoneType object
batch, data_indices = get_batch(data_indices)
``` 
on processes > 0, I'm assuming because the batch and remaining data_indices are not being broadcast as expected.

```
(base) accelerate env

Copy-and-paste the text below in your GitHub issue

- `Accelerate` version: 0.21.0
- Platform: Linux-5.15.0-76-generic-x86_64-with-glibc2.31
- Python version: 3.9.16
- Numpy version: 1.25.2
- PyTorch version (GPU?): 2.0.1 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 1007.67 GB
- GPU type: NVIDIA A100-SXM4-40GB
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: bf16
        - use_cpu: False
        - num_processes: 4
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: all
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - downcast_bf16: yes
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
```

I'm confused why `accelerate launch` launches multiple processes of the same script, instead of spawning multiple processes when called for, like how python multiprocessing or torch DataParallel works. It's unclear to me how I can sync my processes except through these broadcast utilities.

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

`accelerate launch example.py`

### Expected behavior

Objects should be broadcast to all processes and allow the example.py inference script to complete without the TypeError, while keeping `data_indices` in sync across processing to avoid duplicating an inference.

**Comment by muellerzr** [comment]
@tonydavis629 is there a reason you can't create a dataloader and use `accelerator.prepare` on it? (This is hinted in the doc there, and is a better way in your situation I believe)

**Comment by muellerzr** [comment]
It's mentioned here:

> A user might then also think that with 🤗 Accelerate, using the Accelerator to prepare a dataloader for such a task might also be a simple way to manage this. (To learn more, check out the relvent section in the [Quick Tour](https://huggingface.co/docs/accelerate/quicktour#distributed-evaluation))

> Can it manage it? Yes.

**Comment by tonydavis629** [comment]
It seems to pretty clearly discourage using accelerator.prepare() to do this, because the very next sentence is

> Can it manage it? Yes. Does it add unneeded extra code however: also yes.

**Comment by muellerzr** [comment]
We can certainly make that clearer, you are right 😃 I'll take a look at what could be going wrong with broadcast here tommorow!

**Comment by tonydavis629** [comment]
It seems that accelerator.prepare(loader) is not supposed to be used with accelerator.split_between_processes. Is that right? For example:

```
from accelerate import Accelerator
from torch.utils.data import DataLoader
import torch

data = torch.randn(12, 2)
loader = DataLoader(data, batch_size=4)

accelerator = Accelerator()

loader = accelerator.prepare(loader)
for i, batch in enumerate(loader):
    with accelerator.split_between_processes(batch) as split_batch:
        print(split_batch)
```
results in an unexpected 
```
tensor([[-0.0384, -0.1654]], device='cuda:3')
tensor([[ 0.2814, -1.4174]], device='cuda:2')
tensor([[0.6850, 2.1630]], device='cuda:0')
tensor([[-0.2330, -0.2359]], device='cuda:1')
```

whereas 

```
from accelerate import Accelerator
from torch.utils.data import DataLoader
import torch

data = torch.randn(12, 2)
loader = DataLoader(data, batch_size=4)

accelerator = Accelerator()

loader = accelerator.prepare(loader)
for i, batch in enumerate(loader):
    print(batch)

```
results in the desired split batches:

```
tensor([[ 1.3545,  0.8557],
        [-0.5393, -0.8898],
        [-1.0968, -1.8712],
        [-1.9542, -1.7218]], device='cuda:1')

tensor([[ 0.5677, -0.5731],
        [-0.5506,  2.3958],
        [-1.2239, -0.5263],
        [ 0.7602,  0.6682]], device='cuda:3')
tensor([[-0.5488, -0.8386],
        [ 0.9942,  0.6660],
        [-0.4929,  1.3973],
        [ 1.4655, -0.9493]], device='cuda:2')
tensor([[0.5694, 1.0580],
        [0.8980, 0.0167],
        [0.7195, 0.0440],
        [0.6165, 0.6267]], device='cuda:0')
```

So when is accelerator.split_between_processes meant to be used?

**Comment by muellerzr** [comment]
@tonydavis629 correct, just do:

```python
for batch in dl:
   output = model(batch)
```

When using the dataloader method, the same way during training/evaluation during training
