### ISSUE TITLE
Issues with DeepSpeed autotuning and `gradient_accumulation_steps`

### ISSUE THREAD

**Issue by acforvs** [huggingface/accelerate#1830]
Hey, I’m curious if there’s a conventional way to use [deepspeed autotuning ](http://deepspeed.ai/tutorials/autotuning/) with `accelerate launch`? DeepSpeed’s autotuning is useful to improve the throughput of training and inference setups, it would be great for this to be compatible with Accelerate.

I have been trying to set up autotuning in many ways, but none of it seems to be working. Below are my somewhat long thoughts on what seems to be the problem.

#### 1. Use `accelerate launch` with multiple `zero_optimization.stage` values

Using `accelerate launch --config_file accelerate.yaml` with deepspeed_config.deepspeed_config_file section pointing to the file with the following content

```json
{
  "zero_optimization": {
      "stage": [2, 3],
      "offload_optimizer": {
          "device": "nvme",
          "nvme_path": "/mnt/vlad/param_offload"
      },
      "offload_param": {
          "device": "nvme",
          "nvme_path": "/mnt/vlad/param_offload"
      },
      "overlap_comm": true,
      "contiguous_gradients": true,
      "reduce_bucket_size": "auto",
      "stage3_prefetch_bucket_size": "auto",
      "stage3_param_persistence_threshold": "auto",
      "sub_group_size": 1e9,
      "stage3_max_live_parameters": 1e9,
      "stage3_max_reuse_distance": 1e9,
      "stage3_gather_16bit_weights_on_model_save": true
  },
  "gradient_accumulation_steps": "auto",
  "train_batch_size": "auto",
  "train_micro_batch_size_per_gpu": "auto",
  "autotuning": {
    "enabled": true,
    "overwrite": false,
    "fast": false,
    "arg_mappings": {
      "train_micro_batch_size_per_gpu": "--per_device_train_batch_size",
      "gradient_accumulation_steps ": "--gradient_accumulation_steps"
    }
  }
}
```

produces an error here https://github.com/huggingface/accelerate/blob/b30a349078d5301411e8af421720eaa60e984fa2/src/accelerate/accelerator.py#L1602

```
ValidationError: 1 validation error for DeepSpeedZeroConfig
stage
  value is not a valid enumeration member; permitted: 0, 1, 2, 3 (type=type_error.enum; enum_values=[<ZeroStageEnum.disabled: 
0>, <ZeroStageEnum.optimizer_states: 1>, <ZeroStageEnum.gradients: 2>, <ZeroStageEnum.weights: 3>])
```

I believe the reason for this is the lack of `--autotuning run` argument in the deepspeed launch command, which is required according to https://www.deepspeed.ai/tutorials/autotuning/#ease-of-use

#### 2. Use `accelerate launch` with a single `zero_optimization.stage` value

Changing  `"stage": [2, 3]` to `"stage": 3` helps deal with the issue above, but does not initiate parameter search. For example, only one set of parameters was tested during this invocation.

But it does produce the `autotuning_metric.json` file with similar content
```json
{"forward": 92726.27258300781, "backward": 252979.75158691406, "step": 2365466.552734375, "latency": 2711172.576904297, "FLOPS_per_gpu": 86433114272.4862, "throughput": 5.901505546455958, "rank": 0}
```

Again, I believe the reason for the lack of full autotuning search is in the missing `--autotuning run` when  `autotuning.enabled` is set to true 

#### 3. Use vanilla `deepspeed ` with `--autotuning tune` instead of `accelerate launch`

The command I used:
```
deepspeed --autotuning tune  --num_nodes 1 --num_gpus 3 script.py  --deepspeed autotune.json  <other args>
```

script.py contained a trlx training loop, and trlx sets up an Accelerator instance https://github.com/CarperAI/trlx/blob/main/trlx/trainer/accelerate_base_trainer.py#L56.

**This run goes through the parameter search and works as expected until it starts setting `gradient_accumulation_steps` to something rather than 1. In that case, AssertionError is raised:**
```
AssertionError: Check batch related parameters. train_batch_size is not equal to micro_batch_per_gpu * gradient_acc_step * world_size 2010 != 335 * 1 * 3
```

I think the issue is in this line: 

https://github.com/huggingface/accelerate/blob/b30a349078d5301411e8af421720eaa60e984fa2/src/accelerate/accelerator.py#L1487

`gradient_accumulation_steps` defaults to 1 in [`Accelerator.__init__ `](https://github.com/huggingface/accelerate/blob/b30a349078d5301411e8af421720eaa60e984fa2/src/accelerate/accelerator.py#L246), if a value is not provided using  `--config_file` (in the Accelerate CLI) or [gradient_accumulation_steps](https://github.com/huggingface/accelerate/blob/8514c35192ac9762920f1ab052e5cea4c0e46eeb/src/accelerate/accelerator.py#L164) (in `Accelerator.__init__`). This results in a mismatch between deepspeed and Accelerator, which leads to the deepspeed value being overwritten.

This, however, does not happen when the script is launched through `accelerate launch`, because the launching command sets ACCELERATE_GRADIENT_ACCUMULATION_STEPS here https://github.com/huggingface/accelerate/blob/b30a349078d5301411e8af421720eaa60e984fa2/src/accelerate/utils/launch.py#L305 which is later used to to set gradient_accumulation_steps https://github.com/huggingface/accelerate/blob/b30a349078d5301411e8af421720eaa60e984fa2/src/accelerate/accelerator.py#L394

#### Bug with the `gradient_accumulation_steps`
In addition, I think that this bug with `gradient_accumulation_steps` might happen when passing `deepspeed_plugin` directly to Accelerator. To replicate, change lines 53-58 of https://github.com/huggingface/accelerate/blob/b30a349078d5301411e8af421720eaa60e984fa2/examples/complete_nlp_example.py to

```python
deepspeed_plugin = DeepSpeedPlugin(zero_stage=2, gradient_accumulation_steps=2)
accelerator = Accelerator(deepspeed_plugin=deepspeed_plugin)
```

**Initially, it was contributed in a separate PR: https://github.com/huggingface/accelerate/pull/698, so maybe there’s motivation behind it?**

### Summary:
1. The DeepSpeed plugin's `gradient_accumulation_steps` gets overwritten by the Accelerator's `gradient_accumulation_steps` when the two are not equal. To avoid this, users must set the `gradient_accumulation steps` for the Accelerator object separately, either using the [`--config_file`](https://github.com/huggingface/accelerate/blob/b30a349078d5301411e8af421720eaa60e984fa2/docs/source/package_reference/cli.md?plain=1#L36) or [`gradient_accumulation_steps`](https://github.com/huggingface/accelerate/blob/8514c35192ac9762920f1ab052e5cea4c0e46eeb/src/accelerate/accelerator.py#L164) parameters.

This prevents the use of autotuning inside of a single `accelerate launch`, since the value of `gradient_accumulation_steps` will change during tuning.

2. DeepSpeed autotuning does not work through `accelerate launch`. This may be due to lack of support for the `–autotuning run` DeepSpeed CLI parameter.

### Potential Fixes:

To fix (1), I suggest:
- Roll back the changes from https://github.com/huggingface/accelerate/pull/698
- Add tests to https://github.com/huggingface/accelerate/blob/b30a349078d5301411e8af421720eaa60e984fa2/tests/deepspeed/test_deepspeed.py

What are your thoughts on this? I’d be happy to help work on the fixes or provide any additional information, if needed!

**Comment by sgugger** [comment]
cc @pacman100

**Comment by acforvs** [comment]
Hi @pacman100, any news here?

**Comment by pacman100** [comment]
Hello @acforvs, 

Thank you for the detailed issue, very helpful. To give more context, the `gradient_accumulation_steps` was added as a config parameter for DeepSpeed because at that time Accelerate didn't have it as its parameter. The PR using the Accelerate attribute to override the DeepSpeed config was done because the users wanted to use this as it is generic across diff methods like DDP, FSDP ...

It would make sense to deprecate and remove the ds config support for `gradient_accumulation_steps` but might cause backwards compatibility issues. @sgugger and @muellerzr , do you think deprecating it from ds config and using the Accelerate attribute is a better solution than reverting the PR overriding ds config value?

**Comment by sgugger** [comment]
Mmm, the DeepSpeed config should probably not be overridden unless the user is okay with that (setting something like "auto" for gradient accumulation steps) no?

**Comment by muellerzr** [comment]
Agreed, `auto` and specifying that passing `gradient_accumulation_steps` to the `Accelerator` will be what sets/utilizes that is the right solution here I think

**Comment by g-simmons** [comment]
I agree -- as a user I would find it counterintuitive to not be able to use the gradient_accumulation_steps parameter of my DeepSpeed config.

**Comment by g-simmons** [comment]
Just FYI, @acforvs originally looked into this with a goal of using Accelerate in combination with DeepSpeed **autotuning**.

We're aware DS autotuning is not explicitly supported in Accelerate, but we feel it would be feasible and valuable to do this.

I'm reiterating this because DS parameter overrides are a little trickier in the autotuning case than in the non-autotuning case. A good solution here could give Accelerate room to support autotuning, now or in the future.

**Comment by pacman100** [comment]
Hello, the above PR should fix this issue. it would be great if you could confirm the same.
