### ISSUE TITLE
Request for clearer handling of CUDA resources between bitsandbytes and accelerate

### ISSUE THREAD

**Issue by cassianlewis** [huggingface/accelerate#1831]
### System Info

```Shell
- `Accelerate` version: 0.21.0
- Platform: Linux-5.10.178-162.673.amzn2.x86_64-x86_64-with-glibc2.26
- Python version: 3.10.8
- Numpy version: 1.25.0
- PyTorch version (GPU?): 2.0.0+cu117 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 186.60 GB
- GPU type: Tesla T4
- `Accelerate` default config:
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

Steps to reproduce:

1. `Without bitsandbytes`
In a notebook cell, run
```
from accelerate import notebook_launcher
import torch
torch.cuda.is_initialized()
```

This should return `False`

2. Install bitsandbytes: `pip install bitsandbytes`

3. Repeat:
```
from accelerate import notebook_launcher
import torch
torch.cuda.is_initialized()
```

This will now return `true`

### Expected behavior

Why is this a problem?

```
def run():
    pass

notebook_launcher(run, num_processes = 4)
```
 will fail since `torch.cuda` has been used when importing `notebook_launcher` (via `bitsandbytes`):
 
 ```
ValueError                                Traceback (most recent call last)
Cell In[3], line 4
      1 def run():
      2     pass
----> 4 notebook_launcher(run, num_processes = 4)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/accelerate/launchers.py:123, in notebook_launcher(function, args, num_processes, mixed_precision, use_port)
    116     raise ValueError(
    117         "To launch a multi-GPU training from your notebook, the `Accelerator` should only be initialized "
    118         "inside your training function. Restart your notebook and make sure no cells initializes an "
    119         "`Accelerator`."
    120     )
    122 if torch.cuda.is_initialized():
--> 123     raise ValueError(
    124         "To launch a multi-GPU training from your notebook, you need to avoid running any instruction "
    125         "using `torch.cuda` in any cell. Restart your notebook and make sure no cells use any CUDA "
    126         "function."
    127     )
    129 # torch.distributed will expect a few environment variable to be here. We set the ones common to each
    130 # process here (the other ones will be set be the launcher).
    131 with patch_environment(
    132     world_size=num_processes, master_addr="127.0.01", master_port=use_port, mixed_precision=mixed_precision
    133 ):

ValueError: To launch a multi-GPU training from your notebook, you need to avoid running any instruction using `torch.cuda` in any cell. Restart your notebook and make sure no cells use any CUDA function.
```

**Comment by muellerzr** [comment]
This has been solved already, please install via `pip install git+https://github.com/huggingface/accelerate` and it'll work 😄

**Comment by cassianlewis** [comment]
Thank you @muellerzr - seems to have solved it. A new error though:

```
def run():
    model = AutoModelForSeq2SeqLM.from_pretrained(
            't5-small',
            load_in_8bit = 'True',
            cache_dir='model_cache')
    print(model)

notebook_launcher(run, num_processes = 2)
```

leads to:

ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/accelerate/utils/launch.py", line 543, in __call__
    self.launcher(*args)
  File "/tmp/ipykernel_20806/4150162094.py", line 2, in run
    model = AutoModelForSeq2SeqLM.from_pretrained(
  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 493, in from_pretrained
    return model_class.from_pretrained(
  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2295, in from_pretrained
    device_map = {"": torch.cuda.current_device()}
  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/torch/cuda/__init__.py", line 679, in current_device
    _lazy_init()
  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/torch/cuda/__init__.py", line 235, in _lazy_init
    raise RuntimeError(
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method


The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
Cell In[3], line 1
----> 1 notebook_launcher(run, num_processes = 2)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/accelerate/launchers.py:140, in notebook_launcher(function, args, num_processes, mixed_precision, use_port)
    138         except ProcessRaisedException as e:
    139             if "Cannot re-initialize CUDA in forked subprocess" in e.args[0]:
--> 140                 raise RuntimeError(
    141                     "CUDA has been initialized before the `notebook_launcher` could create a forked subprocess. "
    142                     "This likely stems from an outside import causing issues once the `notebook_launcher()` is called. "
    143                     "Please review your imports and test them when running the `notebook_launcher()` to identify "
    144                     "which one is problematic."
    145                 ) from e
    147 else:
    148     # No need for a distributed launch otherwise as it's either CPU, GPU or MPS.
    149     if is_mps_available():

RuntimeError: CUDA has been initialized before the `notebook_launcher` could create a forked subprocess. This likely stems from an outside import causing issues once the `notebook_launcher()` is called. Please review your imports and test them when running the `notebook_launcher()` to identify which one is problematic.

**Comment by muellerzr** [comment]
Make sure to fully restart the notebook and try rerunning it. Otherwise can you share with me the rest of your cells?

**Comment by cassianlewis** [comment]
Yep, fully restarted, same error. 

```
from transformers import AutoTokenizer, T5ForConditionalGeneration, T5Config, AutoModelForSeq2SeqLM
from accelerate import notebook_launcher
import torch
torch.cuda.is_initialized()
```
output: `False`

```
def run():
    model = AutoModelForSeq2SeqLM.from_pretrained(
            't5-small',
            load_in_8bit = 'True',
            cache_dir='model_cache')
    print(model)
```

```
notebook_launcher(run, num_processes = 2)
```

Note: runs fine if I remove the entire `load_in_8bit = 'True',` line.

**Comment by muellerzr** [comment]
Thanks, any chance you could open this in `transformers`? It likely stems from that repo

**Comment by muellerzr** [comment]
Will be solved via https://github.com/huggingface/accelerate/pull/1833

**Comment by cassianlewis** [comment]
Thanks a lot @muellerzr. Any idea when this will get merged?

**Comment by muellerzr** [comment]
Hopefully today :) In the interim you can use `pip install git+https://github.com/huggingface/accelerate@fix-cuda`

**Comment by cassianlewis** [comment]
Thank you!

Different error? now:

```
def run():
    
    model = AutoModelForSeq2SeqLM.from_pretrained(
            't5-small',
            load_in_8bit = 'True',
            device_map = 'auto',
            cache_dir='model_cache')
    
    print(model)
    print('Testing')
```

```
notebook_launcher(run, num_processes = 2)
```
Output: `Launching training on 2 GPUs.`
But the cell says it's finished running :(

**Comment by muellerzr** [comment]
What happens if you use `True` instead? (Use a bool, not a string)

**Comment by cassianlewis** [comment]
Oops, ignore that, I forgot to install `bitsandbytes`! Working now

**Comment by cassianlewis** [comment]
I was getting an error message using `num_processes = 1` (which alerted me to not having bitsandbytes installed). This was not coming up with `num_processes > 1` though. Might be good to look into why this doesn't happen.

**Comment by cassianlewis** [comment]
One more thing...
```
from peft import get_peft_model
import torch
torch.cuda.is_initialized()
```
returns `True`

then causes errors in`notebook_launcher`

```
ValueError                                Traceback (most recent call last)
Cell In[7], line 1
----> 1 notebook_launcher(run, num_processes = 2)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/accelerate/launchers.py:123, in notebook_launcher(function, args, num_processes, mixed_precision, use_port)
    116     raise ValueError(
    117         "To launch a multi-GPU training from your notebook, the `Accelerator` should only be initialized "
    118         "inside your training function. Restart your notebook and make sure no cells initializes an "
    119         "`Accelerator`."
    120     )
    122 if torch.cuda.is_initialized():
--> 123     raise ValueError(
    124         "To launch a multi-GPU training from your notebook, you need to avoid running any instruction "
    125         "using `torch.cuda` in any cell. Restart your notebook and make sure no cells use any CUDA "
    126         "function."
    127     )
    129 # torch.distributed will expect a few environment variable to be here. We set the ones common to each
    130 # process here (the other ones will be set be the launcher).
    131 with patch_environment(
    132     world_size=num_processes, master_addr="127.0.01", master_port=use_port, mixed_precision=mixed_precision
    133 ):

ValueError: To launch a multi-GPU training from your notebook, you need to avoid running any instruction using `torch.cuda` in any cell. Restart your notebook and make sure no cells use any CUDA function.
```

Guessing this is an issue for https://github.com/huggingface/peft?

**Comment by muellerzr** [comment]
Yep I'd open it there

**Comment by muellerzr** [comment]
(You can cc me on it)
