### ISSUE TITLE
patch_environment does not revert previously existing keys

### ISSUE THREAD

**Issue by BenjaminBossan** [huggingface/accelerate#1832]
### System Info

```Shell
does not matter here
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

```python
os.environ["FOO"] = "BAR"
with patch_environment(FOO="BAZ"):
     assert os.environ["FOO"] == "BAZ"
assert os.environ["F00"] == "BAR"  # KeyError
```

### Expected behavior

After leaving the context, the initial environment variables should be restored.

I noticed this while going through the code. If this is an issue, LMK and I'll provide a fix + tests. If, in the context that this function is used, it's not a problem, feel free to close the issue.

**Comment by sgugger** [comment]
cc @muellerzr
