### ISSUE TITLE
Loss Scaled Twice in FSDP examples

### ISSUE THREAD

**Issue by KeremTurgutlu** [huggingface/accelerate#1839]
Here, in this [example](https://github.com/huggingface/accelerate/blob/main/examples/by_feature/fsdp_with_peak_mem_tracking.py#L319) we can see that loss is scaled during grad accumulation but `backward()` already does that for any distributed type other than deepspeed - seen [here](https://github.com/huggingface/accelerate/blob/4d13e4e474def51a67ca23cc7356926d45cd63bc/src/accelerate/accelerator.py#L1906-L1908).

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

Nothing.

### Expected behavior

Minor error in example training scripts.

**Comment by sgugger** [comment]
cc @pacman100

**Comment by pacman100** [comment]
Hello, nice catch, will fix it. Alternatively feel free to raise a PR to fix the example, Thank you!
