### ISSUE TITLE
headless version of accelerate config

### ISSUE THREAD

**Issue by jethrokuan** [huggingface/accelerate#184]
I think it would be helpful to have a headless version of `accelerate config`, so they can be used in scripts that launch training in ephemeral containers.

I am now working around this by producing the accelerate config file manually.

Example flow:

```
accelerate config --fp16 --multi-gpu --num_workers 8 # am making this up
accelerate launch train.py
```

**Comment by sgugger** [comment]
Interesting use case! It would definitely be a welcome feature, I may have a bit of time to work on this next week.

**Comment by jethrokuan** [comment]
I was thinking about it again, and just saw most of the args are available in `accelerate launch` already so this headless version might not be so necessary anymore. Feel free to close if you can confirm.
