### ISSUE TITLE
Loading a HF Model in Multiple GPUs and Run Inferences in those GPUs

### ISSUE THREAD

**Issue by asifehmad** [huggingface/accelerate#1841]
Hi,
Is there any way to load a Hugging Face model in multi GPUs and use those GPUs for inferences as well?

Like, there is this model which can be loaded on a single GPU (default cuda:0) and run for inference as below:

`from transformers import AutoTokenizer, AutoModelForCausalLM`

`tokenizer = AutoTokenizer.from_pretrained("togethercomputer/LLaMA-2-7B-32K")`
`model = AutoModelForCausalLM.from_pretrained("togethercomputer/LLaMA-2-7B-32K", torch_dtype=torch.float16)`

`input_context= "Your text here"`
`input_ids = tokenizer.encode(input_context, return_tensors="pt").to(model.device)`
`output = model.generate(input_ids, max_length=256, temperature=0.7)`
`output_text = tokenizer.decode(output[0], skip_special_tokens=True)`
`print(output_text)`

How should I load and run this model for inference on two or more GPUs using `Accelerate` or `DeepSpeed`?

Any guidance/help would be highly appreciated, thanks in anticipation!

**Comment by sgugger** [comment]
Hi there! Please use the [forums](https://discuss.huggingface.co/) for questions such as this one as we keep issues for bugs and feature requests only. You can have a look at the documentation section on [distributed inference](https://huggingface.co/docs/accelerate/quicktour#distributed-evaluation) as well

**Comment by asifehmad** [comment]
> Hi there! Please use the [forums](https://discuss.huggingface.co/) for questions such as this one as we keep issues for bugs and feature requests only. You can have a look at the documentation section on [distributed inference](https://huggingface.co/docs/accelerate/quicktour#distributed-evaluation) as well

Hi, my bad! I just asked the question in the relevant forms, [Discuss-HuggingFace](https://discuss.huggingface.co/t/loading-a-hf-model-in-multiple-gpus-and-run-inferences-in-those-gpus/50618) and [StackOverflow](https://stackoverflow.com/questions/76894701/loading-a-hf-model-in-multiple-gpus-and-run-inferences-in-those-gpus-not-traini).
