### ISSUE TITLE
FSDP Training Slow Down 2-3x When Resuming from `SHARDED_STATE_DICT`

### ISSUE THREAD

**Issue by KeremTurgutlu** [huggingface/accelerate#1844]
### System Info

```Shell
- `Accelerate` version: 0.22.0.dev0
- Platform: Linux-5.15.0-78-generic-x86_64-with-glibc2.29
- Python version: 3.8.10
- Numpy version: 1.22.2
- PyTorch version (GPU?): 2.1.0.dev20230809+cu121 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 1511.43 GB
- GPU type: NVIDIA A100-SXM4-80GB
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: FSDP
        - mixed_precision: no
        - use_cpu: False
        - debug: False
        - num_processes: 8
        - machine_rank: 0
        - num_machines: 1
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - fsdp_config: {'fsdp_auto_wrap_policy': 'TRANSFORMER_BASED_WRAP', 'fsdp_backward_prefetch_policy': 'BACKWARD_PRE', 'fsdp_forward_prefetch': False, 'fsdp_offload_params': False, 'fsdp_sharding_strategy': 2, 'fsdp_state_dict_type': 'SHARDED_STATE_DICT', 'fsdp_sync_module_states': True, 'fsdp_transformer_layer_cls_to_wrap': 'LlamaDecoderLayer', 'fsdp_use_orig_params': True}
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
        - dynamo_config: {'dynamo_backend': 'INDUCTOR'}
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

I trained and save models every 1000 steps with the following config:

```python
   mixed_precision_policy = MixedPrecision(param_dtype=torch.bfloat16, 
                                            reduce_dtype=torch.bfloat16, 
                                            buffer_dtype=torch.float32)
    
    # Add embedding and lm head if needed.
    llama_auto_wrap_policy = functools.partial(
        transformer_auto_wrap_policy,
        transformer_layer_cls={
            LlamaDecoderLayer,
        },
    )
    
    # This overrides other settings.
    fsdp_plugin = FullyShardedDataParallelPlugin(
                        sharding_strategy=ShardingStrategy.SHARD_GRAD_OP,
                        auto_wrap_policy=llama_auto_wrap_policy,
                        mixed_precision_policy=mixed_precision_policy,
                        state_dict_config=ShardedStateDictConfig(offload_to_cpu=True),
                        optim_state_dict_config=ShardedOptimStateDictConfig(offload_to_cpu=False),
                        backward_prefetch = BackwardPrefetch.BACKWARD_PRE,
                        state_dict_type=StateDictType.SHARDED_STATE_DICT,
                        forward_prefetch=False,
                        use_orig_params=True
                    )
```

I used `SHARDED_STATE_DICT` since it is the "recommended" way per the accelerate docs. During saving and loading I use `load_state` and `save_state` methods, which uses `fsdp_utils` for saving and loading under the hood and handles differences between full and sharded state dicts.

After loading the sharded model and optimizer states (which are in distcp format) my training throughput decreased by a factor of 2-3x. First I thought it might be due to `cpu_offloading` but it wasn't.

Then, I converted these sharded state dicts to full state dicts using the following code snippet in my script and exited the script once they are saved.

```python
# Save FSDP full optimizer state dict. 
full_optim_save_path = os.path.join(output_dir, "optimizer.bin")
optim_state = model.full_optim_state_dict(model, optimizer)
if accelerator.is_local_main_process:
    torch.save(optim_state, full_optim_save_path)
# Save FSDP full model state dict. 
cfg = FullStateDictConfig(offload_to_cpu=True, rank0_only=True)
with model.state_dict_type(model, StateDictType.FULL_STATE_DICT, cfg):
    model_state = model.state_dict()
    full_model_save_path = os.path.join(output_dir, "pytorch_model.bin")
    if accelerator.is_local_main_process:
        torch.save(model_state, full_model_save_path)
```

After this, I changed the FSDP config to the following in my training script:

```python
    fsdp_plugin = FullyShardedDataParallelPlugin(
                        sharding_strategy=ShardingStrategy.SHARD_GRAD_OP,
                        auto_wrap_policy=llama_auto_wrap_policy,
                        mixed_precision_policy=mixed_precision_policy,
                        state_dict_config=FullStateDictConfig(offload_to_cpu=False),
                        optim_state_dict_config=FullOptimStateDictConfig(offload_to_cpu=False),
                        backward_prefetch = BackwardPrefetch.BACKWARD_PRE,
                        state_dict_type=StateDictType.FULL_STATE_DICT,
                        forward_prefetch=False,
                        use_orig_params=True,
                        cpu_offload=False,
                    )   
```

I also had to do some re-naming with the state dicts to be able to load them back with this new FSDP full state dict config, for example:

```python
prefix_len = len("_orig_mod.")
# strip off prefix '_orig_mod.'
optim_sd['state'] = {k[prefix_len:]:v for k,v in optim_sd['state'].items()}
```

After these changes, my training with full state dict config and resuming was able to get the same throughput as before. I am not 100% sure why this happens but it happens when resuming training from sharded state dicts. In order to reproduce you can perhaps use my initial FSDP config which uses `SHARDED_STATE_DICT`, time the throughput, then `save_state` after some iterations and resume back with `load_state` and time it again.

I still think the recommended `SHARDED_STATE_DICT` config is much better in general but this slow down makes it infeasible. I will continue my training with the new full state dict config I have, and report if I find anything else.

### Expected behavior

After resuming with `load_state` training speed should be same as before.

**Comment by sgugger** [comment]
cc @pacman100

**Comment by pacman100** [comment]
Hello, `SHARDED_STATE_DICT` is the recommended way for checkpointing with FSDP as per the PyTorch team. As there is no issue with the integration of FSDP, this issue should be raised with the PyTorch team.

**Comment by KeremTurgutlu** [comment]
Sounds good, I thought maybe you would know if this was a common problem. I will re-open this issue in PyTorch repo.
