### ISSUE TITLE
Device mismatch when using load_checkpoint_and_dispatch with LLaMA

### ISSUE THREAD

**Issue by drunkinlove** [huggingface/accelerate#1851]
### System Info

```Shell
- `Accelerate` version: 0.20.3
- Platform: Linux-5.4.0-84-generic-x86_64-with-glibc2.31
- Python version: 3.9.16
- Numpy version: 1.24.3
- PyTorch version (GPU?): 2.0.1+cu118 (True)
- PyTorch XPU available: False
- System RAM: 116.56 GB
- GPU type: GeForce RTX 2080 Ti
- `Accelerate` default config:
        Not found
- `transformers` version: 4.32.0.dev0
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

The model I'm using is https://huggingface.co/huggyllama/llama-7b

Code I'm running (used [this](https://huggingface.co/docs/accelerate/main/en/usage_guides/big_modeling) as reference):
```
import torch
from transformers import LlamaForCausalLM, LlamaConfig
from accelerate import init_empty_weights, load_checkpoint_and_dispatch

MODEL_NAME_OR_PATH = "models/llama-7b"

with init_empty_weights():
    model = LlamaForCausalLM(LlamaConfig.from_pretrained(MODEL_NAME_OR_PATH))

model = load_checkpoint_and_dispatch(
    model, checkpoint=MODEL_NAME_OR_PATH, device_map="auto"
)
model.tie_weights()

model.generate(input_ids=torch.as_tensor([[1, 2, 3, 4]]))
```

I get the following error (truncated):
```
File ~/miniconda3/envs/llama_prl/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py:184, in apply_rotary_pos_emb(q, k, cos, sin, position_ids)
    182 cos = cos.squeeze(1).squeeze(0)  # [seq_len, dim]
    183 sin = sin.squeeze(1).squeeze(0)  # [seq_len, dim]
--> 184 cos = cos[position_ids].unsqueeze(1)  # [bs, 1, seq_len, dim]
    185 sin = sin[position_ids].unsqueeze(1)  # [bs, 1, seq_len, dim]
    186 q_embed = (q * cos) + (rotate_half(q) * sin)

RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cuda:1)
```

### Expected behavior

Should infer normally, I think

**Comment by sgugger** [comment]
For a Transformers models you should use the Transformers library. You can pass `device_map="auto"` in the `from_pretrained` method which will automatically add the code that is missing here (there are layers to keep on the same device that you did not specify and the weights should be tied before calling `load_checkpoint_and_dispatch`.

**Comment by drunkinlove** [comment]
@sgugger Thanks! I changed my snippet accordingly, and now it seems to work:

```
with init_empty_weights():
    model = LlamaForCausalLM(LlamaConfig.from_pretrained(MODEL_NAME_OR_PATH))
    model.tie_weights()
    model = model.from_pretrained(MODEL_NAME_OR_PATH, device_map="auto")

model = load_checkpoint_and_dispatch(
    model, checkpoint=MODEL_NAME_OR_PATH, dtype=torch.float16
)
```
One last thing: can I use `load_in_8bit` when loading the model this way? Adding the argument to the `from_pretrained` method doesn't seem to work (throws `RuntimeError: expected scalar type Half but found Char`)

**Comment by sgugger** [comment]
cc @SunMarc for the quantization.

**Comment by SunMarc** [comment]
Hi @drunkinlove , as @sgugger said, for transformers models, you should use the Transformers library for [quantization](https://huggingface.co/docs/transformers/main_classes/quantization) or not. But we indeed have a way to quantize any pytorch model with accelerate. You can check this [doc](https://huggingface.co/docs/accelerate/usage_guides/quantization).

**Comment by drunkinlove** [comment]
@SunMarc hi! I checked out the doc and modified my snippet:
```
with init_empty_weights():
    model = LlamaForCausalLM(LlamaConfig.from_pretrained(MODEL_NAME_OR_PATH))
    model.tie_weights()
    model = model.from_pretrained(MODEL_NAME_OR_PATH, device_map="auto")

bnb_quantization_config = BnbQuantizationConfig(load_in_8bit=True, llm_int8_threshold=6)
model = load_and_quantize_model(model, weights_location=MODEL_NAME_OR_PATH, bnb_quantization_config=bnb_quantization_config)
```
however, I get an OOM error:
```
...
File ~/miniconda3/envs/llama2_prl/lib/python3.9/site-packages/torch/nn/parameter.py:55, in Parameter.__deepcopy__(self, memo)
     53     return memo[id(self)]
     54 else:
---> 55     result = type(self)(self.data.clone(memory_format=torch.preserve_format), self.requires_grad)
     56     memo[id(self)] = result
     57     return result

OutOfMemoryError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 0; 10.76 GiB total capacity; 10.11 GiB already allocated; 4.56 MiB free; 10.11 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
am I doing it wrong?

**Comment by drunkinlove** [comment]
@SunMarc still waiting for help on this 🥺

**Comment by SunMarc** [comment]
Hi @drunkinlove , check this [colab notebook](https://colab.research.google.com/drive/1AycEvnws401R1HeeluP4leSd7RzTU8ET?usp=sharing) which showcase how to quantize a llama model using accelerate. Let me know if it works on your end !

**Comment by drunkinlove** [comment]
@SunMarc didn't work unfortunately 🙁
When I try generating with this notebook on my rig, it throws a `RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!`
(and I don't have Colab Pro atm, and the free version doesn't have enough RAM to try, but I guess it works there?)

Here's the output of `transformers-cli env` in case it's useful:
```
- `transformers` version: 4.32.0
- Platform: Linux-5.4.0-84-generic-x86_64-with-glibc2.31
- Python version: 3.9.16
- Huggingface_hub version: 0.15.1
- Safetensors version: 0.3.1
- Accelerate version: 0.22.0
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.0.1+cu118 (True)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
```

**Comment by SunMarc** [comment]
I put a smaller model and it works now on the colab. Strange that it doesn't work on your end. Try the transformers integration [quantization](https://huggingface.co/docs/transformers/main_classes/quantization) and let me know if it works.

**Comment by drunkinlove** [comment]
@SunMarc tried it out and I get the same error:
```
from transformers import AutoTokenizer, AutoModelForCausalLM, GPTQConfig

model_id = "facebook/opt-125m"
tokenizer = AutoTokenizer.from_pretrained(model_id)
gptq_config = GPTQConfig(bits=4, dataset = "c4", tokenizer=tokenizer)

model = AutoModelForCausalLM.from_pretrained(model_id, quantization_config=gptq_config)

text = "Hello my name is"
inputs = tokenizer(text, return_tensors="pt").to(0)

out = model.generate(**inputs)
print(tokenizer.decode(out[0], skip_special_tokens=True))
```
`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument weight in method wrapper_CUDA__native_layer_norm)`

**Comment by SunMarc** [comment]
You are using GPTQ quantization in this case and not bitsandbytes. The error you are getting is normal since the model is on the CPU and the input you've passed is on cuda 0. you can move the model to 0 by using `model.to(0)`

**Comment by drunkinlove** [comment]
@SunMarc that worked indeed, thanks!
What does it mean — should I use this method of quantization with a Llama model loaded in parallel?
[This is where I'm at](https://github.com/huggingface/accelerate/issues/1851#issuecomment-1690523604) with the `accelerate`-backed quantization

**Comment by SunMarc** [comment]
bitsandbytes quantization and gptq quantization have both pros & cons. In a future blopost, we will compare them so stay tuned !

**Comment by SunMarc** [comment]
For the accelerate-backed quantization, I can't help much as I am unable to reproduce the error ;(. Make sure to have the latest libraries. Strange that it works on colab and not your setup

**Comment by drunkinlove** [comment]
@SunMarc I checked [your updated colab notebook](https://colab.research.google.com/drive/1AycEvnws401R1HeeluP4leSd7RzTU8ET?usp=sharing) and tried it out again on my hardware.

It [works](https://gist.github.com/drunkinlove/406d6d8a69963b47fe870036fec90cf7) when I use the `marcsun13/bloom-1b7_with_lm_head` model (or the `facebook/opt-125m` model)
...and [doesn't work](https://gist.github.com/drunkinlove/f4f41b4bb8d7d00e1e7a0fe1acf92a07) when I use the `huggyllama/llama-7b` model.

Would you have any ideas why that could be? (thanks for bearing with me so far!)

**Comment by Wang-Xiaodong1899** [comment]
Hi @SunMarc. How can I split a large custom model in inference? The Custom model is inherited from LlamaForCausalLM. Such as the following:
```
model = CustomLLM(config=config, base_model=base_model)
model.tie_weights()

model = load_checkpoint_and_dispatch(
        model, checkpoint=base_model+'/pytorch_model.bin', device_map="auto", dtype=torch.float16)
```
But in the inference, I met the device error.
**File "/opt/conda/envs/llama/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 307, in forward
    hidden_states = residual + hidden_states
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!**

I know if the model is the same with LlamaForCausalLM, I can just use from_pretrained to make it work. But I do not know how to deal with the custom model.

Can you kindly help me? Thanks a lot!

Xiaodong

**Comment by Wang-Xiaodong1899** [comment]
> Hi @SunMarc. How can I split a large custom model in inference? The Custom model is inherited from LlamaForCausalLM. Such as the following:
> 
> ```
> model = CustomLLM(config=config, base_model=base_model)
> model.tie_weights()
> 
> model = load_checkpoint_and_dispatch(
>         model, checkpoint=base_model+'/pytorch_model.bin', device_map="auto", dtype=torch.float16)
> ```
> 
> But in the inference, I met the device error. **File "/opt/conda/envs/llama/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 307, in forward hidden_states = residual + hidden_states RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!**
> 
> I know if the model is the same with LlamaForCausalLM, I can just use from_pretrained to make it work. But I do not know how to deal with the custom model.
> 
> Can you kindly help me? Thanks a lot!
> 
> Xiaodong

Ok. I find a solution in other issues. Using `device_map="sequential"` make it work. Thanks!

**Comment by SunMarc** [comment]
@drunkinlove It is because you need to specify the modules that should not be split `_no_modules_split` arg. Check what this does [here](https://huggingface.co/docs/accelerate/concept_guides/big_model_inference#nosplitmoduleclasses).

**Comment by SunMarc** [comment]
Hi @Wang-Xiaodong1899, this is the same issue as @drunkinlove , you need to specify the `no_split_module_classes` because you are splitting modules across different devices but those modules may include a residual connection of some kind.

**Comment by drunkinlove** [comment]
@SunMarc that did the trick! 
I quickly looked through the [llama code](https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/modeling_llama.py) for mentions of residual connections and came up with `no_split_module_classes=['LlamaDecoderLayer']`. Now the model successfully parallelizes and quantizes, and I don't get an OOM as with `device_map='sequential'`.
Thank you for help! 😊

**Comment by CrazyBrick** [comment]
> Hi @Wang-Xiaodong1899, this is the same issue as @drunkinlove , you need to specify the `no_split_module_classes` arg because you are splitting modules across different devices but those modules may include a residual connection of some kind.

Hi, @SunMarc ,I met the same problem:`RuntimeError: Expected all tensors to be on the same device, but found at least two devices`,but I don't know which layer to specify `no_split_module_classes=`,how can I determine this? Thank you in advance!

**Comment by SunMarc** [comment]
Hi @CrazyBrick , you need to check for layers that have residual connection. Most of the time, you need to put the encoder/decoder layers in the `no_split_module_classes`.
