### ISSUE TITLE
save_state causes CUDA allocations

### ISSUE THREAD

**Issue by carbocation** [huggingface/accelerate#1865]
### System Info

```Shell
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /opt/conda/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
/opt/conda/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /opt/conda did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 7.5
CUDA SETUP: Detected CUDA version 118
CUDA SETUP: Loading binary /opt/conda/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so...

Copy-and-paste the text below in your GitHub issue

- `Accelerate` version: 0.21.0
- Platform: Linux-5.10.0-23-cloud-amd64-x86_64-with-glibc2.31
- Python version: 3.10.12
- Numpy version: 1.23.5
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 14.65 GB
- GPU type: Tesla T4
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: NO
        - mixed_precision: fp16
        - use_cpu: False
        - num_processes: 1
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: all
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

I'm training dreambooth on a T4 GPU following this [huggingface diffusers README document](https://github.com/huggingface/diffusers/blob/74d902eb59f873b6156621220937f8e2521dfdc0/examples/dreambooth/README_sdxl.md). 

The script I am running is the SDXL Dreambooth LORA trainer, with the [unmodified script from huggingface diffusers permalinked here](https://github.com/huggingface/diffusers/blob/74d902eb59f873b6156621220937f8e2521dfdc0/examples/dreambooth/train_dreambooth_lora_sdxl.py). I'm training for 500 total steps, which also happens to be the default number of steps before a checkpoint gets logged. In saving the checkpoint, an NVIDIA OOM error gets triggered.

```py
Steps: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 500/500 [2:13:17<00:00, 10.31s/it, loss=0.0107, lr=1e-5]
08/19/2023 10:17:12 - INFO - accelerate.accelerator - Saving current state to lora-trained-xl-james/checkpoint-500
Traceback (most recent call last):
  File "/home/james/dreambooth/train_dreambooth_lora_sdxl.py", line 1363, in <module>
    main(args)
  File "/home/james/dreambooth/train_dreambooth_lora_sdxl.py", line 1187, in main
    accelerator.save_state(save_path)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/accelerator.py", line 2551, in save_state
    weights.append(self.get_state_dict(model, unwrap=False))
  File "/opt/conda/lib/python3.10/site-packages/accelerate/accelerator.py", line 2851, in get_state_dict
    state_dict[k] = state_dict[k].float()  
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 50.00 MiB (GPU 0; 14.58 GiB total capacity; 14.14 GiB already allocated; 9.38 MiB free; 14.39 GiB reserved in total by PyTorch) If rese
rved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

### Expected behavior

I think this is worth raising because I don't expect new GPU allocations when saving a checkpoint to disk.

**Comment by sgugger** [comment]
cc @pacman100 
The `.float()` was a temp fix for deepspeed (see #374) but it is now in a path where DeepSpeed is not executed. Can it be safely removed?

**Comment by pacman100** [comment]
Hello @sgugger, `.float()` was never a fix. It has been there apriori for getting the state dict in FP32 for storing them in standard full precision format.

**Comment by sgugger** [comment]
I'm not sure that's important. Many checkpoints are shared in half precision (this makes the weights easier to download as a bonus since they are half the size).

**Comment by pacman100** [comment]
Makes sense, will raise PR to remove `.float()`

**Comment by pacman100** [comment]
@carbocation, please let us know if the above PR resolves the issue?

**Comment by hungvo304ml** [comment]
I am still facing this issue even when I am using the latest `accelerate`.

Seems like there are other issues besides the `.float()`

I am using DDP and FSDP, and the issue happens in both settings.

```
accelerate                0.23.0
torch                     2.1.0
torchaudio                2.1.0
torchmetrics              1.2.0
torchvision               0.16.0
transformers              4.26.1
```
