### ISSUE TITLE
【BUG Report】accelerate method remove_hook_from_module can't remove cpu_offload hook.

### ISSUE THREAD

**Issue by MeJerry215** [huggingface/accelerate#1869]
### System Info

First I wanna cpu offloaded model back to cpu.
so i first call the method `accelerate.cpu_offload(module, CUDA_0)` to offload module to cuda.
then I want my module back to cpu, as i called `remove_hook_from_module(module, recurse=True)`

and remove method tells me NoneType error.

if tensor_name not in module._parameters and tensor_name not in module._buffers:
AttributeError: 'NoneType' object has no attribute '_parameters'

so i check the code, and found that.

![image](https://github.com/huggingface/accelerate/assets/53092165/c6868fef-5bc4-4123-852f-747416eb88b7)
```Shell
the hook detach method should return changed module. Also I see the Base Hook definition `ModelHook`. 
````
![image](https://github.com/huggingface/accelerate/assets/53092165/75267d2b-ff2e-465f-877a-81cd735daaa7)

so the only thing is, class `AlignDevicesHook` not support it well for not return module out.

![image](https://github.com/huggingface/accelerate/assets/53092165/60ea198b-7ff9-4106-b10c-cfb368bd0631)

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

1. call `accelerate.cpu_offload(module, CUDA_0)`  to offload some module to cuda
2. call `remove_hook_from_module(module, recurse=True)` to remove offload hook.

### Expected behavior

detach  hook success.

**Comment by SunMarc** [comment]
Thanks for the detailed report @MeJerry215 ! I've created a PR that will solve this bug.
