### ISSUE TITLE
AttributeError: 'AcceleratorState' object has no attribute 'fsdp_plugin'

### ISSUE THREAD

**Issue by sushantmenon1** [huggingface/accelerate#1893]
### System Info

```Shell
- `Accelerate` version: 0.23.0.dev0
- Platform: Linux-5.10.0-25-cloud-amd64-x86_64-with-glibc2.31
- Python version: 3.10.12
- Numpy version: 1.25.2
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 29.39 GB
- GPU type: Tesla T4
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: FSDP
        - mixed_precision: no
        - use_cpu: False
        - debug: False
        - num_processes: 2
        - machine_rank: 0
        - num_machines: 1
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - fsdp_config: {'fsdp_auto_wrap_policy': 'SIZE_BASED_WRAP', 'fsdp_backward_prefetch_policy': 'NO_PREFETCH', 'fsdp_forward_prefetch': False, 'fsdp_min_num_params': 2000, 'fsdp_offload_params': True, 'fsdp_sharding_strategy': 1, 'fsdp_state_dict_type': 'FULL_STATE_DICT', 'fsdp_sync_module_states': True, 'fsdp_use_orig_params': True}
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Install accelerate. I'm working with the current dev version but the latest release at the time of writing this v0.22.0 throws the same error. I've tried. 
2. Set up config as mentioned using `accelerate config`, but any FSDP configuration throws the same error really, I've tried multiple ones. 
3. Run `accelerate test`

### Expected behavior

Test passes successfully

**Comment by sushantmenon1** [comment]
Just thought this might be useful for debugging: 

When changing `fsdp_use_orig_params` to False, the error message changes to `RuntimeError: CUDA error: an illegal memory access was encountered`

**Comment by sushantmenon1** [comment]
Updating the `torch` version to the nightly release (2.1.0.dev20230827+cu118) throws a new error `RuntimeError: The size of tensor a (3) must match the size of tensor b (2960) at non-singleton dimension 3` at the line: 

```
Traceback (most recent call last):
  File "/home/jupyter/diffusers/examples/text_to_image/train_text_to_image.py", line 1087, in <module>
    main()
  File "/home/jupyter/diffusers/examples/text_to_image/train_text_to_image.py", line 979, in main
    ema_unet.step(unet.parameters())
  File "/opt/conda/envs/stablediffusion/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/envs/stablediffusion/lib/python3.10/site-packages/diffusers/training_utils.py", line 194, in step
    s_param.sub_(one_minus_decay * (s_param - param))
RuntimeError: The size of tensor a (3) must match the size of tensor b (2640) at non-singleton dimension 3
```

**Comment by muellerzr** [comment]
cc @pacman100

**Comment by pacman100** [comment]
Hello, `accelerate test` is incompatible with FSDP. Please see this https://github.com/huggingface/accelerate/issues/1476#issuecomment-1620101722

**Comment by pacman100** [comment]
> Updating the `torch` version to the nightly release (2.1.0.dev20230827+cu118) throws a new error `RuntimeError: The size of tensor a (3) must match the size of tensor b (2960) at non-singleton dimension 3` at the line:
> 
> ```
> Traceback (most recent call last):
>   File "/home/jupyter/diffusers/examples/text_to_image/train_text_to_image.py", line 1087, in <module>
>     main()
>   File "/home/jupyter/diffusers/examples/text_to_image/train_text_to_image.py", line 979, in main
>     ema_unet.step(unet.parameters())
>   File "/opt/conda/envs/stablediffusion/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>   File "/opt/conda/envs/stablediffusion/lib/python3.10/site-packages/diffusers/training_utils.py", line 194, in step
>     s_param.sub_(one_minus_decay * (s_param - param))
> RuntimeError: The size of tensor a (3) must match the size of tensor b (2640) at non-singleton dimension 3
> ```

How is this part of `accelerate test`?

**Comment by steveepreston** [comment]
Facing with exact error!
