### ISSUE TITLE
Finetuned Distilbert device_map='auto' does not assign model to gpu even if it fits

### ISSUE THREAD

**Issue by NPap0** [huggingface/accelerate#1897]
### System Info

```Shell
Windows 10
Python 3.7.13

accelerate 		      0.20.3
numpy                         1.21.6
torch                         1.13.1+cu117
transformers                  4.30.2

```

I have multiple fine-tuned distilbert models that I want to load, the issue is that not all, let's say 10 models fit in my VRAM. So by setting the device_map='auto' I would expect that I would load X in GPU VRAM and when I could no longer fit the next model in the gpu, all other models would be loaded via the cpu. The issue is that when I use device_map='auto' 0 models go to the gpu and they all get loaded in the cpu (I use a loop basically to load all the models needed)
If I omit the device_map and use device=torch.device (my gpu) the models are loaded fine. But because the above will need to be run in multiple computes with different gpus I want to use accelerate's device_map to optimally split the models.

I read in a different issue that BertForSequenceClassification did not have device_map enabled at the time (but it threw an error when calling it and mine doesn't throw an error) https://github.com/huggingface/transformers/issues/25296

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

Steps to reproduce:
1. https://huggingface.co/distilbert-base-uncased
2. Load multiple distilbert models with AutoModelForSequenceClassification using device_map='auto'
3. Check !nvidia-smi for VRAM usage

### Expected behavior

Using device_map I would expect the models to load into gpu, up until I would run out of vram and then the following models would be loaded through the cpu

**Comment by muellerzr** [comment]
cc @SunMarc 👀

**Comment by SunMarc** [comment]
On my side the error pop up ! The error was introduced in later version of transformers. With your version, the error do not appear, the device_map arg do not have an effect as `_no_split_modules` is not set and this is why we load by default the model to the cpu !
