### ISSUE TITLE
Stuck in optimizer.step()

### ISSUE THREAD

**Issue by Xelawk** [huggingface/accelerate#191]
Training with Multi-GPUs then stuck in progress 19622/139600. So I tried to debug with print() step by step, then I found that one of the optimizer is stuck when it trying to make optimizer.step(), but I still can't figure out how to solve it. Please helps.

And this is the example code:
```python
optimizer = transformers.AdamW(model.parameters(), lr=lr)
# prepare optimizer with accelerator
......

loss = get_loss(ret_logits, labels)
if mode == "train":
    optimizer.zero_grad()
    if accelerate:
        print(f"loss: {loss}")
        accelerator.backward(loss)
    else:
        loss.backward()
    print("bp done")
    optimizer.step()
    print("opt done")
    lr_scheduler.step()
    print("sche done")
    lr_scheduler.step()
```

And the outputs show
```python
loss: 0.7963258028030396
bp done
...
```

**Comment by TianyiZhangBIT** [comment]
Hi, has this problem been solved?

**Comment by ZichengDuan** [comment]
Same problem encountered here
