### ISSUE TITLE
multiprocessing and multiple gpus dispatch raise _pickle.PicklingError

### ISSUE THREAD

**Issue by ZeguanXiao** [huggingface/accelerate#1921]
### System Info

```Shell
- `Accelerate` version: 0.22.0
- Platform: Linux-5.4.0-156-generic-x86_64-with-glibc2.17
- Python version: 3.8.17
- Numpy version: 1.24.3
- PyTorch version (GPU?): 1.13.1 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 251.79 GB
- GPU type: NVIDIA GeForce RTX 4090
- `Accelerate` default config:
        Not found
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

```
from transformers import AutoConfig, InstructBlipForConditionalGeneration
import torch
import torch.multiprocessing as mp
from transformers import InstructBlipForConditionalGeneration
from accelerate import init_empty_weights, infer_auto_device_map, dispatch_model, load_checkpoint_and_dispatch

class ValidationProcess(mp.Process):
    def __init__(self, model):
        super().__init__()
        self.model = model

    def run(self):
        print("hehehe")

if __name__ == "__main__":
    mp.set_start_method("spawn")
    mp.set_sharing_strategy('file_system')

    MODEL_PATH = "Salesforce/instructblip-vicuna-7b"
    config = AutoConfig.from_pretrained(MODEL_PATH)
    with init_empty_weights():
        model = InstructBlipForConditionalGeneration._from_config(config)
    model.tie_weights()

     ### _pickle.PicklingError: Can't pickle <function Conv2d.forward at 0x7f9cf068df70>: it's not the same object as 
    device_map = infer_auto_device_map(model,
                                       max_memory={0: '8GiB', 1: '10GiB'},
                                       dtype=torch.float16,
                                       no_split_module_classes=InstructBlipForConditionalGeneration._no_split_modules)
    
    ### work fine
    # device_map = {"":"cuda:0"}

    load_checkpoint_and_dispatch(model, MODEL_PATH, device_map=device_map, dtype="float16")

    p = ValidationProcess(model)
    p.start()
    p.join()

```

### Expected behavior

Beable to load model to multiple GPUs and run in multiprocessing mode.

**Comment by ZeguanXiao** [comment]
I It appears that the issue arises because the `forward` method of the module is wrapped by `accelerate`, causing the failure of pickling the model when multiprocessing is attempted. Do you have any workarounds to solve this problem?

**Comment by muellerzr** [comment]
cc @SunMarc

**Comment by ZeguanXiao** [comment]
Actually, I use` torch.multiprocessing`. While not common in common use cases, some scenarios require it directly.

**Comment by SunMarc** [comment]
After looking into the error, it looks like there is no easy workaround to solve this problem. The wrapping of the forward by accelerate is done during the loading of the weights and not the initialization of the model and we can't change that behavior. More information on why we can't pickle the model [here](https://stackoverflow.com/questions/52185507/pickle-and-decorated-classes-picklingerror-not-the-same-object) and [here](https://discuss.pytorch.org/t/exception-has-occurred-picklingerror-cant-pickle-class-torch-c-variablefunctions-its-not-the-same-object-as-torch-c-variablefunctions/91660/6).
