### ISSUE TITLE
FP8 Inference

### ISSUE THREAD

**Issue by epinnock** [huggingface/accelerate#1924]
Does accelerate support fp8 Inference? If so is there any documentation or examples?

**Comment by pacman100** [comment]
Hello, Accelerate supports FP8. See the documentation of Accelerator class here https://huggingface.co/docs/accelerate/package_reference/accelerator#accelerate.Accelerator.mixed_precision. I think specifying `fp8` as `mixed_precision` should do the job. Could you please try it out and let us know? cc @muellerzr who knows a lot more about FP8.

**Comment by muellerzr** [comment]
Yep, just do `accelerator.prepare(model)` after specifying `mixed_precision="fp8"` either in the accelerator or during `accelerate launch`, and your model will be wrapped for fp8 inference. 

TL;DR:

```python
from accelerate import Accelerator

accelerator = Accelerator(mixed_precision="fp8")

model = accelerator.prepare(model)
```
Note that this fp8 requires the use of specific nvidia hardware.

**Comment by Jack000** [comment]
I'm interested in using fp8 purely in inference mode to increase throughput and decrease memory use.

Is there a way to load only the fp8 weights? Mixed precision seems to use more memory.

would this work to save the fp8 weights? This usecase doesn't seem to be covered in the docs.

```
accelerator = Accelerator(mixed_precision="fp8")
model = accelerator.prepare(model)
model = accelerator.unwrap_model(model)
model.save_pretrained(...)

```

**Comment by muellerzr** [comment]
Correct, exactly. (Which should be soon-ish iirc)
