### ISSUE TITLE
[Feature Request] gather non-tensors objects for metrics (remove duplicates)

### ISSUE THREAD

**Issue by ywangmy** [huggingface/accelerate#1925]
As discussed in #1383, in certain NLP tasks, it is convenient to retain sentences as strings in the dataloader instead of tokenizing them into tensors. I propose implementing a function that gathers non-tensor objects and removes duplicates within the last batch. This function would complement the existing `gather_for_metrics()` (used for tensors) and enhance the capabilities for distributed evaluation in such scenarios. 

Thank you.

**Comment by Lorenzobattistela** [comment]
Hey, I'd like to pick up this issue.

So basically we would need a new function like `gather_for_metrics` for objects and that removes duplicates within the last batch, correct?
As `gather_object` is implemented here: https://github.com/huggingface/accelerate/blob/main/src/accelerate/utils/operations.py
maybe it makes sense do build this in the same file.

What do you think @muellerzr ?

**Comment by muellerzr** [comment]
@Lorenzobattistela or to do a check if something is a tensor or not in `gather_for_metrics`, and call `gather_object` and de-dupe instead :) This way it will automatically work for anything we pass to it. 

Yes that is exactly it! And ideally add some tests to `accelerate/test_utils/scripts/test_metrics`

**Comment by Lorenzobattistela** [comment]
Yeah this approach makes sense. I'll start now. Feel free to assign me :)

**Comment by Lorenzobattistela** [comment]
I thought something like this:

```python
def gather_for_metrics(self, input_data):
        """
        Gathers `tensor` or object and potentially drops duplicates in the last batch if on a distributed system. For objects, duplicates are removed. Should be used
        for gathering the inputs and targets for metric calculation.

        Args:
            input (`torch.Tensor`, a nested tuple/list/dictionary of `torch.Tensor`, `object` or a nested tuple/list/dictionary of `object`):
                The tensors / objects for calculating metrics across all processes

        Example:

        ```python
        >>> # Assuming two processes, with a batch size of 5 on a dataset with 9 samples
        >>> import torch
        >>> from accelerate import Accelerator

        >>> accelerator = Accelerator()
        >>> dataloader = torch.utils.data.DataLoader(range(9), batch_size=5)
        >>> dataloader = accelerator.prepare(dataloader)
        >>> batch = next(iter(dataloader))
        >>> gathered_items = accelerator.gather_for_metrics(batch)
        >>> len(gathered_items)
        9
        ```
        """
        def check_input(input_data):
            if isinstance(input_data, (list, tuple)):
                return all(is_torch_tensor(item) for item in input_data)
            return is_torch_tensor(input_data)

        

        if not check_input(input_data):
            try:
                obj = gather_object(input_data)
                # deduplicate objects within the last batch
                if self.gradient_state.end_of_dataloader and self.gradient_state.remainder > 0:
                    deduplicated_objects = []
                    seen_objects = set()
                    for item in obj:
                        if item not in seen_objects:
                            deduplicated_objects.append(item)
                            seen_objects.add(item)
                return deduplicated_objects

            except Exception:
                return obj

        tensor = self.gather(input_data)
```

Did not found a util for dedup, am I missing something? Also I'm thinking a better name for `input_data`, which is not very descriptive. Maybe `tensor_or_object`.
What do you think @muellerzr ?
Thanks in advance

**Comment by muellerzr** [comment]
@Lorenzobattistela start at the implementation of Accelerator.gather_for_metrics, that's where it should live and be modified. (You should just see a call to gather there + the dedupe)

**Comment by Lorenzobattistela** [comment]
Actually this is at `accelerator.py` function `gather_for_metrics`

**Comment by Lorenzobattistela** [comment]
You mean `accelerate.py`  as in `src/accelerate/accelerator.py` at the function `gather_for_metrics`? Thats where i was changing

**Comment by Lorenzobattistela** [comment]
@muellerzr we can close this
