### ISSUE TITLE
Does device_map no longer support CUDA_VISIBLE_DEVICES?

### ISSUE THREAD

**Issue by nomadlx** [huggingface/accelerate#1927]
I have some 8-gpus server, but only need 2-gpus per evaluation, so I want to be able to simply set up the specified gpu ids (such as 6,7) and `device_map="auto"` automatically assign the model to those gpus in a balanced way.
With older version, I achieved this nicely with the setup of `CUDA_VISIBLE_DEVICES=6,7`. But after I updated to a new version, it no longer worked and it would assign the model across all gpus.
I don't want to specify max_memory because I have servers with different graphics cards that have different gpu memory.
Of course I could write a function to automatically determine the size of the gpu memory to generate max_memory, but I wonder **if there is an easier way to achieve what I want, just as I setting `CUDA_VISIBLE_DEVICES` in older version. And is it a bug that `CUDA_VISIBLE_DEVICES` is no longer supported?**

**Comment by muellerzr** [comment]
cc @SunMarc

**Comment by SunMarc** [comment]
Hi @nomadlx, thanks for reporting! This is indeed strange and `CUDA_VISIBLE_DEVICES` should still be supported. I'll look into that. Can you give me a minimal reproductible script + the env that you are using ?

**Comment by SunMarc** [comment]
I'm using accelerate==0.22 and transformers==4.33 and it works fine with the following script:
```py 
from transformers import LlamaForCausalLM

model = LlamaForCausalLM.from_pretrained(
    "meta-llama/Llama-2-7b-hf", device_map="auto"
)
print(model.hf_device_map)
```

**Comment by nomadlx** [comment]
reproductible script:
```python
import os
import torch
from transformers import AutoModelForCausalLM

os.environ["CUDA_VISIBLE_DEVICES"] = "6,7"
model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-7B-Chat", device_map="auto", trust_remote_code=True)
print(model.hf_device_map)
```
version info:
```
accelerate==0.22.0
transformers==4.31.0
torch==1.12.0+cu113
```

I have observed a strange phenomenon that when I comment out `import torch` or upgrade torch, it works well.

**Comment by muellerzr** [comment]
@nomadlx what do you upgrade torch to where you see that work? If it works when upgrading torch, that would be our recommendation I imagine

**Comment by SunMarc** [comment]
As @muellerzr said, you should then upgrade torch. I tried with the env that you have but it worked on my side 😅

**Comment by maheshmouli** [comment]
I'm trying to run pretrain stable diffusion model v1.5 but it is throwing me this error "    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
" 

this is the cuda visible devices "os.environ['CUDA_VISIBLE_DEVICES'] = '2,3,4'" I have 8 gpus but still it is not giving the same error.

**Comment by SunMarc** [comment]
Hi @maheshmouli, this error shows that CUDA is getting an invalid decide ordinal. It's not linked to this issue.

**Comment by xgwang** [comment]
> Hi [@maheshmouli](https://github.com/maheshmouli), this error shows that CUDA is getting an invalid decide ordinal. It's not linked to this issue.

i  got the same error as [maheshmouli](https://github.com/maheshmouli) had,  with accelerate 1.6.0.  it seems ok with 1.7.0. let me verify more.

i do not have any customized CUDA_VISIBLE_DEVICES settings.
