### ISSUE TITLE
I'm loading llama2 on a single machine with dual GPUs using Accelerate, and it's giving me a CUDA error. It seems that tensors are unexpectedly being allocated to two different GPUs during runtime.

### ISSUE THREAD

**Issue by sev777** [huggingface/accelerate#1930]
### System Info

```Shell
I'm loading llama2 on a single machine with dual GPUs using Accelerate, and it's giving me a CUDA error. It seems that tensors are unexpectedly being allocated to two different GPUs during runtime.
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### System Info

I'm loading llama2 on a single machine with dual GPUs using Accelerate, and it's giving me a CUDA error. It seems that tensors are unexpectedly being allocated to two different GPUs during runtime.

My Computer use:

Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              64
Vendor ID:           AuthenticAMD
CPU family:          23
Model:               49
Model name:          AMD EPYC 7282 16-Core Processor
Virtualization:      AMD-V

GPU: A100 40G

```python
import torch
from transformers import LlamaTokenizer, LlamaForCausalLM
from accelerate import Accelerator
import os
os.environ['CUDA_VISIBLE_DEVICES']="0,1"

accelerator = Accelerator()
model_path = '/root/sev777/LMs/huggingface/llama2_13B'

tokenizer = LlamaTokenizer.from_pretrained(model_path)
model = LlamaForCausalLM.from_pretrained(
    model_path,device_map='auto'
)
model = accelerator.prepare(model)


prompt = 'Q: What is the largest animal?\nA:'
input_ids = tokenizer(prompt, return_tensors="pt").input_ids.cuda(0)
generation_output = model.generate(
    input_ids=input_ids, max_new_tokens=32
)

print(generation_output)

```

My log is: 

`
Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]
Loading checkpoint shards:  33%|███▎      | 1/3 [00:10<00:20, 10.00s/it]
Loading checkpoint shards:  67%|██████▋   | 2/3 [00:19<00:09,  9.64s/it]
Loading checkpoint shards: 100%|██████████| 3/3 [00:25<00:00,  7.87s/it]
Loading checkpoint shards: 100%|██████████| 3/3 [00:25<00:00,  8.39s/it]
Traceback (most recent call last):
  File "mt.py", line 20, in <module>
    generation_output = model.generate(
  File "/root/sev777/miniconda3/envs/llama_adapter/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/root/sev777/miniconda3/envs/llama_adapter/lib/python3.8/site-packages/transformers/generation/utils.py", line 1538, in generate
../aten/src/ATen/native/cuda/IndexKernel.cu:91: operator(): block: [0,0,0], thread: [0,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:91: operator(): block: [0,0,0], thread: [1,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:91: operator(): block: [0,0,0], thread: [2,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
...

../aten/src/ATen/native/cuda/IndexKernel.cu:91: operator(): block: [0,0,0], thread: [32,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:91: operator(): block: [0,0,0    ], thread: [33return self.greedy_search(,0
,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu  File "/root/sev777/miniconda3/envs/llama_adapter/lib/python3.8/site-packages/transformers/generation/utils.py", line 2362, in greedy_search
:91: operator(): block: [0,0,0], thread: [34,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:91: operator(): block: [0,0,0], thread: [35,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.

...

../aten/src/ATen/native/cuda/IndexKernel.cu:91: operator(): block: [1,0,0], thread: [127,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
    return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

`

"Is this because my GPU and CPU are conflicting, or is it due to other reasons?"

Thanks!

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [X] My own task or dataset (give details below)

### Reproduction

I'm loading llama2 on a single machine with dual GPUs using Accelerate, and it's giving me a CUDA error. It seems that tensors are unexpectedly being allocated to two different GPUs during runtime.

### Expected behavior

I'm loading llama2 on a single machine with dual GPUs using Accelerate, and it's giving me a CUDA error. It seems that tensors are unexpectedly being allocated to two different GPUs during runtime.

### Expected behavior

I'm loading llama2 on a single machine with dual GPUs using Accelerate, and it's giving me a CUDA error. It seems that tensors are unexpectedly being allocated to two different GPUs during runtime.

**Comment by SunMarc** [comment]
Hi @sev777, can you try without the `model = accelerator.prepare(model)`. It is unnecessary when doing inference.

**Comment by sev777** [comment]
> Hi @sev777, can you try without the `model = accelerator.prepare(model)`. It is unnecessary when doing inference.

Thanks, I realized that it seems to be related to my device and I am looking for a [solution.
](https://github.com/huggingface/transformers/issues/26001)
