### ISSUE TITLE
accelerate.prepare(model) gets CUDA OOM

### ISSUE THREAD

**Issue by JiyouShin** [huggingface/accelerate#1931]
Hi, I am new to Accelerate and I got stuck on this. 
Below is my code and I kept getting CUDA out of memory issue at model load with accelerator.prepare

I am using A100 80G GPU, model size is 11.6G and its params are 5.8B

```
model = AutoModelForCausalLM.from_pretrained(args.model_name)

from transformers import AdamW, get_scheduler

optimizer = AdamW(model.parameters(), lr = args.learning_rate)
num_training_steps = args.epochs * len(train_dataloader)
scheduler = get_scheduler(
    "linear",
    optimizer = optimizer,
    num_warmup_steps = args.warmup_steps,
    num_training_steps = num_training_steps,
)

optimizers = optimizer, scheduler

from accelerate import Accelerator

accelerator = Accelerator()

model, optimizer, train_dataloader, scheduler = accelerator.prepare(
      model, optimizer, train_dataloader, scheduler) ---> I got OOM issue at here.

print("load model")
```

And below is an error message.

```
Traceback (most recent call last):
  File "train.py", line 187, in <module>
    model, optimizer, train_dataloader, scheduler = accelerator.prepare(
  File "/data_new/sjy98/polyglot-ko/data-parallel/deepspeed-venv/lib/python3.8/site-packages/accelerate/accelerator.py", line 1202, in prepare
    result = tuple(
  File "/data_new/sjy98/polyglot-ko/data-parallel/deepspeed-venv/lib/python3.8/site-packages/accelerate/accelerator.py", line 1203, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
  File "/data_new/sjy98/polyglot-ko/data-parallel/deepspeed-venv/lib/python3.8/site-packages/accelerate/accelerator.py", line 1030, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
  File "/data_new/sjy98/polyglot-ko/data-parallel/deepspeed-venv/lib/python3.8/site-packages/accelerate/accelerator.py", line 1292, in prepare_model
    model = model.to(self.device)
  File "/data_new/sjy98/polyglot-ko/data-parallel/deepspeed-venv/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1811, in to
    return super().to(*args, **kwargs)
  File "/data_new/sjy98/polyglot-ko/data-parallel/deepspeed-venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/data_new/sjy98/polyglot-ko/data-parallel/deepspeed-venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/data_new/sjy98/polyglot-ko/data-parallel/deepspeed-venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/data_new/sjy98/polyglot-ko/data-parallel/deepspeed-venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/data_new/sjy98/polyglot-ko/data-parallel/deepspeed-venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/data_new/sjy98/polyglot-ko/data-parallel/deepspeed-venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 256.00 MiB (GPU 1; 79.35 GiB total capacity; 4.48 GiB already allocated; 208.62 MiB free; 4.50 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 839988 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 839989) of binary: /data_new/sjy98/polyglot-ko/data-parallel/deepspeed-venv/bin/python3
```

Below is my accelerate config file.

```
compute_environment: LOCAL_MACHINE
deepspeed_config:
 gradient_accumulation_steps: 1
 gradient_clipping: 1.0
 offload_optimizer_device: none
 offload_param_device: none
 zero3_init_flag: true
 zero_stage: 2
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

Also my command line is like this
`accelerate launch --config_file default_config.yaml --multi_gpu --gpu_ids “0,2” --num_processes 2 train.py`
but I found out that only one gpu is being used when model is being loaded. 

Can anyone please advise to me what I have done wrong? Thanks in advance.

**Comment by sl5035** [comment]
Hi, I'm having the same issue here. Please let me know if youve fixed it

**Comment by Congcong-Song** [comment]
im facing the same problem.

**Comment by bailixuance** [comment]
im facing the same problem. Please let me know if youve fixed it

**Comment by muellerzr** [comment]
Hi all, can we please provide a model name for me to test with? Thanks

**Comment by bailixuance** [comment]
> Hi all, can we please provide a model name for me to test with? Thanks

my model addr is : https://huggingface.co/codefuse-ai/CodeFuse-13B. 

I want to finetune this model using its script, in this addr: https://github.com/codefuse-ai/MFTCoder/blob/main/mft_peft_hf/src/pefts/mft_accelerate.py. 

my accelerate yaml  accelerate_ds_config.yaml is : 
compute_environment: LOCAL_MACHINE
deepspeed_config:
  gradient_accumulation_steps: 1
  gradient_clipping: 1.0
  offload_optimizer_device: cpu
  offload_param_device: none
  zero3_init_flag: false
  zero3_save_16bit_model: true
  zero_stage: 2
distributed_type: DEEPSPEED
downcast_bf16: 'no'
dynamo_backend: 'NO'
fsdp_config: {}
machine_rank: 0
main_training_function: main
megatron_lm_config: {}
mixed_precision: 'bf16'
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
use_cpu: false

I run script use this script: CUDA_VISIBLE_DEVICES=2,3 accelerate launch --config_file accelerate_ds_config.yaml mft_accelerate.py --train_config configs/gpt_neox_train_config_test.json

then I will get cuda OOM: 
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 200.00 MiB (GPU 0; 23.70 GiB total capacity; 22.41 GiB already allocated; 140.56 MiB free; 22.43 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 200.00 MiB (GPU 2; 23.70 GiB total capacity; 22.41 GiB already allocated; 140.56 MiB free; 22.43 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Besides oom bug, I can't set cuda device by CUDA_VISIBLE_DEVICES=2,3.
This bug has been bothering me for two days, I don't know what to do anymore.

Looking forward your replay!

**Comment by JiyouShin** [comment]
> Hi all, can we please provide a model name for me to test with? Thanks

model_name : 'EleutherAI/polyglot-ko-5.8b'

Thank you ! :)

**Comment by BenjaminBossan** [comment]
@JiyouShin 

Your error message is:

> torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 256.00 MiB (GPU 1; 79.35 GiB total capacity; 4.48 GiB already allocated; 208.62 MiB free; 4.50 GiB reserved in total by PyTorch)

To me, this looks like something else is already occupying your GPU memory, hence the model cannot be allocated, even if it should theoretically fit. Is this possible?

@bailixuance 

Your error message is:

> torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 200.00 MiB (GPU 0; 23.70 GiB total capacity; 22.41 GiB already allocated; 140.56 MiB free; 22.43 GiB reserved in total by PyTorch)

The model you're trying to load seems to be too large for the GPU. Are you sure it should fit?

**Comment by JiyouShin** [comment]
> @JiyouShin
> 
> Your error message is:
> 
> > torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 256.00 MiB (GPU 1; 79.35 GiB total capacity; 4.48 GiB already allocated; 208.62 MiB free; 4.50 GiB reserved in total by PyTorch)
> 
> To me, this looks like something else is already occupying your GPU memory, hence the model cannot be allocated, even if it should theoretically fit. Is this possible?
> 
> @bailixuance
> 
> Your error message is:
> 
> > torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 200.00 MiB (GPU 0; 23.70 GiB total capacity; 22.41 GiB already allocated; 140.56 MiB free; 22.43 GiB reserved in total by PyTorch)
> 
> The model you're trying to load seems to be too large for the GPU. Are you sure it should fit?



> @JiyouShin
> 
> Your error message is:
> 
> > torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 256.00 MiB (GPU 1; 79.35 GiB total capacity; 4.48 GiB already allocated; 208.62 MiB free; 4.50 GiB reserved in total by PyTorch)
> 
> To me, this looks like something else is already occupying your GPU memory, hence the model cannot be allocated, even if it should theoretically fit. Is this possible?
> 
> @bailixuance
> 
> Your error message is:
> 
> > torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 200.00 MiB (GPU 0; 23.70 GiB total capacity; 22.41 GiB already allocated; 140.56 MiB free; 22.43 GiB reserved in total by PyTorch)
> 
> The model you're trying to load seems to be too large for the GPU. Are you sure it should fit?

Thank you for your reply. 
I've checked GPU memory before I run the code and it was empty. When allocating the model, GPU memory usage increased and then stopped with the error message.

**Comment by BenjaminBossan** [comment]
Hmm, that's strange. Is the error always the same when you re-run? What is `accelerator.device`, what dtype is used?

**Comment by JiyouShin** [comment]
> Hmm, that's strange. Is the error always the same when you re-run? What is `accelerator.device`, what dtype is used?

Sorry for late response.

cuda:1
<class 'torch.device'>
cuda:0
<class 'torch.device'>

This is my accelerator.device and dtype. I am using 2 GPUS and numbers are 0 and 1.
