### ISSUE TITLE
Allow (back) distributed setting & single process/GPU

### ISSUE THREAD

**Issue by WarmongeringBeaver** [huggingface/accelerate#1932]
https://github.com/huggingface/accelerate/blob/727d624322c67db66a43c559d8c86414d5ffb537/src/accelerate/commands/launch.py#L813-L814

This sanity check was added in `0.22` in PR #905 , closing #903.

Is there really a good reason to _prevent_ the setup of a distributed setting while running a single process?

- One (well, at least me) could for example like to reuse some code written for a distributed setting _as-is_, but in a single-GPU & single-process setting.
- Yes it works.
- Funnily, if `--num_processes` is not passed and a single GPU is available, `accelerate` will complain:
```bash
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `1`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
```
before continuing its worriless journey as pre-`0.22`. 🙂 

I propose to simply raise a warning (but I might lack insight on why distributed setup & single process is generally a bad idea?)

**Comment by muellerzr** [comment]
Yes, because DDP is strictly un-needed if you are running on a single node, and just adds extra wrappers and some bloat that is not needed. Yes it works, but it's not efficient nor recommended in any capacity. (Unless say you have two nodes, each with a single GPU). 

Not a complain, just setting auto values for you. 

So, this is fully intentional to prevent user errors for doing something they should not do 😉

**Comment by muellerzr** [comment]
If you want to reuse code, that is what the entirety of Accelerate is designed around 😉

**Comment by WarmongeringBeaver** [comment]
Got it.

I need to use some custom `torch.distributed` code to fulfill my needs in a distributed setting but sometimes also use only one GPU. For some reason I thought that accessing the type of distribution to accomodate each case was tricky (and thus reluctant to do it 👼🏼). 

Turns out it's trivial thanks to `Accelerator.distributed_type`. 🙃 ❤️
