### ISSUE TITLE
`get_balanced_memory` raises a `ZeroDivisionError` when `max_memory` of the single GPU available is set to 0

### ISSUE THREAD

**Issue by Mostafa-Samir** [huggingface/accelerate#1933]
### System Info

```Shell
- `Accelerate` version: 0.22.0
- Platform: Linux-6.2.0-1009-aws-x86_64-with-glibc2.17
- Python version: 3.8.17
- Numpy version: 1.24.4
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 62.01 GB
- GPU type: Tesla T4
- `Accelerate` default config:
        Not found
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

On a machine with a single GPU available, run:

```python
import psutil

from transformers import AutoModel

flant5 = AutoModel.from_pretrained(
    "google/flan-t5-xl",
    device_map="auto",
    max_memory={
        0:0, 
        "cpu": psutil.virtual_memory().available
    }
)
```

### Output
```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    flant5 = AutoModel.from_pretrained(
  File "/home/ubuntu/miniconda3/envs/venv/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 516, in from_pretrained
    return model_class.from_pretrained(
  File "/home/ubuntu/miniconda3/envs/venv/lib/python3.8/site-packages/transformers/modeling_utils.py", line 3012, in from_pretrained
    max_memory = get_balanced_memory(
  File "/home/ubuntu/miniconda3/envs/venv/lib/python3.8/site-packages/accelerate/utils/modeling.py", line 802, in get_balanced_memory
    per_gpu = module_sizes[""] // (num_devices - 1 if low_zero else num_devices)
ZeroDivisionError: integer division or modulo by zero
```

### Expected behavior

`get_balanced_memory` should not raise a `ZeroDivisionError` when `max_memory` configurations renders the `num_devices` to be 0. A check should be made if `num_devices` is 0 and immediately return the `max_memory` dictionary without attempting to divide the modules sizes on the GPUs.

**Comment by muellerzr** [comment]
cc @SunMarc

**Comment by SunMarc** [comment]
Thanks for reporting. The PR above should fix the issue. Note that if your goal is only to use the cpu, you can do it by passing only device_map={"":"cpu"} or use low_cpu_mem_usage=True.

**Comment by Mostafa-Samir** [comment]
Thanks for the prompt action @SunMarc 
If we passed `device_map={"":"cpu"}`, will it still offload any excess weights to disk?

**Comment by SunMarc** [comment]
Oh indeed, if your goal is to offload any excess weights to disk, then you can use your method or just set `os.environ["CUDA_VISIBLE_DEVICES"]="" `and `device_map="auto"`.  `device_map={"":"cpu"}` wont work in that case !
