### ISSUE TITLE
RuntimeError: No executable batch size found, reached zero.

### ISSUE THREAD

**Issue by deven367** [huggingface/accelerate#1934]
### System Info

```Shell
accelerate version: 0.22.0
torch version: 2.0.1
numpy version: 1.25.2
python version: 3.10.12
os: SUSE Linux Enterprise Server 15 SP3
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

The dataset used in the code below is public.

The code pasted below is a modification of fine-tuning OPT taken from &rarr; [here](https://colab.research.google.com/drive/1epQObYxxHPwBG2Uztzkg37LY84cSxGhF#scrollTo=NR3yyfWSMDi5)
from the example above, following things were changed,
1. no use of `peft`
2. training from scratch
3. addition of validation set
4. additional arguments were used from the `TrainingArguments` class

Here, upon using the `auto_find_batch_size=True` flag, I was assuming that accelerate would find the ideal batch size. So, I am not sure that caused the runtime error as the training ran successfully for over 2.5 hours.

Here is my code,

```py
from transformers import AutoTokenizer, AutoConfig, AutoModelForCausalLM, OPTConfig
from datasets import load_dataset
import transformers


def main():
    model_name = "facebook/opt-125m"
    # cfg = AutoConfig.from_pretrained(model_name)
    cfg = OPTConfig()
    model = AutoModelForCausalLM.from_config(cfg)

    tokenizer = AutoTokenizer.from_pretrained("facebook/opt-350m")

    ds = load_dataset("deven367/babylm-10M")
    data = ds.map(lambda samples: tokenizer(samples["text"]), batched=True)

    trainer = transformers.Trainer(
        model=model,
        # train_dataset=data['train'],
        train_dataset=data["train"],
        eval_dataset=data["valid"],
        args=transformers.TrainingArguments(
            auto_find_batch_size=True,
            per_device_train_batch_size=2048,
            per_device_eval_batch_size=2048,
            gradient_accumulation_steps=4,
            # warmup_steps=100,
            num_train_epochs=200.,
            evaluation_strategy='epoch',
            learning_rate=2e-4,
            # fp16=True,
            logging_steps=1,
            output_dir="outputs",
        ),
        data_collator=transformers.DataCollatorForLanguageModeling(
            tokenizer, mlm=False
        ),
    )
    model.config.use_cache = (
        False  # silence the warnings. Please re-enable for inference!
    )
    trainer.train()


if __name__ == "__main__":
    main()
```

Here is the entire stacktrace
```py
File "/geode2/home/u020/demistry/BigRed200/projects/train.py", line 56, in <module>
    main()
  File "/geode2/home/u020/demistry/BigRed200/projects/train.py", line 49, in main
    trainer.train( )
  File "/N/u/demistry/BigRed200/mambaforge/envs/torch/lib/python3.10/site-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
  File "/N/u/demistry/BigRed200/mambaforge/envs/torch/lib/python3.10/site-packages/accelerate/utils/memory.py", line 134, in decorator
    raise RuntimeError("No executable batch size found, reached zero.")
RuntimeError: No executable batch size found, reached zero.
Traceback (most recent call last):
  File "/geode2/home/u020/demistry/BigRed200/projects/train.py", line 56, in <module>
    main()
  File "/geode2/home/u020/demistry/BigRed200/projects/train.py", line 49, in main
    trainer.train( )
  File "/N/u/demistry/BigRed200/mambaforge/envs/torch/lib/python3.10/site-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
  File "/N/u/demistry/BigRed200/mambaforge/envs/torch/lib/python3.10/site-packages/accelerate/utils/memory.py", line 134, in decorator
    raise RuntimeError("No executable batch size found, reached zero.")
```

### Expected behavior

Maybe find the ideal batchsize and continue training?

**Comment by muellerzr** [comment]
This means you kept hitting CUDA OOM all the way to the end, at some point, after the batch size was already 1. So there's not really much we can do, since again, you hit CUDA OOM at the smallest possible batch size :)

**Comment by deven367** [comment]
@muellerzr Wow, never thought I'd run into OOM on 4xA100s! I think in this case then, all I can do is reduce the `max_position_embeddings`?

**Comment by deven367** [comment]
Oh, I haven't used FSDP or DeepSpeed before, should I just change `accelerate config` then? Or could you just point me in the right direction? I looked at the docs site for `accelerate` and I'm not sure where to begin...

**Comment by deven367** [comment]
Thanks a lot Zach, I'll go ahead and close this issue!
