### ISSUE TITLE
`vae.encode()` cannot work will multiple gpus

### ISSUE THREAD

**Issue by zheng95z** [huggingface/accelerate#1938]
### System Info

```Shell
- `Accelerate` version: 0.22.0
- Platform: Linux-5.4.241-150.347.amzn2.x86_64-x86_64-with-glibc2.31
- Python version: 3.9.17
- Numpy version: 1.25.2
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 1121.82 GB
- GPU type: NVIDIA A100-SXM4-40GB


`Accelerate` config:
compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
downcast_bf16: 'no'
gpu_ids: all
machine_rank: 0
main_training_function: main
mixed_precision: 'no'
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

```
...

# Load and modify vae
vae = AutoencoderKL.from_pretrained(
    args.pretrained_model_name_or_path,
    subfolder="vae"
)

...

vae, optimizer, train_dataloader, lr_scheduler = accelerator.prepare(
        vae, optimizer, train_dataloader, lr_scheduler
    )

...

vae.train()

with accelerator.accumulate(vae):
  posterior = vae.encode(target).latent_dist

```

### Expected behavior

`vae.encode()` works properly.

Now it's:
```bash
File "train_vae.py", line 484, in main
    posterior = vae.encode(target).latent_dist
  File "/opt/conda/envs/diffusers/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DistributedDataParallel' object has no attribute 'encode'
```

**Comment by BenjaminBossan** [comment]
Hmm, this seems to be a problem with PyTorch's `DistributedDataParallel` class, which only exposes the `forward` method of the module it wraps. I think you would run into the same issue if you were using DDP directly, without accelerate.

There are probably some workarounds for this problem, like patching `DistributedDataParallel` or making the `forward` method of `AutoencoderKL` actually return the encoding result, but all of these comes with drawbacks and probably have no place in accelerate.

**Comment by muellerzr** [comment]
As Benjamin said, so you can get this via `model.model.encode()` iirc

**Comment by ziyizhetutanota** [comment]
hello, I have similar problem, how did you solve it.
