### ISSUE TITLE
could the config performed via config file/shell command?

### ISSUE THREAD

**Issue by zhhongzhi** [huggingface/accelerate#194]
Really enjoy the cli tool for setting. 
But there are some situation that the cli is not preferred. For instance, a docker in task mode [the docker is opened when the job start and released when the job finished]. 
Could we set the accelerate via config file/shell command?

**Comment by sgugger** [comment]
Running `accelerate config` is just to make life easier for users that have access to a terminal. You don't need to run it and can actually set all the arguments when launching `accelerate launch`.

**Comment by zhhongzhi** [comment]
Many thanks!
