### ISSUE TITLE
# Question about Accelerate vs DDP

### ISSUE THREAD

**Issue by mexiQQ** [huggingface/accelerate#196]
Hi Huggingface team:

Thank you guys very much for your contribution to multi-device training.

I would like to ask the following question：

1. Will  Accelerate take more GPU memory than DDP on each GPU device? if yes, can you give a concrete number?
2. If I need to use a large batch size on each device, will it help if I change from Accelerate to DDP?

Thank you very much.

**Comment by sgugger** [comment]
Please use the [forums](https://discuss.huggingface.co/) to ask questions as we keep issues for bug reports and feature requests only :-)
As for your questions, Accelerate is just a wrapper around DDP to work on other contexts as well (TPUs but also single process for debugging) and adds support for things like mixed precision training or deepspeed. So it will take exactly the same amount of space as DDP.

**Comment by mexiQQ** [comment]
Thank you very much for your reply. And sorry for my action.
