### ISSUE TITLE
[Feature request] Gradient accumulation with TPUs

### ISSUE THREAD

**Issue by ifeherva** [huggingface/accelerate#1962]
I see this is currently not supported. Is this a limitation of TPUs or just not yet implemented? In the latter I might do a PR for it.

**Comment by muellerzr** [comment]
Looks like nothing special is needed for this in the end. @ifeherva would you like to try and do this as a PR? Otherwise I'll try and get to this before I go on holiday Friday :) (It's the same as doing it on a single GPU)

**Comment by ifeherva** [comment]
I can look into it but cannot promise I will finish it by Friday.

**Comment by muellerzr** [comment]
No need to finish by friday @ifeherva, that was my own limit from before I go on holiday :) You have two weeks if you choose to 😉

**Comment by muellerzr** [comment]
That's alright as well, we generally have a script that tests gradient accumulation, so it just needs to be ran on TPU. No new tests need to be added actually :)

**Comment by muellerzr** [comment]
see `accelerate/src/accelerate/test_utils/scripts/test_sync.py`
