### ISSUE TITLE
Multi Worker GPU/CPU Sharding Configuration

### ISSUE THREAD

**Issue by ericbugin1** [huggingface/accelerate#1965]
Hello, I am trying to understand what configurations are required for Accelerate to be able to shard a model across multiple workers. I want to use the Transformers library to be able to split a large model across multiple nodes on an EMR cluster. Now, the cluster won't have any configurations (neither Torch, nor Tensorflow etc. and I have to start from scratch installing libraries).

I am wondering what is needed for Accelerate to be able to be used via the "device_map = 'auto' " param to be able to split across all of the nodes if I were, for example, use the Falcon 40B model. 

I don't see anyone using EMR for such operations, but I have to use what I have available, which is EMR. Any thoughts?

**Comment by SunMarc** [comment]
It's not on our roadmap yet as it is very niche and quite complicated to get it done. In the meantime, you can explore for example deepspeed inference that should support optimized mutli-node inference.
