### ISSUE TITLE
 launch --multi_gpu: same script hangs if launched with different flag on same GPUs

### ISSUE THREAD

**Issue by sg-wbi** [huggingface/accelerate#1966]
### System Info

```Shell
- `Accelerate` version: 0.22.0
- Platform: Linux-5.3.18-150300.59.101-default-x86_64-with-glibc2.31
- Python version: 3.9.7
- Numpy version: 1.25.2
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 503.53 GB
- GPU type: GeForce RTX 3090
- `Accelerate` default config:
        Not found
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

I have multiple gpus available with sufficient amount of memory to run multiple processes.

I want to run the same script in parralle just with different flags.

However if I try this:

```bash
# tmux window 1
CUDA_VISIBLE_DEVICES=2,3 accelerate launch --multi_gpu --num_processes 2 --main_process_port 0 cv_example.py --data_dir ./images

# tmux window 2
CUDA_VISIBLE_DEVICES=2,3 accelerate launch --multi_gpu --num_processes 2 --main_process_port 0 cv_example.py --data_dir ./images --mixed_precision fp16
```
Thes script in the second window hangs.

Using only partially overlapping gpus shows the same behaviour:

```bash
# tmux window 1
CUDA_VISIBLE_DEVICES=1,2 accelerate launch --multi_gpu --num_processes 2 --main_process_port 0 cv_example.py --data_dir ./images

# tmux window 2
CUDA_VISIBLE_DEVICES=2,3 accelerate launch --multi_gpu --num_processes 2 --main_process_port 0 cv_example.py --data_dir ./images  --mixed_precision fp16
```

Any idea why this is happening?

To reproduce this simply call the `cv_exmaple.py` script. Change `num_epochs : 3` to `num_epochs : 20`  on [this line](https://github.com/huggingface/accelerate/blob/main/examples/cv_example.py#L206) in `cv_example.py` to allow the script to run for longer. 

Thank you!

### Expected behavior

Both scripts should run:

```bash
# tmux window 1
CUDA_VISIBLE_DEVICES=2,3 accelerate launch --multi_gpu --num_processes 2 --main_process_port 0 cv_example.py --data_dir ./images

# tmux window 2
CUDA_VISIBLE_DEVICES=2,3 accelerate launch --multi_gpu --num_processes 2 --main_process_port 0 cv_example.py --data_dir ./images --mixed_precision fp16
```

**Comment by sg-wbi** [comment]
Thanks for the incredibly fast response. This is kind of a bummer though.

So not even plain `torch` allows this? E.g. `torchrun`?

Thanks again.

**Comment by muellerzr** [comment]
Nope, not to my knowledge.

**Comment by sg-wbi** [comment]
Too bad. Thanks again!
