### ISSUE TITLE
only one gpu used when run python script.py

### ISSUE THREAD

**Issue by world2vec** [huggingface/accelerate#197]
Hi,
I did not launch the script, as this is not a must. But the python script only use one GPU.

In [6]: acc = Accelerator()

In [7]: acc.device
Out[7]: device(type='cuda')

In [8]: acc.state
Out[8]: 
Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda
Use FP16 precision: False

In [9]:

**Comment by sgugger** [comment]
> I did not launch the script, as this is not a must

It is if you want to use more than one GPU, using `python script.py` will only launch one process, you have to use `accelerate launch` or `python -m torch.distributed.launch` to use all your GPUs.

**Comment by world2vec** [comment]
Thanks.
this statement is misleading
```
As you can see in this example, by adding 5-lines to any standard PyTorch training script you can now run on any kind of single or distributed node setting (single CPU, single GPU, multi-GPUs and TPUs) as well as with or without mixed precision (fp16).
```

**Comment by sgugger** [comment]
I don't see why, your script runs normally with python and the torch distributed launcher. Had you written your distributed script with DDP it would stop working with a python launch (unless you go out of your way to put tests everywhere).

**Comment by beyondguo** [comment]
> > I did not launch the script, as this is not a must
> 
> It is if you want to use more than one GPU, using `python script.py` will only launch one process, you have to use `accelerate launch` or `python -m torch.distributed.launch` to use all your GPUs.

Hi @sgugger , I have install `accelerate`,:
![image](https://user-images.githubusercontent.com/37113676/156889220-4a2c6da4-cf15-427f-bc31-459973b942ee.png)
but when I type `python -c "TODO write"` to check if Accelerate is properly installed, I got: 
```
  File "<string>", line 1
    TODO write
             ^
```

also when I type `accelerate config`, I got:
```
bash: accelerate: command not found
```

I don't know what is going wrong?

btw, I'm using the command terminal by Jupyter.

**Comment by sgugger** [comment]
`bash` is probably using a different Python from the one you installed `accelerate` in.

**Comment by cristian1980** [comment]
@beyondguo accelerate is located in /home/{USER}/.local/bin/
add the dir to your PATH **or** create a link:
`sudo ln -s /home/{USER}/.local/bin/accelerate /usr/bin/`
