### ISSUE TITLE
Reproducibility Issue with TorchDynamo

### ISSUE THREAD

**Issue by pratogab** [huggingface/accelerate#1979]
### System Info

```Shell
accelerate v0.22.0 torch v2.0
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

If I run the same code without torch dynamo, I can reproduce the results `set_seed(args.seed, device_specific=True)`, but then if I set:
```
dynamo_config:
  dynamo_backend: INDUCTOR
```
in the config, suddenly the results are never the same. I didn't set it up, but instead of posting my code here, I assume this could be tested with the examples in the accelerate repo. `complete_nlp_examply.py` has a `set_seed` call.

### Expected behavior

Results should be reproducible when using torch dynamo.

**Comment by SunMarc** [comment]
Hi @pratogab, are you able to reproduce the results when you are training your model without accelerate and with torch dynamo ?

**Comment by pratogab** [comment]
I tested this again and the results are reproducible now. It was probably just a mistake on my end. Sorry about that.
