### ISSUE TITLE
Examples for pipeline training for models such as GPT

### ISSUE THREAD

**Issue by mozizhao** [huggingface/accelerate#1986]
Hi,

I am new to the Accelerate framework, and after reading the docs I think megatron-lm is properly integrated into the Accelerate. However, I cannot find any example of training large language models using the pipeline paradigm and the existing language model training scripts are for data parallelism I think. Could anyone provide such training scripts to help clarify how to do it?

**Comment by SunMarc** [comment]
@pacman100

**Comment by pacman100** [comment]
Hello, currently the Megatron LM integration is highly experimental and not actively maintained.

**Comment by mozizhao** [comment]
> Hello, currently the Megatron LM integration is highly experimental and not actively maintained.

Hi, does it mean I cannot use pipeline or tensor parallelism in Accelerate?

**Comment by SunMarc** [comment]
Hi @mozizhao, you can use PP+TP with deepspeed that Accelerate supports.
