### ISSUE TITLE
I have 4 gpu A100, I can use accelerate launch to use 4 gpu for finetuning but when ever I use 3 gpu over 4 gpu, it has a bug as below

### ISSUE THREAD

**Issue by trannhatquy** [huggingface/accelerate#1993]
### System Info

```Shell
github
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

True

### Expected behavior

I have 4 gpu A100, I can use accelerate launch to use 4 gpu for finetuning but when ever I use 3 gpu over 4 gpu, it has a bug as below:
accelerate launch --multi_gpu --num_processes=3 --gpu_ids=1,2,3 --num_machines=1  train.py 

Error: Last error:
XML Import Channel : dev 0 not found.

**Comment by trannhatquy** [comment]
anyone have the same issues, any solutions ?

**Comment by SunMarc** [comment]
Hi @trannhatquy , can you share a minimal reproducer with your env config and the full traceback ?

**Comment by trannhatquy** [comment]
@SunMarc here is my code:
from peft import (
    LoraConfig,
    get_peft_model,
    get_peft_model_state_dict,
    prepare_model_for_int8_training,
    set_peft_model_state_dict,
)
from transformers import AutoTokenizer, AutoModelForCausalLM, TrainingArguments, Trainer
import torch
import json
from torch.utils.data import Dataset
from transformers import get_cosine_with_hard_restarts_schedule_with_warmup, AdamW
from transformers import Seq2SeqTrainer, TrainerCallback, TrainingArguments, TrainerState, TrainerControl
from transformers.trainer_utils import PREFIX_CHECKPOINT_DIR
try:
    from Sophia import SophiaG
except:
    from Sophia import SophiaG
from random import shuffle
import os
from tqdm import tqdm
import torch.distributed as dist
import datetime
from torch.nn.parallel import DistributedDataParallel as DDP
from accelerate import Accelerator

# dist.init_process_group(backend='nccl', timeout=datetime.timedelta(0, 10))
os.environ["WANDB_DISABLED"] = "true"
os.environ["TORCH_DISTRIBUTED_DEBUG"] = "INFO"
os.environ["NCCL_DEBUG"] = "INFO"
# os.environ["NCCL_DEBUG"] = "WARN"
# os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
# os.environ["NCCL_TRACE"] = "1"
os.environ["NCCL_IB_DISABLE"] = "1"
# os.environ["CUDA_VISIBLE_DEVICES"] = "1,2,3"
os.environ["NCCL_P2P_DISABLE"] = "1"
# os.environ["NCCL_SOCKET_IFNAME"] = "eth0"
# model_path = "NousResearch/Yarn-Llama-2-13b-128k"

model_path = "/home/azureuser/quytran/vi_llama2/full_model_ckpt/15_9_vi_llama2_128k_extend_vocab_no_pretraining_finetuning_crosslingual_fixed/checkpoint-14976"
tokenizer = AutoTokenizer.from_pretrained(
    "/home/azureuser/quytran/vi_llama2/merged_llama128k_hf_filtered"
)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"
print(len(tokenizer))
print(tokenizer)
print("Tokenizer loaded")

print(str(int(os.environ.get("LOCAL_RANK")) or 0))
# model = AutoModelForCausalLM.from_pretrained(model_path, torch_dtype=torch.bfloat16, device_map="cuda:0", use_cache=False, cache_dir="/home/azureuser/quytran/vi_llama2/cache", trust_remote_code=True, use_flash_attention=True)
model = AutoModelForCausalLM.from_pretrained(model_path, 
                                             torch_dtype=torch.bfloat16, 
                                             device_map={"": "cuda:" + str(int(os.environ.get("LOCAL_RANK")) or 0)}, 
                                            #  device_map = {"": "cuda"},
                                             use_cache=False, 
                                             cache_dir="/home/azureuser/quytran/vi_llama2/cache", 
                                             trust_remote_code=True, 
                                             use_flash_attention=True,
                                             )
setattr(model, 'model_parallel', True) 
setattr(model, 'is_parallelizable', True)
# accelerator = Accelerator()
# model = accelerator.prepare(model)
# model = model.to("cuda:" + str(int(os.environ.get("LOCAL_RANK") or 0)))
# model = model = DDP(model, device_ids=[(int(os.environ.get("LOCAL_RANK")))])
# model = AutoModelForCausalLM.from_pretrained(model_path, torch_dtype = torch.bfloat16, device_map = 'auto', use_cache=False, cache_dir = "/workspace/quytran/llama2_extend_vocab/cache", trust_remote_code = True)
model.config.pretraining_tp = 1
model.resize_token_embeddings(len(tokenizer))
print(model.config)
print("Model loaded")

with open("/home/azureuser/quytran/vi_llama2/instruction_data_filter_2048/all_train_data.json", "r") as f:
    train_data = json.load(f)
train_data = train_data[:10000]
print(f'len train data: {len(train_data)}')
print(train_data[0])
print("----------")

with open("/home/azureuser/quytran/vi_llama2/instruction_data_filter_2048/all_validation_data.json", "r") as f:
    validation_data = json.load(f)
print(f'len validation data: {len(validation_data)}')
print(validation_data[0])
print("----------")

# model.gradient_checkpointing_enable()
# print("Using gradient checkpointing")
print(model.is_gradient_checkpointing)
# model = prepare_model_for_int8_training(model)

# config = LoraConfig(
#     r=16,
#     lora_alpha=16,
#     target_modules=[
#         "q_proj",
#         "v_proj",
#         "k_proj",
#         "o_proj",
#         "gate_proj",
#         "down_proj",
#         "up_proj"
#     ],
#     lora_dropout=0.05,
#     bias="none",
#     task_type="CAUSAL_LM",
# )
config = LoraConfig(
    r=8,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    modules_to_save=[
        "embed_tokens",
        "lm_head"
    ],
    task_type="CAUSAL_LM",
)

model = get_peft_model(model, config)
print("Peft model loaded")
model.print_trainable_parameters()

def batch_tokenize(arr, max_length = 2048):
    print("tokenizing")
    pre_tokenize = tokenizer(arr[:512], max_length = max_length, padding = "max_length", truncation = True)
    for i in tqdm(range(512, len(arr), 512)):
        temp = tokenizer(arr[i:i+512], max_length = max_length, padding = "max_length", truncation = True)
        pre_tokenize["input_ids"] += temp["input_ids"]
        pre_tokenize["attention_mask"] += temp["attention_mask"]
    return pre_tokenize

class dataset(Dataset):
    def __init__(self, source):
        self.source = source

    def __len__(self):
        return len(self.source["input_ids"])

    def __getitem__(self, idx):
        input_ids = self.source["input_ids"][idx]
        attention_mask = self.source["attention_mask"][idx]
        label = self.source["input_ids"][idx]
        outp = {}
        outp["input_ids"] = torch.tensor(input_ids, dtype=torch.long)
        outp["attention_mask"] = torch.tensor(attention_mask, dtype=torch.long)
        outp["labels"] = torch.tensor(label, dtype=torch.long)
        return outp


train_tokenized = batch_tokenize(
    train_data, max_length=2048)
eval_tokenized = batch_tokenize(
    validation_data, max_length=2048)

eval_dataset = dataset(eval_tokenized)
train_dataset = dataset(train_tokenized)


class SavePeftModelCallback(TrainerCallback):
    def on_save(
        self,
        args: TrainingArguments,
        state: TrainerState,
        control: TrainerControl,
        **kwargs,
    ):
        checkpoint_folder = os.path.join(
            args.output_dir, f"{PREFIX_CHECKPOINT_DIR}-{state.global_step}")

        peft_model_path = os.path.join(checkpoint_folder, "adapter_model")
        kwargs["model"].save_pretrained(peft_model_path)

        pytorch_model_path = os.path.join(
            checkpoint_folder, "pytorch_model.bin")
        if os.path.exists(pytorch_model_path):
            os.remove(pytorch_model_path)
        return control


optimizer = SophiaG(params=model.parameters(), lr=8e-5)
print("Using SophiaG")
# optimizer = AdamW(params  = model.parameters(), lr = 8e-5)
scheduler = get_cosine_with_hard_restarts_schedule_with_warmup(
    optimizer, num_training_steps=2*len(train_data)//48, num_warmup_steps=100, num_cycles=4)
print("Using scheduler")

training_args = TrainingArguments(
    output_dir="/home/azureuser/quytran/vi_llama2/ckpt/20_9_vi_llama2_128k_extend_vocab_no_pretraining_finetuning_crosslingual_fixed",
    evaluation_strategy="steps",
    learning_rate=8e-5,
    num_train_epochs=2,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    weight_decay=0.01,
    save_total_limit=4,
    load_best_model_at_end=True,
    save_strategy="steps",
    eval_steps=624,
    # report_to = "wandb",
    fp16=False,
    bf16=True,
    save_steps=624,
    gradient_accumulation_steps=8,
    warmup_steps=100,
    logging_steps=15,
    # ddp_find_unused_parameters = False
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    callbacks=[SavePeftModelCallback],
    optimizers=[optimizer, scheduler]

)

trainer.train()

**Comment by trannhatquy** [comment]
@SunMarc here is the log:
a100-4x-machines-23fsd-2-dev:531895:531895 [0] NCCL INFO Bootstrap : Using eth0:10.9.0.4<0>
a100-4x-machines-23fsd-2-dev:531895:531895 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
a100-4x-machines-23fsd-2-dev:531895:531895 [0] NCCL INFO cudaDriverVersion 12020
NCCL version 2.14.3+cuda11.7
a100-4x-machines-23fsd-2-dev:531897:531897 [2] NCCL INFO cudaDriverVersion 12020
a100-4x-machines-23fsd-2-dev:531896:531896 [1] NCCL INFO cudaDriverVersion 12020
a100-4x-machines-23fsd-2-dev:531895:532459 [0] NCCL INFO NCCL_IB_DISABLE set by environment to 1.
a100-4x-machines-23fsd-2-dev:531895:532459 [0] NCCL INFO NET/Socket : Using [0]eth0:10.9.0.4<0> [1]br-ce64497c3b44:172.18.0.1<0>
a100-4x-machines-23fsd-2-dev:531895:532459 [0] NCCL INFO Using network Socket
a100-4x-machines-23fsd-2-dev:531897:531897 [2] NCCL INFO Bootstrap : Using eth0:10.9.0.4<0>
a100-4x-machines-23fsd-2-dev:531897:531897 [2] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
a100-4x-machines-23fsd-2-dev:531897:532460 [2] NCCL INFO NCCL_IB_DISABLE set by environment to 1.
a100-4x-machines-23fsd-2-dev:531897:532460 [2] NCCL INFO NET/Socket : Using [0]eth0:10.9.0.4<0> [1]br-ce64497c3b44:172.18.0.1<0>
a100-4x-machines-23fsd-2-dev:531897:532460 [2] NCCL INFO Using network Socket
a100-4x-machines-23fsd-2-dev:531896:531896 [1] NCCL INFO Bootstrap : Using eth0:10.9.0.4<0>
a100-4x-machines-23fsd-2-dev:531896:531896 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
a100-4x-machines-23fsd-2-dev:531896:532461 [1] NCCL INFO NCCL_IB_DISABLE set by environment to 1.
a100-4x-machines-23fsd-2-dev:531896:532461 [1] NCCL INFO NET/Socket : Using [0]eth0:10.9.0.4<0> [1]br-ce64497c3b44:172.18.0.1<0>
a100-4x-machines-23fsd-2-dev:531896:532461 [1] NCCL INFO Using network Socket
a100-4x-machines-23fsd-2-dev:531895:532459 [0] NCCL INFO NCCL_P2P_LEVEL set by environment to LOC
a100-4x-machines-23fsd-2-dev:531896:532461 [1] NCCL INFO NCCL_P2P_LEVEL set by environment to LOC
a100-4x-machines-23fsd-2-dev:531897:532460 [2] NCCL INFO NCCL_P2P_LEVEL set by environment to LOC
a100-4x-machines-23fsd-2-dev:531895:532459 [0] NCCL INFO Setting affinity for GPU 0 to ffffff
a100-4x-machines-23fsd-2-dev:531896:532461 [1] NCCL INFO Setting affinity for GPU 1 to ffff,ff000000
a100-4x-machines-23fsd-2-dev:531897:532460 [2] NCCL INFO Setting affinity for GPU 2 to ff,ffff0000,00000000

a100-4x-machines-23fsd-2-dev:531895:532459 [0] graph/search.cc:625 NCCL WARN XML Import Channel : dev 3 not found.
a100-4x-machines-23fsd-2-dev:531895:532459 [0] NCCL INFO graph/search.cc:655 -> 2
a100-4x-machines-23fsd-2-dev:531895:532459 [0] NCCL INFO graph/search.cc:662 -> 2
a100-4x-machines-23fsd-2-dev:531895:532459 [0] NCCL INFO graph/search.cc:755 -> 2
a100-4x-machines-23fsd-2-dev:531895:532459 [0] NCCL INFO init.cc:565 -> 2
a100-4x-machines-23fsd-2-dev:531895:532459 [0] NCCL INFO init.cc:1089 -> 2
a100-4x-machines-23fsd-2-dev:531895:532459 [0] NCCL INFO group.cc:64 -> 2 [Async thread]
a100-4x-machines-23fsd-2-dev:531895:531895 [0] NCCL INFO group.cc:421 -> 3
a100-4x-machines-23fsd-2-dev:531895:531895 [0] NCCL INFO group.cc:106 -> 3

a100-4x-machines-23fsd-2-dev:531897:532460 [2] graph/search.cc:625 NCCL WARN XML Import Channel : dev 3 not found.
a100-4x-machines-23fsd-2-dev:531897:532460 [2] NCCL INFO graph/search.cc:655 -> 2
a100-4x-machines-23fsd-2-dev:531897:532460 [2] NCCL INFO graph/search.cc:662 -> 2
a100-4x-machines-23fsd-2-dev:531897:532460 [2] NCCL INFO graph/search.cc:755 -> 2
a100-4x-machines-23fsd-2-dev:531897:532460 [2] NCCL INFO init.cc:565 -> 2
a100-4x-machines-23fsd-2-dev:531897:532460 [2] NCCL INFO init.cc:1089 -> 2
a100-4x-machines-23fsd-2-dev:531897:532460 [2] NCCL INFO group.cc:64 -> 2 [Async thread]
a100-4x-machines-23fsd-2-dev:531897:531897 [2] NCCL INFO group.cc:421 -> 3
a100-4x-machines-23fsd-2-dev:531897:531897 [2] NCCL INFO group.cc:106 -> 3

a100-4x-machines-23fsd-2-dev:531896:532461 [1] graph/search.cc:625 NCCL WARN XML Import Channel : dev 3 not found.
a100-4x-machines-23fsd-2-dev:531896:532461 [1] NCCL INFO graph/search.cc:655 -> 2
a100-4x-machines-23fsd-2-dev:531896:532461 [1] NCCL INFO graph/search.cc:662 -> 2
a100-4x-machines-23fsd-2-dev:531896:532461 [1] NCCL INFO graph/search.cc:755 -> 2
a100-4x-machines-23fsd-2-dev:531896:532461 [1] NCCL INFO init.cc:565 -> 2
a100-4x-machines-23fsd-2-dev:531896:532461 [1] NCCL INFO init.cc:1089 -> 2
a100-4x-machines-23fsd-2-dev:531896:532461 [1] NCCL INFO group.cc:64 -> 2 [Async thread]
a100-4x-machines-23fsd-2-dev:531896:531896 [1] NCCL INFO group.cc:421 -> 3
a100-4x-machines-23fsd-2-dev:531896:531896 [1] NCCL INFO group.cc:106 -> 3
a100-4x-machines-23fsd-2-dev:531895:531895 [0] NCCL INFO comm 0x5645a4963d50 rank 0 nranks 3 cudaDev 0 busId 100000 - Abort COMPLETE
Traceback (most recent call last):
  File "/home/azureuser/quytran/vi_llama2/train.py", line 219, in <module>
    a100-4x-machines-23fsd-2-dev:531897:531897 [2] NCCL INFO comm 0x5603f4802150 rank 2 nranks 3 cudaDev 2 busId 300000 - Abort COMPLETE
trainer.train()
  File "/home/azureuser/quytran/vi_llama2/villama2_venv/lib/python3.10/site-packages/transformers/trainer.py", line 1575, in train
a100-4x-machines-23fsd-2-dev:531896:531896 [1] NCCL INFO comm 0x55576f3e5500 rank 1 nranks 3 cudaDev 1 busId 200000 - Abort COMPLETE
    return inner_training_loop(
  File "/home/azureuser/quytran/vi_llama2/villama2_venv/lib/python3.10/site-packages/transformers/trainer.py", line 1713, in _inner_training_loop
Traceback (most recent call last):
  File "/home/azureuser/quytran/vi_llama2/train.py", line 219, in <module>
    model, self.optimizer = self.accelerator.prepare(self.model, self.optimizer)
  File "/home/azureuser/quytran/vi_llama2/villama2_venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1284, in prepare
Traceback (most recent call last):
    trainer.train()
  File "/home/azureuser/quytran/vi_llama2/train.py", line 219, in <module>
  File "/home/azureuser/quytran/vi_llama2/villama2_venv/lib/python3.10/site-packages/transformers/trainer.py", line 1575, in train
    result = tuple(
  File "/home/azureuser/quytran/vi_llama2/villama2_venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1285, in <genexpr>
    trainer.train()
  File "/home/azureuser/quytran/vi_llama2/villama2_venv/lib/python3.10/site-packages/transformers/trainer.py", line 1575, in train
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
  File "/home/azureuser/quytran/vi_llama2/villama2_venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1090, in _prepare_one
    return inner_training_loop(
  File "/home/azureuser/quytran/vi_llama2/villama2_venv/lib/python3.10/site-packages/transformers/trainer.py", line 1713, in _inner_training_loop
    return self.prepare_model(obj, device_placement=device_placement)
  File "/home/azureuser/quytran/vi_llama2/villama2_venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1429, in prepare_model
        model, self.optimizer = self.accelerator.prepare(self.model, self.optimizer)model = torch.nn.parallel.DistributedDataParallel(

      File "/home/azureuser/quytran/vi_llama2/villama2_venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1284, in prepare
return inner_training_loop(  File "/home/azureuser/quytran/vi_llama2/villama2_venv/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 674, in __init__

  File "/home/azureuser/quytran/vi_llama2/villama2_venv/lib/python3.10/site-packages/transformers/trainer.py", line 1713, in _inner_training_loop
    _verify_param_shape_across_processes(self.process_group, parameters)
  File "/home/azureuser/quytran/vi_llama2/villama2_venv/lib/python3.10/site-packages/torch/distributed/utils.py", line 118, in _verify_param_shape_across_processes
    return dist._verify_params_across_processes(process_group, tensors, logger)
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1275, internal error, NCCL version 2.14.3
ncclInternalError: Internal check failed.
Last error:
XML Import Channel : dev 3 not found.
    result = tuple(
  File "/home/azureuser/quytran/vi_llama2/villama2_venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1285, in <genexpr>
    model, self.optimizer = self.accelerator.prepare(self.model, self.optimizer)
  File "/home/azureuser/quytran/vi_llama2/villama2_venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1284, in prepare
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
  File "/home/azureuser/quytran/vi_llama2/villama2_venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1090, in _prepare_one
    result = tuple(
  File "/home/azureuser/quytran/vi_llama2/villama2_venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1285, in <genexpr>
    return self.prepare_model(obj, device_placement=device_placement)
  File "/home/azureuser/quytran/vi_llama2/villama2_venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1429, in prepare_model
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
  File "/home/azureuser/quytran/vi_llama2/villama2_venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1090, in _prepare_one
    model = torch.nn.parallel.DistributedDataParallel(
  File "/home/azureuser/quytran/vi_llama2/villama2_venv/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 674, in __init__
    return self.prepare_model(obj, device_placement=device_placement)
  File "/home/azureuser/quytran/vi_llama2/villama2_venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 1429, in prepare_model
    _verify_param_shape_across_processes(self.process_group, parameters)
  File "/home/azureuser/quytran/vi_llama2/villama2_venv/lib/python3.10/site-packages/torch/distributed/utils.py", line 118, in _verify_param_shape_across_processes
    return dist._verify_params_across_processes(process_group, tensors, logger)
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1275, internal error, NCCL version 2.14.3
ncclInternalError: Internal check failed.
Last error:
XML Import Channel : dev 3 not found.
    model = torch.nn.parallel.DistributedDataParallel(
  File "/home/azureuser/quytran/vi_llama2/villama2_venv/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 674, in __init__
    _verify_param_shape_across_processes(self.process_group, parameters)
  File "/home/azureuser/quytran/vi_llama2/villama2_venv/lib/python3.10/site-packages/torch/distributed/utils.py", line 118, in _verify_param_shape_across_processes
    return dist._verify_params_across_processes(process_group, tensors, logger)
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1275, internal error, NCCL version 2.14.3
ncclInternalError: Internal check failed.
Last error:
XML Import Channel : dev 3 not found.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 531895) of binary: /home/azureuser/quytran/vi_llama2/villama2_venv/bin/python3
Traceback (most recent call last):
  File "/home/azureuser/quytran/vi_llama2/villama2_venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/azureuser/quytran/vi_llama2/villama2_venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/azureuser/quytran/vi_llama2/villama2_venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 977, in launch_command
    multi_gpu_launcher(args)
  File "/home/azureuser/quytran/vi_llama2/villama2_venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 646, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/azureuser/quytran/vi_llama2/villama2_venv/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/azureuser/quytran/vi_llama2/villama2_venv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/azureuser/quytran/vi_llama2/villama2_venv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-09-21_01:11:17
  host      : a100-4x-machines-23fsd-2-dev.internal.cloudapp.net
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 531896)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2023-09-21_01:11:17
  host      : a100-4x-machines-23fsd-2-dev.internal.cloudapp.net
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 531897)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-09-21_01:11:17
  host      : a100-4x-machines-23fsd-2-dev.internal.cloudapp.net
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 531895)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by trannhatquy** [comment]
@SunMarc  @pacman100 I want to use data parallel on 3 gpus over 4 gpus in my machine, any solutions

**Comment by aohan237** [comment]
if just need 3 gpu of 4, you can just 

export CUDA_VISIBLE_DEVICES=0,1,2

then launch. 

it should work

**Comment by trannhatquy** [comment]
@aohan237 I do exactly what you do, but this give me the above error

**Comment by aohan237** [comment]
> @aohan237 I do exactly what you do, but this give me the above error

--multi_gpu --num_processes=3 --gpu_ids=1,2,3 --num_machines=1
delete these args

**Comment by trannhatquy** [comment]
yeah I delete these args, still this error
