### ISSUE TITLE
Is it feasible to write "accelerate launch" CLI into python code?

### ISSUE THREAD

**Issue by feiyangsuo** [huggingface/accelerate#1996]
I have a circumstance that I need to execute code in a remote platform which only accept .py file (and runtime parameters) as input. While I'm trying to deploy a multi-gpu training, I can't integrate ``accelerate launch`` ahead of the executing command (like running ``accelerate launch my_code.py``, cuz I have nowhere to write it).
I wonder if there's a way to put ``accelerate launch`` into the python code, expecting something like:
```
impmort accelerate
accelerate.config(multi_gpu=True, num_processes=2)
accelerate.launch(my_training_function)
```

**Comment by BenjaminBossan** [comment]
When calling `accelerate launch`, this is basically what happens inside of Python:

https://github.com/huggingface/accelerate/blob/80da9cfb09bb3cc9f1b385cb55d6b90d025a5fd9/src/accelerate/commands/launch.py#L963-L996

You could take inspiration from that, but it depends on your exact circumstances how to correctly parse the arguments.

**Comment by muellerzr** [comment]
Or more succinctly:

```python
from accelerate.cli.launch import launch_command_parser, launch_command

args = launch_command_parser().parse_args(“num_processes=1”, …)
launch_command(args)
```
