### ISSUE TITLE
tensorboard tracker overwrites my saved images during some validation step

### ISSUE THREAD

**Issue by aihao2000** [huggingface/accelerate#1997]
### System Info

```Shell
- `Accelerate` version: 0.23.0
- Platform: Linux-5.4.0-117-generic-x86_64-with-glibc2.31
- Python version: 3.10.12
- Numpy version: 1.25.2
- PyTorch version (GPU?): 2.0.1 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 251.56 GB
- GPU type: NVIDIA A100-PCIE-40GB
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: fp16
        - use_cpu: False
        - debug: False
        - num_processes: 4
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: all
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

My code is written learning https://github.com/huggingface/diffusers/blob/main/examples/controlnet/train_controlnet.py.

```python
for tracker in accelerator.trackers:
        if tracker.name == "tensorboard":
            for log in image_logs:
                images = log["images"]
                validation_prompt = log["validation_prompt"]
                validation_image = log["validation_image"]

                formatted_images = []

                formatted_images.append(np.asarray(validation_image))

                for image in images:
                    formatted_images.append(np.asarray(image))

                formatted_images = np.stack(formatted_images)

                tracker.writer.add_images(validation_prompt, formatted_images, step, dataformats="NHWC")
```

### Expected behavior

I found that tensorboard didn't save all the output images, it was sometimes overwritten with new validation images. For example, at 1000 steps the validation image is visible in the browser, but at 2000 steps the result of 1000 steps disappears and the result of 2000 steps is displayed. The number of validation steps I can see now is 2000,3000,4000,12000,21000,25000,33000,34000,38000,43000. There seems to be no pattern, and I'm very confused  about it. Is this a bug?

**Comment by BenjaminBossan** [comment]
This does seem very strange. However, I'm not sure if this relates to accelerate. Since you use `tracker.writer.add_images`, you're basically just using the standard `SummaryWriter` object directly, without any involvement from accelerate, so it's unlikely that accelerate is responsible for the shown behavior. You could try to use the tensorboard `SummaryWriter` directly, without the accelerate wrapper, to check if the same error occurs.
