### ISSUE TITLE
`gather_for_metrics` does not respect dataloader `drop_last=True` setting

### ISSUE THREAD

**Issue by xmagpie** [huggingface/accelerate#2007]
### System Info

```Shell
- `Accelerate` version: 0.23.0
- Platform: Linux-5.15.0-76-generic-x86_64-with-glibc2.35
- Python version: 3.9.16
- Numpy version: 1.24.2
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- `Accelerate` default config:
        Not found
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

This is the minimal snippet adapted directly from the docstring:
```python
import torch
from accelerate import Accelerator

accelerator = Accelerator()
dataloader = torch.utils.data.DataLoader(range(9), batch_size=5, drop_last=True)
dataloader = accelerator.prepare(dataloader)

batch = next(iter(dataloader))
gathered_items = accelerator.gather_for_metrics(batch)

print(gathered_items)
```

This yields `tensor([0, 1, 2, 3], device='cuda:0')`, while the expected is `tensor([0, 1, 2, 3, 4], device='cuda:0')`.

The behavior is more visually erroneous in the following case

```python
dataloader = torch.utils.data.DataLoader(range(11), batch_size=5, drop_last=True)
dataloader = accelerator.prepare(dataloader)

iterator = iter(dataloader)
next(iterator) # Skip first batch tensor([0, 1, 2, 3, 4], device='cuda:0')
batch = next(iterator)
gathered_items = accelerator.gather_for_metrics(batch)
print(batch, gathered_items)
```

yields `tensor([5, 6, 7, 8, 9], device='cuda:0'), tensor([5], device='cuda:0')`.

The error seems to be related to this [check](https://github.com/huggingface/accelerate/blob/80da9cfb09bb3cc9f1b385cb55d6b90d025a5fd9/src/accelerate/accelerator.py#L2228), which does not correctly handle drop_last case, which results in the incorrect usage of remainder.

Also I have noticed that `drop_last` is not correctly initialized on prepared dataloader, in my case `DataLoaderShard`, e.g. it shows `False`. Dunno whether this is intended or not.

### Expected behavior

I expect `gathered_items` to be equal to batch.

**Comment by huangjy-pku** [comment]
I also encountered this issue. I found the reason lies in [https://github.com/huggingface/accelerate/blob/main/src/accelerate/accelerator.py#L2228](https://github.com/huggingface/accelerate/blob/main/src/accelerate/accelerator.py#L2228), where the `Accelerator.gradient_state.remainder` is mistakenly non-zero even `drop_last=True`. And `Accelerator.gradient_state.remainder` equals the batch size of the last batch for `drop_last=False`.
