### ISSUE TITLE
Multi-Node Model Parallelism 

### ISSUE THREAD

**Issue by ishaansehgal99** [huggingface/accelerate#2011]
### Info

I am trying to run Falcon-40b across two nodes: each an A100-80GB GPU (Falcon-40gb requires ~90gb so it OOM's on one node) 

I use the exact example script here: https://huggingface.co/tiiuae/falcon-40b-instruct

I want to run the model across these two nodes. However accelerate does not allow this? Or am I mistaken? In order to use --multi-gpu I have to have num_processes >= 2? And so accelerate will try launching the entire model on each process on each node. This just OOMs on each node! This is not what I want.  

I run this command on each node:
accelerate launch --multi_gpu --num_machines 2 --gpu_ids 0,1,2,3 --same_network --machine_rank 0or1 --main_process_ip xx.xxx.x.xxx --main_process_port 80 --num_processes 2 inference.py

**If accelerate does not have this functionality already, how can I achieve true model parallelism. How can I parallelize the model across the two nodes on the same network that I have? DeepSpeed, Megatron-LM, or FSDP? Which one of these is the right tool/easiest to use? Does anyone have an example? Many thanks - just want this running :)**

### Information

- [X] The official example scripts
- [x] My own modified scripts

### Tasks

- [x] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [x] My own task or dataset (give details below)

### Reproduction

```
# !pip install -U bitsandbytes
# !pip install -U git+https://github.com/huggingface/transformers.git
# !pip install -U git+https://github.com/huggingface/accelerate.git

from transformers import AutoTokenizer, AutoModelForCausalLM
from accelerate import Accelerator
import transformers
import torch


# Initialize the accelerator
accelerator = Accelerator()
print(accelerator.device)

model_id = "tiiuae/falcon-40b-instruct"

tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    device_map="auto",
    torch_dtype=torch.bfloat16,
    trust_remote_code=True,
)

pipeline = transformers.pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    torch_dtype=torch.bfloat16,
    trust_remote_code=True,
    device_map="auto",
)

sequences = pipeline(
   "Girafatron is obsessed with giraffes, the most glorious animal on the face of this Earth. Giraftron believes all other animals are irrelevant when compared to the glorious majesty of the giraffe.\nDaniel: Hello, Girafatron!\nGirafatron:",
    max_length=200,
    do_sample=True,
    top_k=10,
    num_return_sequences=1,
    eos_token_id=tokenizer.eos_token_id,
)
for seq in sequences:
    print(f"Result: {seq['generated_text']}")
```
1. Use the script above
2. Run on each node: 
accelerate launch --multi_gpu --num_machines 2 --gpu_ids 0,1,2,3 --same_network --machine_rank 0or1 --main_process_ip xx.xxx.x.xxx --main_process_port 80 --num_processes 2 inference.py
3. Observe OOM on each node

### Expected behavior

Can run process that is model parallelized across two GPUs on separate nodes.

**Comment by SunMarc** [comment]
Hi @ishaansehgal99 , what is your use case ? If it is for training, people prefer to use FSDP as it is easier to use. However most ML researchers uses Deepspeed to train SOTA models. But it is harder to use. If you want to do multi-nodes multi-gpu inference, we don't have an api that does this at the moment. I would suggest you looking into FasterTransformers and deepspeed for inference.

**Comment by chuyuanli** [comment]
Hi, I am experiencing the same issue as @ishaansehgal99 when I try to fine-tune a 13b model. I am wondering if this issue got any updates so far? Does accelerate now support multi-node model // ? Thanks.

**Comment by averdones** [comment]
I'm interested to know the status too.

Does Hugging Face currently support multi-node inference and/or training?
