### ISSUE TITLE
training_dataloader.batch_size become unaccessible after accelerator.prepare()

### ISSUE THREAD

**Issue by HowLeeHi** [huggingface/accelerate#2012]
After `training_dataloader = accelerator.prepare(training_dataloader)`, It seems training_dataloader.batch_size become unaccessible and yield `None`.

How can I modify the following code to make it work:

```
num_iter = int(len(training_dataloader.dataset) // training_dataloader.batch_size)
c_loader_iter = training_dataloader.__iter__()
for c_iter in tqdm(range(num_iter)):
       ...
```

**Comment by BenjaminBossan** [comment]
Can you store the batch size in a variable _before_ sending the data loader to `prepare`?

**Comment by HowLeeHi** [comment]
> Can you store the batch size in a variable _before_ sending the data loader to `prepare`?

I think the answer is "yes". 
But I really wonder why this attribute becomes inaccessible when accelerator.prepare(training_dataloader) actually returns torch.utils.data.dataloader.DataLoader. As sometimes batch_size for each GPU would change when some parameters change, e.g., split_batches, I think the codes should be more robust if we can read it from dataloader.

**Comment by muellerzr** [comment]
@HowLeeHi can you tell us the type of dataloader returned? (`type(training_dataloader)`). We have methods for doing so, but we need to know just which one to tell you further
