### ISSUE TITLE
Error on save_steps using FSDP

### ISSUE THREAD

**Issue by ghost** [huggingface/accelerate#2013]
### System Info

```Shell
I am currently using the FSDP (Fully Sharded Data Parallelism) approach with the Llama 2 70B model. The training process has begun, but I encounter an error when attempting to save the checkpoint at each save_step. I have set the save_step as 50.

System: 1 Node with 2 A100 80 GB GPU
```

### Information

- [ ] The official example scripts
- [x] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [x] My own task or dataset (give details below)

### Reproduction

Here are the supporting screenshots

![MicrosoftTeams-image (1)](https://github.com/huggingface/accelerate/assets/105478351/20342cf0-7863-42f0-a61b-bd125dd06f5a)

![MicrosoftTeams-image (2)](https://github.com/huggingface/accelerate/assets/105478351/a4aeb3cf-30d9-4742-a96c-4d8273cece90)

### Expected behavior

Checkpoint will be save.

**Comment by pacman100** [comment]
This seems to be an error with PyTorch. Could you please raise an issue with them?
