### ISSUE TITLE
A demo of how to perform multi-GPU parallel inference for transformer LLM is needed

### ISSUE THREAD

**Issue by KexinFeng** [huggingface/accelerate#2018]
In the current demo: "[Distributed inference using Accelerate](https://huggingface.co/docs/accelerate/usage_guides/distributed_inference )" , it is still not clear enough to know how to perform multi-GPU parallel inference for transformer LLM. This gap in the demo has hindered not just me, but also many people in adopting your solution: https://www.reddit.com/r/LocalLLaMA/comments/15rlqsb/how_to_perform_multigpu_parallel_inference_for/
Also in the reply, other frameworks have already started competing for this specific use case. 

Could you provide the demo for this use case?

**Comment by SunMarc** [comment]
Hi @KexinFeng , please let us know why it is not clear enough. Are you not able to run the code ?

**Comment by baolixiong** [comment]
Hi @KexinFeng， I have encountered this problem. Have you solved it?

**Comment by geronimi73** [comment]
hey, just stumbled upon this issue.

Inference on multiple GPUs works for me with the script below. 

However the **performance** is puzzling me a bit (see numbers below). Basically, in this llama2-7b setup, with 3 GPUs i get 60t/s, but with 2 GPUs basically the same as with 1 GPU (40t/s). 
I understand that with distributed _training_ there is a huge overhead slowing things down, but is there also a lot of additional communication with distributed _inference_? Is this expected?

```python
model_path="models/llama2-7b"
model = AutoModelForCausalLM.from_pretrained(
    model_path,    
    device_map="auto",
    torch_dtype=torch.bfloat16,
)
tokenizer = AutoTokenizer.from_pretrained(model_path)   

prompts= [ .. ]

accelerator.wait_for_everyone()
start=time.time()

with accelerator.split_between_processes(prompts_all) as prompts:
    results=dict(outputs=[], num_tokens=0)

    for prompt in prompts:
        prompt_tokenized=tokenizer(prompt, return_tensors="pt").to("cuda")
        output_tokenized = model.generate(**prompt_tokenized, max_new_tokens=50)[0]

        # remove prompt from output 
        output_tokenized=output_tokenized[len(prompt_tokenized["input_ids"][0]):]

        # store outputs and number of tokens in result{}
        results["outputs"].append( tokenizer.decode(output_tokenized) )
        results["num_tokens"] += len(output_tokenized)

    timediff=time.time()-start
    print("GPU {}: {} prompts received, generated {} tokens in {} seconds, {} t/s".format(
        accelerator.process_index,
        len(prompts),
        results["num_tokens"],
        timediff,
        results["num_tokens"]//timediff,
        ))
    results=[ results ] 

results_gathered=gather_object(results)

if accelerator.is_main_process:
    timediff=time.time()-start
    num_tokens=sum([r["num_tokens"] for r in results_gathered ])

    print(f"tokens/sec: {num_tokens//timediff}, total tokens {num_tokens}, time {timediff}")
```

output w/ 1 GPU
```
GPU 0: 65 prompts received, generated 3250 tokens in 79.53455805778503 seconds, 40.0 t/s
tokens/sec: 40.0, total tokens 3250, time 79.5346269607544
```

output w/ 2 GPUs
```
GPU 1: 32 prompts received, generated 1600 tokens in 72.92330050468445 seconds, 21.0 t/s
GPU 0: 33 prompts received, generated 1650 tokens in 77.58914303779602 seconds, 21.0 t/s
tokens/sec: 41.0, total tokens 3250, time 77.59003257751465
```

output w/ 3 GPUs
```
GPU 2: 21 prompts received, generated 1050 tokens in 48.31575059890747 seconds, 21.0 t/s
GPU 0: 22 prompts received, generated 1100 tokens in 51.92913627624512 seconds, 21.0 t/s
GPU 1: 22 prompts received, generated 1100 tokens in 52.516985177993774 seconds, 20.0 t/s
tokens/sec: 61.0, total tokens 3250, time 52.51792597770691
```

@muellerzr

**Comment by muellerzr** [comment]
@KexinFeng haven't fully tested this yet, but if you're using `device_map="auto"` it's worth investigating how the model winds up being mapped. If it's sharded across multiple GPUs and it's pulling those back and forth, it wouldn't surprise me if constantly moving between devices on the same weight locations in memory leads to some throughput issues.

**Comment by geronimi73** [comment]
> if you're using `device_map="auto"`

holy sh*t, didn't realize I was doing that 🤯 yes, you're right, the model of each process was sharded across all the GPUs. thank you!

changed it to ```device_map={"": accelerator.process_index}```. Now t/s are increasing linearly up to 3 GPUs but then saturates.

```
1 GPU: 44t/s
2 GPUs: 88tt/s (avg. 44t/s/GPU)
3 GPUs: 128t/s (avg. 44t/s/GPU)
4 GPUs: 137t/s (avg. 34t/s/GPU)
5 GPUs: 119t/s (avg. 23t/s/GPU)
```

I assume it's some additional communication needed the more GPUs are working, right? 
any idea what this might be or how to make it faster?

**Comment by muellerzr** [comment]
@KexinFeng we're looking at using some pipeline parallelism to speed things up a bit, stay tuned :)

**Comment by SMAntony** [comment]
@geronimi73 Hi, I am working on a webserver and would like to implement your solution. But as I am new to LLM landscape I am finding it very hard. Can you help me out? Is there anyway to contact you?

**Comment by geronimi73** [comment]
> @geronimi73 Hi, I am working on a webserver and would like to implement your solution. I am new to LLM landscape, can you help me out? Is there anyway to contact you?

DM me on twitter https://twitter.com/Geronimo_AI

**Comment by chujiezheng** [comment]
> @KexinFeng we're looking at using some pipeline parallelism to speed things up a bit, stay tuned :)

@muellerzr Hi, is there any progress on inference speedup? :)

**Comment by muellerzr** [comment]
Yes! See here: https://huggingface.co/docs/accelerate/usage_guides/distributed_inference (see the bit on pippy)

**Comment by chujiezheng** [comment]
@muellerzr Thanks for your information!

BTW, I wonder if you have any idea to combine `accelerate.split_between_processes` with `vllm` (designate a specific gpu in each process). You may see my issue raised in the `vllm` repo (https://github.com/vllm-project/vllm/issues/3088)

**Comment by muellerzr** [comment]
Can you not just load a model onto each GPU (this involves nothing special and just follows the normal inference tutorial) using vllm and perform inference on it usually? (I'm not familiar with VLLM)

**Comment by chujiezheng** [comment]
Sure, it works. I resort to `vllm` mainly for a speed/throughput boost. Naive `accelerate.split_between_processes` + `model.generate` somewhat suffers from low efficiency.

**Comment by SefaZeng** [comment]
> Sure, it works. I resort to `vllm` mainly for a speed/throughput boost. Naive `accelerate.split_between_processes` + `model.generate` somewhat suffers from low efficiency.

Hi @chujiezheng , do you solve the low-efficiency issue with `accelerate.split_between_processes` + `model.generate`? I meet the same problem: using 8 GPUs is only 2.2x faster than using 1 GPU.

**Comment by geronimi73** [comment]
> using 8 GPUs is only 2.2x faster than using 1 GPU.

weird. check out this notebook: https://github.com/geronimi73/accelerate_tricks/blob/main/inference_batched.py

![1_SqpuU50pI5IJ7cGYJiEA5Q](https://github.com/huggingface/accelerate/assets/141400217/cb036b55-45c2-40f9-8381-02b63a0e894b)

**Comment by SefaZeng** [comment]
> > using 8 GPUs is only 2.2x faster than using 1 GPU.
> 
> weird. check out this notebook: https://github.com/geronimi73/accelerate_tricks/blob/main/inference_batched.py
> 
> ![1_SqpuU50pI5IJ7cGYJiEA5Q](https://private-user-images.githubusercontent.com/141400217/312321030-cb036b55-45c2-40f9-8381-02b63a0e894b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMDgwMzMsIm5iZiI6MTcxMDMwNzczMywicGF0aCI6Ii8xNDE0MDAyMTcvMzEyMzIxMDMwLWNiMDM2YjU1LTQ1YzItNDBmOS04MzgxLTAyYjYzYTBlODk0Yi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QwNTI4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NzBkMWVhZTFhNWJkYzNkMTQwMmYwN2UwNTA2OGYzNDIxNjkwOWM2Y2VkOTFiMjE5ZTk2MjM1MmRlYWMzMDNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.twegdRZcVi1Il514VZpR11F4sLtf0IU4rEPuupAsCRw)

Thank you so much. I found that the reason is that I did not use batch.

**Comment by sparsh35** [comment]
Hi! Can it be also done using notebook_launcher() , passing the batched inference in notebook_launcher function actually I am trying to run it on kaggle with two gpus , but it is only taking first gpu and not using the second one.

**Comment by geronimi73** [comment]
```python
from accelerate import notebook_launcher

def test():
    from accelerate import Accelerator
    accelerator = Accelerator()
    print(accelerator.distributed_type)

notebook_launcher(test, num_processes=2) 
```

https://github.com/geronimi73/accelerate_tricks/blob/main/distributed_inference.ipynb

**Comment by simpleParadox** [comment]
I was also facing a similar issue and this worked for me. The solution mentioned by @geronimi73 did not work for me, because I was using a dataloader. Effectively, I think if you directly use the _untokenized_ inputs and tokenize them inside the loop, @geronimi73's is the one to go with. If you're using a dataloader (containing tokenized inputs), the following is worth a shot.

```python
generated_texts = []
generated_outputs = []
print("Running inference on a single dataloader.")
# with accelerator.split_between_processes(val_dataloader) as vd: # Instead of this mentioned in 
print("All batch size before prepare: ")
model = model.model
model, vd = accelerator.prepare(model, val_dataloader)
for batch in tqdm(vd):
    input_ids = batch['inputs']['input_ids']
    attention_mask = batch['inputs']['attention_mask']
    
    tokenizer.pad_token_id = tokenizer.eos_token_id

    with torch.no_grad():
        outputs = model.module.generate(
            input_ids=input_ids,
            attention_mask=attention_mask,
            max_length=128,
            num_beams=1,
            early_stopping=False,
            pad_token_id=tokenizer.pad_token_id
        )
    
    # using accelerate.utils.gather_object() does not seem to remove duplicates for me but the gather_for_metrics does.
    # it must be noted the gather_for_metrics() receives a non-string value so that's why the decoding is being done later.
    # gather_for_metrics() also removes any duplicates that were padded in the last batch of the dataloader. This is the case where the number of samples in the dataloader is not divisible by the number of gpus used, resulting in the creation of extra batches by accelerator.prepare() . 
    outputs = accelerator.gather_for_metrics(outputs) # Remove any duplicates. accelerator = Accelerator()
    print("Output shape: ", outputs.shape)
    generated_outputs.append(outputs)

    for o in generated_outputs:
        generated_text = tokenizer.batch_decode(o, skip_special_tokens=True)
        generated_texts.append(generated_text) 
return generated_texts 
```
