### ISSUE TITLE
TPU training example does not work - undefined symbol: _ZN2at13_foreach_erf_EN3c108ArrayRefINS_6TensorEEE

### ISSUE THREAD

**Issue by MoritzLaurer** [huggingface/accelerate#202]
I'm trying to train a model on a google colab TPU with accelerate. When I simply copy and paste the Hugging Face example notebook here https://github.com/huggingface/notebooks/blob/master/examples/accelerate/simple_nlp_example.ipynb

I get the following error: `ImportError: /usr/local/lib/python3.7/dist-packages/_XLAC.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at13_foreach_erf_EN3c108ArrayRefINS_6TensorEEE`

Here is a link to the copied colab with the exact traceback at the end: https://drive.google.com/file/d/1Gp0-7XhJb_h7O4WlmOE-g5K5VB0bGOs6/view?usp=sharing

Update: I get the same error, when I execute Google's own guide to xla in this notebook here: https://colab.research.google.com/github/pytorch/xla/blob/master/contrib/colab/getting-started.ipynb#scrollTo=42avAvSg17by
The error occurs in the line: 
`import torch_xla
`

**Comment by sgugger** [comment]
From the looks of it, Colab upgrade PyTorch to 1.10 so you should replace the line that installs `torch-xla` to
```
!pip install cloud-tpu-client==0.10 https://storage.googleapis.com/tpu-pytorch/wheels/torch_xla-1.10-cp37-cp37m-linux_x86_64.whl
```
Will update the notebook shortly.

**Comment by MoritzLaurer** [comment]
Hey thanks for the quick response!

When I tried it, I got the following error: `ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /usr/local/lib/python3.7/dist-packages/torch_xla/lib/libxla_computation_client.so)`

I don't know what it means, but seems to be a more fundamental issue: https://stackoverflow.com/questions/62324422/version-glibc-2-28-not-found

What just solved it for me was reinstalling`!pip3 install torch==1.9`

**Comment by sgugger** [comment]
Yeah, the migration form PyTorch 1.9 to 1.10 is probably not entirely complete.
