### ISSUE TITLE
ZeRO++ support in Accelerate's DeepSpeed integration

### ISSUE THREAD

**Issue by SumanthRH** [huggingface/accelerate#2020]
Hi,

I've been going over multi-node training strategies with Accelerate + DeepSpeed and had a question: Does the Accelerate integration support [ZeRO++](https://www.deepspeed.ai/tutorials/zeropp/)? With ZeRO++, one can, for example, have a hybrid sharding strategy where you have DS ZeRO-3 running on each machine with data parallelism across machines. I couldn't find any information on whether this was supported. This is a simple config change with DeepSpeed (`zero_hpz_partition_size`) so I'm guessing it is supported, but I wanted clarity. I also see that the corresponding hybrid sharding strategy is supported by the FSDP integration. 

It would be great if this can be clarified in the [docs](https://huggingface.co/docs/accelerate/v0.23.0/en/usage_guides/deepspeed) as well! 

cc @pacman100

**Comment by SumanthRH** [comment]
Ping @pacman100 @muellerzr

**Comment by pacman100** [comment]
Hello @SumanthRH, yes, as you suggested it is a simple config change and should be supported by the current integration of DeepSpeed. If you already have a PR in mind with the updates to the docs, it would be much appreciated. Thank you!

**Comment by SumanthRH** [comment]
Hi @pacman100 , great! I'll put up a PR soon for the documentation!
