### ISSUE TITLE
Is there a best practice for progress bars?

### ISSUE THREAD

**Issue by fang-d** [huggingface/accelerate#2029]
When I use `accelerate` for model training, I usually use a progress bar library (such as `tqdm`) in the main process to wrap the `DataLoader` prepared by `accelerate` to remind me of the training progress and speed.

```python
from tqdm import tqdm
from accelerate import Accelerator
accelerator = Accelerator()

model, optimizer, training_dataloader, scheduler = accelerator.prepare(
    model, optimizer, training_dataloader, scheduler
)

dataloader_with_bar = tqdm(
    training_dataloader, disable=(not accelerator.is_local_main_process)
)

for batch in dataloader_with_bar:
    optimizer.zero_grad()
    inputs, targets = batch
    inputs = inputs.to(device)
    targets = targets.to(device)
    outputs = model(inputs)
    loss = loss_function(outputs, targets)
    accelerator.backward(loss)
    optimizer.step()
    scheduler.step()
```

The program aligns with our expectations when using a single GPU for model training.

When we use multiple GPUs for DDP training, the data obtained by each training process will be split. Since training in multi-GPU situations is asynchronous, the progress bar displays the training progress of the main process rather than the overall training progress.

I wonder if there is a best practice that can count the training progress of all processes without reducing training speed, so that my progress bar can reflect the overall training progress?

**Comment by fang-d** [comment]
Thank you for your response. Your code has indeed offered me a fresh perspective.

However, I'm curious if you've evaluated the performance implications of using the wait_for_everyone function at the end of each batch in DDP? I'm apprehensive that this function might block the thread on each GPU until all batches are completed. Could this blocking mechanism be a bottleneck that affects the efficiency of DDP?

**Comment by geronimi73** [comment]
> if you've evaluated the performance implications

yes I did check. not with training but with inference and there was basically no difference. In your case (training), I would assume there has to be a synch step anyway somewhere within ```step()``` because the weights have to be updated on all GPUs, right? That's an assumption though.

**Comment by muellerzr** [comment]
Just for transparency here, we also have our own `tqdm` module in accelerate which will just print the progress bar on the main process if set with the defaults: https://github.com/huggingface/accelerate/blob/main/src/accelerate/utils/tqdm.py

There would be performance issues yes, so you can just rely on the main progress bar since the dataloader will be split across `n` GPUs so the progress bar will be `1/n` representing each worker. You could update it with each one, sure. But using this main method you avoid `wait_for_everyone`/sync

**Comment by SunMarc** [comment]
Hi @irowberryFS , that error is expected. You cannot call len on an iterable dataset.

**Comment by irowberryFS** [comment]
@SunMarc sorry, I should have been more clear. I currently use non-Hugging Face tqdm, and I pass in the `total` argument (calculated beforehand), and it works. When I use Hugging Face tqdm (including `total`) it throws the `len()` error. I would like to use Hugging Face's tqdm to keep accurate track of training progress efficiently.

**Comment by SunMarc** [comment]
Oh thx for the clarification. This is indeed not normal. Can you provide a quick reproducer, that should be an easy fix.

**Comment by irowberryFS** [comment]
Okay, here is code that reproduces the issue @SunMarc 
```
from accelerate.utils import tqdm
from datasets import load_dataset
from torch.utils.data import DataLoader

dataset = load_dataset('fka/awesome-chatgpt-prompts', 'en', split='train', streaming='true')
dl = DataLoader(dataset, 5)
epochs = 1

for epoch in range(epochs):
    with tqdm(dl, total=1000, unit='batch') as tepoch:
        tepoch.set_description(f"Epoch: {epoch}")
        for batch in tepoch:
            print(batch)
            loss = 0.1
            tepoch.set_postfix(loss=loss)
```
And here's the traceback
```
Traceback (most recent call last):
  File "/home/irowberry/projects/experiments.py", line 10, in <module>
    with tqdm(dl, total=1000, unit='batch') as tepoch:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/irowberry/projects/venv/lib/python3.11/site-packages/accelerate/utils/tqdm.py", line 35, in tqdm
    if main_process_only:
  File "/home/irowberry/projects/venv/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 474, in __len__
    length = self._IterableDataset_len_called = len(self.dataset)  # type: ignore[assignment, arg-type]
                                                ^^^^^^^^^^^^^^^^^
TypeError: object of type 'IterableDataset' has no len()
```

**Comment by irowberryFS** [comment]
@SunMarc  Any update on this?
