### ISSUE TITLE
Question: include reference to pytorch-accelerated in README as high level API example?

### ISSUE THREAD

**Issue by Chris-hughes10** [huggingface/accelerate#203]
Hi,

Great work on accelerate, I'm a big fan and excited to see it continue to grow!

I recently released a previously internal only library, now called `pytorch-accelerated` which provides a training loop built on top of accelerate for users who would like a little more structure in their training loops; it has been popular with my Microsoft colleagues, so hopefully useful to the public too! So, although it looks very new, it is based on something that has been around for a while!

I know there are already a bunch of tools in this space, but the key differentiator here is a streamlined feature set, and a huge emphasis on simplicity and transparency over all parts of the process - which I believe fits nicely with the goals of accelerate. This transparency extends to the fact that the library showcases that accelerate is the key machinery behind this trainer too, which the accelerator clearly accessible and used, as well as promoting accelerate's CLI for launching training jobs; it is even referenced in the name!

I thought it could be mutually beneficial to include a link to `pytorch-accelerated` in your docs and README when discussing other libraries that act as high level APIs to PyTorch, as I believe that `pytorch-accelerated` provides a good entrypoint to the accelerate library for users who perhaps aren't confident in writing/maintaining the whole loop, but like the simplicity and premise of accelerate.

What do you think?

 `pytorch-accelerated` is described in more detail both in the [docs](https://pytorch-accelerated.readthedocs.io/en/latest/index.html), in this [introductory blog post](https://medium.com/@chris.p.hughes10/introducing-pytorch-accelerated-6ba99530608c) and is available on pypi. 

Thanks,
Chris

**Comment by sgugger** [comment]
Hi Chris!
No problem with cross-referencing each other and I'm glad you found Accelerate useful :-) Would you like to take a stab at a PR that lists higher-level frameworks using Accelerate?

**Comment by Chris-hughes10** [comment]
Sure thing, I am only aware of pytorch-accelerated at the moment, but I'll take a look around and add a note to the docs.

**Comment by Chris-hughes10** [comment]
A very small PR is open here: https://github.com/huggingface/accelerate/pull/204
