### ISSUE TITLE
OOM of model trained on 0.22.0 with 0.23.0

### ISSUE THREAD

**Issue by jmzeng** [huggingface/accelerate#2030]
### System Info

```Shell
Working config:

- `Accelerate` version: 0.22.0
- Platform: Linux-5.15.0-84-generic-x86_64-with-glibc2.31
- Python version: 3.10.12
- Numpy version: 1.24.4
- PyTorch version (GPU?): 2.0.1+cu118 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 2015.35 GB
- GPU type: NVIDIA H100 80GB HBM3
- `Accelerate` default config:
        Not found

Config with issue:
- `Accelerate` version: 0.23.0
- Platform: Linux-5.15.0-84-generic-x86_64-with-glibc2.31
- Python version: 3.10.12
- Numpy version: 1.24.4
- PyTorch version (GPU?): 2.0.1+cu118 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 2015.35 GB
- GPU type: NVIDIA H100 80GB HBM3
- `Accelerate` default config:
        Not found
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

I was resuming from a checkpoint of `lmsys/longchat-7b-v1.5-32k` on Huggingface trained on 0.22.0 using HF Trainer. When resuming on 0.22.0, the experiment continues. However, when resuming on 0.23.0, it hits OOM. I'm wondering if there is a backward compatibility issue. 

I even tried restarting without `resume_from_checkpoint` option in Trainer and giving it the checkpoint file as the model directly, this also gives me the same behavior as above. 

### Expected behavior

Run would resume with 0.23 as with 0.22

**Comment by muellerzr** [comment]
Can you provide a full reproducer for me please? When testing in accelerate native I got the same memory results. And more specifically your versions of transformers please
