### ISSUE TITLE
Training with FSDP and Trainer class

### ISSUE THREAD

**Issue by nebrelbug** [huggingface/accelerate#2032]
### System Info

```Shell
- `Accelerate` version: 0.23.0
- Platform: Linux-3.10.0-1160.92.1.el7.x86_64-x86_64-with-glibc2.35
- Python version: 3.10.12
- Numpy version: 1.26.0
- PyTorch version (GPU?): 2.1.0a0+32f93b1 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 2003.87 GB
- GPU type: NVIDIA A100-SXM4-80GB
- `Accelerate` default config:
        Not found
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

`accelerate_config.yaml`
```yaml
compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: FSDP
downcast_bf16: 'no'
fsdp_config:
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_backward_prefetch_policy: BACKWARD_PRE
  fsdp_offload_params: false
  fsdp_sharding_strategy: 1
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_transformer_layer_cls_to_wrap: LlamaDecoderLayer
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
mixed_precision: 'no'
num_machines: 1
num_processes: 8
use_cpu: false
```

`loop.py`
```python
from transformers import LlamaForCausalLM, LlamaTokenizer, Trainer, TrainingArguments
from accelerate import Accelerator
import torch
import os
from get_data import train_dataset, eval_dataset, data_collator

accelerator = Accelerator()

SIZE = "7b"
MODEL_PATH = f"/mnt/models/llama2/hf/Llama-2-{SIZE}-hf"
NAME = f"llama2-{SIZE}-test"
PER_DEVICE_BATCH_SIZE = 1
NUM_EPOCHS = 1
LEARNING_RATE = 2e-5 * accelerator.num_processes
OUTPUT_DIR = os.environ["SLURM_JOB_NAME"]

tokenizer = LlamaTokenizer.from_pretrained(MODEL_PATH, legacy=False)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

model = LlamaForCausalLM.from_pretrained(MODEL_PATH, torch_dtype=torch.bfloat16)
model.config.do_sample = True

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=NUM_EPOCHS,
    learning_rate=LEARNING_RATE,
    logging_steps=10,
    per_device_train_batch_size=PER_DEVICE_BATCH_SIZE,
    remove_unused_columns=False,
    save_steps=1000,
    save_total_limit=1,
    report_to="wandb",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    tokenizer=tokenizer,
    data_collator=lambda x: data_collator(x, tokenizer),
)

trainer.train()
trainer.evaluate()

unwrapped_model = accelerator.unwrap_model(model)

unwrapped_model.save_pretrained(
    f"/mnt/finetunes/{NAME}",
    is_main_process=accelerator.is_main_process,
    save_function=accelerator.save,
    state_dict=accelerator.get_state_dict(model, unwrap=False)
)

if accelerator.is_main_process:
    tokenizer.save_pretrained(f"/mnt/finetunes/{NAME}")
```

`get_data.py`
```python
from datasets import load_from_disk, disable_caching
disable_caching()

IGNORE_TOKEN = -100

#####################
# FORMAT DATA       #
#####################

template_context = """### Instruction:
{instruction}

### Context:
{context}

### Response:
"""

template_no_context = """### Instruction:
{instruction}

### Response:
"""

def data_to_string(data):

    instruction = data["instruction"]
    context = data["context"]
    response = data["response"]

    template = template_context if len(context) > 0 else template_no_context

    source = template.format(instruction=instruction, context=context)

    return {
        "source": source,
        "text": source + response, 
    }

original_dataset = load_from_disk("../datasets/databricks-dolly-15k")["train"] 

dataset = original_dataset.map(
    data_to_string
).remove_columns(
    original_dataset.column_names
).filter(
    lambda x: len(x["text"]) < 1000 # TODO: change to 4000
)

## TEMPORARY truncate data
dataset = dataset.select(range(200))

#####################
# SPLIT DATA        #
#####################

processed_dataset = dataset.train_test_split(test_size=0.1)

train_dataset = processed_dataset["train"]
eval_dataset = processed_dataset["test"]

#####################
# CREATE DATALOADER #
#####################


def data_collator(features, tokenizer):
    sources = [feature["source"] for feature in features]
    targets = [feature["text"] for feature in features]

    source_tokens = tokenizer(
        sources,
        return_tensors="pt",
        padding='longest',
        max_length=None,
    )

    target_tokens = tokenizer(
        targets,
        return_tensors="pt",
        padding='longest',
        max_length=None,
    )
        
    labels = target_tokens["input_ids"].clone()

    for i in range(len(labels)):
        source_len = source_tokens["attention_mask"][i].sum()
        
        labels[i, :source_len] = IGNORE_TOKEN

    res = {
        "input_ids": target_tokens["input_ids"],
        "attention_mask": target_tokens["attention_mask"],
        "labels": labels,
    }

    return res
```

`launch.sh`
```bash
export SLURM_JOB_NAME="local-test"
accelerate launch --config_file ./accelerate_config.yaml loop.py
```

### Expected behavior

My understanding is that the Transformers Trainer class should work out-of-the-box with Accelerate. 

In the above example, I try to use Accelerate with FSDP to fine-tune Llama 2. I've tested the fine-tuning without FSDP and it works exactly as expected.

However, when I run the code with FSDP (see the above `accelerate_config.yaml` file) and then save the model, it outputs gibberish. I've tried combinations of multiple different strategies:
- Calling `model = accelerator.prepare(model)` before passing the model into the Trainer
- Unwrapping the model before calling `save_pretrained()`
- Using `save_function=accelerator.save` in `save_pretrained()`

But none of them seem to fix the problem. Depending on the model architecture, I occasionally get errors like this:
- `Some weights of the model checkpoint at /.../llama2-7b-test were not used when initializing LlamaForCausalLM: ['_flat_param']`

Thanks so much for the help!

**Comment by brcps12** [comment]
In my experience, when training with accelerate + FSDP and saving the model, it was saved properly as shown below.

```python
model = accelerate.prepare(model)

for epoch in range(num_epoch):
     #training

full_state_dict_config = FullStateDictConfig(offload_to_cpu=True, rank0_only=True)

with FSDP.state_dict_type(model, StateDictType.FULL_STATE_DICT, full_state_dict_config):
    state_dict = accelerator.get_state_dict(model, unwrap=False)

accelerator.unwrap_model(model).save_pretrained(
    path_to_save,
    is_main_process=accelerator.is_main_process,
    save_function=accelerator.save,
    state_dict=state_dict,
)
````

Like in your case, the model was not saved properly, such as saying strange words or having a size mismatch error when load the model. After save the model with the above code, it worked well.
However, since I didn't use `Trainer`, I can't say it's the same problem. I hope you it helps.

**Comment by nebrelbug** [comment]
@brcps12 thanks for the tip! did you remove the FSDP config from your accelerate_config.yaml?

**Comment by brcps12** [comment]
> @brcps12 thanks for the tip! did you remove the FSDP config from your accelerate_config.yaml?

No, it is just like as you wrote.

**Comment by nebrelbug** [comment]
@brcps12 this works with 1 node, but not with 2 nodes.

@pacman100 do you happen to have any ideas?

**Comment by nebrelbug** [comment]
I'm still experiencing this issue. Maybe it's because we don't have Pyxis working? Could somebody who has Pyxis installed please try this out?

**Comment by muellerzr** [comment]
cc @pacman100

**Comment by nebrelbug** [comment]
This is still an issue.

**Comment by HanGyeol-Yoo** [comment]
I am also having difficulty applying FSDP using the accelerate config while using the huggingface trainer. I noticed there are fsdp and fsdp_config items in the trainer arguments, have you used them?

**Comment by hanyin88** [comment]
Wondering if any update on this?

**Comment by pacman100** [comment]
Hello @nebrelbug,

Can you please run https://github.com/pacman100/DHS-LLM-Workshop/blob/main/chat_assistant/sft/training/run_fsdp.sh and look at https://github.com/pacman100/DHS-LLM-Workshop/blob/main/chat_assistant/sft/training/train.py on how to use FSDP with Trainer class. Simply using `trainer.save_model()` should work as expected.

**Comment by pacman100** [comment]
Here are the output logs from a previous FSDP training run for above script
[Uploading output (1).log…]()

**Comment by zhaochen0110** [comment]
> Uploading output (1).log…



> Wondering if any update on this?
> 
> Following this approach, typically I would use things like `print(model.model.layers[0].self_attn.q_proj.weight)` to check if the trained model's weight is the same as the saved model's weight. However above code won't work for the model or unwrapped_model in the example script from @nebrelbug .
> 
> In my own case, when loading saved model I run into this error message that don't seem to be right:
> 
> Here's my config setting:
> 
> ```
> compute_environment: LOCAL_MACHINE
> debug: true
> distributed_type: FSDP
> downcast_bf16: 'no'
> fsdp_config:
>   fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
>   fsdp_backward_prefetch_policy: BACKWARD_PRE
>   fsdp_cpu_ram_efficient_loading: false
>   fsdp_forward_prefetch: false
>   fsdp_offload_params: false
>   fsdp_sharding_strategy: 1
>   fsdp_state_dict_type: SHARDED_STATE_DICT
>   fsdp_sync_module_states: true
>   fsdp_use_orig_params: false
>   machine_rank: 0
>   main_training_function: main
>   mixed_precision: bf16
>   num_machines: 1
>   num_processes: 4
>   rdzv_backend: static
> ```
> 
> ```
> Some weights of the model checkpoint at RLHF/runs/test_round2 were not used when initializing LlamaForCausalLM: ['_flat_param']
> - This IS expected if you are initializing LlamaForCausalLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
> - This IS NOT expected if you are initializing LlamaForCausalLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
> Some weights of LlamaForCausalLM were not initialized from the model checkpoint at RLHF/runs/test_round2 and are newly initialized: ['layers.4.mlp.gate_proj.weight', 'layers.3.self_attn.o_proj.weight', 'layers.16.mlp.gate_proj.weight', 'layers.24.mlp.gate_proj.weight', 'layers.19.self_attn.q_proj.weight', 'layers.14.self_attn.q_proj.weight', 'layers.19.post_attention_layernorm.weight', 'layers.27.mlp.up_proj.weight', 'layers.22.self_attn.q_proj.weight', 'layers.23.mlp.up_proj.weight', 
> .... (same error messages for almost all layers)
> 'layers.29.self_attn.q_proj.weight', 
> 'lm_head.weight',
> 
> You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
> ```
> 
> Many thanks.

I also meet the same problem when conducting the inference on my trained models by fsdp. Is there any solution?

**Comment by ShengYun-Peng** [comment]
This is still a problem. I trained with llama3 and gpt2, get size mismatch on both

```
size mismatch for transformer.wte.weight: copying a param with shape torch.Size([5626478]) from checkpoint, the shape in current model is torch.Size([50257, 768]).
size mismatch for transformer.wpe.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([1024, 768]).
size mismatch for transformer.ln_f.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([768]).
size mismatch for transformer.ln_f.bias: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([768]).
You may consider adding `ignore_mismatched_sizes=True` in the model `from_pretrained` method.
```
