### ISSUE TITLE
in version v0.21.0, fp16 will be saved in fp32?

### ISSUE THREAD

**Issue by gauss-clb** [huggingface/accelerate#2049]
### System Info

```Shell
https://github.com/huggingface/accelerate/blob/v0.21.0/src/accelerate/accelerator.py#L2851
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

None

### Expected behavior

Is this behavior expected?

**Comment by muellerzr** [comment]
In the most recent versions we now save in whatever original mixed precision format it was in
