### ISSUE TITLE
Accelerate Examples: What is expected to print on terminal?

### ISSUE THREAD

**Issue by davidleejy** [huggingface/accelerate#2051]
### System Info

```Shell
- `Accelerate` version: 0.23.0
- Platform: Linux-5.4.0-121-generic-x86_64-with-glibc2.31
- Python version: 3.10.13
- Numpy version: 1.26.0
- PyTorch version (GPU?): 1.13.1 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 1007.69 GB
- GPU type: NVIDIA A100-SXM4-40GB
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: fp16
        - use_cpu: False
        - debug: False
        - num_processes: 2
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: 3,4
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

I was trying to run a simple example (`nlp_example.py`) to kind of perform the equivalent of a hello world task in accelerate, but unfortunately, I'm uncertain as to whether it's working correctly, and I'm somewhat embarrassed to have to post this issue ticket to seek assistance. 😅

I ran `$ python examples/nlp_example.py --cpu ` and got this output:

```bash
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
You're using a BertTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
```

I believe the program continues to run after the above message is printed because control of the terminal's prompt isn't returned to me.

There isn't a tqdm bar, progress bar, or signs of life of some sort to indicate that the example was running.

Would be great if someone who has some success at running any basic accelerate example scripts to chime in 🙂

### Expected behavior

Signs of life of some sort to indicate that the example is running fine.

**Comment by muellerzr** [comment]
After every epoch a print statement should show the metrics, which you can find in the file here: https://github.com/huggingface/accelerate/blob/main/examples/nlp_example.py#L188

(In the future, please use the forums for questions like this :) https://discuss.huggingface.co/c/accelerate/18

**Comment by davidleejy** [comment]
Thanks @muellerzr for weighing in.

While statements indicating that training is taking place are printed when the pytorch version is compatible with the CUDA version, these statements aren't printed when the versions are incompatible.

```
epoch 0: {'accuracy': 0.7769607843137255, 'f1': 0.8520325203252033}
epoch 1: {'accuracy': 0.8504901960784313, 'f1': 0.897822445561139}
epoch 2: {'accuracy': 0.8455882352941176, 'f1': 0.8904347826086957}
```

On my end, the only indication that something is afoot when there's an incompatibility between pytorch and CUDA versions is this warning being printed:

```bash
UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11060). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
```

When this warning appears, `nlp_example.py` doesn't contuinue to print statements indicating that training is occurring, nor any errors.

**Comment by muellerzr** [comment]
This is because it's training on the CPU. We can add a new print statement in to print the state probably

**Comment by davidleejy** [comment]
Ah I see... thanks for helping me understand what's going on under the hood.

In the meantime, I will petition my machine's administrator to update the nvidia driver and CUDA libraries.
