### ISSUE TITLE
Memory leak on `accelerate.init_empty_weights`

### ISSUE THREAD

**Issue by Curt-Park** [huggingface/accelerate#2063]
### System Info

```Shell
- `Accelerate` version: 0.18.0
- Platform: Linux-5.15.0-82-generic-x86_64-with-glibc2.31
- Python version: 3.10.12
- Numpy version: 1.25.2
- PyTorch version (GPU?): 2.1.0+cu121 (True)
- `Accelerate` default config:
        Not found
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

```python
import tracemalloc
import psutil
import gc
import torch

from diffusers.models.autoencoder_kl import AutoencoderKL

f = open("tracemalloc.txt", "w")
process = psutil.Process()
tracemalloc.start()

for i in range(1000):
    tracemalloc.reset_peak()
    kwargs = {'torch_dtype': torch.float16, 'device_map': None, 'max_memory': None, 'offload_folder': None, 'offload_state_dict': False, 'variant': None, 'low_cpu_mem_usage': True}
    AutoencoderKL.from_pretrained("./vae", **kwargs)

    size, peak = tracemalloc.get_traced_memory()
    log = f"iter {i+1}: current size: {size}, peak size: {peak}, threshold: {gc.get_threshold()}, cnt: {gc.get_count()}, mem: {process.memory_info().rss}\n"
    print(log)
    f.write(log)

tracemalloc.stop()
f.close()
```
These iterations cause memory leaks.

- Log (1,000 iteration): [tracemalloc.txt](https://github.com/huggingface/accelerate/files/12998967/tracemalloc.txt)

I found the leaks come from `accelerate.init_empty_weights`: https://github.com/huggingface/accelerate/blob/9fd64b7ea994dd34345d42b75372e9dc771d5301/src/accelerate/big_modeling.py#L51

Actually, PyTorch makes this issue when it initializes the parameters on `meta` device.
With other devices (e.g. cpu, cuda), it doesn't leak the memory.

```python
nn.Module.register_parameter(module, name, param)
module._parameters[name] = torch.nn.Parameter(module._parameters[name].to("cpu"), **kwargs)   # NO LEAK!
module._parameters[name] = torch.nn.Parameter(module._parameters[name].to("cuda"), **kwargs)  # NO LEAK!
module._parameters[name] = torch.nn.Parameter(module._parameters[name].to("meta"), **kwargs)  # LEAK!
```

### Expected behavior

I suggest adding an option for `device` for `init_empty_weights`.
For example,
```python
@contextmanager
def init_empty_weights(include_buffers: bool = None, device: str = "cuda"):
    if include_buffers is None:
        include_buffers = parse_flag_from_env("ACCELERATE_INIT_INCLUDE_BUFFERS", False)
    with init_on_device(torch.device(device), include_buffers=include_buffers) as f:
        yield f
```

- Log (1,000 iterations with cuda - No leaks): [tracemalloc_cuda.txt](https://github.com/huggingface/accelerate/files/12999062/tracemalloc_cuda.txt)

**Comment by muellerzr** [comment]
Probably best to open this on pytorch then, and just use `init_on_device` instead for them to fix the root of the issue rather than directly changing a critical part of the Accelerate API.
