### ISSUE TITLE
GPU allocation increases when using save_state()

### ISSUE THREAD

**Issue by hungvo304ml** [huggingface/accelerate#2065]
I am still facing the same issue discussed in https://github.com/huggingface/accelerate/issues/1865#issuecomment-1686078479_, Currently, the fix is suggested by keeping the original model type when saving, but this does not help.

I am using DDP and FSDP. 

Specifically, when using FSDP, the GPU allocation does decrease during training and validation. But when it comes to the checkpoint step using `save_state()`, the amount of GPU allocation increases to the same amount as when FSDP is not used.

Environments:
```
accelerate                0.23.0
torch                     2.1.0
timm                      0.9.7
torchaudio                2.1.0
torchvision               0.16.0
transformers              4.26.1
```

**Comment by muellerzr** [comment]
CC @pacman100

**Comment by pacman100** [comment]
Hello @hungvo304ml, please refer to the documentation on how to save./load models when working with FSDP: https://huggingface.co/docs/accelerate/usage_guides/fsdp#saving-and-loading

**Comment by muellerzr** [comment]
@hungvo304ml can you please provide us a full reproducer? This would help immensely to see what may be going wrong. Thanks!
