### ISSUE TITLE
how to automatically load state dict from memory to a multi-gpu device?

### ISSUE THREAD

**Issue by tlogn** [huggingface/accelerate#2067]
```    Python    
        config_dict = AutoConfig.from_pretrained(model_config, device_map="auto")
        model = AutoModelForCausalLM.from_config(config_dict)
        raw_state_dict = torch.load(args.model_path, map_location="cpu")        
        state_dict = convert_ckpt(raw_state_dict)
        model.load_state_dict(state_dict, strict=False)
```

`model.load_state_dict(state_dict, strict=False)` only loads state dict on a single gpu, even when `device_map="auto"` is set by `AutoConfig`. Additionally,  the `load_checkpoint_and_dispatch` func only accepts a file path as the `checkpoint` parameter.

Is there any way to automatically load state dict from memory to a multi-gpu device?

**Comment by SunMarc** [comment]
Hi @tlogn, if you want to understand how we load the state dict from memory to `multi-gpu `device, just look into the `load_checkpoint_and_dispatch` function.

**Comment by tlogn** [comment]
> Hi @tlogn, if you want to understand how we load the state dict from memory to `multi-gpu `device, just look into the `load_checkpoint_and_dispatch` function.

Yes, I successfully load llama70B by simply imitating the `load_checkpoint_and_dispatch ` func. I would appreciate it if an official huggingface function could be provided to perform this task.  Since my current implementation is not versatile enough, I will need to make modifications to support other models such as Baichuan and chatglm.

Below is my implementation. Can you provide any suggestions to enhance its generalization?

```Python

    max_memory = get_balanced_memory(
        model,
        no_split_module_classes=["LlamaDecoderLayer"],
        dtype=dtype,
    )
    device_map = infer_auto_device_map(model, max_memory=max_memory, no_split_module_classes=["LlamaDecoderLayer"], dtype=dtype)

    for param_name, param in state_dict.items():
        module_name = param_name
        while len(module_name) > 0 and module_name not in device_map:
            module_name = ".".join(module_name.split(".")[:-1])
        if module_name == "" and "" not in device_map:
            # TODO: group all errors and raise at the end.
            raise ValueError(f"{param_name} doesn't have any device set.")
        param_device = device_map[module_name]

        set_module_tensor_to_device(
            model,
            param_name,
            param_device,
            value=param,
            dtype=dtype,
            fp16_statistics=None,
        )
    dispatch_model(
        model,
        device_map=device_map,
    )
```

**Comment by muellerzr** [comment]
cc @SunMarc
