### ISSUE TITLE
How to use cpu_offload function, attach_align_device_hook function，

### ISSUE THREAD

**Issue by LeonNerd** [huggingface/accelerate#2068]
attach_align_device_hook is called in the cpu_offload function. How is skip_keys used in attach_align_device_hook ?
def attach_align_device_hook(
    module: torch.nn.Module,
    execution_device: Optional[torch.device] = None,
    offload: bool = False,
    weights_map: Optional[Mapping] = None,
    offload_buffers: bool = False,
    module_name: str = "",
    skip_keys: Optional[Union[str, List[str]]] = None,
    preload_module_classes: Optional[List[str]] = None,
):
 I wonder what the role of skip keys is?I see this function in diffusers inference stable-diffusion using enable_sequential_cpu_offload.
What I want to achieve is to adjust some of the stable-diffusion submodules to run in the gpu, so that the vram occupancy can be controlled.

**Comment by SunMarc** [comment]
see this https://github.com/huggingface/accelerate/issues/1394
