### ISSUE TITLE
Support of Dynamic Batching (varying batch size BatchSampler)

### ISSUE THREAD

**Issue by zhliu0106** [huggingface/accelerate#207]
Hi!

I wrote a BatchSampler that can iteratively generate dynamic batch indices for Dynamic Batching (using max_tokens instead of fixed batch_size). It works with a single GPU, but not with multiple GPUs. 

I read Accelerate source code and found the BatchSampler will be wrapped up by `class BatchSamplerShard`  from `accelerate/data_loader.py`. Let's take a look at BatchSamplerShard's `_iter_with_no_split` method code:

```python
def _iter_with_no_split(self):
        initial_data = []
        batch_to_yield = []
        for idx, batch in enumerate(self.batch_sampler):
            # We gather the initial indices in case we need to circle back at the end.
            if not self.drop_last and idx < self.num_processes:
                initial_data += batch
            # We identify the batch to yield but wait until we ar sure every process gets a full batch before actually
            # yielding it.
            if idx % self.num_processes == self.process_index:
                batch_to_yield = batch
            if idx % self.num_processes == self.num_processes - 1 and len(batch) == self.batch_size:
                yield batch_to_yield
                batch_to_yield = []
        ....
```
As shown in the code, BatchSamplerShard will check whether the length of batch is equal to self.batch_size (`len(batch)==self.batch_size`) before yield batch indices. However, the number of the batch indices generated from my BatchSampler is not always equal to the fixed batch_size. 

**When I delete `and len(batch) == self.batch_size`, it worked**. But I don't know what bug this will lead to in other situations.

Can you update the code to support dynamic batching (varying batch size) officially?

Thank you!

**Comment by sgugger** [comment]
That is a bit tricky since some of the methods that gather tensors across all GPUs then require batches of the same size, so that check is mainly there to make sure we either drop the last incomplete batch or complete it with some data.

I'll see what can be done to add support for batches of varying size with a new flag :-)

**Comment by zhliu0106** [comment]
That will be very helpful, thank you!
