### ISSUE TITLE
Could not use log_artifact with mlflow tracking

### ISSUE THREAD

**Issue by phucdoitoan** [huggingface/accelerate#2070]
### System Info

```Shell
- `Accelerate` version: 0.23.0
- Platform: Linux-4.18.0-477.13.1.el8_8.x86_64-x86_64-with-glibc2.28
- Python version: 3.9.18
- Numpy version: 1.25.2
- PyTorch version (GPU?): 2.0.1 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 1007.10 GB
- GPU type: NVIDIA A40
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: fp16
        - use_cpu: False
        - debug: False
        - num_processes: 1
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: all
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
```

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [x] My own task or dataset (give details below)

### Reproduction

I try to access the mlflow internal tracker and to use log_artifact as in the documentation https://huggingface.co/docs/accelerate/usage_guides/tracking#accessing-the-internal-tracker , but faced errors.

`
from accelerate import Accelerator
accelerator = Accelerator(log_with="mlflow")

accelerator.init_trackers("my_project_name")

if accelerator.is_main_process:
    tracker = accelerator.get_tracker('mlflow')
    tracker.log_artifact('tmp')`

> AttributeError                          Traceback (most recent call last)
Cell In[2], line 8
      6 if accelerator.is_main_process:
      7     tracker = accelerator.get_tracker('mlflow')
----> 8     tracker.log_artifact('tmp')
AttributeError: 'MLflowTracker' object has no attribute 'log_artifact'

Or 

`from accelerate import Accelerator
accelerator = Accelerator(log_with="mlflow")

accelerator.init_trackers("my_project_name")

tracker = accelerator.get_tracker("mlflow", unwrap=True)
with accelerator.on_main_process:
    tracker.log_artifact("tmp")
`

> AttributeError                          Traceback (most recent call last)
Cell In[1], line 7
      4 accelerator.init_trackers("my_project_name")
      6 tracker = accelerator.get_tracker("mlflow", unwrap=True)
----> 7 with accelerator.on_main_process:
      8     tracker.log_artifact("tmp")
AttributeError: \_\_enter\_\_

### Expected behavior

Being able to use log_artifact with internal mlflow tracker.

**Comment by EdwardJRoss** [comment]
In the first example I think you need to pass `unwrap=True` to `get_tracker`.

In the second example I don't think you can use `on_main_process` like that as it is a [function decorator](https://huggingface.co/docs/accelerate/v0.24.0/en/package_reference/accelerator#accelerate.Accelerator.on_main_process).

How about using `accelerator.is_main_process` instead?

```
from accelerate import Accelerator
accelerator = Accelerator(log_with="mlflow")

accelerator.init_trackers("my_project_name")

tracker = accelerator.get_tracker("mlflow", unwrap=True)
if accelerator.is_main_process:
    tracker.log_artifact("tmp")
```

**Comment by HernandoR** [comment]
not working on my side, error 'GeneralTracker' object has no attribute 'log_artifact 

seems returnning a GeneralTracker instead of a MLflowTracker

**Comment by luiz0992** [comment]
I just merged a PR that fixes this.

https://github.com/huggingface/accelerate/pull/3419

After the next release or installing from the `main` branch should include `log_artifacts`, `log_artifact` and `log_figure` at the MLFlowTracker.
