### ISSUE TITLE
Question/Feature Request - Model Pipeline Parallelism on multiple GPUs without offloading?

### ISSUE THREAD

**Issue by chiragjn** [huggingface/accelerate#2074]
### System Info

```Shell
accelerate==0.23.0
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

This started from https://github.com/huggingface/peft/issues/868 issue where `device_map="auto"` can leave some of the weights on the meta device because of insufficient resources when calculating the device map but that can cause issues when saving the checkpoint as weights are not being moved to a real device before saving.

While device_map="auto" is very useful, how can I optionally,
- Disable any offloading to CPU and Disk but still use multiple GPUs while inferring the device map automatically
- Provide a list of devices explicitly and enforce that nothing stays on meta device - raise an error if the model will not fit on given devices.

### Expected behavior

NA

**Comment by SunMarc** [comment]
Hi @chiragjn, thanks for raising this issue. We are looking into how to better handle this. 
To answer some of your questions: 

> Disable any offloading to CPU and Disk but still use multiple GPUs while inferring the device map automatically

If device_map = "auto" uses offloading, it means that you don't have enough space on your GPUs to load your your model. 

> Provide a list of devices explicitly and enforce that nothing stays on meta device - raise an error if the model will not fit on given devices.

Currently, there is a `memory_map` arg that can be used for this purpose but you need to map each device to a memory size.
