### ISSUE TITLE
It seems that FSDP's cpu_ram_efficient_loading setting doesn't work?

### ISSUE THREAD

**Issue by lllukehuang** [huggingface/accelerate#2100]
I run my FSDP scripts with the following configs:

```
compute_environment: LOCAL_MACHINE
debug: false
distributed_type: FSDP
downcast_bf16: 'no'
fsdp_config:
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_backward_prefetch_policy: BACKWARD_PRE
  fsdp_cpu_ram_efficient_loading: true
  fsdp_forward_prefetch: false
  fsdp_offload_params: false
  fsdp_sharding_strategy: 1
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_sync_module_states: true
  fsdp_use_orig_params: false
machine_rank: 0
main_training_function: main
mixed_precision: 'bf16'
num_machines: 1
num_processes: 4
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

But it seems that there are still 4 processes loading the full model checkpoint and transferring data from CPU to GPU?  Does `fsdp_cpu_ram_efficient_loading: true` still work?

**Comment by lllukehuang** [comment]
Seems that the `fsdp_cpu_ram_efficient_loading` config is loaded through 
https://github.com/huggingface/accelerate/blob/55747318a0f47cdfbc281e11269ba96214e4092d/src/accelerate/utils/launch.py#L106
and finally transferred into torch.distributed.run API:
https://github.com/huggingface/accelerate/blob/55747318a0f47cdfbc281e11269ba96214e4092d/src/accelerate/commands/launch.py#L654

Am I getting this right?

But I couldn't find any handling code for `fsdp_cpu_ram_efficient_loading` in Pytorch, does that mean the `fsdp_cpu_ram_efficient_loading` can't change anything?

Thanks for your reply.

**Comment by pacman100** [comment]
Hello, this only works with Transformers Models as is mentioned when setting that config parameter. It is used in Transformers when doing `from_pretrained`. See these:

https://github.com/huggingface/transformers/blob/c5be38cd27bee92be73c73ba09aec8bedf841423/src/transformers/modeling_utils.py#L131


https://github.com/huggingface/transformers/blob/c5be38cd27bee92be73c73ba09aec8bedf841423/src/transformers/modeling_utils.py#L476-L483


https://github.com/huggingface/transformers/blob/c5be38cd27bee92be73c73ba09aec8bedf841423/src/transformers/modeling_utils.py#L2598-L2599


https://github.com/huggingface/transformers/blob/c5be38cd27bee92be73c73ba09aec8bedf841423/src/transformers/modeling_utils.py#L3907-L3935

> But it seems that there are still 4 processes loading the full model checkpoint and transferring data from CPU to GPU?

On non-main processes, the weights are `torch.empty` weights.
Hope this resolves your question!
