### ISSUE TITLE
Cuda out or memory when resuming the training

### ISSUE THREAD

**Issue by Msadat97** [huggingface/accelerate#2102]
### System Info

```Shell
accelerate version: 0.22.0
os: ubuntu 22.04
python: 3.10.13
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

I can train the model normally from scratch on the gpu without OOM issue but when i stop the training process, load the saved states (checkpoints), and continue training, it gives me cuda out of memory error.

### Expected behavior

CUDA OOM should be independent on whether the script is loading the training state or not.

**Comment by muellerzr** [comment]
Can you try upgrading your accelerate version? IIRC we fixed this
