### ISSUE TITLE
OOM while generating with bitsandbytes & parallelization

### ISSUE THREAD

**Issue by drunkinlove** [huggingface/accelerate#2112]
### System Info

```Shell
- `Accelerate` version: 0.22.0
- Platform: Linux-5.4.0-84-generic-x86_64-with-glibc2.31
- Python version: 3.9.16
- Numpy version: 1.24.3
- PyTorch version (GPU?): 2.0.1+cu118 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 376.56 GB
- GPU type: GeForce RTX 2080 Ti
- `Accelerate` default config:
        Not found
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

Load `huggyllama/llama-30b` with 8-bit quantization & split on four 2080 Ti-GPUs, then try generating:
```
from transformers import AutoModelForCausalLM, AutoTokenizer
from accelerate import init_empty_weights
from accelerate.utils import load_and_quantize_model, BnbQuantizationConfig

model_name_or_path = "huggyllama/llama-30b"
with init_empty_weights():
    empty_model = AutoModelForCausalLM.from_pretrained(model_name_or_path)
empty_model.tie_weights()
bnb_quantization_config = BnbQuantizationConfig(load_in_8bit=True)
model = load_and_quantize_model(empty_model, weights_location=model_name_or_path, device_map="auto", bnb_quantization_config=bnb_quantization_config, no_split_module_classes=['LlamaDecoderLayer'])

model.config.max_length = 1536

tokenizer = AutoTokenizer.from_pretrained(model_name_or_path)
sample = "I think the weather outside is"
sample = tokenizer(sample)["input_ids"]
model.generate(torch.as_tensor([sample]))
```
Generation fails because there's not enough VRAM.

### Expected behavior

Model weights size estimated with [this tool](https://huggingface.co/docs/accelerate/main/en/usage_guides/model_size_estimator#gradio-demos) is 30 GB, and Eleuther AI's approximation for the amount of VRAM needed for inference is no more than 20% of the weights' size, or no more than 6 GB.
With parallelization and bnb-quantization, the `device_map` seems to suggest that each GPU holds around 8 GB of weights, leaving just above 2 GB free, or 8 GB total free.  However, inference fails, meaning the estimate doesn't work here. Is there a way to calculate the amount of VRAM I need for generation in my case?

**Comment by SunMarc** [comment]
Hi @drunkinlove , we wish it was easy to calculate the exact amount of VRAM needed. However, this depends on many factors and even more when it involves quantization.

**Comment by drunkinlove** [comment]
@SunMarc Thanks, I guess that's not surprising. Is there no way I can get at least a rough estimate of how much VRAM/how many devices I need?

**Comment by drunkinlove** [comment]
@SunMarc hi! Reminding you about my question (even though the answer is probably no)

**Comment by drunkinlove** [comment]
@SunMarc so no or at least not yet. Got it, thanks 🙂
