### ISSUE TITLE
Difference between huggingface deepspeed integration and accelerate deepspeed-plugin

### ISSUE THREAD

**Issue by jerryli1981** [huggingface/accelerate#214]
huggingface transformer support deepspeed (https://huggingface.co/docs/transformers/main_classes/deepspeed )

accelerate also support deepspeed via ds-plugin, so what is design thoughts besides no trainer flexibility?

**Comment by jerryli1981** [comment]
Another quick question is "BatchSamplerShard" in data_loader.py is functionally equal to torch.utils.data.distributed.DistributedSampler ?

**Comment by sgugger** [comment]
Please use [the forums](https://discuss.huggingface.co/) to ask questions as we keep the issues for bugs and feature requests only. The `Trainer` supports deepspeed but Accelerate is designed for people who don't want to use a `Trainer`. It also supports deepseed for people who want to use that library and retain full control over their training loop.
