### ISSUE TITLE
Feature Request: Support MS-AMP

### ISSUE THREAD

**Issue by winglian** [huggingface/accelerate#2143]
[Docs](https://azure.github.io/MS-AMP/docs/introduction)

MS-AMP would allow us to also store the weights in FP8, allowing for larger models to be trained on smaller hardware, as right now the weights are still stored on device as fp16/bf16.

The implementation example they provide seems similar to `accelerate.prepare(...)`:
```python
model, optimizer = msamp.initialize(model, optimizer, opt_level="O2")
```

**Comment by muellerzr** [comment]
Might be good to have this as an alternative choice, from their docs:

MS-AMP has the following benefit comparing with Transformer Engine:

    Speed up memory-limited operations by accessing one byte compared to half or single-precision.
    Reduce memory requirements for training models, enabling larger models.
    Speed up communication for distributed model by transmitting lower precision gradients.
    Reduce training time for large language models with larger minibatches.

**Comment by casper-hansen** [comment]
+++ would love to see MS-AMP supported. Currently, H100s are on par with A100s cost-wise even with the current FP8 implementation, but if MS-AMP FP8 can be implemented, it is likely anywhere between a 50-100% boost in training speed. We still need Flash Attention with FP8, but MS-AMP is a great first step towards faster training.

**Comment by muellerzr** [comment]
@winglian not quite yet! But I'll let you know for you to test :)

**Comment by muellerzr** [comment]
@winglian go ahead and try the branch out :) Note that it only works on single GPU for now (will look at deepspeed tommorow), and you shouldn't see a time decrease I don't *think*. What you should see though is a memory decrease for NLP based models.

For example, I ran bert-base-cased (NLP example) and saw:

```
FP8:
Before: 610.92 MB
After: 2.14 GB
BF16:
Before: 413.69 MB
After: 2.72 GB
```

But time was almost ~2x 😱

**Comment by casper-hansen** [comment]
Shouldn’t the FLOPs increase and thereby reducing training time? It should not be present on small models, but if you take a 30B, I would be surprised if you don’t see a difference

**Comment by muellerzr** [comment]
Correct. I only tested on a tiny model just to get the API stable 😉

**Comment by muellerzr** [comment]
Now that it’s a bit more stable, I saw both memory  decreases and speed increases when combining MS-AMP and TransformerEngine. More details are in the PR

**Comment by LSC527** [comment]
@muellerzr accelerate fp8 with ms-amp backend seems not work with deepspeed. However ms-amp itself support work with deepspeed (zero) https://azure.github.io/MS-AMP/docs/user-tutorial/usage/#usage-in-deepspeed

**Comment by muellerzr** [comment]
Correct, I'm looking into that this week
