### ISSUE TITLE
notebook_launcher fails when loading model from_pretrained 

### ISSUE THREAD

**Issue by nikrruun** [huggingface/accelerate#2148]
### System Info

```Shell
- `Accelerate` version: 0.25.0.dev0
- Platform: Linux-6.2.0-36-generic-x86_64-with-glibc2.35
- Python version: 3.9.18
- Numpy version: 1.25.0
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 2015.52 GB
- GPU type: NVIDIA A40
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: no
        - use_cpu: False
        - debug: False
        - num_processes: 2
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: 1,2
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

Run this snippet in a Jupyter Notebook on a multi-gpu machine:

```python
from accelerate import notebook_launcher, Accelerator
from transformers import AutoModelForCausalLM

def a():
    state = Accelerator()
    print(state.process_index, state.device)

model = AutoModelForCausalLM.from_pretrained("gpt2")

notebook_launcher(a, args=(), num_processes=2)
```

**Output**
```python
RuntimeError: CUDA has been initialized before the `notebook_launcher` could create a forked subprocess. This likely stems from an outside import causing issues once the `notebook_launcher()` is called. Please review your imports and test them when running the `notebook_launcher()` to identify which one is problematic and causing CUDA to be initialized.
```

### Expected behavior

The code above without ```model = AutoModelForCausalLM.from_pretrained("gpt2")``` gives:
```terminal
Launching training on 2 GPUs.
0 cuda:0
1 cuda:1

```

Any suggestions?

**Comment by muellerzr** [comment]
Pretty sure AutoModel will move the model to CUDA. I would check that, and keep that under your a() function if so.

**Comment by nikrruun** [comment]
If that were the case, then the official example for the notebook_launcher would fail too ([link](https://github.com/huggingface/notebooks/blob/main/examples/accelerate_examples/simple_nlp_example.ipynb))

Excerpt:
ln [16]:
```python
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(model_checkpoint, num_labels=2)
```

and ln [25]:
```python
from accelerate import notebook_launcher

notebook_launcher(training_function, (model,))
```

**Comment by muellerzr** [comment]
@nikrruun can you provide your output for `pip freeze` please?

**Comment by nikrruun** [comment]
I narrowed the problem down to bitsandbytes package. Importing it immediately causes cuda init, which is not allowed for notebook_launcher.
Removing the package resolves the issue, but is probably undesirable.
To summarize: AutoModel.from_pretrained automatically imports bitsandbytes (idk for what purpose) if it is available.



pip freeze of the non-working env as a file: 
[pip.txt](https://github.com/huggingface/accelerate/files/13348970/pip.txt)

**Comment by muellerzr** [comment]
Yes, that is something unavoidable and what I was going to ask about.
