### ISSUE TITLE
[Bug] DataLoader always return batches in the same order (Expected Random)

### ISSUE THREAD

**Issue by allanj** [huggingface/accelerate#2157]
### System Info

```Shell
`accelerate==0.24.1`

The error does not happen with accelerate `0.23.0`
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

Using the following example script

```python3
import torch
from torch.utils.data import Dataset, DataLoader
import numpy as np
from accelerate import Accelerator

class CustomDataset(Dataset):
    def __init__(self, data):
        self.data = data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        item = self.data[idx]
        return item


# Example data
data = np.random.randn(10, 5)  # 100 samples, 10 features each

# Convert to PyTorch tensors
data = torch.tensor(data, dtype=torch.float32)
from accelerate.utils import set_seed

accelerator = Accelerator()
dataset = CustomDataset(data)

# Create data loader
data_loader = DataLoader(dataset, batch_size=3, shuffle=True)
data_loader = accelerator.prepare(data_loader)
epochs = 2
for ep in range(2):
    for batch_idx, data in enumerate(data_loader):
        if accelerator.is_main_process:
            print(data)
    
    if accelerator.is_main_process:
        print("end batch")

```

Run the above in a distributed environment by
```bash
accelerate launch --main_process_port 9205 example.py
```

### Expected behavior

It will output something like this, suppose __we want different epochs have different order of batches, and different batches__

But now is "same batch order" and "same batches" for two epochs

```bash
tensor([[ 0.7063, -0.0190, -2.6028,  0.7356,  0.9286],
        [ 0.1154, -1.0464, -0.0675, -0.3442,  0.9731],
        [ 0.8266, -1.0352, -0.6741, -0.8682, -0.5972]], device='cuda:0')
tensor([[ 0.8992, -1.0027,  0.1585,  1.6470, -1.2425],
        [-0.3033,  0.3626, -0.8370,  0.0797,  0.5549],
        [-1.3101,  0.2919, -0.5106,  0.7952,  2.1747]], device='cuda:0')
end batch
tensor([[ 0.7063, -0.0190, -2.6028,  0.7356,  0.9286],
        [ 0.1154, -1.0464, -0.0675, -0.3442,  0.9731],
        [ 0.8266, -1.0352, -0.6741, -0.8682, -0.5972]], device='cuda:0')
tensor([[ 0.8992, -1.0027,  0.1585,  1.6470, -1.2425],
        [-0.3033,  0.3626, -0.8370,  0.0797,  0.5549],
        [-1.3101,  0.2919, -0.5106,  0.7952,  2.1747]], device='cuda:0')
end batch
```

Quick fixes that we tried:
1. the data sampler seems broken, we tried the following should work.
```python3
data_loader.batch_sampler.batch_sampler.sampler.set_epoch(ep)
```
2. We also tried 0.23.0 accelerate version also work
3. Or simply commented the following code also work
https://github.com/huggingface/accelerate/blob/0f2686c8d3e6d949c4b7efa15d7f2dee44f7ce91/src/accelerate/data_loader.py#L836-L846

**Comment by allanj** [comment]
I feel like it would be great to fix this quickly as it seems affect a lot of previous experiments that use the newer version of accelerate

**Comment by hyang0511** [comment]
I have the same issue with both 0.24.1 and 0.23.0.

**Comment by allanj** [comment]
I checked the master branch, the output seems fine. Does it mean the master branch fix it? (but may not be an elegant way

**Comment by muellerzr** [comment]
Thanks for the update! We’ll be pushing a new release next week that should include the fix. #2126

**Comment by allanj** [comment]
Yes. For now, I think I switch to 0.23.0, it seems they haven't fixed this issue to update the version.

**Comment by muellerzr** [comment]
Sorry for the delay on this, a release will be happening Friday with the fix included in it!
