### ISSUE TITLE
'Accelerator' object has no attribute 'deepspeed_engine_wrapped'

### ISSUE THREAD

**Issue by xxcheng0708** [huggingface/accelerate#2159]
![image](https://github.com/huggingface/accelerate/assets/33124611/10bb072b-ec17-46cb-8576-1a802cfcf9ef)

**Comment by Sdamuu** [comment]
do you fix this? i see same problem as well...

**Comment by xxcheng0708** [comment]
> do you fix this? i see same problem as well...

No, but I checked the data and found that it may be a problem with the deepspeed environment, which should be deepspeed not installed properly

**Comment by Sdamuu** [comment]
The version of deepspeed I am using is 0.12.2, and I am not using the accelerate mode of deepspeed....

**Comment by xxcheng0708** [comment]
check your ds_report results, Check the fused_adam status. I'm NO here,  I think the correct state should be True

**Comment by TuhinKundu** [comment]
Facing the same problem here too, anyone got a solution to this?

**Comment by we1k** [comment]
Facing the same problem, however, I figure out this error was caused by missng preparing the object `args` for deepspeed training setting.

Adding accelerator.prepare before training code works for me.

```python
# + model, optimizer, dataloader, lr_scheduler = accelerator.prepare(model, optimizer, dataloader, lr_scheduler)
for epoch in range(num_epochs):
		...YOUR_TRAINING_CODE...
```

**Comment by xxcheng0708** [comment]
It doesn't work for me because I've already done it

**Comment by xxcheng0708** [comment]
> Facing the same problem, however, I figure out this error was caused by missng preparing the object `args` for deepspeed training setting.
> 
> Adding accelerator.prepare before training code works for me.
> 
> ```python
> # + model, optimizer, dataloader, lr_scheduler = accelerator.prepare(model, optimizer, dataloader, lr_scheduler)
> for epoch in range(num_epochs):
>     ...YOUR_TRAINING_CODE...
> ```

Could you please check the execution result of ds_report command and share it

**Comment by Xiang-cd** [comment]
same issue

**Comment by muellerzr** [comment]
@Xiang-cd can you give us your code please?
