### ISSUE TITLE
Error when putting string or list into batch dict

### ISSUE THREAD

**Issue by anaivebird** [huggingface/accelerate#216]
def train_data_collator(data:list):
        inputs = [row["input"] for row in data]
        batch = encoder_tokenizer.prepare_seq2seq_batch(src_texts=inputs, max_length=256, padding='longest', truncation=True, return_tensors='pt')
        batch["nums"] = [row["nums"].split(';') for row in data]

        return batch

 File "/home/tiger/.local/lib/python3.7/site-packages/accelerate/utils.py", line 178, in recursively_apply
    f"Can't apply {func.__name__} on object of type {type(data)}, only of nested list/tuple/dicts of objects "
TypeError: Can't apply _send_to_device on object of type <class 'str'>, only of nested list/tuple/dicts of objects that satisfy _has_to_method.

Any way to put list of string in batch? Since we need it to do calculation in each batch.

**Comment by sgugger** [comment]
You shouldn't have that error on the main branch (and maybe the last release too but not quite sure). Could you check if:
- you have the latest version (v0.5.1)
- if the bug persists with a source install (`pip install git+https://github.com/huggingface/accelerate`)

**Comment by anaivebird** [comment]
The problem exists on v0.5.1 but fixed on master branch(source install)
