### ISSUE TITLE
It seems deepspeed activation checkpointing is not support in accelerate?

### ISSUE THREAD

**Issue by chenjianhuii** [huggingface/accelerate#2160]
I use the following setting in deepspeed config and launch with 

```
accelerate launch \
    --use_deepspeed \
    --deepspeed_config_file  my_deepspeed_config\
    ...
```

```
"activation_checkpointing": {
        "partition_activations": true,
        "cpu_checkpointing": true,
        "contiguous_memory_optimization": true,
        "number_checkpoints": 8,
        "synchronize_checkpoint_boundary": true,
        "profile": true
    }
```
But the GPU memory usage is the same as turning this off

**Comment by muellerzr** [comment]
cc @pacman100

**Comment by stas00** [comment]
Deepspeed's activation checkpointing has some superior features, so it'd be probably useful to explore:
https://deepspeed.readthedocs.io/en/latest/activation-checkpointing.html

The thing is you need to change the modeling code to replace the pytorch checkpointing code with deepspeed's one for this to work. So you don't need Accelerate to do that for you, you can just do it.

I wonder if some monkey patching could be used to keep the HF Transformers modeling code intact and replace `torch.utils.checkpoint` with `deepspeed.checkpointing.checkpoint`

**Comment by huyiwen** [comment]
Is there a tutorial for using DeepSpeed's activation checkpointing instead of PyTorch's?
