### ISSUE TITLE
Why the default value of dispatch_batches is False using IterableDataset in distributional training?

### ISSUE THREAD

**Issue by MarshtompCS** [huggingface/accelerate#2162]
I am wondering why the default value of dispatch_batches is False using IterableDataset in distributional training, and why use DataLoaderDispatcher rather than DataLoaderShard?

**Comment by MarshtompCS** [comment]
Using Dispatch dataloader will result in heavy CPU memory cost if we use many nodes for distributional training, no?

**Comment by MarshtompCS** [comment]
Maybe creating data in every local_rank=0 processes is better than creating all data from one host.

**Comment by muellerzr** [comment]
It shouldn't be, `prepare_dataloader` should know to grab and use `DataLoaderShard` if we have an iterable dataset. Can you provide a clean, concise example of where this isn't the case? I can point to the exact lines in `prepare_dataloader` that check and do this.

The way this works is we create 1/n of the data on each node instead, not the entire dataset. So one node has the entire dataset only, and the rest get chunks of processed data as it comes through the DataLoader

**Comment by MarshtompCS** [comment]
> It shouldn't be, `prepare_dataloader` should know to grab and use `DataLoaderShard` if we have an iterable dataset. Can you provide a clean, concise example of where this isn't the case? I can point to the exact lines in `prepare_dataloader` that check and do this.
> 
> The way this works is we create 1/n of the data on each node instead, not the entire dataset. So one node has the entire dataset only, and the rest get chunks of processed data as it comes through the DataLoader

The work flow of dispatch_batches:

1. dispatch_batches will be set to True if we use IterableDataset: [accelerator.py line 209](https://github.com/huggingface/accelerate/blob/427ef8bd009f25c5c1beabd25435266b2704caaf/src/accelerate/accelerator.py#L209)
2. prepare(), prepare_data_loader() use dispatch_baches: [accelerator.py line 1877](https://github.com/huggingface/accelerate/blob/427ef8bd009f25c5c1beabd25435266b2704caaf/src/accelerate/accelerator.py#L1877)
3. prepare_data_loader() return a DataLoaderDispatcher() dataloader: [data_loader.py line 902](https://github.com/huggingface/accelerate/blob/427ef8bd009f25c5c1beabd25435266b2704caaf/src/accelerate/data_loader.py#L902C35-L902C35)
4. In DataLoaderDispatcher, only process 0 construct data, and other proces will stop iteration: [data_loader.py line 591](https://github.com/huggingface/accelerate/blob/427ef8bd009f25c5c1beabd25435266b2704caaf/src/accelerate/data_loader.py#L591)

My question is if it is reasonable to let process-0 to create all data. If we use 16 hosts, the host-0 will be responsible for creating all 16 hosts' data, and dispach them to other hosts.

**Comment by muellerzr** [comment]
Yes, that is how the API is currently. (And thus, is reasonable so far from users). Changing that to be the local process is fairly straightforward and trivial. Would you like to test it out and see if that helps reduce your CPU load? Just replace `process_index` with `local_process_index`. We can then add a flag to the `Accelerator` with args on which to use.

**Comment by MarshtompCS** [comment]
of course! 
I think it will make difference if we use distributional trianing at scale, where the data processing and communication could be a bottleneck if we only use host-0 to process data. Increasing the num_workers may be a solution but results in a high CPU memory cost in host-0 -- that's why I want to implement local host data processing.

**Comment by muellerzr** [comment]
If it works for you, definitely feel free to open a PR please 🙏 However it's okay if you would like me to do so instead, it's probably about time we add a dataloader config to Accelerator anyways since there's so many parameters.

**Comment by JohnHerry** [comment]
> Yes, that is how the API is currently. (And thus, is reasonable so far from users). Changing that to be the local process is fairly straightforward and trivial. Would you like to test it out and see if that helps reduce your CPU load? Just replace `process_index` with `local_process_index`. We can then add a flag to the `Accelerator` with args on which to use.

How to set the dispatch_batches to False even I am using the IterableDataset?  I can not afford the memory to keep all samples padded to the max_lenght of the whole dataset,  but the data is too large so I should have to used IterableDataset.  currently I can not find the "dispatch_batches" param in Accelerator init param list.
