### ISSUE TITLE
trust_remote_code=True will load model even with accelerate.init_empty_weights

### ISSUE THREAD

**Issue by MingLiangDai** [huggingface/accelerate#2163]
### System Info

Hi,

I tried to use `accelerate.init_empty_weights` to instantiate a model that requires the keyword `trust_remote_code` to be set and it seems to load the model weights into memory when calling `.from_pretrained`

```
with init_empty_weights():
    # below line will load the model into memory
    model = transformers.AutoModelForCausalLM.from_pretrained('baichuan-inc/Baichuan-7B', config=config, trust_remote_code=True)
```

However, instantiating the model using `.from_config` will not load the model into memory.

```
config = transformers.AutoConfig.from_pretrained('baichuan-inc/Baichuan-7B', trust_remote_code=True)
with init_empty_weights():
    # below line will not load the model into memory
    model = transformers.AutoModelForCausalLM.from_config(config=config, trust_remote_code=True)
```

I initially thought that is just the behavior of `.from_config` but calling `.from_config` without `init_empty_weights` will in fact, interestingly enough, load the model into memory.

```
config = transformers.AutoConfig.from_pretrained('baichuan-inc/Baichuan-7B', trust_remote_code=True)
# below line will not load the model into memory
model = transformers.AutoModelForCausalLM.from_config(config=config, trust_remote_code=True)
```

So it appears that `accelerate.init_empty_weights` is working for `from_config` but not for `from_pretrained` for models that require `trust_remote_code=True`?

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

Try running 

```
import transformers
from accelerate import init_empty_weights

with init_empty_weights():
    # below line will load the model into memory
    model = transformers.AutoModelForCausalLM.from_pretrained('baichuan-inc/Baichuan-7B', config=config, trust_remote_code=True)
```
vs

```
import transformers
from accelerate import init_empty_weights

config = transformers.AutoConfig.from_pretrained('baichuan-inc/Baichuan-7B', trust_remote_code=True)
with init_empty_weights():
    # below line will not load the model into memory
    model = transformers.AutoModelForCausalLM.from_config(config=config, trust_remote_code=True)
```
vs

```
import transformers

config = transformers.AutoConfig.from_pretrained('baichuan-inc/Baichuan-7B', trust_remote_code=True)
# below line will not load the model into memory
model = transformers.AutoModelForCausalLM.from_config(config=config, trust_remote_code=True)
```

### Expected behavior

Expect both `from_pretrained` and `from_config` to not load model weights when using `accelerate.init_empty_weights()`

**Comment by MingLiangDai** [comment]
cc: @aarnphm

**Comment by SunMarc** [comment]
Hi @MingLiangDai, thanks for reporting this. This is linked to the fact that when using `from_pretrained` with a pytorch_model.bin file (file saved with pytorch), we need to get the state_dict somehow `state_dict= torch.load(checkpoint_file, map_location="cpu")` hence the memory used. However, at the end of the loading, the memory consumption should decrease back to its original value. To solve this issue, you can either switch to safetensors or use the from_config as you did !

**Comment by aarnphm** [comment]
Hi @SunMarc so this is I assume an expected behaviour?

**Comment by SunMarc** [comment]
Yes, this is expected @aarnphm . If you don't want to load the weights in the end, it is better to use `.from_config` !

**Comment by aarnphm** [comment]
Sounds good. Thanks for the information. @MingLiangDai I think this is now resolved.

**Comment by MingLiangDai** [comment]
Sounds good. Thanks @SunMarc @aarnphm!
