### ISSUE TITLE
how to get same timestamp in different subprocesses while using accelerate launch

### ISSUE THREAD

**Issue by shliu0** [huggingface/accelerate#2164]
I would like to get a unique timestamp to name my result folder like below 
```
def get_time_string() -> str:
    x = datetime.datetime.now()
    return f"{(x.year - 2000):02d}{x.month:02d}{x.day:02d}-{x.hour:02d}{x.minute:02d}{x.second:02d}"
```
, however, it sometimes will get a different timestamp in different subprocesses, is there anyway to get a unique timestamp?
Thanks very much for your time!

**Comment by BenjaminBossan** [comment]
Interesting problem. A rough solution would be to reduce the precision (drop the seconds) and hope that it matches up, but this is a brittle solution.

The better solution is probably to create the timestamp only on the main process and sync it across all processes. If it is converted into a unix timestamp, it could be synced as an int via PyTorch and then collected by `accelerator.reduce`.

Depending on your hardware setup, you could also write it to a file and read the file on all processes.

If you could explain why you need this timestamp in the first place, maybe we can even come up with a completely different idea.

Btw. using `x.strftime("%y%m%d-%H%M%S")` will get you the same string representation in a more concise way.

**Comment by shliu0** [comment]
> timestamp



> Interesting problem. A rough solution would be to reduce the precision (drop the seconds) and hope that it matches up, but this is a brittle solution.
> 
> The better solution is probably to create the timestamp only on the main process and sync it across all processes. If it is converted into a unix timestamp, it could be synced as an int via PyTorch and then collected by `accelerator.reduce`.
> 
> Depending on your hardware setup, you could also write it to a file and read the file on all processes.
> 
> If you could explain why you need this timestamp in the first place, maybe we can even come up with a completely different idea.
> 
> Btw. using `x.strftime("%y%m%d-%H%M%S")` will get you the same string representation in a more concise way.



> Interesting problem. A rough solution would be to reduce the precision (drop the seconds) and hope that it matches up, but this is a brittle solution.
> 
> The better solution is probably to create the timestamp only on the main process and sync it across all processes. If it is converted into a unix timestamp, it could be synced as an int via PyTorch and then collected by `accelerator.reduce`.
> 
> Depending on your hardware setup, you could also write it to a file and read the file on all processes.
> 
> If you could explain why you need this timestamp in the first place, maybe we can even come up with a completely different idea.
> 
> Btw. using `x.strftime("%y%m%d-%H%M%S")` will get you the same string representation in a more concise way.

Thanks for your answer!
I want to get the timestamp every time i run a train script, so that i can easily trace my diff experiments result according to the timestamp (e.g. save results in ./results/timestamp). You mentioned "create the timestamp only on the main process and sync it across all processes", this seems not work for my pipeline, cause i use `accelerate launch` in a bash script to execute my train.py, so every processes will run the same script(train.py) as the main process, right?
Btw, thanks for your concise representation, i will replace it later. : )

**Comment by BenjaminBossan** [comment]
Thanks for explaining the problem you want to solve. I think usually for this type of problem, people will create a folder not by timestamp, but by number of steps/iterations. Is that something you could do instead?

> cause i use `accelerate launch` in a bash script to execute my train.py, so every processes will run the same script(train.py) as the main process, right?

I don't know what your setup is, but normally, once process is the main process and the other ones are child processes.

**Comment by shliu0** [comment]
As the toy example below, 
```
# test_acc.py
import datetime
from accelerate import Accelerator
def get_time_string() -> str:
    x = datetime.datetime.now()
    return x.strftime("%y%m%d-%H%M%S")
def main():
    time_string = get_time_string()
    accelerator = Accelerator()
    print(time_string, accelerator.device)

if __name__ == "__main__":
    time_string = get_time_string()
    print(time_string)
    main()
```
I run it by `CUDA_VISIBLE_DEVICES="0,2" accelerate launch --config_file="./configs/acc_mgpu_config.yaml" test_acc.py`, then it outputs
```
231127-172429
231127-172430
231127-172430 cuda:1
231127-172429 cuda:0
```
so it seems that once the command line command is executed, each processes will run exactly same code in test_acc.py(even before Accelerator() is instanced)? I would like to know how to 
> create the timestamp only on the main process and sync it across all processes
in this case.

**Comment by BenjaminBossan** [comment]
I was thinking of something like this:

```python
# test_acc.py
import datetime
import torch
from accelerate import Accelerator

def get_timestamp() -> str:
    x = datetime.datetime.now()
    return int(x.timestamp())  # taking float should also work, gives more precision

def main():
    accelerator = Accelerator()
    accelerator.tic = torch.tensor([0])
    if accelerator.is_main_process:
        ts = get_timestamp()
        accelerator.tic = torch.tensor([ts])
        print(f"created timestamp {ts} on main process")

    t = accelerator.reduce(accelerator.tic)
    d = datetime.datetime.fromtimestamp(t[0].item()).strftime("%y%m%d-%H%M%S")
    print(f"{t}, {d}, {accelerator.process_index}")

if __name__ == "__main__":
    main()
```

When I call it, I get:

```
$ accelerate launch accel-issue-2164.py 
created timestamp 1701101229 on main process
tensor([1701101229]), 231127-160709, 0
tensor([1701101229]), 231127-160709, 1
```

There is probably an easier way, but that's the first thing that came to my mind.

**Comment by shliu0** [comment]
it helps, thanks so much!
