### ISSUE TITLE
ValueError: Query/Key/Value should either all have the same dtype,

### ISSUE THREAD

**Issue by khayamgondal** [huggingface/accelerate#2182]
`--enable_xformers_memory_efficient_attention` fails with the following error when run with accelerate
```
File "/anaconda/envs/diffusers-ikin/lib/python3.8/site-packages/xformers/ops/fmha/__init__.py", line 348, in _memory_efficient_attention_forward_requires_grad
    inp.validate_inputs()
  File "/anaconda/envs/diffusers-ikin/lib/python3.8/site-packages/xformers/ops/fmha/common.py", line 121, in validate_inputs
    raise ValueError(
ValueError: Query/Key/Value should either all have the same dtype, or (in the quantized case) Key/Value should have dtype torch.int32
  query.dtype: torch.float32
  key.dtype  : torch.float16
  value.dtype: torch.float16
Steps:   0%|                                           | 0/1000 [00:02<?, ?it/s]
[2023-11-25 14:03:17,898] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 5264) of binary: /anaconda/envs/diffusers-ikin/bin/python
Traceback (most recent call last):
  File "/anaconda/envs/diffusers-ikin/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/anaconda/envs/diffusers-ikin/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/anaconda/envs/diffusers-ikin/lib/python3.8/site-packages/accelerate/commands/launch.py", line 985, in launch_command
    multi_gpu_launcher(args)
  File "/anaconda/envs/diffusers-ikin/lib/python3.8/site-packages/accelerate/commands/launch.py", line 654, in multi_gpu_launcher
    distrib_run.run(args)
  File "/anaconda/envs/diffusers-ikin/lib/python3.8/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/anaconda/envs/diffusers-ikin/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/anaconda/envs/diffusers-ikin/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
diffusers/examples/dreambooth/train_dreambooth_lora_sdxl.py FAILED
```

I am running accelerate as following
```
accelerate launch diffusers/examples/dreambooth/train_dreambooth_lora_sdxl.py \
      --pretrained_model_name_or_path="stabilityai/stable-diffusion-xl-base-1.0" \
      --instance_data_dir={input_dir} \
      --output_dir={output_dir} \
      --instance_prompt=instance_prompt \
      --mixed_precision="fp16" \
      --resolution=1024 \
      --train_batch_size=1 \
      --gradient_accumulation_steps=4 \
      --learning_rate=1e-4 \
      --lr_scheduler="constant" \
      --lr_warmup_steps=0 \
      --checkpointing_steps=500 \
      --max_train_steps=1000 \
      --seed="0" \
      --checkpoints_total_limit=5 \
      --enable_xformers_memory_efficient_attention
```

```
Accelerate config
{
  "compute_environment": "LOCAL_MACHINE",
  "debug": false,
  "distributed_type": "MULTI_GPU",
  "downcast_bf16": false,
  "machine_rank": 0,
  "main_training_function": "main",
  "mixed_precision": "no",
  "num_machines": 1,
  "num_processes": 2,
  "rdzv_backend": "static",
  "same_network": false,
  "tpu_use_cluster": false,
  "tpu_use_sudo": false,
  "use_cpu": false
}
```

Versions:
```
xformers==0.0.23.dev687
accelerate==0.24.1
torch==2.1.0
torchvision==0.16.1
```

**Comment by SunMarc** [comment]
Thanks for reporting @khayamgondal, is it working without accelerate ? It looks like the query don't have the same dtype as the key and the value. I would suggest trying to find out why it is the case.

**Comment by khayamgondal** [comment]
If I run accelerate without `--enable_xformers_memory_efficient_attention` flag, training works fine. Llooks like somehow xformers upscales query vector to float32.

**Comment by sr5434** [comment]
+1

**Comment by SunMarc** [comment]
@sr5434 can you try without accelerate ? it doesn't seems to be an issue with accelerate since we don't modify the dtype. Maybe it is probably something in train_dreambooth_lora_sdxl.py that modifies the dtype. LMK how it goes !

**Comment by klopez89** [comment]
> If I run accelerate without `--enable_xformers_memory_efficient_attention` flag, training works fine. Looks like somehow xformers upscales query vector to float32.

this made all the difference. thank you!

**Comment by sr5434** [comment]
@klopez89 that seems more like a workaround though

**Comment by sr5434** [comment]
@SunMarc This is the source code: https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image_lora_sdxl.py
Also when I just use python the error stays the same

**Comment by SunMarc** [comment]
Thanks for clarifying @sr5434 ! This issue is not related to accelerate then. You should probably open an issue on diffusers repository. My guess is that xformers attention is not working as expected in the script.

**Comment by xiaohaipeng** [comment]
i think the problem is caused by xformers and pytorch used different cuda version to compile, xformers is compiled used cuda 11.8 or higher,but the cuda version  your pytorch compiled is 11.7 or lower.solution is to download xfomers source code and compile it in your environment

**Comment by sr5434** [comment]
@SunMarc I was able to fix the problem by disabling xformers

**Comment by billvsme** [comment]
+1

**Comment by JakobLS** [comment]
I get the same error when running the `train_text_to_image_lora_sdxl.py` script. I've made sure to align the CUDA version as suggestion above but no difference.

```bash
accelerate==0.26.1
torch==2.1.2+cu118
torchvision==0.16.2+cu118
xformers==0.0.23.post1+cu118
```

Can the same Dreambooth fixes be applied here as well?

**Comment by SunMarc** [comment]
Hi @JakobLS , can you try to build xformers from source ?

**Comment by JakobLS** [comment]
I'm running this in a cloud VM and it's freezing when I do that. Tried it twice - in my original and in a new I created. If I don't align the CUDA versions before, as I showed above, I get the following error:

```bash
  The detected CUDA version (11.8) mismatches the version that was used to compile
  PyTorch (12.1). Please make sure to use the same CUDA versions.
```

**Comment by SunMarc** [comment]
Hi @JakobLS , you need to either reinstall pytorch with the cu121. Or the you can the version of CUDA of your driver to 11.8

**Comment by JakobLS** [comment]
Hi @SunMarc, I might not be explaining myself properly. That's what I wanted to show with my [first comment](https://github.com/huggingface/accelerate/issues/2182#issuecomment-1900705096).

The VM comes installed with CUDA 11.8. 

- If I install a Pytorch version with CUDA 11.8 and run it _with no mixed precision it works fine_. If I run it with `mixed_precision="fp16"` I get the following error:

```bash
ValueError: Query/Key/Value should either all have the same dtype, or (in the quantized case) Key/Value should have dtype torch.int32
  query.dtype: torch.float32
  key.dtype  : torch.float16
  value.dtype: torch.float16
```

- Similarly if I install a Pytorch version with CUDA 12.1 and run it _with no mixed precision it also works fine_. But if I run it with `mixed_precision="fp16"` I get the exact same error.

It doesn't like when I run it with mixed precision so it looks like the issue might be there rather than in the CUDA version. I'd like to use mixed precision though due to the speed advantage.

**Comment by JakobLS** [comment]
Let me know if you want me to open a new issue for this btw.

**Comment by JakobLS** [comment]
@SunMarc, when I install from source, the installation automatically terminates and the terminal window shuts down. No xformers is being installed. Using the following script:

```bash
pip install ninja
pip install -v -U git+https://github.com/facebookresearch/xformers.git@main#egg=xformers
```

This is the installed Pytorch:

```bash
accelerate==0.26.1
torch==2.1.2+cu118
torchvision==0.16.2+cu118
```
and CUDA (checking with `nvcc --version`):

```bash
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```

**Comment by SunMarc** [comment]
This is indeed strange that you are not able to install from source. Let's try this then: pip3 install -U xformers --index-url https://download.pytorch.org/whl/cu118. You should get the 11.8 version this way.

**Comment by JakobLS** [comment]
That successfully installs xformers:

```bash
accelerate==0.26.1
torch==2.1.2+cu118
torchvision==0.16.2+cu118
xformers==0.0.23.post1+cu118
```

But when I now execute the script `train_text_to_image_lora_sdxl.py ` as shown [above](https://github.com/huggingface/accelerate/issues/2182#issuecomment-1900705096), I get the same error as OP:

```bash
ValueError: Query/Key/Value should either all have the same dtype, or (in the quantized case) Key/Value should have dtype torch.int32
  query.dtype: torch.float32
  key.dtype  : torch.float16
  value.dtype: torch.float16
```

**Comment by JakobLS** [comment]
If I run the script without `--enable_xformers_memory_efficient_attention` I instead get the following error:

```bash
ValueError: Attempting to unscale FP16 gradients.
```

**Comment by SunMarc** [comment]
`ValueError: Attempting to unscale FP16 gradients.` error means that the model is on fp16. See this [thread](https://github.com/huggingface/diffusers/issues/1246#issuecomment-1322220413) for more information. 

As for the other issue, it seems that compiling both pytorch and xformers with the same cuda version doesn't work. I will try to debug that.

**Comment by JakobLS** [comment]
Thanks for looking into it. I'll keep `--enable_xformers_memory_efficient_attention` enabled to reap its benefits though. 🙂

If it helps you, it's working if I **remove** mixed precision like this:

```bash
accelerate launch $SCRIPT_PATH \
  --enable_xformers_memory_efficient_attention \

  # Same as before
```

Still, I'd like to use `mixed_precision="fp16"` for the speed boost.

**Comment by faceslog** [comment]
Still the same issue thanks for the workaround @JakobLS

**Comment by GaParmar** [comment]
Has anyone found a fix to this? I still facing the same issues.

**Comment by JakobLS** [comment]
It's now some time ago and I'm not working on it anymore. But I think I "solved" it by using `mixed_precision="fp16"` over `xformers` instead since the latter seem to lead to clearer degradation in image quality which `fp16` doesn't. 

You could also try to update to later cuda, torch and xformers versions if you really want to use xformers (I think I tried that and got it to work).
