### ISSUE TITLE
smaller unet gives out of memory

### ISSUE THREAD

**Issue by makinyilmaz** [huggingface/accelerate#2185]
Hello,

I am training dreambooth model with the stable diffusion v1.5 pipeline. When I just initialize a random unet having much smaller number of channels (320, 640, 128, 1280 is the default and I changed to 32, 64, 128, 128), I get cuda out of memory error. When I tried training the same small model without accelerate, it works fine. What could be the reason for this ? 

Thank you a lot

**Comment by BenjaminBossan** [comment]
Hi, could you please provide the training script that you're using? Otherwise, it'll be very hard to figure out the issue.
