### ISSUE TITLE
NPU for get_max_memory 

### ISSUE THREAD

**Issue by jq460494839** [huggingface/accelerate#2186]
### System Info

```Shell
torch-npu 2.1.0
py39
```

### Reproduction

NPU not support accelerate/utils/modeling.py:get_max_memory() now. It cause the test case error that test_common_gpu.py:test_lora_causal_lm_mutli_gpu_inference from peft

torch_npu will add the interface torch.npu.mem_get_info() in 2.2.0, and will modify accelerate/utils/modeling.py at that time.

### Expected behavior

[test_common_gpu.py:test_lora_causal_lm_mutli_gpu_inference] pass

**Comment by statelesshz** [comment]
Hi @jq460494839 `torch.npu.mem_get_info` has been added to branch v2.1.0 of `torch_npu` :-) and npu  support for big model inference was recently merged, see https://github.com/huggingface/accelerate/pull/2222
