### ISSUE TITLE
how to collect outputs(not tensor dtype) on multi gpus 

### ISSUE THREAD

**Issue by shliu0** [huggingface/accelerate#2187]
As the toy example below, 

```
val_dataset = ['a', 'b', 'c', 'd', 'e']
val_dataloader = DataLoader(
        val_dataset, batch_size=2
    )
accelerator = Accelerator()
val_dataloader = accelerator.prepare(val_dataloader)
for step, batch in enumerate(val_dataloader):
    print(batch, accelerator.device)
```

When i run this script by `CUDA_VISIBLE_DEVICES="0,1" accelerate launch --config_file="./configs/acc_mgpu_config.yaml" test_batch.py` , i will get below results, how can I get ['a', 'b', 'c', 'd', 'e'] in main process after reduce batch in all processes? 
```
['a', 'b'] cuda:0
['e', 'a'] cuda:0
['c', 'd'] cuda:1
['b', 'c'] cuda:1
```

I know that accelerate have a `gather_for_metrics` can gathers input and potentially **drops duplicates** in the last batch if on a distributed system. But this function seems only works for data which is tensor type, in this example, my data is string, is there any way to achieve this?
(if i use `print(accelerator.gather_for_metrics((batch)), accelerator.device)`, it will raise error like below
```
TypeError: Unsupported types (<class 'str'>) passed to `_gpu_gather_one`. Only nested list/t
uple/dicts of objects that are valid for `is_torch_tensor` should be passed.
```
Thanks for any potential answers!

**Comment by geronimi73** [comment]
use ```gather()``` instead

here's my guess of what you are trying to do:
```python
from accelerate import Accelerator
from accelerate.utils import gather_object
from torch.utils.data import DataLoader

val_dataset = ['a', 'b', 'c', 'd', 'e']
val_dataloader = DataLoader(
        val_dataset, batch_size=2
    )
accelerator = Accelerator()
val_dataloader = accelerator.prepare(val_dataloader)

for step, batch in enumerate(val_dataloader):
    eval_results=[]
    for sample in batch:
        # do your eval
        eval_results.append( sample + "_processed" ) 
    print(batch, accelerator.device)

eval_results_gathered = gather_object(eval_results)

if accelerator.is_main_process:
    print(eval_results_gathered)

```

output
```
['a', 'b'] cuda:0
['c', 'd'] cuda:1
['e', 'a'] cuda:2
['a_processed', 'b_processed', 'c_processed', 'd_processed', 'e_processed', 'a_processed']
```

something like this. but for some reason sample 'a' is processed twice?

**Comment by shliu0** [comment]
yes, I would like to know if there is a method that will not processed 'a' twice

**Comment by shliu0** [comment]
got it! Thanks very much! : )
