### ISSUE TITLE
gather_object() changes the type of the input from dict to list

### ISSUE THREAD

**Issue by ShushanArakelyan** [huggingface/accelerate#2188]
### System Info

```Shell
- `Accelerate` version: 0.24.1
- Platform: Linux-5.4.0-162-generic-x86_64-with-glibc2.35
- Python version: 3.10.6
- Numpy version: 1.24.3
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 503.53 GB
- GPU type: NVIDIA RTX A6000
- `Accelerate` default config:
        Not found
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

I have a dictionary where I store a mapping of inputs->model predictions (I'm precomputing model outputs). I store inputs as strings, and outputs are numpy arrays. Both **keys** and **values** need to be gathered. After calling accelerate.utils.gather_object() on the dict, the returned object is a list (keys only), instead of the merged dictionary.

```
print(type(input_to_pred)) # dict
input_to_pred = accelerate.utils.gather_object(input_to_pred)
print(type(input_to_pred)) # list
```

### Expected behavior

Calling gather_object on a dictionary should return a dictionary, not a list.

**Comment by geronimi73** [comment]
wrap it in a list before ```gather()```

```python
input_to_pred = [ input_to_pred ] 

input_gathered = accelerate.utils.gather_object(input_to_pred)
```

```input_gathered``` will be a list of dicts
