### ISSUE TITLE
How does Model Parallel with transformer.trainer 

### ISSUE THREAD

**Issue by AliscaCL** [huggingface/accelerate#2189]
Currently, I am expecting to finetune or ptuning ChatGLM3 model with my own data. But there occure a problem. 
While I am load model with the parameter "device_map='auto'". The model has been divided into two parts to two GPU.
The inference step works well with this model parallel model. But while I am expect to finetune with transformers.trainer, an issues has been raised: 
You can't train a model that has been loaded with `device_map='auto'` in any distributed mode. Please rerun your script specifying '--num_process=1' or by launching with 'python {{myscript.py}}'. 

Is there any way to finetune a model that load with device_map='auto'?

```python
model = AutoModel.from_pretrained(model_name_or_path, trust_remote_code=True, device_map='auto')
trainer = Trainer(model=model, *args, **kwargs)
trainer.train()
```

**Comment by muellerzr** [comment]
No, there is not. You can use methods like `DeepSpeed` or FSDP which can cut the model across devices to limit the total memory used (which accelerate supports)
