### ISSUE TITLE
Difference between  accelerator.unwrap_model(model).generate and model.module.generate

### ISSUE THREAD

**Issue by anaivebird** [huggingface/accelerate#219]
Difference between `accelerator.unwrap_model(model).generate` and `model.module.generate` if we need generate when training?

**Comment by sgugger** [comment]
Please use the [forums](https://discuss.huggingface.co/) to ask questions like this, as we keep issues for bugs and feature requests only.

The short version is that the first will always work, the second will only work if you launch your script in a distributed fashion.

**Comment by anaivebird** [comment]
Thanks
