### ISSUE TITLE
DeepSpeed ignore_unused_parameters bug?

### ISSUE THREAD

**Issue by harshil-shah** [huggingface/accelerate#2194]
### System Info

```Shell
- `Accelerate` version: 0.23.0
- Platform: Linux-6.2.0-1016-azure-x86_64-with-glibc2.35
- Python version: 3.11.6
- Numpy version: 1.26.1
- PyTorch version (GPU?): 2.1.1+cu121 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 1771.73 GB
- GPU type: NVIDIA A100-SXM4-80GB
- `Accelerate` default config:
	- compute_environment: LOCAL_MACHINE
	- distributed_type: DEEPSPEED
	- mixed_precision: no
	- use_cpu: False
	- debug: False
	- num_processes: 8
	- machine_rank: 0
	- num_machines: 1
	- rdzv_backend: static
	- same_network: True
	- main_training_function: main
	- deepspeed_config: {'gradient_accumulation_steps': 1, 'offload_optimizer_device': 'none', 'offload_param_device': 'none', 'zero3_init_flag': False, 'zero_stage': 2}
	- downcast_bf16: no
	- tpu_use_cluster: False
	- tpu_use_sudo: False
	- tpu_env: []
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

When using DeepSpeed to train a model with some unused parameters, training hangs. Simple example below:

```python
import random

import torch
from accelerate import Accelerator
from torch import nn
from torch.utils.data import DataLoader, Dataset

IN_DIM = 32
OUT_DIM = 64

BATCH_SIZE = 4


class ModelA(nn.Module):
    def __init__(self, dim: int) -> None:
        super().__init__()
        self.layer = nn.Linear(dim, dim)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.layer(x)


class ModelB(nn.Module):
    def __init__(self, in_dim: int, out_dim: int) -> None:
        super().__init__()
        self.layer = nn.Linear(in_dim, out_dim)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.layer(x)


class Model(nn.Module):
    def __init__(self, model_a: ModelA, model_b: ModelB) -> None:
        super().__init__()
        self.model_a = model_a
        self.model_b = model_b

    def forward(self, x: torch.Tensor, use_model_a: bool) -> torch.Tensor:
        if use_model_a:
            x_a = self.model_a(x)
        else:
            x_a = x

        x_b = self.model_b(x_a)

        return x_b.sum()


def init_model(in_dim: int, out_dim: int) -> Model:
    model_a = ModelA(in_dim)
    model_b = ModelB(in_dim, out_dim)

    model = Model(model_a, model_b)

    return model


class MyDataset(Dataset):
    def __init__(self, dim: int) -> None:
        super().__init__()
        self.dim = dim

    def __len__(self) -> int:
        return 9999999999

    def __getitem__(self, index) -> torch.Tensor:
        x = torch.randn((self.dim,))

        return x


def collate_fn(batch: list[torch.Tensor]) -> tuple[torch.Tensor, bool]:
    x = torch.stack(batch)

    use_model_a = random.choice((True, False))

    return x, use_model_a


def main() -> None:
    accelerator = Accelerator()

    model = init_model(IN_DIM, OUT_DIM)
    optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

    dataset = MyDataset(IN_DIM)
    dataloader = DataLoader(dataset=dataset, batch_size=BATCH_SIZE, collate_fn=collate_fn)

    model, optimizer, dataloader = accelerator.prepare(model, optimizer, dataloader)

    iteration = 1

    for batch in dataloader:
        optimizer.zero_grad()

        x, use_model_a = batch

        print(f"{iteration = }")
        print(f"{use_model_a = }")

        loss = model(x, use_model_a)

        print(f"{loss = }")

        accelerator.backward(loss)
        optimizer.step()

        iteration += 1


if __name__ == "__main__":
    main()
```

This produces the following output (I launched with `accelerate launch accelerate_ds_bug.py`):

```
iteration = 1
use_model_a = True
loss = tensor(0.2562, device='cuda:1', grad_fn=<SumBackward0>)
loss = tensor(8.5453, device='cuda:5', grad_fn=<SumBackward0>)
loss = tensor(0.2873, device='cuda:3', grad_fn=<SumBackward0>)
loss = tensor(-0.5268, device='cuda:4', grad_fn=<SumBackward0>)
loss = tensor(4.4580, device='cuda:2', grad_fn=<SumBackward0>)
loss = tensor(0.8927, device='cuda:7', grad_fn=<SumBackward0>)
loss = tensor(-5.2301, device='cuda:6', grad_fn=<SumBackward0>)
loss = tensor(6.5631, device='cuda:0', grad_fn=<SumBackward0>)

```

At which point training hangs. This does not occur when not using DeepSpeed, as when instantiating the `Accelerator` I can pass in: `kwargs_handlers=[DistributedDataParallelKwargs(find_unused_parameters=True)]`.

This seems strange as DeepSpeed's default value for `ignore_unused_parameters` is `True` ([docs](https://deepspeed.readthedocs.io/en/latest/zero3.html#deepspeed.runtime.zero.config.DeepSpeedZeroConfig.ignore_unused_parameters)).

In my output I can also see the following, which includes `ignore_unused_parameters=True`:

```
[INFO] [config.py:964:print]   zero_config .................. stage=2 contiguous_gradients=True reduce_scatter=True reduce_bucket_size=500,000,000 allgather_partitions=True allgather_b
ucket_size=500,000,000 overlap_comm=False load_from_fp32_weights=True elastic_checkpoint=False offload_param=DeepSpeedZeroOffloadParamConfig(device='none', nvme_path=None, buffer_count=5, buffer_size=100,000,00
0, max_in_cpu=1,000,000,000, pin_memory=False) offload_optimizer=DeepSpeedZeroOffloadOptimizerConfig(device='none', nvme_path=None, buffer_count=4, pin_memory=False, pipeline=False, pipeline_read=False, pipelin
e_write=False, fast_init=False) sub_group_size=1,000,000,000 cpu_offload_param=None cpu_offload_use_pin_memory=None cpu_offload=None prefetch_bucket_size=50,000,000 param_persistence_threshold=100,000 model_per
sistence_threshold=sys.maxsize max_live_parameters=1,000,000,000 max_reuse_distance=1,000,000,000 gather_16bit_weights_on_model_save=False stage3_gather_fp16_weights_on_model_save=False ignore_unused_parameters
=True legacy_stage1=False round_robin_gradients=False zero_hpz_partition_size=1 zero_quantized_weights=False zero_quantized_gradients=False mics_shard_size=-1 mics_hierarchical_params_gather=False memory_effici
ent_linear=True pipeline_loading_checkpoint=False override_module_apply=True
```

Any help would be much appreciated.

### Expected behavior

Training doesn't hang when using DeepSpeed with unused parameters.

**Comment by SunMarc** [comment]
cc @pacman100. I can submit a quick PR to add the attribute + test on a example if you would like.

**Comment by pacman100** [comment]
The issue is different processes having different flags. 

DDP has full copy per GPU and as such can neglect the parts not being used . However, in DeepSpeed as the parameters are sharded, they need to be gathered by all processes for a given forward call of module. If process one has `use_model_a` as True but process 2 has that as False, process 2 will never certificate in gathering of model a parameters and as such process 0 will hang indefinitely waiting for the remaining sharded parameters from other processes. To fix this, have only process 0 generate the `use_model_a` flag and communicate that with all the other processes so that all processes get the same value and hence are in sync wrt which module parameters to gather. 

![Screenshot 2023-11-29 at 12 37 22 PM](https://github.com/huggingface/accelerate/assets/13534540/a729bd53-41f4-424e-89ec-704f8b022112)

**Comment by pacman100** [comment]
> cc @pacman100. I can submit a quick PR to add the attribute + test on a example if you would like.

Thank you @SunMarc but this issue is incorrect usage rather than integration support.

**Comment by harshil-shah** [comment]
> If process one has use_model_a as True but process 2 has that as False, process 2 will never paticipate in gathering of model a parameters and as such process 0 will hang indefinitely waiting for the remaining sharded parameters from other processes.

This makes sense, but this was just a toy example. If, for example, we are training a multi-modal model (images and text) but a batch on one of the processes consists of text-only examples, then the image model won't be called for that batch.

So effectively we can't have the `use_model_a` flag be the same on all processes.

**Comment by pacman100** [comment]
I don't see a solution for this other than alternating batches wherein each batch is either text only, image only or text+image inputs. I also skimmed through https://github.com/microsoft/DeepSpeedExamples/tree/master/applications/DeepSpeed-VisualChat but they seem to have (image,text) for each sample.

**Comment by Mizar77** [comment]
@pacman100 hi, I also encountered a similar issue. Has this problem been resolved now?

**Comment by Pengjie-W** [comment]
hi, I also encountered a similar issue. Has this problem been resolved now?
