### ISSUE TITLE
Attribute name conflicts in AcceleratedOptimizer

### ISSUE THREAD

**Issue by yuxinyuan** [huggingface/accelerate#220]
I notice that `AcceleratedOptimizer` uses attribute name `state` to store a reference to `AcceleratorState`. However, pytorch's `Optimizer` class also has a `state` attribute. (Links are pasted below)

https://github.com/huggingface/accelerate/blob/18e5a56cbbca9c6a344853b5dce7675e2c5798ea/src/accelerate/optimizer.py#L56

https://github.com/pytorch/pytorch/blob/fb78a31916d471ebdfb0466dc53446f27f4f41b2/torch/optim/optimizer.py#L44

Since `AcceleratedOptimizer` should only serve as a thin wrapper for `Optimizer`, I think the `state` attribute of `AcceleratedOptimizer`  should be renamed.

**Comment by sgugger** [comment]
Good point. I won't have time to work on this today and am leaving on vacation, but will do something about this the week I'm back!

Or if you want to open a PR, we could rename this attribute to `accelerator_state` and then have a property that returns the inner optimizer state when a user tries to access the state attribute.
