### ISSUE TITLE
How can I set N GPUs but only using M GPUs

### ISSUE THREAD

**Issue by zyh3826** [huggingface/accelerate#2201]
On my machine I have 8 GPUs, but I only want to use 7 of them, the last one I will save some parameters during training, how can I do this? I tried setting `num_processes=8` and `gpu_ids=0,1,2,3,4,5,6` will raise `RuntimeError: CUDA error: invalid device ordinal`.
I set `num_processes=7` and `param.to('cuda:7')` will also raise `RuntimeError: CUDA error: invalid device ordinal`

do there have some ways to solve this? thanks

**Comment by SunMarc** [comment]
Hi @zyh3826 thanks for reporting. Does this happens when you are trying to only use 2 GPUs ?

**Comment by muellerzr** [comment]
iirc we don't support this/can't because `torch.distributed` needs to know how many processes to spawn, and that sets how many GPUs to use. As a result, accelerate uses all available GPUs when starting the distributed process. 

You might be able to do something like so with this modification:

```python
from dataclasses import dataclass
from accelerate.utils import KwargsHandler
from typing import Optional
from datetime import timedelta
from torch import tensor

@dataclass
class InitProcessGroupKwargs(KwargsHandler):
    backend: Optional[str] = "nccl"
    init_method: Optional[str] = None
    timeout: timedelta = timedelta(seconds=1800)
    world_size=-1

kwargs = [InitPorcessGroupKwargs(world_size=7)]
accelerator = Accelerator(kwargs=kwargs)

t = tensor([1,2,3])
t.to("cuda:7")
```

Let me know if that works.

**Comment by zyh3826** [comment]
> Hi @zyh3826 thanks for reporting. Does this happens when you are trying to only use 2 GPUs ?

the answer is no, I tried 2, 3, 4, 5, 6, 7, 8 GPUs

**Comment by zyh3826** [comment]
> iirc we don't support this currently because `torch.distributed` needs to know how many processes to spawn, and that sets how many GPUs to use. As a result, accelerate uses all available GPUs when starting the distributed process.
> 
> You might be able to do something like so with this modification:
> 
> ```python
> from dataclasses import dataclass
> from accelerate.utils import KwargsHandler
> from typing import Optional
> from datetime import timedelta
> from torch import tensor
> 
> @dataclass
> class InitProcessGroupKwargs(KwargsHandler):
>     backend: Optional[str] = "nccl"
>     init_method: Optional[str] = None
>     timeout: timedelta = timedelta(seconds=1800)
>     world_size=-1
> 
> kwargs = [InitPorcessGroupKwargs(world_size=7)]
> accelerator = Accelerator(kwargs=kwargs)
> 
> t = tensor([1,2,3])
> t.to("cuda:7")
> ```
> 
> Let me know if that works and we can expose that level of the API

@muellerzr sorry for reply later, I tried your scripts, modify it like this:
```python
from dataclasses import dataclass
from accelerate.utils import KwargsHandler
from typing import Optional
from datetime import timedelta
from torch import tensor
from accelerate import Accelerator
import time
import subprocess as sp


def get_gpu_memory():
    command = "nvidia-smi --query-gpu=memory.free --format=csv"
    memory_free_info = sp.check_output(command.split()).decode('ascii').split('\n')[:-1][1:]
    memory_free_values = {i: int(x.split()[0]) for i, x in enumerate(memory_free_info)}
    return memory_free_values


@dataclass
class InitProcessGroupKwargs(KwargsHandler):
    backend: Optional[str] = "nccl"
    init_method: Optional[str] = None
    timeout: timedelta = timedelta(seconds=1800)
    world_size: int = -1

kwargs = [InitProcessGroupKwargs(world_size=7)]
accelerator = Accelerator(*kwargs)

print(get_gpu_memory())
time.sleep(5)
t = tensor([1,2,3])
t.to("cuda:7")
time.sleep(5)
print('=' * 50)
print(get_gpu_memory())
```
it worked, but I don't know if I load a model on 0 1 2 3 4 5 6 and then load some parameters to GPU 7, can this still work
