### ISSUE TITLE
How can I freeze part of the tensor?

### ISSUE THREAD

**Issue by Yangr116** [huggingface/accelerate#2202]
Hi, how can I freeze part of the tensor while using Accelerate?
For example:
I have a tensor with a shape of ```[b, c, m+10]```. I would like to freeze ```[b, c, m]``` and train ```[b, c, m:]``` only.
How could I achieve it, can you help me?

**Comment by BenjaminBossan** [comment]
I don't think that's possible in PyTorch, a tensor either has `requires_grad=True` or `False`. You probably need to split the tensor in two.

**Comment by muellerzr** [comment]
The right way to do this would be something like registering a hook instead which updates the grads and freezes them etc. https://discuss.pytorch.org/t/freezing-a-part-of-the-tensor/89720

**Comment by muellerzr** [comment]
However this is also a torch question, so please migrate it to the [forums](https://discuss.huggingface.co/) as it's not directly related to Accelerate in this instance.

**Comment by Yangr116** [comment]
Thanks, I will try it.

> The right way to do this would be something like registering a hook instead which updates the grads and freezes them etc. https://discuss.pytorch.org/t/freezing-a-part-of-the-tensor/89720

**Comment by Yangr116** [comment]
> I don't think that's possible in PyTorch, a tensor either has `requires_grad=True` or `False`. You probably need to split the tensor in two.

I want to expand the tokenizer and training embeddings of new tokens. Splitting the tensor in two may not be possible.
