### ISSUE TITLE
data_loader fail when batch_sampler is None

### ISSUE THREAD

**Issue by PPWangyc** [huggingface/accelerate#2205]
### System Info
Name: accelerate
Version: 0.24.1
Summary: Accelerate
Home-page: https://github.com/huggingface/accelerate
Author: The HuggingFace team
Author-email: sylvain@huggingface.co
License: Apache
Location: /home/ppwang/miniconda3/envs/mindeye/lib/python3.10/site-packages
Requires: huggingface-hub, numpy, packaging, psutil, pyyaml, torch
Required-by: dalle2-pytorch

  File "/home/ppwang/miniconda3/envs/mindeye/lib/python3.10/site-packages/accelerate/data_loader.py", line 630, in __iter__
    self.set_epoch(self.iteration)
  File "/home/ppwang/miniconda3/envs/mindeye/lib/python3.10/site-packages/accelerate/data_loader.py", line 707, in set_epoch
    if hasattr(self.batch_sampler.sampler, "set_epoch"):
AttributeError: 'NoneType' object has no attribute 'sampler'

def set_epoch(self, epoch: int):
        # In case it is manually passed in, the user can set it to what they like
        if self.iteration != epoch:
            self.iteration = epoch
        if hasattr(self.batch_sampler.sampler, "set_epoch"):
            self.batch_sampler.sampler.set_epoch(epoch)
        if hasattr(self.dataset, "set_epoch"):
            self.dataset.set_epoch(epoch)

When batch_sampler is None, it fails

Hope it supports when batch_sampler is None

**Comment by Boltzmachine** [comment]
How do you resolve it?
