### ISSUE TITLE
Accelerators hang at the end of a single epoch

### ISSUE THREAD

**Issue by zheyuye** [huggingface/accelerate#221]
I was using a DataLoader with `torch.utils.data.IterableDataset`, the training progress always hang at the end of a single epoch. 

Same error happens using infinite dataloader

**Comment by jaketae** [comment]
Hey @zheyuye, can you provide a minimal reproducible example (script or Colab notebook) that demonstrates the error?

**Comment by zheyuye** [comment]
It seems that this error was caused by my own customized `IterableDatase`t not supporting multi-gpus distribution. 
I'm closing this issue.
