### ISSUE TITLE
Following the Accelerate documentation, but only one GPU is used

### ISSUE THREAD

**Issue by nickjtay** [huggingface/accelerate#2215]
I started with the LoRA example from the list of Transformers examples (I replaced the model with flan-t5-small for testing on my machine). Next I followed the examples and documentation provided in the Accelerate library to ensure both of my CUDA GPUs were utilized. I checked nvidia-smi, and I can confirm that the model is still training on a single GPU. Is there something in the documentation missing?

I've attached my code here:
[LoRA-multi-gpu.zip](https://github.com/huggingface/accelerate/files/13553643/LoRA-multi-gpu.zip)

**Comment by muellerzr** [comment]
What command are you using to launch your job? What is the output of `accelerate env`

**Comment by nickjtay** [comment]
I'm executing a jupyter notebook with the same code.

- `Accelerate` version: 0.15.0
- Platform: Linux-6.2.0-37-generic-x86_64-with-glibc2.35
- Python version: 3.10.12
- Numpy version: 1.24.2
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- `Accelerate` default config:
	Not found

**Comment by muellerzr** [comment]
You’re not using the notebook launcher, this is expected. https://huggingface.co/docs/accelerate/basic_tutorials/notebook

**Comment by nickjtay** [comment]
Thank you, I missed this entirely.
