### ISSUE TITLE
Accelerate Error 

### ISSUE THREAD

**Issue by nickjtay** [huggingface/accelerate#2216]
My notebook was working and then stopped working when I duplicated my notebook to test out a small revision that required bitsandbytes. I installed bitsandbytes to the same virtual environment, which I wouldn't expect to cause any issues. I went back to the original notebook and it no longer ran successfully. I'm now getting the error below. I have since uninstalled bitsandbytes and restarted the kernel. I'm not sure what happened and I cannot track down someone experiencing this issue on stackoverflow or elsewhere.

[LoRA-multi-gpu-working.zip](https://github.com/huggingface/accelerate/files/13556484/LoRA-multi-gpu-working.zip)

Error:
```
---------------------------------------------------------------------------
ProcessRaisedException                    Traceback (most recent call last)
File ~/Projects/llmtest1/lib/python3.10/site-packages/accelerate/launchers.py:186, in notebook_launcher(function, args, num_processes, mixed_precision, use_port, master_addr, node_rank, num_nodes)
    185 try:
--> 186     start_processes(launcher, args=args, nprocs=num_processes, start_method="fork")
    187 except ProcessRaisedException as e:

File ~/Projects/llmtest1/lib/python3.10/site-packages/torch/multiprocessing/spawn.py:202, in start_processes(fn, args, nprocs, join, daemon, start_method)
    201 # Loop on join until it returns True or raises an exception.
--> 202 while not context.join():
    203     pass

File ~/Projects/llmtest1/lib/python3.10/site-packages/torch/multiprocessing/spawn.py:163, in ProcessContext.join(self, timeout)
    162 msg += original_trace
--> 163 raise ProcessRaisedException(msg, error_index, failed_process.pid)

ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/nickjtay/Projects/llmtest1/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 74, in _wrap
    fn(i, *args)
  File "/home/nickjtay/Projects/llmtest1/lib/python3.10/site-packages/accelerate/utils/launch.py", line 562, in __call__
    self.launcher(*args)
  File "/tmp/ipykernel_5874/1694138925.py", line 8, in training_loop
    accelerator = Accelerator(mixed_precision=mixed_precision)
  File "/home/nickjtay/Projects/llmtest1/lib/python3.10/site-packages/accelerate/accelerator.py", line 371, in __init__
    self.state = AcceleratorState(
  File "/home/nickjtay/Projects/llmtest1/lib/python3.10/site-packages/accelerate/state.py", line 758, in __init__
    PartialState(cpu, **kwargs)
  File "/home/nickjtay/Projects/llmtest1/lib/python3.10/site-packages/accelerate/state.py", line 218, in __init__
    if not check_cuda_p2p_ib_support():
  File "/home/nickjtay/Projects/llmtest1/lib/python3.10/site-packages/accelerate/utils/environment.py", line 71, in check_cuda_p2p_ib_support
    device_name = torch.cuda.get_device_name()
  File "/home/nickjtay/Projects/llmtest1/lib/python3.10/site-packages/torch/cuda/__init__.py", line 419, in get_device_name
    return get_device_properties(device).name
  File "/home/nickjtay/Projects/llmtest1/lib/python3.10/site-packages/torch/cuda/__init__.py", line 449, in get_device_properties
    _lazy_init()  # will define _get_device_properties
  File "/home/nickjtay/Projects/llmtest1/lib/python3.10/site-packages/torch/cuda/__init__.py", line 284, in _lazy_init
    raise RuntimeError(
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method


The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
Cell In[3], line 2
      1 args = ("fp16", 42, 64)
----> 2 notebook_launcher(training_loop, args, num_processes=2)

File ~/Projects/llmtest1/lib/python3.10/site-packages/accelerate/launchers.py:189, in notebook_launcher(function, args, num_processes, mixed_precision, use_port, master_addr, node_rank, num_nodes)
    187 except ProcessRaisedException as e:
    188     if "Cannot re-initialize CUDA in forked subprocess" in e.args[0]:
--> 189         raise RuntimeError(
    190             "CUDA has been initialized before the `notebook_launcher` could create a forked subprocess. "
    191             "This likely stems from an outside import causing issues once the `notebook_launcher()` is called. "
    192             "Please review your imports and test them when running the `notebook_launcher()` to identify "
    193             "which one is problematic and causing CUDA to be initialized."
    194         ) from e
    195     else:
    196         raise RuntimeError(f"An issue was found when launching the training: {e}") from e

RuntimeError: CUDA has been initialized before the `notebook_launcher` could create a forked subprocess. This likely stems from an outside import causing issues once the `notebook_launcher()` is called. Please review your imports and test them when running the `notebook_launcher()` to identify which one is problematic and causing CUDA to be initialized.
```

**Comment by muellerzr** [comment]
Again, please state info about your env as I asked in the other issue. 

Bits and bytes and other libraries similar will init CUDA on import. You need to hide this import inside your training function so it gets imported after you’ve launched your notebook launcher. Later versions of accelerate will warn if this happens

**Comment by nickjtay** [comment]
Thank you, that makes sense, but I had removed bitsandbytes and rebooted. Not sure why it says there is no default config, because I walked through the config wizard and successfully had accelerate working.

Copy-and-paste the text below in your GitHub issue

- `Accelerate` version: 0.25.0
- Platform: Linux-6.2.0-37-generic-x86_64-with-glibc2.35
- Python version: 3.10.12
- Numpy version: 1.24.2
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 62.69 GB
- GPU type: NVIDIA GeForce RTX 3060
- `Accelerate` default config:
	Not found

**Comment by nickjtay** [comment]
I reconfigured accelerate, but I'm still getting the same error.

- `Accelerate` version: 0.25.0
- Platform: Linux-6.2.0-37-generic-x86_64-with-glibc2.35
- Python version: 3.10.12
- Numpy version: 1.24.2
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 62.69 GB
- GPU type: NVIDIA GeForce RTX 3060
- `Accelerate` default config:
	- compute_environment: LOCAL_MACHINE
	- distributed_type: MULTI_GPU
	- mixed_precision: fp8
	- use_cpu: False
	- debug: True
	- num_processes: 2
	- machine_rank: 0
	- num_machines: 1
	- gpu_ids: 0,1
	- rdzv_backend: static
	- same_network: True
	- main_training_function: main
	- downcast_bf16: no
	- tpu_use_cluster: False
	- tpu_use_sudo: False
	- tpu_env: []

**Comment by muellerzr** [comment]
Can you try installing from accelerate main? `pip install git+https://github.com/huggingface/accelerate`

**Comment by nickjtay** [comment]
Still experiencing the error. I rebooted as well. I'm also not running any other notebooks or processes which would use CUDA. I don't see anything in the code that would call initialize CUDA before the `notebook_launcher()` function runs, either.

- `Accelerate` version: 0.25.0.dev0
- Platform: Linux-6.2.0-37-generic-x86_64-with-glibc2.35
- Python version: 3.10.12
- Numpy version: 1.24.2
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 62.69 GB
- GPU type: NVIDIA GeForce RTX 3060
- `Accelerate` default config:
	- compute_environment: LOCAL_MACHINE
	- distributed_type: MULTI_GPU
	- mixed_precision: fp8
	- use_cpu: False
	- debug: True
	- num_processes: 2
	- machine_rank: 0
	- num_machines: 1
	- gpu_ids: 0,1
	- rdzv_backend: static
	- same_network: True
	- main_training_function: main
	- downcast_bf16: no
	- tpu_use_cluster: False
	- tpu_use_sudo: False
	- tpu_env: []

**Comment by geronimi73** [comment]
> RuntimeError: CUDA has been initialized before the `notebook_launcher` could create a forked subprocess. This likely stems from an outside import causing issues once the `notebook_launcher()` is called. Please review your imports and test them when running the `notebook_launcher()` to identify which one is problematic and causing CUDA to be initialized.

```from accelerate import Accelerator``` initializes CUDA, you have to move it into ```training_loop```. 
If the error persists, move all the other imports except ```from accelerate import notebook_launcher``` too

**Comment by muellerzr** [comment]
> from accelerate import Accelerator initializes CUDA, you have to move it into training_loop.

That shouldn't be the case/shouldn't be happening 👀 

I ran this locally just fine, can you give me the output from `pip freeze` @geronimi73?

As all the imports in Accelerate are very cuda-careful for this exact reason

**Comment by geronimi73** [comment]
nevermind! 

> from accelerate import Accelerator initializes CUDA, you have to move it into training_loop.

this was definitely the case with accelerate-0.21.0. after a pip update to accelerate-0.25.0: gone. 

sorry for the distraction

**Comment by BenjaminBossan** [comment]
Yes, we should revisit this in PEFT!

**Comment by BenjaminBossan** [comment]
> Should I be moving peft to the loop as well?

Yes, please test that as well and let us know if it solves the problem.

**Comment by nickjtay** [comment]
Nevermind, I see, moving both modules into the loop solved it. Thank you!
