### ISSUE TITLE
Can we prepare multiple models with accelerate?

### ISSUE THREAD

**Issue by pminervini** [huggingface/accelerate#222]
`amp.initialize` supports multiple models and optimizers: https://nvidia.github.io/apex/advanced.html#initialization-with-multiple-models-optimizers

Can we do the same with `accelerate`?

**Comment by sgugger** [comment]
Please use the [forums](https://discuss.huggingface.co/) to ask questions like this as we keep issues for bugs and feature requests only.
And the answer is yes.
