### ISSUE TITLE
split_between_processes support for Datasets

### ISSUE THREAD

**Issue by conceptofmind** [huggingface/accelerate#2220]
### System Info

```Shell
python 3.10
pytorch 2.1
cuda 12.1
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

This does not work:
```python
dataset = load_dataset(
    "wikitext",
    "wikitext-2-v1",
    split="train",
)

print(len(dataset)) # 36718

# Assume 8 processes

with accelerator.split_between_processes(dataset) as data:
    print(len(data)) # 36718
    
   for out in pipe(
        KeyDataset(data, "text"), 
    ):
        continue
```
This works:
```python
dataset = load_dataset(
    "wikitext",
    "wikitext-2-v1",
    split="train",
)
print(len(dataset))

# Assume 8 processes

with accelerator.split_between_processes(dataset["text"]) as data:
    print(len(data))
```
Moving from: https://github.com/huggingface/transformers/issues/27838

### Expected behavior

I am unsure if this is intended behavior or not. A dataset consisting of the lists or input id tensors is split correctly. The dictionary provided from datasets will not be split.

Maybe this is more of a feature request?

Where the dataset could be split across all 8 processes to be used with the transformers feature extraction pipeline for inference.

**Comment by muellerzr** [comment]
This would indeed be a feature request. Simply because a `Dataset` is not actually a dict:

```python
from datasets import load_dataset

dataset = load_dataset(
    "wikitext",
    "wikitext-2-v1",
    split="train",
)
isinstance(dataset, dict)
# Returns False
```

**Comment by conceptofmind** [comment]
> This would indeed be a feature request. Simply because a `Dataset` is not actually a dict:
> 
> ```python
> from datasets import load_dataset
> 
> dataset = load_dataset(
>     "wikitext",
>     "wikitext-2-v1",
>     split="train",
> )
> isinstance(dataset, dict)
> # Returns False
> ```

Thanks for the response.

I should have been more explicit about what I had meant in relation to the returned dictionaries from datasets. I do understand that they are not dictionaries directly.

**Comment by muellerzr** [comment]
Agreed, I'm saying this is why it's failing, we look for this :)

**Comment by conceptofmind** [comment]
> Agreed, I'm saying this is why it's failing, we look for this :)

Ah. I understand now.

I appreciate you taking a look into this feature request. I think it would be a valuable feature to be able to partition datasets across devices directly for inference.

Thank you again,

Enrico

**Comment by geronimi73** [comment]
> Waitting this feature !!!

alternatively you could split the dataset indices between the processes instead

```python
from datasets import load_dataset
from accelerate import Accelerator

dataset = load_dataset(
    "wikitext",
    "wikitext-2-v1",
    split="train",
)

accelerator = Accelerator()

accelerator.print(f"total {len(dataset)} entries") 

with accelerator.split_between_processes(list(range(len(dataset)))) as dataset_idcs:
	my_dataset=dataset.select(dataset_idcs)

	print(f"GPU{accelerator.process_index} working on {len(my_dataset)} entries")

	# do some work!    
```
