### ISSUE TITLE
ValueError: The port number of the rendezvous endpoint 'None:None'

### ISSUE THREAD

**Issue by akkasi** [huggingface/accelerate#2240]
### System Info

```Shell
accelerate version: 0.24.0
python version 3.10
Os: mint
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

I am trying to run my code on a HPC with 2 nodes and 4 GPUs for each with slurm configuration.  The code works fine with only 1 node, but using more than 1 node with the following command I am getting an error:
`accelerate launch --num_processes 8 --num_machines 2 --machine_rank 0 --mixed_precision 'no' --gpu_ids '0,1,2,3' --same_network 'true' --main_process_ip '206.12.124.2' --main_process_port 63333  --rdzv_backend 'static' mainScript.py $model $data Evaluation_FullFineTuning.tsv`

and the error I get is:

`ValueError: The port number of the rendezvous endpoint 'None:None' must be an integer between 0 and 65536.
`

### Expected behavior

I expect to get the code working.

**Comment by akkasi** [comment]
@muellerzr

**Comment by muellerzr** [comment]
Your issue is `--same_network` is a `store_true` flag, so it should only be passed, not with a value to set it. Try:

```bash
accelerate launch --num_processes 8 --num_machines 2 --machine_rank 0 --mixed_precision 'no' --gpu_ids '0,1,2,3' --same_network --main_process_ip '206.12.124.2' --main_process_port 63333  --rdzv_backend 'static' mainScript.py $model $data Evaluation_FullFineTuning.tsv
```

**Comment by muellerzr** [comment]
I'll try to see if it's possible for us to catch cases like this.
