### ISSUE TITLE
Multiple node failed.

### ISSUE THREAD

**Issue by tingxueronghua** [huggingface/accelerate#2245]
The code writing with accelerate could run on a single machine. But failed for multiple node

I notice that there is a quite strange network error:

```
9.91.4.251: [W socket.cpp:601] [c10d] The IPv6 network addresses of (/root/cuda11.8.bashrc, 45458) cannot be retrieved (gai error: -3 - Temporary failure in name resolution).
```

Have no idea why the IP address is so strange. Does any one notice the same problem before?

I have updated accelerate to the newest version.

**Comment by muellerzr** [comment]
Please go through the questionairre that should have been presented to you when filing a bug report. There is nothing we can do without seeing:

1. Your code (or a minimal example of it)
2. The output of `accelerate env`

**Comment by tingxueronghua** [comment]
Sorry for the confusion I caused. I will close this issue and open another meaningful one.
