### ISSUE TITLE
`test_trigger()` fails when running `accelerate test` on TPU v3-8

### ISSUE THREAD

**Issue by vanbasten23** [huggingface/accelerate#2247]
### System Info

```Shell
accelerate version: HEAD
OS: debian
python version: py 3.8
torch: nightly (11/13/2023)
accelerate config:

compute_environment: LOCAL_MACHINE
distributed_type: TPU
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: 'no'
num_machines: 1
num_processes: 4
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

In short, when I run `accelerate test` on my TPU v3-8, it fails with error: [full output]( https://gist.github.com/vanbasten23/efda86202a2e8ff6da83bf5ce1c9eac7)
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/local/lib/python3.8/concurrent/futures/process.py", line 198, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/usr/local/lib/python3.8/concurrent/futures/process.py", line 198, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/ansible/.venv/lib/python3.8/site-packages/torch_xla/runtime.py", line 87, in wrapper
    return fn(*args, **kwargs)
  File "/ansible/.venv/lib/python3.8/site-packages/torch_xla/_internal/pjrt.py", line 77, in _run_thread_per_device
    replica_results = list(
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/ansible/.venv/lib/python3.8/site-packages/torch_xla/_internal/pjrt.py", line 70, in _thread_fn
    return fn()
  File "/ansible/.venv/lib/python3.8/site-packages/torch_xla/_internal/pjrt.py", line 176, in __call__
    self.fn(runtime.global_ordinal(), *self.args, **self.kwargs)
  File "/root/accelerate/src/accelerate/utils/launch.py", line 562, in __call__
    self.launcher(*args)
  File "/root/accelerate/src/accelerate/test_utils/scripts/test_script.py", line 668, in main
    test_trigger()
  File "/root/accelerate/src/accelerate/test_utils/scripts/test_script.py", line 610, in test_trigger
    assert accelerator.check_trigger() is True
AssertionError
```

Moreover, I added a `print('xw32 checking flag_tensor')` right before this [line](https://github.com/huggingface/accelerate/blob/eafcea07f639a5476385854ea9bccdbba467db9d/src/accelerate/accelerator.py#L1961) but I can see it printed 5 times ([output](https://gist.github.com/vanbasten23/141f2764f699972e0eb2709daa1fd7a3)) even though `args.num_processes` is 4 at https://github.com/huggingface/accelerate/blob/eafcea07f639a5476385854ea9bccdbba467db9d/src/accelerate/commands/launch.py#L756

### Expected behavior

Running the test `accelerate test` should succeed.

**Comment by vanbasten23** [comment]
Found a conversation previously from my teammates, basically https://github.com/huggingface/accelerate/blob/6b2d968897c91bc3f96274b4679d84e9950ad908/src/accelerate/utils/operations.py#L618C16-L618C26 doesn't change the `cloned_tensor` in-place. We can change that line with:
```
xm.all_reduce("sum", cloned_tensor, scale)
```
or even add a `mark_step` after it. But either way, the program just hangs ([output](https://gist.github.com/vanbasten23/d240e6527e24f4519b0697e8adf35d17))

**Comment by vanbasten23** [comment]
The reason why it hangs in https://github.com/huggingface/accelerate/issues/2247#issuecomment-1856449563 is that the xm.all_reduce is called only on the main process while it should be called on all processes: https://github.com/huggingface/accelerate/blob/6b2d968897c91bc3f96274b4679d84e9950ad908/src/accelerate/test_utils/scripts/test_script.py#L605-L606

**Comment by vanbasten23** [comment]
So the intention of the new breakpoint API (context: https://discuss.pytorch.org/t/how-to-use-break-in-distributeddataparallel-training/88296/5 for multi-processing) is that if one process figures out it needs to exit (eg, the loss starts to increase in this process) and break the loop, it can do a `set_trigger` ([implementation](https://github.com/huggingface/accelerate/blob/eafcea07f639a5476385854ea9bccdbba467db9d/src/accelerate/accelerator.py#L1907) which create a tensor of value 1) and all the other processes get the notification via a `get_trigger`([implementation](https://github.com/huggingface/accelerate/blob/eafcea07f639a5476385854ea9bccdbba467db9d/src/accelerate/accelerator.py#L1933) which does a all_reduce).

If PyTorch/XLA requires all the processes to do the same thing, then I'm not sure if Pytorch/XLA would support this capability. What do you think? @will-cromar @JackCaoG

**Comment by will-cromar** [comment]
How different are the HLOs produced by the processes? 1 and 0 are built into the graph as constants, so that may be the difference. Does it work if you disable the constants with `XLA_NO_SPECIAL_SCALARS=1`?

**Comment by vanbasten23** [comment]
With the change in the PR https://github.com/huggingface/accelerate/pull/2263, I got the hlo dump for process [0](https://gist.githubusercontent.com/vanbasten23/a45ec5481895a8921c3ac7f8c4dba038/raw/c0b689d3d427b8d7651670abffd91e99d595105e/gistfile1.txt) and [1](https://gist.github.com/vanbasten23/16a476faaa8918c29ce7431aba831927). The difference is more than the 1 and 0. I was expecting to find the `set_trigger` difference but I didn't.

Using `XLA_NO_SPECIAL_SCALARS=1` didn't resolve the hang.

**Comment by vanbasten23** [comment]
The HLO for process 0 has one more graph than other processes:
```
[ScheduleSyncTensorsGraph]
TensorsGraphInfo:
  check_trigger (/root/accelerate/src/accelerate/accelerator.py:1961)
  test_trigger (/root/accelerate/src/accelerate/test_utils/scripts/test_script.py:613)
  main (/root/accelerate/src/accelerate/test_utils/scripts/test_script.py:668)
...
```
which is triggered at https://github.com/huggingface/accelerate/blob/a03c361ffbee604ee9fd6738716b608f9996aea4/src/accelerate/test_utils/scripts/test_script.py#L613.

The reason why other processes didn't run the above line is that the previous check https://github.com/huggingface/accelerate/blob/a03c361ffbee604ee9fd6738716b608f9996aea4/src/accelerate/test_utils/scripts/test_script.py#L610 fails: I can verify that all other processes return false in the check_trigger function https://github.com/huggingface/accelerate/blob/a03c361ffbee604ee9fd6738716b608f9996aea4/src/accelerate/accelerator.py#L1999.

Then the questions become why xm.all_reduce returns 1 for process 0 but returns 0 for other processes.

**Comment by vanbasten23** [comment]
Ok, I can make the test pass by replacing https://github.com/huggingface/accelerate/blob/a03c361ffbee604ee9fd6738716b608f9996aea4/src/accelerate/utils/operations.py#L618 with:
```
xm.mark_step()
xm.all_reduce(xm.REDUCE_SUM, [cloned_tensor], scale)
```

But I am not sure why we need to call `mark_step()` before the `all_reduce`.

**Comment by will-cromar** [comment]
Calling `xm.mark_step` will clear the pending graph that process 0 has, so the HLO created by `xm.all_reduce` will match the others. Can you tell where the extra graph comes from? Ideally we want anything that creates a HLOs for this test to also sync to prevent it from failing downstream tests.

**Comment by vanbasten23** [comment]
> Calling `xm.mark_step` will clear the pending graph that process 0 has, so the HLO created by `xm.all_reduce` will match the others. Can you tell where the extra graph comes from? Ideally we want anything that creates a HLOs for this test to also sync to prevent it from failing downstream tests.

Thanks for the explanation!

The extra graph on process 0 comes from https://github.com/huggingface/accelerate/blob/a03c361ffbee604ee9fd6738716b608f9996aea4/src/accelerate/test_utils/scripts/test_script.py#L613, the 3rd `assert check_trigger()` in the `test_trigger` function. On processes other than process 0, the 2nd `assert check_trigger` simply fails so the 3rd `assert check_trigger` wouldn't run.

Irrespective the extra graph on process 0, all previous HLO graphs are almost identical as the ones on other processes, except for one difference: process 0 runs `set_trigger` but other processes don't. Perhaps, the `mark_step` forces the HLO graphs on all processes to be identical hence the `all_reduce` works.
