### ISSUE TITLE
Should `get_linear_schedule_with_warmup` consider `gradient_accumulation_steps`?

### ISSUE THREAD

**Issue by avsdfirst** [huggingface/accelerate#225]
I think `num_training_steps` should be `len(train_dataloader) * num_epochs // gradient_accumulation_steps`

**Comment by avsdfirst** [comment]
Sorry, I mean `accelerate/examples/nlp_example.py`  `line 128`, `num_training_steps` should be `len(train_dataloader) * num_epochs // gradient_accumulation_steps`. Now it doesn't consider `gradient_accumulation_steps`.

**Comment by sgugger** [comment]
Thanks for the precision! That's completely correct, would you like to make a PR to fix this?
