### ISSUE TITLE
incorrect reference to bnb 4bit param class name (FP4Params vs Params4bit)

### ISSUE THREAD

**Issue by poedator** [huggingface/accelerate#2250]
### System Info
version: Accelerate since April 2023 till now

When debugging 4bit serialization, I noticed that accelerate still uses previous class name for 4bit quantized parameters `FP4Params`. 
Example line: https://github.com/huggingface/accelerate/blob/ad3a5bc92084b9c5c6d5e141eb5ff0029f3fcc78/src/accelerate/utils/modeling.py#L330

In bnb it changed to `Params4bit` in April 2023 in this PR https://github.com/TimDettmers/bitsandbytes/commit/4ea489d3bfc119ab4ceb50f999ce611690dc21e2#diff-4d235c7e595546c6656c229dfa139298ce6602b356c2d0bafcb2352eb2cfae79R136

It appeared in Accelerate in June 2023, in this PR: https://github.com/huggingface/accelerate/pull/1626, after the class was renamed in bnb.

Not sure if this actually causes any errors, but the HF / BNB maintainers may want to look into this. Maybe it is not an issue and only aimed at users with older bnb versions??

### Expected behavior

coordination with bnb classes, incl Params4bit

cc @younesbelkada @SunMarc @Titus-von-Koeller

**Comment by SunMarc** [comment]
thanks for the heads-up ! I will investigate what are the potential issues in accelerate ! In transformers, we use a [patched](https://github.com/huggingface/transformers/blob/bb1d0d0d9e7ca356cf5673031183e955cc160158/src/transformers/integrations/bitsandbytes.py#L24) version of this function. So this should not impact transformers at least

**Comment by poedator** [comment]
> Thanks for the heads-up @poedator ! I will investigate what are the potential issues in accelerate ! In transformers, we use a [patched](https://github.com/huggingface/transformers/blob/bb1d0d0d9e7ca356cf5673031183e955cc160158/src/transformers/integrations/bitsandbytes.py#L24) version of this function. So this should not impact transformers at least

Thank you for the quick feedback. I see that you have a copy of this function in the integrations. Still it it does impact transformers because during dispatch phase it gets called inside accelerate. So it bit me when I tested the 4bit quantization (ref [huggingface/accelerate#2254](https://github.com/huggingface/accelerate/pull/2254). Perhaps the accelerate function copy could be simplified, with most functionality moved to transformers.

**Comment by SunMarc** [comment]
i'm closing this since the PR was merged !
