### ISSUE TITLE
Add sagemaker 'checkpoint_s3_uri' as standard param in default_config.yaml

### ISSUE THREAD

**Issue by dnandha** [huggingface/accelerate#2255]
### System Info

```Shell
- `Accelerate` version: 0.25.0
- Platform: Linux-6.6.2-arch1-1-x86_64-with-glibc2.38
- Python version: 3.10.13
- Numpy version: 1.26.2
- PyTorch version (GPU?): 1.11.0+cu102 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 7.64 GB
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Follow this guide: [https://github.com/huggingface/notebooks/tree/main/sagemaker/22_accelerate_sagemaker_examples](https://github.com/huggingface/notebooks/tree/main/sagemaker/22_accelerate_sagemaker_examples)
2. Issue: Checkpoints not saved / synced to S3

### Expected behavior

Currently, the support for [AWS SageMaker checkpoints](https://docs.aws.amazon.com/sagemaker/latest/dg/model-checkpoints.html#model-checkpoints-saved-file) is not documented in accelerate.

Nonetheless, S3 checkpoints can be enabled via 'additional_args' as such:
`additional_args: {'checkpoint_s3_uri': 's3://<bucket_name>/'}`.

Reference: [SageMaker Python SDK](https://github.com/aws/sagemaker-python-sdk/blob/889d7b7c8cb49d69a802a375d2e79006e36f1f27/src/sagemaker/estimator.py#L313)

I propose adding this parameter as a standard parameter and including the documentation respectively.

**Comment by SunMarc** [comment]
Hi @dnandha, thanks for reporting. We do have a section about sagemaker in our docs. The relevant section for your issue should be this [one](https://huggingface.co/docs/accelerate/usage_guides/sagemaker#advanced-configuration). LMK this works !
