### ISSUE TITLE
can't set attribute 'device', for some reason i need to train model on only one gpu on a mutlti gpu machine.

### ISSUE THREAD

**Issue by Yuhyeong** [huggingface/accelerate#2266]
### System Info

```Shell
File "/home/asasa/repo/kohya_ss/train_network.py", line 222, in train
    accelerator.device = torch.device("cuda:7" if torch.cuda.is_available() else "cpu")
  File "/home/asasa/repo/kohya_ss/train_new.py", line 302, in train_lora
    trainer.train(args)
  File "/home/asasa/repo/kohya_ss/train_new.py", line 733, in total_train
    train_args = train_lora(train_dataset_dir, name, lora_dir, log_dir)
AttributeError: can't set attribute 'device'
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

I'm doing some lora experiments on my 8-GPU machine, while im running other training process on 6 of 8 gpus. And I cant use CUDA_VISIBLE_DEVICES for i need to launch the trainging by using multi threads. If I set the env var, that would work like a two gpus distributed training. But i need train different exp on different gpu.

So I decide to set the `device` attribute straightly when creating the Acclerator object, but i failed for there is no params named device or sth. And then I tried set the attribute after created the Acclerator object, it fails too, like the `error` above. 

My train process need one gpu for each, so i have to make them seperate. is there anyway to set the device before the train process?

### Expected behavior

Expected each thread of training can be running on different gpu seprately.

**Comment by BenjaminBossan** [comment]
The error occurs because the `device` attribute on the `Accelerator` class is a `@property`. Maybe you can try if setting `accelerator.state.device` works, but I'm not sure if that doesn't cause problems elsewhere.

> And I cant use CUDA_VISIBLE_DEVICES for i need to launch the trainging by using multi threads.

Could you please explain that, why does using multiple threads prevent using the env var?

**Comment by Yuhyeong** [comment]
> The error occurs because the `device` attribute on the `Accelerator` class is a `@property`. Maybe you can try if setting `accelerator.state.device` works, but I'm not sure if that doesn't cause problems elsewhere.
> 
> > And I cant use CUDA_VISIBLE_DEVICES for i need to launch the trainging by using multi threads.
> 
> Could you please explain that, why does using multiple threads prevent using the env var?

thank u for the adveice, i would try it later.

I mean that, though I could set the env var to make every experiment run in different gpu seperately. But My tutor ask me to use threads to lauch the experiments which aims to provide concurrency for the further study

**Comment by Yuhyeong** [comment]
> The error occurs because the `device` attribute on the `Accelerator` class is a `@property`. Maybe you can try if setting `accelerator.state.device` works, but I'm not sure if that doesn't cause problems elsewhere.
> 
> > And I cant use CUDA_VISIBLE_DEVICES for i need to launch the trainging by using multi threads.
> 
> Could you please explain that, why does using multiple threads prevent using the env var?

if i use env var while using threads, the env var would change if the other thread starts. to prevent this circumstances. I need to acquire a lock and unlock it until the stage which need the env var passed. 

that would spent too much time, so I decide no to change env var in my code. 

By the way, I successfully set the accelerator device, I would give feedback is I have bug. 

Thank u!

**Comment by BenjaminBossan** [comment]
Great. Feel free to re-open the issue if you have further questions.
