### ISSUE TITLE
Is there anyway to specify multiple gpu ids for device_map? 

### ISSUE THREAD

**Issue by justinphan3110cais** [huggingface/accelerate#2270]
Hi team,
So instead of loading the model with `device_map="auto"`. I only want to load on specific gpus. Is there best practice to do this without the need of design a manual device_map?

For example in process on a cluster with 4 gpus, I want to load model1 on gpu_ids=0,1,2 and model2 on gpu_ids=3

**Comment by heraclex12** [comment]
Let's say you have 4 gpus and you want to use gpus 0, 1, 2 for model1 and gpu 3 for model2. You can use the following code to set the maximum memory of three devices (0, 1, 2):
```python
max_memory = {i: torch.cuda.mem_get_info(i)[0] for i in range(3)} 
device_map = infer_auto_device_map(model)
```

Or you can use the following code to exclude n-th last devices:
```python
max_memory = {i: torch.cuda.mem_get_info(i)[0] for i in range(torch.cuda.device_count() - 1)} 
device_map = infer_auto_device_map(model)
```

**Comment by justinphan3110cais** [comment]
Thank you solve my issue!
