### ISSUE TITLE
[feature request] improve FSDP config usability 

### ISSUE THREAD

**Issue by stas00** [huggingface/accelerate#2273]
I have just tried out using FSDP and run into:

```
  fsdp_sharding_strategy: 1
```

how can a user know the meaning of this setting?

And the rest of the options aren't documented either.

After grepping I found

```
src/accelerate/utils/constants.py:FSDP_SHARDING_STRATEGY = ["FULL_SHARD", "SHARD_GRAD_OP", "NO_SHARD", "HYBRID_SHARD", "HYBRID_SHARD_ZERO2"]
```

I'm guessing then that `1` maps to `SHARD_GRAD_OP`? as in index 1 of the above list? I think not, since I tried setting it to `0` and got:

```
ValueError: 0 is not a valid ShardingStrategy
```

Can these strings be used as the values instead of numbers so that the user can see what they are configuring? The rest of the FSDP Accelerate options are implemented this way (meaningful strings), so I'm not sure why `fsdp_sharding_strategy` isn't.

and could these options be added to the docs?

Thank you!

**Comment by stas00** [comment]
ok, so debugging this some more - this is enum so the values are starting from 1 and not 0 and they are:

```
1:ShardingStrategy.FULL_SHARD
2:ShardingStrategy.SHARD_GRAD_OP
3:ShardingStrategy.NO_SHARD
4:ShardingStrategy.HYBRID_SHARD
5:ShardingStrategy._HYBRID_SHARD_ZERO2
```

Allowing a user to say:

```
  fsdp_sharding_strategy: FULL_SHARD
```

would probably be the most consistent and self-documenting approach if I may suggest.

**Comment by muellerzr** [comment]
Agreed with you there @stas00, I was going to look into enabling both options for the user :)

**Comment by pacman100** [comment]
Yes, this is something I wanted to correct but didn't do it for backwards compatibility. Will work on it

**Comment by pacman100** [comment]
Hello, the above PR should resolve this issue by being backwards compatible while making the string values the default now.

**Comment by stas00** [comment]
Thanks a lot, this is much better now, Sourab.

**Comment by AfrinDange** [comment]
Can you also add more details about the several options used in FSDP config? I am a beginner and struggling to find resources to use FSDP for my custom pytorch module. 
Currently, I am referring to [this page](https://huggingface.co/docs/accelerate/usage_guides/fsdp). It focuses on transformer models only.
Please point out any relevant documentation that I might be missing.

**Comment by stas00** [comment]
Thank you for resolving my request, Sourab. I'm closing this Issue.

@AfrinDange, usually adding things to an existing Issue leads to it getting ignored. So I highly recommend to open a new issue.
