### ISSUE TITLE
[feature request] fsdp fwd/bwd prefetch config name consistency 

### ISSUE THREAD

**Issue by stas00** [huggingface/accelerate#2275]
fwd and bwd prefetch are "symmetrical" values, though currently the naming is strangely inconsistent:

```
  fsdp_forward_prefetch:
  fsdp_backward_prefetch_policy: 
```

should it be:
```
fsdp_forward_prefetch
fsdp_backward_prefetch
```
or:
```
fsdp_forward_prefetch_policy
fsdp_backward_prefetch_policy
```

thanks.

**Comment by pacman100** [comment]
Hello, the above PR should address this issue by deprecating `fsdp_backward_prefetch_policy` and having it as `fsdp_backward_prefetch`

**Comment by stas00** [comment]
super, thank you for the quick improvements, Sourab!
