### ISSUE TITLE
torch.distributed.new_group

### ISSUE THREAD

**Issue by PeggyPeppa** [huggingface/accelerate#2282]
Does accelerate support torch.distributed.new_group?

**Comment by SunMarc** [comment]
Hi @PeggyPeppa , what would be the use case of this function in accelerate ? cc @muellerzr

**Comment by PeggyPeppa** [comment]
Like such code, when I need to set syncbn, I wonder whether my use is proper? Can accelerate due with this setting?    
    if int(self.sync_bn) > 1:
        self.nr_gpus = self.sync_bn
        self.world_size = int(os.environ.get("RLAUNCH_REPLICA_TOTAL", 1)) * int(self.nr_gpus)
        self.local_rank = int(os.environ.get("LOCAL_RANK", 0))
        self.global_rank = int(self.nr_gpus) * int(os.environ.get("RLAUNCH_REPLICA", 0)) + self.local_rank
        ranks = np.arange(int(os.environ.get("RLAUNCH_REPLICA_TOTAL", 1)) * int(self.nr_gpus)).reshape(-1, self.sync_bn)
        process_groups = [torch.distributed.new_group(list(pids)) for pids in ranks]
        self.model = torch.nn.SyncBatchNorm.convert_sync_batchnorm(
            self.model, process_groups[self.global_rank // self.sync_bn]
        )

    elif int(self.sync_bn) == 1:
        self.model = torch.nn.SyncBatchNorm.convert_sync_batchnorm(self.model)

    self.model, self.opt, self.lr_scheduler = \
        self.accelerator.prepare(self.model, self.opt, self.lr_scheduler)

**Comment by muellerzr** [comment]
If you want a separate pg just for sync bn, your use is correct. No one has mentioned this yet and seems quite niche, so for now what you have done is the proper way (we do not handle sync bn during `.prepare` in general)
