### ISSUE TITLE
Bug with tqdm helper

### ISSUE THREAD

**Issue by AjayP13** [huggingface/accelerate#2283]
@muellerzr, I believe the tqdm helper here:
 
https://github.com/huggingface/accelerate/blob/d08c23c20975f39393b431143237c193733e7bb8/src/accelerate/utils/tqdm.py#L36

is not doing the correct check, should this be using `!=` instead of '==' like:

```python
disable = PartialState().local_process_index != 0
```

instead?

**Comment by SunMarc** [comment]
Hi @AjayP13, that's indeed the case. Would you like a submit a PR to fix this ? =)

**Comment by AjayP13** [comment]
Looks like #2223 got to it a few weeks ago, but it hasn't made it's way to PyPI yet. Closing.
