### ISSUE TITLE
[QUESTION] why stage3_gather_16bit_weights_on_model_save is set to false no matter what value of it in deepspeed config

### ISSUE THREAD

**Issue by LaniakeaS** [huggingface/accelerate#2289]
[`accelerator._prepare_deepspeed()`](https://github.com/huggingface/accelerate/blob/d08c23c20975f39393b431143237c193733e7bb8/src/accelerate/accelerator.py#L1464C13-L1464C82) looks to force the `stage3_gather_16bit_weights_on_model_save` to `false`, which should raise an exception in [`accelerator.get_state_dict()`](https://github.com/huggingface/accelerate/blob/d08c23c20975f39393b431143237c193733e7bb8/src/accelerate/accelerator.py#L2985C17-L2985C68). Additionally, [`trainer.save_model()`](https://github.com/huggingface/transformers/blob/c48787f347bd604f656c2cfff730e029c8f8c1fe/src/transformers/trainer.py#L2827C17-L2827C77) invoke above function, then catch this exception and raise another exception. Yet, the log seems totally fine. I'm confused... Why this happened?

**Comment by LaniakeaS** [comment]
And the `stage3_gather_16bit_weights_on_model_save` should not to be forced to `false` neither, isn't it?

**Comment by SunMarc** [comment]
cc @pacman100

**Comment by LaniakeaS** [comment]
any response please?

**Comment by LaniakeaS** [comment]
never mind... that's a stupid question...
