### ISSUE TITLE
How I can save a custom model inherit from nn.Module

### ISSUE THREAD

**Issue by scarydemon2** [huggingface/accelerate#229]

**Comment by scarydemon2** [comment]
Or how I can implement a custom save_pretrained() func in my own model Class

**Comment by jaketae** [comment]
Hey @scarydemon2,

If I understand your question correctly, you can first unwrap the model, then use the normal torch routine to save it.

```python
# assume `model` was previously wrapped via `accelerator.prepare(...)`
unwrapped_model = accelerator.unwrap(model)
torch.save(unwrapped_mdoel.state_dict(), PATH)
```

Does this accomplish your goal?

**Comment by sgugger** [comment]
Please use the [forums](https://discuss.huggingface.co/) for questions like this, as we keep issues for bugs and feature requests only.
You should check the [documentation on saving models](https://huggingface.co/docs/accelerate/quicktour.html#saving-loading-a-model).

**Comment by scarydemon2** [comment]
> Please use the [forums](https://discuss.huggingface.co/) for questions like this, as we keep issues for bugs and feature requests only. You should check the [documentation on saving models](https://huggingface.co/docs/accelerate/quicktour.html#saving-loading-a-model).

sorry for the bad format. This issue has been solved.
