### ISSUE TITLE
'GradientState' object has no attribute '_set_end_of_dataloader'

### ISSUE THREAD

**Issue by Humble2967738843** [huggingface/accelerate#2291]
### System Info

```Shell
- `Accelerate` version: 0.25.0
- Platform: Linux-4.4.0-142-generic-x86_64-with-glibc2.17
- Python version: 3.8.18
- Numpy version: 1.24.3
- PyTorch version (GPU?): 1.12.1 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 251.55 GB
- GPU type: Tesla P100-SXM2-16GB
- `Accelerate` default config:
        Not found
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

28 Dec 00:09    ERROR Traceback (most recent call last):
  File "/data/utils/dashboard.py", line 311, in new_experiment
    yield True
  File "/data/quick_start/experiment.py", line 140, in run
    self._do_train_and_valid()
  File "/data/quick_start/experiment.py", line 115, in _do_train_and_valid
    self.valid_result = self.trainer.fit(train_data, valid_data)
  File "/data/textbox/trainer/trainer.py", line 452, in fit
    loss = self._train_epoch(train_data, epoch_idx, valid_data)['loss']
  File "/data/textbox/trainer/trainer.py", line 236, in _train_epoch
    self.accelerator.gradient_state._set_end_of_dataloader(False)
AttributeError: 'GradientState' object has no attribute '_set_end_of_dataloader'

### Expected behavior

'GradientState' object has no attribute '_set_end_of_dataloader'

**Comment by muellerzr** [comment]
Whatever implementation you have for `trainer` is incorrect and using the wrong configuration. It should call `_set_sync_gradients` instead. I would open an issue with whatever library you are using
