### ISSUE TITLE
unet.save_pretrained() only save a super small file (2MB) if use ZeRO-3 training on multi-GPUs

### ISSUE THREAD

**Issue by Wang-Xiaodong1899** [huggingface/accelerate#2294]
### System Info

```Shell
lastest accelerate
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

I try to finetune the text-to-video model using the `UNetSpatioTemporalConditionModel` from `diffusers` as the U-Net backbone on my private dataset, and the training process was normal, but when I need to use `unet.save_pretrained(os.path.join(args.output_dir, "unet"))`, it only save a config file and a very small file, you know ,here is a safetensors files, but only 2Mb, even 2Kb, very strange.

```
from diffusers import UNetSpatioTemporalConditionModel
unet = UNetSpatioTemporalConditionModel(cross_attention_dim=768, in_channels=4)
...
unet.load_state_dict(new_state_dicts, strict=False)
unet, optimizer, train_dataloader, lr_scheduler = accelerator.prepare(
        unet, optimizer, train_dataloader, lr_scheduler
    )
...
for epoch in range(first_epoch, args.num_train_epochs):
        train_loss = 0.0
        for step, batch in enumerate(train_dataloader):
            with accelerator.accumulate(unet):
...

accelerator.wait_for_everyone()
if accelerator.is_main_process:
    unet = accelerator.unwrap_model(unet)

    #TODO save UNet
    unet.save_pretrained(os.path.join(args.output_dir, "unet"))

```

I used ZeRO-3 training and sharded the model on two GPUs, and my training script is:
```
accelerate launch --mixed_precision="fp16" finetune_video.py --train_batch_size=2 \
--gradient_accumulation_steps=4 --gradient_checkpointing --num_train_epochs 1 \
--learning_rate=1e-5 --max_grad_norm=1 --enable_xformers_memory_efficient_attention \
--lr_scheduler=constant --lr_warmup_steps=0 --output_dir=video-test --pretrained_model_name_or_path CompVis/stable-diffusion-v1-4
```
The training process was normal, but after the training was completed, I only got a 2M diffusion_pytorch_model. safetensors file. 

Additionally, I modified the loading process because I need to load the previous text-to-image weights (spatial weights) into the new `UNetSpatioTemporalConditionModel`.

Any suggestions? Thanks a lot!

### Expected behavior

Using ZeRO-3 training and sharded the model on two GPUs.
After `unet.save_pretrained(os.path.join(args.output_dir, "unet"))`, it can save a weight file with more than 3GB size.

**Comment by muellerzr** [comment]
cc @pacman100
