### ISSUE TITLE
How can I check how many GPUs are used in this library?

### ISSUE THREAD

**Issue by ciaoyizhen** [huggingface/accelerate#2297]
### System Info

```Shell
I use wgpus to show that there are four cards. However, when I start training the model, I only see one card being used. I want to query a reason, but I cannot find a command to see how many graphics cards are used by the module.

I use the command os.environ["CUDA_VISIBLE_DEVICES"] = "0,1,2,3" and still only one graphics card is in use.

By the way, I would like to ask, when using accelerator.perpare, my dataloader is still text instead of tensor. Can it be passed in for use? I see that the code does not report any errors.
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

None

### Expected behavior

None

**Comment by BenjaminBossan** [comment]
Could you please provide your training script (or a minimal version of it that reproduces the error), on top of environment information (`accelerate env`) and the command you use to call the script?

**Comment by ciaoyizhen** [comment]
> Could you please provide your training script (or a minimal version of it that reproduces the error), on top of environment information (`accelerate env`) and the command you use to call the script?

I'm very sorry that the company's internal code cannot be provided. I will briefly describe the technology used. First, I used the bigbird model of transformers. I used this model to get the results of the last layer. I used full connections to complete the long text classification task. I used pytorch. I customized the dataset and dataloader, but due to the use of dynamic filling, what I returned in the dataloader was still a text, not a tensor.

I tried modifying os.environ["CUDA_VISIBLE_DEVIECES"] = "1,2,3" and now the code runs on 1 instead of 0.
My level of knowledge is limited. By looking at the documentation and the difference in my code. I now think there are two possible reasons for this result.
The first is that the bigbird model uses sparse attention and may not be split? It's not clear to me, so it only works on one card?
The second is that when I use accelerate.perpare, my dataloader is not of tensor type?
There may be other reasons, I don't know now.
If you know anything else, please feel free to enlighten me, thank you.

**Comment by muellerzr** [comment]
Are you running the code with `python` or `accelerate launch`/`torchrun`. Please see the CLI tutorial guides on how to properly launch your code, otherwise it will only use a single GPU

**Comment by ciaoyizhen** [comment]
> Are you running the code with `python` or `accelerate launch`/`torchrun`. Please see the CLI tutorial guides on how to properly launch your code, otherwise it will only use a single GPU

yes yes  thank you . I used python instead of using accelerator launch. I have solved this problem now. Thanks again.
