### ISSUE TITLE
Inference API: Pinning models doesn't seem to work

### ISSUE THREAD

**Issue by daniel-ziegler** [huggingface/accelerate#230]
We've pinned models (both using the API call and using the dashboard at https://api-inference.huggingface.co/dashboard/pinned_models), but still get "currently loading" errors when we try to make inference API calls.

One example: model https://huggingface.co/redwoodresearch/redwood_deberta-v3-sift_82b19d290a74410caa804fa47e94a80b (private but we can make it public if that would help). It's currently (supposedly) pinned but still requires a minute of warmup after a period of inactivity.

**Comment by sgugger** [comment]
I am unsure how exactly this relates to the `Accelerate` library. I think you opened an issue in the wrong place.

**Comment by daniel-ziegler** [comment]
Yep, sorry, followed the wrong series of links.
