### ISSUE TITLE
issue with using deepspeed with transformers.pipeline  AttributeError:  `'dict' object has no attribute '_commit_hash'`

### ISSUE THREAD

**Issue by LuciusLan** [huggingface/accelerate#2303]
### System Info

```Shell
- `Accelerate` version: 0.25.0
- Platform: Linux-5.15.0-89-generic-x86_64-with-glibc2.35
- Python version: 3.10.13
- Numpy version: 1.26.2
- PyTorch version (GPU?): 2.1.2 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 503.72 GB
- GPU type: NVIDIA A100-SXM4-40GB
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: DEEPSPEED
        - use_cpu: False
        - debug: True
        - num_processes: 4
        - machine_rank: 0
        - num_machines: 1
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - deepspeed_config: {'deepspeed_config_file': './acc_dsconfig', 'zero3_init_flag': False}
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

So I am trying some inference code from my schoolmate (who likely had used different version of accerlerate/transformers than me)
```
model = AutoModelForCausalLM.from_pretrained("meta-llama/Llama-2-13b-chat-hf")

tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-2-13b-chat-hf")

accelerator = Accelerator()

model, test_dataloader = accelerator.prepare(model, test_dataloader)

pipeline = transformers.pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
)
```

And the pipeline initialization would fail with my enviroment, error message: `'dict' object has no attribute '_commit_hash'`

The cause seemed to be obvious: the original `model.config` should contain the information of the model like below:
![661ecf01a8cd5c27b8e3cc78333635f](https://github.com/huggingface/accelerate/assets/21154348/b2168206-1f17-4fed-8e39-a45e57d50deb)
While after `accelerator.prepare`, the `model.config` becomes accelerator's config:
![e11d8c80fea22bd94a7a4cd73fc9ef6](https://github.com/huggingface/accelerate/assets/21154348/b2838667-ab1e-4232-b0fd-3507a3236663)

I'm currently running experiment without the pipeline, or simple workaround is to sync with my schoolmate's enviorment libraries version. I would like to just raise this issue here to help anyone else who happen to encounter this issue.

### Expected behavior

N.A.

**Comment by LuciusLan** [comment]
Sorry I just confirmed with my schoolmate that he was not using DeepSpeed, so this should be a deepspeed specific problem that the deepspeed-wrapped model is not compatible with transformers.pipeline . I'm not sure if I should open a issue there

**Comment by muellerzr** [comment]
Open an issue in transformers would be my recommendation please :)
