### ISSUE TITLE
You can't train a model that has been loaded with `device_map='auto'` in any distributed mode.

### ISSUE THREAD

**Issue by candygocandy** [huggingface/accelerate#2311]
### System Info

```Shell
So what I have is that:

base_model = AutoModelForCausalLM.from_pretrained(
    "/root/autodl-tmp/.cache/modelscope/hub/AI-ModelScope/Mistral-7B-v0.1", local_files_only=True,
     torch_dtype=torch.float16,
#    device_map={"": Accelerator().local_process_index},
    device_map="auto",
)

I have 4x4090 GPU and I wanna train Llama7B model across each one of these GPUs. Each 4090GPU has 24 GB, but loading 7B model will take 54GB of memory, so, holding it on single GPU won't work. So, How should I handle this error? Can I make it load at device="0,1,2,3" (i.e, all 4 gpu?)

Traceback (most recent call last):
  File "examples/research_projects/stack_llama_2/scripts/sft.py", line 175, in <module>
    trainer.train()
  File "/root/miniconda3/lib/python3.8/site-packages/trl/trainer/sft_trainer.py", line 315, in train
    output = super().train(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/trainer.py", line 1537, in train
    return inner_training_loop(
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/trainer.py", line 1672, in _inner_training_loop
    model, self.optimizer = self.accelerator.prepare(self.model, self.optimizer)
  File "/root/miniconda3/lib/python3.8/site-packages/accelerate/accelerator.py", line 1168, in prepare
    raise ValueError(
ValueError: You can't train a model that has been loaded with `device_map='auto'` in any distributed mode. Please rerun your script specifying `--num_processes=1` or by launching with `python {{myscript.py}}`.
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

just run

### Expected behavior

no error.

**Comment by SunMarc** [comment]
Hi @candygocandy, as stated, you can't train a model with distributed mode (data-parallel training DDP) when using `device_map`. However, you can still train it when the model is split on multiple devices with the normal setup ( specifying `--num_processes=1` or by launching with `python {{myscript.py}}`). You can also switch to model-parallel training by using FSDP in PyTorch. Here's a great [guide](https://huggingface.co/blog/ram-efficient-pytorch-fsdp) on how to finetune a 70b Llama with FSDP.

**Comment by candygocandy** [comment]
@SunMarc , I am trying to use the 2nd approach, `python myscript.py`

Question about the guide, if I am not using lora, how do I modify this block of code (from the guide) to enable FSDP?
```

    if model_args.use_peft_lora:
        # handle PEFT+FSDP case
        trainer.model.print_trainable_parameters()
        if getattr(trainer.accelerator.state, "fsdp_plugin", None):
            from peft.utils.other import fsdp_auto_wrap_policy
            from torch.distributed.fsdp import (
                FullyShardedDataParallel as FSDP,
            )

            fsdp_plugin = trainer.accelerator.state.fsdp_plugin
            auto_wrap_policy = fsdp_auto_wrap_policy(trainer.model)
            kwargs = {
                "sharding_strategy": fsdp_plugin.sharding_strategy,
                "cpu_offload": fsdp_plugin.cpu_offload,
                "auto_wrap_policy": auto_wrap_policy,
                "mixed_precision": fsdp_plugin.mixed_precision_policy,
                "sync_module_states": fsdp_plugin.sync_module_states,
                "use_orig_params": False,  # this should be `False`
                "limit_all_gathers": True,
                "param_init_fn": fsdp_plugin.param_init_fn,
                "device_id": trainer.accelerator.device,
            }
            trainer.model = trainer.model_wrapped = FSDP(trainer.model, **kwargs)
            trainer.args.remove_unused_columns = False
```

**Comment by SunMarc** [comment]
> @SunMarc , for the first approach --num_processes=1 with accelerate at the launch, do I need to set device_map='auto'?

You need to set device_map="auto" since otherwise the model won't fit in a single gpu for both approach.

Question about the guide, if I am not using lora, how do I modify this block of code (from the guide) to enable FSDP?

If you are not using lora, then you shouldn't need to add code related to fsdp. Just properly set the accelerate config. See [docs](https://huggingface.co/docs/accelerate/v0.10.0/en/fsdp) here.
