### ISSUE TITLE
Why do you unilaterally disable p2p when detecting RTX 3090

### ISSUE THREAD

**Issue by markrmiller** [huggingface/accelerate#2328]
### System Info

```Shell
I assume this done due to the various issues people hit when they don’t have p2p support, but there seems to be no opt out? It’s annoying to have to go and edit the source.

NVLinked 3090s support p2p. What am I missing?
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

Run launch with 2 NVLinked 3090s

### Expected behavior

accelerate doesn’t override p2p env variables on you

**Comment by muellerzr** [comment]
To my knowledge they disabled P2P speedups and IB speedups on the 3090, no? So NVLink no longer works on consumer grade cards after (and including) the 3090?

**Comment by muellerzr** [comment]
Looks like I am incorrect, it's only on the 4000-series, will look into re-enabling this!

**Comment by muellerzr** [comment]
@markrmiller for now you can do `pip install git+https://github.com/huggingface/accelerate` to no longer have to worry about this :) Our next release is planned for in February in the meantime
