### ISSUE TITLE
Issue with FSDP in Evaluation Mode for Mixtral7*8B Model

### ISSUE THREAD

**Issue by uygnef** [huggingface/accelerate#2337]
Hello,

I am encountering an issue when attempting to use Fully Sharded Data Parallel (FSDP) with a 56-billion-parameter sparse MoE model in evaluation mode. The model is too large to fit on a single GPU, and when I enable FSDP in evaluation mode, it does not seem to function properly.

Upon setting evaluation_mode to False, I found that FSDP works correctly. This behavior is related to the following code snippet from the accelerate library:

# https://github.com/huggingface/accelerate/blob/31fd2b1ad6b9c1cd1480568399a311b3caaf62dc/src/accelerate/accelerator.py#L1341

>evaluation_mode (`bool`, *optional*, defaults to `False`):
>              Whether or not to set the model for evaluation only, by just applying mixed precision and
>              `torch.compile` (if configured in the `Accelerator` object).

Based on the description, it seems that setting evaluation_mode to False should not affect precision during the evaluation task. Can you confirm if my understanding is correct? Moreover, is there a known issue with FSDP in evaluation mode, or could you suggest any workaround to use FSDP with such a large model in evaluation mode?

Thank you for your assistance.

**Comment by pkumc** [comment]
@muellerzr

**Comment by eval-dev** [comment]
I think it probably assumed model would fit in one gpu when inference, and also fsdp is not efficient in terms of inference.

My preference is having fsdp enabled when evaluation, so that we can at least run big model across multiple GPUs. If user don't want to or need to use fsdp, they can choose not to pass "--use_fsdp" when running evaluation.
