### ISSUE TITLE
'Tensor' object has no attribute 'named_children'

### ISSUE THREAD

**Issue by coollzd** [huggingface/accelerate#2338]
### System Info

```Shell
- `Accelerate` version: 0.20.3
- Platform: Linux-5.15.0-89-generic-x86_64-with-debian-bullseye-sid
- Python version: 3.7.16
- Numpy version: 1.21.6
- PyTorch version (GPU?): 1.12.0+cu113 (True)
- PyTorch XPU available: False
- System RAM: 125.48 GB
- GPU type: NVIDIA GeForce RTX 3090
- `Accelerate` default config:
        Not found
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

 text_encoder = T5EncoderModel.from_pretrained(
        "/home/coolzd/instant-ngp/SD_model",
        subfolder="text_encoder",
        device_map="auto",
        load_in_8bit=True,
        variant="8bit"
    )
    pipe = IFInpaintingPipeline.from_pretrained(
        "/home/coolzd/instant-ngp/SD_model",
        text_encoder=text_encoder,
        unet=None,
        device_map="auto"
    )

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/coolzd/instant-ngp/deepfloyd.py:57 in <module>                                             │
│                                                                                                  │
│   54 │   │   "/home/coolzd/instant-ngp/SD_model",                                                │
│   55 │   │   text_encoder=text_encoder,                                                          │
│   56 │   │   unet=None,                                                                          │
│ ❱ 57 │   │   device_map="auto"                                                                   │
│   58 │   )                                                                                       │
│   59                                                                                             │
│   60                                                                                             │
│                                                                                                  │
│ /home/coolzd/anaconda3/envs/ngp/lib/python3.7/site-packages/diffusers/pipelines/pipeline_utils.p │
│ y:1124 in from_pretrained                                                                        │
│                                                                                                  │
│   1121 │   │   │   │   │   from_flax=from_flax,                                                  │
│   1122 │   │   │   │   │   variant=variant,                                                      │
│   1123 │   │   │   │   │   low_cpu_mem_usage=low_cpu_mem_usage,                                  │
│ ❱ 1124 │   │   │   │   │   cached_folder=cached_folder,                                          │
│   1125 │   │   │   │   )                                                                         │
│   1126 │   │   │   │   logger.info(                                                              │
│   1127 │   │   │   │   │   f"Loaded {name} as {class_name} from `{name}` subfolder of {pretrain  │
│                                                                                                  │
│ /home/coolzd/anaconda3/envs/ngp/lib/python3.7/site-packages/diffusers/pipelines/pipeline_utils.p │
│ y:472 in load_sub_model                                                                          │
│                                                                                                  │
│    469 │                                                                                         │
│    470 │   # check if the module is in a subdirectory                                            │
│    471 │   if os.path.isdir(os.path.join(cached_folder, name)):                                  │
│ ❱  472 │   │   loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwar  │
│    473 │   else:                                                                                 │
│    474 │   │   # else load from the root directory                                               │
│    475 │   │   loaded_sub_model = load_method(cached_folder, **loading_kwargs)                   │
│                                                                                                  │
│ /home/coolzd/anaconda3/envs/ngp/lib/python3.7/site-packages/diffusers/models/modeling_utils.py:7 │
│ 13 in from_pretrained                                                                            │
│                                                                                                  │
│    710 │   │   │   │   │   │   │   )                                                             │
│    711 │   │   │   │   │   │   │   model._undo_temp_convert_self_to_deprecated_attention_blocks  │
│    712 │   │   │   │   │   │   else:                                                             │
│ ❱  713 │   │   │   │   │   │   │   raise e                                                       │
│    714 │   │   │   │                                                                             │
│    715 │   │   │   │   loading_info = {                                                          │
│    716 │   │   │   │   │   "missing_keys": [],                                                   │
│                                                                                                  │
│ /home/coolzd/anaconda3/envs/ngp/lib/python3.7/site-packages/diffusers/models/modeling_utils.py:6 │
│ 81 in from_pretrained                                                                            │
│                                                                                                  │
│    678 │   │   │   │   │   │   │   max_memory=max_memory,                                        │
│    679 │   │   │   │   │   │   │   offload_folder=offload_folder,                                │
│    680 │   │   │   │   │   │   │   offload_state_dict=offload_state_dict,                        │
│ ❱  681 │   │   │   │   │   │   │   dtype=torch_dtype,                                            │
│    682 │   │   │   │   │   │   )                                                                 │
│    683 │   │   │   │   │   except AttributeError as e:                                           │
│    684 │   │   │   │   │   │   # When using accelerate loading, we do not have the ability to l  │
│                                                                                                  │
│ /home/coolzd/anaconda3/envs/ngp/lib/python3.7/site-packages/accelerate/big_modeling.py:482 in    │
│ load_checkpoint_and_dispatch                                                                     │
│                                                                                                  │
│   479 │   │   │   │   low_zero=(device_map == "balanced_low_0"),                                 │
│   480 │   │   │   )                                                                              │
│   481 │   │   device_map = infer_auto_device_map(                                                │
│ ❱ 482 │   │   │   model, max_memory=max_memory, no_split_module_classes=no_split_module_classe   │
│   483 │   │   )                                                                                  │
│   484 │   if offload_state_dict is None and device_map is not None and "disk" in device_map.va   │
│   485 │   │   offload_state_dict = True                                                          │
│                                                                                                  │
│ /home/coolzd/anaconda3/envs/ngp/lib/python3.7/site-packages/accelerate/utils/modeling.py:761 in  │
│ infer_auto_device_map                                                                            │
│                                                                                                  │
│    758 │   │   # Case 1 -> We're too big!                                                        │
│    759 │   │   if current_max_size is not None and current_memory_used + module_size > current_  │
│    760 │   │   │   # Split or not split?                                                         │
│ ❱  761 │   │   │   modules_children = [] if isinstance(module, nn.Parameter) else list(module.n  │
│    762 │   │   │   if verbose:                                                                   │
│    763 │   │   │   │   print(                                                                    │
│    764 │   │   │   │   │   f"Not enough space on {devices[current_device]} to put {name} (space  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'Tensor' object has no attribute 'named_children'

### Expected behavior

can you tell me how to solve this problem?

**Comment by muellerzr** [comment]
cc @SunMarc
