### ISSUE TITLE
How to load model to specified GPU devices?

### ISSUE THREAD

**Issue by davidluciolu** [huggingface/accelerate#2347]
I'm trying a large model LLaVA1.5.

I know that if I set the parameter `device_map='auto'` in `LlavaMPTForCausalLM.from_pretrained`, the model will be loaded on all visible GPUs (FSDP).

Now I hope to load LLaVA1.5 on some of the visible GPUs, still in the FSDP mode, and automatically decide device_map like `device_map='auto'`. Note that the GPUs can be **arbitrarily assigned**, i.e. GPU 2, 3, 4, but not starting with GPU 0. 
I try to achieve this by passing a `max_memory`, like
`model = LlavaMPTForCausalLM.from_pretrained(model_path,device_map='auto', max_memory={2: 33271054336, 3: 33271054336, 4: 33271054336})`

However, an error occured
![image](https://github.com/huggingface/accelerate/assets/46648807/85a2eafc-ac94-4122-aae3-9a105d631f96)

I think the loop should be modified?
Or is there are any simpler ways to achieve my goal?

**Comment by yukyeongmin** [comment]
Have you tried to set CUDA_VISIBLE_DEVICES=2,3,4?
Like `CUDA_VISIBLE_DEVICES=2,3,4 accelerate launch code.py`

**Comment by davidluciolu** [comment]
> Have you tried to set CUDA_VISIBLE_DEVICES=2,3,4? Like `CUDA_VISIBLE_DEVICES=2,3,4 accelerate launch code.py`

I want to load LLaVA1.5 on GPU2,3,4, but another model on GPU 0,1, in one code.
