### ISSUE TITLE
Mps isn't being recognized when I run accelerate config Apple M2

### ISSUE THREAD

**Issue by midescribba** [huggingface/accelerate#2348]
### System Info

```Shell
- `Accelerate` version: 0.25.0
- Platform: macOS-14.1.1-arm64-arm-64bit
- Python version: 3.9.6
- Numpy version: 1.26.3
- PyTorch version (GPU?): 2.0.0 (False)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 16.00 GB
- `Accelerate` default config:
	- compute_environment: LOCAL_MACHINE
	- distributed_type: NO
	- mixed_precision: no
	- use_cpu: False
	- debug: False
	- num_processes: 1
	- machine_rank: 0
	- num_machines: 1
	- gpu_ids: all
	- rdzv_backend: static
	- same_network: True
	- main_training_function: main
	- downcast_bf16: no
	- tpu_use_cluster: False
	- tpu_use_sudo: False
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

Run `accelerate config` I get the options:  
`No distributed training
    multi-CPU
    multi-XPU
    multi-GPU
    multi-NPU
    TPU`

### Expected behavior

I expected to be able to use mps as the machine.

**Comment by menglingtong** [comment]
Same issue, no MPS in the list. please let me know if u have a solution

**Comment by muellerzr** [comment]
You no longer need to specify MPS, just select "No distributed training" in the CLI.
