### ISSUE TITLE
Query Regarding Gradient Scaling for bfloat16 in Accelerator

### ISSUE THREAD

**Issue by jytime** [huggingface/accelerate#2358]
Hi Team,

While working with the Accelerator, I noticed that we do not unscale the gradients for mixed precision with bfloat16. Specifically, no GradScaler is defined for bfloat16 as seen in the following code snippet:

https://github.com/huggingface/accelerate/blob/5ec00da2befbe9fa666f1bee8bdb1dd4daf713e3/src/accelerate/accelerator.py#L430-L460

Moreover, the accelerator.clip_grad_norm_() function, which calls unscale_gradients() to unscale the gradients, does not seem to apply to bfloat16 either.

However, in the document of [pytorch amp](https://pytorch.org/docs/stable/amp.html), it seems to imply that we need to use GradScaler for bfloat16.

As a new finger in this area, I was wondering is there a specific reason we don't use gradient scaling for bfloat16? If so, probably it is better to include this information in the Accelerator's documentation?

Best,
Jianyuan

**Comment by SunMarc** [comment]
Hi @jytime, bloat16 do not need gradient scaling compared to float16. I can't find the information in the doc you shared.

**Comment by jytime** [comment]
Thanks for the clarification!
