### ISSUE TITLE
Dynamic batch size

### ISSUE THREAD

**Issue by pengzhangzhi** [huggingface/accelerate#2359]
Hi there! just want to mention the possibility of implementing dynamic batch size during training. The size of the batch is determined by the max memory of the GPU such that we can use all the memories of the GPU. 

Just to add more context. I am using dynamic padding so that the sequence length of a batch is dynamic during the training. I observed that the memory usage in different iterations is also different. Therefore I am thinking about constructing a batch based on max num of tokens (determined by the memory limit).

**Comment by pengzhangzhi** [comment]
A simple idea would be load a huge amount of sequences and remove a few based on the max token limit.

**Comment by muellerzr** [comment]
You can use the batch_size finder to help with this currently, though it's exponential decay of the batch size: https://github.com/huggingface/accelerate/blob/main/examples/by_feature/memory.py

https://huggingface.co/docs/accelerate/v0.26.1/en/basic_tutorials/troubleshooting#findexecutablebatchsize

**Comment by ZhongQiyu** [comment]
> A simple idea would be load a huge amount of sequences and remove a few based on the max token limit.

You would need to consider the clips that overload or overshot the max-token-limit. It might be an option to take the average on the grand dataset instead of the single implementation.
