### ISSUE TITLE
different seed for each device

### ISSUE THREAD

**Issue by ZhiyuanChen** [huggingface/accelerate#236]
Current `set_seed` implementation set the same seed for every devices, which could results the same data agumentation applied for each data across the process and damage model performance. Consider set different random seed for each device, such as:
```python
    def init_seed(self):
        """
        Set up random seed
        """
        torch.manual_seed(self.rank + self.seed)
        torch.cuda.manual_seed(self.rank + self.seed)
        np.random.seed(self.rank + self.seed)
        random.seed(self.rank + self.seed)
```

**Comment by sgugger** [comment]
This is just a small utility function, setting the same or a different seed for each process is the responsibility of the user. You can call it in your script with `set_seed(seed + accelerator.process_index)` for instance.

But I'll see if we can add a boolean argument to do what you suggest!
