### ISSUE TITLE
Not able to load peft (promt-tuned) model in multi-gpu settings for inference

### ISSUE THREAD

**Issue by dineshkh** [huggingface/accelerate#2360]
I have prompt tuned the ``Falcon-7B-Instruct model``. Now, I want to perform inference using prompt tuned model in multi-gpu settings using ``accelerate``. I am using 2 A100 gpus and batch size of 1 on each gpu.

my code:

`- `Accelerate` version: 0.25.0
- Platform: Linux-4.18.0-477.15.1.el8_8.x86_64-x86_64-with-glibc2.28
- Python version: 3.11.2
- Numpy version: 1.24.1
- PyTorch version (GPU?): 2.1.2+cu118 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 2003.40 GB
- GPU type: NVIDIA A100-SXM4-80GB
- `Accelerate` default config:
	Not found`

I am getting following error:

`Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████| 2/2 [00:10<00:00,  5.17s/it]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████| 2/2 [00:10<00:00,  5.17s/it]
Traceback (most recent call last):
  File "/dccstor/dinesh/distillation_prompt_tuning/slot_filling_inference_accelerate.py", line 121, in <module>
    app.run(main)
  File "/dccstor/dinesh/conda_environments/kd_promt/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/dccstor/dinesh/conda_environments/kd_promt/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/dccstor/dinesh/distillation_prompt_tuning/slot_filling_inference_accelerate.py", line 51, in main
    model = PeftModel.from_pretrained(model, FLAGS.ckpt_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dccstor/dinesh/conda_environments/kd_promt/lib/python3.11/site-packages/peft/peft_model.py", line 352, in from_pretrained
    model.load_adapter(model_id, adapter_name, is_trainable=is_trainable, **kwargs)
  File "/dccstor/dinesh/conda_environments/kd_promt/lib/python3.11/site-packages/peft/peft_model.py", line 689, in load_adapter
    adapters_weights = load_peft_weights(model_id, device=torch_device, **hf_hub_download_kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dccstor/dinesh/conda_environments/kd_promt/lib/python3.11/site-packages/peft/utils/save_and_load.py", line 270, in load_peft_weights
    adapters_weights = safe_load_file(filename, device=device)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dccstor/dinesh/conda_environments/kd_promt/lib/python3.11/site-packages/safetensors/torch.py", line 310, in load_file
    result[k] = f.get_tensor(k)
                ^^^^^^^^^^^^^^^
RuntimeError: CUDA error: CUDA-capable device(s) is/are busy or unavailable
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

{'ckpt_path': '/dccstor/dinesh/prompt_tuning/falcon-7b-instruct/20240117-071924/slot_filling_tiiuae/falcon-7b-instruct_ckpt_step_4000', 'dataset_path': '/dccstor/dinesh/distillation_prompt_tuning/my_data_new/full_data_15Dec23/slot_filling_data_nomal_slot_lib', 'output_file_path': '/dccstor/dinesh/prompt_tuning/test_output_4000.jsonl', 'max_new_tokens': 200}
[2024-01-21 05:35:10,311] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 1955936 closing signal SIGTERM
[2024-01-21 05:35:10,521] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 1 (pid: 1955937) of binary: /dccstor/dinesh/conda_environments/kd_promt/bin/python3.1
Traceback (most recent call last):
  File "/dccstor/dinesh/conda_environments/kd_promt/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/dccstor/dinesh/conda_environments/kd_promt/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/dccstor/dinesh/conda_environments/kd_promt/lib/python3.11/site-packages/accelerate/commands/launch.py", line 1008, in launch_command
    multi_gpu_launcher(args)
  File "/dccstor/dinesh/conda_environments/kd_promt/lib/python3.11/site-packages/accelerate/commands/launch.py", line 666, in multi_gpu_launcher
    distrib_run.run(args)
  File "/dccstor/dinesh/conda_environments/kd_promt/lib/python3.11/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/dccstor/dinesh/conda_environments/kd_promt/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dccstor/dinesh/conda_environments/kd_promt/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:`

My configuration:

`- `Accelerate` version: 0.25.0
- Platform: Linux-4.18.0-477.15.1.el8_8.x86_64-x86_64-with-glibc2.28
- Python version: 3.11.2
- Numpy version: 1.24.1
- PyTorch version (GPU?): 2.1.2+cu118 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 2003.40 GB
- GPU type: NVIDIA A100-SXM4-80GB
- `Accelerate` default config:
	Not found`

**Comment by geronimi73** [comment]
could you please share the code in ```slot_filling_inference_accelerate.py```?

**Comment by dineshkh** [comment]
@geronimi73 sorry for late reply. Below is the code:

```
 def main(_):
    FLAGS = flags.FLAGS
    config = PeftConfig.from_pretrained(FLAGS.ckpt_path)
    model = AutoModelForCausalLM.from_pretrained(config.base_model_name_or_path, torch_dtype=torch.bfloat16, attn_implementation="flash_attention_2")
    model = PeftModel.from_pretrained(model, FLAGS.ckpt_path)
    model_state_dict = model.state_dict()
    tokenizer = AutoTokenizer.from_pretrained(config.base_model_name_or_path)
    model.to(device)
    model.eval()
    test_directory_path = FLAGS.dataset_path
    data_files = {"test": test_directory_path+'/*.jsonl'}
    test_dataset = load_dataset('json', data_files=data_files)
    #test_dataset = test_dataset.remove_columns(["dialogue_id", "turn_id", "random_slot_title_map", "approx_tokens_in_input", "data_source"])
    list_of_dicts = []
    for i in tqdm(range(len(test_dataset["test"]))):
        with torch.no_grad():
            temp_dict = copy.deepcopy(test_dataset["test"][i])
            input_string = test_dataset["test"][i]["input"] + "\nSlots:\n"
            inputs = tokenizer(input_string, return_tensors="pt")
            #print(input_string)
            inputs = {k: v.to(device) for k, v in inputs.items()}
            outputs = model.generate(input_ids=inputs["input_ids"], attention_mask=inputs["attention_mask"], max_new_tokens=FLAGS.max_new_tokens)
            #print(outputs.shape)
            num_input_tokens = inputs["input_ids"].shape[1]
            #print(num_input_tokens)
            #print(outputs[:,num_input_tokens:].shape)
            output_string = tokenizer.batch_decode(outputs[:, num_input_tokens:].detach().cpu().numpy(), skip_special_tokens=True)[0]
            #print(output_string)
            temp_dict["generated_text"] = output_string
            print(input_string, flush=True)
            print(output_string, flush=True)
            temp_dict["data_name"] = "slot_filling_data-normal-slot-library"
            list_of_dicts.append(temp_dict)
    save_jsonl_files(list_of_dicts,  FLAGS.output_file_path)
```

**Comment by geronimi73** [comment]
ok, so it seems like the adapter merging already fails but there's not enough code to figure out what's wrong. not sure if this is related to accelerate at all.
2 options:
* start with some minimal example. single GPU. no accelerate. make it work on a single GPU and then move to multiple GPUs
* or you provide the entire code and weights and i'll try to reproduce it

**Comment by dineshkh** [comment]
@geronimi73 I have updated the code above, please check now
Here is one checkpoint: [falcon-7b-instruct_ckpt_step_4000.zip](https://github.com/huggingface/accelerate/files/14121322/falcon-7b-instruct_ckpt_step_4000.zip)

Also, without using accelerate I am able to run inference on single GPU ?

**Comment by geronimi73** [comment]
> Also, without using accelerate I am able to run inference on single GPU ?

with a 7B model? yes

**Comment by dineshkh** [comment]
@geronimi73 sorry for incorrect statement above (I have corrected it). 
I am able to do inference with prompt tuned 7B model on single gpu without accelerate.

**Comment by dineshkh** [comment]
@geronimi73 any pointers on what is the issue here.

I have tried loading the base model (`tiiuae/falcon-7b-instruct`) without any PEFT adapter that worked. I have loaded the base model using accelerate on 2 GPUs. The `falcon-7b-instruct` model is in `.bin` format, not in the `safetensors` format. Therefore, I tried loading `mistralai/Mistral-7B-v0.1` which is in `safetensors` format and that also worked.

**Comment by pacman100** [comment]
Hello @dineshkh, could you please share a minimal reproducible example with a ckpt that we too can access, the versions of the libraries such as Accelerate, PEFt and Transformers along with the launch command?

**Comment by dineshkh** [comment]
@pacman100 here is the minimal reproducible example.

```
from peft import PeftModel, PeftConfig
from transformers import AutoModelForCausalLM
import torch
from absl import flags
from absl import app
from accelerate import Accelerator
from accelerate.utils import gather_object

device = "cuda"
flags.DEFINE_string('ckpt_path', None, help='checkpoint path')

def main(_):
    FLAGS = flags.FLAGS
    accelerator = Accelerator()
    # each GPU creates a string
    message = [f"Hello this is GPU {accelerator.process_index}"]
    # collect the messages from all GPUs
    messages = gather_object(message)

    # output the messages only on the main process with accelerator.print()
    accelerator.print(messages)

    config = PeftConfig.from_pretrained(FLAGS.ckpt_path)
    model = AutoModelForCausalLM.from_pretrained(config.base_model_name_or_path, torch_dtype=torch.bfloat16, attn_implementation="flash_attention_2")
    model = PeftModel.from_pretrained(model, FLAGS.ckpt_path, is_trainable=False)
    model = model.to(accelerator.device)

if __name__ == '__main__':
    app.run(main)
```

Here is the checkpoint:
[falcon-7b-instruct_ckpt_step_4000.zip](https://github.com/huggingface/accelerate/files/14209279/falcon-7b-instruct_ckpt_step_4000.zip)

**launch command:**

`accelerate launch slot_filling_inference_accelerate_demo.py --ckpt_path falcon-7b-instruct_ckpt_step_4000`


```
accelerate                0.25.0                   pypi_0    pypi
peft                      0.7.1                    pypi_0    pypi
python                    3.11.2               h7a1cb2a_0
safetensors               0.4.1                    pypi_0    pypi
tokenizers                0.15.0                   pypi_0    pypi
torch                     2.1.2+cu118              pypi_0    pypi
torchvision               0.16.2+cu118             pypi_0    pypi
transformers              4.36.2                   pypi_0    pypi
```

**Comment by geronimi73** [comment]
> minimal reproducible example

cannot reproduce the errors. had to adapt the code for a jupyter notebook (see below) and it runs without errors.

```python
from accelerate import notebook_launcher

# device = "cuda"
# flags.DEFINE_string('ckpt_path', None, help='checkpoint path')

ckpt_path="falcon-7b-instruct_ckpt_step_4000"

def main():
    from peft import PeftModel, PeftConfig
    from transformers import AutoModelForCausalLM
    import torch
    # from absl import flags
    # from absl import app
    from accelerate import Accelerator
    from accelerate.utils import gather_object
    
    # FLAGS = flags.FLAGS
    accelerator = Accelerator()
    # each GPU creates a string
    message = [f"Hello this is GPU {accelerator.process_index}"]
    # collect the messages from all GPUs
    messages = gather_object(message)

    # output the messages only on the main process with accelerator.print()
    accelerator.print(messages)

    # config = PeftConfig.from_pretrained(FLAGS.ckpt_path)
    config = PeftConfig.from_pretrained(ckpt_path)
    model = AutoModelForCausalLM.from_pretrained(
        config.base_model_name_or_path, 
        torch_dtype=torch.bfloat16, 
        attn_implementation="flash_attention_2"
    )
    # model = PeftModel.from_pretrained(model, FLAGS.ckpt_path, is_trainable=False)
    model = PeftModel.from_pretrained(model, ckpt_path, is_trainable=False)
    model = model.to(accelerator.device)
    print(model.device)

# if __name__ == '__main__':
#     app.run(main)
# main()
notebook_launcher(main, num_processes=2)  
```
output
```
Launching training on 2 GPUs.
['Hello this is GPU 0', 'Hello this is GPU 1']
```

```
accelerate==0.26.1
peft==0.8.1
safetensors==0.4.2
tokenizers==0.15.1
torch==2.1.0
transformers==4.37.2
```

**Comment by geronimi73** [comment]
i managed to reproduce the error. could you please show me the exact command you use to launch the script ie. `accelerate launch ..` and the output of `nvidia-smi`?

**Comment by dineshkh** [comment]
**Command :** 
`accelerate launch slot_filling_inference_accelerate_demo.py --ckpt_path ./test_peft/falcon-7b-instruct_ckpt_step_4000`

**Output:** 
```

The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `2`
		More than one GPU was found, enabling multi-GPU training.
		If this was unintended please pass in `--num_processes=1`.
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
W0212 15:22:21.893285 22989373785152 logging.py:61] Detected kernel version 4.18.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
['Hello this is GPU 0', 'Hello this is GPU 1']
You are attempting to use Flash Attention 2.0 with a model not initialized on GPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`.
You are attempting to use Flash Attention 2.0 with a model not initialized on GPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`.
Loading checkpoint shards:   0%|                                                                             | 0/2 [00:00<?, ?it/s]/dccstor/dinesh/conda_environments/kd_promt/lib/python3.11/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
/dccstor/dinesh/conda_environments/kd_promt/lib/python3.11/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████| 2/2 [00:42<00:00, 21.02s/it]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████| 2/2 [00:42<00:00, 21.06s/it]
Traceback (most recent call last):
  File "/dccstor/dinesh/distillation_prompt_tuning/slot_filling_inference_accelerate_demo.py", line 28, in <module>
    app.run(main)
  File "/dccstor/dinesh/conda_environments/kd_promt/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/dccstor/dinesh/conda_environments/kd_promt/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/dccstor/dinesh/distillation_prompt_tuning/slot_filling_inference_accelerate_demo.py", line 24, in main
    model = PeftModel.from_pretrained(model, FLAGS.ckpt_path, is_trainable=False)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dccstor/dinesh/conda_environments/kd_promt/lib/python3.11/site-packages/peft/peft_model.py", line 354, in from_pretrained
    model.load_adapter(model_id, adapter_name, is_trainable=is_trainable, **kwargs)
  File "/dccstor/dinesh/conda_environments/kd_promt/lib/python3.11/site-packages/peft/peft_model.py", line 695, in load_adapter
    adapters_weights = load_peft_weights(model_id, device=torch_device, **hf_hub_download_kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dccstor/dinesh/conda_environments/kd_promt/lib/python3.11/site-packages/peft/utils/save_and_load.py", line 318, in load_peft_weights
    adapters_weights = safe_load_file(filename, device=device)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dccstor/dinesh/conda_environments/kd_promt/lib/python3.11/site-packages/safetensors/torch.py", line 310, in load_file
    result[k] = f.get_tensor(k)
                ^^^^^^^^^^^^^^^
RuntimeError: CUDA error: CUDA-capable device(s) is/are busy or unavailable
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[2024-02-12 15:23:13,554] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 1 (pid: 789905) of binary: /dccstor/dinesh/conda_environments/kd_promt/bin/python3.1
Traceback (most recent call last):
  File "/dccstor/dinesh/conda_environments/kd_promt/bin/accelerate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/dccstor/dinesh/conda_environments/kd_promt/lib/python3.11/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/dccstor/dinesh/conda_environments/kd_promt/lib/python3.11/site-packages/accelerate/commands/launch.py", line 1014, in launch_command
    multi_gpu_launcher(args)
  File "/dccstor/dinesh/conda_environments/kd_promt/lib/python3.11/site-packages/accelerate/commands/launch.py", line 672, in multi_gpu_launcher
    distrib_run.run(args)
  File "/dccstor/dinesh/conda_environments/kd_promt/lib/python3.11/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/dccstor/dinesh/conda_environments/kd_promt/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dccstor/dinesh/conda_environments/kd_promt/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
```
```

`(/dccstor/dinesh/conda_environments/kd_promt) [dikhand1@cccxc567 distillation_prompt_tuning]$ nvidia-smi
Mon Feb 12 15:25:36 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100-SXM4-80GB          On  | 00000000:0A:00.0 Off |                    0 |
| N/A   23C    P0              59W / 400W |      4MiB / 81920MiB |      0%   E. Process |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-SXM4-80GB          On  | 00000000:44:00.0 Off |                    0 |
| N/A   23C    P0              60W / 400W |      4MiB / 81920MiB |      0%   E. Process |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+`
```

**Comment by geronimi73** [comment]
try this pls:

```python
from peft import PeftModel, PeftConfig
from transformers import AutoModelForCausalLM
import torch
from absl import flags
from absl import app
from accelerate import Accelerator
from accelerate.utils import gather_object

device = "cuda"
flags.DEFINE_string('ckpt_path', None, help='checkpoint path')

def main(_):
    FLAGS = flags.FLAGS
    accelerator = Accelerator()
    # each GPU creates a string
    message = [f"Hello this is GPU {accelerator.process_index}"]
    # collect the messages from all GPUs
    messages = gather_object(message)

    # output the messages only on the main process with accelerator.print()
    accelerator.print(messages)

    config = PeftConfig.from_pretrained(FLAGS.ckpt_path)
    model = AutoModelForCausalLM.from_pretrained(
        config.base_model_name_or_path, 
        torch_dtype=torch.bfloat16, 
        attn_implementation="flash_attention_2"
        device_map={"": accelerator.process_index},
    )
    model = PeftModel.from_pretrained(model, FLAGS.ckpt_path, is_trainable=False)
    # model = model.to(accelerator.device)

if __name__ == '__main__':
    app.run(main)
```

**Comment by dineshkh** [comment]
@geronimi73 getting the same error with above code as well.

**Comment by geronimi73** [comment]
does it run on a single GPU? ie. like this

```bash
export CUDA_VISIBLE_DEVICES=0
python3 slot_filling_inference_accelerate_demo.py --ckpt_path ./test_peft/falcon-7b-instruct_ckpt_step_4000
```

**Comment by dineshkh** [comment]
Yes, this is working
```
python3 slot_filling_inference_accelerate_demo.py --ckpt_path ./test_peft/falcon-7b-instruct_ckpt_step_4000
W0213 03:41:28.766963 22602687669312 logging.py:61] Detected kernel version 4.18.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
['Hello this is GPU 0']
Loading checkpoint shards:   0%|                                                                             | 0/2 [00:00<?, ?it/s]/dccstor/dinesh/conda_environments/kd_promt/lib/python3.11/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████| 2/2 [03:53<00:00, 116.90s/it]
```

**Comment by dineshkh** [comment]
`accelerate launch slot_filling_inference_accelerate_demo.py --num_processes 1 --ckpt_path ./test_peft/falcon-7b-instruct_ckpt_step_4000` -> Works 
`accelerate launch slot_filling_inference_accelerate_demo.py --num_processes 2 --ckpt_path ./test_peft/falcon-7b-instruct_ckpt_step_4000` -> gives error

**Comment by dineshkh** [comment]
above also fails for me. still facing the issue.

**Comment by muellerzr** [comment]
Looking at https://github.com/pytorch/pytorch/issues/100691, its likely some process is still using the GPU when doing things. Try running `nvidia-smi -g 0 -c 0`

**Comment by sidtandon2014** [comment]
@geronimi73: Did you find any resolution for this? I think while loading weights to model (https://github.com/huggingface/peft/blob/v0.10.0/src/peft/peft_model.py#L730) is loading everything on GPU:0 because while loading the PEFT weights there are 8 processes running on GPU0 and only 1 process on other GPUs)

**Comment by geronimi73** [comment]
> @geronimi73: Did you find any resolution for this? I think while loading weights to model (https://github.com/huggingface/peft/blob/v0.10.0/src/peft/peft_model.py#L730) is loading everything on GPU:0 because while loading the PEFT weights there are 8 processes running on GPU0 and only 1 process on other GPUs)

can't solve because can't reproduce. give me access to your machine 😉 and i'll see what i can do

**Comment by zzaebok** [comment]
I am currently facing the same issue. @dineshkh did you find the reason of the problem?

**Comment by dineshkh** [comment]
@zzaebok I can't find the reason or solution for the problem. 
Can you provide more details about your setting?

**Comment by yujianll** [comment]
@dineshkh Hi, I have the same issue when loading a trained LoRA adapter for further fine-tuning. Everything works fine if I use a single GPU but fails on multi-GPU. I wonder if you find any solutions?
