### ISSUE TITLE
how to prevent accelerate from concatenating tensors in batch? 

### ISSUE THREAD

**Issue by feiyangsuo** [huggingface/accelerate#2367]
My `collate_fn` in dataloader returns a list of image tensors with different height and width. After using `accelerator.prepare(model, optimizer, dataloader)`, I noticed that accelerate seems to automatically concatenate the tensors during `for step, batch in enumerate(train_dataloader)` iteration, and the size-mismatch leads to Exceptions. 
Is there any parameter to prevent the auto-concatenating?
Or, should I remove `dataloader` from `accelerator.prepare` params?

**Comment by muellerzr** [comment]
You need to remove it, or try setting `dispatch_batches=False` in the `Accelerator()` init.

**Comment by feiyangsuo** [comment]
> You need to remove it, or try setting `dispatch_batches=False` in the `Accelerator()` init.

Seems `dispatch_batches=False` works. While it's still bewildering me that some elements returned now are wrapped with an additional list ... maybe there's still bug in my code? Anyway there's no information lost so I currently solve the problem by adding a `[0]` index to them

**Comment by feiyangsuo** [comment]
> You need to remove it, or try setting `dispatch_batches=False` in the `Accelerator()` init.

both methods work. thanks
