### ISSUE TITLE
typing (list/tuple/dict) in accelerate.utils

### ISSUE THREAD

**Issue by ZhiyuanChen** [huggingface/accelerate#237]
Hi, 

I can't help noticing the typing in accelerate.utils is a bit messy.

The type check for `dict` is actually `Mapping` (which I think is a better approach as it allows user defined `Mapping`, maybe there needs some doc work.
And the type check for list/tuple is `(list, tuple)` which I believe `Sequence` could works better. 

Also, https://github.com/huggingface/accelerate/blob/main/src/accelerate/utils.py#L119-L122 has specific behavior for type `namedtuple` and may not work with some other type, maybe it's better to use EAFP here?

```python
    try:
        return type(obj)(generator)
    except TypeError:
        return type(obj)(*list(generator))
```

**Comment by sgugger** [comment]
`Mapping` only checks the class implements a couple of methods, it offers no guarantee that you can instantiate an object of that class with a dictionary. Same for the check for `list/tuple`, `Sequence` does not guarantee you can instantiate the object with a generator.

Your suggestion for the re-instantiation of a list/tuple/namedtuple sounds great! If you'd like to make a PR of it that would be awesome!

**Comment by ZhiyuanChen** [comment]
> Mapping only checks the class implements a couple of methods, it offers no guarantee that you can instantiate an object of that class with a dictionary. Same for the check for list/tuple, Sequence does not guarantee you can instantiate the object with a generator.

Yes, objects like `range()` are `Sequence` but definitely not what we wanted. In this case, maybe we should make all `Mapping` `Dict`?

> Your suggestion for the re-instantiation of a list/tuple/namedtuple sounds great! If you'd like to make a PR of it that would be awesome!

Submitted~

**Comment by sgugger** [comment]
Ah yes, I forgot we were already using `Mapping`. We just need to make sure the check covers both `dict` and `UserDict`, so if `Dict` covers both, let's roll with that!

**Comment by ZhiyuanChen** [comment]
> Ah yes, I forgot we were already using `Mapping`. We just need to make sure the check covers both `dict` and `UserDict`, so if `Dict` covers both, let's roll with that!

I just did a small check, it seems Dict covers Dict and OrderedDict but not UserDict...

**Comment by sgugger** [comment]
Ok, so let's keep `Mapping` for now to keep it simple.
