### ISSUE TITLE
Stuck at training controlnet with multi_node with single gpu

### ISSUE THREAD

**Issue by Xelawk** [huggingface/accelerate#2373]
### System Info

```Shell
- `Accelerate` version: 0.26.1
- Platform: Linux-5.4.0-169-generic-x86_64-with-glibc2.31
- Python version: 3.10.13
- Numpy version: 1.23.5
- PyTorch version (GPU?): 2.0.1+cu118 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 251.42 GB
- GPU type: NVIDIA GeForce RTX 3090
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: no
        - use_cpu: False
        - debug: True
        - num_processes: 2
        - machine_rank: 0
        - num_machines: 2
        - gpu_ids: 0
        - main_process_ip: 10.12.64.73
        - main_process_port: 6860
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
```
I am trying to train a controlnet using multi_node with single gpu but encountering an issue where the program gets stuck at follow code:. 

```python
    with accelerator.main_process_first():
        print("start setting the training transforms...")
        if args.max_train_samples is not None:
            dataset["train"] = dataset["train"].shuffle(seed=args.seed).select(range(args.max_train_samples))
        # Set the training transforms
        train_dataset = dataset["train"].with_transform(preprocess_train)
```

When I attempt to remove `with accelerator.main_process_first():`, the program then gets stuck again at the follow code:
```python
    logger.info("Prepare everything with our accelerator")
    controlnet, optimizer, train_dataloader, lr_scheduler = accelerator.prepare(
        controlnet, optimizer, train_dataloader, lr_scheduler
    )
```

The program outputs:
```shell
2024-01-24 16:59:46.483456: I tensorflow/core/util/[port.cc:113](http://port.cc:113/)] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-01-24 16:59:46.511379: I tensorflow/core/platform/[cpu_feature_guard.cc:182](http://cpu_feature_guard.cc:182/)] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
01/24/2024 16:59:47 - INFO - __main__ - Distributed environment: MULTI_GPU  Backend: nccl
Num processes: 2
Process index: 0
Local process index: 0
Device: cuda:0

Mixed precision type: no

You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
{'sample_max_value', 'prediction_type', 'thresholding', 'timestep_spacing', 'variance_type', 'dynamic_thresholding_ratio', 'clip_sample_range'} was not found in config. Values will be initialized to default values.
{'force_upcast', 'scaling_factor'} was not found in config. Values will be initialized to default values.
{'addition_embed_type_num_heads', 'conv_in_kernel', 'resnet_out_scale_factor', 'upcast_attention', 'class_embed_type', 'transformer_layers_per_block', 'num_attention_heads', 'num_class_embeds', 'dual_cross_attention', 'mid_block_only_cross_attention', 'timestep_post_act', 'addition_time_embed_dim', 'cross_attention_norm', 'only_cross_attention', 'use_linear_projection', 'mid_block_type', 'time_embedding_dim', 'time_embedding_act_fn', 'encoder_hid_dim_type', 'addition_embed_type', 'time_cond_proj_dim', 'conv_out_kernel', 'projection_class_embeddings_input_dim', 'time_embedding_type', 'resnet_skip_time_act', 'resnet_time_scale_shift', 'reverse_transformer_layers_per_block', 'encoder_hid_dim', 'class_embeddings_concat', 'dropout', 'attention_type'} was not found in config. Values will be initialized to default values.
01/24/2024 16:59:51 - INFO - __main__ - Initializing controlnet weights from unet
01/24/2024 16:59:53 - INFO - __main__ - accelerator.register_save_state_pre_hook(save_model_hook)...
01/24/2024 16:59:53 - INFO - __main__ - accelerator.register_load_state_pre_hook(load_model_hook)
01/24/2024 16:59:55 - INFO - __main__ - Optimizer creation
01/24/2024 16:59:55 - INFO - __main__ - make train dataset
01/24/2024 16:59:55 - INFO - __main__ - loading dataset from /appdata2/dataset/controlnet_dataset/huggingface_dataset/yq_avatar_facial_grey_512x512_20240123_debug
01/24/2024 16:59:55 - INFO - __main__ - dataset with_transform (preprocess_train)
start setting the training transforms...
2e65e5aee658:1918299:1918299 [0] NCCL INFO Bootstrap : Using eth0:[172.18.0.2](http://172.18.0.2/)<0>
2e65e5aee658:1918299:1918299 [0] NCCL INFO NET/Plugin : No plugin found ([libnccl-net.so](http://libnccl-net.so/)), using internal implementation
2e65e5aee658:1918299:1918299 [0] NCCL INFO cudaDriverVersion 11070
NCCL version 2.14.3+cuda11.8
2e65e5aee658:1918299:1918585 [0] NCCL INFO NET/IB : No device found.
2e65e5aee658:1918299:1918585 [0] NCCL INFO NET/Socket : Using [0]eth0:[172.18.0.2](http://172.18.0.2/)<0>
2e65e5aee658:1918299:1918585 [0] NCCL INFO Using network Socket
```

The console output ends with `2e65e5aee658:1918299:1918585 [0] NCCL INFO Using network Socket` and the program remains stuck, unable to proceed normally. Notably, the program can execute the training code normally when using a single GPU on a single machine.

I would appreciate any assistance in resolving this issue. Thank you.

**Comment by muellerzr** [comment]
How are you launching the code?

**Comment by Xelawk** [comment]
> How are you launching the code?

export ACCELERATE_CONFIG_PATH=default_config.yml

export NCCL_DEBUG=INFO

accelerate launch --config_file ${ACCELERATE_CONFIG_PATH} examples/controlnet/train_controlnet.py \
  --pretrained_model_name_or_path="runwayml/stable-diffusion-v1-5" \
  --output_dir="/xxx" \
  --train_data_dir="/xxx" \
  --conditioning_image_column=source_img \
  --image_column=target_img \
  --caption_column=tags \
  --resolution=512 \
  --lr_num_cycles=1 \
  --learning_rate=5e-6 \
  --lr_scheduler=cosine_with_restarts \
  --num_train_epochs=5 \
  --train_batch_size=4 \
  --gradient_accumulation_steps=1 \
  --tracker_project_name="xxx" \
  --enable_xformers_memory_efficient_attention \
  --checkpointing_steps=10000

**Comment by Xelawk** [comment]
> How are you launching the code?

here is the source [code](https://github.com/huggingface/diffusers/blob/main/examples/controlnet/train_controlnet.py)

**Comment by muellerzr** [comment]
What does the config look like on the other machine?

**Comment by Xelawk** [comment]
> What does the config look like on the other machine?

another machine config:
- `Accelerate` version: 0.26.1                                                                                                                     
- Platform: Linux-5.8.0-43-generic-x86_64-with-glibc2.31                                                                                           
- Python version: 3.10.13                                                                                                                          
- Numpy version: 1.23.5                                                                                                                            
- PyTorch version (GPU?): 2.0.1+cu118 (True)                                                                                                       
- PyTorch XPU available: False                                                                                                                     
- PyTorch NPU available: False                                                                                                                     
- System RAM: 188.43 GB                                                                                                                            
- GPU type: NVIDIA GeForce RTX 3090                                                                                                                
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: no
        - use_cpu: False
        - debug: True
        - num_processes: 2
        - machine_rank: 1
        - num_machines: 2
        - gpu_ids: 0
        - main_process_ip: 10.12.64.73
        - main_process_port: 6860
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []

**Comment by Xelawk** [comment]
please help
