### ISSUE TITLE
Python 3.12 distutils deprecation error

### ISSUE THREAD

**Issue by AieatAssam** [huggingface/accelerate#2379]
### System Info

```Shell
accelerate 0.26.1, Windows 11, Python 3.12.1
```

### Information

- [ ] The official example scripts
- [x] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

To reproduce behaviour:
1. In Python 3.12 install latest accelerate with
` pip3 install accelerate --upgrade `
2. Try to initialise accelerate with:
```python
from accelerate import Accelerator
accelerator = Accelerator()
```

This results in the error caused by https://github.com/huggingface/accelerate/blob/f88661b5d9f4977b5a1555a92e64ef3cd359cbc9/src/accelerate/utils/environment.py#L19

![image](https://github.com/huggingface/accelerate/assets/7803161/8b88d142-cf67-43b5-9b02-3f9346baa02a)
The fundamental issue is deprecation of distutils as part of https://peps.python.org/pep-0632/

### Expected behavior

Accelerate should not depend on deprecated package and be compatible with Python 3.12+

**Comment by muellerzr** [comment]
Thanks! It looks like we should replace this with `shutil.which` instead (with zero logic changes)

would you like to make a PR?

**Comment by AieatAssam** [comment]
> Thanks! It looks like we should replace this with `shutil.which` instead (with zero logic changes)
> 
> would you like to make a PR?

Sure. I’ll look into it next week. Does seem fairly straightforward.
