### ISSUE TITLE
Save checkpoint with DeepSpeed Zero3

### ISSUE THREAD

**Issue by Hannibal046** [huggingface/accelerate#2380]
### System Info

- `Accelerate` version: 0.22.0
- Platform: Linux-5.15.0-1050-azure-x86_64-with-glibc2.31
- Python version: 3.10.13
- Numpy version: 1.26.3
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 1771.74 GB
- GPU type: NVIDIA A100-SXM4-80GB
- `Accelerate` default config:
        Not found

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

Hi, I am asking what is the recommended way to save a model with DeepSpeed Zero3 in accelerate? The following snippet I use would cause the saved parameters don't match with the original ones, even if I didn't perform any update operation:
```python
from accelerate import Accelerator
from transformers import AutoModelForCausalLM
import torch

def save_with_accelerate(accelerator, model, output_dir):
    unwrapped_model = accelerator.unwrap_model(model)
    state_dict = accelerator.get_state_dict(model)
    unwrapped_model.save_pretrained(
        output_dir, 
        is_main_process=accelerator.is_main_process, 
        save_function=accelerator.save, 
        state_dict=state_dict
    )

if __name__ == "__main__":
    accelerator = Accelerator()

    ## init model and dataloader
    dataset = torch.utils.data.TensorDataset(torch.rand(2,2))
    dataloader = torch.utils.data.DataLoader(dataset)
    model = AutoModelForCausalLM.from_pretrained("huggyllama/llama-7b")

    ## prepare
    model,dataloader = accelerator.prepare(model,dataloader)

    ## save
    save_with_accelerate(accelerator,model=model,output_dir="tmp/test_save")
    accelerator.wait_for_everyone()

```

I test it with the original model weight with:
```python
from transformers import AutoModelForCausalLM
model = AutoModelForCausalLM.from_pretrained("huggyllama/llama-7b")

pretrained_path = "tmp/test_save"
tuned_model = AutoModelForCausalLM.from_pretrained(pretrained_path)

import torch
tuned_model_dict = dict(tuned_model.named_parameters())
for n,p in model.named_parameters():
    original_parameters = p
    tuned_parameters = tuned_model_dict[n]
    if not torch.all(torch.lt(torch.abs(torch.add(original_parameters, -tuned_parameters)), 0.001)):
        print("mismatched:",n)
    else:
        print("matched:",n)
```

And this is the results:
![image](https://github.com/huggingface/accelerate/assets/38466901/ea238ece-355f-4888-a9e3-3c0106da4aa7)

### Expected behavior

I thought there would be a perfect match between two weights.

**Comment by Hannibal046** [comment]
BTW, I launched the script with:
```
accelerate launch \
    --mixed_precision no \
    --num_machines 1 \
    --num_processes 8 \
    --use_deepspeed \
    --deepspeed_config_file ds_configs/stage3_no_offloading_accelerate.conf \
    test_accelerate_save.py
```
where the `ds_config` is:
```json
{
    "bf16": {
        "enabled": "auto"
    },
    "zero_optimization": {
        "stage": 3,
        "overlap_comm": true,
        "contiguous_gradients": true,
        "sub_group_size": 1e9,
        "reduce_bucket_size": "auto",
        "stage3_prefetch_bucket_size": "auto",
        "stage3_param_persistence_threshold": "auto",
        "stage3_max_live_parameters": 1e9,
        "stage3_max_reuse_distance": 1e9,
        "stage3_gather_16bit_weights_on_model_save": true
    },
    "gradient_accumulation_steps": "auto",
    "gradient_clipping": "auto",
    "steps_per_print": 1e5,
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "wall_clock_breakdown": false
}
```

**Comment by Hannibal046** [comment]
By changing `--mixed_precision` from `bf16` to `no`. There is a perfect match. This is not the desired behaviour in the case I only want to use `bf16` to train certain parts of the model while keeping the others fixed.

**Comment by xuanyaoming** [comment]
I encounted the exact same problem a few days ago. Is there a solution to finetune a model with fp16 enabled?

**Comment by wangxr1999** [comment]
hello,similar error ,how to solve this problem?

**Comment by JYX1216** [comment]
Hi, I have the same problem. Is there any good solution?
