### ISSUE TITLE
[DOCS] Underscore in certain function, is rendered as italic

### ISSUE THREAD

**Issue by SuperSecureHuman** [huggingface/accelerate#2382]
https://huggingface.co/docs/accelerate/quicktour#use-gradient-clipping

![Screenshot from 2024-01-28 14-46-31](https://github.com/huggingface/accelerate/assets/88489071/fa95e158-71ff-4a70-9744-d302bf67a6d3)

Here, the actual function name is `clip_grad_value_` , but the '_' is converted to italic.

I believe this issue could be there in the other part of the docs, but there is where I noticed first.

**Comment by SunMarc** [comment]
Hi @SuperSecureHuman, thanks for raising the issue. This is something that could be raised [here](https://github.com/huggingface/doc-builder) instead. This is not something we can fix on our side.

**Comment by SuperSecureHuman** [comment]
Got it!  Thanks for the correction, I'll close the issue here, and have it open there
