### ISSUE TITLE
Accelerator State Doesn't Match Config

### ISSUE THREAD

**Issue by cccx3** [huggingface/accelerate#2384]
Hi,

I've been trying to use Accelerate for a muti-GPU use case. I'm running on a GCP VM via Jupyterlab. I've set up a config, as below:
                                                
```
compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
gpu_ids: all
fp16: true
machine_rank: 0
main_process_ip: null
main_process_port: null
num_machines: 1
num_processes: 4
```

Calling accelerate env reflects this config is recognized:

```
- `Accelerate` version: 0.26.1
- Platform: Linux-5.10.0-26-cloud-amd64-x86_64-with-glibc2.31
- Python version: 3.10.13
- Numpy version: 1.25.2
- PyTorch version (GPU?): 2.0.0+cu118 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 51.00 GB
- GPU type: Tesla T4
- `Accelerate` default config:
	- compute_environment: LOCAL_MACHINE
	- distributed_type: MULTI_GPU
	- mixed_precision: fp16
	- use_cpu: False
	- debug: False
	- num_processes: 4
	- machine_rank: 0
	- num_machines: 1
	- rdzv_backend: static
	- same_network: False
	- main_training_function: main
	- downcast_bf16: False
	- tpu_use_cluster: False
	- tpu_use_sudo: False
```

However, when I check the state of the accelerator in my notebook, it's reflected as below:

```
Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: no
```

Also of note: I get a missing XLA error when running accelerate test in the CLI:

```
The combined stderr from workers follows:
terminate called after throwing an instance of 'std::runtime_error'
terminate called after throwing an instance of '  what():  std::runtime_errortensorflow/compiler/xla/xla_client/computation_client.cc:280 : Missing XLA configuration'
```

Any help would be appreciated. My current project is using TRL's PPO for a natural language processing problem; the current model I am trying to use is the GPT-NEO 1.3B. I am new to Accelerate, but the config seemingly being both recognized and not recognized strikes me as odd.

Thanks in advance for any help.

**Comment by muellerzr** [comment]
In your notebook be sure you are using the notebook launcher and follow that tutorial https://huggingface.co/docs/accelerate/basic_tutorials/notebook

the accelerate config entered via the CLI will not matter since this is separate

**Comment by ninellekam** [comment]
i have the same problem(((
