### ISSUE TITLE
Adding py.typed file for distributing type information?

### ISSUE THREAD

**Issue by justin-yan** [huggingface/accelerate#2396]
As a user of `accelerate`, this would be nice in enabling typechecking for usages of accelerate.

It's usually not too much trouble to add: https://peps.python.org/pep-0561/#packaging-type-information

- add a `py.typed` file to the package root
- add this file to the package_data dictionary in the setup.py file

If this is something that the maintainers would be amenable to, I'm more than happy to open a PR for it!

**Comment by muellerzr** [comment]
We generally don't do this for our repos. See more here: https://github.com/huggingface/datasets/issues/3841
