### ISSUE TITLE
Multi-node distributed training failed on A100

### ISSUE THREAD

**Issue by zheyuye** [huggingface/accelerate#240]
I was using 2 training nodes with 2 A100 on each and use simple command `accelerate test`with following config
```
compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: MULTI_GPU
fp16: false
machine_rank: 0
main_process_ip: xxx.xxx.xxx.xx
main_process_port: 1234
main_training_function: main
num_machines: 2
num_processes: 4
```
configure of another machine is quite simlar but carrying different `machine_rank` with value `1`. An error was generated under the basic test command `accelerate test` as below, or you guys can check this full [error log](https://gist.github.com/zheyuye/e1d0ebfd4b988cff3bb1e9b0c725f33a) out ~

```
stderr: *****************************************
stderr: Traceback (most recent call last):
stderr:   File "/usr/local/lib/python3.6/dist-packages/accelerate/test_utils/test_script.py", line 291, in <module>
stderr:     main()
stderr:   File "/usr/local/lib/python3.6/dist-packages/accelerate/test_utils/test_script.py", line 278, in main
stderr:     rng_sync_check()
stderr:   File "/usr/local/lib/python3.6/dist-packages/accelerate/test_utils/test_script.py", line 38, in rng_sync_check
stderr:     synchronize_rng_states(["torch"])
stderr:   File "/usr/local/lib/python3.6/dist-packages/accelerate/utils.py", line 110, in synchronize_rng_states
stderr:     synchronize_rng_state(RNGType(rng_type), generator=generator)
stderr:   File "/usr/local/lib/python3.6/dist-packages/accelerate/utils.py", line 92, in synchronize_rng_state
stderr:     torch.distributed.broadcast(rng_state, 0)
stderr:   File "/usr/local/lib/python3.6/dist-packages/torch/distributed/distributed_c10d.py", line 1159, in broadcast
stderr:     work = default_pg.broadcast([tensor], opts)
stderr: RuntimeError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:957, unhandled system error, NCCL version 21.0.3
stderr: ncclSystemError: System call (socket, malloc, munmap, etc) failed.
```

Here is the environment I used that couse above error message:
```
GPU: NVIDIA A100 SXM 80GB 
Driver Version: 495.29.05
python version: 3.6.9
cuda version: 11.3
pytorch version: 1.10.1+cu113
accelerate: 0.5.1
```
And the same error occurs on `torch==1.9.0+cu111`

**Comment by zheyuye** [comment]
> NCCL errors are usually linked to a problem in the driver/CUDA versions installed. Can you run any other PyTorch distributed script on the same setup? Note that I can't access your error log, the link is 404 for me.

the log link redirect to a gist  file https://gist.githubusercontent.com/zheyuye/e1d0ebfd4b988cff3bb1e9b0c725f33a/raw/cb5df39f8c81cdb698c8ba9f8831e30c4f4d9502/acclerate_test.log.  would you please take a look?

**Comment by Aaryan369** [comment]
Hi, any update on this? I am trying to do the same on multiple A100 machines. 
Any advice on the package versions?
