### ISSUE TITLE
Freeze on accelerate.gather if tensors are not places to different devices

### ISSUE THREAD

**Issue by kkontras** [huggingface/accelerate#2414]
### System Info

```Shell
- `Accelerate` version: 0.26.1
- Platform: Linux-4.18.0-513.5.1.el8_9.x86_64-x86_64-with-glibc2.28
- Python version: 3.9.18
- Numpy version: 1.24.4
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 62.84 GB
- GPU type: NVIDIA GeForce RTX 3060
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: no
        - use_cpu: False
        - debug: False
        - num_processes: 2
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: all
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

 `
model, optimizer, data_loader, scheduler = self.accelerator.prepare( model, optimizer, data_loader, scheduler )

for epoch in range(5):
   for data, label in enumerate(data_loader):
        data = data.cuda()
        label = label.cuda()
        pred = model(data)
        label = label.to(device_0) #error in the code 
        out = {"pred": pred, "label": label}
        out = accelerator.gather(out) #Here code stalls 
`

### Expected behavior

Expected behavior would be to produce an error message that would indicate that there are Tensors we asked to be gathered that belong to the same device or even better gather them despite the issue (if possible). Similar message could be useful when gathered info is not Tensor.

**Comment by BenjaminBossan** [comment]
I could not reproduce the error, could you please give more details?

- full code to reproduce
- accelerate config
- how you launch the script
- what hardware setup you use

**Comment by bibhabasumohapatra** [comment]
device_0 should be replaced with  self.accelerator.device
