### ISSUE TITLE
Code runs without accelerate.prepare 

### ISSUE THREAD

**Issue by cheapkai** [huggingface/accelerate#244]
I missed accelerate.prepare(model, optimiser, data)

Yet the script runs on both gpu and cpu (single) - the rest of the code is as is given in instructions , device = accelerate device .

I wanted to know if it is alright to leave it as it is or i still need to ass accelerate.prepare

**Comment by sgugger** [comment]
The goal of `Accelerate` is to make it easy to train in a distributed setup, so your code won't run in any kind of distributed environment.

Please ask your questions like this on the [forums](https://discuss.huggingface.co/) as we keep the issues for bugs and feature requests only.
