### ISSUE TITLE
Does the recent news about speeding up pytorch model loading apply to huggingface transformers APIs?

### ISSUE THREAD

**Issue by plamb-viso** [huggingface/accelerate#2447]
https://twitter.com/RisingSayak/status/1756634311493890559

Can this apply to using transfomers APIs? Take the below for example:

```python
    model = DistilBertForSequenceClassification.from_pretrained(model_path, local_files_only=True).to(
        torch.device("cpu")
    )
```
Can this be modified to load faster?

**Comment by muellerzr** [comment]
That won't work. You should use exactly his code, or use `low_cpu_mem_usage=True` (and no context manager needed)
