### ISSUE TITLE
I have two optimisers - how do i use the accelerate.prepare

### ISSUE THREAD

**Issue by cheapkai** [huggingface/accelerate#245]
The following are my two optimisers for two parts of the model :

    optim_c = optim(list(model.conditioner.parameters()), **optim_args)
    optim_s = optim(list(model.segmentor.parameters()), **optim_args)

how do i modify the following function call -

accelerate.prepare(model, optimiser, data)

**Comment by sgugger** [comment]
You can pass as many accelerators as you like to the `prepare` method, and you will get back the objects in the same order.
