### ISSUE TITLE
How to initialize Accelerator twice but with different setup within the same code ? 

### ISSUE THREAD

**Issue by soneyahossain** [huggingface/accelerate#2463]
### System Info

```Shell
Hello I want to initialize accelerate once for the training and another time for the inference. 

Looks like it does not work and the error message is not clear. Is there a way to reset the previously initialized accelerate and then initialize with inference setup? 

For training  I am doing : 
    accelerator = Accelerator(kwargs_handlers=[process_group_kwargs])
    model,test_loader, valid_loader, optimizer, scheduler = accelerator.prepare(
                model, test_loader, valid_loader, optimizer, scheduler)

For inference I want to do: accelerator = Accelerator()
model, valid_loader, optimizer = eval_accelerator.prepare(model, valid_loader, optimizer)

For inference, I do no want to use optimizer but I get error as I am using zero_stage: 1, So I used the optimizer I used during training. But then I was getting batch size error for the valid set then I prepare the valid loader one more time after initializing the Accelerator. Still during inference I am getting error on the preparation. 

Any idea how to fix this?
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

1. Initialize Accelerator for training 
2. Once the training is done, initialize again for the inference.  

### Expected behavior

I just want to prepare the accelerate for the inference task once the training is done.

**Comment by BenjaminBossan** [comment]
It is generally not recommended to initialize `Accelerator` twice in the same process. You could try if calling `AcceleratorState._reset_state()` works for you but beware that this is outside of how accelerate should be used normally.
