### ISSUE TITLE
Not to use_seedable_sampler causes `accelerate test` failure on TPU v2/v3

### ISSUE THREAD

**Issue by vanbasten23** [huggingface/accelerate#2479]
### System Info

We have found that https://github.com/huggingface/accelerate/pull/2319 causes `accelerate test` fails on TPU v2/v3 but the v4 tests succeed.  The PR huggingface/transformers#28664 doesn't help because we are directly using `accelerate test` in accelerate instead of transformers. 

The failing tests are here https://github.com/huggingface/accelerate/blob/60bfdaa9349e3e1a373863a8c5f20baa89cfd000/src/accelerate/test_utils/scripts/test_script.py#L214-L237 when we use a DataLoader with `shuffle` enabled. The error message is:
```
stderr: """
stderr: Traceback (most recent call last):
stderr:   File "/usr/local/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
stderr:     r = call_item.fn(*call_item.args, **call_item.kwargs)
stderr:   File "/usr/local/lib/python3.8/concurrent/futures/process.py", line 198, in _process_chunk
stderr:     return [fn(*args) for args in chunk]
stderr:   File "/usr/local/lib/python3.8/concurrent/futures/process.py", line 198, in <listcomp>
stderr:     return [fn(*args) for args in chunk]
stderr:   File "/ansible/pytorch/xla/torch_xla/runtime.py", line 88, in wrapper
stderr:     return fn(*args, **kwargs)
stderr:   File "/ansible/pytorch/xla/torch_xla/_internal/pjrt.py", line 78, in _run_thread_per_device
stderr:     replica_results = list(
stderr:   File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
stderr:     yield fs.pop().result()
stderr:   File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 444, in result
stderr:     return self.__get_result()
stderr:   File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
stderr:     raise self._exception
stderr:   File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
stderr:     result = self.fn(*self.args, **self.kwargs)
stderr:   File "/ansible/pytorch/xla/torch_xla/_internal/pjrt.py", line 71, in _thread_fn
stderr:     return fn()
stderr:   File "/ansible/pytorch/xla/torch_xla/_internal/pjrt.py", line 189, in __call__
stderr:     self.fn(runtime.global_ordinal(), *self.args, **self.kwargs)
stderr:   File "/root/accelerate/src/accelerate/utils/launch.py", line 569, in __call__
stderr:     self.launcher(*args)
stderr:   File "/root/accelerate/src/accelerate/test_utils/scripts/test_script.py", line 695, in main
stderr:     dl_preparation_check()
stderr:   File "/root/accelerate/src/accelerate/test_utils/scripts/test_script.py", line 221, in dl_preparation_check
stderr:     assert result == list(range(length)), "Wrong shuffled dataloader result."
stderr: AssertionError: Wrong shuffled dataloader result.
stderr: """
```
In our case, the `length` [here](https://github.com/huggingface/accelerate/blob/60bfdaa9349e3e1a373863a8c5f20baa89cfd000/src/accelerate/test_utils/scripts/test_script.py#L214) is 256. The expected result is indeed `list(range(256))`, but the result we got has duplicates, such as `[0,1,1, ...]` 

Let me create a fix.

cc: @will-cromar @miladm

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

```
export PJRT_DEVICE=TPU
accelerate test
```

### Expected behavior

The script `accelerate test` should succeed on TPU v2/v3.

**Comment by SunMarc** [comment]
Hi @vanbasten23, thanks for working on the fix. Let us know if you have any questions ! cc @muellerzr
