### ISSUE TITLE
stuck on model prepare for single node multi gpu

### ISSUE THREAD

**Issue by kboseong** [huggingface/accelerate#248]
## My accelerate config
In which compute environment are you running? ([0] This machine, [1] AWS (Amazon SageMaker)): 0
Which type of machine are you using? ([0] No distributed training, [1] multi-CPU, [2] multi-GPU, [3] TPU): 2
How many different machines will you use (use more than 1 for multi-node training)? [1]: 1
Do you want to use DeepSpeed? [yes/NO]: No
How many processes in total will you use? [1]: 2
Do you wish to use FP16 (mixed precision)? [yes/NO]: yes

## Enviroment Info
Machine Info : A6000 X 2
NGC docker version : pytorch:21.09-py3(pytorch 1.10.0, cuda 11.4, python 3.8)
accerlerate version : 0.5.1

## reproducible code
```python
model = torch.nn.Transformer()
model = accelerator._prepare_one(model)
```

## Additional Explanation
I use NGC docker Image on my development setting. I try to use accelerate but script stuck on accelerator.prepare part.
So I try to separate model, optimizer, dataloader with _prepare_one method, I can figure out model prepare part is reason.
Simple reproducible code is above, How can I fix it?

Thank you

**Comment by sgugger** [comment]
How are you launching your script with this code?

**Comment by kboseong** [comment]
> How are you launching your script with this code?

I launch the script same as documentation

```bash
accelerate launch train.py 
```

**Comment by dipam0111** [comment]
@sgugger I have the same issue, 1 AWS instance, 4 GPUs. I'm creating a config using `accelerate config` and then when I run it as `accelerate launch --config_file default_config.yaml my_file.py` it's stuck in the train function. The train func is pretty standard

```
for i, _ in enumerate(range(steps_per_epoch)):
            self.optimizer.zero_grad()
            page_ids, images, targets = next(dataloader)

            losses = self.model(images, targets)

            loss = compute_loss(losses)

            # loss.backward()
            self.accelerator.backward(loss)
            self.optimizer.step()
```

no logs / no processes running, just stuck. PS: I'm running it inside a docker image and not directly on the instance
