### ISSUE TITLE
How to log information into a local logging file?

### ISSUE THREAD

**Issue by Luciennnnnnn** [huggingface/accelerate#2485]
### System Info

```Shell
Hi, I want to save a copy of logs to a local file, how to achieve this? Specifically, I want accelerator.log also write information in my local file.
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

Hi, I want to save a copy of logs to a local file, how to achieve this? Specifically, I want accelerator.log also write information in my local file.

### Expected behavior

Hi, I want to save a copy of logs to a local file, how to achieve this? Specifically, I want accelerator.log also write information in my local file.

**Comment by BenjaminBossan** [comment]
If you mean the general logging by accelerate, something like this should work:

```python
import logging

logger = logging.getLogger("accelerate")
file_handler = logging.FileHandler("accelerate.log")
logger.addHandler(file_handler)
```

However, `accelerator.log` is different as it uses trackers like WandB. If it is possible to log their output to a file (and how) depends on the logger, but I don't think there is a general solution. For example, these trackers can log images, which would not be supported for file logging.
