### ISSUE TITLE
improve documentation for mixed precision with torch.cuda.amp.cast

### ISSUE THREAD

**Issue by Guptajakala** [huggingface/accelerate#2487]
### System Info

```Shell
Ubuntu 20
accelerate 0.26.1
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

The tutorial says the `accelerator.backward(loss)` will take care of the mixed precision automatically. But what if I want to enforce part of the model to use fp32 for precision-sensitive operations? Pytorch can do this by using context manager like:
```
with autocast(enabled=False):
  ...
```
Pytorch then requires a scaling step like `scaler.scale(loss).backward()`. I'm wondering if I use pytorch's context manager, will accelerator be compatible with that, and I don't need any unscaling myself?

### Expected behavior

improved tutorial clarification on this part.

**Comment by muellerzr** [comment]
It is, but it's recommended to just use `with accelerator.autocast(enabled=False)` instead (to be device-agnostic still)
