### ISSUE TITLE
Can I call prepare() separately on multiple models or should it be a single call?

### ISSUE THREAD

**Issue by NagabhushanSN95** [huggingface/accelerate#2488]
Hi,

I'm training two models in tandem, say `model1` and `model2`. When calling prepare, can I call it separately as in the below code

```
model1, dataloader, optimizer = accelerator.prepare(model1, dataloader, optimizer)
if some_condition:
    model2 = acceletator.prepare(model2)
```
or do I have to call it only once as in the below code
```
if not some_condition:
    model1, dataloader, optimizer = accelerator.prepare(model1, dataloader, optimizer)
else:
    model1, model2, dataloader, optimizer = acceletator.prepare(model1, model2, dataloader, optimizer)
```

**Comment by muellerzr** [comment]
You can call them separately for the most part or both, it shouldn't matter bar one case. It gets a bit trickier with DeepSpeed involved as we need all of the stuff at once, but generally as deepspeed doesn't support multiple models via accelerate right now your method should still be just fine.
