### ISSUE TITLE
Cannot submit jobs with different num_processes with SLURM

### ISSUE THREAD

**Issue by JoyHuYY1412** [huggingface/accelerate#2489]
Hi, my SLURM bash looks like:

`
accelerate launch \
    --mixed_precision=bf16  \
    --machine_rank 0 \
    --num_machines 1 \
    --main_process_port 11135 \
    --num_processes $GPUS_PER_NODE \
    fastcomposer/train.py \
`
I need to run `accelerate config` in an interactive way first and set _distributed_type_ to _multi_gpu_ also so that it runs with 4 GPUs.

However, when I want to submit a new interactive job when only 1 process, I need to run  `accelerate config` again to make it run on the single GPU. So I think there maybe some bug when my 4-GPU task resumes from the checkpoint, is there any suggestions?

**Comment by muellerzr** [comment]
You can just not use `accelerate config` in this instance. E.g.:

```bash
accelerate launch \ --mixed_precision=bf16  \ --machine_rank 0 \ --num_machines 1 \ --main_process_port 11135 \ --num_processes $GPUS_PER_NODE \ fastcomposer/train.py \
```

(This alone should be just fine and automatically work btw)

or:

```bash
accelerate launch \ --multi_gpu \ --mixed_precision=bf16  \ --machine_rank 0 \ --num_machines 1 \ --main_process_port 11135 \ --num_processes $GPUS_PER_NODE \ fastcomposer/train.py \
```

**Comment by muellerzr** [comment]
Also, while it is SLURM, if it's just one machine you don't need to add `--machine_rank` and `--num_machines`

**Comment by JoyHuYY1412** [comment]
> You can just not use `accelerate config` in this instance. E.g.:
> 
> ```shell
> accelerate launch \ --mixed_precision=bf16  \ --machine_rank 0 \ --num_machines 1 \ --main_process_port 11135 \ --num_processes $GPUS_PER_NODE \ fastcomposer/train.py \
> ```
> 
> (This alone should be just fine and automatically work btw)
> 
> or:
> 
> ```shell
> accelerate launch \ --multi_gpu \ --mixed_precision=bf16  \ --machine_rank 0 \ --num_machines 1 \ --main_process_port 11135 \ --num_processes $GPUS_PER_NODE \ fastcomposer/train.py \
> ```

Thanks for your reply!
My problem is I sometimes debug on SLURM with a single GPU and I find the `distributed_type` can only be modified by `accelerate config`, but running that may influence my multi-GPU jobs. 

`accelerate launch \ --mixed_precision=bf16  \ --machine_rank 0 \ --num_machines 1 \ --main_process_port 11135 \ --num_processes $GPUS_PER_NODE \ fastcomposer/train.py \` cannot change the` default_config.yaml `in my case, and I see the `accelerate.state` which still shows num_processes=1, but after I run `accelerate config` then it is OK. 

Maybe I can try `export ACCELERATE_CONFIG_FILE=/path/to/my_accelerate_config.yaml` when running on single GPU? DOes that make sense to you?

**Comment by muellerzr** [comment]
If you don't have a config file and just pass in `--multi_gpu` it will be just fine. 

You also can pass in `--num_processes {x}` which will help. 

To point to a config file, you can do `accelerate launch --config_file {ENV_VAR}` which would be the easiest solution here as all of your configs can be stored there, and you can keep these config files in a shared filesystem somewhere the server can reach (or you can grab etc). This is what I tend to do

**Comment by JoyHuYY1412** [comment]
> If you don't have a config file and just pass in `--multi_gpu` it will be just fine.
> 
> You also can pass in `--num_processes {x}` which will help.
> 
> To point to a config file, you can do `accelerate launch --config_file {ENV_VAR}` which would be the easiest solution here as all of your configs can be stored there, and you can keep these config files in a shared filesystem somewhere the server can reach (or you can grab etc). This is what I tend to do

Thank you so much!
