### ISSUE TITLE
[Feature request] Mechanism to Disable Accerate in runtime

### ISSUE THREAD

**Issue by thiagocrepaldi** [huggingface/accelerate#2494]
### System Info

```Shell
main branch
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

Assuming I have migrated my script to use the Accelerator as below

```diff
  import torch
  import torch.nn.functional as F
  from datasets import load_dataset
+ from accelerate import Accelerator

- device = 'cpu'
+ accelerator = Accelerator()

- model = torch.nn.Transformer().to(device)
+ model = torch.nn.Transformer()
  optimizer = torch.optim.Adam(model.parameters())

  dataset = load_dataset('my_dataset')
  data = torch.utils.data.DataLoader(dataset, shuffle=True)

+ model, optimizer, data = accelerator.prepare(model, optimizer, data)

  model.train()
  for epoch in range(10):
      for source, targets in data:
-         source = source.to(device)
-         targets = targets.to(device)

          optimizer.zero_grad()

          output = model(source)
          loss = F.cross_entropy(output, targets)

-         loss.backward()
+         accelerator.backward(loss)

          optimizer.step()
```

### Expected behavior

What I would like to achieve is to have the ability to disable Accelerate through an Environment variable or an API such that the code was execute as if Accelerate was not present. 

With this, with a single version of the user script (containing the Accelerate lines) the users can benchmark the model with and without Accelerate in action

**Comment by BenjaminBossan** [comment]
Thanks for the suggestion, I agree it would be nice to have such a feature, but I don't think this is easily possible to add it. First of all, we would have to ensure that each user facing API for accelerate adds a no-op when this flag is set (sometimes even more logic is required). This would be quite a significant addition. Second, lines such as `source = source.to(device)` are out of accelerate's control, so the script would still fail.

In the end, you have to adjust your script by adding checks if accelerate is being used or not, or you maintain a second script without accelerate being used.

**Comment by thiagocrepaldi** [comment]
> Thanks for the suggestion, I agree it would be nice to have such a feature, but I don't think this is easily possible to add it. First of all, we would have to ensure that each user facing API for accelerate adds a no-op when this flag is set (sometimes even more logic is required). This would be quite a significant addition. Second, lines such as `source = source.to(device)` are out of accelerate's control, so the script would still fail.
> 
> In the end, you have to adjust your script by adding checks if accelerate is being used or not, or you maintain a second script without accelerate being used.

Thanks for the reply. Indeed, APIs such as `accelerator.prepare()` and `accelerator.loss()` would need a no-op implementation for the basic flow. More APIs certainly would need the same. The `.to(device)` calls are removed when Accelerate is used, so it shouldn't be a problem.

The problem this feature request tries to solve is when the accelerate is used as part of a third-party library in which we have no control over the code. It is not feasible to `pip install transformers` and then monkey patch it to remove the accelerate engine.

As an example,take this repro in which we want to export Stable Diffusion XL to ONNX using PyTorch Fake Tensor, which is currently not compatible with Accelerate:

```python
import torch
from diffusers import DiffusionPipeline

import safetensors
import transformers


# Monkey-patch for https://github.com/huggingface/safetensors/pull/318
class ONNXTorchPatcher:

    def __init__(self):
        def safetensors_load_file_wrapper(filename, device="cpu"):
            result = {}
            with safetensors.torch.safe_open(  # type: ignore[attr-defined]
                filename, framework="pt", device=device
            ) as f:
                for k in f.keys():
                    fake_mode = torch._guards.detect_fake_mode()
                    if not fake_mode:
                        result[k] = f.get_tensor(k)
                    else:
                        empty_tensor = f.get_slice(k)
                        result[k] = torch.empty(
                            tuple(empty_tensor.get_shape()),
                            dtype=safetensors.torch._getdtype(
                                empty_tensor.get_dtype()
                            ),
                        )
            return result

        self.safetensors_torch_load_file = safetensors.torch.load_file
        self.safetensors_torch_load_file_wrapper = safetensors_load_file_wrapper
        self.transformers_modeling_utils_safe_load_file = (
            transformers.modeling_utils.safe_load_file
        )

    def __enter__(self):
        safetensors.torch.load_file = self.safetensors_torch_load_file_wrapper
        transformers.modeling_utils.safe_load_file = (
            self.safetensors_torch_load_file_wrapper
        )

    def __exit__(self, exc_type, exc_value, traceback):
        safetensors.torch.load_file = self.safetensors_torch_load_file
        transformers.modeling_utils.safe_load_file = (
            self.transformers_modeling_utils_safe_load_file
        )

with torch._subclasses.FakeTensorMode(), ONNXTorchPatcher():
    fake_model = DiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0", use_safetensors=False)
```

The error would be something like

```bash
Traceback (most recent call last):
  File "/opt/pytorch/test_sdxl.py", line 50, in <module>
    fake_model = DiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0", use_safetensors=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/ptca/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/ptca/lib/python3.11/site-packages/diffusers/pipelines/pipeline_utils.py", line 1286, in from_pretrained
    loaded_sub_model = load_sub_model(
                       ^^^^^^^^^^^^^^^
  File "/opt/conda/envs/ptca/lib/python3.11/site-packages/diffusers/pipelines/pipeline_utils.py", line 531, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/ptca/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/ptca/lib/python3.11/site-packages/diffusers/models/modeling_utils.py", line 652, in from_pretrained
    model = cls.from_config(config, **unused_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/ptca/lib/python3.11/site-packages/diffusers/configuration_utils.py", line 259, in from_config
    model = cls(**init_dict)
            ^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/ptca/lib/python3.11/site-packages/diffusers/configuration_utils.py", line 649, in inner_init
    init(self, *args, **init_kwargs)
  File "/opt/conda/envs/ptca/lib/python3.11/site-packages/diffusers/models/autoencoders/autoencoder_kl.py", line 88, in __init__
    self.encoder = Encoder(
                   ^^^^^^^^
  File "/opt/conda/envs/ptca/lib/python3.11/site-packages/diffusers/models/autoencoders/vae.py", line 85, in __init__
    self.conv_in = nn.Conv2d(
                   ^^^^^^^^^^
  File "/opt/pytorch/torch/nn/modules/conv.py", line 447, in __init__
    super().__init__(
  File "/opt/pytorch/torch/nn/modules/conv.py", line 134, in __init__
    self.weight = Parameter(torch.empty(
    ^^^^^^^^^^^
  File "/opt/pytorch/torch/nn/modules/module.py", line 1723, in __setattr__
    self.register_parameter(name, value)
  File "/opt/conda/envs/ptca/lib/python3.11/site-packages/accelerate/big_modeling.py", line 123, in register_empty_parameter
    module._parameters[name] = param_cls(module._parameters[name].to(device), **kwargs)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: FakeTensor.__new__() got an unexpected keyword argument 'fake_device'
```

Ideally, we don't need accelerate to export the model to ONNX as it is not an architectural library, but we can't change the `DiffusionPipeline.from_pretrained` implementation either

**Comment by muellerzr** [comment]
The code you show here has nothing at all to do with `accelerator.prepare()` though, or the `Accelerator` class at all. cc @SunMarc is there something we can do about this error perhaps? (as this is our big model inference side)

**Comment by thiagocrepaldi** [comment]
> The code you show here has nothing at all to do with `accelerator.prepare()` though, or the `Accelerator` class at all. cc @SunMarc is there something we can do about this error perhaps? (as this is our big model inference side)

It is not directly related to `.prepare`, but my suggestion is to give users the ability to bypass `accelerate` when they are embedded on third-party libraries. I'm not familiar with the `accelerate` internals, so maybe I am missing your point, but had `accelerate` not tried to allocate a Tensor in `File "/opt/conda/envs/ptca/lib/python3.11/site-packages/accelerate/big_modeling.py", line 123, in register_empty_parameter` when I used `transformers`, the use of Transformers with FakeTensor might have succeeded.

Nonetheless, I am also interested in ways to fix this issue, but I hope the feature is still valuable for integrating hf with pytorch and other libraries.

**Comment by BenjaminBossan** [comment]
> The .to(device) calls are removed when Accelerate is used, so it shouldn't be a problem.

I don't understand this. If we deactivate accelerate, the data won't be on the right device, so the `.to` calls need to be added back or else things will break, wouldn't they? Therefore, it's not possible to make deactivate accelerate without also touching the code that uses it.

**Comment by thiagocrepaldi** [comment]
> > The .to(device) calls are removed when Accelerate is used, so it shouldn't be a problem.
> 
> I don't understand this. If we deactivate accelerate, the data won't be on the right device, so the `.to` calls need to be added back or else things will break, wouldn't they? Therefore, it's not possible to make deactivate accelerate without also touching the code that uses it.

We have 2 scenarios here: 1) the one that motivated my request with the backtrace above and 2) the generic approach that a broader audience might leverage.

For 1) the Transformers + PyTorch FakeTensor, default device (cpu) is ok in this scenario. FakeTensor pretends to allocate memory on a `meta` device. For the purpose of converting a `torch.nn.Module` to ONNX, for example, that is enough. ONNX does not have the notion of device.

For 2), although the user doesn't have control over the `/opt/conda/envs/ptca/lib/python3.11/site-packages/accelerate/big_modeling.py::register_empty_parameter` call made by the user's `model = DiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0", use_safetensors=False)`, the user certainly can move the model to any device they need after `from_pretrained` is returned. That is, the user managed to bypass `accelerate` which was an implementation detail of a 3rd-party library and revert to the traditional device allocation strategy.

Makes sense?

**Comment by BenjaminBossan** [comment]
Thanks for elaborating Thiago.

I agree that there can be scenarios where a flag to turn off accelerate would be useful. My feeling is, however, that in the vast majority of cases, that would not be sufficient to run a script as is but would require further modifications (which would be impossible if 3rd party code is involved). When taking into account the effort required to implement this feature (which wouldn't be as easy as a no-op on all public methods), the cost/benefit doesn't look worthwhile. If we had to rewrite accelerate from the ground up today, it would make sense to keep this feature in mind, but adding it now would be quite expensive.

For this reason, I concur with Zach that we should indeed try to focus on the specific problems and solve them quickly instead of finding a way to sidestep accelerate completely.

**Comment by thiagocrepaldi** [comment]
Thanks @muellerzr `low_cpu_mem_usage=False` kind of works for the specific scenario I got. I understand the issues with fixing th generic problem at 2), so I will try to focus on 1)
