### ISSUE TITLE
The batch size of "Model Memory Calculator"

### ISSUE THREAD

**Issue by nai-kon** [huggingface/accelerate#2512]
The Model Memory Calculator is very useful, but what is the batch size of this result?
I can't find any information.

https://huggingface.co/docs/accelerate/usage_guides/model_size_estimator

**Comment by muellerzr** [comment]
Batch size of 1

**Comment by nai-kon** [comment]
Thank you for the quick reply!

**Comment by nai-kon** [comment]
I have an additional question.
If I increase batch_size by 2 or 4, etc., will the amount of memory be proportional to 2 or 4 times?

**Comment by muellerzr** [comment]
No

**Comment by nai-kon** [comment]
Thank you for your detailed explanation.
Your tool is very powerful and useful for estimating, so I'm glad if the batch size is also supported in the future.
