### ISSUE TITLE
Select GPUs to use at runtime

### ISSUE THREAD

**Issue by rb-synth** [huggingface/accelerate#2529]
The suggested way of using a subset of GPUs is `CUDA_VISIBLE_DEVICES=1,2 accelerate launch`.

However, I want to use, say, 7 GPUs for training and an 8th GPU for rendering in my dataset. As far as I can see, this is not possible in the current version of `accelerate`. As it stands, it seems that `accelerate` either uses all 8 GPUs, or I set `CUDA_VISIBLE_DEVICES` and then I can't access the 8th GPU at all.

**Comment by muellerzr** [comment]
That's not possible with PyTorch I'm afraid.

**Comment by rb-synth** [comment]
Can we open a feature request for it? It feels like useful functionality!

**Comment by muellerzr** [comment]
You’re welcome to on the PyTorch repo :)

**Comment by rb-synth** [comment]
Thanks!
