### ISSUE TITLE
`gather_for_metrics` incorrectly flattens nested lists of objects

### ISSUE THREAD

**Issue by malik-ali** [huggingface/accelerate#2537]
### System Info

```Shell
- Platform: Linux-5.4.0-153-generic-x86_64-with-glibc2.31
- Python version: 3.11.8
- Numpy version: 1.26.4
- PyTorch version (GPU?): 2.2.1+cu121 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 755.63 GB
- GPU type: NVIDIA RTX A6000
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: no
        - use_cpu: False
        - debug: False
        - num_processes: 2
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: all
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

To reproduce the problem, try running `accelerator.gather_for_metrics` with a tuple of objects. Example:

```
preds = ["Sentence1", "Sentence2"]
refs = ["Ref1", "Ref2"]

accelerator.gather_for_metrics((preds, refs))
```

This should return a tuple, one containing a list of the gathered preds and the other containing a list of the gathered references. However it returns one big list with all the entries flattened.

This is due to the following line:
https://github.com/huggingface/accelerate/blob/10882eeddd841b0a1a8064421816ee0daef99920/src/accelerate/utils/operations.py#L447C5-L448C50

The easy fix is to not do that flattening but since there is a comment there, I assume it was put there for a reason? Another fix is to call gather_for_metrics separately, on each independent variable like:

```
preds = accelerator.gather_for_metrics(preds)
refs = accelerator.gather_for_metrics(refs)
```

### Expected behavior

I expect this should return a tuple/list/dict of the same structure as passed in and gather all the objects for each entry in this structure. This is the wording suggested by the documentation

> input (torch.Tensor, object, a nested tuple/list/dictionary of torch.Tensor, or a nested tuple/list/dictionary of object) — The tensors or objects for calculating metrics across all processes

**Comment by muellerzr** [comment]
Yes that's expected behavior for objects specifically. `gather_object` is very finicky as well, and the torch team has directly stated that it is not recommended to do so. 

My recommendation is to call them separately if you have things that are not tensors, like you have done here.
