### ISSUE TITLE
The results are inconsistent with using pytorch directly

### ISSUE THREAD

**Issue by XiaoXiao-Woo** [huggingface/accelerate#2547]
### System Info

```Shell
accelerate version: 0.20.3
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

```
# Results using pytorch directly
input_mean:   tensor(0.1748, device='cuda:2') tensor(0.1748, device='cuda:2')
input_mean:   tensor(0.1760, device='cuda:2') tensor(0.1760, device='cuda:2')
ddp_test - Iter [2] Epoch(train) [1]/[1] [2/2]  lr: 1.000e-04, eta: 0:00:00, time: 0.273, data_time: 0.057, memory: 197MB, loss: 0.00728, grad_norm: 0.10437
ddp_test - Iter [2] Epoch(test) [1]/[1] [10/10]  PSNR: 23.86963
```

```
# Results accelerate launch  my_script.py
input_mean:   tensor(0.1748, device='cuda:2') tensor(0.1748, device='cuda:2')
input_mean:   tensor(0.1760, device='cuda:2') tensor(0.1760, device='cuda:2')
ddp_test - Iter [2] Epoch(train) [1]/[1] [2/2]  lr: 1.000e-04, eta: 0:00:00, time: 0.219, data_time: 0.012, memory: 100MB, loss: 0.00729, grad_norm: 0.10437
ddp_test - Iter [2] Epoch(test) [1]/[1] [20/20] PSNR: 23.86795
```

The difference is in the following code. I don't know what Accelerator.prepare is doing since the input data is the same in both cases.
```python
model = accelerator.prepare(model) 
```

### Expected behavior

Check the results and make the results the same as pytorch. If possible, please tell me what happens in accelerator.prepare(model) of a model.

**Comment by muellerzr** [comment]
Please provide us all your code, we can’t know anything otherwise
