### ISSUE TITLE
Running launch command without python script

### ISSUE THREAD

**Issue by parameter-concern** [huggingface/accelerate#256]
Currently, the main argument to the `accelerate launch` command is a python script. For some projects, it would be convenient for me to be able to pass either a python module or a non-python executable (e.g. a shell script) to launch instead. This is not too hard to do manually with the `--module` or `--no_python` flags in `torch.distributed.launch`, but then I lose the convenience of the `accelerate` config and launch commands.

One example use case for this is that sometimes I like to bundle up code and utility commands (like training/fine-tuning and evaluation) into python packages and give them CLI entry points in `setup.py`. It would be nice to be able to pass in the training entry point to `accelerate launch` instead of the underlying `.py` file for consistency and ease of packaging/distributing/running.

If this is something that the maintainers or others would like to see supported, I'm happy to submit a PR, but I would understand if they didn't want to bloat up the launch arguments list and preferred if people just did stuff like this manually.

**Comment by parameter-concern** [comment]
Below are some notes I took while hacking this into my local environment:

In the case of the `simple_launcher`, `multi_gpu_launcher`, and `deepspeed_launcher` used in `commands/launch.py`, this support would be easy to add by mimicking the `--module` and `--no_python` [arguments](https://github.com/pytorch/pytorch/blob/master/torch/distributed/run.py#L452) and [command setup](https://github.com/pytorch/pytorch/blob/master/torch/distributed/run.py#L660) from `torch.distributed.launch`.  The deepspeed [args](https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/launcher/launch.py#L56) and [command setup](https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/launcher/launch.py#L155) are very similar and actually a bit simpler to read.

For the `tpu_launcher`, the argument is already interpreted as a module which is imported and run, so a `--no_python` flag could probably just be ignored and setting the `--module` flag could allow the argument to be used by `importlib.import_module` directly if given instead of parsing the path.

For the `sagemaker_launcher`, both arguments would probably just be ignored if set, since sagemaker's [`entry_point`](https://sagemaker.readthedocs.io/en/stable/frameworks/pytorch/sagemaker.pytorch.html) is required to be a python script, as far as I understand (I haven't used sagemaker before).

**Comment by sgugger** [comment]
Thanks a lot for taking the time to investigate. I think your request is sensible and it should be possible to implement it in most use cases (and error in the `sagemaker_launcher` before launching anything). If you want to start working on a PR for this feature, please do so!

**Comment by sgugger** [comment]
Fixed by #258
