### ISSUE TITLE
[Multi-GPU training] How to specific backend used in DDP training?

### ISSUE THREAD

**Issue by Luciennnnnnn** [huggingface/accelerate#2560]
### System Info

```Shell
.....
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

......

### Expected behavior

<img width="921" alt="image" src="https://github.com/huggingface/accelerate/assets/20135317/aaef21fc-17ad-457d-98c1-bdfa82891978">

I encounter above errors when my problem have run 7 hours in 4 A100s, I don't known what's the cause of it, but the information suggests accelerate use GLOO as DDP backend, how to switch to NCCL? as my best knowledge, it's better than GLOO.

**Comment by SunMarc** [comment]
Hi @Luciennnnnnn, it should use nccl if you are on a multi-gpu setup. Could you print your accelerate config ? Here's the related [code](https://github.com/huggingface/accelerate/blob/c470a1336a7a2711f9903807a81a8fecf60cc1b2/src/accelerate/state.py#L728) with you want to try debugging.
