### ISSUE TITLE
Exactly the same problem as mentioned in #2334

### ISSUE THREAD

**Issue by tingxueronghua** [huggingface/accelerate#2568]
### System Info

```Shell
accelerate 0.28.0
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

Just try to load data batch containing string.

### Expected behavior

  File "/data/miniconda3/lib/python3.9/site-packages/accelerate/utils/operations.py", line 625, in concatenate
    raise TypeError(f"Can only concatenate tensors but got {type(data[0])}")
TypeError: Can only concatenate tensors but got <class 'str'>

**Comment by ttw1018** [comment]
So, how to solve this?
