### ISSUE TITLE
Kernel version issues.

### ISSUE THREAD

**Issue by surak** [huggingface/accelerate#2573]
On #2174, you mention the kernel version and now you check for minimal version 5.5. For example, the following was asked there:

> Do you have the possibility to upgrade the Linux kernel? We found that kernel versions < 5.5 could lead to processes hanging.

This is impossible on data centers using Red Hat Enterprise Linux - usually OS of choice on the ones with dozens of thousands of gpus.

Is there any alternative?

**Comment by muellerzr** [comment]
Nope, it's a torch issue, nothing we can do about it except accept that it's a possibility that could lead to some errors users were reporting. It's one of many things we can look towards during debugging, but often it is not the root cause.

**Comment by surak** [comment]
Hi @muellerzr , thanks. Do you have some issue number or docu about that on Torch's side? I can try and see if we can push a backport, although I doubt I can convince any sysadmin to take a kernel patch that easily.

**Comment by surak** [comment]
Hi @muellerzr
