### ISSUE TITLE
Implicit initializations when using `PartialState`

### ISSUE THREAD

**Issue by carefree0910** [huggingface/accelerate#2587]
What happened:
- Used `PartialState` for some dist info
- Initialize `Accelerator` with `InitProcessGroupKwargs` (e.g., set `timeout`)
- Settings not taking effect because `PartialState` already done the initializations

By reading the source code the logics are easy, but from the docs of `PartialState` -

> ... Does *not* need to be initialized from `Accelerator`.

The name of `PartialState` also indicates its uniqueness, but now it actually contains implicit initializations.

I've seen some refactors / enhancements on `PartialState` ( #2572 , #2576 ), but I'm not sure whether they tackle this problem.

> Maybe this is more of a design issue?

**Comment by muellerzr** [comment]
It's just what happens if you start the init state before the `Accelerator`.

The alternative is to do the following:

```python
kwargs = InitProcessGroupKwargs(...)

state = PartialState(**kwargs.to_kwargs())
```

**Comment by muellerzr** [comment]
I chose to expand the docstring instead, to make it more known what to do :) Let me know if you're satisfied with this solution @carefree0910

**Comment by carefree0910** [comment]
> It's just what happens if you start the init state before the `Accelerator`.
> 
> The alternative is to do the following:
> 
> ```python
> kwargs = InitProcessGroupKwargs(...)
> 
> state = PartialState(**kwargs.to_kwargs())
> ```

This is exactly what I'm doing now, and yes, a better docstring can help users better understand `PartialState` already!

One other thing though: will it be better to have something *completely* free to use? Since many operations, which depend on `PartialState`, still implicitly trigger initializations and may not tell users in their docstrings (e.g., `wait_for_everyone`).

**Comment by carefree0910** [comment]
What I'm doing now is something like this:

```python
import torch.distributed as dist
from accelerate.utils import wait_for_everyone as accelerate_wait

def wait_for_everyone() -> None:
    if dist.is_initialized():
        accelerate_wait()
```

Which makes sure that `wait_for_everyone` is a no-op when `dist` is not initialized.

It will invent other potential bugs (e.g., users use DDP but have not `init_process_group`) so it is not ideal, but I believe you `accelerate` team is far more expert than me and can have better solutions!
