### ISSUE TITLE
Are there recommended approaches for using multiple lr schedulers with different stepping strategy?

### ISSUE THREAD

**Issue by universuen** [huggingface/accelerate#2598]
Hi! I've encountered a problem when building a trainer using `Accelerate`:
In a scenario where you are employing multiple optimizers with distinct schedulers—specifically, Scheduler A which executes `.step()` after each training iteration, and Scheduler B which does so following each epoch—how should one configure the `accelerator.step_scheduler_with_optimizer` ? This parameter appears to be tailored for scenarios involving a single scheduler.

**Comment by muellerzr** [comment]
If you're okay with handling the step by optimizer yourself, I'd recommend just doing the epoch one separately and don't prepare it.
