### ISSUE TITLE
How to load a FSDP checkpoint model

### ISSUE THREAD

**Issue by nlpkiddo-2001** [huggingface/accelerate#2603]
I have fine tuned gemma 2b model using FSDP and these are the below files available under the checkpoint 

```
optimizer_0  pytorch_model_fsdp_0  rng_state_0.pth  rng_state_1.pth  scheduler.pt  trainer_state.json
```
How can i load the above FSDP object? 

kindly help me with this issue,

**Comment by helloworld1** [comment]
Would this help? https://discuss.huggingface.co/t/transformers-trainer-accelerate-fsdp-how-do-i-load-my-model-from-a-checkpoint/61585/3
