### ISSUE TITLE
AttributeError: 'Accelerator' object has no attribute 'save_model'

### ISSUE THREAD

**Issue by selviramya** [huggingface/accelerate#2604]
### System Info

```Shell
Libraries:
accelerate==0.20.3
numpy==1.21.5
torch==1.13.1+cpu
torchvision==0.14.1+cpu
transformers==4.30.2

Python Version: 3.10.12
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

Code Fragment:
```
from transformers import T5Tokenizer, T5ForConditionalGeneration,AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("intfloat/multilingual-e5-base")
model = T5ForConditionalGeneration.from_pretrained("intfloat/multilingual-e5-base")

from accelerate import Accelerator

save_directory="/content/model"
accelerator = Accelerator()

accelerator.save_model(model=model, save_directory=save_directory)
```

**Exception:**

> AttributeError: 'Accelerator' object has no attribute 'save_model'

### Expected behavior

This should be a supported method as I could see the implementation in the `accelerate.py`

**Comment by muellerzr** [comment]
Try upgrading your accelerate version. You’re using one ~6 months old now, and this may have been added in that timeframe
