### ISSUE TITLE
Wrapped Torch/Transformers Schedulers Results in Broken .step() Wrapper

### ISSUE THREAD

**Issue by Jordach** [huggingface/accelerate#2605]
### System Info

```Shell
Truncated pip list with relevant items:
Package                  Version
------------------------ -----------
accelerate               0.26.0
bitsandbytes             0.43.0
huggingface-hub          0.21.4
numpy                    1.26.4
nvidia-cuda-runtime-cu12 12.1.105
torch                    2.2.1
torchtools               0.3.5
torchvision              0.17.1
transformers             4.39.0

accelerate env output:

- `Accelerate` version: 0.26.0
- Platform: Linux-5.15.0-100-generic-x86_64-with-glibc2.35
- Python version: 3.10.9
- Numpy version: 1.26.4
- PyTorch version (GPU?): 2.2.1+cu121 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 125.60 GB
- GPU type: NVIDIA GeForce RTX 4090
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: NO
        - mixed_precision: bf16
        - use_cpu: False
        - debug: False
        - num_processes: 1
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: 1
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []```
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [x] My own task or dataset (give details below)

### Reproduction

Uncomment these lines to show that LR does not warmup from zero:

https://github.com/Jordach/CascadeTuner/blob/main/train_stage_c.py#L551
https://github.com/Jordach/CascadeTuner/blob/main/train_stage_c.py#L554

(If the Text Encoder is being trained, also uncomment this!)
https://github.com/Jordach/CascadeTuner/blob/main/train_stage_c.py#L569
https://github.com/Jordach/CascadeTuner/blob/main/train_stage_c.py#L572

Run training with a few hundred images, and observe that LR stays equal to zero as it never performs it's warmup steps.

### Expected behavior

The LR warmup should occur over a few steps and be the designated constant LR set in the yaml configuration. LR warmup works as expected when not wrapped with Accelerate.

This is likely due to the deprecation of `_LRScheduler` in Torch 2.2 specifically.

**Comment by muellerzr** [comment]
Please provide the exact commands, configurations, etc to run your code, or provide a minimal example that doesn't use outside libraries :)
