### ISSUE TITLE
accelerator.skip_first_batches very slow make nccl timeout

### ISSUE THREAD

**Issue by lipiji** [huggingface/accelerate#2606]
skipped_dataloader = accelerator.skip_first_batches(dataloader, num_batches=500000)

for input, target in skipped_dataloader: 

It seems that it is very flow in the batch fectching and the nccl is timeout before it fetchs one batch using the above iteration skipped_dataloader. 

Make num_batches small (say 1000) or the original dataloader will be OK.
Then how to make this work?

**Comment by lipiji** [comment]
> You're likely hitting a timeout just because it takes so long to skip through that amount of batches. If it's not possible to skip that yourself, my only advice is to increase the timeout itself using the `DistributedDataParallelKwargs` util and passing it to the `Accelerator` `kwargs_handlers`

Thanks. One more thing, I restart a job 12hrs ago and I find that it is still skiping the data (600000 batches) and has not start to train yet. Is it normal? Thanks.

**Comment by muellerzr** [comment]
You’re iterating over all your data, yes. That will take a *very* long time.

**Comment by muellerzr** [comment]
You can do something like this to see when it's done/how it's going I suppose:

```python
skipped_dataloader = accelerator.skip_first_batches(dataloader, num_batches=500000)
print(f"Finished skipping on {accelerator.process_index}")
```
