### ISSUE TITLE
How to I selectively apply accelerate to trainers

### ISSUE THREAD

**Issue by zyzhang1130** [huggingface/accelerate#2614]
I have two trainers in a script, one is SFTTrainer and one is PPOTrainer, both from trl library. Is it possible to only apply accelerate to PPOTrainer?

**Comment by SunMarc** [comment]
Hi @zyzhang1130 , SFTTrainer and PPOTrainer all uses accelerate as the backend. Does this answer your question ?

**Comment by zyzhang1130** [comment]
But do both of them use accelerate by default? What I meant was, is it possible to **selectively** apply accelerate to, say, PPOTrainer, when both SFTTrainer and PPOTrainer exist in my script? 
On that note, it seems the way to use accelerate in PPOTrainer is somewhat different compared to SFTTrainer:
```
device = ppo_trainer.accelerator.device
if ppo_trainer.accelerator.num_processes == 1:
    device = 0 if torch.cuda.is_available() else "cpu"  # to avoid a `pipeline` bug
sentiment_pipe = pipeline("sentiment-analysis", model="lvwerra/distilbert-imdb", device=device)
```
(see https://github.com/huggingface/trl/blob/main/examples/notebooks/gpt2-sentiment.ipynb)

**Comment by SunMarc** [comment]
Could you give me your use case. I'm not sure to understand why you would want to selectively apply accelerate. Both Trainer relies on accelerate to prepare the model, the optimizer and the dataset + training setup. You can't just disable accelerate.

**Comment by SunMarc** [comment]
Could you share the full traceback ? Thanks !

**Comment by zyzhang1130** [comment]
@SunMarc can you please show me an example, where I can move either `SFTtrainer` or `ppo_trainer` to device other than 'device:0' for training? If this works it can solve my issue. I worry my code is too complex to look at the trace.
