### ISSUE TITLE
Support for saving and loading custom objects

### ISSUE THREAD

**Issue by muellerzr** [huggingface/accelerate#262]
Idea from @sgugger:

> Add an optional argument to the `save_state` function, or add a `register_for_checkpoints` method to the Accelerator object that would take objects not passed to the prepare method but the user still wants to save.
(Most likely it would be a `register_for_checkpoints`)

**Comment by hiyyg** [comment]
add an optional argument would be great. That is how deepspeed achieve this. Why closing this issue? Is it supported already?

**Comment by muellerzr** [comment]
Yes, accelerator has a register for check pointing function now.
