### ISSUE TITLE
Deepspeed can not be detected

### ISSUE THREAD

**Issue by MagicianWu** [huggingface/accelerate#2621]
### System Info

```Shell
- `Accelerate` version: 0.28.0
- Platform: Linux-5.4.0-173-generic-x86_64-with-glibc2.31
- Python version: 3.9.13
- Numpy version: 1.21.5
- PyTorch version (GPU?): 2.2.1+cu121 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 2015.53 GB
- GPU type: NVIDIA A800-SXM4-80GB
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: bf16
        - use_cpu: False
        - debug: True
        - num_processes: 8
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: [0,1,2,3,4,5,6,7]
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

<img width="1349" alt="image" src="https://github.com/huggingface/accelerate/assets/68132494/18786212-ffe9-4acf-89a5-7fd62cf5688b">

### Expected behavior

Deepspeed is installed

**Comment by muellerzr** [comment]
Probably same answer as this https://github.com/huggingface/accelerate/issues/2622#issuecomment-2037037718

**Comment by MagicianWu** [comment]
After I conda deactivate and activate, it still does not find deepspeed.
<img width="1376" alt="image" src="https://github.com/huggingface/accelerate/assets/68132494/f7be7107-3a8b-43dc-9399-6c8ad215668a">
