### ISSUE TITLE
Cuda becomes unavailable and script is excuted by multiple times

### ISSUE THREAD

**Issue by MagicianWu** [huggingface/accelerate#2622]
### System Info

```Shell
- `Accelerate` version: 0.28.0
- Platform: Linux-5.4.0-173-generic-x86_64-with-glibc2.31
- Python version: 3.9.13
- Numpy version: 1.21.5
- PyTorch version (GPU?): 2.2.1+cu121 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 2015.53 GB
- GPU type: NVIDIA A800-SXM4-80GB
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: bf16
        - use_cpu: False
        - debug: True
        - num_processes: 8
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: [0,1,2,3,4,5,6,7]
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

import torch 
from accelerate import Accelerator
import os

def main():
    accelerator = Accelerator()
    print(torch.cuda.is_available())    

if __name__ == "__main__":
    main()
   

Executed with command:
accelerate launch accelerate_test.py 
<img width="1924" alt="image" src="https://github.com/huggingface/accelerate/assets/68132494/b1162b40-6dd2-413f-8011-c8aeda1bde04">

When executed with command:
python accelerate_test.py
<img width="1903" alt="image" src="https://github.com/huggingface/accelerate/assets/68132494/152b2e13-aaff-4ade-8737-e97e9e247500">

### Expected behavior

Cuda should be available while using accelerate.
And based on my understanding, print function should not be excuted by multiple times?

**Comment by muellerzr** [comment]
Can you check `python -c "import torch; print(torch.cuda.is_available())` from the CLI?

This means something is up with your torch build and/or cuda drivers.

And yes, print will be ran `n` times because you're not using `accelerator.print()` :) (N==num gpus)

**Comment by muellerzr** [comment]
You also have multiple envs active, which can lead to weird issues like this (been there/seen it before). Do a `conda deactivate` fully then `conda activate meshgpt`. Might also solve the issue (could be pointing to the wrong python or bash!)

**Comment by MagicianWu** [comment]
@muellerzr Thanks for your quick response!
<img width="1965" alt="image" src="https://github.com/huggingface/accelerate/assets/68132494/11c0dd42-b617-4899-a88f-d81cb8a2d644">
<img width="1012" alt="image" src="https://github.com/huggingface/accelerate/assets/68132494/efe45f60-ce0a-4ded-9e67-a27a2b56338e">

**Comment by muellerzr** [comment]
My best guess is you installed accelerate in another env, and it's messed up your bash scripts, so `accelerate launch` is pointing to the wrong accelerate. I recommend a full uninstall, as your system is borked from the accelerate installs.

How to check:
```bash
which accelerate launch
```
It should point to something equivalent to:
```bash
/.../mycondalocation/envs/meshgpt/bin/accelerate
```

**Comment by muellerzr** [comment]
Actually I can see right there it's calling it from your `.local` bash, so you installed it without conda possibly once, messing up the whole thing?
<img width="1376" alt="319584355-f7be7107-3a8b-43dc-9399-6c8ad215668a" src="https://github.com/huggingface/accelerate/assets/7831895/d5315563-ca38-4bb5-8dfa-b1b69758e221">

**Comment by MagicianWu** [comment]
<img width="662" alt="image" src="https://github.com/huggingface/accelerate/assets/68132494/1456d96c-06a7-44dd-9953-695c0629a892">

**Comment by MagicianWu** [comment]
Should I reinstall accelerate or the whole environment?

**Comment by MagicianWu** [comment]
@muellerzr Thanks for your help! Problems in this issue and [issue2621](https://github.com/huggingface/accelerate/issues/2621) are resolved!

**Comment by muellerzr** [comment]
Fantastic! Glad to hear it @MagicianWu :)
