### ISSUE TITLE
Cuda is not available after using accelerate launch to run script

### ISSUE THREAD

**Issue by MagicianWu** [huggingface/accelerate#2626]
### System Info

```Shell
- `Accelerate` version: 0.28.0
- Platform: Linux-5.4.0-173-generic-x86_64-with-glibc2.31
- Python version: 3.10.14
- Numpy version: 1.26.4
- PyTorch version (GPU?): 2.2.1+cu121 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 2015.53 GB
- GPU type: NVIDIA A800-SXM4-80GB
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: bf16
        - use_cpu: False
        - debug: True
        - num_processes: 8
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: [0,1,2,3,4,5,6,7]
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: F
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

```python
import torch
from accelerate import Accelerator

def main():
    accelerator = Accelerator()
    accelerator.print(torch.cuda.is_available())

if __name__ == "__main__":
    main()
``` 
![image](https://github.com/huggingface/accelerate/assets/68132494/8fc1582a-6e40-49d6-aa25-342aa4bce84c)

### Expected behavior

torch.cuda.is_available() should return True

**Comment by SunMarc** [comment]
Hi @MagicianWu, I'm unable to reproduce this behavior. Did you try reinstalling torch with cuda ? Does this happens only after you initialize `Accelerator()` ?
