### ISSUE TITLE
Significant performance regression on `PartialState` initialization

### ISSUE THREAD

**Issue by carefree0910** [huggingface/accelerate#2633]
The regression comes from this line:

```python
if self.device.type == "cuda" and not check_cuda_p2p_ib_support():
    ...
```

because `check_cuda_p2p_ib_support` is very slow.

This regression will cause many things to be very slow as well (e.g., the plain `wait_for_everyone` function, which may be critical because `wait_for_everyone` was almost no-op before).

**Comment by carefree0910** [comment]
One possible quick fix is to make this line a one-time checker, but it might make the codes ugly 😂

> btw by saying it 'very slow', it does not mean a single call (which is ~300ms i guess) is very slow. It will only become unbearable when i call it crazily as i did in version 0.28.0).

**Comment by muellerzr** [comment]
It's quite alright, I can see the chunk that is being called again. This class uses the Singleton design, so it doesn't need the LRU cache. We just need to put that block of code under the initialization check (which it wasn't before)

**Comment by carefree0910** [comment]
Ah, true, will be much neater!
