### ISSUE TITLE
missing parentheses when calling `is_xpu_avaliable`

### ISSUE THREAD

**Issue by ArthurinRUC** [huggingface/accelerate#2637]
Hi, I wonder if the code is missing a pair of parentheses when calling `is_xpu_avaliable`, should it be `is_xpu_avaliable()` instead?
https://github.com/huggingface/accelerate/blob/6d92198ef4d162a4e9e4ffc350586174bd771e7f/src/accelerate/state.py#L207-L210

**Comment by muellerzr** [comment]
Yes indeed! Would you like to make a PR? :)

**Comment by ArthurinRUC** [comment]
Thanks a lot :D
