### ISSUE TITLE
Why to use convert_outputs_to_fp32 for prepare_model on mixed precision training

### ISSUE THREAD

**Issue by npuichigo** [huggingface/accelerate#2638]
### System Info

```Shell
- `Accelerate` version: 0.29.1
- Platform: Linux-5.19.0-46-generic-x86_64-with-glibc2.35
- `accelerate` bash location: /home/yuchao/miniconda3/envs/TorchTTS/bin/accelerate
- Python version: 3.10.13
- Numpy version: 1.23.5
- PyTorch version (GPU?): 2.2.1+cu118 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- PyTorch MLU available: False
- System RAM: 125.48 GB
- GPU type: NVIDIA GeForce RTX 4090
- `Accelerate` default config:
        Not found
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

The document says `For the best performance with Accelerate, the loss should be computed inside your model (like in Transformers models) because computations outside of the model are computed in full precision. `, but in engineering it may break the code structure and couple the model forwarding and loss computation which may always be `None` for inference.

The main problem is the use of `convert_outputs_to_fp32` when preparing models, which cast the model outputs to `fp32` explicitly instead of using `fp16` for loss calculatation.

Two questions：
1. would that hurt performance if I calculate loss after `convert_outputs_to_fp32`. 
2. If yes, why not provide a way to disable it or that may break the training process?

### Expected behavior

Able to do amp training like use raw python script, at least should work for the PyTorch official tutorial codes. https://pytorch.org/tutorials/recipes/recipes/amp_recipe.html

```
use_amp = True

net = make_model(in_size, out_size, num_layers)
opt = [torch.optim.SGD](https://pytorch.org/docs/stable/generated/torch.optim.SGD.html#torch.optim.SGD)(net.parameters(), lr=0.001)
scaler = [torch.cuda.amp.GradScaler](https://pytorch.org/docs/stable/amp.html#torch.cuda.amp.GradScaler)(enabled=use_amp)

start_timer()
for epoch in range(epochs):
    for input, target in zip(data, targets):
        with [torch.autocast](https://pytorch.org/docs/stable/amp.html#torch.autocast)(device_type=device, dtype=torch.float16, enabled=use_amp):
            output = net(input)
            loss = loss_fn(output, target)
        scaler.scale(loss).backward()
        scaler.step(opt)
        scaler.update()
        opt.zero_grad() # set_to_none=True here can modestly improve performance
end_timer_and_print("Mixed precision:")
```

**Comment by muellerzr** [comment]
You can see Sylvain's answer here: https://github.com/huggingface/accelerate/issues/382#issuecomment-1134792983

It shouldn't, if you're truly worried about that then you can just remove it, we don't have a flag for this though because no one has noticed issues with this for the 2+ years it's been a part of the library. 

```python
# after prepare
model.forward = model.forward.__wrapped__
```

**Comment by raphael-sch** [comment]
So i have a use case where this is needed. When values are returned that are not needed to compute the loss, e.g. image_hidden_states in VLMs, then I don't want them to be upcasted automatically because it spikes memory and is not needed in full precision. Zach's solution doesn't work for me:

`TypeError: Idefics3ForConditionalGeneration.forward() missing 1 required positional argument: 'self'`

**Comment by raphael-sch** [comment]
Found a workaround. You have to wrap the model outputs in a structure that isn't iterable:

`class ProtectHalfPrecisionOutputWrapper:
    def __init__(self, logits=None, image_hidden_states=None):
        self.logits = logits
        self.image_hidden_states = image_hidden_states`
