### ISSUE TITLE
allow `strict=True` in `load_checkpoint_and_dispatch`

### ISSUE THREAD

**Issue by yiyixuxu** [huggingface/accelerate#2640]
### System Info

```Shell
accelerate = 0.29.1
```

### Information

this PR https://github.com/huggingface/accelerate/pull/2588 breaks the loading behavior in diffusers when:
1. `accelerate.load_checkpoint_and_dispatch` is used
2. the checkpoint contains deprecated weight names for the attention class 

As you can see [here](https://github.com/huggingface/diffusers/blob/7e808e768a7305b3f8f9e981ad14f2de3598e9a6/src/diffusers/models/modeling_utils.py#L703), we rely on the error to rename the parameters' names on our end. Is there a better way to do this in diffusers? 
The alternative is to allow us a pass a `strict=True` from `load_checkpoint_and_dispatch`- let me know what you think :)

### Reproduction

this script fails currently but it should not 
```python
from diffusers import DiffusionPipeline
pipe = DiffusionPipeline.from_pretrained(
    "hf-internal-testing/tiny-stable-diffusion-pipe", device_map="sequential", safety_checker=None
)
```

**Comment by yiyixuxu** [comment]
cc @SunMarc

**Comment by SunMarc** [comment]
Let's just pass `strict=True` in `load_checkpoint_and_dispatch`. Sorry for introducing a breaking change ;)
