### ISSUE TITLE
Does Accelerate support speed up custom cuda forward?

### ISSUE THREAD

**Issue by EricLina** [huggingface/accelerate#2648]
Hello
I've defined some [custom cuda function](https://github.com/state-spaces/mamba/tree/main/csrc/selective_scan) in the python code, but I haven't observed significant reductions in memory usage and execution time through Accelerate. 

So my question is does accelerate support to speed up custom cuda forward?

**Comment by muellerzr** [comment]
No, I don't think it should at all. Accelerate just helps with optimizing DDP etc easier.
