### ISSUE TITLE
Some questions about saving checkpoints and logging

### ISSUE THREAD

**Issue by XuecWu** [huggingface/accelerate#265]
Hi, thank you for your great work! I am so glad to find accelerate. But I have some questions with accelerate. Here, I set my process to 2.
1. I follow the README to change my train script, but the logs printed out is very chaotic.  
2. I saved two checkpoints 
3. Training time has not decreased and the loss decrease cannot exceed that of DataParallel used before.
 Thank you and I am looking forward to your reply.

**Comment by sgugger** [comment]
I am sorry, I don't understand what your issue is. Please also be aware that without code to reproduce, there is little we can do to help you and fix it :-)

**Comment by XuecWu** [comment]
Thank you for your reply. I have fixed it.
