### ISSUE TITLE
Resume training from checkpoint: logger tensorboard/wandb

### ISSUE THREAD

**Issue by luisaforozco** [huggingface/accelerate#2653]
I've looked trough the issues and examples but I do not seem to find a way to **save and load the state or information of the logger** (tensorboard or wandb).

When loading the checkpoint back via `accelerator.load_state` the logging does not continue on the previous file (tensorboard)/ run (wandb) but creates a new one. 

Indeed, if one is resuming a training I think one would like that the results get logged in the same logger and not a separate one.

**Comment by kerkathy** [comment]
hey @luisaforozco did you find any solution ? I'm having the same issue

**Comment by luisaforozco** [comment]
> hey @luisaforozco did you find any solution ? I'm having the same issue

No solution 😞

**Comment by jiuntian** [comment]
Hi, I found this post while I was looking on the same problem, I have tried to resume log on wandb with the following:

```python
tracker_init_kwargs = {}
for tracker in accelerator.log_with:
    if str(tracker) == "wandb" and args.wandb_resume_id:
        logger.info(f"Resuming wandb run on id=`{args.wandb_resume_id}`.")
        tracker_init_kwargs = {
            "wandb": {
                "id": args.wandb_resume_id,
                "resume": "allow",
            },
        }
accelerator.init_trackers("project-name",
                          config=vars(args),
                          init_kwargs=tracker_init_kwargs,
                          )
```

Hope this could help.
