### ISSUE TITLE
How can I use "accelerate launch" in my anaconda virtual environment?

### ISSUE THREAD

**Issue by hummingbird2030** [huggingface/accelerate#2660]
I have installed accelerate by using the following command in my own anaconda environment: pip install accelerate But when I try to locate the path of accelerate, it appears like: 

> which accelerate 
/home/user/.local/bin/accelerate

I also try to use accelerate to train a model by using the following command, after activate my anaconda env: 
`CUDA_VISIBLE_DEVICES=0 accelerate launch \ --mixed_precision bf16 \ --num_machines 1 \ --num_cpu_threads_per_process 2 \ --num_processes $NUM_GPUS \ --use_deepspeed \ --deepspeed_config_file stage3_no_offloading_accelerate.conf \ finetune.py \ --model_name_or_path  ../../Llama-2-7b-hf \ --use_flash_attn \ --tokenizer_name ../../Llama-2-7b-hf \ --use_slow_tokenizer \ --train_file full_output_1005.jsonl \ --max_seq_length 2048 \ --preprocessing_num_workers 16 \ --per_device_train_batch_size $BATCH_SIZE_PER_GPU \ --gradient_accumulation_steps $GRADIENT_ACC_STEPS \ --learning_rate 2e-5 \ --lr_scheduler_type linear \ --warmup_ratio 0.03 \ --weight_decay 0. \ --num_train_epochs 3 \ --output_dir output/self_rag_${MODEL_SIZE}/ \ --with_tracking \ --report_to tensorboard \ --logging_steps 1 \ --use_special_tokens`

 Similar bug appeared:

>  Traceback (most recent call last): File "/home/user/.local/bin/accelerate", line 8, in <module> sys.exit(main()) File "/home/user/.local/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main args.func(args) File "/home/user/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 995, in launch_command args, defaults, mp_from_config_flag = _validate_launch_command(args) File "/home/user/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 928, in _validate_launch_command raise ValueError(err.format(mode="bf16", requirement="PyTorch >= 1.10 and a supported device.")) ValueError: bf16 mixed precision requires PyTorch >= 1.10 and a supported device.

In fact, I have install torch in my anaconda env, but it seems that "accelerate launch" didn't use my virtual env. I wonder how to fix this problem.

**Comment by muellerzr** [comment]
Do you have `accelerate` installed in your non-conda base pip env? This is likely the reason.

**Comment by hummingbird2030** [comment]
> Do you have `accelerate` installed in your non-conda base pip env? This is likely the reason.

I have installed accelerate in my base env. When I use `which accelerate`, its response is `/home/user/.local/bin/accelerate`, which is in my base env.

**Comment by muellerzr** [comment]
I’d recommend not doing that and limiting it to non-base envs only, as they each have their own env-based bash local to use. And doing so like this results to a large influx of issues such as what you’ve observed here

**Comment by hummingbird2030** [comment]
> I’d recommend not doing that and limiting it to non-base envs only, as they each have their own env-based bash local to use. And doing so like this results to a large influx of issues such as what you’ve observed here

Thank you for your prompt reply. I wonder how to limit it to 'non-base envs' only. Does it mean  I can create other  envs using `conda create -n my_env`?

**Comment by muellerzr** [comment]
Yes. Then activate them and install accelerate in those envs specifically

**Comment by hummingbird2030** [comment]
> Yes. Then activate them and install accelerate in those envs specifically

Thanks. But in fact I have installed accelerate in my non-base env. I activated my non-base env and it appeared this bug. It seems like accelerate links to base env. And I don't know how to fix it.
![image](https://github.com/huggingface/accelerate/assets/78951476/61ae086d-8e1c-4226-b0f0-894248577604)

**Comment by muellerzr** [comment]
You need to do the following:

```bash
conda deactivate
pip uninstall accelerate -y
conda activate base
pip uninstall accelerate -y
rm /home/{thing you blurred out}/.local/bin/accelerate
conda activate rag
pip install accelerate --force-reinstall --no-deps
```

This will fully remove the old, broken file and install the new one

**Comment by hummingbird2030** [comment]
> You need to do the following:
> 
> ```shell
> conda deactivate
> pip uninstall accelerate -y
> conda activate base
> pip uninstall accelerate -y
> rm /home/{thing you blurred out}/.local/bin/accelerate
> conda activate rag
> pip install accelerate --force-reinstall --no-deps
> ```
> 
> This will fully remove the old, broken file and install the new one

Thank you for your detailed solution. I solved the problem with this method you provided.

**Comment by hummingbird2030** [comment]
> You need to do the following:
> 
> ```shell
> conda deactivate
> pip uninstall accelerate -y
> conda activate base
> pip uninstall accelerate -y
> rm /home/{thing you blurred out}/.local/bin/accelerate
> conda activate rag
> pip install accelerate --force-reinstall --no-deps
> ```
> 
> This will fully remove the old, broken file and install the new one

Hello, I wonder the reason why this problem occurs. I solved the problem you provided yesterday, but today the same problem appears again. I didn't change my env, but the problem occurs again!  I wonder what I have changed. :(

**Comment by muellerzr** [comment]
The dual env issue may arise from this: https://x.com/TheZachMueller/status/1778912110547959853
