### ISSUE TITLE
doc typo in "Start Here!"

### ISSUE THREAD

**Issue by lc150303** [huggingface/accelerate#2661]
https://huggingface.co/docs/accelerate/main/en/usage_guides/explore

Missing a comma in line 3 after "optimizer".

![45A)U 8S 9@PZ`` 5U3S}_B](https://github.com/huggingface/accelerate/assets/33141649/1475fcca-488d-42e3-8a44-a6a2bee0397b)

**Comment by BenjaminBossan** [comment]
Indeed, thanks for reporting this. Not sure how to create a PR on the embedded Space, @muellerzr can you fix this?

**Comment by muellerzr** [comment]
Yep, otherwise a PR can be opened here: https://huggingface.co/spaces/hf-accelerate/accelerate_examples/

**Comment by muellerzr** [comment]
Thanks for reporting! I've fixed this in `main`, should be rebuilt shortly.

**Comment by BenjaminBossan** [comment]
Thanks, Zach, this is fixed now.
