### ISSUE TITLE
Use accelerate for finetuning model via multi node and multi gpu

### ISSUE THREAD

**Issue by OriAlpha** [huggingface/accelerate#2678]
Hallo, 

Does anyone have suggestion for finetuning a model via slrum on multinode and multigpu. I have seen examples for model train in https://github.com/huggingface/accelerate/tree/main/examples but this a basic example. 
But is there any option to combine this for finetuning model since it uses `TrainingArguments` api from transformers and `SFTTrainer` api from trl: 
```
training_arguments = TrainingArguments(
        output_dir=model_details["output_dir"],  # directory to save and repository id
        num_train_epochs=num_train_epochs,  # number of training epochs
        ......................................
    )

  trainer = SFTTrainer(
      model=peft_model,
      train_dataset=train_dataset,
      eval_dataset=eval_dataset,
      ................................
  )
```

**Comment by muellerzr** [comment]
Your code won't change, what matters is how you launch the code. So just have your own scripts and then launch using the recommendations for slurm over in the `examples` https://github.com/huggingface/accelerate/tree/main/examples/slurm

**Comment by OriAlpha** [comment]
Thanks for your answer i will check it out.

**Comment by OriAlpha** [comment]
I was able to run model via multi node and multi gpu. Now i need to reduce my batchsize before i was able to train my model on 2 GPUs around 30 batch size, after runing on multi node i have to reduce my batch size to 5, which is very less and i feel, something is wrong. 

Is there somthing i need to add changes in code so its traning faster, i am using BitsAndBytesConfig and flash_attention_2

```
    peft_config = LoraConfig(
        r=256,
        lora_alpha=512,
        lora_dropout=0.25,
        target_modules="all-linear",
        task_type="CAUSAL_LM",
        bias="none",
    )

quantization_config = BitsAndBytesConfig(
          load_in_4bit=True,
          bnb_4bit_use_double_quant=True,
          bnb_4bit_quant_type="nf4",
          bnb_4bit_compute_dtype=torch.bfloat16,
      )

gradient_checkpointing = True

model_kwargs = dict(
    attn_implementation="flash_attention_2",
    torch_dtype=torch.bfloat16,
    use_cache=False if gradient_checkpointing else True,
    device_map=get_kbit_device_map() if quantization_config is not None else None,
    quantization_config=quantization_config,

)

training_arguments = TrainingArguments(
        output_dir=model_details["output_dir"],  # directory to save and repository id
        num_train_epochs=num_train_epochs,  # number of training epochs
        ......................................
    )

  trainer = SFTTrainer(
      model=model_name,
      model_init_kwargs=model_kwargs,
      peft_config=peft_config,
      train_dataset=train_dataset,
      eval_dataset=eval_dataset,
      ................................
  )
```
