### ISSUE TITLE
Should `torch.nn.SyncBatchNorm` added by myself if I need?

### ISSUE THREAD

**Issue by avsdfirst** [huggingface/accelerate#268]
Should `torch.nn.SyncBatchNorm` added by myself if I need?
Because I don't find `nn.SyncBatchNorm` in function `prepare_model()` in `accelerate/src/accelerate/accelerator.py`

**Comment by sgugger** [comment]
Please use the [forums](https://discuss.huggingface.co/) to ask questions as we keep issues for bugs and feature requests only.

You should write the model with the layers you need. Accelerate won't change them.
