### ISSUE TITLE
`wait_for_everyone` hang the GPUs

### ISSUE THREAD

**Issue by nmd2k** [huggingface/accelerate#2690]
### System Info

```Shell
OS: ubuntu 20.04
Pytorch: 2.2.0
Transformers: 4.39.0
Accelerate: 0.27.2
```

### Information

- [x] The official example scripts
- [x] My own modified scripts

### Tasks

- [x] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

I used code from the examples: [https://github.com/huggingface/transformers/blob/main/examples/pytorch/language-modeling/run_clm_no_trainer.py#L682](https://github.com/huggingface/transformers/blob/main/examples/pytorch/language-modeling/run_clm_no_trainer.py#L682)

But modified the saving process with addition else using `wait_for_everyone()`

### Expected behavior

The GPUs started to hang after the saving process was done, and no progress was made after then.

```python
if accelerator.is_main_process:
        unwrapped_model = accelerator.unwrap_model(model)

        state_dict = accelerator.get_state_dict(model)
        unwrapped_model.save_pretrained(output_dir, state_dict=state_dict, safe_serialization=True)

        tokenizer.save_pretrained(output_dir)
        
    else:
        accelerator.wait_for_everyone()
```

And I noticed when the main process was saving weight, the others were computing something (until nccl timeout)
![image](https://github.com/huggingface/accelerate/assets/48562727/96842e9a-69bb-4ad8-a5fd-780c3a094447)

Idk what `wait_for_everyone()` does in the backend, or maybe, can someone confirm that `wait_for_everyone` is not necessary in this case (since remove it solve the hanging problem).

**Comment by muellerzr** [comment]
`wait_for_everyone` needs to be outside of your loop, as it waits for *everyone* to be at that point. Your main process will never hit `else`, so your main process is the one hanging things :) 

Aka:

```python
if accelerator.is_main_process:
        unwrapped_model = accelerator.unwrap_model(model)

        state_dict = accelerator.get_state_dict(model)
        unwrapped_model.save_pretrained(output_dir, state_dict=state_dict, safe_serialization=True)

        tokenizer.save_pretrained(output_dir)
        
accelerator.wait_for_everyone()
```
