### ISSUE TITLE
Typo in examples README

### ISSUE THREAD

**Issue by arjunchandra** [huggingface/accelerate#27]
Happened to find a typo in the [examples README](https://github.com/arjunchandra/accelerate/blob/main/examples/README.md).
Lines `60` and `148` use the option `fb16`, which I believe should be `fp16`.

Thank you for this new library and launch tool!

**Comment by sgugger** [comment]
That's right, thanks! Do you want make a PR to fix it?

**Comment by arjunchandra** [comment]
Sure -- https://github.com/huggingface/accelerate/pull/28

**Comment by sgugger** [comment]
Fixed by #28 thanks :-)
