### ISSUE TITLE
`utils.is_bf16_available` does not check for MPS device

### ISSUE THREAD

**Issue by ggoggam** [huggingface/accelerate#2700]
### System Info

```Shell
- `Accelerate` version: 0.29.2
- Platform: macOS-14.4.1-arm64-arm-64bit
- `accelerate` bash location: /opt/homebrew/Caskroom/miniconda/base/envs/ojk/bin/accelerate
- Python version: 3.10.13
- Numpy version: 1.24.1
- PyTorch version (GPU?): 2.2.1 (False)
- PyTorch XPU available: False
- PyTorch NPU available: False
- PyTorch MLU available: False
- System RAM: 32.00 GB
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: NO
        - mixed_precision: no
        - use_cpu: False
        - debug: False
        - num_processes: 1
        - machine_rank: 0
        - num_machines: 1
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - enable_cpu_affinity: False
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

Pretty straight forward.  Calling `is_bf16_available` returns `True` on MPS devices (e.g. Mac M1/M2)

```python
from accelerate.utils import is_bf16_available

print(is_bf16_available())

>>> True
```

### Expected behavior

It should return `False`.

**Comment by muellerzr** [comment]
cc @SunMarc

**Comment by SunMarc** [comment]
This should be fixed [here](https://github.com/huggingface/accelerate/pull/2699#event-12575795407) !

**Comment by ggoggam** [comment]
I am closing this as it is being resolved!
