### ISSUE TITLE
[diffusers]`cpu_offload` does not work with models with buffers 

### ISSUE THREAD

**Issue by yiyixuxu** [huggingface/accelerate#2701]
In diffusers, certain models do not work correctly with `enable_sequential_cpu_offload`; I would like to understand why and what is the best way to handle them.

we have been excluding some models from the offloading by adding them to the `_exclude_from_cpu_offload` list of the pipeline e.g. https://github.com/huggingface/diffusers/blob/7404f1e9dcdac286caf6ca3cfa43b294f61583bf/src/diffusers/pipelines/unclip/pipeline_unclip.py#L65; However, by doing this we also exclude the model from `enalbe_model_cpu_offload()`, which is a more popular offloading method and would have worked correctly with these models

I attached a reproducible script (basically this code here https://github.com/huggingface/diffusers/blob/7404f1e9dcdac286caf6ca3cfa43b294f61583bf/src/diffusers/pipelines/pipeline_utils.py#L1163), we expect it to return a `AlignDevicesHook,` but ia `SequentialHook` is attached instead

Sorry in advance if this has been looked into, I could not find relevant conversation, so I think that knowledge has been lost. 

### Reproduction

```python
# test hook on transformer (pixart-alpha)

from diffusers import Transformer2DModel
from accelerate import cpu_offload
import torch

weight_dtype = torch.float16
device = "cuda"

model = Transformer2DModel.from_pretrained(
    "PixArt-alpha/PixArt-Alpha-DMD-XL-2-512x512", 
    subfolder="transformer", torch_dtype=weight_dtype)

print(f" before offload")
try:
    print(f"_hf_hook: {model._hf_hook}")
except AttributeError:
    print("_hf_hook not found")
print(f" model._paramters: {model._parameters}")
offload_buffers = len(model._parameters) > 0
print(f"offload_buffers: {offload_buffers}")
cpu_offload(model, device, offload_buffers=offload_buffers)

print(f" after offload")
try:
    print(f"_hf_hook: {model._hf_hook}")
except AttributeError:
    print("_hf_hook not found")
```

```
 before offload
_hf_hook not found
 model._paramters: OrderedDict([('scale_shift_table', Parameter containing:
tensor([[ 2.3560e-02,  6.9714e-04,  1.3666e-03,  ...,  1.3800e-03,
         -6.7940e-03,  7.0095e-04],
        [-9.4092e-01, -9.7852e-01, -9.8242e-01,  ..., -9.8291e-01,
         -9.6777e-01, -9.9072e-01]], dtype=torch.float16, requires_grad=True))])
offload_buffers: True
 after offload
_hf_hook: <accelerate.hooks.SequentialHook object at 0x7f76429a3fd0>
```

### System Info

```Shell
accelerate == '0.29.3'
```

**Comment by yiyixuxu** [comment]
or is this expected, and we just have to update our logic to remove hooks here?https://github.com/huggingface/diffusers/blob/7404f1e9dcdac286caf6ca3cfa43b294f61583bf/src/diffusers/pipelines/pipeline_utils.py#L1008

**Comment by muellerzr** [comment]
cc @SunMarc

**Comment by SunMarc** [comment]
Hi @yiyixuxu, this is expected when you use `cpu_offload`. You get a `SequentialHook` because in `cpu_offload`, we add a hook to make sure that we put back the `input_data` where it was (`io_same_device=True`). On top of that, we add the `hook` to enable the cpu offload. Hence, to combine those two hooks, we just the `SequentialHook` class.  I think that you can just update your logic to remove the hooks. Hope that it helps you fix the issue with `_exclude_from_cpu_offload` !

**Comment by yiyixuxu** [comment]
@SunMarc thanks!
