### ISSUE TITLE
NCCL timeout remains at 600s and does not get updated if 1800s passed when initializing Accelerator

### ISSUE THREAD

**Issue by jubueche** [huggingface/accelerate#2703]
### System Info

```Shell
Accelerate version: 0.30.0.dev0
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

When doing 
```
init_proc = InitProcessGroupKwargs(timeout=timedelta(seconds=1800))
accelerator = Accelerator(log_with="wandb", kwargs_handlers=[init_proc])
```
This won't update the timeout [here](https://github.com/huggingface/accelerate/blob/f7daaaa305362e1a959183e23bf85244798ceb35/src/accelerate/state.py#L213).
Why? Because the `kwargs` are generated by `init_proc.get_kwargs()` which returns `{}` if the timeout is the defualt. However, for `torch.distributed.init_process_group` the default timeout **is not** 1800s.

So maybe change the default in `InitProcessGroupKwargs` to 600?

### Expected behavior

It should set the timeout correctly.

**Comment by muellerzr** [comment]
Yes, we need to update those to be aligned with the torch defaults, as they changed recently. Would you like to open a PR for this?

**Comment by jubueche** [comment]
Yes added one.
