### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'debug'

### ISSUE THREAD

**Issue by qinchangchang** [huggingface/accelerate#2719]
### System Info

```Shell
run code as follows:
export MODEL_NAME="CompVis/stable-diffusion-v1-4" \
export TRAIN_DATA_DIR="./data/data_p/0.2_fourier_removeeval_alpha_0.15_beta_0.1/train" \
export OUTPUT_DIR="./model/0.2_fourier_removeeval_alpha_0.15_beta_0.1" \

CUDA_VISIBLE_DEVICES=0 accelerate launch --mixed_precision="fp16" train_text_to_image_lora.py \
--pretrained_model_name_or_path=$MODEL_NAME \
--train_data_dir=$TRAIN_DATA_DIR --caption_column="additional_feature" \
--resolution=512 --random_flip \
--train_batch_size=1 \
--num_train_epochs=100 --checkpointing_steps=5000 \
--learning_rate=1e-04 --lr_scheduler="constant" --lr_warmup_steps=0 \
--seed=42 \
--output_dir=$OUTPUT_DIR \
--validation_prompt=None --report_to="wandb"
bug is as follows:
  File "/home/qc/miniconda3/envs/FIBA/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/qc/miniconda3/envs/FIBA/lib/python3.7/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/qc/miniconda3/envs/FIBA/lib/python3.7/site-packages/accelerate/commands/launch.py", line 918, in launch_command
    args, defaults, mp_from_config_flag = _validate_launch_command(args)
  File "/home/qc/miniconda3/envs/FIBA/lib/python3.7/site-packages/accelerate/commands/launch.py", line 805, in _validate_launch_command
    defaults = load_config_from_file(args.config_file)
  File "/home/qc/miniconda3/envs/FIBA/lib/python3.7/site-packages/accelerate/commands/config/config_args.py", line 72, in load_config_from_file
    return config_class.from_yaml_file(yaml_file=config_file)
  File "/home/qc/miniconda3/envs/FIBA/lib/python3.7/site-packages/accelerate/commands/config/config_args.py", line 135, in from_yaml_file
    return cls(**config_dict)
TypeError: __init__() got an unexpected keyword argument 'debug'
python_version:3.7;accelerate_version:0.20.3
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

I just run the text-to-image-lora.py, followed by the official scripts but my own datasets.
export MODEL_NAME="CompVis/stable-diffusion-v1-4" \
export TRAIN_DATA_DIR="./data/data_p/0.2_fourier_removeeval_alpha_0.15_beta_0.1/train" \
export OUTPUT_DIR="./model/0.2_fourier_removeeval_alpha_0.15_beta_0.1" \

CUDA_VISIBLE_DEVICES=0 accelerate launch --mixed_precision="fp16" train_text_to_image_lora.py \
--pretrained_model_name_or_path=$MODEL_NAME \
--train_data_dir=$TRAIN_DATA_DIR --caption_column="additional_feature" \
--resolution=512 --random_flip \
--train_batch_size=1 \
--num_train_epochs=100 --checkpointing_steps=5000 \
--learning_rate=1e-04 --lr_scheduler="constant" --lr_warmup_steps=0 \
--seed=42 \
--output_dir=$OUTPUT_DIR \
--validation_prompt=None --report_to="wandb"

### Expected behavior

run

**Comment by muellerzr** [comment]
Debug was added in v0.22.0. You need a higher python version and accelerate version to use this. (We've required at least python 3.8 for a while as 3.7 has been EOL for a bit)
