### ISSUE TITLE
Make it possible to pickle accelerated model with AMP

### ISSUE THREAD

**Issue by BenjaminBossan** [huggingface/accelerate#273]
Currently, when using accelerate with AMP, the resulting module is being modified so that it can no longer be pickled. The reason is that the `forward` method of the module is replaced by a decorated function:

https://github.com/huggingface/accelerate/blob/6ffab178accebda485295bddf8eb6bf436ff698f/src/accelerate/accelerator.py#L363

The decorated function, since it uses a closure, cannot be pickled. This is unfortunate because normally, PyTorch modules can be pickled and pickling is useful/necessary in certain circumstances.

A possible solution would be to wrap the function with a class instead of a closure:

```python
import pickle
from accelerate.utils import convert_to_fp32, convert_outputs_to_fp32
from transformers import AutoModelForSequenceClassification

# PROBLEM
bert = AutoModelForSequenceClassification.from_pretrained('bert-base-uncased')
bert.forward = convert_outputs_to_fp32(bert.forward)
_ = pickle.dumps(bert)  # fails

# SOLUTION
from functools import update_wrapper

class ConvertOutputsToFp32:
    def __init__(self, model_forward):
        self.model_forward = model_forward
        update_wrapper(self, model_forward)  # optional
    def __call__(self, *args, **kwargs):
        return convert_to_fp32(self.model_forward(*args, **kwargs))

bert = AutoModelForSequenceClassification.from_pretrained('bert-base-uncased')
bert.forward = ConvertOutputsToFp32(bert.forward)
_ = pickle.dumps(bert)  # works
```

It's not beautiful but it would solve the issue. Alternatively, there might be a way to achieve the same thing using [forward hooks](https://pytorch.org/tutorials/beginner/former_torchies/nnft_tutorial.html#forward-and-backward-function-hooks) but I'm not sure.

Info: `accelerate.__version__` tested was 0.5.1.

NB: When using decorators, it is recommended to use [`functools.wraps`](https://docs.python.org/3/library/functools.html#functools.wraps). This way, `help(bert.forward)` shows the correct help. This is why I use `update_wrapper` in the proposed code, it does the same thing.

**Comment by sgugger** [comment]
Thanks for flagging this and suggesting a solution. While using a class is not my first choice, it does work to solve the problem, so we should use this. Would you mind opening a PR with code since you proposed it?

**Comment by sgugger** [comment]
I think you can test whether the model pickles or not as you did on any device. It's when trying to run training that we would need a GPU (and not even, basic operations can run on CPU with float16). I'm pretty sure the model in testing-utils/training can be used for instance in FP16 on CPU.
