### ISSUE TITLE
The logic of some methods is too complex

### ISSUE THREAD

**Issue by Iain-S** [huggingface/accelerate#2731]
The quantity of conditional logic in some methods/functions makes them difficult to follow. For example, [PartialState.\_\_init\_\_](https://github.com/huggingface/accelerate/blob/2c767338f29989e54ce93b3036b41e02013af7a7/src/accelerate/state.py#L111) has a cyclomatic complexity of 25 and [Accelerator.\_\_init\_\_](https://github.com/huggingface/accelerate/blob/2c767338f29989e54ce93b3036b41e02013af7a7/src/accelerate/accelerator.py#L246) has a CC of 54 (as measured by enabling the "C90" ruff rule, which has a default max CC of 10). 

It looks like PartialState and AcceleratorState are mostly trying to:

1. Dynamically import libraries such as ipex and deepspeed.
2. Set environment variables needed by those libraries and/or other parts of Accelerate.
3. Choose which launcher to use.
4. Perform some sanity checks.

...but those concerns have become entangled. I think they could be simplified and am happy to give it a shot if the PR would be welcome, though I would probably need to know a bit more about the motivation behind the Borg-esque state dict shared between the two state classes.

In addition to lowering the complexity of some methods for the reader, I would suggest checking for pre-existing env var values before overriding them. For example, it's plausible that a user could manually set CCL_PROCESS_LAUNCHER only to have it [silently overridden](https://github.com/huggingface/accelerate/blob/2c767338f29989e54ce93b3036b41e02013af7a7/src/accelerate/state.py#L222). It should be straightforward to add a convenience function that checks for an existing, conflicting value before writing a new one.

**Comment by muellerzr** [comment]
You can try, certainly, however those methods are that complex/centralized for a reason. After the recent refactor as well they're done in a way to allow for easier leveraging of new backends. 

Can you explain with an example of where you see they have become "entangled"?

**Comment by Iain-S** [comment]
> they're done in a way to allow for easier leveraging of new backends

Great, I shall bear that in mind.

> Can you explain with an example of where you see they have become "entangled"?

Absolutely, though I won't have a chance for a couple of days.

**Comment by Iain-S** [comment]
OK, I think I can summarise the thing that I found confusing. There are effectively four ways that "config" is handled (where "config" means some kind of run-time option):

1. CLI options, such as `--cpu`.
2. Config file values, such as `use_cpu: true`, which are loaded into Base/Cluster/SageMaker Config objects.
3. Environment variables, such as `ACCELERATE_USE_CPU=true`.
4. Partial/Accelerator State member variables, such as `self._cpu`.

In `commands/launch.py`, we parse CLI args and then merge them with the config file (see recent PR linked above). Then, in `utils/launch.py`, we sort-of serialise some of the args to env vars, as a way of sending info to sub-processes. 

https://github.com/huggingface/accelerate/blob/aa21174de9c47a9f5d772935413839e0633914c9/src/accelerate/utils/launch.py#L100

Then, in the child processes, in `state.py`, we de-serialise the env vars to set local variables.

It would take some work but, in the long run, I think it would be beneficial to combine these four things somewhat. This could be done, for example, by modifying the Config classes in `config_args.py`:

```python
def set_env(env: dict):
    """Set the environment variables from a dictionary."""
    for key, value in env.items():
        old_value = os.environ.get(key)
        if old_value != value:
            print("Overriding", key, "to", value, "from", old_value)
        os.environ[key] = str(value)

class SomeConfig(BaseConfig):
  def from_cli_args(self, args):
    if self.use_cpu is None:
      self.use_cpu = args.cpu
    ...  # handle other params
    super().from_cli_args(args)

  def to_env(self):
    env = {}
    env["ACCELERATE_USE_CPU"] = self.use_cpu
    ...  # handle other params
    set_env(env)
    super().set_env()

  def from_env(self):
    """Warning, will override any config or cli-derived defaults."""
    if os.environ.get("ACCELERATE_USE_CPU", None)
      self.use_cpu = os.environ["ACCELERATE_USE_CPU"]
    ...  # handle other params
    super().from_env()

class PartialState():
  def __init__(self, cpu=False):
    if something:  # decide whether we are on a cluster, or AWS, etc
      config = BaseConfig()
    else:
      config = ClusterConfig()
    
    config.from_env()

    if config.use_cpu or cpu:
      self.device = torch.device("cpu")
    ...
    
```
    
I think that this, or something like it, would have the following benefits:

* It would group the logic that converts CLI args into a config or a config to/from env vars.
* PartialState could have a `self.config`, which would remove the duplication between state, cli and config.
* Converting args to config has type-checking and code-completion benefits since the members of args are dynamic and harder to inspect, whereas they are more static for config classes.

**Comment by muellerzr** [comment]
I disagree with this, as the layered API approach with options between configs and not is on purpose, and having those interop is not something we want to have interact in this way with the library at this time. 

If you notice also I had to revert your PR, as it broke many things where defaults were not simple booleans/are complex. 

Users can either use their direct `Plugin` related classes or from a config file combined with `accelerate launch`. These are two distinct API choices that while I am looking at how we can combine them, touching with how the CLI operates is not the way forward with this.

**Comment by Iain-S** [comment]
Cool, no worries. I don't entirely follow your logic but I'm sure there are solid reasons for doing things the way you do.

I shall take a look at the reverted PR.
