### ISSUE TITLE
Loading llama model with empty weights

### ISSUE THREAD

**Issue by markovalexander** [huggingface/accelerate#2735]
### System Info

```Shell
- `Accelerate` version: 0.29.3
- Platform: Linux-5.15.0-1042-oracle-x86_64-with-glibc2.31
- `accelerate` bash location: .venv/bin/accelerate
- Python version: 3.10.14
- Numpy version: 1.26.4
- PyTorch version (GPU?): 2.3.0+cu121 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- PyTorch MLU available: False
- System RAM: 2015.67 GB
- GPU type: NVIDIA A100-SXM4-80GB
- `Accelerate` default config:
	Not found
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

```
import accelerate
import transformers
import torch


config = transformers.AutoConfig.from_pretrained("/mdoels/Llama-2-7b-chat-hf/")

with accelerate.init_empty_weights():
    model = transformers.LlamaForCausalLM(config)

model = accelerate.load_checkpoint_and_dispatch(model, "/models/Llama-2-7b-chat-hf/")
# model(inputs_ids=some_tensor)
```

Loading model results into warning (any value of include_buffer arg inside init_empty_weight):

`Some weights of the model checkpoint at /models/Llama-2-7b-chat-hf/ were not used when initializing LlamaForCausalLM: {'model.layers.9.self_attn.rotary_emb.inv_freq', 'model.layers.17.self_attn.rotary_emb.inv_freq', 'model.layers.22.self_attn.rotary_emb.inv_freq', 'model.layers.5.self_attn.rotary_emb.inv_freq', 'model.layers.15.self_attn.rotary_emb.inv_freq', 'model.layers.27.self_attn.rotary_emb.inv_freq', 'model.layers.21.self_attn.rotary_emb.inv_freq', 'model.layers.24.self_attn.rotary_emb.inv_freq', 'model.layers.6.self_attn.rotary_emb.inv_freq', 'model.layers.20.self_attn.rotary_emb.inv_freq', 'model.layers.2.self_attn.rotary_emb.inv_freq', 'model.layers.12.self_attn.rotary_emb.inv_freq', 'model.layers.18.self_attn.rotary_emb.inv_freq', 'model.layers.30.self_attn.rotary_emb.inv_freq', 'model.layers.1.self_attn.rotary_emb.inv_freq', 'model.layers.26.self_attn.rotary_emb.inv_freq', 'model.layers.31.self_attn.rotary_emb.inv_freq', 'model.layers.11.self_attn.rotary_emb.inv_freq', 'model.layers.4.self_attn.rotary_emb.inv_freq', 'model.layers.8.self_attn.rotary_emb.inv_freq', 'model.layers.0.self_attn.rotary_emb.inv_freq', 'model.layers.10.self_attn.rotary_emb.inv_freq', 'model.layers.19.self_attn.rotary_emb.inv_freq', 'model.layers.29.self_attn.rotary_emb.inv_freq', 'model.layers.13.self_attn.rotary_emb.inv_freq', 'model.layers.28.self_attn.rotary_emb.inv_freq', 'model.layers.25.self_attn.rotary_emb.inv_freq', 'model.layers.7.self_attn.rotary_emb.inv_freq', 'model.layers.16.self_attn.rotary_emb.inv_freq', 'model.layers.3.self_attn.rotary_emb.inv_freq', 'model.layers.23.self_attn.rotary_emb.inv_freq', 'model.layers.14.self_attn.rotary_emb.inv_freq'}. This may or may not be an issue - make sure that the checkpoint does not have unnecessary parameters, or that the model definition correctly corresponds to the checkpoint.
`

Trying to make forward pass results into error:

`RuntimeError: User specified an unsupported autocast device_type 'meta'
`

How can I load model? 

### Expected behavior

Model loads without warnings, forward pass works

**Comment by muellerzr** [comment]
cc @SunMarc

**Comment by SunMarc** [comment]
Hi @markovalexander , can you load your model like that :  `model = AutoModelforCausalLM.from_pretrained("meta-llama/Llama-2-7b-chat-hf", device_map="cpu")`. Also your checkpoint looks a bit strange since you shouldn't have `inv_freq` saved.

**Comment by markovalexander** [comment]
Hi @SunMarc ! Thanks for looking into it. Re: checkpoint -- it was downloaded from huggiingface hub probably the day it was released, so may be checkpoint in HF was updated (i.e. config has wrong number for "max_positional_embeddings" which was fixed in HF hub but I fixed it manually)

Regarding from_pretrained: It is taking extremely long time (4 minutes) to read the model with `from_pretrained`. 
I tried 

```
import transformers
import torch

quantization_config = transformers.BitsAndBytesConfig(
    load_in_4bit=True,
    llm_int8_threshold=6.0,
    llm_int8_has_fp16_weight=False,
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4")


with torch.device('cuda'):
    model = transformers.AutoModelForCausalLM.from_pretrained(
        "/inworld/public_models/llama_v2/Llama-2-7b-chat-hf/",
        quantization_config=quantization_config,
        torch_dtype=torch.bfloat16,
        config={"_flash_attn_2_enabled": True},)
        #device_map='cuda')
```
(when I passed device_map I removed torch context manager). Profiling also shows that most of the time is taken by "torch.half" function which should not happen here (I load bf16 weights and quantise them, where does torch.float16 appears?)

Anyway, for some reason loading is super slow with from_pretrained

**Comment by SunMarc** [comment]
Hi @markovalexander, thanks for the reproducer but i'm unable to reproduce your issue on a A100. It's taking me max 1min to load the model with the snippet you shared. Also You don't need the context manager at all when loading bnb model. We will put it on cuda nevertheless. Are you on the latest transformers ?

**Comment by markovalexander** [comment]
@SunMarc yes. I actually debugged slow loading and since you also cannot reproduce the issue I believe it's in slow disk IO operations. I think we can close it for now
