### ISSUE TITLE
Tool to get current installed versions

### ISSUE THREAD

**Issue by LysandreJik** [huggingface/accelerate#277]
A tool to get current installed versions helps when opening issues to provide all software versions in the current environment.

This helps to debug issues easier or to catch versions mismatches straight away. A similar tool has been implemented for transformers [here](https://github.com/huggingface/transformers/blob/master/src/transformers/commands/env.py).

Accelerate would benefit from such a tool, which could be as simple as a runtime method such as `get_versions()` as proposed in https://github.com/huggingface/accelerate/pull/254.

**Comment by johnnv1** [comment]
Hi, i  would like to work on this

**Comment by LysandreJik** [comment]
Thanks for your contribution @johnnv1! Closing this issue.
