### ISSUE TITLE
pdb like breakpoint Multiprocess Debugging with Accelerator

### ISSUE THREAD

**Issue by ermu2001** [huggingface/accelerate#2803]
# Feature request
Is it possible to have a pdb-like debug breakpoint with Accelerator that stops the program even when training or evaluating with multiple processes?

Currently, when running with a single process, we can use the following code to stop the program and debug:
```python
...
print('here')
pdb.set_trace();
...
```

However, this does not work when running multiprocess training. It would be highly beneficial to have an interface that stops the program during multiprocess training, allowing us to investigate the current state of variables. For example:

```python
accelerator = Accelerator()
...

print('here')
accelerator.set_trace() # stop all the process here and we can investigate on the current variables.
...
```

# Motivation
Switching between single-process and multiprocess training can be burdensome. Additionally, it's crucial to ensure that multiprocess training works correctly, even if single-process training is successful. A unified debugging interface would streamline the debugging process and improve productivity.

**Comment by BenjaminBossan** [comment]
pdb does not work with multiprocessing and it probably requires some low level Python coding to make it work. IMO, this is outside of scope for accelerate. You'll probably find more success with extensive logging and old fashioned print debugging.
