### ISSUE TITLE
ValueError: Attempting to unscale FP16 gradients.

### ISSUE THREAD

**Issue by NimbusLongfei** [huggingface/accelerate#2819]
### System Info

```Shell
Name: accelerate
Version: 0.30.1
Summary: Accelerate
Home-page: https://github.com/huggingface/accelerate
Author: The HuggingFace team
Author-email: zach.mueller@huggingface.co
License: Apache
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

When I was debugging in VSCode, the following error appeared, but strangely, this error did not occur when using` accelerate launch`.
``ValueError: Attempting to unscale FP16 gradients.``
Note that the Settings and parameters for debugging and running are exactly the same

### Expected behavior

I would like to know why this error occurs.

**Comment by SunMarc** [comment]
Hi @NimbusLongfei, thanks for reporting ! Could you share a minimal reproducer ?

**Comment by Abhrant** [comment]
Hi @NimbusLongfei , is it possible that you are using BnB 4 bit quantization with FP16=True? //is thats the case, that gives this error.
