### ISSUE TITLE
v0.6.0 refactoring issue with 'use_fp16'

### ISSUE THREAD

**Issue by Nomiizz** [huggingface/accelerate#286]
On line 481 of accelerator.py, `self.state.use_fp16` is being used whereas `use_fp16` has been renamed to `mixed_precision`. This is causing the code to break. This check should probably be replaced with a call to the property method at line 234.

**Comment by sgugger** [comment]
Very good point, will fix and issue a patch!

**Comment by sgugger** [comment]
Should be fixed by [this commit](https://github.com/huggingface/accelerate/commit/211e6555fac3a35d17a7c1fbc5fc559e60044e7c).
