### ISSUE TITLE
Incorrect Argument Default for DeepSpeed Multi-node Training

### ISSUE THREAD

**Issue by jomayeri** [huggingface/accelerate#2869]
### System Info

```Shell
pip install accelerate.
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

Run accelerate for multi-node training.

### Expected behavior

Accelerate is setting the default DeepSpeed hostfile to [None](https://github.com/huggingface/accelerate/blob/1f7a79b428749f45187ec69485f2c966fe21926e/src/accelerate/commands/launch.py#L477) this overrides the DeepSpeed default of `/job/hostfile`. Overriding this default is causing issues with users attempting multi-node trading. Please change the default to match DeepSpeed's default.

**Comment by SunMarc** [comment]
Hi @jomayeri, thanks for reporting ! Make sense to switch to the DeepSpeed's default. Would you like to open the PR ? Otherwise, I can do it ! cc @muellerzr
