### ISSUE TITLE
Stuck forever in accelerator.backward without any logs

### ISSUE THREAD

**Issue by ashutoshsaboo** [huggingface/accelerate#287]
Hi there, 

I've a fairly standard training loop, see below. I've added a bunch of logs in between, just to see where is it stuck. To my surprise, the last log that I see is the log4 one below - just before `accelerator.backward`. Am I doing something wrong here? Or why is it stuck if you could please help? @sgugger 

As I inspect on nvidia-smi, the processes on the GPUs haven't been killed and have still memory occupied. I'm running this on multi-GPUs on the Sagemaker notebook (which is similar to a EC2) - i.e, not on the Sagemaker training job (which requires different configurations altogether in `accelerate config` - i.e, I haven't selected the AWS (Amazon SageMaker) sagemaker option while setting this up). I'm on accelerate==0.6.1 version. 

The training loop is fairly similar to the one here: https://github.com/huggingface/transformers/blob/master/examples/pytorch/text-classification/run_glue_no_trainer.py . 

```
        train_model.train()
        total_train_loss=0
        total_epoch_steps=0
        total_samples=0
        probs=[]
        refs=[]
        for step, batch in enumerate(dataloader):
            outputs = train_model(**batch)
            loss = outputs.loss
            loss = loss / args.gradient_accumulation_steps            
            probabilities = outputs.logits
            train_loss = accelerator.gather(loss).sum().item()
            print(train_loss, probabilities, "log1")
            predictions = accelerator.gather(probabilities.argmax(dim=-1)).detach().cpu()
            references = accelerator.gather(batch["labels"]).detach().cpu()
            print(predictions, references, "log2")
            batch_samples=len(accelerator.gather(batch['input_ids']))
            print(batch_samples, "log3")
            total_samples+=batch_samples
            total_train_loss+=(train_loss*batch_samples)
            print(total_train_loss, "log4")
            accelerator.backward(loss)
            print("backward done")
            if step % args.gradient_accumulation_steps == 0 or step == len(train_dataloader) - 1:
                print(step)
                print("optimizer step")
                optimizer.step()
                lr_scheduler.step()
                optimizer.zero_grad()
                progress_bar.update(1)
                completed_steps+=1
                total_epoch_steps+=1
            
            print("after loop")
            probs.extend(probabilities.softmax(dim=-1).detach().cpu().tolist())
            refs.extend(references.tolist())
            print(train_loss, step, epoch, refs)
            print(accelerator.is_main_process)
            metric.add_batch(
                predictions=predictions,
                references=references,
            )                
            print("done with metric add_batch")
            if completed_steps >= args.max_train_steps:
                break
                
        sorted_labels = [id2label[key] for key in sorted(id2label)]
        metrics = metric.compute(target_names=sorted_labels)
        print(metrics)
        print(accelerator.is_main_process)
```

**Comment by ashutoshsaboo** [comment]
I debugged on this more, looks like calling gather on batch always results in issues. 
For example in the above I'm doing: `batch_samples=len(accelerator.gather(batch['input_ids']))`. There's no error on the terminal as well, and processes just get stuck without any logs. 
So I was trying to get the total batch_size across batches spread on various GPUs here, reason is pytorch by default I think gives avg loss, and I need this to ultimately get avg loss per training sample. But anyways I got around this with a workaround for now, by just doing `len(batch['input_ids'])*4` (since I have 4 processes/GPUs running). 

Another use-case for which I haven't been able to find a workaround is: to get decoded input to log them to an experiment tracker for analysis later on. 2 ways to do this either: 
a) Call gather on `batch["input_ids"]` and then call tokenizer.batch_decode on the gathered inputs. This works perfectly fine on 1 GPU, but fails on multi gpu case. Not fully sure - Is it intentional to not allow gathering over batch["input_ids"] (these input_ids are set by the tokenizer, I'm using standard BERT etc models from HF's transformers lib)? 
b) Call tokenizer.batch_decode on current batch across GPUs, and then eventually gather on those decoded_texts. This doesn't work unfortunately because tokenizer.batch_decode returns a list rather than some tensor ([docs](https://huggingface.co/docs/transformers/internal/tokenization_utils#transformers.PreTrainedTokenizerBase.batch_decode)). And accelerator.gather doesn't seem to work on lists looks like. 
```
decoded_text = tokenizer.batch_decode(batch) #len(decoded_text) is correctly set in logs 
aggregated_decoded_text = accelerator.gather(decoded_text) #len(aggregated_decoded_text) is always 0 in logs presumably because accelerator.gather might not be working on lists as expected
``` 

I'm not sure why it's not allowed to call accelerate.gather on input batch from dataloader or if I'm doing anything wrong here. 

Can you please suggest is there any workaround here? Or how to suffice for this use-case? @sgugger

**Comment by sgugger** [comment]
Are you sure your input IDs have all the same shapes? If not, you need to pad them first as you can't gather tensors that are not of the same shape (this would result in the training hanging with no logs, so seems familiar ;-) ), with `accelerate.pad_across_processes`.

**Comment by ashutoshsaboo** [comment]
Thanks, yes that seemed to work. 

I know you mentioned here: https://github.com/huggingface/accelerate/issues/226#issuecomment-1009245459 that Accelerate pads it to nearest batch length*num_processes multiple. But in the compute_metrics function wouldn't that result in side-effects? I logged the length of predictions and references in the metrics class, and I don't see the exact total original dataset size, but the padded one to nearest batch_size multiple. I tried to peak into starting few and ending few elements as well, none of these seem to be gibberish padded values - so I've no idea where exactly these values are getting padded. I'm wondering if the eval metrics wouldn't get distorted because of this. What exactly does Accelerate pad dataloaders with to match this batch size multiple? Are they valid examples (which can be possible only by oversampling?) or some gibberish static tokens that the metrics explicitly need to ignore for while calculating scores? @sgugger 

In the precision metric impl - [link](https://github.com/huggingface/datasets/blob/master/metrics/precision/precision.py) - I couldn't see any such special handling in place. So, not fully sure how this is getting handled.

**Comment by sgugger** [comment]
I'm not sure I understand your question. To be able to build tensors with vectors of different lengths, you need padding. The fact that you are in distributed mode doesn't change that, you just need to pad the tensors on each process on top of padding to build them in the first place. The method lets you choose the padding value, which should be the same you used to pad your vectors inside batches.

And then of course your metric should take this into account, but again, nothing new here from the distributed side. It should already have been the case :-)

**Comment by ashutoshsaboo** [comment]
No I'm not talking about padding, I was mentioning about dataset level padding that accelerate does. So if my batch_size is 16 (4 GPUs, so effective batch size is 64), and my dataset has 630 samples then Accelerate will add samples and make it to 640 right so the batch size is consistent right? What are these samples that Accelerate adds to ensure the higher batch size can be met? Is it oversampling or where do the extra 10 samples come from? 

Because in compute_metric, if I get 640 samples, in place of 630 then the number can be possibly incorrect right? So I was wondering if a) the 10 added samples are valid examples b) In either case if they are valid/invalid examples, do you think if any extra care should be taken in compute_metric to ensure these added samples are explicitly ignored? @sgugger

**Comment by sgugger** [comment]
As sorry, I misunderstood the comment. If you want your evaluation metric strictly computed on the dataset you should:
- accumulate all your predictions/labels
- truncate them the length of your evaluation dataset
- then send that to `metric.compute`

Otherwise you get those 10 examples (from 631 to 640 in your example) in duplicate (they are the 10 first examples).

**Comment by ashutoshsaboo** [comment]
I'm gathering all predictions/labels in each epoch and using add_batch to let metrics cache the predictions/labels (rather than gather across epochs and maintaining aggregated state myself), any idea in that case how could I achieve it? 

In the compute_metric should I strip over there to my dataset length and ignore the last 10 examples (like in the example above) as you suggested? Or any alternatives? 

I'm not fully sure if the strong ordering is preserved when metrics caches after various add_batch calls and if that can be fully relied upon to do stripping (i tried seeing the source for `add_batch` and `compute` but there seem to be multiple caching strategies implemented etc so I'm not fully sure about the same)? Any suggestions? @sgugger

**Comment by ashutoshsaboo** [comment]
I must say - I'm actually also slightly perplexed at this stage, in all the official examples and HF metric implementations - nothing of such special handling seems to be in place - wouldn't that result in slightly (you could say well even though only slightly but still that could matter?) deviated metrics? @sgugger

**Comment by ashutoshsaboo** [comment]
Thanks a lot, this is helpful. :) In case if I'm shuffling my dataloader right towards the start before I get into my first epoch, in that case what's the scenario like:
a. Is it still true that the last 10 examples will be the added examples, and will they be added _after_ the shuffling of the original dataset is done?
b. Or is the case like - the 10 extra examples will be added, and the dataloader will then be shuffled, so the 10 added examples could go anywhere after shuffling and there's no guarantee that last 10 elements will be the extra examples? 

Could you please help with the same @sgugger ? If it's the case as described in (b) above - then how will one go about evaluating metric strictly on the original dataset only (and not the added 10 examples)?

**Comment by sgugger** [comment]
No, the situation is (a), so the samples added are the first ones seen, even with a shuffle. What accelerate does behind the scenes is just extending the permutation of the dataset taken. So tripping the last n examples will always work.

**Comment by XueruiSu** [comment]
I meet the similar error about the stuck forever in accelerator.backward without any logs. Here is my backward code:


    def tsrl_step(
            self, 
            prompts_list: list[torch.Tensor], 
            input_ids_list: list[torch.Tensor],
            attention_mask_list: list[torch.Tensor],
            prediction: tuple = None,
            init_value_list: list[float] = None,
            max_n_sample: int = 8,
            cur_max_new_tokens: int = 32,
        ) -> dict[str, Any]:
            print( [prompt.shape for prompt in prompts_list], [prompt.shape for prompt in input_ids_list], [prompt.shape for prompt in attention_mask_list], )
            print(prediction, init_value_list, max_n_sample, cur_max_new_tokens)
            losses, better_sample_rewards, worse_sample_rewards, max_lengths = [], [], [], []
            n_sample = len(input_ids_list)
            start = prompts_list[0].size(-1) - 1
            better_idx = -1
            worse_idx = 0 if self.args.choose_worst else -2
            
            all_better_input_ids, all_worse_input_ids = [], []
            all_better_attention_mask, all_worse_attention_mask = [], []
            all_init_value_list = []
            for sample_id in range(n_sample):
                if len(all_better_input_ids) >= max_n_sample: break
                
                input_ids = input_ids_list[sample_id]
                attention_mask = attention_mask_list[sample_id]
                
                n_output = input_ids.size(0)
                if n_output < 2: continue
                
                if self.args.choose_random:
                    worse_idx = random.choice(range(n_output - 1))
                    
                all_better_input_ids.append(input_ids[better_idx])
                all_worse_input_ids.append(input_ids[worse_idx])
                all_better_attention_mask.append(attention_mask[better_idx])
                all_worse_attention_mask.append(attention_mask[worse_idx])
                all_init_value_list.extend([init_value_list[sample_id][better_idx], init_value_list[sample_id][worse_idx]])
            all_input_ids = pad_tensors(all_better_input_ids + all_worse_input_ids, pad_value=self.tokenizer.pad_token_id) # torch.Size([2, 209])
            all_attention_mask = pad_tensors(all_better_attention_mask + all_worse_attention_mask, pad_value=False) # torch.Size([2, 209])
            print(all_input_ids.shape, all_attention_mask.shape)
            print(self.actor_model, self.actor_reference_model, self.actor_model.device, self.actor_reference_model.device)
            torch.cuda.empty_cache()
            all_sequence_log_probs = self.compute_log_probs(
                self.actor_model,
                input_ids=all_input_ids,
                attention_mask=all_attention_mask,
            ) #  torch.Size([2, 208])
            all_better_input_ids, all_worse_input_ids = all_input_ids.chunk(chunks=2, dim=0)
            all_better_attention_mask, all_worse_attention_mask = all_attention_mask.chunk(chunks=2, dim=0)
            all_better_sequence_log_probs, all_worse_sequence_log_probs = all_sequence_log_probs.chunk(chunks=2, dim=0) # torch.Size([1, 208]) torch.Size([1, 208])
            print(all_better_input_ids.shape, all_worse_input_ids.shape)
            print(all_better_attention_mask.shape, all_worse_attention_mask.shape)
            print(all_better_sequence_log_probs.shape, all_worse_sequence_log_probs.shape)
            
            label_smoothing_values = []
            for sample_id in range(len(all_better_input_ids)):
                better_input_ids = all_better_input_ids[sample_id] # torch.Size([209])
                better_attention_mask = all_better_attention_mask[sample_id] # torch.Size([209])
                
                worse_input_ids = all_worse_input_ids[sample_id] # torch.Size([209])
                worse_attention_mask = all_worse_attention_mask[sample_id] # torch.Size([209])
                
                init_values = [all_init_value_list[sample_id * 2], all_init_value_list[sample_id * 2 + 1]]
                better_sequence_log_probs, worse_sequence_log_probs = all_better_sequence_log_probs[sample_id], all_worse_sequence_log_probs[sample_id]
                
                print(better_sequence_log_probs.shape, worse_sequence_log_probs.shape)
                with torch.no_grad():
                    torch.cuda.empty_cache()
                    ref_better_sequence_log_probs = self.compute_log_probs(
                        self.actor_reference_model,
                        input_ids=better_input_ids.unsqueeze(0),
                        attention_mask=better_attention_mask.unsqueeze(0),
                    )[0] # torch.Size([208])
                    torch.cuda.empty_cache()
                    ref_worse_sequence_log_probs = self.compute_log_probs(
                        self.actor_reference_model,
                        input_ids=worse_input_ids.unsqueeze(0),
                        attention_mask=worse_attention_mask.unsqueeze(0),
                    )[0] # torch.Size([208])
                print(ref_better_sequence_log_probs.shape, ref_worse_sequence_log_probs.shape)
                
                better_end_index = better_attention_mask.nonzero()[-1]
                worse_end_index = worse_attention_mask.nonzero()[-1]
                try:
                    diverge_index = (better_input_ids != worse_input_ids).nonzero()[0]
                    assert 0 <= diverge_index <= better_end_index, 'diverge index is out of range!'
                    assert 0 <= diverge_index <= worse_end_index, 'diverge index is out of range!'
                except:
                    continue
                
                better_seq_slice = slice(diverge_index - 1, better_end_index)
                worse_seq_slice = slice(diverge_index - 1, worse_end_index)
                
                better_log_probs = better_sequence_log_probs[better_seq_slice].sum(dim=-1)
                worse_log_probs = worse_sequence_log_probs[worse_seq_slice].sum(dim=-1)
                ref_better_log_probs = ref_better_sequence_log_probs[better_seq_slice].sum(dim=-1)
                ref_worse_log_probs = ref_worse_sequence_log_probs[worse_seq_slice].sum(dim=-1)
                better_log_ratio = better_log_probs - ref_better_log_probs
                worse_log_ratio = worse_log_probs - ref_worse_log_probs
                if self.args.norm_prob or self.args.ipo:
                    better_log_ratio /= better_attention_mask[better_seq_slice].sum(dim=-1) ** self.args.length_penalty
                    worse_log_ratio /= worse_attention_mask[worse_seq_slice].sum(dim=-1) ** self.args.length_penalty
                logits = better_log_ratio - worse_log_ratio
                
                if self.args.ipo:
                    losses.append((logits - 1 / (2 * self.scale_coeff)) ** 2)
                elif self.args.conservative:
                    qb, qw = init_values
                    confidence = calculate_preference_confidence(qb, qw)
                    label_smoothing = min(1 - confidence, 0.5)
                    losses.append(
                        - F.logsigmoid(self.scale_coeff * logits) * (1 - label_smoothing)
                        - F.logsigmoid(-self.scale_coeff * logits) * label_smoothing
                    )
                    label_smoothing_values.append(label_smoothing)
                else:
                    losses.append(-F.logsigmoid(self.scale_coeff * logits))
                better_sample_rewards.append(self.scale_coeff * better_log_ratio.detach())
                worse_sample_rewards.append(self.scale_coeff * worse_log_ratio.detach())
                
                max_lengths.append(better_attention_mask[start:].float().sum())
                max_lengths.append(worse_attention_mask[start:].float().sum())
            
            if not len(losses): return {}
            
            loss = torch.stack(losses).mean()
            max_generated_length = torch.stack(max_lengths).max()
            total_max_generated_length = max_generated_length + start
            better_sample_rewards = torch.stack(better_sample_rewards)  # size = (B,)
            worse_sample_rewards = torch.stack(worse_sample_rewards)  # size = (B,)
            rewards_accuracy = (
                (better_sample_rewards > worse_sample_rewards).float().mean()
            )  # size = ()
            better_sample_rewards = better_sample_rewards.mean()  # size = ()
            worse_sample_rewards = worse_sample_rewards.mean()  # size = ()
            rewards = better_sample_rewards + worse_sample_rewards  # size = ()
            rewards_margin = better_sample_rewards - worse_sample_rewards  # size = ()
            
            torch.cuda.empty_cache()
            # loss = all_sequence_log_probs.mean()
            self.optimizer.zero_grad()
            print("losslosslosslosslosslosslosslosslosslosslossloss-------", loss)
            # self.accelerator.wait_for_everyone()
            print(self.accelerator)
            self.accelerator.backward(loss)
            print("self.accelerator.backward(loss) done")
            print("loss backward-------")
            self.optimizer.step()
            self.lr_scheduler.step()
            print("loss step-------")
            
            loss = get_all_reduce_mean(loss)
            rewards = get_all_reduce_mean(rewards)
            better_sample_rewards = get_all_reduce_mean(better_sample_rewards)
            worse_sample_rewards = get_all_reduce_mean(worse_sample_rewards)
            rewards_accuracy = get_all_reduce_mean(rewards_accuracy)
            rewards_margin = get_all_reduce_mean(rewards_margin)
            max_generated_length = get_all_reduce_max(max_generated_length)
            total_max_generated_length = get_all_reduce_max(total_max_generated_length)
            
            return {
                'train/loss': loss.item(),
                'train/rewards': rewards.item(),
                'train/better_sample_rewards': better_sample_rewards.item(),
                'train/worse_sample_rewards': worse_sample_rewards.item(),
                'train/rewards_accuracy': rewards_accuracy.item(),
                'train/rewards_margin': rewards_margin.item(),
                'train/lr': self.actor_model.optimizer.param_groups[0]['lr'],
                'train/r_scores': float(prediction[0]),
                'train/correct': float(prediction[1]),
                'train/n_sample': n_sample,
                'train/max_generated_length': max_generated_length.item(),
                'train/total_max_generated_length': total_max_generated_length.item(),
                'train/label_smoothing': sum(label_smoothing_values) / len(label_smoothing_values) if len(label_smoothing_values) else 0,
                'train/cur_max_new_tokens': cur_max_new_tokens,
            }


I tried in 1 GPU with same code, it worked but stuck when using 4 GPUs. Below is the output when using 1 GPU:

```
losslosslosslosslosslosslosslosslosslosslossloss------- tensor(0.6932, device='cuda:0', grad_fn=<MeanBackward0>)
  Invalidate trace cache @ step 422 and module 0: cache has only 422 modules
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO Using non-device net plugin version 0
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO Using network Socket
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO bootstrapSplit: comm 0x76bf9803f340 parent 0xfe0a210 rank 0 nranks 1 color -1091263299 key 0 prev 0 next 0 - DONE
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO ncclCommSplit comm 0x76bf9803f340 rank 0 nranks 1 cudaDev 0 nvmlDev 0 busId 100000 parent 0xfe0a210 color -1091263299 key 0 commId 0x55efba2da9b35614 - Init START
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO Setting affinity for GPU 0 to ffffff
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO comm 0x76bf9803f340 rank 0 nRanks 1 nNodes 1 localRanks 1 localRank 0 MNNVL 0
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO Channel 00/32 :    0
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO Channel 01/32 :    0
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO Channel 02/32 :    0
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO Channel 03/32 :    0
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO Channel 04/32 :    0
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO Channel 05/32 :    0
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO Channel 06/32 :    0
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO Channel 07/32 :    0
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO Channel 08/32 :    0
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO Channel 09/32 :    0
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO Channel 10/32 :    0
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO Channel 11/32 :    0
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO Channel 12/32 :    0
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO Channel 13/32 :    0
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO Channel 14/32 :    0
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO Channel 15/32 :    0
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO Channel 16/32 :    0
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO Channel 17/32 :    0
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO Channel 18/32 :    0
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO Channel 19/32 :    0
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO Channel 20/32 :    0
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO Channel 21/32 :    0
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO Channel 22/32 :    0
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO Channel 23/32 :    0
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO Channel 24/32 :    0
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO Channel 25/32 :    0
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO Channel 26/32 :    0
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO Channel 27/32 :    0
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO Channel 28/32 :    0
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO Channel 29/32 :    0
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO Channel 30/32 :    0
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO Channel 31/32 :    0
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO Trees [0] -1/-1/-1->0->-1 [1] -1/-1/-1->0->-1 [2] -1/-1/-1->0->-1 [3] -1/-1/-1->0->-1 [4] -1/-1/-1->0->-1 [5] -1/-1/-1->0->-1 [6] -1/-1/-1->0->-1 [7] -1/-1/-1->0->-1 [8] -1/-1/-1->0->-1 [9] -1/-1/-1->0->-1 [10] -1/-1/-1->0->-1 [11] -1/-1/-1->0->-1 [12] -1/-1/-1->0->-1 [13] -1/-1/-1->0->-1 [14] -1/-1/-1->0->-1 [15] -1/-1/-1->0->-1 [16] -1/-1/-1->0->-1 [17] -1/-1/-1->0->-1 [18] -1/-1/-1->0->-1 [19] -1/-1/-1->0->-1 [20] -1/-1/-1->0->-1 [21] -1/-1/-1->0->-1 [22] -1/-1/-1->0->-1 [23] -1/-1/-1->0->-1 [24] -1/-1/-1->0->-1 [25] -1/-1/-1->0->-1 [26] -1/-1/-1->0->-1 [27] -1/-1/-1->0->-1 [28] -1/-1/-1->0->-1 [29] -1/-1/-1->0->-1 [30] -1/-1/-1->0->-1 [31] -1/-1/-1->0->-1
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO P2P Chunksize set to 131072
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO Connected all rings
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO Connected all trees
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO 32 coll channels, 32 collnet channels, 0 nvls channels, 32 p2p channels, 32 p2p channels per peer
  GCRAZGDL1146:4143282:4162655 [0] NCCL INFO ncclCommSplit comm 0x76bf9803f340 rank 0 nranks 1 cudaDev 0 nvmlDev 0 busId 100000 parent 0xfe0a210 color -1091263299 key 0 commId 0x55efba2da9b35614 - Init COMPLETE
  loss backward------- tensor(0.6932, device='cuda:0', grad_fn=<MeanBackward0>)
  loss step------- tensor(0.6932, device='cuda:0', grad_fn=<MeanBackward0>)
```

And below is the output when using 4 GPUs:
```
losslosslosslosslosslosslosslosslosslosslossloss------- tensor(0.6935, device='cuda:0', grad_fn=<MeanBackward0>)
<accelerate.accelerator.Accelerator object at 0x7f2b085b42e0>
rl4svm2:96486:98083 [0] NCCL INFO AllReduce: opCount 246 sendbuff 0x7f1f84000000 recvbuff 0x7f1f84000000 count 525336576 datatype 9 op 0 root 0 comm 0x11753a70 [nranks=4] stream 0xc8fe8a0
rl4svm2:96486:98083 [0] NCCL INFO 1050673152 Bytes -> Algo 1 proto 2 time 105109.914062
```

Before the line of "print("losslosslosslosslosslosslosslosslosslosslossloss-------", loss)". The code will print the output It should print no matter I use 1 GPU or 4 GPUs. 

Where should I start debugging? I am currently using the deepspeed setting based on accelerate:
```
compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  gradient_accumulation_steps: 4
  zero_stage: 2
distributed_type: DEEPSPEED
enable_cpu_affinity: true
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 4
rdzv_backend: static
same_network: true
use_cpu: false
```
