### ISSUE TITLE
How to use tensorboard or tensorboardX when using accelerate for distributed training?

### ISSUE THREAD

**Issue by catqaq** [huggingface/accelerate#288]
Thanks for your great tool!
I followed your demo code to tune my training script to use accelerate for distributed training. But I got a problem that tensorboardX will crash due to conflict between log directories in different processes when I use tensorboardX and accelerate. It seems that tensorboard does not support distributed [logs.](https://github.com/tensorflow/tensorboard Does TensorBoard support multiple or distributed summary writers? NO). Then i found tensorboardX.GlobalSummaryWriter, but it still did not work. Additionally, tensorboardX sometimes crashes and sometimes works. I guess it may be because the directories created by each process according to time are sometimes the same and sometimes different.
Here is the error info:
Traceback (most recent call last):
  File "/root/miniconda3/envs/se/lib/python3.6/site-packages/tensorboardX/record_writer.py", line 47, in directory_check
Traceback (most recent call last):
  File "/root/miniconda3/envs/se/lib/python3.6/site-packages/tensorboardX/record_writer.py", line 47, in directory_check
Traceback (most recent call last):
Traceback (most recent call last):
  File "/root/miniconda3/envs/se/lib/python3.6/site-packages/tensorboardX/record_writer.py", line 47, in directory_check
  File "/root/miniconda3/envs/se/lib/python3.6/site-packages/tensorboardX/record_writer.py", line 47, in directory_check
    factory = REGISTERED_FACTORIES[prefix]
KeyError: './logs/bert-lr5e-05-cls-20220322-024953'
......
KeyError: './logs/bert-lr5e-05-cls-20220322-024953'

**Comment by sgugger** [comment]
We'll add something to make it easier to log to TensorBoard in the coming weeks, but in the meantime, you should only call your code that logs something in a
```
if accelerator.is_main_process
```
block.

**Comment by catqaq** [comment]
@sgugger Thanks for your advice. Yay, i used tensorboardX to record my training log successfully this afternoon by wrapping my writer in the "if accelerator.is_main_process". It works fine, but not very convenient. Looking forward to your official support for tensorboard.

**Comment by muellerzr** [comment]
You can keep track of the progress for this here 😄 

https://github.com/huggingface/accelerate/issues/291

**Comment by muellerzr** [comment]
Closed with https://github.com/huggingface/accelerate/issues/291, there's now an official API you can use. Read more about it here: 

https://huggingface.co/docs/accelerate/main/en/tracking

**Comment by catqaq** [comment]
@muellerzr Great job!
