### ISSUE TITLE
typo in examples/slurm/submit_multinode.sh script

### ISSUE THREAD

**Issue by hubutui** [huggingface/accelerate#2881]
### System Info

```Shell
None
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

https://github.com/huggingface/accelerate/blob/1f7a79b428749f45187ec69485f2c966fe21926e/examples/slurm/submit_multinode.sh#L40

### Expected behavior

https://github.com/huggingface/accelerate/blob/1f7a79b428749f45187ec69485f2c966fe21926e/examples/slurm/submit_multinode.sh#L40
should be:
```bash
export CMD="$LAUNCHER $SCRIPT $SCRIPT_ARGS"
```

**Comment by BenjaminBossan** [comment]
Indeed, thanks for reporting. Do you want to create a PR to fix this?

**Comment by hubutui** [comment]
thanks, and no.
