### ISSUE TITLE
Can't apply LoRA's PiSSA weight init when using DeepSpeed ZeRO3 + LoRA to finetune!

### ISSUE THREAD

**Issue by ANYMS-A** [huggingface/accelerate#2886]
### System Info

```Shell
accelerate：0.25.0
OS：Ubuntu 20.04
python version: 3.11
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

1. Using the official example of LoRA + ZeRO3: https://github.com/huggingface/peft/blob/main/examples/sft/run_peft_deepspeed.sh
2. Add `init_lora_weights ="pissa"` when init the LoRA config in No.150 line of the utils.py of the exampe scirpt: https://github.com/huggingface/peft/blob/d716adf31cc16d93c402b88e0c4e3892841741cb/examples/sft/utils.py#L150
3. Run the training script!
4. Get error:
```bash
    main(model_args, data_args, training_args)
  File "/data/deployment/workspace/h30058272/LLM_Dataset_Constructor/scripts/train/lora_ZeRO3/train_lora_ZeRO3.py", line 96, in main
    trainer = SFTTrainer(
              ^^^^^^^^^^^
  File "/root/program/miniconda3/envs/py311/lib/python3.11/site-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/root/program/miniconda3/envs/py311/lib/python3.11/site-packages/trl/trainer/sft_trainer.py", line 254, in __init__
    model = get_peft_model(model, peft_config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/program/miniconda3/envs/py311/lib/python3.11/site-packages/peft/mapping.py", line 149, in get_peft_model
    return MODEL_TYPE_TO_PEFT_MODEL_MAPPING[peft_config.task_type](model, peft_config, adapter_name=adapter_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/program/miniconda3/envs/py311/lib/python3.11/site-packages/peft/peft_model.py", line 1395, in __init__
    super().__init__(model, peft_config, adapter_name)
  File "/root/program/miniconda3/envs/py311/lib/python3.11/site-packages/peft/peft_model.py", line 138, in __init__
    self.base_model = cls(model, {adapter_name: peft_config}, adapter_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/program/miniconda3/envs/py311/lib/python3.11/site-packages/peft/tuners/lora/model.py", line 139, in __init__
    super().__init__(model, config, adapter_name)
  File "/root/program/miniconda3/envs/py311/lib/python3.11/site-packages/peft/tuners/tuners_utils.py", line 166, in __init__
    self.inject_adapter(self.model, adapter_name)
  File "/root/program/miniconda3/envs/py311/lib/python3.11/site-packages/peft/tuners/tuners_utils.py", line 372, in inject_adapter
    self._create_and_replace(peft_config, adapter_name, target, target_name, parent, current_key=key)
  File "/root/program/miniconda3/envs/py311/lib/python3.11/site-packages/peft/tuners/lora/model.py", line 223, in _create_and_replace
    new_module = self._create_new_module(lora_config, adapter_name, target, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/program/miniconda3/envs/py311/lib/python3.11/site-packages/peft/tuners/lora/model.py", line 314, in _create_new_module
    new_module = dispatcher(target, adapter_name, lora_config=lora_config, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/program/miniconda3/envs/py311/lib/python3.11/site-packages/peft/tuners/lora/layer.py", line 1116, in dispatch_default
    new_module = Linear(target, adapter_name, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/program/miniconda3/envs/py311/lib/python3.11/site-packages/peft/tuners/lora/layer.py", line 410, in __init__
    self.update_layer(
  File "/root/program/miniconda3/envs/py311/lib/python3.11/site-packages/peft/tuners/lora/layer.py", line 117, in update_layer
    self.pissa_init(adapter_name, init_lora_weights)
  File "/root/program/miniconda3/envs/py311/lib/python3.11/site-packages/peft/tuners/lora/layer.py", line 173, in pissa_init
    V, S, Uh = torch.linalg.svd(weight.data, full_matrices=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: linalg.svd: The input tensor A must have at least 2 dimensions.
```

5. I checked the parameters of the model, their shape all become 0! I doubt this is because of the ZeRO3 weight partition init session.  But I dont know how to solve it,.

### Expected behavior

I wish the weight init process of the LoRA layers can be executed successfully!

I highly doubt the reason of this problem is because of this:  https://github.com/huggingface/peft/issues/297#issuecomment-1639989289

Hope to find a decent solution for this issue! Thanks！

**Comment by BenjaminBossan** [comment]
Might be related to [this comment](https://github.com/huggingface/peft/issues/896#issuecomment-2172455458).

I have a suspicion what the issue might be, it would be great if you could test it. For this line:

https://github.com/huggingface/peft/blob/d716adf31cc16d93c402b88e0c4e3892841741cb/src/peft/tuners/lora/layer.py#L118

could you put it inside of the `gather_params_ctx` context (it can be imported from `peft.utils.integrations`)?

So it should look like this:

```python
            with gather_params_ctx(self.get_base_layer().weight):
                self.pissa_init(adapter_name, init_lora_weights)
```

**Comment by ANYMS-A** [comment]
> Might be related to [this comment](https://github.com/huggingface/peft/issues/896#issuecomment-2172455458).
> 
> I have a suspicion what the issue might be, it would be great if you could test it. For this line:
> 
> https://github.com/huggingface/peft/blob/d716adf31cc16d93c402b88e0c4e3892841741cb/src/peft/tuners/lora/layer.py#L118
> 
> could you put it inside of the `gather_params_ctx` context (it can be imported from `peft.utils.integrations`)?
> 
> So it should look like this:
> 
> ```python
>             with gather_params_ctx(self.get_base_layer().weight):
>                 self.pissa_init(adapter_name, init_lora_weights)
> ```

Nice! I tested it, it works! Then I think maybe during the weight init stage, we should check if is deepspeed_zero3_enabled, then chose to init the wegiths within the gather_params_ctx

**Comment by ANYMS-A** [comment]
BTW, I have a further question about the ZeRO3's parameter partition. Currently I understand that the pretrained model's(not peft model) weights will be partitioned is ZeRO3 is enabled. But when initialize the peft model(e.g. LoRA model), will the LoRA layers be partitioned as well? And how can I verify that all the parameters are partitioned by DeepSpeed

**Comment by BenjaminBossan** [comment]
> Nice! I tested it, it works! Then I think maybe during the LoRA layer's whole init stage, we should check if is deepspeed_zero3_enabled, then chose to init the wegiths within the gather_params_ctx.

Great, thanks for testing. I'm creating a PR in LoRA to fix this: https://github.com/huggingface/peft/pull/1887

> will the LoRA layers be partitioned as well? And how can I verify that all the parameters are partitioned appropriately by DeepSpeed

Sorry, I don't have a lot of experience with DeepSpeed, so I don't know by what logic parameters are partitioned.
