### ISSUE TITLE
How to set a custom Config in python code using Accelerate?

### ISSUE THREAD

**Issue by konstantinator** [huggingface/accelerate#2891]
Hello everyone!

Could you please advise how to replace the console command for setting a config
```
accelerate launch --config_file {path/to/config/my_config_file.yaml} {script_name.py} {--arg1} {--arg2}
```
with code in the Python file script_name.py?

I am expecting something like the following functionality:
```
from accelerate import Accelerator
accelerator = Accelerator()
accelerator.set_config_file('path/to/config/my_config_file.yaml')
```

I would like to run the script through Python and use all the benefits of launching with the Accelerate launch command with config file:
```
python script_name.py
```

**Comment by SunMarc** [comment]
cc @muellerzr  for when you will be back !

**Comment by konstantinator** [comment]
@muellerzr any update?

**Comment by muellerzr** [comment]
Looking into this, as I've considered this too instead of having users make an `FSDPPlugin`/`DeepSpeedPlugin`. The main problem/limitation is this has to be done first to have easier usage with `transformers` since we rely on some of the env variables being set, but yes this can/should be done

**Comment by muellerzr** [comment]
TBh though I'd rather have users create an `FullyShardedDataParallelPlugin` and `DeepSpeedPlugin`, as that's what they are made for. We generally don't want users to do `python`. If you want that, you can do `python -m accelerate.commands.launch`
