### ISSUE TITLE
With the same epoch, the result of multiple Gpus is much lower than that of a single gpu，why？

### ISSUE THREAD

**Issue by xiuguangLi** [huggingface/accelerate#2903]
Under the same epoch, multi-gpu training is less accurate than single-gpu training, but eventually both results converge to a certain value. Is this normal? Why is the result of multi-gpu so much lower at the same epoch?

**Comment by muellerzr** [comment]
Please make sure to follow the debugging guide, it mentions why: https://huggingface.co/docs/accelerate/concept_guides/performance
