### ISSUE TITLE
Add logging capability

### ISSUE THREAD

**Issue by muellerzr** [huggingface/accelerate#291]
# Feature Request: Logging Capability

## Feature Summary
- Add a method called `Accelerator.log` that takes in dictionary-like values and saves to configured logger
- `Accelerator.__init__` should get a new param of `log_with` that takes a list of strings as potential options or `"all"`
- The default should be `None` and no loggers are configured. If `"all"` is selected, find all installed loggers (similar to `Trainer`)

## Timeline
Supported integrations:
- [x] TensorBoard/X
- [x] WandB
- [x] CometML
- [ ] NeptuneAI
﻿

**Comment by ashutoshsaboo** [comment]
Is it possible to add support for custom loggers too? Like the open-source experiment tracker Aim (others above other than tboard are closed source): https://github.com/aimhubio/aim .

**Comment by muellerzr** [comment]
@ashutoshsaboo essentially this will just be a small convenience wrapper to a few back-ends. For any and all loggers you can simply have them log below the following if statement and it should run without issue:
```python
if accelerator.is_main_process:
  # Do my logging of everything here
```

**Comment by ashutoshsaboo** [comment]
That's fine, Would I still be able to use Accelerator.log? I was thinking more in the sense of having a callback interface (like Trainer implements) which Accelerate could also do, and can be extended easily? This helps various lib owners provide their own custom impls that can be used out of the box. @muellerzr

**Comment by muellerzr** [comment]
Putting Neptune.AI off the roadmap for now, given that their API is much more user-specific and needs specific key namings when logging items, rather than being generalizable.

They should follow the `if accelerator.is_main_process:` and do the logging themselves.

**Comment by congchan** [comment]
Hi, what parameters should I use to enable tensorboard and disable wandb, when using `accelerate launch --config_file`
