### ISSUE TITLE
KeyError: 'step' when resume from checkpoint

### ISSUE THREAD

**Issue by kxhit** [huggingface/accelerate#2923]
### System Info

```Shell
accelerate 0.32.0
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

My training script works fine with accelerate==0.23.0 and when using 0.32.0, and resume from checkpoint (saved by 0.32.0 version as well), I got an error 

"accelerate/accelerator.py", line 3147, in load_state
    self.step = override_attributes["step"]
KeyError: 'step'" 

### Expected behavior

I believe this [line](https://github.com/huggingface/accelerate/blob/2471eacdd648446f2f63eccb9b18a7731304f401/src/accelerate/accelerator.py#L3147) causes the error and in accelerate==0.23.0, there is no "step". 

Hope to get some suggestion in avoiding this bug or get it fixed.

I downgraded my accelerate to 0.31.0 and it works.

**Comment by alexanderswerdlow** [comment]
For anyone who has a similar issue, I also encountered this loading of the internal step to be problematic. Specifically, after adding a try/catch, I found that it succeeds on the master rank but not other ranks. In turn, this causes the ranks to become out of sync, in my case with different amounts of gradient accum in the first step. Ultimately, this can result in a hang later on.

**Comment by rahji** [comment]
I'm having the same problem. How did you downgrade accelerate to 0.31.0, @kxhit ?

**Comment by BenjaminBossan** [comment]
Thanks for reporting, as correctly stated, downgrading accelerate is the correct workaround.

This was most likely caused by #2765. IMO it would be best if checkpoints were compatible between accelerate versions, so ideally there is a fix that makes the `step` key optional to have. Let's see what @muellerzr thinks about this when he's back in office.

**Comment by priyammaz** [comment]
I just build my environment so i was running the newest 0.33.0 accelerate version. I saved a checkpoint with this version, when when trying to load it, it throws the key error for "step". I downgraded to 0.31 and its totally fine now, but just thought id mention that even within the same version of accelerate there may be a slight issue.

**Comment by rbli-john** [comment]
May I ask is there any plan to fix this issue?

**Comment by simonhessner** [comment]
PRs https://github.com/huggingface/accelerate/pull/2992 and https://github.com/huggingface/accelerate/pull/2765 seem to deal with this issue and they have already been merged. As far as I can see they haven't been released in a new version yet. 

Does anyone know when the next release will be published?

**Comment by DuominuoAiEr** [comment]
> 我刚刚搭建了环境，所以运行的是最新的 0.33.0 Acceleration 版本。我用这个版本保存了一个检查点，但尝试加载时，却报了“step”的键错误。我降级到 0.31 版本，现在一切正常。不过我想提一下，即使使用同一版本的 Acceleration，也可能存在一些小问题,。

oh , is work !
