### ISSUE TITLE
CPU RAM bottleneck when loading large models

### ISSUE THREAD

**Issue by lvwerra** [huggingface/accelerate#294]
Hi there

We noticed that when using `accelerate` to run a script on multiple GPUs that the RAM requirement increases the more workers there are. The issue seems to be that the model is loaded n-times to CPU RAM before uploaded to the GPU memory. Especially when working with larger models this can become a bottleneck.

Do you think it would be feasible to load the model only on the main process and then dispatch it to the GPU from there? Or is this too much of a niche case?

cc @liyongsea

**Comment by sgugger** [comment]
I'm not sure that's feasible automaticlly inside of Accelerate as it is, since it deals with initialized models only (via `accelerator.prepare`). So for now, I'd say it's the responsibility of the user (Accelerate will work fine once you've done one load and send across devices).

We could add a util function that does such a load. Do you have an example in mind?

**Comment by lvwerra** [comment]
Do you think something along those lines could work:

```Python
if accelerator.is_main_process():
    model = AutoModel.from_pretrained("some_model")
    distributed_models = []
    for index in range(accelerator.state.num_processes):
        device = torch.device("cuda", index)
        distributed_models.append(model.to(device))
    distributed_models = broadcast_object_list(distributed_models)
model = distributed_models[accelerate.state.local_process_index]
model = accelerator.prepare(model, device_placement=False)

# then a second `prepare` call with `device_placement=True` for all the other objects?
```

I can do a bit more testing with that next week if you think something like that would be viable.

**Comment by sgugger** [comment]
You don't need to do `model = accelerator.prepare(model, device_placement=False)`, the device placement is a noop if the model is already on the right device, so `model` can be sent to the regular `accelerator.prepare` call.

As for your specific code before, it'd need testing :-)
