### ISSUE TITLE
Unable to load sharded checkpoints containing variants

### ISSUE THREAD

**Issue by sayakpaul** [huggingface/accelerate#2946]
Currently, `accelerate` doesn't consider the "variant" when loading from a directory containing both non variant and variant checkpoints. 

I have a directory of checkpoints that contains the following sharded checkpoints:

```bash
config.json
diffusion_pytorch_model-00001-of-00002.fp16.safetensors
diffusion_pytorch_model-00001-of-00003.safetensors
diffusion_pytorch_model-00002-of-00002.fp16.safetensors
diffusion_pytorch_model-00002-of-00003.safetensors
diffusion_pytorch_model-00003-of-00003.safetensors
diffusion_pytorch_model.safetensors.fp16.index.json
diffusion_pytorch_model.safetensors.index.json
```

When I tried loading these into the underlying class `AuraFlowTransformer2DModel`, it errored out like so: 

```bash
ValueError: /raid/.cache/huggingface/models--fal--AuraFlow/snapshots/f16d500f22e8689f10581936c6a453d7c6fe646a/transformer containing more than one `.index.json` file, delete the irrelevant ones.
```

The checkpoints can be downloaded from here: https://huggingface.co/fal/AuraFlow/tree/main/transformer. 

And then then:

```python
from diffusers import AuraFlowTransformer2DModel

model = AuraFlowTransformer2DModel.from_pretrained(ckpt_path, variant="fp16")
```

You need to install `diffusers` from the source to avail `AuraFlowTransformer2DModel`. 

Cc: @muellerzr @SunMarc

**Comment by sayakpaul** [comment]
A gentle ping :)

**Comment by SunMarc** [comment]
Hey @sayakpaul, can you have a look at the PR above ? This should fix your issue !
