### ISSUE TITLE
allow `variant='fp16'` in load_checkpoint_and_dispatch

### ISSUE THREAD

**Issue by CanvaChen** [huggingface/accelerate#2961]
```python
with init_empty_weights():
    text_encoder_one = ChatGLMModel.from_pretrained(
        args.pretrained_model_name_or_path, subfolder="text_encoder", revision=args.revision, variant=args.variant,
    )
device_map = infer_auto_device_map(
    model=text_encoder_one,
    max_memory={0: "3GiB", 1: "11GiB"},
)
text_encoder_one = load_checkpoint_and_dispatch(text_encoder_one,
                                                args.pretrained_model_name_or_path + '/text_encoder',
                                                device_map=device_map)
```
> ValueError: text_encoder is not a folder containing a `.index.json` file or a pytorch_model.bin or a model.safetensors file

![image](https://github.com/user-attachments/assets/3f444721-8601-4d79-9cde-84d331ed5f93)

**Comment by SunMarc** [comment]
Hey @CanvaChen, thanks for reporting ! You can pass the index json file instead of  args.pretrained_model_name_or_path + '/text_encoder' when loading with `load_checkpoint_and_dispatch` ! LMK if this solution is good enough for you !
