### ISSUE TITLE
Support Specifying Multiple Devices for `device_map`

### ISSUE THREAD

**Issue by Co1lin** [huggingface/accelerate#2962]
### System Info

```Shell
Copy-and-paste the text below in your GitHub issue

- `Accelerate` version: 0.29.1
- Platform: Linux-5.15.0-102-generic-x86_64-with-glibc2.31
- `accelerate` bash location: /local/arise/ubuntu/miniforge3/envs/py10/bin/accelerate
- Python version: 3.10.14
- Numpy version: 1.26.4
- PyTorch version (GPU?): 2.3.1+cu121 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- PyTorch MLU available: False
- System RAM: 251.74 GB
- GPU type: NVIDIA GeForce RTX 3090
- `Accelerate` default config:
        Not found
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

I have 4 GPUs. I want to load one model to gpu 0, 1 and the other one to gpu 2, 3 in the same program. Here I tried to use `max_memory` to load the first model to only gpu 0, 1, but not on the same device error happened. This will not happen when I only use one model in a program and use environment variables to use only gpu 0, 1 with `device_map='auto'`. However in this case I need to load 2 models so I cannot use environment variables to set limitation.

```python
from transformers import AutoTokenizer, AutoModelForCausalLM, AutoConfig
from accelerate import infer_auto_device_map, init_empty_weights
import torch

model_id = "meta-llama/Meta-Llama-3-8B-Instruct"
tokenizer = AutoTokenizer.from_pretrained(model_id)

config = AutoConfig.from_pretrained(model_id)
with init_empty_weights():
    model = AutoModelForCausalLM.from_config(config)
device_map = infer_auto_device_map(model, max_memory={
    0: "24GiB", 1: "24GiB",
    2: "0GiB", 3: "0GiB",
})
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    torch_dtype=torch.bfloat16,
    device_map=device_map,
)

messages = [
    {"role": "system", "content": "You are a pirate chatbot who always responds in pirate speak!"},
    {"role": "user", "content": "Who are you?"},
]

input_ids = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt=True,
    return_tensors="pt"
).to(model.device)

terminators = [
    tokenizer.eos_token_id,
    tokenizer.convert_tokens_to_ids("<|eot_id|>")
]

outputs = model.generate(
    input_ids,
    max_new_tokens=256,
    eos_token_id=terminators,
    do_sample=True,
    temperature=0.6,
    top_p=0.9,
)
'''
...
  File "/local/arise/ubuntu/miniforge3/envs/py10/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 733, in forward
    hidden_states = residual + hidden_states
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!
'''
response = outputs[0][input_ids.shape[-1]:]
print(tokenizer.decode(response, skip_special_tokens=True))
```

### Expected behavior

When using `max_memory` to limit GPU usage, the library should handle multiple devices correctly just as using `device_map='auto'`.

Also, it will be easier if we can use `device_map='cuda:0,1'` to only use GPU 0, 1.

**Comment by muellerzr** [comment]
cc @SunMarc

**Comment by Co1lin** [comment]
Any follow up?

**Comment by SunMarc** [comment]
Hi @Co1lin, sorry for the delay. I don't think I understand your issue. I see in the script that you shared that you are only trying to load one model no ?

**Comment by Co1lin** [comment]
@SunMarc Thanks for following this! Yeah in the script I shared, I only loaded one model. But actually I want to load two models. So you can see that I'm trying to load the first model into GPU 0, 1 with `infer_auto_device_map`, so that I can load the second model into GPU 2, 3. However, the attempt to load the first model to and only to GPU 0, 1 failed.

**Comment by SunMarc** [comment]
In order to load your model on gpu 0 and 1 , you can do it in one line ! You don't need to use `init_empty_weights` and `infer_auto_device_map` as the logic is already in transformers code.
```py
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    torch_dtype=torch.bfloat16,
    device_map="auto",
    max_memory={0: "24GiB", 1: "24GiB"}
)
```

**Comment by Co1lin** [comment]
This one works fine! Thanks!
