### ISSUE TITLE
Seq2seq example

### ISSUE THREAD

**Issue by jordiae** [huggingface/accelerate#297]
Hi all and thanks for this library. Is there any Seq2seq project based on Accelerate that you know of?

**Comment by sgugger** [comment]
Hi there! Please use the [forums](https://discuss.huggingface.co/) for such questions as we keep issues for bugs and feature requests only.

The Transformers repo contains two seq2seq examples using Accelerate: one for [translation](https://github.com/huggingface/transformers/blob/main/examples/pytorch/translation/run_translation_no_trainer.py) and one for [summarization](https://github.com/huggingface/transformers/blob/main/examples/pytorch/summarization/run_summarization_no_trainer.py).

**Comment by jordiae** [comment]
Thank you!
