### ISSUE TITLE
Community ideas for v1.0.0 and beyond!

### ISSUE THREAD

**Issue by muellerzr** [huggingface/accelerate#2976]
Use this issue to voice any thoughts and opinions you may want/have/etc on accelerate 1.0.0 and beyond. Our full roadmap can be found here: https://github.com/orgs/huggingface/projects/55

**Comment by JaheimLee** [comment]
Hope to support 3D parallel training. From pytorch 2.4, it seems possible to use Dtensor and device_mesh to support fsdp2, tp, torch.distributed.pipelining at the same time. Maybe you can release a Beta/Prototype feature like pytorch.
