### ISSUE TITLE
Accelerate `estimate-memory` not working.

### ISSUE THREAD

**Issue by renekts** [huggingface/accelerate#2980]
### System Info

```Shell
- `Accelerate` version: 0.21.0
- Platform: macOS-14.5-arm64-arm-64bit
- Python version: 3.10.14
- Numpy version: 1.26.2
- PyTorch version (GPU?): 2.1.0 (False)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 16.00 GB
- `Accelerate` default config:
        Not found
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

When running the accelerate cli to estimate the memory usage of a HuggingFace model according to the documentation a invalid command choice is being returned. 

Command:
`accelerate estimate-memory bert-base-cased`

Error:
usage: accelerate <command> [<args>]
Accelerate CLI tool: error: argument {config,env,launch,tpu-config,test}: invalid choice: 'estimate-memory' (choose from 'config', 'env', 'launch', 'tpu-config', 'test')

Replication:
Execute mentioned command

Documentation Link:
https://huggingface.co/docs/accelerate/main/en/usage_guides/model_size_estimator

### Expected behavior

Return a table representation of the dtypes and memory usage as described in the documentation.

**Comment by muellerzr** [comment]
You need to upgrade your accelerate version
