### ISSUE TITLE
`find_tied_parameters` miss tied parameters

### ISSUE THREAD

**Issue by qubvel** [huggingface/accelerate#2984]
### System Info

```Shell
- `Accelerate` version: 0.33.0
- Platform: Linux-6.5.0-1020-aws-x86_64-with-glibc2.35
- `accelerate` bash location: /home/ubuntu/projects/transformers/.venv/bin/accelerate
- Python version: 3.10.12
- Numpy version: 1.26.3
- PyTorch version (GPU?): 2.4.0+cu121 (True)
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

I used a simple net with a shared layer and assumed that shared layer parameters should be returned by `find_tied_parameters`, however, an empty list is returned. Is it expected behavior or do I misunderstand what the `find_tied_parameters` purpose is?

```python
import torch
from accelerate.utils import find_tied_parameters

class DummyModel(torch.nn.Module):
    def __init__(self):
        super().__init__()
        shared_linear = torch.nn.Linear(4, 4)
        self.linear1 = shared_linear
        self.linear2 = shared_linear
        self.linear3 = shared_linear
        self.linear4 = shared_linear

model = DummyModel()
assert model.linear1.weight is model.linear2.weight
assert model.linear1.weight.data_ptr() == model.linear2.weight.data_ptr()

tied_params = find_tied_parameters(model)
print(tied_params)
# []
```

The root issue is related to the transformers repo, I found that for GroundingDino `tied_params` are different if `device_map` is provided and the `find_tied_parameters` function is used instead of `id_tensor_storage` function to find tied weights.
https://github.com/huggingface/transformers/blob/53f0c9c2906e0b0f1623bfdfb420fca1e655098d/src/transformers/modeling_utils.py#L4124-L4134

### Expected behavior

`find_tied_parameters` function returns shared parameters

cc @SunMarc

**Comment by SunMarc** [comment]
Hi @qubvel, thanks for your investigation. find_parameters is failing in this case because when initializing the model like that, we don't have the linear layers in `model.named_children`. Only the shared layers appears. This is why we are not able to find these modules + check if the tensors are tied in `find_parameters` . If you initialize the module like that, it works however: 

```python
class DummyModel(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.shared_linear = torch.nn.Linear(4, 4)
        self.linear1 = torch.nn.Linear(4, 4)
        self.linear2 = torch.nn.Linear(4, 4)
        self.linear3 = torch.nn.Linear(4, 4)
        self.linear4 = torch.nn.Linear(4, 4)
        
        self.linear1.weight = self.shared_linear.weight
        self.linear2.weight = self.shared_linear.weight
        self.linear3.weight = self.shared_linear.weight
        self.linear4.weight = self.shared_linear.weight
```

Not sure yet what's the best solution. One solution would be to find a way to have access to these children modules, like `model.named_children`. LMK if you find something !

**Comment by qubvel** [comment]
Hi @SunMarc, thanks for the reply.

For newer versions of PyTorch (2.0+) we can use `model.named_parameters(remove_duplicate=False)` and `model.named_parameters(remove_duplicate=True)` to identify tied parameters defined that way. However, for the earlier versions `remove_duplicate` is not supported argument.

**Comment by qubvel** [comment]
@SunMarc I've submitted a PR to fix it, please review it whenever you have time. I copied and modified methods from torch to iterate over modules and parameters to make it backward compatible with torch < 2.0

**Comment by SunMarc** [comment]
Thanks for fixing and submitting the PR @qubvel !
