### ISSUE TITLE
Support NumPy 2.0 and Greater.

### ISSUE THREAD

**Issue by KyleMylonakisProtopia** [huggingface/accelerate#3027]
Please excuse the blank template, but the only template publicly available for accelerate is a bug template which is not applicable here.

Currently accelerate requires numpy less than version 2.0. This has resulted in numpy being forcibly downgraded in some environments such as what is happening in https://github.com/huggingface/transformers/issues/31802. This issue was closed with Hugging Face employees recommending that a ticket for NumPy 2.0 support be opened in accelerate.

If you could support NumPy version 2.0 (or whatever the latest version of NumPy is) I and the rest of the accelerate and Hugging Face user base would be grateful.

**Comment by muellerzr** [comment]
Let me run the tests and see if anything fails. So long as nothing breaks, we're set :)

**Comment by muellerzr** [comment]
Note that there are other (commonly used) deps that require lower numpy versions, currently I'm noticing this is scikit-learn. However everything seems to run fine so I think we're okay

**Comment by Fred-Wu** [comment]
Has this been resolved? Still got issues when installing accelerate, which forces numpy to downgrade. 

<img width="698" alt="image" src="https://github.com/user-attachments/assets/9da8a222-dbac-4938-82fe-cede07547de9">

**Comment by BenjaminBossan** [comment]
The restriction on the numpy version has been lifted:

https://github.com/huggingface/accelerate/commit/52fae0960cef264d1a9b7bda6c9cbadb2361bd33#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R73

It's included in the latest release. The most likely explanation is that another dependency is responsible. Could you show the commands you used to create this enviroment?

**Comment by Fred-Wu** [comment]
Thanks. Here is my YAML header file for creating the environment. 


name: nlp-macos

channels:
  - conda-forge

dependencies:
- python=3.12.*
- pip
- notebook
- jupyterlab
- ipyparallel
- ipython
- ipywidgets
- scipy
- sympy
- plotly
- numpy
- libblas=*=*accelerate
#- transformers

- pip:
  - Faker
  - tqdm
  - polars
  - pandas
  - altair
  - nltk
  - plotnine[all]
  - seaborn[stats]
  - emoji
  - pip-review
  - pyarrow
  - jax==0.4.26
  - jaxlib==0.4.26
  - jax-metal
  - torch
  - torchvision
  - scikit-learn
  - gym
  - tensorboard

**Comment by BenjaminBossan** [comment]
Thanks for the file. Unfortunately, I keep running into issues trying to install from this file, probably because I'm not on Mac. Therefore, I cannot reproduce. When you create a minimal environment with only numpy 2.0 and the latest accelerate, do you still observe the numpy downgrade?

**Comment by Fred-Wu** [comment]
> Thanks for the file. Unfortunately, I keep running into issues trying to install from this file, probably because I'm not on Mac. Therefore, I cannot reproduce. When you create a minimal environment with only numpy 2.0 and the latest accelerate, do you still observe the numpy downgrade?

Thanks for the suggestion. Just tried the following

```
conda create -n myenv python=3.12 
conda activate myenv
conda install numpy=2.1.1
conda install accelerate 
```

It seems OK without downgrade message. However, it only tries to install `accelerate-0.31.0`, not the latest one. 
<img width="717" alt="image" src="https://github.com/user-attachments/assets/bb7b2d5c-2da5-4f6b-b4dd-78caec145df4">



Then the issue appears when installing `conda install accelerate=0.34.0`

<img width="767" alt="image" src="https://github.com/user-attachments/assets/50d632ec-c3bd-4665-88a2-72fede6995a2">

**Comment by BenjaminBossan** [comment]
> Then the issue appears when installing `conda install accelerate=0.34.0`

What about v0.34.1 or v0.34.2? Not sure if they're on the conda-forge channel, so you might have to use pip.

**Comment by Fred-Wu** [comment]
v0.34.1 is not on conda-forge.  v0.34.2 is, but with the same issue.

**Comment by muellerzr** [comment]
The conda channels aren't maintained by us, the pypi channels are though. Can you do `conda install pip; pip install accelerate`? This should work fine in the end I think
