### ISSUE TITLE
[Request] Decouple `prepare_data_loader` from Accelerator/AcceleratorState

### ISSUE THREAD

**Issue by siddk** [huggingface/accelerate#3039]
I really love using `accelerate.PartialState()` as an independent / minimal utility. Reading through the [`prepare_data_loader()`](https://github.com/huggingface/accelerate/blob/v0.33.0/src/accelerate/data_loader.py#L797) code path, it seems like (all of?) its functionality is pretty independent, and can be similarly isolated from the rest of the heavy-weight `Accelerator()` class.

Is this true? If so, would be awesome to make `PartialState` the sole dependency of the library's `dataloader` handling. Would be especially useful to tap into `dispatch_batches` and some of the random seeding logic (which are really awesome extensions over what's provided by PyTorch)!

**Comment by muellerzr** [comment]
I thought about this yesterday actually! Would you like to take a stab at a PR? It should be as straightforward as replacing the AcceleratorState with PartialState’s

**Comment by siddk** [comment]
Yes - on it right now!

**Comment by siddk** [comment]
PR is here: #3047
