### ISSUE TITLE
`preload_module_classes` is lost in attach_execution_device_hook.

### ISSUE THREAD

**Issue by wejoncy** [huggingface/accelerate#3060]
### System Info

https://github.com/huggingface/accelerate/blob/3fcc9461c4fcb7228df5e5246809ba09cfbb232e/src/accelerate/hooks.py#L439
Should we pass preload_module_classes  to the next calling? such as
```
        attach_execution_device_hook(child, execution_device, tied_params_map=tied_params_map, 
 preload_module_classes=preload_module_classes)
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

Step into the code is enough.

### Expected behavior

Identify the bug.

**Comment by wejoncy** [comment]
Hi @muellerzr 
Could you please take a look at it? Sorry if I ping the wrong contributor could you please help to contact the correct one? Thanks

**Comment by wejoncy** [comment]
Could anyone help to look at this issue？

**Comment by wejoncy** [comment]
Hi @SunMarc 

Could you please take a look at this issue when you get a time?
Thanks.

**Comment by SunMarc** [comment]
Oh my bad sorry for the delay @wejoncy, I totally missed it. We indeed need to pass it. Could you open a PR to fix it ?

**Comment by wejoncy** [comment]
Sure.
I opened a PR to resolve this.
https://github.com/huggingface/accelerate/pull/3248
