### ISSUE TITLE
bf16 accelerator is unavailable on MPS

### ISSUE THREAD

**Issue by bghira** [huggingface/accelerate#3064]
### System Info

```Shell
latest accelerate, pytorch 2.4
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

```
File ".venv/lib/python3.10/site-packages/accelerate/accelerator.py", line 488, in __init__
    raise ValueError("bf16 mixed precision requires PyTorch >= 1.10 and a supported device.")
ValueError: bf16 mixed precision requires PyTorch >= 1.10 and a supported device
```

```py
import accelerate
accelerator = accelerate.Accelerator(
    mixed_precision="bf16"
)
```

### Expected behavior

With torch >2.3 we have bf16 support.

Since AMP is disabled, we should be able to use low-precision training still. This works in SimpleTuner, but we have to tell Accelerate we are in fp32 😢

**Comment by muellerzr** [comment]
We're waiting for autocast, which is still on nightly. (There's an open issue for this). You can manually turn the model to half precision and train if you desire.

**Comment by bghira** [comment]
but i do this:

```py
        if torch.backends.mps.is_available():
            self.accelerator.native_amp = False
```

the mixed_precision arg doesn't take this into account and still rejects the MPS device due to lack of AMP.

**Comment by muellerzr** [comment]
We may need some further tweaks to allow full bf16/half precision training, you're right. If you'd like to take a stab at it (which would basically convert everything to half) I'm open to the idea if it's this much of a blocker, or just wait until torch 2.4 for autocast. 

If we go this route, it must be `False` by default.

**Comment by bghira** [comment]
it's not very bad - it's just a bit ugly to have to capture the value and ignore it for mps. but it's already worked-around in simpletuner, i just wanted it tracked here since bf16 on mps has been stable for some time and as a community we're looking forward to getting away from autocast altogether. it can be a future improvement

**Comment by bghira** [comment]
we have autocast now

**Comment by muellerzr** [comment]
@bghira do you know if it's 2.5 torch or 2.6?
