### ISSUE TITLE
Recommend dropping MS-AMP support 

### ISSUE THREAD

**Issue by rationalism** [huggingface/accelerate#3065]
As someone who used this library for a while in prod, then gave up, I'd honestly recommend just dropping it to simplify the code. There are several issues:

 - it isn't being very actively maintained, the last change to the code was in February 
 - it is pinned to an old version of MS's NCCL fork, which in turn pins it to Torch 2.1, which is now several major versions ago
 - replacing NCCL with a fork itself is prone to cause issues, since packages like MLNX_OFED also rely on it
 - both the Accelerate MS-AMP integrations with DeepSpeed and FSDP, which you'd normally want for large model training, are broken on main
 - by default, it doesn't work with DeepSpeed Zero3 at all
 - FSDP itself is being replaced with FSDP2, creating more messiness
 - internally, the code uses a bunch of monkey-patches, including monkey-patching DeepSpeed and monkey-patching Torch's linear module, which has sucked to debug

As a replacement, I've switched over to using:

 - FBGEMM for high speed FP8 matmul (https://github.com/pytorch/FBGEMM)
 - Optimi for low precision optimizers (https://github.com/warner-benjamin/optimi)

**Comment by bghira** [comment]
i've also completely moved away from autocast, especially because Apple MPS hasn't supported it yet and pure bf16 training has just gotten better and better. `optimi` is awesome.

**Comment by muellerzr** [comment]
I don't disagree, for complete-ness as we go to 1.0 I want to include support up until then, after we can drop it and explore other avenues. Re; main can you give some reproducers? I did some extensive testing, but I'll be looking at all failures this weekend.

**Comment by muellerzr** [comment]
In the future we intend on looking at `nanotron`'s FP8 support instead first, once they are all ready https://github.com/huggingface/nanotron/

(future being in the next month or two if it's good to go by then)
