### ISSUE TITLE
accelerate v0.33 load_state has KeyError

### ISSUE THREAD

**Issue by bghira** [huggingface/accelerate#3067]
### System Info

```Shell
accelerate v0.33.0
```

### Information

- [x] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

1. Upgrade from accelerate v0.31.0 to v0.33.0
2. Begin a training session using Lion optimiser from `torch-optimi` package
3. `accelerator.save_state()`
4. `accelerator.load_state()`

Observe KeyError:

```
'step'
Traceback (most recent call last):
  File "simpletuner/train.py", line 51, in <module>
    trainer.init_resume_checkpoint()
  File "simpletuner/helpers/training/trainer.py", line 1253, in init_resume_checkpoint
    self.accelerator.load_state(os.path.join(self.config.output_dir, path))
  File "/home/bghira/simpletuner/.venv/lib64/python3.11/site-packages/accelerate/accelerator.py", line 3156, in load_state
    self.step = override_attributes["step"]
                ~~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'step'
```

### Expected behavior

I am not sure where this was introduced, but downgrading to v0.31 makes it work again.

The issue doesn't seem to manifest when using other optimisers eg. adamw_bf16

The strange thing is that it's failing to pull the step from the random states pkl.

**Comment by muellerzr** [comment]
Can you try building off main? (Which next release will *literally* be tommorow). This is familiar and fairly confident we fixed it

**Comment by bghira** [comment]
hmm, the step of the lr scheduler isn't being set

**Comment by bghira** [comment]
ok the step of the LR scheduler also wasn't set properly in v0.31.0 @muellerzr even though the step keyerror disappeared. it seems like v0.33 is actually possibly the closest... since it tries to find the step, but fails

**Comment by muellerzr** [comment]
FYI this should be fine now, we check if `step` is in `override_attributes` first. LMK if not.

**Comment by Stickic-cyber** [comment]
I got this issue again

accelarate == 1.6.0

<img width="553" alt="Image" src="https://github.com/user-attachments/assets/dcda650d-60a8-4b36-91f8-f04e573e8cef" />
