### ISSUE TITLE
Setting FSDP FULL_STATE_DICT explicitly doesn't work

### ISSUE THREAD

**Issue by thepowerfuldeez** [huggingface/accelerate#3072]
### System Info

```Shell
accelerate==0.34.0
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

`trainer.accelerator.state.fsdp_plugin.set_state_dict_type("FULL_STATE_DICT")`

(trying to set FULL_STATE_DICT from fsdp config doesn't work either)

### Expected behavior

`trainer.accelerator.state.fsdp_plugin.set_state_dict_type("FULL_STATE_DICT")`works

**Comment by muellerzr** [comment]
@thepowerfuldeez is there a reason why you're trying to dynamically change the state dict type? We should only be relying on how you instantiate the FSDPPlugin here, which is why you found this change.

**Comment by thepowerfuldeez** [comment]
@muellerzr I remember cpu offload didn't work with sharded state dict, so it's changed dynamically in the code. I tried removing this part of code and changing from the config, but it doesn't work either.

**Comment by muellerzr** [comment]
If we're doing it this way, you would need to first override it manually on the plugin, then call `set_state_dict_type()`. But some code is really needed for me to wrap around this workflow.
