### ISSUE TITLE
How can I load the model silently?

### ISSUE THREAD

**Issue by sherlcok314159** [huggingface/accelerate#3083]
### System Info

```Shell
- `Accelerate` version: 0.33.0
- Platform: Linux-4.18.0-348.el8.0.2.x86_64-x86_64-with-glibc2.28
- `accelerate` bash location: /mntcephfs/lab_data/taiyunpeng/.conda/envs/gpt/bin/accelerate
- Python version: 3.9.18
- Numpy version: 1.26.3
- PyTorch version (GPU?): 2.4.0+cu118 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- PyTorch MLU available: False
- PyTorch MUSA available: False
- System RAM: 1007.73 GB
- GPU type: NVIDIA A100-SXM4-40GB
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

When using `xxx.from_pretrained(model_name, device_map='auto')`, the terminal will output `Loading checkpoint shards:`. I want the model loading process to be silent.

### Expected behavior

Loading model silently.

**Comment by ArthurinRUC** [comment]
You can use the following code to disable tqdm bar:
```python
from transformers import logging
logging.disable_progress_bar()
```
