### ISSUE TITLE
main_process_port: 0 in config for next free port not working - times out

### ISSUE THREAD

**Issue by lorenzflow** [huggingface/accelerate#3091]
### System Info

```Shell
`Accelerate` version: 0.29.3
- Python version: 3.11.4
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

Example of the config file:

```
compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_config_file: configs/deepspeed_rl.json
  zero3_init_flag: false
distributed_type: DEEPSPEED
downcast_bf16: no
machine_rank: 0
main_training_function: main
main_process_port: 0
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

Then I run

`accelerate launch --config_file config my_script.py`.

I get the following error message:

```
 File "/lustre/home/ucabwol/projects/rlhf/lib/python3.11/site-packages/torch/distributed/rendezvous.py", line 170, in _create_c10d_store
    tcp_store = TCPStore(hostname, port, world_size, False, timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.distributed.DistNetworkError: The client socket has timed out after 1800s while trying to connect to (127.0.0.1, 0).
```

### Expected behavior

Accelerate finds the next free port to use.

**Comment by muellerzr** [comment]
@lorenzflow can you give some example code you've tried running? (E.g. does this happen even if your script just does `print()`)?

**Comment by ziyannchen** [comment]
> [@lorenzflow](https://github.com/lorenzflow) can you give some example code you've tried running? (E.g. does this happen even if your script just does `print()`)?
> 
> (And also just in case can you try on the latest accelerate version?)

I got the same error message `TimeoutError: The client socket has timed out after 1800s while trying to connect to (127.0.0.1, 0).`

The command I used is CUDA_VISIBLE_DEVICES=1 accelerate launch --num_processes=1 --main_process_port 0 inference.py ....`

It seems that pass 0 to the param `--main_process_port` just can not work.

**Comment by lorenzflow** [comment]
Sorry for the slow reply...

@ziyannchen I have not tried to just run `print()`, but the below code searching for a free port and using that seemed to work so far:

```
find_free_port() {
    python3 -c "
import socket
with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
    s.bind(('', 0))
    print(s.getsockname()[1])
"
}

# Get a free port
FREE_PORT=$(find_free_port)

accelerate launch --config_file config.yaml --main_process_port $FREE_PORT
```
