### ISSUE TITLE
Use accelerate on both CPUs and GPUs.

### ISSUE THREAD

**Issue by fy222fy** [huggingface/accelerate#3094]
The `accelerator` supports running in multiple GPUs and multiple CPUs scenarios. 
Can I run `accelerate` in scenarios where both CPUs and GPUs exist at the same time? 
For example, machine 1 uses the GPU and machine 2 uses the CPU?

**Comment by muellerzr** [comment]
If you mean for training, no that's not supported.

**Comment by fy222fy** [comment]
@muellerzr 
Yes, it is training/fine-tuning. 
I hope to fine-tune some layers of the llm on CPU and other layers o GPU, and implement Pipeline Parallelism. 
Does the accelerator have plans to support this capability? 
And do you have any other related suggestions?
Thanks for your answer!

**Comment by muellerzr** [comment]
We support that via DeepSpeed/FSDP weight offloading. We're looking into native pipeline parallelism soon

**Comment by fy222fy** [comment]
Thanks for your reply. 
I don't want to do weight offloading here, but I hope to use CPU and GPU at the same time in pipeline parallelism, for example, train the first layer in CPU, then train the second layer in GPU, etc.
Is this possible in the current `accelerate` PP?

**Comment by muellerzr** [comment]
No, we do not.
