### ISSUE TITLE
Logger behaviors with Cross-Validation and the Global Steps

### ISSUE THREAD

**Issue by muellerzr** [huggingface/accelerate#310]
# Interaction of Multiple Runs (such as Cross Validation) With Logging

## What is the problem?

After talking with Boris Dayma at Weights and Biases, he pointed out that there are a few flaws in the current design of the tracking API (and this feedback is valid as a whole, not just for W&B):

We set the `step` when using W&B, and there are a few drawbacks to this approach:
- If we did cross validation or something else, and suddenly the step decreases (goes back to 0), all values will be dropped
- When we use the `step`, the current log is not committed as it waits for potentially more dict values from a later call (and will then auto-commit from the next step), so all steps will be 1 step late

## Potential Pathways
The first basic solution is when we can, don't pass in an explicit step unless we are *extremely* sure that's what the user wants. However, there is an argument that this may never be the case, and we should just log the global step passed in as a key, rather than setting a config somewhere if posible

For the rest, there are three possible ways we can address this issue:
- We can explicitly write directions that if you are writing for Cross-Validation (or some case where we have reasons the first condition is met), to call `Accelerate.init_trackers()` again with a different run name to "reset" the run, and `Accelerate.finish_training()` at the end of each fold, rather than the end of the entire training process (not ideal for that second one)
- Add in a method of something such as `finish_fold` or `finish_logs` that just ties up the loggers specifically, and this gets called from `Accelerate` itself during `finish_training`, and adds `Accelerate.finish_logs` to keep the namings similar
- Lastly, we really **shouldn't** be assigning the internal steps of the loggers, since it can lead to issues with things potentially being misaligned. (See W&B feedback for more details)

## W&B Specific Feedback:
- Something done in the Lightning trainer is they log the global step as:
`"trainer/global_step"`, but I think having `"accelerate/global_step"` is a bit much personally
- We can "hack" the ability to add extra calls to `wandb.log` without messing up the steps, by adding in a metric to align the x-axis together (so rather than 1:1 step for step, our users can use W&B at their own will if they want to log something else). Essentially we throw this in after creating our run:
```python
wandb.define_metric("*", step_metric="my_default_x_axis")
```
And then doing something like the following will keep them affiliated in the same run, even though they are "different":
```python
wandb.log({'eval/accuracy': accuracy_value})
wandb.log({'train/loss': training_loss})
```
Personally I feel that these are more "power user" directions, as internally nothing much should need to happen here. We just tell the user "Once you've called `Accelerate.init_trackers`, if you want to be able to log more items and keep everything affiliated with each other than just what is supported in Accelerate (since we limit to floats, but W&B has a host of other logging functions), you can log them with..." and have an example of `if accelerator.is_main_process:...`

## Priority List
Adjusting `step` just pass in the `global_step` and never set the raw step in the tracker seems like that should be done relatively ASAP, since it leads to behavioral issues and expectation troubles

However with the "power user" approach, this can be turned into a later tutorial, probably showcasing cross-validation and how to do that properly

WDYT @sgugger?

**Comment by borisdayma** [comment]
Looks good!

I think if you just log with `wandb.log({'step':step, **dict})` and use the `define_metric` command after creating the run, everything will work smoothly for everybody, even if for any reason they call manually `wandb.log(…)` (for logging gradient histograms, image tables, sample predictions, timing metrics…).

If you plan to log some other metrics like `elapsed_samples`, `elapsed_time`, etc, I would suggest using a group such as `trainer/step`, `trainer/elapsed_samples`, etc, so they are nicely grouped and you select the one you want as x-axis in your graphs.

**Comment by muellerzr** [comment]
@borisdayma where we're staying is if they want to get specific, the user should always be able to do:
```python
if accelerator.is_main_process:
  # log whatever
```
for the more nitty-gritty. As this wrapper serves as a general alias to quickly log whatever you may need generally. 

When it comes to specific cases of whether the step should be passed in as overriding the global step or not, PR's are welcome towards addressing that specific area to the `Tracker`, which all are available to see in `accelerate/src/tracking.py`. 

We'll leave this issue open as a reference for those folks as well 🤗
