### ISSUE TITLE
CAN'T Run Two Accelerates in Parallel on a Single Machine with Multiple GPUs 

### ISSUE THREAD

**Issue by vegetable-lion** [huggingface/accelerate#3106]
### System Info

```Shell
compute_environment: LOCAL_MACHINE
distributed_type: 'MULTI_GPU'
downcast_bf16: 'no'
gpu_ids: all
machine_rank: 0
main_training_function: main
mixed_precision: 'fp16'
num_machines: 1
num_processes: 4
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
main_process_port: 0
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction
for the 1st accelerate:
```python
export CUDA_VISIBLE_DEVICES=0,1,2,3 && HF_ENDPOINT=https://hf-mirror.com accelerate launch      --config_file="./configs/multi_gpu.yml"   tests.py  
```
for the 2nd accelerate:
```python
export CUDA_VISIBLE_DEVICES=4,5,6,7 && HF_ENDPOINT=https://hf-mirror.com accelerate launch      --config_file="./configs/multi_gpu.yml"   tests.py  
```

### Expected behavior

I am running multiple experiments on a single machine with 8 GPU cards. My current setup involves allocating 4 GPUs for the first experiment and another 4 GPUs for the second experiment. However, I can't run accelerate successfully because main_process_port is ignored... Is there any possible solution?

**Comment by muellerzr** [comment]
What happens if you manually set one to 29500 and 29501?

**Comment by vegetable-lion** [comment]
> What happens if you manually set one to 29500 and 29501?

Then my problem is solved!!! Thank you so much!
