### ISSUE TITLE
Can't run notebook_launcher on Colab TPU

### ISSUE THREAD

**Issue by emusiienko** [huggingface/accelerate#3115]
### System Info

```Shell
accelerate version: 0.34.2
```

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

1. Open notebook in google colab
2. Create any training_function
3. run this function using notebook_launcher in TPU env

here is how I run it:

------
from accelerate import notebook_launcher
from train import training_function
import os

os.environ["TPU_NAME"] = "dummy"
os.environ["XRT_TPU_CONFIG"]="localservice;0;localhost:51011"

notebook_launcher(training_function, (model, tokenized_datasets), mixed_precision="bf16")
-------

Result: error
ValueError                                Traceback (most recent call last)
[<ipython-input-11-0b7a61f5707e>](https://localhost:8080/#) in <cell line: 12>()
     10 os.environ["XRT_TPU_CONFIG"]="localservice;0;localhost:51011"
     11 
---> 12 notebook_launcher(training_function, (model, tokenized_datasets), mixed_precision="bf16")

3 frames
[/usr/lib/python3.10/enum.py](https://localhost:8080/#) in __new__(cls, value)
    708                 ve_exc = ValueError("%r is not a valid %s" % (value, cls.__qualname__))
    709                 if result is None and exc is None:
--> 710                     raise ve_exc
    711                 elif exc is None:
    712                     exc = TypeError(

ValueError: 'TPU' is not a valid DistributedType

--------
Comments:
It happens because in the file "launchers.py", row 148 launcher is created like:          
"launcher = PrepareForLaunch(function, distributed_type="TPU")"

However DistributedType doesn't accept 'TPU', it's deprecated. ('TPU = DeprecatedFieldDescriptor("TPU", "XLA")'). 
Initialization of this enum with 'TPU' string raises the mentioned exception. (prooved by trying this locally)

### Expected behavior

Expected: function is run

**Comment by SunMarc** [comment]
Hi @emusiienko, thanks for the report ! Could you try this [PR](https://github.com/huggingface/accelerate/pull/3118) to see if this solves your issue ?

**Comment by emusiienko** [comment]
Hi @SunMarc , sorry that maybe late, it works, thank you!
