### ISSUE TITLE
profiler requires torch >= 2.4.0

### ISSUE THREAD

**Issue by jenspetersen** [huggingface/accelerate#3128]
### System Info

```Shell
accelerate >= 0.32.0
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

accelerate.utils.dataclasses.ProfileKwargs._get_profiler_activity has a profiler_activity_map variable, which accesses various elements of the torch.profiler.ProfilerActivity enum. The enum changed with torch versions, and the currently required elements are only fully available in torch >= 2.4.0. In particular, they became available in the following versions (ignoring RCs):

torch.profiler.ProfilerActivity.CPU -> 1.13.0
torch.profiler.ProfilerActivity.CUDA -> 1.13.0
torch.profiler.ProfilerActivity.XPU -> 2.4.0
torch.profiler.ProfilerActivity.MTIA -> 2.1.0

### Expected behavior

accelerate.utils.dataclasses.ProfileKwargs._get_profiler_activity should work if not all enum elements are available, but the desired ones are (e.g. the user only wants to profile CPU and CUDA, then an older torch version without XPU/MTIA support should still work).

**Comment by yhna940** [comment]
I have created a [PR](https://github.com/huggingface/accelerate/pull/3136) to address this issue. Thank you for reporting it!
