### ISSUE TITLE
dsitributed on mulit-CPU

### ISSUE THREAD

**Issue by arita37** [huggingface/accelerate#32]
Just wondering if there is way to distribute over CPU  (single node, or multi nodes).
It would be very useful features for some sparse models.

**Comment by sgugger** [comment]
I don't think this is supported for now. How do you use PyTorch for this use case? Accelerate is syntax sugar over PyTorch, so if the feature does not exist in PyTorch, we probably won't be able to add it.

**Comment by arita37** [comment]
Horovod can handle on distributed CPU:
https://github.com/huggingface/accelerate/issues/32#issuecomment-822466053

**Comment by sgugger** [comment]
Ok, so support for Horovod is what you need. It's on the roadmap :-)

**Comment by ddkalamk** [comment]
> I don't think this is supported for now. How do you use PyTorch for this use case? Accelerate is syntax sugar over PyTorch, so if the feature does not exist in PyTorch, we probably won't be able to add it.

Could you please consider support for MPI backend in torch DDP? Ideally, I want to specify backend from command line argument so I can specify some custom backend. An example use for Intel oneCCL backend (using Intel torch-ccl) can be found at https://github.com/ddkalamk/transformers/blob/pcl-v4.0.0/examples/question-answering/run_squad.py#L746

Assumption is we launch the application using MPI (similar to horovod) and based on environment variable initialize distributed backend.

**Comment by sgugger** [comment]
Will look into this one too!

**Comment by sgugger** [comment]
Should be fixed by #63
