### ISSUE TITLE
Type of Accelerator.distributed_type() might be wrong

### ISSUE THREAD

**Issue by ffrancesco94** [huggingface/accelerate#3205]
Hi,
I am trying to run one of the slurm examples, specifically multi-node GPU training. I tried to pick two GPUs on two different nodes as a small test. If, during the `complete_nlp_example.py` script I make it print the number of GPUs with `accelerator.num_processes` and the type with `accelerator.distributed_type`, I get 2 (correctly), but the type is DistributedType.MULTI_CPU. Is this just a case of the multi-node "shadowing" the fact that each node actually has GPUs or does it mean that the model is actually running on CPUs? Thank you!

**Comment by muellerzr** [comment]
It would mean it's actually running on CPU. You can verify this by checking the device of the model or the data coming in

**Comment by ffrancesco94** [comment]
Thank you! So to be clear, whether the GPUs sit all on one node or they're
distributed, the type should be always MULTI_GPU?

PS: checking the device would still mean doing it through the Accelerator
object or how else? Thank you very much!

**Comment by muellerzr** [comment]
Correct.

You can also do `from accelerate import PartialState; print(PartialState().device)`

For a quick one-liner

**Comment by ffrancesco94** [comment]
Ok, seems like I'm hitting some kind of bug, opening another thread for that though.
