### ISSUE TITLE
PyPI published Accelerate==1.1.0 is missing Source Distributions 

### ISSUE THREAD

**Issue by helloworld1** [huggingface/accelerate#3216]
### System Info

```Shell
accelerate==1.1.0
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

Previous versions of accelerate provides source distribution but accelerate 1.1.0 is missing source distribution

### Expected behavior

PyPI has source distribution

**Comment by muellerzr** [comment]
Not sure what you mean? https://github.com/huggingface/accelerate/releases/tag/v1.1.0

**Comment by mgorny** [comment]
He probably meant https://pypi.org/project/accelerate/1.1.0/#files that has `.whl` only but no Source Distributions.

**Comment by helloworld1** [comment]
Yes, exactly the https://pypi.org/project/accelerate/1.1.0/#files is missing source distribution. Our build system requires source distribution to validate the package. Thanks!
