### ISSUE TITLE
slurmstepd: error: execve(): accelerate: No such file or directory

### ISSUE THREAD

**Issue by huiyang865** [huggingface/accelerate#3237]
### System Info

```Shell
accelerate==1.1.1
torch==2.5.1
Python3.10
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

An issue like https://github.com/huggingface/accelerate/issues/2192

### Expected behavior

Hello, I have the same problem like https://github.com/huggingface/accelerate/issues/2192. I log in to each node to check that accelerate has been installed. However, when a task is pushed on the primary node, an error is still reported.

![image](https://github.com/user-attachments/assets/72bd2b0c-db82-4e5f-a112-46b7c2a3ebfc)

Next log is a test running of accelerate on each node.
![image](https://github.com/user-attachments/assets/7f0bbbf7-7e1e-48cc-9e14-7f8984b9e1e8)

How to fix it?

**Comment by ffrancesco94** [comment]
Does the same happen if you use a submit script where you also instantiate the conda environment? I think slurm does not source your .bashrc file when using srun/sbatch, so you have to tell it to use conda explicitly. Have you tried writing a small script that sources and instantiates the conda environment and then calls `accelerate`?

**Comment by huiyang865** [comment]
Yes, the accelerate environment of compute nodes need to be explicitly deployed on the host node. 

But I ran into another problem, while I srun the slurm with 2 compute nodes by the command: srun accelerate launch --config_file config_yaml_templates/multi_node.yaml complete_cv_example.py --data_dir /nas/yanghui/slurm_data/images/

Slurm has prompted an error: torch.distributed.DistStoreError: Timed out after 901 seconds waiting for clients. 1/2 clients joined.

More error details:
![C0D463FF-F556-470f-A6F9-E8CCEEDF4CF2](https://github.com/user-attachments/assets/8ada496e-065f-4844-aa0b-9620c9979668)

The content of config_yaml_templates/multi_node.yaml is:
![36864B59-8E8D-44f6-BD56-8F34B347EB09](https://github.com/user-attachments/assets/6fbd7dc3-22ca-4be8-93b3-6249a748a748)

It seems that slurm can only start one compute node. How can I solve this problem?

**Comment by huiyang865** [comment]
refer to https://github.com/huggingface/accelerate/issues/3206, I have trained on multinodes successfully.
