### ISSUE TITLE
deepspeed zero3 save model

### ISSUE THREAD

**Issue by Reginald-L** [huggingface/accelerate#3238]
Hi, I am using deepspeed zero3 to fine tune flux model using kohya scripts.

```
flux = accelerator.unwrap_model(flux)
print(f"flux - {flux.state_dict()['single_blocks.7.linear1.weight'].shape}")
print(f"flux - {flux.state_dict()['single_blocks.7.linear1.weight'].device}")
```
I got the below result:
![image](https://github.com/user-attachments/assets/9592b35b-7ee4-4d75-ab01-3ee786e34514)

and When I save the trained model, I got this:
![image](https://github.com/user-attachments/assets/94a3377a-308f-4de9-9c73-c35241ed6119)

Here is my zero config:
![image](https://github.com/user-attachments/assets/1f9a7ccd-4209-4d08-b4c2-92d3ca4dc9b9)

**Comment by BenjaminBossan** [comment]
Could you try the `with deepspeed.zero.GatheredParameters(params)` context?

**Comment by Reginald-L** [comment]
> Could you try the `with deepspeed.zero.GatheredParameters(params)` context?

Cool， thanks very much， your solution is pretty useful
