### ISSUE TITLE
OOM error when training llama 7B model using Accelerate FSDP setting

### ISSUE THREAD

**Issue by JlPang863** [huggingface/accelerate#3239]
### System Info

```Shell
- `Accelerate` version: 0.31.0
- Platform: Linux-5.15.0-125-generic-x86_64-with-glibc2.35
- `accelerate` bash location: 
- Python version: 3.10.12
- Numpy version: 1.26.4
- PyTorch version (GPU?): 2.5.1+cu124 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- PyTorch MLU available: False
- System RAM: 755.48 GB
- GPU type: NVIDIA L40S
- `Accelerate` default config:
compute_environment: LOCAL_MACHINE
debug: false
distributed_type: FSDP
downcast_bf16: 'no'
enable_cpu_affinity: false
fsdp_config:
  fsdp_activation_checkpointing: true
  fsdp_auto_wrap_policy: NO_WRAP
  fsdp_backward_prefetch: BACKWARD_PRE
  fsdp_cpu_ram_efficient_loading: true
  fsdp_forward_prefetch: false
  fsdp_offload_params: true
  fsdp_sharding_strategy: FULL_SHARD
  fsdp_state_dict_type: SHARDED_STATE_DICT
  fsdp_sync_module_states: true
  fsdp_use_orig_params: true
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

            accelerate launch \
                --num_machines 1 \
                --num_processes $NUM_GPUS \
                --mixed_precision bf16 \
                --use_fsdp \
                --fsdp_sharding_strategy FULL_SHARD \
                --fsdp_offload_params true \
                --fsdp_activation_checkpointing true \
                --main_process_port 29501 \
                open_instruct/finetune.py \
                --model_name_or_path $base_model \
                --gradient_checkpointing \
                --use_lora \
                --lora_rank 64 \
                --lora_alpha 16 \
                --lora_dropout 0.1 \
                --tokenizer_name $base_model \
                --use_slow_tokenizer \
                --train_file $train_data \
                --max_seq_length $max_seq_length \
                --preprocessing_num_workers 16 \
                --checkpointing_steps epoch \
                --per_device_train_batch_size $BATCH_SIZE_PER_GPU \
                --gradient_accumulation_steps $GRADIENT_ACC_STEPS \
                --learning_rate 1e-4 \
                --lr_scheduler_type linear \
                --warmup_ratio 0.03 \
                --weight_decay 0. \
                --num_train_epochs 5 \
                --output_dir $cluster_root_path/models/${labeling_model}/${train_dataset_name}/${base_model}/lora_${data_type}/ \
                --with_tracking \
                --report_to tensorboard \
                --logging_steps 1 

### Expected behavior

The maximum memory of GPU I used is 45GB. I am trying to train 7B model with a mixed precision bf16. Ideally, the allocated gpu memory should be 15GB, which is okay. However, when I load the model to GPU, I observe an unusual GPU OOM error. The required GPU memory suddenly becomes very high and then result in OOM.  I test using the `torchrun --enable-fsdp` setting to train the same script, which works. However, I cannot figure out why accelerate config using the same FSDP setting would raise the OOM error.

**Comment by BenjaminBossan** [comment]
Strange that `torchrun` works but `accelerate launch` doesn't. Could you please also paste the full error message and the contents of `finetune.py `?

**Comment by Dludora** [comment]
I'd ask: have u fixed this problem? I meet with the same problem.
