### ISSUE TITLE
[BUG] Accelerator.__init__() got an unexpected keyword argument 'logging_dir'

### ISSUE THREAD

**Issue by as12138** [huggingface/accelerate#3257]
### System Info

```Shell
accelerate version: main
python version: 3.11
torch version: 2.4
numpy version: 1.26.4
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

When I run the accelerate/examples/megatron_1m_gpt_pretraining. py file 
accelerate launch --config_file megatron_gpt_pretraining.py \
--config_name "gpt2-large" \
--tokenizer_name "gpt2-large" \
--dataset_name wikitext \
--dataset_config_name wikitext-2-raw-v1 \
--block_size 1024 \
--learning_rate 5e-5 \
--per_device_train_batch_size 24 \
--per_device_eval_batch_size 24 \
--num_train_epochs 5 \
--with_tracking \
--report_to "wandb" \
--output_dir "awesome_model"

### Expected behavior

Normal training, but I found that in megatron_1m_gpt_pretraining on line 255 of the py file, there is an undefined parameter 'logging.dir' in the __init__ method of the Accelerator function

**Comment by BenjaminBossan** [comment]
Thanks for pointing this out. I think it should be `project_dir` instead. Are you interested in submitting a PR to fix this?

**Comment by muellerzr** [comment]
For clarity, the file is at `https://github.com/huggingface/accelerate/blob/main/examples/by_feature/megatron_lm_gpt_pretraining.py` :)

**Comment by as12138** [comment]
of course
