### ISSUE TITLE
Incorrect set of --nproc_per_node through accelerate launch

### ISSUE THREAD

**Issue by chenzhekl** [huggingface/accelerate#327]
It seems that accelerate is unable to handle multi-node training where each machine is equipped with different number of GPUs. The cause might be this line of code:

https://github.com/huggingface/accelerate/blob/main/src/accelerate/commands/launch.py#L190-L190

**Comment by sgugger** [comment]
It might be unsupported by the `accelerate launch` command, but if you have a way to make it work with the PyTorch distributed launcher, you can launch you script with it :-)
