### ISSUE TITLE
Calling infer_auto_device_map() with max_memory=None throws an error in version 1.2.0

### ISSUE THREAD

**Issue by chmeyers** [huggingface/accelerate#3276]
### System Info

```Shell
accelerate==1.2.0
```

### Reproduction

Bug is from this commit:
https://github.com/huggingface/accelerate/commit/d7b1b368e9f484a18636a71600566b757d5cf87e

`max_memory` initialization was moved into `_init_infer_auto_device_map`, which does not return the `max_memory` value.

So if max_memory=None is passed to `infer_auto_device_map` (the default value), then it will still be None at line 1415:
https://github.com/huggingface/accelerate/blob/cb8b7c637a8588668c52bd306f9b2828f69d9585/src/accelerate/utils/modeling.py#L1415

Leading to error: TypeError: 'NoneType' object is not subscriptable

### Expected behavior

max_memory=None when passed to `infer_auto_device_map` does not throw an error.

**Comment by chmeyers** [comment]
@Nech-C

**Comment by Nech-C** [comment]
Sorry for the oversight. I will fix it ASAP. Thanks for pointing it out!
