### ISSUE TITLE
1.2.0 released to pypi with no corresponding release on repo

### ISSUE THREAD

**Issue by Qubitium** [huggingface/accelerate#3292]
At ModelCloud/GPTQModel we are encountering incompatibility between 1.2.0 vs 1.1.1 but without official repo release and changelog, it will be more work than necessarily to debug the issue.

Please cut a repo release that corresponds to pypi

![Screenshot_2024-12-13-18-00-20-09_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/user-attachments/assets/3f4baf2d-bd13-4cd3-be6d-4497ea07a355)

**Comment by Qubitium** [comment]
The regression part has been fixed with PR https://github.com/huggingface/accelerate/pull/3293

**Comment by muellerzr** [comment]
Patch will be going out today + release notes on both!
