### ISSUE TITLE
Missing 'logging.py' file in pip installation

### ISSUE THREAD

**Issue by sptom** [huggingface/accelerate#349]
Hi there! 

Tried to run your code from "Transformers\examples\pytorch\run_image_classification_no_trainer.py.
I installed the required accelerate package via pip, seems to be the right version (0.7.1), 

but the code crashes on the line "from accelerate.logging import get_logger" line with the error that there's no such module.
I even tried to edit the init file, but I can access all other modules - Accelerator, checkpointing, tracking etc...

It's as if I downloaded an older version without '.logging', but the version number seems correct. 
Any idea why this might happen, and how could I fix it without manually cloning your repository from github?

Thanks

**Comment by muellerzr** [comment]
The directions state that you need to install from source, as we're rapidly working on Accelerate and bringing in new features. 

https://github.com/huggingface/transformers/tree/main/examples/pytorch#using-accelerate

**Comment by sptom** [comment]
Thank you!

This is from the 'transformers' directions, while I was looking in the directions in the 'accelerate' repository itself where there's a regular installation command. 

![image](https://user-images.githubusercontent.com/12126222/167260945-757631dd-d063-444c-bd0a-651dba515596.png)

Anyway, installed from source as you suggested, works well now, thanks again!

**Comment by muellerzr** [comment]
@sptom thanks, all the directions in transformers now state this 🤗
