### ISSUE TITLE
Evaluation could have duplicated validation data

### ISSUE THREAD

**Issue by allanj** [huggingface/accelerate#350]
When we use the accelerator `gather` function, potentially, we would receive more validation data than we have.
For example, the batch size for each device is `8` and we have `3` devices. Our actually total data is 22 samples.
When we do `gather`, we receive `24` samples but not `22`, this might cause an inconsistent evaluation metric.

What I did after I realized this issue, I did the following two lines.
```python3
## here predictions is after we do gather operation and did certain post-processing
predictions = predictions[:len(valid_dataloader.dataset)]
targets = targets[:len(valid_dataloader.dataset)]
```

Shall we kind of specify this note in the README or the example (https://github.com/huggingface/accelerate/blob/main/examples/nlp_example.py#L160-L169)?

**Comment by muellerzr** [comment]
Thanks for catching this! Will fix these examples next week. The transformers no_trainer examples have the right behavior, I just did not update these it seems.

https://github.com/huggingface/transformers/blob/main/examples/pytorch/text-classification/run_glue_no_trainer.py#L525

**Comment by muellerzr** [comment]
This will be closed by https://github.com/huggingface/accelerate/pull/352, but we came to a conclusion that this is specified inside of the https://github.com/huggingface/accelerate/blob/main/examples/by_feature/multi_process_metrics.py example here. A note in the README couldn't hurt
