### ISSUE TITLE
accelerate & deepspeed port

### ISSUE THREAD

**Issue by bujiahao** [huggingface/accelerate#351]
I use deepspeed for my program.

How can I specify the master port?

the script "accelerate launch --main_process_port 29051 run_mlm_no_trainer.py" does not seem to work fine.

the actual cmd is "cmd = /home/toc/SDE/miniconda3/envs/trans/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMV19 --master_addr=127.0.0.1 --master_port=29500 --no_local_rank run_mlm_no_trainer.py --model_name_or_path roberta-base --dataset_name wikitext --dataset_config_name wikitext-2-raw-v1 --per_device_train_batch_size 8 --per_device_eval_batch_size 8 --output_dir /tmp/test-mlm"

**Comment by bujiahao** [comment]
the script "accelerate launch --main_process_port 29051  run_mlm_no_trainer.py" does not seem to work fine.

the log is "[2022-05-09 04:41:16,315] [INFO] [runner.py:453:main] cmd = /home/toc/SDE/miniconda3/envs/trans/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMV19 --master_addr=127.0.0.1 --master_port=29500 --no_local_rank run_mlm_no_trainer.py --model_name_or_path roberta-base --dataset_name wikitext --dataset_config_name wikitext-2-raw-v1 --per_device_train_batch_size 8 --per_device_eval_batch_size 8 --output_dir /tmp/test-mlm"

**Comment by sgugger** [comment]
The `main_process_port` is ignored if you don't have several machines, and it doesn't look like you set `--num_machines` to anything > 1.

**Comment by 2catycm** [comment]
> The `main_process_port` is ignored if you don't have several machines, and it doesn't look like you set `--num_machines` to anything > 1.

this is a wrong design. Supposs I am running multiple experiments on a single machine with 8 GPU cards, 4 for the first run and 4 for the second. You see, I cannot use accelerate successfully!

**Comment by pongib** [comment]
> > The `main_process_port` is ignored if you don't have several machines, and it doesn't look like you set `--num_machines` to anything > 1.
> 
> this is a wrong design. Supposs I am running multiple experiments on a single machine with 8 GPU cards, 4 for the first run and 4 for the second. You see, I cannot use accelerate successfully!

I’ve actually been able to use multiple `main_process_port` values on the same machine for different experiments without issues.

**Comment by Kemsekov** [comment]
Same issue

Why no attention??

**Comment by yguooo** [comment]
Got the same issue as well.

**Comment by Kemsekov** [comment]
I had a problem with ports because i was running accelerate launch on all my nodes specified in hostfile, but you actually need only to run main node, and deepspeed will look into hostfile and run all other nodes on it's own.

You only need to make sure main node can connect to all others without password by sloth ip via ssh and make sure that NCCL_SOCKET_IFNAME is available and accessible.

**Comment by Jesteinbe** [comment]
I've got the same issue. This is especially true when you're using a shared compute resource and either you and/or others are submitting jobs at the same time which often get run on the same node. It would be way better if there was a simple way to manage the necessary ports.

**Comment by FredericOdermatt** [comment]
Here is the limited things I gathered:

#1657 adds a comment to set `main_process_port` to `0` to automatically assign the next port. This unfortunately doesn't work for most setups.

From what I gather, this is only correct when using `rdzv_backend` `c10d`. Check here for [related discussion](https://github.com/pytorch/pytorch/issues/73320#issuecomment-1055785232)

Following the related discussion, the proper approach is likely to update the comment to propose to use backend `c10d` in case of collisions with `args.rdvz_endpoint = localhost:0`

Currently `args.rdvz_endpoint` is only set if  `args.num_machines > 1` and `args.same_network = True`

https://github.com/huggingface/accelerate/blob/d6d3e03cd4868b1f69d4f334ddd341e4d414c342/src/accelerate/utils/launch.py#L199
