### ISSUE TITLE
Export summarization pipeline to ONNX

### ISSUE THREAD

**Issue by asheru** [huggingface/accelerate#353]
Hello,
   Can you please provide me with an example of exporting **summarization**-pipeline to ONNX?
   I looked at the notebook exemplifying how to export  NER pipeline to ONNX (please refer to  https://towardsdatascience.com/nlp-transformers-pipelines-with-onnx-9b890d015723).

In the ner example,  a class was inherited from TokenClassificationPipeline, and the method _forward was overrided, such that "self.model(model_inputs.data)" was replaced by "session.run(output_names=[outputs_name], input_feed=inputs)" . (inputs is a conversion of inputs_data to numpy arrays.) 

Trying to mimic the procedure to Summarization, my problem: 
         I inherited a class from SummarizationPipeline, and then tried  to override the _generate method. However, I do not succeed to replace "self.tokenizer.decode(...)"  with "session.run(...)"
Thank you,
asher.uziel@gmail.com

**Comment by muellerzr** [comment]
Please post questions like these in the forums, especially as this doesn't relate to the Accelerate library.

I'd recommend this topic: https://discuss.huggingface.co/c/beginners/5

**Comment by asheru** [comment]
Will do - Thank you very much!
