### ISSUE TITLE
Cannot tweak the DeepSpeed from script

### ISSUE THREAD

**Issue by vlianmcent** [huggingface/accelerate#354]
I would like to tweak the DeepSpeed from my program.
However, it seems that the program does not activate the DeepSpeed.

[pretrain.sh]
python -m torch.distributed.launch --nproc_per_node 8 --use_env pretrain_wav2vec.py ....

[pretrain_wav2vec.py]
deepspeed_plugin = DeepSpeedPlugin(zero_stage=2, gradient_accumulation_step = 8)
accelerator = Accelerator(fp16=True, deepspeed_plugin= deepspeed_plugin)

Thanks for the help!

**Comment by sgugger** [comment]
Indeed, passing a `DeepSpeedPlugin` will not activate deepspeed automatically. Maybe you can ahve a look into this @pacman100 ?

**Comment by pacman100** [comment]
Hello, PR to fix this : #356

**Comment by vlianmcent** [comment]
Thanks a lot!!
