### ISSUE TITLE
some accelerator enhancements

### ISSUE THREAD

**Issue by ZhiyuanChen** [huggingface/accelerate#366]
Hi,

My [main code base](https://github.com/ZhiyuanChen/DanLing/tree/develop) have been switched to be based on accelerate for a while, it works grate! Thank you guys so much!

There are a few things I think it's a common need.

The first is `.distsibuted` attributes, which is basically `.num_processes > 1`. I mean, it's not a lot of works but .... I'm an extremely lazy person.
```
def distsibuted(self):
    """
    Runs in distributed mode
    """
    return self.num_processes > 1
```

Besides, these two decorators are often used in my code when saving models and downloading datasets, I think it could be useful.

```
def on_main_process(func):
    """
    Run func on main process
    """
    @wraps(func)
    def wrapper(self, *args, **kwargs):
        if self.is_main_process or not self.distributed:
            return func(self, *args, **kwargs)
    return wrapper


def on_local_main_process(func):
    """
    Run func on local main process
    """
    @wraps(func)
    def wrapper(self, *args, **kwargs):
        if self.is_local_main_process or not self.distributed:
            return func(self, *args, **kwargs)
    return wrapper
```

**Comment by muellerzr** [comment]
Nice idea! @sgugger WDYT of instead having this wrap around AcceleratorState directly, rather than having this be attached to Accelerator?

**Comment by sgugger** [comment]
I don't mind having wrappers on the Accelerator for those. As long as the naming is clear, it's not a bad thing to have multiple properties/methods/context managers for different use cases :-)

**Comment by ZhiyuanChen** [comment]
I do think `distsibuted` should be in `AcceleratorState`, but for the decorators, I think it's better to put it in the `Accelerator`

**Comment by sgugger** [comment]
There is no way to set it and make it work (you can't transform the training in distributed mode suddenly), so it should be a property.

**Comment by ZhiyuanChen** [comment]
> There is no way to set it and make it work (you can't transform the training in distributed mode suddenly), so it should be a property.

Ohh, by property I meant the `@property` decorated function, and by variable I meant a value. So I assume variable is better.

Though as PyTorch is supporting elastic training, maybe other values (e.g. num_processes) should be set to a property?

**Comment by sgugger** [comment]
I understood properly, and I still stand by the fact it should be a property, decorated by `@property` and not a variable.

**Comment by ZhiyuanChen** [comment]
Should we makee other variables (e.g. `num_processes`) property too?

**Comment by muellerzr** [comment]
@ZhiyuanChen I'd say it couldn't hurt I think!

**Comment by ZhiyuanChen** [comment]
Hi sorry for this late reply.... but do you mean if changing doesn't hurt or not changing doesn't hurt...

**Comment by muellerzr** [comment]
Changing it! 😄

**Comment by ZhiyuanChen** [comment]
> Changing it! 😄 

Haha will do

**Comment by ZhiyuanChen** [comment]
I believe everything has been merged now, so I'm gonna close this issue.

Thanks again for this grate work!
