### ISSUE TITLE
distribution data across multiple GPUs?

### ISSUE THREAD

**Issue by milad1378yz** [huggingface/accelerate#367]
I have a fundamental question, how can this library distribute data across multiple GPUs?

**Comment by pacman100** [comment]
Hello, thank you for the question. However, correct place for such questions is the [Hugging Face Forums] (https://discuss.huggingface.co/c/accelerate/18). 

To answer you question for timebeing, separate partitions/shards of the dataset are made available to different GPUs in case of PyTorch `Dataset`. This makes sure each GPU sees different data and gradients are aggregated over GPUs in distributed setup.  In case of PyTorch `IterableDataset`, `n` times the dataset is iterated on main process and then it broadcasts the corresponding batches to each of the `n` GPUs. Accelerate handles the synchronisation of random number generators across processes under the hood for enabling above functionalities.
