### ISSUE TITLE
How to run `run_mlm_no_trainer.py` with specific GPUs ?

### ISSUE THREAD

**Issue by reshinth-adith** [huggingface/accelerate#368]
Hello, Thanks for this awesome library. I found that [run_mlm_no_trainer.py](https://github.com/huggingface/transformers/blob/main/examples/pytorch/language-modeling/run_mlm_no_trainer.py) is recently ported to accelerate. What is the right way to run the script with specific GPUs(say `1,2,3`) in a `1,2,3,4,5,6,7,8` GPUs present.
Thanks.

**Comment by sgugger** [comment]
Please use the [forums](https://discuss.huggingface.co/) to ask questions as we keep issues for bugs and feature requests only.

As for your question, use the env variable `CUDA_VISIBLE_DEVICES` to set the GPUs you want to use:
```
CUDA_VISIBLE_DEVICES="1,2,3" accelerate launch run_mlm_no_trainer.py ...
```
