### ISSUE TITLE
Multi machine training not working

### ISSUE THREAD

**Issue by Fengdalu** [huggingface/accelerate#37]
I am trying to run my training code on 2 machines. Each of them has 2 GPUs. However, it seems the program runs separately and do not fasten the training progress. Here is my `config.yaml`

machine 1:

```
compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
fp16: true
machine_rank: 0
main_process_ip: 192.168.0.1
main_process_port: 99999
main_training_function: main
num_machines: 2
num_processes: 4

```

machine 2:

```
compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
fp16: true
machine_rank: 1
main_process_ip: 192.168.0.1
main_process_port: 99999
main_training_function: main
num_machines: 2
num_processes: 4

```

**Comment by sgugger** [comment]
The two configs look right to me. Are you launching your script with `accelerate launch` afterward on both machines? What do you mean the programs run separately and do not fasten the training progress?

**Comment by Fengdalu** [comment]
> The two configs look right to me. Are you launching your script with `accelerate launch` afterward on both machines? What do you mean the programs run separately and do not fasten the training progress?

I run `accelerate launch` in both two machines and the program runs as same as the single machines. The number of batches and total duration of each epoch do not change. Will be `accelerator` wait until all machines start?

**Comment by sgugger** [comment]
Normally you shouldn't see anything until all machines have started, yes.

**Comment by sgugger** [comment]
Oh I can reproduce and I found the cause, the config arguments are not all passed properly to the launcher :facepalm: A fix is on its way!

**Comment by sgugger** [comment]
Could you check again with a source install that everything works properly now?

**Comment by Fengdalu** [comment]
> Could you check again with a source install that everything works properly now?

I reinstall accelerate from Github version. The training stop at the `accelerator = Accelerator()`. It seems PyTorch keeps waiting for all machines. 

Here is my config
machine 1:

```
compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
fp16: true
machine_rank: 0
main_process_ip: 192.168.0.1
main_process_port: 2333
main_training_function: main
num_machines: 2
num_processes: 4
```

machine 2:

```

compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
fp16: true
machine_rank: 1
main_process_ip: 192.168.0.1
main_process_port: 2333
main_training_function: main
num_machines: 2
num_processes: 4
```

**Comment by zhuhaonan** [comment]
> Oh I can reproduce and I found the cause, the config arguments are not all passed properly to the launcher facepalm A fix is on its way!

Hello, could you release a new pip version? I have a same problem, it seems that pip version can't multi machine training.

**Comment by sgugger** [comment]
Yes, you need a source install for now. There will be a new release before the end of the week!

**Comment by thakursc1** [comment]
@sgugger does the latest release have this update ? I am still facing this issue.

**Comment by sgugger** [comment]
Yes it should be fixed with the latest release. If you have a problem, please open a new issue with the command you are running and the results you get.
