### ISSUE TITLE
how to use Accelerate in distributed data parallel traning

### ISSUE THREAD

**Issue by SiyuanWei** [huggingface/accelerate#41]
By simply adding a few lines of codes as the readme shows, I can not use all the gpus in a DDP way
![image](https://user-images.githubusercontent.com/20530918/115847718-cfc67f80-a455-11eb-912c-21de57d00a3b.png)

**Comment by philschmid** [comment]
Hey @SiyuanWei, 

Could you please add your `accelerate` config and how you installed `accelerate`? 

You find the config under `~/.cache/huggingface/accelerate/default_config.yaml` if you haven't changed the cache dir or saved it elsewhere.

**Comment by SiyuanWei** [comment]
Hi,my Accelerate config is as following:
![image](https://user-images.githubusercontent.com/20530918/115850838-de626600-a458-11eb-8332-814e57fa05b5.png)
I install it by pip3 and use it by adding sample codes as the readme shows and launching "python3 train.py"

**Comment by philschmid** [comment]
are you launching it with `python3 train.py` or with `accelerate launch train.py`?

**Comment by SiyuanWei** [comment]
python3 train.py~ should I use "accelerate launch train.py"?

**Comment by philschmid** [comment]
Yes, you need to use `accelerate launch train.py`. Accelerate will then use your configuration and initializes the correct setup and executes your script.  

As feedback and for improvement, was that not clear enough documented [here](https://github.com/huggingface/accelerate#launching-script)?

**Comment by SiyuanWei** [comment]
Hi, I've tried this and it works as you said! Thanks a lot!!

**Comment by philschmid** [comment]
Perfect! Your welcome! Feel free to close the issue then.
