### ISSUE TITLE
AcceleratedOptimizer `zero_grad` argument not supported: `set_to_none`

### ISSUE THREAD

**Issue by lengstrom** [huggingface/accelerate#42]
Currently the `AcceleratedOptimizer` class doesn't support the argument `set_to_none`, is this an intentional exclusion?

**Comment by sgugger** [comment]
It's not intended, I actually wasn't aware PyTorch had added it in 1.7.0. Will just need to be careful to only accept it when the version of PyTorch is recent enough but support for it should be pretty straightforward otherwise!

**Comment by sgugger** [comment]
This should be fixed by the PR mentioned above and you can test with a source install. Don't hesitate to reopen the issue if you still have trouble with this!

**Comment by lengstrom** [comment]
Awesome thanks for the quick turnaround time!

**Comment by vblagoje** [comment]
I raised it https://github.com/NVIDIA/apex/issues/1196 I've seen also a few other LAMB optimizers out there and they simply inherit from PyTorch Optimizer and don't implement zero_grad method. Therefore I doubt this problem is widespread.
