### ISSUE TITLE
`psutil` required by utils/modeling.py but it isn't delayed a

### ISSUE THREAD

**Issue by willfrey** [huggingface/accelerate#444]
### System Info

```Shell
Accelerate `0.10.0.dev0` on Debian Bullseye running Python 3.10.5.


File "/opt/venv/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 276, in get_max_memory
    import psutil
ModuleNotFoundError: No module named 'psutil'
```

I'm not sure if you have any minimum version you need to satisfy for `psutil` as a runtime dependency but I see that there are no constraints on it as a `test` dependency in setup.py.

If you don't have any requirements, I'm happy to just add it myself and open a patch PR.

Thanks!
```


### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

Use `device_map="auto"` when loading any model that supports it.

### Expected behavior

```Shell
I expect that `psutil` is declared as a runtime dependency of the `accelerate` package instead of having to install it myself.
```

**Comment by sgugger** [comment]
It is already in our extra "tests" (see [here](https://github.com/huggingface/accelerate/blob/29eef234c9151ed4b11632ee15d356b0aea9c20c/setup.py#L22)), did you mean that you'd like it in the main dependencies?

**Comment by willfrey** [comment]
Yes, since it's required for some runtime functionality in at least one place.

**Comment by willfrey** [comment]
Thank you!
