### ISSUE TITLE
Best practice to load only the model weights from an Accelerator.save_state() checkpoint?

### ISSUE THREAD

**Issue by LoganWalls** [huggingface/accelerate#446]
Hello,

First off, thank you for the great library! It is making life a lot easier for me so far.

I have a training script that uses `Accelerator.save_state()` to save checkpoints during training, but I would like to load only the model weights from these checkpoints in a separate script so that I can e.g. generate samples, or do offline evaluations at each checkpoint. Is there a recommended method for this?

I am mostly confused about when/whether I need to use `Accelerator.unwrap_model()`. (To be clear, I want to be able to resume training using the checkpoints, so I don't to unwrap the model before saving – unless that's what is recommended, in which case I am not sure how to use the unwrapped model to resume training).

Thank you for your help!

**Comment by muellerzr** [comment]
You'd follow the torch docs for this [here](https://pytorch.org/tutorials/beginner/saving_loading_models.html#saving-loading-model-for-inference)

E.g.:
```python
# Assume model is prepared from accelerate.prepare, etc
model.load_state_dict(torch.load(input_model_file, map_location="cpu"))
```

`input_model_file` looks like so:

```python
accelerate.save_state("my_folder_name")
input_model_file = "my_folder_name/pytorch_model.bin"
```
And if you have multiple models stored/registered as part of accelerate, its `"my_folder_name/pytorch_model_{i}.bin"`

**Comment by LoganWalls** [comment]
Ah, great. Thank you very much!
