### ISSUE TITLE
Multi-GPU inference issues (device map assignment and unused but reserved GPU memory)

### ISSUE THREAD

**Issue by hepengfe** [huggingface/accelerate#448]
### System Info

```Shell
- `Accelerate` version: 0.9.0
- Platform: Linux-5.13.0-44-generic-x86_64-with-debian-bullseye-sid
- Python version: 3.7.0
- Numpy version: 1.21.5
- PyTorch version (GPU?): 1.10.2+cu113 (True)
- `Accelerate` default config:
        Not found
```

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

Referring the notebook below and running it with my GPU settings: 3 x A6000 (48GB)
https://colab.research.google.com/drive/14wnxMvD9zsiBQo2FtTpxn6w2cpXCcb-7#scrollTo=Q0Zf_d5RhVpO&uniqifier=1

I tried model OPT-30b on multi-GPU but it gives OOM error.
* `infer_auto_device_map` doesn't give a consistent result in some runs. Sometimes it gives `decoder` = 0 sometimes it gives a detailed decoder layer's device map.
       * for `decoder` = 0 case, it will not use other GPUs. But rather move rest layers (not in the first GPU) to CPU. 
       * for a detailed decoder layer's device map, if it uses other GPUs, run `model.generate()` will report error `RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking argument for argument mat2 in method wrapper_mm)`
* For the environment variable `CUDA_VISIBLE_DEVICES`, although invisible gpus' memory are not used but the memory are reserved for some reason.

### Expected behavior

```Shell
* `infer_auto_device_map` should give a consistent result given the same RAM/GPU configuration. Also it should consider the memory size occupied by input data.
* When multiple GPUs are assigned in device_map, the `model.generate()` should work without error.
* invisible gpus' memory shoudn't be reserved.
```

**Comment by hepengfe** [comment]
I think the first issue is mentioned here https://github.com/huggingface/accelerate/issues/362
Only the second issue about reserved GPU memory needs to be addressed now.

**Comment by sgugger** [comment]
Please provide a reproducer for your issue as we can't help you without reproducing it.
