### ISSUE TITLE
Saving the entire model

### ISSUE THREAD

**Issue by ushakovegor** [huggingface/accelerate#449]
Hello,
I try to use Animus with Accelerator. Recently, I have faced with problem with saving model. There are two ways of saving model: state_dict and entirely. For the first method I used 
` model_to_save = self.engine.unwrap_model(self.model).state_dict()`
` self.engine.wait_for_everyone()`
` self.engine.save(model_to_save, "path_to_model")`
And it was done good. But I need to save the entire model like [here](https://pytorch.org/tutorials/beginner/saving_loading_models.html#save-load-entire-model). I have tried to use these:
` model_to_save = self.engine.unwrap_model(self.model)`
` self.engine.wait_for_everyone()`
` torch.save(model_to_save, "path_to_model")`
But I have this error:
`Can't pickle <function HeatmapDetector.forward at 0x7fac2fd6ff40>: it's not the same object as animus.models.detectors.heatmap.HeatmapDetector.forward`
Could you please help me with that?

**Comment by sgugger** [comment]
Hi there! This is not related to Accelerate, which does not define a `HeatmapDetector` class. In general it's not recommended to try to pickle the whole models (for issues like this) but to save its `state_dict`. As for fixing the problem with `HeatmapDetector`, I'd raise the issue in `animus`.

**Comment by ushakovegor** [comment]
Hi. `HeatmapDetector` is just a `torch.nn.Module` and don't depend from Animus. I assume that problem may be in Accelerator.

**Comment by ushakovegor** [comment]
I have found that using `mixed_precision="fp16"` provide crushes of `torch.save`.

**Comment by sgugger** [comment]
And also, as the bug template asks, please copy-paste the result of `accelerate env` so we know which version of the library you're using.
