### ISSUE TITLE
Add Apple's M1 metal integration

### ISSUE THREAD

**Issue by Rexhaif** [huggingface/accelerate#453]
It would be nice to have an option to use accelerate with pytorch's MPS backend.

Recent addition of accelerated pytorch training on Mac [https://pytorch.org/blog/introducing-accelerated-pytorch-training-on-mac/](https://pytorch.org/blog/introducing-accelerated-pytorch-training-on-mac/) enabled Mac-users to train pytorch models with speed comaprable to some old-generation Nvidia GPUs. 

Integration is fairly simple - instantiate mps device and move model/tensors to it, see details [here](https://pytorch.org/docs/master/notes/mps.html?highlight=mps).

**Comment by fcakyon** [comment]
@sgugger it is now live in pytorch 1.12 :rocket:  https://pytorch.org/docs/stable/notes/mps.html
