### ISSUE TITLE
Very poor performance on two RTX 3060

### ISSUE THREAD

**Issue by fireindark707** [huggingface/accelerate#455]
### System Info

Hi, I used the Transformers [example code](https://github.com/huggingface/transformers/tree/main/examples/pytorch/text-classification) (which uses accelerate) to test the GPUs‘ performances. It turns out that for the text classification task, a single GPU can achieve a speed of 2.82 iters per second, but if I use 2 GPUs for distributed training, the speed can only reach 1 iter per second. Moreover, I tried to reduce the batch size, but the result was still slow.

Since the 3060 does not support NVLINK, I would like to ask if pytorch's distributed training can only run on graphics cards that support NVLINK? Or, how do I check for this error. Thanks.

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

Run the example script on two 3060 GPU

### Expected behavior

```Shell
Faster speed
```

**Comment by fireindark707** [comment]
In addition, I found some interesting phenomena, when two GPUs are working in parallel, their usage is not always 100%, but constantly jumping between 20% and 100%. This may mean that they are spending time waiting for each other.

**Comment by fireindark707** [comment]
Here is the performance of 2 GPUs (20 samples per batch on each GPU)
```
***** train metrics *****
  epoch                    =        3.0
  train_loss               =     0.4375
  train_runtime            = 0:06:15.83
  train_samples            =       3668
  train_samples_per_second =     29.279
  train_steps_per_second   =      0.734
```

**Comment by sgugger** [comment]
Please follow the issue template, in particular copy and paste the result of `accelerate env` and if not using the default config, the config you are using, as well as the launch command for the script, so we can investigate more.
