### ISSUE TITLE
Variables or Operations to identify rank at the begining of the program

### ISSUE THREAD

**Issue by sailist** [huggingface/accelerate#46]
I need to identify the `main` or `first` process to do something(for example, log) at the begining of the program, but I can't find any variables that can make it. 

Only after some module/dataloader/optimzer is prepared by `accelerator.prepare()`, then `torch .distributed.get_rank()` can be used to do it.

Are there any other variables or operations(like an empty prepare() function) can help me get a flag to distinguish these process at program begin?

Any suggestion?

**Comment by sailist** [comment]
I got it, `os.environ.get('LOCAL_RANK',-1)`

**Comment by sgugger** [comment]
You can also look at `accelerator.is_main_process` (only true for one process) or `accelerator.process_index` for the specific index of a given process.

**Comment by sailist** [comment]
> You can also look at `accelerator.is_main_process` (only true for one process) or `accelerator.process_index` for the specific index of a given process.

thanks! That's what I want!

**Comment by jubueche** [comment]
How do I map `accelerator.process_index` to the actual device I am using? I guess `accelerator.process_index` is always relative and starts at zero, but sometimes I am just making devices 1,2,3 visible (and not 0).

**Comment by muellerzr** [comment]
Not sure we *can* easily, you can check `torch.cuda.get_device_name()` or `torch.cuda.current_device()`
