### ISSUE TITLE
[QUESTION] Why do we reinit `AcceleratorState` everytime we prepare an object again?

### ISSUE THREAD

**Issue by amaarora** [huggingface/accelerate#47]
Hey @sgugger ! 

Thanks for the clean & concise code. I love it! 

Could I please ask what's the idea behind initializing `state=AcceleratorState()` inside `prepare_data_loader` [here](https://github.com/huggingface/accelerate/blob/main/src/accelerate/data_loader.py#L353) again? 

In which case would this condition `if num_processes is None:` or `if process_index is None:` be True please? As I understand inside the Accelerator we have already set `state=AcceleratorState()` which sets the variables `num_processes`, `process_index` etc based on the config. 

So why do need to initialize `AcceleratorState` again please?

**Comment by sgugger** [comment]
Please use the [forums](https://discuss.huggingface.co/c/accelerate/) for general questions :-)

The `AcceleratorState` is a special class: there can only be one instance of it. The first time it's initialized, every other call won't do anything, just give an `AcceleratorState` with the same state. So it's completely harmless to instantiate it multiple times.

As for your second question, it depends on what could call the `prepare_data_loader` in the future. For now, it's only called by the `Accelerator` with all the arguments set but a user could import it and use it differently, or the library could call it in a different context in the future.

**Comment by sgugger** [comment]
Closing the issue, let's continue the discussion on the [forums](https://discuss.huggingface.co/c/accelerate/18)!
