### ISSUE TITLE
Niche case with device_map=auto

### ISSUE THREAD

**Issue by younesbelkada** [huggingface/accelerate#473]
### System Info

```Shell
accelerate==0.10.0
```

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

```
from transformers import AutoModelForCausalLM

model = AutoModelForCausalLM.from_pretrained("/gpfsscratch/rech/six/commun/opt/opt-175b", device_map="auto", torch_dtype=torch.float16)
vec = torch.LongTensor([[1]*156]).cuda()

model(vec)
```

This throws a CUDA OOM error simply because it is a very niche case where the GPUs were maxed out just right on their capacity, even if the other GPUs are free. 
The actual strategy for getting the `device_map` is to max-out the available GPUs. Can we get another strategy let's say `equivalent` that dispatch the model into equivalent chunks on available GPUs? Or is there a way to directly give a value for `max_memory` when loading the model ? 
Thanks a lot 🙏 

### Expected behavior

```Shell
A working inference without CUDA OOM errors
```

**Comment by sgugger** [comment]
You can specify the `max_memory` when using `from_pretrained` (see the [doc](https://huggingface.co/docs/transformers/main_classes/model#transformers.PreTrainedModel.from_pretrained)).

**Comment by younesbelkada** [comment]
You are totally right, sorry for the confusion and thanks for the help!
