### ISSUE TITLE
Invalid parameter passing in launcher 

### ISSUE THREAD

**Issue by Fengdalu** [huggingface/accelerate#48]
https://github.com/huggingface/accelerate/blob/548109297be89208fc94957724015d311150e595/src/accelerate/commands/launch.py#L143

The `--node_rank` is duplicated. It should be changed to `--master_port`

```
        cmd.extend(
            [
                "--nproc_per_node",
                str(args.num_processes // args.num_machines),
                "--nnodes",
                str(args.num_machines),
                "--node_rank",
                str(args.machine_rank),
                "--master_addr",
                args.main_process_ip,
                "--master_port",
                str(args.main_process_port),
            ]
```

**Comment by sgugger** [comment]
Very very good point! Thanks a lot for spotting this. I'm opening a PR, I'll put you as co-author as you found the fix.

**Comment by sgugger** [comment]
Should be fixed by [this commit](https://github.com/huggingface/accelerate/commit/0d0985fd1070e07542e81d9c7ef1e61e4f6a0241), which also removed the duplicate `--nproc_per_node`.

My setup for multinode test crashed so trying to figure out a new one to make sure it did solve the issue this time. Please let me know if you still have the problem.

**Comment by sgugger** [comment]
Ok, rebuilt my testing environment for multinode GPU training and it worked perfectly (using the master branch of the library with all the last fixes). Let me know if the issue is solved for you too!

**Comment by Fengdalu** [comment]
> Ok, rebuilt my testing environment for multinode GPU training and it worked perfectly (using the master branch of the library with all the last fixes). Let me know if the issue is solved for you too!

The issue is already solved in my environment, thanks for testing and quick response.
