### ISSUE TITLE
Loading Big Model exceed max_memory

### ISSUE THREAD

**Issue by agemagician** [huggingface/accelerate#483]
### System Info

```Shell
- `Accelerate` version: 0.11.0.dev0
- Platform: Linux-5.4.188+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.7.13
- Numpy version: 1.21.6
- PyTorch version (GPU?): 1.11.0+cu113 (True)
- `Accelerate` default config:
	Not found
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

https://colab.research.google.com/drive/1lh9rduNcnGNPHgqWfgTmRK_5k51gF75q?usp=sharing

### Expected behavior

```Shell
When using "max_memory" parameter, the script should only use the specified max memory. However, it exceed the max_memory parameter and consumes the whole memory, then it crashes Colab.

Any idea why it doesn't respect the parameter?
```

**Comment by agemagician** [comment]
@sgugger Do you have any idea what is the issue here?

**Comment by sgugger** [comment]
You need to also activate `offload_state_dict=True` to not go above the max memory on CPU: when loading your model, the checkpoints take some CPU RAM when loaded (the size of the checkpoint or each shard of the checkpoint if the checkpoint is shared) + the space taken by the weights on CPU.

To limit this to the size of the checkpoint/checkpoint shard, `offload_state_dict=True` will offload the weights that will eventually be on the CPU during the load time, then put them back once the state dict are not in CPU RAM anymore, so this will limit your RAM usage further.

**Comment by agemagician** [comment]
> On my side it crashes because there is not enough disk space left to offload the weights, nothing linked to `max_memory` being exceeded. I don't think you will be able to load that model in Colab free without using FP16 (but then predictions are crappy in FP16 because this specific model was trained on TPU). Colab pro might let you have higher RAM/a bigger disk.

Hmmm, I have Colab Pro+, and I am using the standard memory, which has a lot of HDD space.
It doesn't crash because of the HDD storage, since there is enough storage, but it crashes because of the RAM.

It does work when I use a High memory environment in Colab Pro+, so I can confirm it is a problem with memory.
Maybe, it will crash first if there is not enough hdd space, but since it is not a problem for me, then it crash if there is not enough RAM.

**Comment by agemagician** [comment]
Hmmm, Good point, but in Colab there is free 12GB of memory which should fit each shard file.

More details :
Colab CPU doesn't work even there is enough memory to load the shard file:
Memory: 12GB Free Memory .
HDD: 140GB Free Disk Space
Shard File: 10GB
Max Memory: 11GB

#```
 Load 45 GB Model  -> 11 Billion Model
model = AutoModelForSeq2SeqLM.from_pretrained(
  "bigscience/T0pp",
  revision="sharded",
  device_map="auto",
  offload_state_dict=True,
  #max_memory={0: "11GIB", "cpu": "11GIB"},
  max_memory={"cpu": "11GIB"},
  offload_folder="/content/offload_folder",
)
```

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
[<ipython-input-7-6a6a84c1e707>](https://localhost:8080/#) in <module>()
      7   #max_memory={0: "4GIB", "cpu": "4GIB"},
      8   max_memory={"cpu": "11GIB"},
----> 9   offload_folder="/content/offload_folder",
     10 )

2 frames
[/usr/local/lib/python3.7/dist-packages/transformers/models/auto/auto_factory.py](https://localhost:8080/#) in from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
    444         elif type(config) in cls._model_mapping.keys():
    445             model_class = _get_model_class(config, cls._model_mapping)
--> 446             return model_class.from_pretrained(pretrained_model_name_or_path, *model_args, config=config, **kwargs)
    447         raise ValueError(
    448             f"Unrecognized configuration class {config.__class__} for this kind of AutoModel: {cls.__name__}.\n"

[/usr/local/lib/python3.7/dist-packages/transformers/modeling_utils.py](https://localhost:8080/#) in from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
   2141         # Dispatch model with hooks on all devices if necessary
   2142         if device_map is not None:
-> 2143             dispatch_model(model, device_map=device_map, offload_dir=offload_folder)
   2144 
   2145         if output_loading_info:

[/usr/local/lib/python3.7/dist-packages/accelerate/big_modeling.py](https://localhost:8080/#) in dispatch_model(model, device_map, main_device, state_dict, offload_dir, offload_buffers, preload_module_classes)
    210 
    211     if main_device is None:
--> 212         main_device = [d for d in device_map.values() if d not in ["cpu", "disk"]][0]
    213 
    214     cpu_modules = [name for name, device in device_map.items() if device == "cpu"]

IndexError: list index out of range
```


Colab GPU doesn't work even there is enough memory to load the shard file:
GPU: V100 16 GB Free Memory.
Memory: 12GB Free Memory .
HDD: 140GB Free Disk Space
Shard File: 10GB
Max Memory: 11GB

```
# Load 45 GB Model  -> 11 Billion Model
model = AutoModelForSeq2SeqLM.from_pretrained(
  "bigscience/T0pp",
  revision="sharded",
  device_map="auto",
  offload_state_dict=True,
  max_memory={0: "11GIB", "cpu": "11GIB"},
  #max_memory={"cpu": "11GIB"},
  offload_folder="/content/offload_folder",
)
```

`Your session crashed after using all available RAM. [Get more RAM](javascript:void(0))`

**Comment by xnohat** [comment]
I success load big model on Colab Pro with this guide from Huggingface

https://huggingface.co/docs/transformers/big_models
https://huggingface.co/docs/accelerate/big_modeling

```
model = AutoModelForCausalLM.from_pretrained("bigscience/bloom-6b3", torch_dtype=torch.float16, use_cache=True, low_cpu_mem_usage=True) #torch_dtype=torch.float32 for CPU only, on CPU require use float32 (full-precision) because CPU only accept float32 registers, torch_dtype=torch.float16 for CUDA only, on CUDA use float16 (half precision) to accelerate generation and optimize memory consumption on GPU

import os
import tempfile

offload_dir='/content/offload'
os.makedirs(offload_dir) if not os.path.exists(offload_dir) else None

with tempfile.TemporaryDirectory() as tmp_dir:
    model.save_pretrained(tmp_dir, max_shard_size="200MB")
    print('Temp Dir Path:', tmp_dir)
    print(sorted(os.listdir(tmp_dir)))
    new_model = AutoModelForCausalLM.from_pretrained(tmp_dir, low_cpu_mem_usage=True, device_map="auto", offload_folder=offload_dir)
```

**Comment by jagadeeshi2i** [comment]
@agemagician Were you able load the model. I am running into the same error.

**Comment by lilong669** [comment]
hI , I think you do not split the model into small pieces try the code when you save your model .
 `model.save_pretrained(save_path, max_shard_size="2GB")`
