### ISSUE TITLE
Cannot run distributed training on sagemaker

### ISSUE THREAD

**Issue by plamb-viso** [huggingface/accelerate#492]
I know that distributed data parallelism in the actual accelerate library is still underdevelopment, but per the HF/AWS webinar here https://youtu.be/vEuJBdnb_uM?t=1153 all I should need to do to launch a fully utilized distributed sagemaker job is pass a well formed `distribution` dict to a `sagemaker.huggingface.HuggingFace` estimator with an appropriate instance.

I'm currently running a job like this

```python
distribution = {
    'smdistributed': {
        'dataparallel': {'enabled': True }
    }
}

estimator = HuggingFace(
                      image_uri=image_uri,
                      role=role.arn,
                      train_instance_count=1,
                      train_instance_type="ml.p3dn.24xlarge",
                      volume_size_in_gb=50,
                      max_run=(24*60*60),
                      hyperparameters=hyperparameters,
                      base_job_name=JOB_NAME,
                      distribution=distribution,
                      py_version='py36',
                      entry_point='./container/layoutlmv2/train.py'
                      )

 estimator.fit()
```
The only difference between my job and the youtube video is that I'm passing a custom image_uri to the estimator.

My train.py file sets up accelerator as follows:

```python
...
accelerator = Accelerator()
...
train_dataloader, valid_dataloader, model, optimizer, lr_scheduler = accelerator.prepare(
        train_dataloader, valid_dataloader, model, optimizer, lr_scheduler
    )

print("Accelerator has determined the num processes to be: ", accelerator.num_processes)
```

Now the specified instance is an appropriate instance and has the following attributes:
```
#   name        GPUS    Mem     Type  
# p3dn.24xlarge 8       32GB    V100       
```

Except when execution reaches that print statement I get back:

```
Accelerator has determined the num processes to be:  1
```
What am I missing to make accelerator work across multiple GPUs on a single AWS instance?

**EDIT**
I noticed that the provided [HF training DLC](https://github.com/aws/deep-learning-containers/blob/master/huggingface/pytorch/training/docker/1.9/py3/cu111/Dockerfile.trcomp.gpu) installs Horovod. Is this the missing piece? Would just adding these lines to my custom container solve it?

```dockerfile
# Install Horovod
ENV HOROVOD_VERSION=0.21.3
RUN pip uninstall -y horovod \
 && ldconfig /usr/local/cuda-11.1/targets/x86_64-linux/lib/stubs \
 && HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_CUDA_HOME=/usr/local/cuda-11.1 HOROVOD_WITH_PYTORCH=1 pip install --no-cache-dir horovod==${HOROVOD_VERSION} \
 && ldconfig
```

**Comment by sgugger** [comment]
SageMaker DataParallel as you are using is not supported yet in Accelerate (it's actually something @pacman100 will be working on in the coming weeks). I think the webinar was mentioning the use of the Transformers Trainer, which fully support SageMaker DataParallel.

Long story short, SageMaker DataParallel uses its own `torch.distributed` module, so here Accelerate sees one process in `torch.distributed` as it's not looking into the right place. If you remove 
```
distribution = {
    'smdistributed': {
        'dataparallel': {'enabled': True }
    }
}
```
then your job should use the regular `torch.distributed` and run fine.

Also cc @philschmid for information.

**Comment by plamb-viso** [comment]
@sgugger do you mean remove the `distribution` param and add something like this to the training dockerfile?

```dockerfile
ENTRYPOINT [ \
    "python3.9", \
    "-m", \
    "torch.distributed.launch", \
    "--nproc_per_node", \
    "8", \
    "--use_env", \
    "/opt/ml/code/train.py" \
]
```

**Comment by plamb-viso** [comment]
@philschmid I'm going to give this a try; are there any added dependencies that should be in the docker container in addition to 
```
accelerate
accelerate[sagemaker]
torch+cu111
torchvision+cu111
```
for `accelerate launch ...` to work?

**Comment by plamb-viso** [comment]
For those that find this, I ran accelerate launch locally and then copied the config file to my docker container and added this line:

```dockerfile
ENTRYPOINT [ \
    "accelerate", \
    "launch", \
    "--config_file", \
    "/opt/ml/code/multi_gpu_config.yaml", \
    "/opt/ml/code/train.py" \
]
```

**Comment by plamb-viso** [comment]
@pacman100 in theory should this work with a custom `image_uri` or do I have to use HF's DLC? If it can, is there any dependency that must be copied out of HF's DLC (for e.g. the Horovod dependency)?

**Comment by plamb-viso** [comment]
@pacman100 wouldnt one need to extend HF's DLCs anyway since they don't install `accelerate` ?

https://github.com/aws/deep-learning-containers/blob/master/huggingface/pytorch/training/docker/1.10/py3/cu113/Dockerfile.trcomp.gpu
