### ISSUE TITLE
Possible to download training data in `is_main_process()` and "send" it to workers?

### ISSUE THREAD

**Issue by plamb-viso** [huggingface/accelerate#496]
It may be that I'm simply missing the idiomatic way to use accelerate, but my instinct was to try downloading my data from s3 in the main process so its only downloaded once and then my thought was that `.prepare()` would appropriately "send" the data to my GPUs.
 
To achieve this:

`accelerate launch --config_file /opt/ml/code/multi_gpu_config.yaml /opt/ml/code/train.py`

```python
accelerator = Accelerator()
if accelerator.is_main_process:
   # download data 
   # create dataloaders
   # get the model
   # create the optimizer/lr_scheduler

accelerator.wait_for_everyone()

train_dataloader, valid_dataloader, model, optimizer, lr_scheduler = accelerator.prepare(
        train_dataloader, valid_dataloader, model, optimizer, lr_scheduler
    )

# train
```
Of course when execution reaches the `.prepare()` statement, the other (in my case 7) processes do not have access to these variables.

If I remove the `.is_main_process()` guard, the data is downloaded in all 8 processes. Is that what I should be expecting? Does `.prepare()` some how coordinate sharding across all the copies?

**Comment by sgugger** [comment]
While you should definitely download your data on the main process only, you need to create your datasets and dataloaders on all processes afterward. Your processes share the file storage, but they can't share objects. So all the variables need to be defined in all of them.

**Comment by sgugger** [comment]
You can even go shorter with:
```
with accelerator.main_process_first():
    dataset = load_from_disk(encoded_data_path, fs=s3fs)
```
which does exactly what you typed before.
