### ISSUE TITLE
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one.

### ISSUE THREAD

**Issue by plamb-viso** [huggingface/accelerate#497]
I am currently getting the error in the issue topic when running my accelerate job. I've modeled my training loop as closely to

https://github.com/huggingface/accelerate/blob/main/examples/complete_nlp_example.py

as possible.

I'm kicking off an accelerate job across 8 GPUS as follows:

`accelerate launch --config_file /opt/ml/code/multi_gpu_config.yaml /opt/ml/code/train.py`

The beginning of my training loop looks like:

```python
accelerator = Accelerator()
...
train_dataloader, valid_dataloader, model, optimizer, lr_scheduler = accelerator.prepare(
    train_dataloader, valid_dataloader, model, optimizer, lr_scheduler
)
...
# We need to keep track of how many total steps we have iterated over
overall_step = 0
# We also need to keep track of the stating epoch so files are named properly
starting_epoch = 0

for epoch in range(starting_epoch, hyperparams['epochs']):
    accelerator.print("\n--Epoch: " + str(epoch) + "--\n")
    model.train()
    total_loss = 0
    for step, batch in enumerate(train_dataloader):
        outputs = model(**batch)
        loss = outputs.loss
        loss = loss / gradient_accumulation_steps
        total_loss += loss.detach().float()
        accelerator.backward(loss)
        if step % gradient_accumulation_steps == 0:
            optimizer.step()
            lr_scheduler.step()
            optimizer.zero_grad()

        overall_step += 1
```

I've traced execution and can confirm it makes it through one iteration of `for step, batch in enumerate(train_dataloader):` and then errors out on `outputs = model(**batch)` on the second iteration.

I've seen a few pytorch threads on this issue, but nothing immediately illuminating. One solution that has worked for some people is passing `find_unused_parameters=True` to `DistributedDataParallel()`, but I would need to pass this through accelerate somehow i believe. Do the accelerate folks know how to solve this?

**EDIT**
I just found this in the test files:
```python
ddp_scaler = DistributedDataParallelKwargs(bucket_cap_mb=15, find_unused_parameters=True)
accelerator = Accelerator(kwargs_handlers=[ddp_scaler])
```
Might be the solution but still curious to hear from Accelerate folks

**Comment by plamb-viso** [comment]
I implemented the above solution,

```python
ddp_scaler = DistributedDataParallelKwargs(bucket_cap_mb=15, find_unused_parameters=True)
accelerator = Accelerator(kwargs_handlers=[ddp_scaler])
```
and it worked

**Comment by neel04** [comment]
import:
```py
from accelerate.utils import DistributedDataParallelKwargs
```
saved you a couple mins 😉
