### ISSUE TITLE
[typo] Example should be accelerator

### ISSUE THREAD

**Issue by voidful** [huggingface/accelerate#5]
I found a typo in the documentation.
In the model backward section, it should be `accelerator` instead of `accelerate`

According to the Readme example https://github.com/huggingface/accelerate/blob/main/README.md, all
```
accelerate.backward(loss)
```
should be
```
accelerator.backward(loss)
```

I appreciate this work to make distributed training easier.

**Comment by sgugger** [comment]
Thanks for flagging! Will fix tomorrow but if you want to open a PR to fix it first, don't hesitate!

**Comment by sgugger** [comment]
Fixed by #6
