### ISSUE TITLE
Fix formatting of Accelerator docs

### ISSUE THREAD

**Issue by nateraw** [huggingface/accelerate#507]
The accelerator docs are formatted in a way that is a bit confusing. Attributes show up as functions, which if you copy+paste, are wrong. On [this page](https://huggingface.co/docs/accelerate/accelerator#accelerate.Accelerator) you can see that `is_main_process` shows up as `is_main_process()`, etc. Would be nice if these attributes don't get auto formatted as functions.

**Comment by muellerzr** [comment]
CC @sgugger, this would probably come from autodoc + `@property` decorator I think.

**Comment by nateraw** [comment]
Looks like everything's merged and we're just waiting for a re-deploy. Closing this and will reopen if it persists. Thank you @sgugger + @muellerzr !! ❤️
