### ISSUE TITLE
Torch Geometric compatibility

### ISSUE THREAD

**Issue by MilesCranmer** [huggingface/accelerate#51]
Hi,

Awesome package, I'm really liking how easy it is to plug-and-play in my training scripts.

Would it be possible to have compatibility with PyTorch geometric? (graph neural networks, etc). torch geometric uses a custom collate function in their DataLoader to deal with graph-like data, so right now putting it into the `Accelerator` gives this error upon iterating:
```python
TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'torch_geometric.data.data.Data'>
```

Here is the relevant code: https://github.com/rusty1s/pytorch_geometric/blob/480f9d59d6d18166a5da2e2519fa9a6b33d3d4ad/torch_geometric/data/dataloader.py#L8-L70

Thanks!
Miles

**Comment by sgugger** [comment]
Hi there! Could you share how you created the data loader that returned this error? Looking at the code, Accelerate should honor the special data collator (it keeps the one in the data loader you pass to `prepare_data_loader`). You might lose the attributes `follow_batch` and `exclude_keys` but that's something we can easily add in Accelerate.

**Comment by MilesCranmer** [comment]
Sorry, it turns out I made a really dumb mistake (unrelated to accelerate). Looks like it already works well! Nice job.

Sorry for posting the issue!
Cheers,
Miles
