### ISSUE TITLE
how to use ray tune with accelerate

### ISSUE THREAD

**Issue by DogeWatch** [huggingface/accelerate#515]
I want to do hyperparameters finetuning with accelerate, use like the ray tune, is there some example code?

**Comment by sgugger** [comment]
There is no example yet, if you want to contribute one, by all means :-)

**Comment by ayulockin** [comment]
Hey @DogeWatch were you able to perform hyperparameters finetuning with accelerate using ray tune? :)

**Comment by fzyzcjy** [comment]
Hi, is it possible to use ray tune with hf accelerate? Thanks!
