### ISSUE TITLE
Slurm support 

### ISSUE THREAD

**Issue by eliahuhorwitz** [huggingface/accelerate#518]
Hey,
I am wondering if you accelerate supports SLURM and if so, how does one run accelerate on slurm in a multi GPU setting?
Thanks,
Eliahu

**Comment by eliahuhorwitz** [comment]
Thanks for the quick answer!
I am using a repo that was written with accelerate but using a slurm cluster. Assuming I am successful in launching the code with `torch.distributed.launch`, should the current code written with the accelerate API support it, or will I need to refactor the code to support PyTorch DDP?

**Comment by sgugger** [comment]
It should all work as long as you can launch it!

**Comment by eliahuhorwitz** [comment]
Perfect, thanks!

**Comment by ZhiyuanChen** [comment]
Could you please reopen this issue?
I think I can work on this, maybe we can have some configuration worth the help of submitit

**Comment by eliahuhorwitz** [comment]
> Could you please reopen this issue?
> I think I can work on this, maybe we can have some configuration worth the help of submitit

Reopened, thanks!
