### ISSUE TITLE
Question: Does Accelerate support pipeline parallelism?

### ISSUE THREAD

**Issue by wookjeHan** [huggingface/accelerate#537]
I want to implement pipeline parallelism for large language(does not fit to single gpu) models pretrained and saved in huggingface hub.

Does accelerate support pipeline parallelism for large LM saved in huggingface hub?

I'm also wondering whether is there any stronger way than pipeline parallelism to make large LM that does not fit to single gpu to load in multi gpu?

**Comment by sgugger** [comment]
Please use the [forums](https://discuss.huggingface.co/) for questions like this :-) 
Accelerate does not support pipeline parallelism for models yet.

**Comment by wookjeHan** [comment]
Thanks!
