### ISSUE TITLE
Mixed Precision: AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by satpalsr** [huggingface/accelerate#549]
### System Info

```Shell
- `Accelerate` version: 0.11.0
- Platform: Linux-5.4.188+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.7.13
- Numpy version: 1.21.6
- PyTorch version (GPU?): 1.12.0+cu113 (False)
- `Accelerate` default config:
	Not found
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

Error:
```
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 684, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 280, in simple_launcher
    mixed_precision = PrecisionType(args.mixed_precision.lower())
AttributeError: 'NoneType' object has no attribute 'lower'
```

Reproduce: Follow example commands from [Diffusers](https://github.com/huggingface/diffusers/tree/main/examples#training-examples)

1. ```pip install diffusers[training] accelerate datasets```
2. 
```
accelerate launch train_unconditional.py \
  --dataset="huggan/flowers-102-categories" \
  --resolution=64 \
  --output_dir="ddpm-ema-flowers-64" \
  --train_batch_size=16 \
  --num_epochs=100 \
  --gradient_accumulation_steps=1 \
  --learning_rate=1e-4 \
  --lr_warmup_steps=500 \
  --mixed_precision=no \
  --push_to_hub
  ```
  
  **More Info**:    
 Instead of training script mixed precision argument, default argument value is used causing the issue. [Link to line](https://github.com/huggingface/accelerate/blob/e98dc22a37d6f51f111dee3e5a919d4e022f4fe9/src/accelerate/commands/launch.py#L293)   
 No default value is set for mixed precision causing it to be None. [Link to line](https://github.com/huggingface/accelerate/blob/e98dc22a37d6f51f111dee3e5a919d4e022f4fe9/src/accelerate/commands/launch.py#L185)
  

### Expected behavior

```Shell
Expected the mixed precision value to be taken from the training script instead of the None value.
```

**Comment by sgugger** [comment]
You need to run `accelerate config` before being able to use `accelerate launch`.

**Comment by satpalsr** [comment]
Ouch! Thanks @sgugger

**Comment by sgugger** [comment]
Otherwise, you can pass it before the training script (but it's easier to just run `accelerate config`  ;-) 
```
accelerate launch --mixed_precision=no train_unconditional.py ...
```
