### ISSUE TITLE
how to use evaluate with accelerate

### ISSUE THREAD

**Issue by fcakyon** [huggingface/accelerate#574]
I couldn't find a full tutorial on using accelerate with evaluate metrics. Can you help me on this issue: https://github.com/huggingface/evaluate/issues/208

**Comment by muellerzr** [comment]
There's an example here: https://github.com/huggingface/accelerate/blob/main/examples/by_feature/multi_process_metrics.py

**Comment by fcakyon** [comment]
> Calling compute() resets the stored predictions/labels etc

Thanks a lot that answers my question!

**Comment by fcakyon** [comment]
> Though take care that you should probably use gather_for_metrics if you're building from main.

I am using the latest release, what would I miss by using `gather` instead of `gather_for_metrics`?

**Comment by muellerzr** [comment]
The code block here explains it. https://github.com/huggingface/accelerate/blob/main/examples/by_feature/multi_process_metrics.py#L182-L194

**Comment by fcakyon** [comment]
OK I remember this [twit thread](https://twitter.com/TheZachMueller/status/1550085911303430144) :+1: Thanks for all the explanations!
