### ISSUE TITLE
Unexpected behaviors with DispatchDataloader

### ISSUE THREAD

**Issue by muellerzr** [huggingface/accelerate#585]
### System Info

```Shell
- `Accelerate` version: 0.12.0.dev0
- Platform: Linux-5.10.0-16-cloud-amd64-x86_64-with-debian-11.4
- Python version: 3.7.12
- Numpy version: 1.19.5
- Transformers version: 4.21.0.dev0
- PyTorch version (GPU?): 1.12.0+cu113 (True)
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: no
        - use_cpu: False
        - num_processes: 2
        - machine_rank: 0
        - num_machines: 1
        - main_process_ip: None
        - main_process_port: None
        - main_training_function: main
        - deepspeed_config: {}
        - fsdp_config: {}
        - downcast_bf16: False
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

1. Check out the `metrics-evaluation` branch
2. Run `pip install -e .; pip install fastcore`
3. Setup config like mine
4. `accelerate launch nlp_example.py` (this will save the final model into an `nlp_example` folder)
6. Run `cd examples; accelerate launch evaluation.py --dispatch_batches --split_batches`

### Expected behavior

I'd expect Dispatched Batches to not make me require two behaviors. 

First, when calculating the final metrics it seems we shouldn't adjust the final batch based on the number of samples. i.e. don't do:

```python
if not dispatch_batches:
    samples_seen += references.shape[0]
    if step == (len(dataloader) - 1):
        preds = preds[: len(dataloader.dataset) - samples_seen]
        references = references[: len(dataloader.dataset) - samples_seen]
```

Is this intentional?

And second, when running with just `dispatch_batches`, I get a size mismatch error when the dataloader length is not perfectly the size of a batch. This is also the case if `drop_last=True` because that drop last seems to get ignored from what I could quickly see. 

Stack trace:
```bash
Running baseline
Len dl: 25
Len dset: 408

Running with basic distributed setup
Traceback (most recent call last):
  File "evaluation.py", line 48, in <module>
    split_batches: bool = False,  # Whether to split batches
  File "/opt/conda/lib/python3.7/site-packages/fastcore/script.py", line 122, in call_parse
    return _f()
  File "/opt/conda/lib/python3.7/site-packages/fastcore/script.py", line 117, in _f
    tfunc(**merge(args, args_from_prog(func, xtra)))
  File "evaluation.py", line 75, in main
    for step, batch in enumerate(dataloader):
  File "/home/zach_mueller_huggingface_co/accelerate/src/accelerate/data_loader.py", line 478, in __iter__
    batch, batch_info, skip = self._fetch_batches(main_iterator)
  File "/home/zach_mueller_huggingface_co/accelerate/src/accelerate/data_loader.py", line 443, in _fetch_batches
    batch = concatenate(batches, dim=0)
  File "/home/zach_mueller_huggingface_co/accelerate/src/accelerate/utils/operations.py", line 375, in concatenate
    return type(data[0])({k: concatenate([d[k] for d in data], dim=dim) for k in data[0].keys()})
  File "/home/zach_mueller_huggingface_co/accelerate/src/accelerate/utils/operations.py", line 375, in <dictcomp>
    return type(data[0])({k: concatenate([d[k] for d in data], dim=dim) for k in data[0].keys()})
  File "/home/zach_mueller_huggingface_co/accelerate/src/accelerate/utils/operations.py", line 378, in concatenate
    return torch.cat(data, dim=dim)
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 81 but got size 76 for tensor number 1 in the list.
```

**Comment by Aman-4-Real** [comment]
I have the same problem that `"Sizes of tensors mismatch"` when I generate sentences during validation of a training process. Sometimes it works well but other cases result in the mismatch bug on generated sequence length (like `RuntimeError: Sizes of tensors must match except in dimension 1. Got 150 and 129 (The offending index is 0)`). I also tried both `accelerator.gather()` and `accelerator.gather_for_metrics()` but it still does not work.
