### ISSUE TITLE
How to use data visualization API with accelerate.tracking?

### ISSUE THREAD

**Issue by zh-plus** [huggingface/accelerate#592]
The accelerate.tracking API only supports `accelerator.log`, which can be used to log key-value pairs. 

However, we can't use `accelerator` to visualize the data and predictions. For example, in [wandb docs](https://wandb.ai/stacey/mnist-viz/reports/Visualize-Predictions-over-Time--Vmlldzo1OTQxMTk), we need `wandb.run.log_artifact(test_data_at)` to sync the visualization table. 

In https://github.com/huggingface/accelerate/blob/29a222a2619a56636cc80fe62ba2e925f3f5d064/src/accelerate/tracking.py#L193 the `self.run` is initialized and used in log function like this: https://github.com/huggingface/accelerate/blob/29a222a2619a56636cc80fe62ba2e925f3f5d064/src/accelerate/tracking.py#L224

Right now if I want to access `self.run` (suppose I just use wandb), we need to iterate all the trackers in `Accelerator` like this:
```
wandb_run = accelerator.trackers[0].run
wandb_run.log_artifact(test_data_at)
```
It is kind of weird to access the internal list. Can we add a function in `Accelerator` such that `accelerator.wandb_run()` return the `accelerator.trackers[0].run`? The same as `accelerator.tensorboard_writer()` and `accelerator.cometml_writer()`.

**Comment by muellerzr** [comment]
Thanks! Should be good now with https://github.com/huggingface/accelerate/pull/594 now 😄
