### ISSUE TITLE
Running with Pycharm debugger

### ISSUE THREAD

**Issue by SeoHyeong** [huggingface/accelerate#593]
I'm trying to run a script with accelerate on Pycharm debugger. I've come across [issue-535](https://github.com/huggingface/accelerate/issues/535) and followed the steps. However, I'm getting the following lines of error.

`Traceback (most recent call last):
  File "/home/envs/HF/lib/python3.7/site-packages/accelerate/commands/launch.py", line 280, in simple_launcher
    mixed_precision = PrecisionType(args.mixed_precision.lower())
AttributeError: 'NoneType' object has no attribute 'lower'
python-BaseException`

Do I need additional parameters when running with module accelerate.commands.launch?

<img width="1101" alt="Screen Shot 2022-08-02 at 4 13 38 PM" src="https://user-images.githubusercontent.com/27022196/182314669-dd7d0222-dc47-480f-b7d6-a6efeb5641bd.png">

**Comment by muellerzr** [comment]
You need to still configure accelerate. Run `accelerate config` from thr CLI. This error will be much more clear in the next release.

**Comment by SeoHyeong** [comment]
Thanks for the comment! 

I configured running `accelerate config`. However, I'm getting another error as follows. Though it seems like either python `subprocess` error or a compatibility problem between `accelerate` and `subprocess`, I'm sharing the error message here in case you've seen something similar before. 

`Traceback (most recent call last):
  File "/home/.conda/envs/ltr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/home/.conda/envs/ltr/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'torchrun': 'torchrun'
python-BaseException`

**Comment by muellerzr** [comment]
Is pytorch installed? How did you install accelerate?

**Comment by SeoHyeong** [comment]
Pytorch is installed. I installed accelerate through `pip install accelerate` and ran `accelerate config` right after.

**Comment by sunformoon** [comment]
@SeoHyeong 
Has you solved the `"FileNotFoundError: [Errno 2] No such file or directory: 'torchrun': 'torchrun'"` error?
