### ISSUE TITLE
`DataLoaderShard` returns `None` batch

### ISSUE THREAD

**Issue by fcakyon** [huggingface/accelerate#601]
Hello, I have a design-related question.

Because of this line: https://github.com/huggingface/accelerate/blob/8944975a3c8db55f57774e9e566e7a791be766cb/src/accelerate/data_loader.py#L351 accelerate dataloader occasionally (after 1 epoch, i.e when dataset iterations exhaust) returns `None` batch. Is it expected? Should I add a check in my training loop that skips when the batch is `None`?

There is no such check in examples so I am wondering if I am missing anything.

**Comment by muellerzr** [comment]
This only occurs at the very first batch of a dataloader iteration (i.e. start of `iter()`), and it's only there in case you can't actually iterate over an iterate dataset at all (it has no batches), so we return nothing since we could grab nothing. 

So if it happens only occasionally then it may be something different?

**Comment by fcakyon** [comment]
I have a `torch.utils.data.IterableDataset` named `LabeledVideoDataset`, I am converting it to a `torch.utils.data.Dataset` as:

```python
class TrainDatasetWrapper(torch.utils.data.Dataset):
    def __init__(self, dataset, dataset_multiplier: int = 1):
        super().__init__()
        self._dataset = dataset
        self.dataset_multiplier = dataset_multiplier
        self.dataset_iter = None

    def __getitem__(self, index):
        if self.dataset_iter is None:
            self.dataset_iter = itertools.chain.from_iterable(
                itertools.repeat(iter(self._dataset), self.dataset_multiplier)
            )
        return next(self.dataset_iter)

    def __len__(self):
        return self._dataset.num_videos * self.dataset_multiplier
```

but the dataset gets exhausted after an epoch and returns `None` batch. Should I manually init dataset iter when batch is `None`?

**Comment by fcakyon** [comment]
I could not find any solution so reimplemented my dataset class as IterableDataset now everything is working crystal clear 👍

**Comment by mufernando** [comment]
@fcakyon can you point me to your solution to this issue? Thank you!
