### ISSUE TITLE
Infer auto device map fills up GPUs too much

### ISSUE THREAD

**Issue by jesbu1** [huggingface/accelerate#608]
Currently, when using `device_map="auto"` during instantiation of large language models in the transformers library, accelerate seems to essentially fill up GPUs' RAM such that, depending on the model and GPUs, a moderate batch size (e.g. 8) will cause a CUDA out of memory error.

Is there a way for accelerate to take a target batch size parameter with a specified number of tokens parameter so that it can try to ensure this doesn't happen? Or perhaps just a maximum memory % of free space accelerate will leave available on each GPU. Right now the number of bytes of GPU memory must be provided on a per-GPU basis, manually.

### Reproduction

Use transformers `AutoModelForCausalLM.from_pretrained("facebook/opt-33b", device_map="auto")` 

Then:
1. call `model.generate()` on a small batch size

### Expected behavior

```Shell
CUDA OOM error for certain configurations of GPUs and small-moderate batch sizes.
```

**Comment by sgugger** [comment]
On the main branch of Transformers, `device_map="auto"` will evenly spread your models on the GPUs so you have space left to use a bigger batch size (as long as you have enough GPU memory). For generation, you can also use `device_map="balanced_low_0"`, which will keep the maximum amount of space it can on GPU 0, which require a bit more space since the generation happens there.

**Comment by jesbu1** [comment]
I have noticed that for example, on my RTX 3090 machines, a GPT-J model with device map auto will be stored all on one card even when there are multiple GPUs available, with device map auto on the latest transformers release. This leaves little room for a larger batch size.

Is that the intended behavior of device map auto? I will also try “balanced_low_0”, thanks.

**Comment by sgugger** [comment]
> on the latest transformers release
I said on the main branch, not the latest release. You need to do a source install.

**Comment by jesbu1** [comment]
Got it, device map auto seems to be working as described on the main branch of transformers. Thanks!
