### ISSUE TITLE
Link between source code and documentation incorrect (documentation issue)

### ISSUE THREAD

**Issue by clefourrier** [huggingface/accelerate#615]
### System Info

```Shell
- System info not relevant
- doc at main
- source at main
```

### Information

- [x] The official example scripts

### Tasks

- [x] Documentation

### Reproduction

Hi! 
The doc "source" links of Accelerate are not sending to the proper place in the source code. 
For example, "source" button of https://huggingface.co/docs/accelerate/main/en/accelerator#accelerate.Accelerator.prepare (far right in the capture) redirects to https://github.com/huggingface/accelerate/blob/main/src/accelerate/accelerator.py#L554 which is about 10 lines above the relevant function `prepare`.

![image](https://user-images.githubusercontent.com/22726840/183579864-b8e4590c-2128-4cd4-82cf-efb9f839003b.png)

### Expected behavior

```Shell
The source button should send to the correct place in code.
```

**Comment by sgugger** [comment]
Thanks a lot for flagging!

Looks like the documentation build has been silently failing for a while, even if it shows green ticks. That's why those links are out of date. Will take a closer look this morning!

**Comment by sgugger** [comment]
Aaaaah! You are looking at the wrong page (how did you get there?) This one is thus not updated anymore and the correct one has the proper link: https://huggingface.co/docs/accelerate/main/en/package_reference/accelerator#accelerate.Accelerator.prepare

**Comment by clefourrier** [comment]
Got here with my "search engines redirect me to weird doc places" problem ^^"
Thank you for the link, issue closable on my side then!
