### ISSUE TITLE
Warning message for multi-gpu configuration incorrect

### ISSUE THREAD

**Issue by ezhang7423** [huggingface/accelerate#621]
### System Info

```Shell
accelerate==0.12.0
torch==1.12.1
numpy==1.23.1
python version: 3.8.5
OS: Ubuntu 18.04

accelerate config:

compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: MULTI_GPU
downcast_bf16: 'no'
fsdp_config: {}
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
mixed_precision: 'no'
num_machines: 1
num_processes: 2
use_cpu: false
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

1. Set accelerate distributed type to MULTI_GPU
2. Run `accelerate launch --num_processes *1* <script>`

The issue is [line 818](https://github.com/huggingface/accelerate/blob/4df9010b70479ef59314fa7f10c96c03f556a2b4/src/accelerate/commands/launch.py#L818). and [line 797](https://github.com/huggingface/accelerate/blob/4df9010b70479ef59314fa7f10c96c03f556a2b4/src/accelerate/commands/launch.py#L797) in `src/accelerate/commands/launch.py`. This will output that the configuration variable was not set, even though it clearly has been and rather is invalid with MULTI_GPU.

### Expected behavior

The existing message can lead to confusion and wasted time. I would suggest either throwing an error here or changing the logic of the warning here to reflect what has actually happened.

**Comment by muellerzr** [comment]
@ezhang7423 this should have been fixed via https://github.com/huggingface/accelerate/pull/907, can you try again?
