### ISSUE TITLE
Outside of venv?

### ISSUE THREAD

**Issue by jt4186** [huggingface/accelerate#64]
I'm interested in using this on a jupyterhub machine, which is a single node.  Do you expect that to have any issues?  I can only assume the recommendation to use a virtual environment is for package compatibility, which I'm comfortable with sorting through in the base jupyterhub environment.

**Comment by sgugger** [comment]
There shouldn't be any issue, the virtual env recommendation is just for package compatibility as you mentioned.

**Comment by jt4186** [comment]
Excellent.  Thank you.
