### ISSUE TITLE
Accelerator starting multiple wandb runs

### ISSUE THREAD

**Issue by ezhang7423** [huggingface/accelerate#644]
Hi there! I may be doing something wrong, but when I call `accelerator.init_trackers` in my main function, I get N different runs for each process. Is this the expected behavior?

**Comment by muellerzr** [comment]
@ezhang7423 a pr was just merged to adjust this. But if you peek at the examples currently you'll see it's done under an `if accelerator.is_main_process` first. (Next release will do this automatically)

**Comment by Gladiator07** [comment]
Hi @ezhang7423, you should do a source install of accelerate and that issue should be fixed.
`pip install git+https://github.com/huggingface/accelerate`

**Comment by ezhang7423** [comment]
This works for me now!
