### ISSUE TITLE
getting error while training LayoutLMV2 model on multi gpu setup

### ISSUE THREAD

**Issue by sujit420** [huggingface/accelerate#648]
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by 
making sure all `forward` function outputs participate in calculating loss. 
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameters which did not receive grad for rank 0: layoutlmv2.pooler.dense.bias, layoutlmv2.pooler.dense.weight, layoutlmv2.visual.backbone.fpn_output5.bias, layoutlmv2.visual.backbone.fpn_output5.weight, layoutlmv2.visual.backbone.fpn_output4.bias, layoutlmv2.visual.backbone.fpn_output4.weight, layoutlmv2.visual.backbone.fpn_output3.bias, layoutlmv2.visual.backbone.fpn_output3.weight
Parameter indices which did not receive grad for rank 0: 16 17 20 21 24 25 510 511
Traceback (most recent call last):
  File "LayoutLMv2 Best Model - 0.7873 - Finetuning on LS Internal All Data.py", line 788, in <module>
    outputs = model(**train_batch)
  File "/root/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/py38/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 873, in forward
    if torch.is_grad_enabled() and self.reducer._rebuild_buckets():
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by 
making sure all `forward` function outputs participate in calculating loss. 
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameters which did not receive grad for rank 1: layoutlmv2.pooler.dense.bias, layoutlmv2.pooler.dense.weight, layoutlmv2.visual.backbone.fpn_output5.bias, layoutlmv2.visual.backbone.fpn_output5.weight, layoutlmv2.visual.backbone.fpn_output4.bias, layoutlmv2.visual.backbone.fpn_output4.weight, layoutlmv2.visual.backbone.fpn_output3.bias, layoutlmv2.visual.backbone.fpn_output3.weight
Parameter indices which did not receive grad for rank 1: 16 17 20 21 24 25 510 511

I am following the guide here: https://huggingface.co/docs/transformers/accelerate

Can anyone help??

**Comment by muellerzr** [comment]
@sujit420 as the error states it wants you to pass in `find_unused_params=True`. These are from the DDP kwargs and you can pass them in when building your `Accelerator` object: https://huggingface.co/docs/accelerate/package_reference/kwargs#accelerate.DistributedDataParallelKwargs

Can you try the following when declaring your Accelerator?

```python
from accelerate import DistributedDataParallelKwargs
accelerator = Accelerator(kwargs_handlers=DistributedDataParallelKwargs(find_unused_parameters=True)
```

**Comment by sujit420** [comment]
> 
Thanks a lot @muellerzr  for help.
Any idea how to do inference?
I am saving model via:
'''
accelerator.wait_for_everyone()
accelerator.unwrap_model(model)
accelerator.save_state('output/model_epoch_' + str(epoch))
'''
But if I load the model for prediction using:
'''
finetuned_model = accelerator.load_state(model_finteuned_path)
'''
it returns me empty object.
<img width="203" alt="Screenshot 2022-08-23 at 8 25 26 PM" src="https://user-images.githubusercontent.com/15769598/186191172-00c0c206-21cb-4bb2-babe-979956ae42aa.png">
this is how model is saved.

**Comment by muellerzr** [comment]
@sujit420 you should just do `accelerate.save` and pass in everything like you would when doing torch.save.

If it's a transformers model, there's examples in the no_trainer script on how to use save_pretrained here: https://github.com/huggingface/transformers/blob/main/examples/pytorch/text-classification/run_glue_no_trainer.py#L578-L583

**Comment by sujit420** [comment]
Thanks, @muellerzr for the prompt response. It was constructive.

**Comment by nbroad1881** [comment]
For anyone looking at this, the code to solve this problem is now:

```python
accelerator = Accelerator(kwargs_handlers=[DistributedDataParallelKwargs(find_unused_parameters=True)])
```

**Comment by AisingioroHao0** [comment]
@muellerzr Hi, I used this method to solve the problem, but the batch size had to be reduced. Originally, a single gpu could have a batch size of 10. But now the double gpu cases, a gpu seemingly can only take 4 batch size. Is that normal? Do not meet my understanding

**Comment by AisingioroHao0** [comment]
@muellerzr On first reading, it seems find_unused_parameters incurs extra overhead in some models. Is there any way to fix this, I'm using CLIPVisionModel from huggingface transformers
