### ISSUE TITLE
Feature request: Add support for NamedTuples in dataloaders

### ISSUE THREAD

**Issue by PhilMacKay** [huggingface/accelerate#65]
In order to produce self-documenting code, our team has the habit of using NamedTuples instead of plain tuples as the return type of our datasets.

Since they are sub-classes of tuples, they are handled by every PyTorch mechanism we've encountered as if they are tuple, so it all works smoothly.

When using Accelerate, I get an error in `send_to_device` at line 114. `type(tensor)(send_to_device(t, device) for t in tensor)` raises a type error because `type(tensor)` returns my NamedTuple, which cannot use the generator `(send_to_device(t, device) for t in tensor)` as argument. We would need some way to transform the generator into a type that is accepted by the NamedTuple.

**Comment by sgugger** [comment]
Added support in the PR mentioned above!
