### ISSUE TITLE
Multiple dataloaders support

### ISSUE THREAD

**Issue by cyk1337** [huggingface/accelerate#653]
Hi @sgugger , does `accelerate.prepare` support multiple dataloaders for multi-node distributed training ? Since I need to sample batches from 100+ different datasets. 
```bash
dataloader1, dataloader2, ..., dataloader200=accelerate.prepare(dataloader1, dataloader2, ..., dataloader200)
```
When generating batch in distributed training , it got stuck. Any solution to it?

**Comment by cyk1337** [comment]
@pacman100

**Comment by sgugger** [comment]
You can send as many dataloaders as you want to the `prepare` method as long as you unpack them in the same order as you send them.
