### ISSUE TITLE
CUDA_VISIBLE_DEVICES ignored by DeepSpeed

### ISSUE THREAD

**Issue by scuyjzh** [huggingface/accelerate#663]
![image](https://user-images.githubusercontent.com/12816241/187153512-0b194917-7dbc-4ec3-9c2c-3e8164990318.png)

![image](https://user-images.githubusercontent.com/12816241/187154056-a0a34793-749e-4121-99ff-f2a0010718ee.png)

![image](https://user-images.githubusercontent.com/12816241/187153780-207a70ff-ed74-47a8-b0cf-6b3775231c37.png)

Detected CUDA_VISIBLE_DEVICES=2,4,5,7 but ignoring it because one or several of --include/--exclude/--num_gpus/--num_nodes cl args were used. If you want to use CUDA_VISIBLE_DEVICES don't pass any of these arguments to deepspeed.

How can I solve this problem?

**Comment by pacman100** [comment]
Hello @scuyjzh, please use the [forum](https://discuss.huggingface.co/c/accelerate/18) for such questions which aren't bugs/feature requests. Please try PR #626 and let us know if that solves the above problem

**Comment by YouJiacheng** [comment]
@pacman100 I tested that v0.13.0 solves this problem.
