### ISSUE TITLE
not able to launch accelerate in notebook with 2 processes

### ISSUE THREAD

**Issue by sujit420** [huggingface/accelerate#664]
I have 2 GPU setups but I am not able to launch training using accelerate on both GPUs. However, it works on a single GPU.
notebook_launcher(training_function, (model,), num_processes=1)

Can anyone help?

**Comment by muellerzr** [comment]
Can you please provide the full error, your environment, and how you setup your notebook? You should have been prompted to do so when opening your issue. We can't help otherwise

**Comment by sujit420** [comment]
> Can you please provide the full error, your environment, and how you setup your notebook? You should have been prompted to do so when opening your issue. We can't help otherwise

Launching training on 2 GPUs.
  0%|          | 0/418 [00:00<?, ?it/s]
---------------------------------------------------------------------------
ProcessExitedException                    Traceback (most recent call last)
/tmp/ipykernel_11960/4075470079.py in <module>
      1 from accelerate import notebook_launcher
      2 
----> 3 notebook_launcher(training_function, (model,), num_processes=2)

~/py38/lib/python3.8/site-packages/accelerate/launchers.py in notebook_launcher(function, args, num_processes, use_fp16, mixed_precision, use_port)
    125 
    126                 print(f"Launching training on {num_processes} GPUs.")
--> 127                 start_processes(launcher, args=args, nprocs=num_processes, start_method="fork")
    128 
    129         else:

~/py38/lib/python3.8/site-packages/torch/multiprocessing/spawn.py in start_processes(fn, args, nprocs, join, daemon, start_method)
    186 
    187     # Loop on join until it returns True or raises an exception.
--> 188     while not context.join():
    189         pass
    190 

~/py38/lib/python3.8/site-packages/torch/multiprocessing/spawn.py in join(self, timeout)
    128             if exitcode < 0:
    129                 name = signal.Signals(-exitcode).name
--> 130                 raise ProcessExitedException(
    131                     "process %d terminated with signal %s" %
    132                     (error_index, name),

ProcessExitedException: process 0 terminated with signal SIGSEGV

**Comment by muellerzr** [comment]
Can you confirm it works when on a single worker? Also we need to know your environment. Please post the output of `accelerate env`

**Comment by sujit420** [comment]
> accelerate env

Yes, it works on a single worker using notebook_launcher(training_function, (model,), num_processes=1)
below is output from accelerate env:
- `Accelerate` version: 0.12.0
- Platform: Linux-5.4.0-88-generic-x86_64-with-glibc2.29
- Python version: 3.8.10
- Numpy version: 1.21.3
- PyTorch version (GPU?): 1.10.0+cu111 (True)
- `Accelerate` default config:
        Not found

**Comment by muellerzr** [comment]
I can run the `notebook_launcher` just fine using the example you linked, so it seems to be stemming from your code. 

Could you open a new discussion [here](https://discuss.huggingface.co/c/accelerate/18) to help you a bit more with your specific issue? And if possible please include the notebook you are using. Otherwise we have nothing to go off of to help you 😃
