### ISSUE TITLE
find a dead loop in the code

### ISSUE THREAD

**Issue by jcyk** [huggingface/accelerate#678]
https://github.com/huggingface/accelerate/blob/60d6807c36e968282221c500927079d752da8662/src/accelerate/data_loader.py#L481-L484

As seen, if `stop_iteration`  is `False` and `next_skip` is `True`, this is a dead loop. I encountered this problem in my training, did not figure out the logics. please help.

**Comment by sgugger** [comment]
Thanks for reporting! This should be addressed by the PR above!

**Comment by jcyk** [comment]
Thanks!
