### ISSUE TITLE
question about amp

### ISSUE THREAD

**Issue by gunwook-datab** [huggingface/accelerate#68]
hello. I'm very excited for using this library.

I have a question. can it use with torch.amp?

I want to use both library for training!

thanks!

**Comment by Guptajakala** [comment]
@sgugger if I dont set `fp16` on the Accelerator side, will the accelerater's loss backward handle it correctly (e.g. unscaling)? Or do I need torch's original scaler to handle it?

**Comment by muellerzr** [comment]
Yes, it will handle the unscaling

**Comment by Guptajakala** [comment]
I noticed [here](https://github.com/huggingface/accelerate/blob/main/src/accelerate/accelerator.py#L1996) that only when `self.scaler` has been specified will accelerator handle the unscaling. But this is only when fp16 enabled (https://github.com/huggingface/accelerate/blob/main/src/accelerate/accelerator.py#L462). Did I miss anything?
@muellerzr

**Comment by muellerzr** [comment]
Nope
