### ISSUE TITLE
`notebook_launcher` cannot use MPS device on M1 or M2 Mac

### ISSUE THREAD

**Issue by faraday** [huggingface/accelerate#692]
### System Info

```Shell
- `Accelerate` version: 0.13.0.dev0
- Platform: macOS-12.5.1-arm64-arm-64bit
- Python version: 3.10.4
- Numpy version: 1.23.1
- PyTorch version (GPU?): 1.13.0.dev20220909 (False)
- `Accelerate` default config:
	- compute_environment: LOCAL_MACHINE
	- distributed_type: MPS
	- mixed_precision: no
	- use_cpu: False
	- num_processes: 1
	- machine_rank: 0
	- num_machines: 1
	- main_process_ip: None
	- main_process_port: None
	- rdzv_backend: static
	- same_network: False
	- main_training_function: main
	- deepspeed_config: {}
	- fsdp_config: {}
	- downcast_bf16: no
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

Steps to reproduce:
1. Stable Diffusion Textual Inversion Colab script: https://colab.research.google.com/github/huggingface/notebooks/blob/main/diffusers/sd_textual_inversion_training.ipynb
2. Run script on M1 Max, expecting `accelerate.notebook_launcher` to report running the training on *GPU (or MPS)*
3. Observe it runs the training on *CPU* instead

### Expected behavior

```Shell
With a previous PR, `mps` M1 GPU support was introduced to Accelerate: https://github.com/huggingface/accelerate/pull/596

However `notebook_launcher` needs to be adapted to make use of this change as well.
```

**Comment by pacman100** [comment]
Hello @faraday, thank you for bringing this to the notice. The above PR should fix it.
