### ISSUE TITLE
nlp example doesn't run faster with multi-gpu

### ISSUE THREAD

**Issue by cccntu** [huggingface/accelerate#71]
I am running the example on 2080ti, where each epoch takes 21 seconds with 1 GPU. When using 2 GPUs, it also takes 21 seconds. (I used tqdm to measure the time)
Everything looks right: GPU utilization is ~100% in both GPUs, the # of batch per device is halved, but it's not faster.
I tried the cv example, and using 2 GPUs does speed up the training. 

Is this normal? What might be the cause of this?

**Comment by sgugger** [comment]
Are your GPU linked with an NVlink? If not, the communication between them can slow things down quite a bit and result in this slowdown. In general don't expect your training to go exactly 2x faster (it should be a little bit faster but it's not linear).

**Comment by cccntu** [comment]
nvidia-smi nvlink says `<inactive>`, so I guess not. 
I stumbled upon this issue https://github.com/huggingface/transformers/issues/9371, saying multi-GPU could even be slower than single GPU, maybe it happens that the 2 effects cancel each other in this case.

**Comment by sgugger** [comment]
Yes, this issue has a very nice table that summarizes all results!

**Comment by cccntu** [comment]
Thanks! Closing now.

**Comment by Ruiyuan-Zhang** [comment]
<img width="592" alt="image" src="https://user-images.githubusercontent.com/71813586/203489036-f4a30eb7-801a-4f66-ada5-1075cc3c08f1.png">
