### ISSUE TITLE
How to train on multiple models

### ISSUE THREAD

**Issue by hbwu-ntu** [huggingface/accelerate#720]
Hi, I have two models, A and B. I want to use accelerate for training, and only the parameters of B will be updated. Can I just initialize a new model, called MainModel, which includes A and B?

For para in A, I do 
for param in MainModel.A.parameters():
       param.requires_grad = False
I initialize an optimizer,
   optimizer = torch.optim.AdamW(
        model.B.parameters(),  # only optimize the B
    )
Then I set 
model, optimizer, train_dataloader = accelerator.prepare(
        model, optimizer, train_dataloader
    )

Then I start training. Is this solution okay?
Thanks for your help.

**Comment by sgugger** [comment]
This should work yes! Also please post questions like this on our [forums](https://discuss.huggingface.co/) instead of opening as issues, as we use them for feature requests and bugs only.
