### ISSUE TITLE
using `accelerate` in a SLURM environment

### ISSUE THREAD

**Issue by deven-gqc** [huggingface/accelerate#730]
Hello,

A member in our team has access to a compute cluster and we wish to use `accelerate` in that environment to accomplish distributed training across multiple GPUs. 

However, the documentation on the [accelerate config](https://huggingface.co/docs/accelerate/v0.12.0/en/package_reference/cli#accelerate-config) page is a little confusing for me. 

Here are a few questions
1. if I have multi-gpu selected as yes, does that mean `--num_processes == no of GPUs`?
2. `--num_cpu_threads_per_process -- The number of CPU threads per process. Can be tuned for optimal performance.` -- can someone explain this a little further? Does this mean, a single py file would be run on multiple threads in parallel?

Let me know, if I should move this into the forums or the the Discord channel. TIA!

**Comment by pacman100** [comment]
Hello @deven-gqc,


Forum would be the correct place for above queries. As for your questions
1. with `multi-gpu`, it is usually equal to the number of GPUs on a machine * number of machines.
2. `num_cpu_threads_per_process` is mainly for multi-cpu scenario and to parallelize CPU intensive tasks across CPU cores, e.g., data tokenization.

 
Sylvain and Zach would be able to add more context.
