### ISSUE TITLE
Add context to to move tensors within multiple submodel devices without intrusion

### ISSUE THREAD

**Issue by piEsposito** [huggingface/accelerate#743]
**Is your feature request related to a problem? Please describe.**
In some cases, to enable models to run on very small GPUs, we can keep just the heavy one (let's say the UNet on Stable Diffusion, for example) on the GPU and keep the other, lighter ones, on CPU. The problem is that, when we do such thing, we would need to manually enter the submodels code and move the intermediate results between devices.

This solution is not optimal, as what I tried to do at https://github.com/huggingface/diffusers/pull/537 to solve https://github.com/huggingface/diffusers/issues/540.

I can work on that and open a PR if you would let me.

**Describe the solution you'd like**
I would solve this by creating an `accelerate` context that will handle moving tensors between submodules and submodels (from `transformers` and `diffusers`) without having to intrude the models and pipeline code.

```python
with accelerate.move_between_devices():
    pipeline("a photograph of an astronaut riding a horse")
```

**Describe alternatives you've considered**
- Move tensors between devices on the model code
- Do not move tensors between devices at all

**Additional context**
Adding this feature would enable solving https://github.com/huggingface/diffusers/issues/540 in a very elegant way.

**Comment by piEsposito** [comment]
@patrickvonplaten (I'm tagging you because you usually answer my issues and PRs) an I open a PR to add this feature?

**Comment by sgugger** [comment]
There is no need for adding a context manager as this is already handle by accelerate with [`dispatch_model`](https://github.com/huggingface/accelerate/blob/693d46826e32507376d44f99967df4710886c984/src/accelerate/big_modeling.py#L204).

**Comment by piEsposito** [comment]
Thanks, that will solve my problem.
