### ISSUE TITLE
how to turn off accelerate?

### ISSUE THREAD

**Issue by shizhediao** [huggingface/accelerate#75]
when I want to run my program without accelerate, I just type in "python my_file" instead of "accelerate launch my_file".
However, my program got stuck. 
Could you help me? Thanks!

**Comment by sgugger** [comment]
Just running with python son't do anything distributed, so the failure should be in your script. It's hard to help without seeing it and the stack trace though.

**Comment by shizhediao** [comment]
Thanks for your reply!
I am using the same script from https://github.com/huggingface/transformers/blob/master/examples/pytorch/language-modeling/run_clm_no_trainer.py 
Firstly, I can run 'python run_clm_no_trainer.py' well without 'accelerate config'.
Then I tried 'accelerate config' and 'accelerate launch', it works well.
However, when I turn back to 'python run_clm_no_trainer.py', I encountered the problem.

**Comment by shizhediao** [comment]
![image](https://user-images.githubusercontent.com/18120087/117683751-f53de200-b1e6-11eb-95dc-c90cca788461.png)
As you can see from this figure, it stuck at loading data

**Comment by shizhediao** [comment]
oh, I found it is related to "PYTHONUNBUFFERED".
If I am running my python file with "PYTHONUNBUFFERED=1 python xxx.py", it works well.
But if without it, it will stuck.
Is it just a printing issue?

**Comment by sgugger** [comment]
I must say I haven't seen this before, but yes, it does look like just a printing issue (e.g. the script runs fine but stops printing on the console).
