### ISSUE TITLE
device_map dictionary corruption in diffusers tests possibly caused by accelerate?

### ISSUE THREAD

**Issue by Thomas-MMJ** [huggingface/accelerate#750]
I suspect, but am not sure, that this is an accelerate bug

https://github.com/huggingface/diffusers/issues/790

Running the following series of pytests in the diffusers head, triggers the last two of the accelerate tests to fail, due to a corrupted device_map dictionary.

`pytest ./tests/test_layers_utils.py::AttentionBlockTests::test_attention_block_default ./tests/test_models_unet.py::UNetLDMModelTests::test_from_pretrained_hub ./tests/test_models_unet.py::UNetLDMModelTests::test_from_pretrained_accelerate ./tests/test_models_unet.py::UNetLDMModelTests::test_from_pretrained_accelerate_wont_change_results`

eliminating the AttentionBlockTest and all three pass.  If I eliminate test_from_pretrained_hub, then the test_from_pretrained_accelerate passes, and test_from_pretrained_accelerate_wont_change_results fails.

Deleting device_map="auto" from

```
>       model, _ = UNet2DModel.from_pretrained(
            "fusing/unet-ldm-dummy-update", output_loading_info=True, device_map="auto"
        )
```
also passes.

This occurs on Windows 11 in conda, and WSL (Windows Subsystem for Linux) Debian with current head diffusers and current head accelerate on a 3060 NVidia GPU, CUDA 11.8.  They have different pytorches, and other different libraries.

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

This is actually the testing folder for diffusers, but presumably close enough.  To reproduce run

`pytest ./tests/test_layers_utils.py::AttentionBlockTests::test_attention_block_default ./tests/test_models_unet.py::UNetLDMModelTests::test_from_pretrained_hub ./tests/test_models_unet.py::UNetLDMModelTests::test_from_pretrained_accelerate ./tests/test_models_unet.py::UNetLDMModelTests::test_from_pretrained_accelerate_wont_change_results`

in the root of the diffusers checkout.

Note that @patrickvonplaten was not able to reproduce the bug on whatever system he is using.

Here is the pytest output,

[fail if run after attention block test.txt](https://github.com/huggingface/accelerate/files/9749889/fail.if.run.after.attention.block.test.txt)

### Expected behavior

The tests should run with out failing/corruption of the device_map dictionary, regardless of order of tests or specific inclusion or exclusion of tests.

**Comment by sgugger** [comment]
The bug indicates you are trying to run with `device_map="auto"` on a setup that does not have a GPU (or not enough GPU memory to accommodate one layer of the model). Give your report, I think the reason is that pypi does not release the CUDA memory between each tests, or maybe tries to run them in parallel automatically.

**Comment by Thomas-MMJ** [comment]
the tests aren't being ran in parallel AFAIK (there is a pypi variant that does, but not the default pypi), and the GPU is a Nvidia 3060 (mobile) with 6GB so should be plenty for the test.

Adding 

```
torch.cuda.empty_cache()
gc.collect()

```

after the functions results in the tests passing.  So your theory seems to be correct.  Three of the functions are in the same submodule, so it isn't clear why the other function is interfering.
