### ISSUE TITLE
device_map error

### ISSUE THREAD

**Issue by mayank31398** [huggingface/accelerate#762]
### System Info

```Shell
- `Accelerate` version: 0.12.0
- Platform: Linux-4.18.0-305.25.1.el8_4.x86_64-x86_64-with-glibc2.17
- Python version: 3.8.13
- Numpy version: 1.23.1
- PyTorch version (GPU?): 1.11.0a0+gitbc2c6ed (True)
- `Accelerate` default config:
      Not found
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

```
File "/net/llm-shared-nfs/nfs/mayank/transformers-bloom-inference/bloom-inference-server/models/hf_accelerate.py", line 33, in __init__
    self.model = AutoModelForCausalLM.from_pretrained(**kwargs)
  File "/net/llm-shared-nfs/nfs/yelkurdi/conda/miniconda3/envs/bloom-server/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 463, in from_pretrained
    return model_class.from_pretrained(
  File "/net/llm-shared-nfs/nfs/yelkurdi/conda/miniconda3/envs/bloom-server/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2324, in from_pretrained
    model, missing_keys, unexpected_keys, mismatched_keys, error_msgs = cls._load_pretrained_model(
  File "/net/llm-shared-nfs/nfs/yelkurdi/conda/miniconda3/envs/bloom-server/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2386, in _load_pretrained_model
    raise ValueError(
ValueError: The current `device_map` had weights offloaded to the disk. Please provide an `offload_folder` for them.
```
This happend with max_memory = {0: '0GIB', 1: '51GIB', 2: '51GIB', 3: '51GIB', 4: '51GIB', 5: '51GIB', 6: '51GIB', 7: '51GIB'}
and device_map = "auto" in kwargs for BLOOM-176 B.

This issue was not seen in transformers 4.21.2

@sgugger fyi

### Expected behavior

```Shell
related: https://github.com/huggingface/transformers-bloom-inference/issues/17
```

**Comment by sgugger** [comment]
Without seeing the code you run, it's hard to see the root. Are you sure you passed along the `torch_dtype`? I don't see any problem on my side when this argument is passed.

Also note that now you only need to pass `device_map="balanced_low_0"` and not `memory_map` to achieve the the same results (fill all the GPUs to the max and put as little as possible on the first one).

**Comment by mayank31398** [comment]
ok, ill try to replicate and share a minimal script

**Comment by mayank31398** [comment]
@sgugger 
max_memory_per_gpu = {
                0: "0GIB",
                1: "51GIB",
                2: "51GIB",
                3: "51GIB",
                4: "51GIB",
                5: "51GIB",
                6: "51GIB",
                7: "51GIB",
            }
and device_map = "auto" fails.

but your suggestion is working well.
Should I close this issue? Or does this need a fix?

**Comment by sgugger** [comment]
Found where the bug was coming from, the PR linked above should fit it.
