### ISSUE TITLE
Accelerate not moving anything to execution device after cpu_offload

### ISSUE THREAD

**Issue by piEsposito** [huggingface/accelerate#767]
### System Info

```Shell
- `Accelerate` version: 0.13.2
- Platform: Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.31
- Python version: 3.9.12
- Numpy version: 1.23.3
- PyTorch version (GPU?): 1.12.1+cu116 (True)
- `Accelerate` default config:
        Not found
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

Run 

```python
import torch
from torch import nn
import accelerate

class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.nn_parameter = nn.Parameter(torch.ones(1), requires_grad=False)
        
    def forward(self, x):
        print(x.device, self.nn_parameter.device)
        return self.nn_parameter + x
    
net = Net()

assert torch.cuda.is_available()
net = accelerate.cpu_offload(net, execution_device=torch.device("cuda"))

x = torch.zeros(1, 1)
net(x)
```

Returns

`cpu meta`

and 

`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, 
meta and cpu!`

### Expected behavior

```Shell
Should output


cuda:0 cuda:0
tensor([[1.]], device='cuda:0')
```
```

**Comment by piEsposito** [comment]
I think I found the problem:

On https://github.com/huggingface/accelerate/blob/a63511107b099505bd499c6931bd28bf3dce73fe/src/accelerate/big_modeling.py#L146-L155

When we add the hook on top of the previous hook, the first hook is deleted and we lose all the devices placement hook.

**Comment by sgugger** [comment]
Thanks for the very clear bug report. You have found the cause, although the fix is not quite right ;-)
Will comment on the PR!
