### ISSUE TITLE
Multi-GPU inference

### ISSUE THREAD

**Issue by shivangsharma1** [huggingface/accelerate#769]
Hi Team,

I have trained a t5/mt5 hugging face model, I am looking for a way to to inference 1Million examples on multiple GPU. I was able to inference using single GPU but I want a way to load the pretrained saved huggingface model and do multi-GPU inference and save it at last.

Can someone please share a script to do the process?

**Comment by pacman100** [comment]
Hello @shivangsharma1, please go through this resolution of same issue: https://github.com/huggingface/accelerate/issues/754#issuecomment-1277219368

**Comment by shivangsharma1** [comment]
Hi @pacman100 , 
I have reviewed that code, I didn't find much help from the script. Would it be possible for you share a small script, as I am new to this Accelerator Api.

**Comment by ZhiyuanChen** [comment]
Basically you just need to call `accelerator.prepare` on your model and dataloader, and everything else is set up for you
