### ISSUE TITLE
How to specify the GPU number available for accelerator program？

### ISSUE THREAD

**Issue by kenjewu** [huggingface/accelerate#77]
Suppose there are 4 GPUs on a machine, and now there are two training programs that use accelerator. How to specify  0,1 gpus for the first program and 2,3 gpus for the second program. The CUDA_VISIABLE_DEVICES=XX  does not seem to work fine.

**Comment by hyusterr** [comment]
I have the same problem! still trying hard to figure out how to fix it

**Comment by sgugger** [comment]
Could you tell me which command you are using to launch the two programs?

**Comment by kenjewu** [comment]
Hi, @sgugger 
1. Command of the first program:
```
accelerate launch --config_file accelerate_config.json train.py
```
the content of accelerate_config.json:
```
{
  "compute_environment": "LOCAL_MACHINE",
  "distributed_type": "MULTI_GPU",
  "fp16": false,
  "machine_rank": 0,
  "main_process_ip": null,
  "main_process_port": null,
  "main_training_function": "main",
  "num_machines": 1,
  "num_processes": 2
}
```
2. the second:
```
CUDA_VISIABLE_DEVICES=2,3 accelerate launch --config_file accelerate_config.json train.py
```
the content of accelerate_config.json:
```
{
  "compute_environment": "LOCAL_MACHINE",
  "distributed_type": "MULTI_GPU",
  "fp16": false,
  "machine_rank": 0,
  "main_process_ip": null,
  "main_process_port": 20655,
  "main_training_function": "main",
  "num_machines": 1,
  "num_processes": 2
}
```
Since the first program will occupy 0,1 gpu by default, I tried to use `CUDA_VISIABLE_DEVICES` to allocate 2,3 gpu to the second program. But it didn't work. In addition, although I modified the port in the second configuration file, I still get an error, Address already in use, when I start the program.

**Comment by sgugger** [comment]
Sorry for the delay, it took me a bit of time to get a machine with 4 GPUs for testing. First, make sure you have a source install of accelerate since this is the one I tried (no point fixing bugs already solved!)

Then make sure to have `CUDA_VISIBLE_DEVICES` on both your commands otherwise the GPUs might be taken by the first one. In my case doing:
```
CUDA_VISIBLE_DEVICES=0,1 accelerate launch train_script.py
```
and
```
CUDA_VISIBLE_DEVICES=2,3 accelerate launch second_config.yaml train_script.py
```
worked flawlessly and the 4 GPUs were used.

My default config was:
```
compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
fp16: false
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
num_machines: 1
num_processes: 2
```
and the content of `second_config.yaml` was
```
compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
fp16: false
machine_rank: 0
main_process_ip: null
main_process_port: 20655
main_training_function: main
num_machines: 1
num_processes: 2
```

Note that this also works without defining a second config by overriding the default port like this:
```
CUDA_VISIBLE_DEVICES=2,3 accelerate launch --main_process_port 20655 train_script.py
```

**Comment by VirajBagal** [comment]
I am facing the same problem. I have 2 GPUs on 1 machine. I ran one script using:
```
python main.py
```

It uses 1st GPU (i.e GPU 0) and runs well. Then I tried to run the same script simultaneously on the second GPU using:

```
CUDA_VISIBLE_DEVICES=1 accelerate launch accelerate_config.yaml main.py
```

Here is my accelerate_config.yaml file:
```
compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
fp16: true
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
num_machines: 1
num_processes: 2
```


I get the following error when I run the second command:
```
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "accelerate_config.yaml", line 1, in <module>
    compute_environment: LOCAL_MACHINE
NameError: name 'LOCAL_MACHINE' is not defined
Traceback (most recent call last):
  File "accelerate_config.yaml", line 1, in <module>
    compute_environment: LOCAL_MACHINE
NameError: name 'LOCAL_MACHINE' is not defined
Killing subprocess 37660
Killing subprocess 37661
```

Please help.

**Comment by sgugger** [comment]
If you want to use one process for each launch you should adjust your `num_processes` to 1 in the last line of the config. They will also likely need to use different ports (look at how I specified a new one in the command in my previous comment).

**Comment by VirajBagal** [comment]
I have made the changes you suggested, but I still get the following errors. 

When using accelerate_config.json, I get this error:

```
Traceback (most recent call last):
  File "accelerate_config.json", line 4, in <module>
    "fp16": false,
NameError: name 'false' is not defined
Traceback (most recent call last):
  File "accelerate_config.json", line 4, in <module>
    "fp16": false,
NameError: name 'false' is not defined
Killing subprocess 125824
Killing subprocess 125825
```

The json is following:
```
{
  "compute_environment": "LOCAL_MACHINE",
  "distributed_type": "MULTI_GPU",
  "fp16": false,
  "machine_rank": 0,
  "main_process_ip": null,
  "main_process_port": 20655,
  "main_training_function": "main",
  "num_machines": 1,
  "num_processes": 1
}
```


When I use accelerate_config.yaml, I get the following error:

```
Traceback (most recent call last):
  File "accelerate_config.yaml", line 1, in <module>
    compute_environment: LOCAL_MACHINE
NameError: name 'LOCAL_MACHINE' is not defined
Traceback (most recent call last):
  File "accelerate_config.yaml", line 1, in <module>
    compute_environment: LOCAL_MACHINE
NameError: name 'LOCAL_MACHINE' is not defined
Killing subprocess 125118
Killing subprocess 125119
```

The yaml is following:
```
compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
fp16: true
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
num_machines: 1
num_processes: 1
```

**Comment by sgugger** [comment]
You shouldn't run 
```
CUDA_VISIBLE_DEVICES=1 accelerate launch accelerate_config.yaml main.py
```
the file just after `launch` needs to be a python file. The right command is
```
CUDA_VISIBLE_DEVICES=1 accelerate launch main.py --config_file accelerate_config.yaml
```

**Comment by VirajBagal** [comment]
In your comment above on May 14, you mentioned that you used this command and it worked for you: 

`CUDA_VISIBLE_DEVICES=2,3 accelerate launch second_config.yaml train_script.py`

Here you used config file just after `launch`

**Comment by sgugger** [comment]
That was probably a typo from my side.

**Comment by kenjewu** [comment]
> Sorry for the delay, it took me a bit of time to get a machine with 4 GPUs for testing. First, make sure you have a source install of accelerate since this is the one I tried (no point fixing bugs already solved!)
> 
> Then make sure to have `CUDA_VISIBLE_DEVICES` on both your commands otherwise the GPUs might be taken by the first one. In my case doing:
> 
> ```
> CUDA_VISIBLE_DEVICES=0,1 accelerate launch train_script.py
> ```
> 
> and
> 
> ```
> CUDA_VISIBLE_DEVICES=2,3 accelerate launch second_config.yaml train_script.py
> ```
> 
> worked flawlessly and the 4 GPUs were used.
> 
> My default config was:
> 
> ```
> compute_environment: LOCAL_MACHINE
> distributed_type: MULTI_GPU
> fp16: false
> machine_rank: 0
> main_process_ip: null
> main_process_port: null
> main_training_function: main
> num_machines: 1
> num_processes: 2
> ```
> 
> and the content of `second_config.yaml` was
> 
> ```
> compute_environment: LOCAL_MACHINE
> distributed_type: MULTI_GPU
> fp16: false
> machine_rank: 0
> main_process_ip: null
> main_process_port: 20655
> main_training_function: main
> num_machines: 1
> num_processes: 2
> ```
> 
> Note that this also works without defining a second config by overriding the default port like this:
> 
> ```
> CUDA_VISIBLE_DEVICES=2,3 accelerate launch --main_process_port 20655 train_script.py
> ```

Hi，@sgugger.  Your answer helped me solve the problem very well, thank you very much. 👍

**Comment by lzy37ld** [comment]
@sgugger ,
Hi! Hope this finds you well.

I want to use accelerate to run a RLHF code but with small 5 gpus say 24GB. I wanna place the RLHF training process wth accelerate on the first 4 gpus and place the reward model at the 5th GPU, Does that work or not? Since If I place the reward model on any of them, then it would meet OOM.
