### ISSUE TITLE
What is the best practice to do inference in bf16 with accelerate during training?

### ISSUE THREAD

**Issue by huchinlp** [huggingface/accelerate#771]
### System Info

```Shell
Basically, I want to do training with mixed precision and evaluate the model with bfloat16.
I found the model is stored in fp32 after calling acclerate.prepare() and have to convert it to bf16 for faster inference. Can I avoid `explictly` model conversion and  make the most use of accelerate?
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

,

### Expected behavior

```Shell
Ideally, we do not want manually model conversion.
```

**Comment by sgugger** [comment]
Please use the [forums](https://discuss.huggingface.co/) to ask such questions as we keep the issues for bugs and feature requests only.

Mixed precision training uses... mixed precision as the name indicates. So the model is still in float32 and there is no easy way to perform inference in bfloat16 within the same script other than casting the model to bfloat16 and back.
