### ISSUE TITLE
Can we launch accelerate from a Python script instead of CLI?

### ISSUE THREAD

**Issue by ayulockin** [huggingface/accelerate#804]
I am trying to do hyperparameter optimization using Ray Tune and want to use accelerate to handle multi-gpu training.

I am fairly new to accelerate and could only find the CLI method (`accelerate launch`) to launch the script. Do we have something like `accelerate.launch` or something similar to `notebook_launcher` that can launch the training from the script?

I am looking to see if I can pass a function that takes a config as an argument - something like this: `accelerate.launch(my_train_func, ags=[config], ...)`

Thanks in advance.

**Comment by sgugger** [comment]
This would require to run independent subprocesses, not too sure how Ray Tune is going to like that since it won't be able to inspect how training is going.

**Comment by samiede** [comment]
I have a similar issue: I have a server that is taking requests from outside to then launch training. I want to make the training distributed but of course only have the server process run on a single process. Since the message reading is running in a 
```
while True:
    process_message(message)
```

I can't wrap that in a `if accelerator.is_local_main_process:` because then the whole training loop would only run on one GPU. Did you ever find a solution to what you were trying to do @ayulockin ?

**Comment by ayulockin** [comment]
I didn't find any solution with accelerate. In my case, I would have used Ray Train for distributed training.

**Comment by samiede** [comment]
Does Ray Train allow for distributed functions?

**Comment by ayulockin** [comment]
This is my reference: https://docs.ray.io/en/latest/tune/tutorials/tune-resources.html#how-to-run-distributed-training-with-tune
<img width="704" alt="image" src="https://user-images.githubusercontent.com/31141479/205573810-01a15550-b450-44a4-9c1b-8c77f45d976f.png">

**Comment by pacman100** [comment]
Hello @samiede and @ayulockin, have you looked at this test: https://github.com/huggingface/accelerate/blob/main/tests/deepspeed/test_deepspeed.py#L657-L699 wherein accelerate is launched from a python script instead of cli? Let us know if that solves the issue.

**Comment by LouisCastricato** [comment]
Reopening.

**Comment by richardliaw** [comment]
We implemented a Huggingface Accelerate integration for Ray - https://github.com/ray-project/ray/pull/33269
