### ISSUE TITLE
Make AlignDevicesHook suport bitsandbytes Linear layers natively

### ISSUE THREAD

**Issue by piEsposito** [huggingface/accelerate#816]
It would be great if `AlignDevicesHook` supported bitsandbytes 8bit Linear layers. 

To implement it, we would just have to add something like [set_module_8bit_tensor_to_device ](https://github.com/huggingface/transformers/blob/main/src/transformers/utils/bitsandbytes.py#L17-L86) from transformers to AlignDevicesHook when handling `Int8Params` from bitsandbytes.

If you folks agree this can be implemented I can (try to) submit a PR.

**Comment by sgugger** [comment]
The method should be merged with the existing `set_module_tensor_to_device` I agree. It works without issue for model parallelism (as seen in Transformers) but does not work for offloading however: the 8bit layers have a state that does not disappear and takes a lot of GPU memory.
