### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by 0xdevalias** [huggingface/accelerate#822]
### System Info

```Shell
> accelerate env

Copy-and-paste the text below in your GitHub issue

- `Accelerate` version: 0.13.2
- Platform: Linux-5.15.0-43-generic-x86_64-with-glibc2.28
- Python version: 3.10.8
- Numpy version: 1.23.3
- PyTorch version (GPU?): 1.12.1 (True)
- `Accelerate` default config:
	Not found
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

```
> accelerate launch train_dreambooth.py --pretrained_model_name_or_path=CompVis/stable-diffusion-v1-4 --instance_data_dir=./instance_images --class_data_dir=./class_images --output_dir=./trained_model --with_prior_preservation --prior_loss_weight=1.0 --instance_prompt=a photo of sks dog --class_prompt=a photo of dog --resolution=512 --train_batch_size=1 --gradient_accumulation_steps=1 --learning_rate=5e-6 --lr_scheduler=constant --lr_warmup_steps=0 --num_class_images=200 --max_train_steps=800 --seed=1337

The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `{args.num_processes}`
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--num_cpu_threads_per_process` was set to `8` to improve out-of-box performance
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.

Traceback (most recent call last):
  File "/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 910, in launch_command
    simple_launcher(args)
  File "/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 397, in simple_launcher
    process = subprocess.Popen(cmd, env=current_env)
  File "/venv/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/venv/lib/python3.10/subprocess.py", line 1767, in _execute_child
    env_list.append(k + b'=' + os.fsencode(v))
  File "/venv/lib/python3.10/os.py", line 811, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.

TypeError: expected str, bytes or os.PathLike object, not NoneType
```

### Expected behavior

Not to receive a `TypeError`, or to receive better details about what is going wrong so I can fix it.

**Comment by sgugger** [comment]
cc @muellerzr

**Comment by muellerzr** [comment]
@0xdevalias I believe this has already been fixed in the dev version of accelerate, but it stems from you skipping the `accelerate config` part of the steps outlined in here: https://github.com/huggingface/diffusers/tree/main/examples/dreambooth#installing-the-dependencies

Can you try installing with `pip install git+https://github.com/huggingface/accelerate` to verify? A new release should be out soon

**Comment by 0xdevalias** [comment]
> I believe this has already been fixed in the dev version of accelerate

Awesome!

> but it stems from you skipping the `accelerate config` part of the steps outlined in here: [huggingface/diffusers@`main`/examples/dreambooth#installing-the-dependencies](https://github.com/huggingface/diffusers/tree/main/examples/dreambooth?rgh-link-date=2022-11-07T17%3A27%3A11Z#installing-the-dependencies)

Yeah, that makes sense. I was skipping that partly to see if I could, and partly because there is no good non-interactive way to use the `accelerate config` CLI at the moment (eg. from a jupyter notebook)

My hacky workaround was to generate the file on a throwaway machine, then copy/paste it into my notebook and have the notebook itself write it out.

> Can you try installing with `pip install git+https://github.com/huggingface/accelerate` to verify? A new release should be out soon that solves this error from ever occurring again :)

Glad to hear it! While I didn't explicitly install this version to test yet, I ran the same notebook that was failing the other day and it seemed like it might have worked, so I'm guessing the version with the fix in it may have already been pushed out?

**Comment by 0xdevalias** [comment]
> My hacky workaround was to generate the file on a throwaway machine, then copy/paste it into my notebook and have the notebook itself write it out.

For anyone else who stumbles upon this issue in future, I have also just found out that there is a programmatic way of writing this config file now too:

> I can probably assist on this, as this is a fair point as more libraries start using Accelerate that we should template's how to quickly write configs for users to use that are relevant to them. One option is we have a `write_basic_config` function in accelerate that creates a config file based on all the GPUs available and let's you set the mixed precision mode: https://huggingface.co/docs/accelerate/v0.14.0/en/package_reference/utilities#accelerate.utils.write_basic_config
> 
> So e.g. a better option may be to direct the user to perform:
> 
> ```python
> from accelerate.utils import write_basic_config
> write_basic_config(mixed_precision="fp16")
> ```
> We can also experiment with adding a command of something like `accelerate config basic`. Which from your perspective is easier on you @exo-pla-net? Likely the CLI option I imagine? 😃
> 
> _Originally posted by @muellerzr in https://github.com/huggingface/diffusers/issues/1228#issuecomment-1309476017_
