### ISSUE TITLE
Allow setting logger's LOGLEVEL via env var / CLI argument / etc

### ISSUE THREAD

**Issue by 0xdevalias** [huggingface/accelerate#834]
Currently (as best I can tell) there is no way to control accelerate's `logger` without modifying code. It would be nice if we were able to pass an ENV var / CLI argument to `accelerate` to change the log level without having to modify any code run by it.

- https://huggingface.co/docs/accelerate/main/en/package_reference/logging
- https://github.com/huggingface/accelerate/blob/main/src/accelerate/logging.py#L52

```
import logging
import os

LOGLEVEL = os.environ.get('LOGLEVEL', 'WARNING').upper()
logging.basicConfig(level=LOGLEVEL)
```

- https://docs.python.org/3/library/logging.html#logging.basicConfig

My  use case is wanting to crank up the logging on `train_dreambooth.py ([ref](https://github.com/huggingface/diffusers/tree/main/examples/dreambooth#training-with-prior-preservation-loss)) without having to modify the code itself:

```
from accelerate.logging import get_logger

LOGLEVEL = os.environ.get('LOGLEVEL', 'WARNING').upper()

logger = get_logger(__name__)
logger.basicConfig(level=LOGLEVEL)
```

```
AttributeError: 'MultiProcessAdapter' object has no attribute 'basicConfig'
```

**Comment by 0xdevalias** [comment]
Seemingly I can hack it in the code like this, but it would be nice if the `accelerate` logger was configurable directly, without code modification:

```
import logging
LOGLEVEL = os.environ.get('LOGLEVEL', 'WARNING').upper()
logging.basicConfig(level=LOGLEVEL)
```

**Comment by sgugger** [comment]
cc @muellerzr

**Comment by muellerzr** [comment]
@0xdevalias this is more of a user error but we can still improve it. In order for `logging.basicConfig` to work you **first need to define a logger**, and you specifically need to define *accelerate*'s logger. So e.g. the following would work:

```python
from accelerate.logging import get_logger
import logging

logger = get_logger(__name__)
logging.basicConfig("DEBUG")
```

That being said I'll introduce a PR shortly that let's you do:

```python
from accelerate.logging import get_logger

logger = get_logger(__name__, log_level="DEBUG")
```

**Comment by muellerzr** [comment]
Thanks @0xdevalias, sorry I was a bit unclear in my last note so I removed it. This is a good point and the issue with `filter_trackers` and this should be solved in a PR shortly!
