### ISSUE TITLE
The multi process lr scheduler implementation doesn't seem right

### ISSUE THREAD

**Issue by ernestchu** [huggingface/accelerate#843]
https://github.com/huggingface/accelerate/blob/074d8d5a5a131501cc0a2a690cc14337395dcb09/src/accelerate/scheduler.py#L72-L75

The scheduler should not step if `self.scheduler._step_count > self.scheduler.total_steps`.

**Comment by muellerzr** [comment]
Thanks for the notice! Will be fixed by #849
