### ISSUE TITLE
How to use on CPU?

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [huggingface/accelerate#85]
Hey guys,  how do I use the accelerator on CPU?

```python
acc = Accelerator(cpu=True)
print(acc.device)
```
Output `cuda`.

Thank you!

Cheers,

Francesco

**Comment by sgugger** [comment]
Are you sure you are using the last version/a source install? I just tried on both and this code prints "cpu".

**Comment by FrancescoSaverioZuppichini** [comment]
working now :)
