### ISSUE TITLE
`DISABLE_RICH` => `ACCELERATE_DISABLE_RICH`

### ISSUE THREAD

**Issue by stas00** [huggingface/accelerate#888]
## Feature Update

I'm working on adding `M4_DISABLE_RICH` and noticed Accelerate didn't add the `ACCELERATE_` prefix to the same functionality, and uses `DISABLE_RICH`.

IMHO, it'd be good if each project kept its env vars contained to its "namespace", so users of each project can turn on/off different flags w/o impacting other projects. I am aware that this in no way interferes with my work. I just thought that we could sync across HF projects at how we manage the env var name space if you're open to that, of course.

Incidentally this also helps when reading the output of `printenv` - `ACCELERATE_DISABLE_RICH` tells me that the flag disables RICH in Accelerate. `DISABLE_RICH` on the other hand is very ambiguous, especially since I don't think `rich` supports it (at least I couldn't find it in its docs).

Thank you for considering my proposition.

**Comment by muellerzr** [comment]
Agreed, this is a very good point and *all* env variables I think should use `ACCELERATE` prefix so it's clear what's being set (unless specifically `torchrun` etc needs it). WDYT @sgugger @pacman100. We already did this with `ACCELERATE_LOG_LEVEL` so it would make sense to trickle this up and keep things consistent

**Comment by sgugger** [comment]
Works for me!

**Comment by stas00** [comment]
Thank you for the fix, @muellerzr! and syncing the rest of the env vars too - awesome!
