### ISSUE TITLE
Reduce memory when using DeepspeedPlugin

### ISSUE THREAD

**Issue by Pna2791** [huggingface/accelerate#897]
- I want to using deepspeed for training T5-large but not enough memory.
- I tried to using DeepspeedPlugin in accelerate, but memory do not reduce.
-- **How to config deepspeedPlugin to reduce memory?**

My config in script:
```
  deepspeed_plugin = DeepSpeedPlugin(
      gradient_accumulation_steps=1,
      zero3_init_flag=True,
      zero_stage=3,
      gradient_clipping=1.0
  )
```
But I found in log has:
```
activation_checkpointing_config  {
    "partition_activations": false, 
    "contiguous_memory_optimization": false, 
    "cpu_checkpointing": false, 
    "number_checkpoints": null, 
    "synchronize_checkpoint_boundary": false, 
    "profile": false
}
```

**Comment by pacman100** [comment]
Hello @Pna2791, as mentioned in DeepSpeed docs, [activation-checkpointing](https://www.deepspeed.ai/docs/config-json/#activation-checkpointing)  can only be used with model parallelism and not with ZeRO data parallelism. To further reduce memory, please set `offload_optimizer_device='cpu'` and `offload_param_device='cpu'`.  

Please also refer to the [blogpost](https://huggingface.co/blog/accelerate-deepspeed#cpudisk-offloading-to-enable-training-humongous-models-that-wont-fit-the-gpu-memory) for more details.
