### ISSUE TITLE
When using the streaming method to read the training file, an error is reported when the multi-GPU data is loaded

### ISSUE THREAD

**Issue by biandh** [huggingface/accelerate#899]
### System Info

```Shell
accelerate==0.13.2

compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: MULTI_GPU
downcast_bf16: 'no'
fsdp_config: {}
gpu_ids: all
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
use_cpu: false
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

``` ptyhon
# https://github.com/huggingface/accelerate/blob/main/src/accelerate/data_loader.py

raw_datasets = load_dataset(extension, data_files=data_files, streaming=True)
train_dataset = raw_datasets["train"]
eval_dataset = raw_datasets["validation"]

train_dataloader = DataLoader(train_dataset, shuffle=False, collate_fn=data_collator,
                                      batch_size=args.per_device_train_batch_size) 

train_dataloader = accelerator.prepare(train_dataloader)
for step, batch in enumerate(train_dataloader):
    print(batch)

```

![image](https://user-images.githubusercontent.com/16524285/205079474-40320404-e03c-443b-8224-908f79e2d6e8.png)

When using multiple GPUs, **self.state.num_processes > 1**, therefore, the length of **input_ids** loaded by different processes **may not match**, so an exception will be reported

![image](https://user-images.githubusercontent.com/16524285/205080774-e859676a-3913-4e60-ae65-8c0ced4acdb6.png)

### Expected behavior

```Shell
As shown in FIG.
```

**Comment by sgugger** [comment]
You need your data to have fixed size in the batches when using streaming or any kind of iterable dataset by default. If noy, you can try to use `dispatch_batches=False` when defining your `Accelerator`.
