### ISSUE TITLE
how to save model while keeping the original ones unchanged in output folder?

### ISSUE THREAD

**Issue by zixiliuUSC** [huggingface/accelerate#93]
I find this line in transformers' examples but it always override the previous output models. 
unwrapped_model.save_pretrained(args.output_dir, save_function=accelerator.save)

**Comment by sgugger** [comment]
You can just change `args.output_dir` by whatever you like.

**Comment by zixiliuUSC** [comment]
Thanks for your reply~ Actually, I mean I want to keep all checkpoints during the training. I check out an solution by writing a save function on my own. 

`def save(obj, f):
    """
    Save the data to disk. Use in place of :obj:`torch.save()`.
    Args:
        obj: The data to save
        f: The file (or file-like object) to use to save the data
    """
    path = f
    if path[-1]=='/':
        path = path[:-1]
    filelist = os.listdir(path)
    num_set = set()
    for i in filelist:
        if 'output_model_' in i:
            num = i.split('output_model_')[-1]
            try:
                num = int(num)
            except:
                continue
            num_set.add(int(num))
    if len(num_set)>0:
        num_set = sorted(list(num_set))
        n = num_set[-1]+1
    else:
        n = 1
    os.mkdir(path+'/output_model_'+str(n))
    f1 = path+'/output_model_'+str(n)
    if AcceleratorState().distributed_type == DistributedType.TPU:
        import torch_xla.core.xla_model as xm
        xm.save(obj, f1)
    elif AcceleratorState().local_process_index == 0:
        torch.save(obj, f1)`
