### ISSUE TITLE
Should I do 'accelerator.prepare()' again after 'accelerator.unwrap_model()' ?

### ISSUE THREAD

**Issue by DtYXs** [huggingface/accelerate#948]
For multi-gpu training:
`model = accelerator.prepare(model)`
I want to save ckpt during training. Then I do this:
`model = accelerator.unwrap_model(model)`
`pipeline = Pipeline(model=model)`
`pipeline.save_pretrained(...)`
And I want to continue training. Should I do `model = accelerator.prepare(model)` again after saving?

**Comment by pacman100** [comment]
Hello, 

below is the code structure of follow:
```
model = accelerator.prepare(model)

for epoch in range(num_epochs):
    # train loop
    
    # eval loop
    
    # saving checkpoint
    unwrapped_model = accelerator.unwrap_model(model)
    
    pipeline = Pipeline(model=unwrapped_model)
    pipeline.save_pretrained(...)

   # alternatively you can save using `unwrapped_model.save_pretrained(...)`
```

Let us know if that solves your query. For such queries in future, please use https://discuss.huggingface.co/c/accelerate/18

**Comment by DtYXs** [comment]
> Hello,
> 
> below is the code structure of follow:
> 
> ```
> model = accelerator.prepare(model)
> 
> for epoch in range(num_epochs):
>     # train loop
>     
>     # eval loop
>     
>     # saving checkpoint
>     unwrapped_model = accelerator.unwrap_model(model)
>     
>     pipeline = Pipeline(model=unwrapped_model)
>     pipeline.save_pretrained(...)
> 
>    # alternatively you can save using `unwrapped_model.save_pretrained(...)`
> ```
> 
> Let us know if that solves your query. For such queries in future, please use https://discuss.huggingface.co/c/accelerate/18

Thanks for your helpful reply. And if the operation of `unwrapped_model ` affect `model`?
Actually, in my code, if I continue to train the original `model` after doing this, there will be problems. I want to know whether this `unwrapped_model` is completely independent of `model`, and if not, how can I save the ckpt multiple times without destroying the training process, not only after the full training, but also after B and then save the ckpt.

**Comment by pacman100** [comment]
Hello @DtYXs, can you please provide a minimal reproducible example of the issue that you are facing?

**Comment by sgugger** [comment]
Yes it does, this was added recently by @muellerzr.
Maybe we should have a flag in `unwrap_model` so the user can select if they want model hooks to be removed or not.

**Comment by miquelmarti** [comment]
One would expect they get removed on the returned object, but never on the object you pass to this function, or?

**Comment by sgugger** [comment]
It's tricky since a model is a reference type, and we can't really create a whole copy of the model.

**Comment by muellerzr** [comment]
@miquelmarti what Sylvain already describes is actually supported. Just do:

```python
model = accelerator.unwrap_model(model, keep_fp32_wrapper=True)
```

Will this work for you? :)

**Comment by miquelmarti** [comment]
I understand and yes, this flag does work for me. However, the behaviour before the change was equivalent to setting the flag to True and IMO that should be the default now as well so that unwrapping the model does not affect the next calls to forward. I think train -> checkpoint -> keep training is probably the most common use case of `unwrap_model`. If you have good reason for it not being set to True by default, some warning on the documentation would probably save people upgrading or having expectations similar to mine some debugging time :')

**Comment by JeS24** [comment]
@muellerzr @sgugger Was any consensus reached on what to do here? I am facing the same dilemma as @miquelmarti and would rather prefer that unwrapping and checkpointing the model (using `save_pretrained()`) does not impact its ability to continue training.
