### ISSUE TITLE
Simple NLP Example fails in colab

### ISSUE THREAD

**Issue by caroheymes** [huggingface/accelerate#954]
### System Info

```Shell
- `Accelerate` version: 0.15.0.dev0
- Platform: Linux-5.10.147+-x86_64-with-glibc2.27
- Python version: 3.8.16
- Numpy version: 1.21.6
- PyTorch version (GPU?): 1.13.0+cu116 (False)
- `Accelerate` default config:
	Not found
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

run this notebook : 
https://colab.research.google.com/github/huggingface/notebooks/blob/main/examples/accelerate_examples/simple_nlp_example.ipynb#scrollTo=AuM9kPcpY7a_

Error : 
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-25-154ee529f21e>](https://localhost:8080/#) in <module>
      1 from accelerate import notebook_launcher
      2 
----> 3 notebook_launcher(training_function, (model,))

[/usr/local/lib/python3.8/dist-packages/accelerate/launchers.py](https://localhost:8080/#) in notebook_launcher(function, args, num_processes, mixed_precision, use_port)
     59     if (in_colab or in_kaggle) and (os.environ.get("TPU_NAME", None) is not None):
     60         # TPU launch
---> 61         import torch_xla.distributed.xla_multiprocessing as xmp
     62 
     63         if len(AcceleratorState._shared_state) > 0:

ModuleNotFoundError: No module named 'torch_xla'

### Expected behavior

```Shell
Hope you can fix it !
```

**Comment by sgugger** [comment]
It is installed in the first cell. Maybe this cell needs to be updated to the latest version of PyTorch.

**Comment by caroheymes** [comment]
In fact the notebook is perfect  except for Google Colab Pro +.
Here is how to adapt the install cell : 

`
import os
assert os.environ['COLAB_TPU_ADDR'], 'Make sure to select TPU from Edit > Notebook settings > Hardware accelerator'
!pip install cloud-tpu-client==0.10 torch==1.13.0 https://storage.googleapis.com/tpu-pytorch/wheels/colab/torch_xla-1.13-cp38-cp38-linux_x86_64.whl
!curl https://raw.githubusercontent.com/pytorch/xla/master/contrib/scripts/env-setup.py -o pytorch-xla-env-setup.py
!python pytorch-xla-env-setup.py --version $VERSION
import os 
os.environ['LD_LIBRARY_PATH']='/usr/local/lib'
!echo $LD_LIBRARY_PATH

!sudo ln -s /usr/local/lib/libmkl_intel_lp64.so /usr/local/lib/libmkl_intel_lp64.so.1
!sudo ln -s /usr/local/lib/libmkl_intel_thread.so /usr/local/lib/libmkl_intel_thread.so.1
!sudo ln -s /usr/local/lib/libmkl_core.so /usr/local/lib/libmkl_core.so.1

!ldconfig
!ldd /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch.so
`
