### ISSUE TITLE
`gather_for_metrics` and `GradientState` don't work with arbitrary evaluation intervals

### ISSUE THREAD

**Issue by ernestchu** [huggingface/accelerate#960]
I try to run evaluation on the evaluation_dataloader (entire eval epoch) every given steps (instead of running after an entire train epoch). After evaluation,  the `GradientState` used by `gather_for_metrics` seems to stuck as-is in the last epoch of evaluation, which is
```
Sync Gradients: True                                                                                  
At end of current dataloader: True                                                                     
Extra samples added: 20
```
and it cause `gather_for_metrics` drop samples on train_loader for the following training until it reaches the end of the train epoch.

I noticed that the `gradient_state` in `Accelerator` main instance and both `DataLoaderShard` are synced, in a way I can't find in the accelerate source code.

Can someone elaborate what the design philosophy of `GradientState` and how it syncs between the accelerator and dataloaders. Additionally, if it is possible to do evaluation in the middle of the train epoch like I mentioned above. Thanks!

**Comment by ernestchu** [comment]
After some investigations, I know the `GradientState` is synced by the **singleton class** design. My current workaround is manually setting `accelerator.gradient_state.end_of_dataloader` to `False` after the evaluation, so the following training would not incorrectly drop samples.

**Comment by sgugger** [comment]
cc @muellerzr

**Comment by muellerzr** [comment]
@ernestchu `GradientState` is a singleton designed to work with a single dataloader that is currently being iterated upon, which is why you're experiencing this trouble. One thing I could think of is setting an api such as `pause` and `resume` which will "turn off" `GradientState` and/or reset it. So essentially the API would be:

```python
dl1, dl2 = accelerator.prepare(dl1, dl2)
for i,batch in enumerate(dl1):
    ...
    if i == 5:
        accelerator.gradient_state.pause()
        for batch in dl2:
            ....
        accelerator.gradient_state.resume()
    ...
```

Does this seem reasonable to you both @ernestchu @sgugger

**Comment by muellerzr** [comment]
Should be closed with https://github.com/huggingface/accelerate/pull/1162, doesn't require any modification in the code
