### ISSUE TITLE
dispatch_batches issue, empty batch and duplicate samples

### ISSUE THREAD

**Issue by pratogab** [huggingface/accelerate#961]
### System Info

```Shell
- `Accelerate` version: 0.15.0
- Platform: Linux-4.15.0-194-generic-x86_64-with-glibc2.27
- Python version: 3.9.12
- Numpy version: 1.22.3
- PyTorch version (GPU?): 1.12.0 (True)
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: DEEPSPEED
        - mixed_precision: no
        - use_cpu: False
        - dynamo_backend: NO
        - num_processes: 3
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: None
        - main_process_ip: None
        - main_process_port: None
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - deepspeed_config: {'gradient_accumulation_steps': 1, 'offload_optimizer_device': 'cpu', 'offload_param_device': 'cpu', 'zero3_init_flag': True, 'zero3_save_16bit_model': False, 'zero_stage': 3}
        - fsdp_config: {}
        - megatron_lm_config: {}
        - downcast_bf16: no
        - tpu_name: None
        - tpu_zone: None
        - command_file: None
        - commands: None
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

I am running into some issues using `dispatch_batches=True` and multi-gpu. The issue is that when I run out of samples towards the end of an epoch, accelerate's dataloader does one of two things. Sometimes it duplicates a sample, so for example if I use 3 GPUs and the batch only has two elements (A and B), I might get something like first GPU gets sample A, second GPU gets sample B and third GPU gets sample A. Does Accelerator keep track of this and adjusts the loss such that A and B have equal weight in the loss? Another thing that can happen is that the dataloader simply yields no sample to certain device, so again, first GPU might get sample A, second GPU might get sample B and then third GPU gets nothing. In that case, I can't just `continue` on the GPU that gets nothing, the process hangs. Not sure if this is an expected behaviour as I have not found much details about this in the doc.

### Expected behavior
In the case where samples get duplicated, the loss should be computed appropriately such that duplicated samples get weighted appropriately. In the case where devices get no sample, not sure what one should do in that case.

**Comment by pratogab** [comment]
The issue seems to be in `accelerate/data_loader.py`, line 528:
```python
if not self._drop_last and stop_iteration and observed_batch_size % self.state.num_processes != 0:
    # If the last batch is not complete, let's add the first batch to it.
    batch = concatenate([batch, first_batch], dim=0)
    # Batch size computation above is wrong, it's off by 1 so we fix it.
    batch_size += 1
```
When the last batch is not complete, only one sample is added to the batch to fill the gap, instead of x samples being added such that (observed_batch_size + x) % self.state.num_processes = 0

**Comment by pratogab** [comment]
Or you could appropriately slice the data on line 534:
```python
data_slice = slice(self.state.process_index * batch_size, (self.state.process_index + 1) * batch_size)
```

**Comment by pratogab** [comment]
I ended up changing the code in `accelerate/data_loader.py` on line 528 to:
```python
if not self._drop_last and stop_iteration and observed_batch_size % self.state.num_processes != 0 and observed_batch_size < self.state.num_processes:
    number_missing_samples = self.state.num_processes - (observed_batch_size % self.state.num_processes)
    repeated_shape = [1] * len(batch.shape)
    repeated_shape[0] = math.ceil(self.state.num_processes / observed_batch_size)
    batch = batch.repeat(repeated_shape)[:batch.shape[0] + number_missing_samples]
    batch_size = (observed_batch_size + number_missing_samples) // self.state.num_processes
```
But now I need to fix the loss not taking into account duplicate samples.

**Comment by pratogab** [comment]
Alright, final solution that works.

`accelerate/data_loader.py` line 516:
```python
observed_batch_size = find_batch_size(batch)
            batch_size = max(observed_batch_size // self.state.num_processes, 1)

            stop_iteration = self._stop_iteration
            if not stop_iteration:
                # We may still be at the end of the dataloader without knowing it yet: if there is nothing left in
                # the dataloader since the number of batches is a round multiple of the number of processes.
                next_batch, next_batch_info = self._fetch_batches(main_iterator)
                # next_batch_info[0] is None when there are no more batches, otherwise we still need to process them.
                if self._stop_iteration and next_batch_info[0] is None:
                    stop_iteration = True

            if not self._drop_last and stop_iteration and observed_batch_size % self.state.num_processes != 0 and observed_batch_size < self.state.num_processes:
                number_missing_samples = self.state.num_processes - (observed_batch_size % self.state.num_processes)
                repeated_shape = [1] * len(batch.shape)
                repeated_shape[0] = math.ceil(self.state.num_processes / observed_batch_size)
                batch = batch.repeat(repeated_shape)[:batch.shape[0] + number_missing_samples]
                duplicate_mask = torch.zeros(batch.shape[0], dtype=torch.bool, device=batch.device)
                duplicate_mask[observed_batch_size:] = 1
                batch_size = (observed_batch_size + number_missing_samples) // self.state.num_processes
            else:
                duplicate_mask = torch.zeros(batch.shape[0], dtype=torch.bool, device=batch.device)

            data_slice = slice(self.state.process_index * batch_size, (self.state.process_index + 1) * batch_size)
            batch = slice_tensors(batch, data_slice)
            duplicate_mask = slice_tensors(duplicate_mask, data_slice)

            if stop_iteration:
                self.gradient_state._set_remainder(observed_batch_size)
                self.gradient_state._set_end_of_dataloader(True)
            yield batch, duplicate_mask
```
And in my training function, the loss function does not reduce the loss tensor, instead I multiply with the duplicate_mask and then average the remainder.

**Comment by sgugger** [comment]
Will have a look into this and fix what needs to be fixed next week (or if you have a clear idea of the problem, I welcome any PR :-) )

**Comment by simonhessner** [comment]
I am still experiencing batch duplication in version 0.25.0. It happens whenever `batch_size % num_gpus != 0`. What is the recommended way to solve this?

**Comment by muellerzr** [comment]
@simonhessner that's an issue with our new sampler we're fixing ASAP. For now please use 0.24.0, we'll be reverting that fix in the next release.

**Comment by simonhessner** [comment]
Thanks for your quick response. I have tried version 0.24.0, but get the same behaviour. Here is my sample code

```
from accelerate import Accelerator
from torch.utils.data import Dataset, DataLoader

class TestDataset(Dataset):
    def __init__(self):
        self.data = list(range(10))
    
    def __len__(self):
        return len(self.data)

    def __getitem__(self, index) -> int:
        return self.data[index]


def main():
    import multiprocessing
    accelerator = Accelerator()

    dataset = TestDataset()
    dataloader = DataLoader(dataset, batch_size=10, shuffle=False)
    dataloader = accelerator.prepare(dataloader)
    
    for d in dataloader:
        print(multiprocessing.current_process().pid, d)

if __name__ == "__main__":
    main()
```

Output with batch_size=10:

> 30529 tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], device='cuda:1')
> 30528 tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], device='cuda:0')

I would expect one one batch on the first GPU and the second GPU doing nothing.

With batch_size=5 I get what I expect:

> 31235 tensor([0, 1, 2, 3, 4], device='cuda:0')
> 31236 tensor([5, 6, 7, 8, 9], device='cuda:1')

With 2 the first batch gets duplicated:

> 31479 tensor([2, 3], device='cuda:1')
> 31479 tensor([6, 7], device='cuda:1')
> 31479 tensor([0, 1], device='cuda:1')
> 31478 tensor([0, 1], device='cuda:0')
> 31478 tensor([4, 5], device='cuda:0')
> 31478 tensor([8, 9], device='cuda:0')

I am not sure if this is actually a bug or if the framework internally accounts for duplicated batches by masking the loss function. What I intuitively would expect is that every batch is sent to exactly one GPU and there are no duplicates. In case they can't be evenly distributed, some GPUs would have to handle more than others and possibly have to wait for the others to finish their batch.

**Comment by simonhessner** [comment]
I just found out that when I set `even_batches=False` I get batches without any duplicates. The one case where this fails is when I set `batch_size=len(dataset)`. In that case I get this error:

```
Traceback (most recent call last):
  File "/home/user/main.py", line 29, in <module>
    main()
  File "/home/user/main.py", line 25, in main
    for d in dataloader:
  File "/opt/conda/lib/python3.10/site-packages/accelerate/data_loader.py", line 460, in __iter__
    current_batch = send_to_device(current_batch, self.device)
UnboundLocalError: local variable 'current_batch' referenced before assignment
```

But this is an edgecase that isn't really a problem for me.

**Comment by LuciusLan** [comment]
Hi guys, I found that the issue is not just regarding duplicate batch, but some data points are somehow ignored by the `DataLoader` when the duplication happens. (accelerate version: 0.26.1 pytroch version: 2.1.2)
And if setting `Accelerator(even_batches=False)`, the inference simply won't reach an end, which is expected. (Testing on a small scale dataset glue/wnli/validation set, total 71 entries)

(Sorry I can't give a link to a repo for now, but I believe it won't be hard to reproduce, if code is needed I can give a simple demo)

**Comment by steveepreston** [comment]
Found the root. This happen when:
`len(train_dataset)` < `num_devices` * `per_device_train_batch_size`
or
`len(eval_dataset)` < `num_devices` * `per_device_eval_batch_size`

* care about Packing too
