### ISSUE TITLE
Mixed precision not working

### ISSUE THREAD

**Issue by LvanderGoten** [huggingface/accelerate#964]
### System Info

```Shell
- `Accelerate` version: 0.15.0
- Platform: Linux-6.1.4-arch1-1-x86_64-with-glibc2.10
- Python version: 3.8.12
- Numpy version: 1.22.3
- PyTorch version (GPU?): 1.13.1 (True)
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: fp16
        - use_cpu: False
        - dynamo_backend: NO
        - num_processes: 2
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: all
        - main_process_ip: None
        - main_process_port: None
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - deepspeed_config: {}
        - fsdp_config: {}
        - megatron_lm_config: {}
        - downcast_bf16: no
        - tpu_name: None
        - tpu_zone: None
        - command_file: None
        - commands: None
```

GPUs: 2x NVIDIA RTX 3090

### Information

- [X] The official example scripts
- [X] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

I tried to get *fp16* training working. I did the following to get the example https://github.com/huggingface/accelerate/blob/main/examples/cv_example.py working:

Running 

1. `python  ./cv_example.py --data_dir /home/lennartv/Data/Oxford-Pets/` trains the network on one GPU (GPU RAM consumption roughly 3039 MB)
2. `accelerate launch  ./cv_example.py --data_dir /home/lennartv/Data/Oxford-Pets/` trains the network on both GPUs (GPU RAM consumption roughly 3070 MB on both)
3. `accelerate launch --fp16 ./cv_example.py --data_dir /home/lennartv/Data/Oxford-Pets/`, trains the network on both GPUs with **same** memory consumption as for 2)
4. `accelerate launch --mixed_precision fp16 ./cv_example.py --data_dir /home/lennartv/Data/Oxford-Pets/`, trains the network on both GPUs with **same** memory consumption as for 2)
5. `accelerate launch --mixed_precision no ./cv_example.py --data_dir /home/lennartv/Data/Oxford-Pets/` , trains the network on both GPUs with **same** memory consumption as for 2)

It seems that **fp16** training is either always on or never on. I can also replicate this behavior with my own project.

### Expected behavior

```Shell
FP16 should lead to less GPU memory consumption
```

**Comment by sgugger** [comment]
FP16 training is not there to reduce GPU memory but to make training faster. Especially at small batch size you might even get more memory consumption as a copy of the model is kept in both FP32 and FP16 during mixed precision training.

**Comment by pacman100** [comment]
Hello, building upon @sgugger, the only GPU memory reduction is that of activations of forward pass which are in `fp16` but as 2 copies of model weights are maintained (`fp16` and `fp32`) one usually doesn't see any memory usage drop. You can quickly check this using test here : `src/accelerate/test_utils/scripts/external_deps/test_peak_memory_usage.py` (changed the batch size to 32 in the script and used 1 A100 GPU) . Again, the main purpose of using `fp16` is faster training.

With Mixed Precision:
```
time accelerate launch --mixed_precision "fp16" src/accelerate/test_utils/scripts/external_deps/test_peak_memory_usage.py --model_name_or_path "roberta-large" --n_train 3200
```

Output: 
```
Memory before entering the train : 1355
Memory consumed at the end of the train (end-begin): 4111
Peak Memory consumed during the train (max-begin): 9046
Total Peak Memory consumed during the train (max): 10401

real	0m29,698s
user	0m30,152s
sys	0m10,117s
```

Without Mixed Precision:
```
time accelerate launch --mixed_precision "no" src/accelerate/test_utils/scripts/external_deps/test_peak_memory_usage.py --model_name_or_path "roberta-large" --n_train 3200
```
Output: 
```
Memory before entering the train : 1355
Memory consumed at the end of the train (end-begin): 4077
Peak Memory consumed during the train (max-begin): 10495
Total Peak Memory consumed during the train (max): 11850

real	0m55,307s
user	0m42,445s
sys	0m23,685s
```

So, you can see training is much faster `1.89X` (55/29, i.e., time for no mp/ time for fp16). Also, the `Total Peak Memory consumed during the train` is lower for `fp16` because of activations in lower precision but the overall memory is higher because of 2 copies of weights when using `fp16`.

**Comment by LvanderGoten** [comment]
okay, thank you very much for the clarification to both of you. Issue can be closed.
