### ISSUE TITLE
Feature request: distributed logger

### ISSUE THREAD

**Issue by xiabingquan** [huggingface/accelerate#969]
In single process training, we may use the original `logging.Logger` to record log information. However, in multi-process training(such as DDP), since there're multiple running processes, using `logging.Logger` will print log information much more verbosely.

I'm wondering whether `Accelerate` will support distributed logger as Colossal does in the future. Using the naive `Accelerator.print` is not flexible enough.

**Comment by sgugger** [comment]
cc @muellerzr

**Comment by muellerzr** [comment]
This already exists, check out the logger:

https://huggingface.co/docs/accelerate/package_reference/logging

**Comment by xiabingquan** [comment]
> This already exists, check out the logger:
> 
> https://huggingface.co/docs/accelerate/package_reference/logging

Got it. Thanks a lot. I'll close this issue.

**Comment by ZeyiLiao** [comment]
I want to add a handler and it says **'MultiProcessAdapter' object has no attribute 'addHandler'**
```
log_format = '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
logger = get_logger(__name__)
file_handler = logging.FileHandler("mylogs.log")
formatter = logging.Formatter(log_format)
file_handler.setFormatter(formatter)

# Don't forget to add the file handler
logger.addHandler(file_handler)
logger.info("I am a log from project")
```
