### ISSUE TITLE
ImportError: cannot import name 'validate_args' from 'megatron.arguments'

### ISSUE THREAD

**Issue by xiasanshi** [huggingface/accelerate#970]
### System Info

```Shell
- `Accelerate` version: 0.15.0
- Platform: Linux-4.9.0-141-custom-x86_64-with-debian-stretch-sid
- Python version: 3.7.10
- Numpy version: 1.21.6
- PyTorch version (GPU?): 1.12.1+cu102 (True)
- `Accelerate` default config:
	- compute_environment: LOCAL_MACHINE
	- distributed_type: MEGATRON_LM
	- mixed_precision: fp16
	- use_cpu: False
	- dynamo_backend: NO
	- num_processes: 4
	- machine_rank: 0
	- num_machines: 1
	- gpu_ids: None
	- main_process_ip: None
	- main_process_port: None
	- rdzv_backend: static
	- same_network: True
	- main_training_function: main
	- deepspeed_config: {}
	- fsdp_config: {}
	- megatron_lm_config: {'megatron_lm_gradient_clipping': 1.0, 'megatron_lm_pp_degree': 1, 'megatron_lm_recompute_activations': True, 'megatron_lm_sequence_parallelism': False, 'megatron_lm_tp_degree': 4, 'megatron_lm_use_distributed_optimizer': True}
	- downcast_bf16: no
	- tpu_name: None
	- tpu_zone: None
	- command_file: None
	- commands: None
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

error message:
import accelerate
  File "/data/xxx/venv/lib/python3.7/site-packages/accelerate/__init__.py", line 7, in <module>
    from .accelerator import Accelerator
  File "/data/xxx/venv/lib/python3.7/site-packages/accelerate/accelerator.py", line 27, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/data/xxx/venv/lib/python3.7/site-packages/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/data/xxx/venv/lib/python3.7/site-packages/accelerate/utils/__init__.py", line 103, in <module>
    from .megatron_lm import (
  File "/data/xxx/venv/lib/python3.7/site-packages/accelerate/utils/megatron_lm.py", line 50, in <module>
    from megatron.arguments import _add_data_args, _add_validation_args, parse_args, validate_args
ImportError: cannot import name 'validate_args' from 'megatron.arguments' (/data/xxx/venv/lib/python3.7/site-packages/megatron/arguments.py)

accelerate==0.15.0
megatron-lm==2.2.0

### Expected behavior

```Shell
ImportError: cannot import name 'validate_args' from 'megatron.arguments' (/data/xxx/venv/lib/python3.7/site-packages/megatron/arguments.py)
```

**Comment by sgugger** [comment]
cc @pacman100

**Comment by pacman100** [comment]
Hello @xiasanshi, you have to install the HF fork of Megatron-LM as mentioned in the `Pre-Requisites` section of the usage guide: https://huggingface.co/docs/accelerate/usage_guides/megatron_lm#prerequisites
