### ISSUE TITLE
device_map='auto' causes memory to not be freed with torch.cuda.empty_cache()

### ISSUE THREAD

**Issue by oobabooga** [huggingface/accelerate#973]
### System Info

If I load a model like this

```
model = AutoModelForCausalLM.from_pretrained("models/opt-13b", device_map='auto', load_in_8bit=True)
```

and then do

```
model = None
torch.cuda.empty_cache()
```

the VRAM is not freed. The only way I have found to release it is to kill the program and start it over. 

Freeing the memory like this works if the model is loaded the normal way with

```
model = AutoModelForCausalLM.from_pretrained("models/opt-13b", low_cpu_mem_usage=True, torch_dtype=torch.float16).cuda()
```
I have created this issue [on the transformers repository](https://github.com/huggingface/transformers/issues/21094) and was redirected here. @sgugger has suggested that the `load_in_8bit=True` part may be the culprit.

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

Code snippet is provided in the description above.

### Expected behavior

VRAM should be freed with `torch.cuda.empty_cache()`.

**Comment by gante** [comment]
I'm reopening this issue, as I've noticed that this problem still exists :) 

In a nutshell, as long as the device mapping is used, memory won't be freed by `torch.cuda.empty_cache()`. Here's a script for reproducibility

```py
from transformers import AutoModelForCausalLM
import torch

# this works okay, no memory allocated
model = AutoModelForCausalLM.from_pretrained("facebook/opt-1.3b")
del model
torch.cuda.empty_cache()
print(torch.cuda.memory_allocated(0))

# GPU memory > model memory requirements -> fails to clear out memory
model = AutoModelForCausalLM.from_pretrained(
    "facebook/opt-1.3b", device_map="auto", max_memory={0: "20GiB", "cpu": "50GiB"}
)
del model
torch.cuda.empty_cache()
print(torch.cuda.memory_allocated(0))

# GPU memory < model memory requirements -> fails to clear out memory
model = AutoModelForCausalLM.from_pretrained(
    "facebook/opt-1.3b", device_map="auto", max_memory={0: "1GiB", "cpu": "50GiB"}
)
del model
torch.cuda.empty_cache()
print(torch.cuda.memory_allocated(0))
```

cc @sgugger

**Comment by sgugger** [comment]
Does it make you go OOM? Last time I investigated this, the memory was not officially available, but if you tried to use the GPU it found it again.

**Comment by gante** [comment]
@sgugger If we loop over the initialization with device mapping, it is stable, but not the same -- it uses model allocated memory + memory that failed to clear up.

In the particular case I ran into this bug was when trying two large models in the same script, to compare their results -- the memory did not deallocate when deleting the first model, running into an exception (OOM) when loading the 2nd. Running the exact same code one model at a time throws no exceptions.

**Comment by sgugger** [comment]
I am investigating this. Note that as a first step, adding
```
import gc

gc.collect()
```
along with every `torch.cuda.empty_cache()` fixes the issue on my side.
