### ISSUE TITLE
[Discussion] `save_state` / `load_state` don't use custom saving/loading methods.

### ISSUE THREAD

**Issue by patrickvonplaten** [huggingface/accelerate#976]
`save_state` currently serializes models always as a simple `pytorch_model.bin` file, but no additional metadata is saved such as the model config.

Could it make sense to add functionality to `save_state` and `load_state` that would allow to customize saving & loading more? e.g. allow models to be loaded and saved with their unique `save_pretrained` and `from_pretrained(...)` methods? 

The problem we're currently experiencing in `diffusers` is that intermediate saved checkpoints are difficult to load & use for inference as explained here: https://github.com/huggingface/diffusers/issues/732#issuecomment-1383006354 and shown here: https://github.com/huggingface/diffusers/blob/main/docs/source/en/training/dreambooth.mdx#performing-inference-using-a-saved-checkpoint

During training we save both a `transformers` and `diffusers` model without a config simply under `"pytorch_model{i}.bin"` which then makes it quite hard / unintuitive to load those checkpoints afterward for inference (one has to run this code: https://github.com/huggingface/diffusers/blob/main/docs/source/en/training/dreambooth.mdx#performing-inference-using-a-saved-checkpoint).

Currently, I don't see a clean & easy solution though to add this to `save_state` so maybe it'd be best to just tell users to use directly the customized `save_pretrained(...)` method? We could possible add a mapping such as the following to `accelerate`: https://github.com/huggingface/diffusers/blob/b2ea8a84e9db71c207d28687722d241447bde81e/src/diffusers/pipelines/pipeline_utils.py#L70 to allow for customized loading and saving.

This way we could maybe get the best of both worlds: Leverage `load/save_state` for all saving/loading in the training script **and** create an easy to re-use folder structure when saving? 

Wdyt @sgugger ?

**Comment by patrickvonplaten** [comment]
Also cc @pcuenca FYI

**Comment by sgugger** [comment]
I have nothing against having a mapping like the one you mention that would use `save_pretrained`/`from_pretrained` for diffusers/transformers models in the `save_state` method (and we can support third-party special functions the same way if users want it). It looks like the easiest way to get the best of both worlds.

**Comment by pacman100** [comment]
I've started to look into this. The main issue is that saving checkpoints when using DeepSpeed/FSDP/Megatron-LM, `from_pretrained` won't work. Also, just to make sure that we are aligned on the purpose of `save_state` and `load_state` is for resuming training. At the end of training one can use `from_pretrained` to save the whole model with unet and clip and their configs for inference, right?

**Comment by sgugger** [comment]
This is an other feature request entirely. If you have very specific needs like this, maybe you need to not rely on `save_state`/`load_state` from Accelerate but deal with the checkpointing with a diffusers-specific method.

**Comment by patrickvonplaten** [comment]
For `diffusers` they go hand-in-hand . It doesn't help to just add a dict of save/load_pretrained without being able to save multiple models in different subfolders (otherwise things would overwrite each other).

So in short, if you can think of a solution to create folder names and save models in separate folders that would be great, if it's too much totally fine - we leave things as they are or think about some abstraction on top of it :-) 

When opening this feature request I thought it's maybe too much of an edge case for accelerate - it's just that every example training in diffusers (dreambooth, textual-inversion, text-to-image) needs this functionality.

**Comment by sgugger** [comment]
That seems more feasible yes! I don't want to add any complexity to `accelerator.prepare`, but we can definitely have a new method which is only used for this kind of use-cases. If hooks manage to get the job down, I'm okay with that, or we can just have something like `set_checkpoint_structure`.

**Comment by patrickvonplaten** [comment]
Great! Yes I think that's cleaner as well :-) Then we also don't to add a library saving / loading mapping - will open a first draft PR :-)

**Comment by sgugger** [comment]
This has been fixed by #991
