### ISSUE TITLE
Accelerate/Deepspeed not using BFloat16 Optimizer

### ISSUE THREAD

**Issue by zanussbaum** [huggingface/accelerate#997]
### System Info

```Shell
- `Accelerate` version: 0.15.0
- Platform: Linux-5.15.0-1023-aws-x86_64-with-glibc2.29
- Python version: 3.8.10
- Numpy version: 1.24.1
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: NO
        - mixed_precision: no
        - use_cpu: False
        - dynamo_backend: NO
        - num_processes: 1
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: all
        - main_process_ip: None
        - main_process_port: None
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - deepspeed_config: {}
        - fsdp_config: {}
        - megatron_lm_config: {}
        - downcast_bf16: no
        - tpu_name: None
        - tpu_zone: None
        - command_file: None
        - commands: None
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

I launch my script with the following command

`accelerate launch --deepspeed_multinode_launcher standard --deepspeed_hostfile hostnames --mixed_precision=bf16 --use_deepspeed --zero_stage=2 --offload_param_device=cpu --offload_optimizer_device=cpu --gradient_accumulation_steps=1 train.py`

but recently when using `deepspeed==0.8.0`, I've faced an overflow error after many steps when using `bfloat16` where I get the following error
```
RuntimeError: value cannot be converted to type float without overflow
```
when calling `accelerator.backward`. This happens after about 50k steps

However, when I checked the logs, I see that we are supposed to be using `bfloat16`
```
[2023-01-22 04:26:55,308] [INFO] [config.py:997:print_user_config]   json = {
    "train_batch_size": 160,
    "train_micro_batch_size_per_gpu": 10,
    "gradient_accumulation_steps": 1,
    "zero_optimization": {
        "stage": 2,
        "offload_optimizer": {
            "device": "cpu"
        },
        "offload_param": {
            "device": "cpu"
        },
        "stage3_gather_16bit_weights_on_model_save": false
    },
    "steps_per_print": inf,
    "bf16": {
        "enabled": true
    },
    "zero_allow_untested_optimizer": true
}
```
But the optimizer seems to be created using `fp16`

```
[2023-01-22 04:26:50,701] [INFO] [logging.py:68:log_dist] [Rank 0] Creating fp16 ZeRO stage 2 optimizer
```
I believe the corresponding line [can be found here](https://github.dev/microsoft/DeepSpeed/blob/867da307d047c8122454ac8b0880cd23d38949e7/deepspeed/runtime/engine.py#L1529-L1530) when I'd expect a `bfloat16` optimizer to be created. Is this expected? I assume this may be an issue on the DeepSpeed side so happy to open an issue there as well if needed. 

### Expected behavior

Shouldn't we create a `bfloat16` optimizer instead of `fp16`? I am just using `torch.optim.Adam`

**Comment by zanussbaum** [comment]
Ah seems like this is related: https://github.com/microsoft/DeepSpeed/issues/2734

**Comment by reciprocated** [comment]
I think this is related: https://github.com/microsoft/DeepSpeed/pull/2732
